### ISSUE TITLE
[IOS] approved event always triggered when store.refresh() called after buy auto renewable product

### ISSUE THREAD

**Issue by tpid-febra** [j3k0/cordova-plugin-purchase#1002]
Hello, thank you for the plugin. I have question, why "approved" event always triggered when store.refresh() called after buy auto renewable product (in sandbox environment)?
I have product with type: Non-renewing subscription & Consumable, it works fine when buy the product and "approved" event not triggered after store.refresh() called.

Environment :
	- Mojave v 10.14.5
	- XCode v 10.3
	- Cordova 9.0.0
	- Device: iPhone 7
	- cordova-plugin-purchase v 10.0.1.

Here is my code:

	store.register({
	    id: "ios_product_id",
	    alias: "alias",
	    type: store.PAID_SUBSCRIPTION
	});

	store.when("id_product_ios")
	    .approved((product) => {
	        const url = "xxxxxxx";
	        store.validator = url;
	        product.verify();
	    })
	    .cancelled((product) => {
	        product.finish();
	    })
	    .verified((product) => {
	        product.finish();
	    })

	store.refresh();

### Expected behavior
When I open product page (and call store.refresh()) "approved" event not triggered except the subscription is expired: every 5 minutes after last subscription (I set the product 1 month in app store)

### Observed behavior
Whenever I open product page (and call store.refresh()) "approved" event always triggered and called product.verify()

### Steps to reproduce
Open product page > buy auto-renewable product > success > go to another page > go back to product page

Please help me

**Comment by meiichin** [comment]
wait to answer too, good luck ^^

**Comment by j3k0** [comment]
Because you shouldn't call "refresh()" when opening the product page, only at app startup.

Apple requires that your app is ready to handle store events from startup, because people can make purchases on different devices and even from the AppStore. Register your handlers only once, when the app starts.

Refresh performs a full refresh cycle. It'll send all `owned` products to the `approved` state and check their status again (cancelled, renewed, expired, refunded, ...).

The latest version of the plugin has a new method called `store.update()` that only refreshes the price of the products. That's the one to call when entering the product page.

**Comment by dminkovsky** [comment]
So basically, with an auto-renewable, on every `refresh()` it will go from "valid" to "approved", and at that point you have to `verify()` or `finish()`? Is that correct? If so, calling `finish()` is idempotent for a product that is not currently being purchased? 

For example: say you bought an auto-renewable. You went through the whole process: valid -> approved -> verify -> finish. Then, a few minutes later, you close/open the app again. The product goes through this whole process again, but the user will not be charged? What is the point of ` `finish()` then? Just to put it into "owned" state? And "owned"—that is purely a construct of this plugin, right? Apple has no such state?

**Comment by j3k0** [comment]
Yes, `.finish()` is a construct of this plugin. It's a good thing to have in place though: it tells the plugin that purchase/transaction has been processed by the app and resolves it. On Android, it means acknowledging a transaction if it isn't already (https://developer.android.com/google/play/billing/billing_library_releases_notes#2_0_acknowledge). On iOS it means finishing all pending transactions in the queue for the product (see `https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction?language=objc`)

**Comment by dminkovsky** [comment]
Great, thanks for confirming. That was my understanding based on:

https://github.com/j3k0/cordova-plugin-purchase/blob/afdba1449909d97604e67d1cee90ef94d87253ba/src/js/platforms/ios-adapter.js#L67-L90

Thanks a lot for this plugin.
