### ISSUE TITLE
[IOS] Rejected App - "Sign-In Required" prompt after successful purchase

### ISSUE THREAD

**Issue by merri-ment** [j3k0/cordova-plugin-purchase#1004]
### system info
 
```
iPadOS 13.3.1
Cordova 9.0.0
Device: iPad (7th generation)
Plugin Version: 10.0.1
```

### Expected behavior
Purchasing a non-consumable item should be a two step process;
1.  "Confirm Your In-App Purchase" form 
2.  "Your all set" popup

### Observed behavior
The user is asked to fill in a "Sign-In Required" form after successful purchase

### Steps to reproduce
Upon selecting "Purchase";
1. "Confirm Your In-App Purchase" form - User enters their password 
2. "Your all set" popup - Selects ok
3. "Sign-In Required" form - User is asked to fill in their password
 
--------

The App has been rejected by the Apple Testers as a result of the 2nd "Sign-In Required" form.
I thought initially after reading the Apple Testers feedback that i may have called "store.order(productId)" twice, but this is not the case.

> Guideline 2.1 - Performance - App Completeness
> 
> 
> We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 13.3.1 on Wi-Fi.
> 
> - After we purchased the IAP the app still asks us to buy the IAP again.
> 
> Next Steps
> 
> When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.

--------

Thanks in advance,
Cam

**Comment by merri-ment** [comment]
I managed to pass the Apple Submission by updating the messaging on the Purchase Button. based on the purchase state. "Purchase Item" > "Processing" > "Complete".

**Comment by Seanmclem** [comment]
@merri-ment did you ever find out why this is happening?
