### ISSUE TITLE
[Android] Register multiple products

### ISSUE THREAD

**Issue by ragunathans** [j3k0/cordova-plugin-purchase#1005]
Hi,

I want to display multiple products from the play store and the users will select any one of them and they will purchase the selected product.

Here my question, do I need to register the handlers multiple time for every product?

Also, .ready() event not fired.

How to get the product price and display in the HTML view?

Thanks in advance

**Comment by j3k0** [comment]
Hello, all those questions are answered in the documentation. Good resource to start: https://purchase.cordova.fovea.cc/
