### ISSUE TITLE
Adding Android billing key with Ionic capacitor

### ISSUE THREAD

**Issue by topcatcreatives** [j3k0/cordova-plugin-purchase#1010]
Hi there,
Do you know the best/recommended approach to adding the billing key for Android when using Ionic Capacitor. It is my understanding that while using Capacitor I cannot not use this command:
cordova plugin add cordova-plugin-purchase --variable BILLING_KEY="MIIB...AQAB"
Instead
npm install followed by npx cap sync
which bypasses the step to add billing key
I have this plugin working for iOS and its excellent. Just this one step for the billing key is something I need to get it working for Android.

Any help would be appreciated, Many thanks.

**Comment by dchedufa** [comment]
Hi! I have tried adding the information in the package.json file in my capacitor project.
cordova": {
    "plugins": {
      "cordova-plugin-purchase": {
        "BILLING_KEY": "<key>"
      }
    },

Apparently it's working, though im trying to trace transactions on the fovea billing page using it as receipt validator but with no success.

**Comment by topcatcreatives** [comment]
@dchedufa thanks for the suggestion. I will try this approach. Cheers.

**Comment by j3k0** [comment]
The latest version of the plugin doesn't use the billing key anymore, as the best practice is to do server-side validation. Documentation has to be updated.

**Comment by topcatcreatives** [comment]
Ok cool. thanks.

**Comment by vycoder** [comment]
> The latest version of the plugin doesn't use the billing key anymore, as the best practice is to do server-side validation. Documentation has to be updated.

Hi @j3k0, I'm sorry but just to clarify, does it mean that we no longer need to add the BILLING key and the plugin already handles it?

**Comment by Diex** [comment]
https://github.com/j3k0/cordova-plugin-purchase/issues/1010#issuecomment-605834386 
good to know @j3k0 ... anyway, I think you need to add it. otherwise you won't be able to add any product/subscription to google play console. am I right?
thx !

**Comment by Diex** [comment]
indeed... after adding the cordova-plugin-purchase with the android KEY_BILLING variable I was granted to create subscriptions. (thinking out loud: without the billing key var, would it be working?)

regards !
dx

**Comment by mley** [comment]
If that's really the case, it would be great if you keep the documentation up-to-date. See https://purchase.cordova.fovea.cc/use-cases/subscription-android#4.-install-cordova-purchase-plugin
