### ISSUE TITLE
Tracking first initial purchase

### ISSUE THREAD

**Issue by jonasmeier1212** [j3k0/cordova-plugin-purchase#1011]
Is there any event or possibility to track the first purchase of any product.
Because the events like _finished_ or _owned_ get fired every time store.refresh() is called even if the product isn't purchased before, but the subscription still valid.
The background of this is, that I have to track every purchase in a custom system and for that I need a location in code where I can fire this _in_app_purchase_ event.
If I put this somewhere in the finished or owned event handler I get duplicated events...

**Comment by weswarnerofx** [comment]
There maybe a more robust solution, but could you set a local state when user invokes store.order(), and then when the owned event is triggered and state.orderInvoked = true, you know there has been a purchase. Cheers

**Comment by topcatcreatives** [comment]
There maybe a more robust solution, but could you set a local state when user invokes store.order(), and then when the owned event is triggered and state.orderInvoked = true, you know there has been a purchase. Cheers

**Comment by j3k0** [comment]
You can setup some "once" listeners before making the purchase.

```js
const onOwned = function() {
   // ...do your stuff
   cleanup();
}
const onError = function() {
   // ...do your stuff
   cleanup();
}
const cleanup = function() {
  store.off(onOwned)
  store.off(onError)
}
store.once("my_product_id", "owned", onOwned)
store.once("my_product_id", "error", onError)
store.order("my_product_id");
```
