### ISSUE TITLE
[IOS] Buy confirmation alert not rendered and user charged

### ISSUE THREAD

**Issue by osama-klabs** [j3k0/cordova-plugin-purchase#1014]
One of user claims that he charged two times without asking default confirmation alert when he enter credential. He sent the proved (bill). is that possible? Please guide me

we are using non-renewing subscription and in finish event we call server API to save the buy state of product.
I noticed that in production sometimes api call multiple times (in other words finish event fired multiple times) and sometimes finish event not fire.

```"@ionic-native/in-app-purchase-2": "^5.18.0"```

### Ionic Info
```Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.8.1
   native-run (update available: 0.3.0)   : 0.2.7

System:

   Android SDK Tools : 26.1.1 (/Users/ahmed/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.10.0 (/usr/local/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by j3k0** [comment]
It's only possible to create 2 orders if you call `store.order()` twice. Also, I think an order cannot be created if there's already a purchase in progress. Can you share some log and code?
