### ISSUE TITLE
[ANDROID] Store refresh trigger is not working

### ISSUE THREAD

**Issue by ermite1408** [j3k0/cordova-plugin-purchase#1015]
### System info

```
Cordova 9.0.1
Device: Android 8.0
Plugin Version: 10.0.1
```

After app loading I register store items and run store.refresh();
I create a trigger so that after the refresh run check item state, but trigger never fire:

```
store.register(item);
store.trigger('refreshed', this.onStoreRefreshed);
store.refresh();
```

I replaced trigger to when/once, but it doesn’t work correctly

```
function onStoreRefreshed() {
  const item = store.get('exampleItem');
  console.log(store.state) // show "registered"
  setTimeout(() => console.log(store.state), 5000); // show "verify" after 5 seconds
}

store.register(item);
store.once('refreshed', onStoreRefreshed);
store.refresh();
```

I found a temporary solution:

```
store.register(item);
setTimeout(onStoreRefreshed, 5000);
store.refresh();
```
But I'd better do it right way. Please advise how to achieve this. Thanks

**Comment by j3k0** [comment]
Hello,

You are not supposed to use `store.trigger`, it's an internal method called by the plugin itself. You should call `store.once("refreshed", ...)` (but it's only called right away when someone requests a refresh, not when the refresh is complete)

Anyway, can I ask why you want to wait for refresh?

**Comment by ermite1408** [comment]
Sorry for delay

If the payment did not go right away and the user closed the app, the next entry app I want to check the status of the items and give item if it was paid but was not received
