### ISSUE TITLE
[Android] Google Cancelling auto-renewing subscriptions

### ISSUE THREAD

**Issue by nvahalik** [j3k0/cordova-plugin-purchase#1016]
### system info

Using Cordova 9 with latest master of module.

### Expected behavior

Google subscriptions should not be cancelled after 3 days.

### Observed behavior

Google is cancelling subscriptions after 3 days.

### Steps to reproduce

Purchase a subscription on a Google device.

I am using the Fovea validator and also calling `product.finish()` within `verified()`.

**Comment by j3k0** [comment]
Are you definitely sure `product.finish()` is called? Could it be that some code triggers an exception before this is executed (so it's not executed).

`product.finish()` is almost a direct call to the internal `acknowledgePurchase()` method of the google play library. So far, we didn't hear reports of the same issue with anyone else, so I tend to go with "something in your code" (no offance). Please reopen with more data to show me wrong (like logs showing the full purchase flow of a user up to the call to finish).

**Comment by nvahalik** [comment]
OK. Something strange is happening, but at this point, I'm going to point at Google and say that something appears to be wrong here.
