### ISSUE TITLE
[Android] Manually place billing key when using capacitor

### ISSUE THREAD

**Issue by duy-a** [j3k0/cordova-plugin-purchase#1017]
### Issue

When installing the plugin using the Cordova you can just run the cordova command with a --variable indicate the billing key. However, when using the capacitor all the variables/ hooks have to be added manually.

I can't figure out for the past 3 days where and what to place in the android project in order to include the billing key. (basically manually recreate the steps done when using a --variable command)

A help is much appreciated

### Steps to reproduce
Follow the ionic native instructions for the capacitor
1. npm install cc.fovea.cordova.purchase
2. npm install @ionic-native/in-app-purchase-2
3. ionic cap sync

**Comment by dminkovsky** [comment]
https://github.com/j3k0/cordova-plugin-purchase/issues/1010#issuecomment-605834386
