### ISSUE TITLE
[IOS] Cannot recover from failed consumable purchase

### ISSUE THREAD

**Issue by steveetm** [j3k0/cordova-plugin-purchase#1020]
### system info

```
OSX Sierra 10.12.04
Cordova 9.0.0
Device: iPhone iOS 13.3.1
Plugin Version: 10.0.1
```

### Steps to reproduce
```
store.register({id:'myconsumable', type: store.CONSUMABLE});
store.refresh();
store.when('myconsumable')
.approved(p=>{p.verify()});
.verified(p=>{this.functionWhichWasBuggyAndThrew(); p.finish())}
store.order('myconsumable');
```
Run this, fix that buggy function and restart the app.

### Expected behavior
After I fixed `verified` callback, it should finish the consumable.

### Observed behavior
If I ever fails to call `p.finish()` for a consumable, that consumable won't pass `initiated` state.
I see the popup saying 'This In-App Purchase has aready been bough. It will be restored for free'
And no events fired after that, I can not register this consumable nor I finish it.
`__cc_fovea_store_ios_owned_myconsumable` is `0` in localStorage.

**Comment by gbbarroso** [comment]
p.verify is not being executed, it's missing a `()`

**Comment by steveetm** [comment]
It was just a typo in the example.
