### ISSUE TITLE
[IOS] Testing auto-renewable subscriptions in sandbox

### ISSUE THREAD

**Issue by veronicatc** [j3k0/cordova-plugin-purchase#1022]
I am testing in sandbox with auto renewable subscription.

I first used one sandbox test user, and this user has a purchase and each time the app starts for this user, the app validates this same receipt with all its renewals. This seems to be the correct behavior, as far as I understood. 

I wanted to test from scratch again so I created another test user, and on the device, logged out from previous sandbox account, and logged in with the new one. At the Sandbox Account at bottom of Settings > iTunes & App Store. This device has iOS 13.

When I go back into the app, it still gets the receipt that belongs to the previous sandbox id when I do the initial store.refresh(), and validates it. How can this be cleared so that the new fresh sandbox test user doesn't get the old transactions which belonged to the other id? I am new to In App Purchases and I must be missing some step, but I thought that the only transactions that would show would be those for currently logged in sandbox account.

Thanks for any help!

**Comment by Lindsay-Needs-Sleep** [comment]
I think you can try re-installing the app.  (Might need to actually uninstall the app first to wipe it’s memory.)

Not totally sure if that will work, or if it is the proper way...

**Comment by veronicatc** [comment]
I ended up uninstalling and reinstalling as suggested and that helped. Thanks.
