### ISSUE TITLE
[IOS] Product information not updated immediately after purchase. Change only visible after click or re-visiting the page.

### ISSUE THREAD

**Issue by kheber92** [j3k0/cordova-plugin-purchase#1023]
Hi,

I have a page in my Ionic application where I'm displaying all products available for InApp Purchase. When a product is purchased via `store.order()` method, the product information (especially the `owned` product state) is not updated immediately. 

The data is refreshed only if I
- click on any random button (doesn't have to have a function)
- leave the current page (navigate to a different one) and come back

This is problematic because I have to indicate wether the user has bought a product or not (by disabling the purchase button for example), and this is currently only visible after clicking another button or navigating to a different page or re-starting the application.

# system info
Plugin: cordova-plugin-purchase 10.1.0
Framework: Ionic 5
Device: iPad Pro with iOS 13

### Expected behavior
Product state (and other information) gets updated immediately after successful purchase.

### Observed behavior
Product state (and other information) gets updated only after clicking a random button or leaving the page after successful purchase.

### Steps to reproduce
I'm registering all product IDs and the handlers for purchase (like `registered`, `owned`, `approved`, ...) in my component already.
In the following pages I'm using them.

**page.ts (simplified version)** 

```
const inAppProductID = 'my_product_id';

ngOnInit() {
    this.getIapProduct();
}

getIapProduct() {
    this.store.ready(() => {
       this.iapProduct = this.store.get(inAppProductID);
       this.title = this.iapProduct.title;
       this.price = this.iapProduct.price;
       this.owned = this.iapProduct.owned;
    });
  }

purchase(inAppProductID) {
    try {
      let product = this.store.get(inAppProductID);
      this.store.order(inAppProductID).then((p) => {
        console.log('Purchase Succesful' + JSON.stringify(p));
      }).catch((e) => {
        console.log('Error Ordering From Store' + e);
      });
    } catch (err) {
      console.log('Error Ordering ' + JSON.stringify(err));
    }
    this.store.refresh();
  }
```

**page.html (simplified version)** 
```
<div>
    <p>{{title}}</p>
    <button *ngIf="owned == false" (click)="purchase('my_product_id')">{{price}}</button>
    <button *ngIf="owned == true" disabled>Already bought</button>
  </div>
```

Is this a bug or am I missing something?
Thank you in advance!

**Comment by rastafan** [comment]
Hi,

i don't know if this will be of any help, but according to the code, the "setOwned" method (which is, as you can guess, what sets the owned status to true or false) on iOS is called when:

-The "owned" event is triggered (it is set to true)
-The "finished" event is triggered (be it true or false)
-The "expired" event is triggered (it is set to false)

Did you try calling the "finished" method after the purchase was completed? Check the docs [here](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#-purchasing) for more info.

@j3k0 can you please confirm the "finished" method should always be called, be it after a successful or failed validation, or immediatly after an order call if no validation is involved? thank you.

**Comment by biesbjerg** [comment]
This looks like it’s an Angular change detection issue. Try putting some console.logs in your code and I’ll bet you’ll see it works as expected. 
Look up how to force change detection to run (I’m on mobile so it’s a bit difficult to help you more)

**Comment by j3k0** [comment]
> Can you please confirm the "finished" method should always be called, be it after a successful or failed validation.

Depends on the reason for the failure, if your validator could not validate because of an internal error you don't want to finalize the transaction. If you've not been able to deliver the purchase, don't finish either. Only finish when you're done processing the transaction.

**Comment by j3k0** [comment]
@kheber92 I would expect your code to define a listener to the `updated` event.

```js
store.when("product").updated(function() {
  refreshPage();
})
```

I've got some piece of code for an unknown version of angular:

```js
        function sync() {
          $scope.ready = store.ready();
          $scope.product = Object.assign({}, store.get("my_product_id"));
        }
        const dsync = window.debounce(sync, 50);

        $scope.$on("$ionicView.beforeEnter", function () {
          dsync();
          store.when("my_product_id").updated(dsync);
        });

        $scope.$on("$ionicView.beforeLeave", function () {
          store.off(dsync);
        });
```
(https://gist.github.com/j3k0/0c0c9217c63944d11f7b1d8a0ec43821)

I'm not sure if it's still the way to do that in angular nowadays (@biesbjerg ?)

**Comment by rastafan** [comment]
> > Can you please confirm the "finished" method should always be called, be it after a successful or failed validation.
> 
> Depends on the reason for the failure, if your validator could not validate because of an internal error you don't want to finalize the transaction. If you've not been able to deliver the purchase, don't finish either. Only finish when you're done processing the transaction.

Would and expired subscription (triggering the expired event) be considered as a finished process? Or should we call it only with successful verification of valid and active subscriptions?

i'm sorry for bothering you but i feel like i'm missing something and i'm trying to figure it out.

**Comment by chuchuva** [comment]
Calling detectChanges() fixed this issue for me:

```
import { ChangeDetectorRef } from '@angular/core';
// ...
  constructor(
    private changeDetector: ChangeDetectorRef,
    // ...
  ) { }

// ...
    let self = this;
    this.store.when("subscription").cancelled(() => {
      console.log('Purchase was cancelled');
      // ...
      self.changeDetector.detectChanges();
    });
```
