### ISSUE TITLE
APPLE/iOS- Not getting receipt after purchase from apple inapp auto-renewable subscriptions

### ISSUE THREAD

**Issue by mineexcellence** [j3k0/cordova-plugin-purchase#1025]
Hi,

I am purchasing the product I am not getting any receipt in sandbox testing for iOS.

Please refer attached screenshot.
![image_2020_04_27T09_12_58_396Z](https://user-images.githubusercontent.com/58325526/80355503-d0a1f100-8895-11ea-8053-e6b93c613879.png)

I am getting

transaction:{
id: "XXXXXXXX",
"original_transaction_id":"XXXXXX",
"type":"ios-appstore"
}

I couldnt see any receipt here

system info

Plugin: cc.fovea.cordova.purchase 8.1.1
Framework: Ionic 4
Device: iPad Pro with iOS 13

### Expected behavior

As  per documentation link(https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#transactions) of repo, It should return receipt data i.e appStore receipt along with transaction data 

### Observed behavior
I am not getting any receipt for sandbox purchase

**Comment by Seanmclem** [comment]
@mineexcellence would this be a show-stopper? Am I not going to be able to use this for subscriptions on iOS because of this issue?

**Comment by j3k0** [comment]
In plugin version `10.1` and below, the receipt was available only if you have setup a receipt validator (`store.validator`) and after you call `verify()`. Starting version `10.2`, the receipt is available in the `approved()` call in all cases. If you're starting fresh, I recommend setting up a validator. It has a number of advantages.

https://billing.fovea.cc provides a receipt validator that works out of the box with this plugin. With it in place subscriptions are supported perfectly on all platforms. It's free, up to 100 subscribers.

**Comment by Seanmclem** [comment]
@j3k0 thanks, I have setup https://billing.fovea.cc now. I noticed in [this doc](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/ios.md) it says when testing auto-renewals, that we will get 21006 error after 25 minutes and need to create a new user in iTunes connect. Is that elaborated on anywhere? I feel like I saw a doc about it once but can't find much now on sandbox testing

**Comment by j3k0** [comment]
This doc is outdated, the behavior has changed and you should be able to re-subscribe your test users (and get the 5 auto-renewal) in sandbox
