### ISSUE TITLE
[common] update version of ionic-native plugin

### ISSUE THREAD

**Issue by ab-kily** [j3k0/cordova-plugin-purchase#1029]
Hello, J3k0! 

Thanks for your great plugin! I'm using it with your billing (billing.fovea.cc) and it works like a charm!

My app is written using Ionic 4 framework, and it seems the ionic-native wrapper for your plugin has outdated API. Do you have plans to update ionic-native API for your plugin?

**Comment by oofaish** [comment]
see if this helps? https://github.com/j3k0/cordova-plugin-purchase/issues/987
