### ISSUE TITLE
App stops when calling store.refresh()

### ISSUE THREAD

**Issue by ozexpert** [j3k0/cordova-plugin-purchase#103]
Was working just fine with 1.9.0-beta1
But with current version, I just dies when calling store.refresh()

**Comment by agamemnus** [comment]
drbeermann: right... same problems here.

**Comment by macfam** [comment]
I am still having these issues as well.

**Comment by jambots** [comment]
I am also having the crash on store.refresh() after a test purchase has been made. Is there a way to determine using the console that my billing key has made it to the plugin? 
In PhoneGap Build I am adding the parameter like so: 
&lt;gap:plugin name="cc.fovea.cordova.purchase" source="plugins.cordova.io"&gt;
  &lt;param name="BILLING_KEY" value="MIIB...AQAB" /&gt;
&lt;/gap:plugin&gt;

**Comment by CodeHunger** [comment]
I've found a solution @ #123

**Comment by vtntimo** [comment]
Just repeating what's being said, but this did work for me:

Edit file platforms/android/res/values/billing_key_param.xml:

<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="billing_key_param">$BILLING_KEY</string>
</resources>

to:

<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="billing_key_param">$BILLING_KEY</string>
    <string name="billing_key_param">  MY BILLING KEY HERE  </string>
</resources>

Works with Cordova 3.6 + Crosswalk. This is merely a hack, which seems to be not working on some setups. I am guessing that Cordova has a bug with optional variable setting at plugin install. Maybe a possible fix would be to add the line "<preference name="BILLING_KEY" />" to plugin.xml to make it mandatory? I am wondering does this break the plugin for those wanting to use only iOS in-app billing though..

**Comment by rahmadid** [comment]
Hi, for those of you who experience crash after purchase related to billing key, please install the plugin from the git address. Don't install from plugin registry, it seems that the registry hasn't been updated with the latest code. It just works, I don't have to do any manual code changes. Hope that helps.

**Comment by speige** [comment]
@rahmadid can you post your working <gap:plugin> tag (without an obfuscated billing_key, of course), so we can see how it should be done with PhoneGapBuild? I'm not sure what you mean by "use the git address". Thanks.

**Comment by rahmadid** [comment]
@speige Sorry for the misunderstanding, my solution above is only for phonegap/cordova, not phonegap build. Thanks.

**Comment by Alphatiger** [comment]
changing the value in the android.json is working for me

**Comment by cherniv** [comment]
@vtntimo 's solution worked for me! Thanks, Timo

**Comment by sarahsga** [comment]
#123 fixed it for me. @flexed 's answer worked for me perfectly! I have answered it too in hope that it might help.
