### ISSUE TITLE
[Android] second "refresh" doesn't trigger any events

### ISSUE THREAD

**Issue by svzi** [j3k0/cordova-plugin-purchase#1033]
When I call `store.refresh()` a second time, e.g. with a "Restore Purchases" button, after the store was correctly initialized once, no events are getting triggered for users, who haven't purchased anything before (or doesn't have a valid/active subscription anymore for example). But it works like expected, when there is a purchase to restore.

I've registered one update trigger (`store.when().updated(() => { /* do something */ });`, but it get only called after the very first `store.refresh()`. I don't remove the event trigger anywhere in the code (no `store.off(...)`). 

### system info

```
Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 29 other plugins)

Utility:

   cordova-res (update available: 0.13.1) : 0.8.1
   native-run (update available: 1.0.0)   : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.17.0 (/Users/svzi/.n/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504

Plugin version: 10.1.1
```

### Expected behavior
The `store.when().updated()` trigger should be called every time I call `store.refresh()`, no matter if the user has already purchased something (that is still valid) or not.

**Comment by j3k0** [comment]
This is a follow-up of #1026 

`store.when().updated()` is only triggered when a change happened to one of the product. So this shouldn't be triggered when nothing changed (like a restore in the case the user never purchased anything).

So yeah, my solution to your other issue is lacking in this case. Instead of polishing my solution, to this problem most have to solve, I though it'd be better to have a way to achieve it more simply.

So, PR #1035 (still untested).

**Comment by alexp25** [comment]
I do not understand this solution, as I have encountered this problem as well on Android, while on iOS it works  #1036 . It now seems impossible to use the same logic on both platforms, as expected with using ```when()``` and declaring the event handlers only once. How should the list of products be refreshed, should I hold a list of products locally after the first loading?

**Comment by stolzda** [comment]
> I do not understand this solution, as I have encountered this problem as well on Android, while on iOS it works #1036 . It now seems impossible to use the same logic on both platforms, as expected with using `when()` and declaring the event handlers only once. How should the list of products be refreshed, should I hold a list of products locally after the first loading?

I had the same problem - and this is exactly what I did, I'm storing the products locally after the first refresh. I don't think it is ideal but it works for me - I didn't find a different way to allow the users to navigate to a shop page and then back, and later to the shop page again.
