### ISSUE TITLE
[IOS] crashing when loading product details

### ISSUE THREAD

**Issue by alexp25** [j3k0/cordova-plugin-purchase#1036]
# [IOS] crashing when loading product details

### system info

macOS Catalina 10.15.3
Framework: Ionic 4 Cordova
Device: iPhone iOS 13.3.1 
Plugin Version: 10.0.1

### Expected behavior

The product details should be loaded and the app should not crash.

### Observed behavior

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SKProduct localizedPrice]: unrecognized selector sent to instance 0x28191ca40'`

When I try to test a purchase on iOS, the app crashes with above message. The app is also unable to retrieve product details from the store. I mention that the app is not yet released and it's currently in TestFlight, and the apple paid apps agreement has been signed (was not even working before, returning null/invalid products).

### Steps to reproduce

let productId = "coin_pack_1";
let iapOptions: IAPProductOptions = {
    id: productId,
    alias: productId,
    type: this.store.CONSUMABLE
};

this.store.register(iapOptions);
this.store.verbosity = this.store.DEBUG;

let product: IAPProduct = this.store.get(productId);

// register handlers
this.store.once(productId).approved((data: IAPProduct) => {
    // Fired when a purchase has been approved by the store
    console.log("approved, ", data);
    product.finish();
    resolve(true);
});
this.store.refresh();

**Comment by j3k0** [comment]
Are you loading products at startup? Under normal circumstances I would not expect this "once" call but a "when". Then you should call .finish() on the product passed as a parameter to this function.

Do you have some logs to share? Ty

**Comment by alexp25** [comment]
Products are loaded when showing the product list in the app (not at startup) => This also happens when I load the product details (as App Store actually requires to load product details from their servers) like this:
```this.store.get(productId);```
I also call ```this.store.refresh()``` after registering all handlers.
Also this.store is called via ionic wrapper, though that shouldn't be an issue. 
I couldn't find a way to use ```when()``` as it didn't allow for clearing the handlers properly, so I used ```once()```. I mention that there are no problems on Android with the same code. 

I attach the full logs:

```
InAppPurchase[objc]: load: Product request started
2020-05-18 15:24:47.151855+0300 Leplace World[459:76686] InAppPurchase[objc]: BatchProductsRequestDelegate.productsRequest:didReceiveResponse:
2020-05-18 15:24:47.152013+0300 Leplace World[459:76686] InAppPurchase[objc]: BatchProductsRequestDelegate.productsRequest:didReceiveResponse: Has 1 validProducts
2020-05-18 15:24:47.153027+0300 Leplace World[459:76686] InAppPurchase[objc]: BatchProductsRequestDelegate.productsRequest:didReceiveResponse:  - coin_pack_2: Coin Pack Level 2
2020-05-18 15:24:47.153135+0300 Leplace World[459:76686] -[SKProduct localizedPrice]: unrecognized selector sent to instance 0x282f0ee90
2020-05-18 15:24:47.165202+0300 Leplace World[459:76709] CRASH: -[SKProduct localizedPrice]: unrecognized selector sent to instance 0x282f0ee90 Stack Trace: (
	0   CoreFoundation                      0x00000001a56f8604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
	1   libobjc.A.dylib                     0x00000001a541abcc objc_exception_throw + 56
	2   CoreFoundation                      0x00000001a55fcea8 409609CD-8410-38E1-BA5D-BDED609D2018 + 192168
	3   CoreFoundation                      0x00000001a56fc694 409609CD-8410-38E1-BA5D-BDED609D2018 + 1238676
	4   CoreFoundation                      0x00000001a56fe5bc _CF_forwarding_prep_0 + 92
	5   Leplace World                       0x000000010461d7a8 -[BatchProductsRequestDelegate productsRequest:didReceiveResponse:] + 5020
	6   StoreKit                            0x00000001b42d252c F61422D2-AFEB-39BD-9143-458D82A29536 + 87340
	7   libdispatch.dylib                   0x0000000106f8a338 _dispatch_call_block_and_release + 24
	8   libdispatch.dylib                   0x0000000106f8b730 _dispatch_client_callout + 16

2020-05-18 15:24:47:164 Leplace World[459:76686] CRASH: -[SKProduct localizedPrice]: unrecognized selector sent to instance 0x282f0ee90 Stack Trace: (
	0   CoreFoundation                      0x00000001a56f8604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
	1   libobjc.A.dylib                     0x00000001a541abcc objc_exception_throw + 56
	2   CoreFoundation                      0x00000001a55fcea8 409609CD-8410-38E1-BA5D-BDED609D2018 + 192168
	3   CoreFoundation                      0x00000001a56fc694 409609CD-8410-38E1-BA5D-BDED609D2018 + 1238676
	4   CoreFoundation                      0x00000001a56fe5bc _CF_forwarding_prep_0 + 92
	5   Leplace World                       0x000000010461d7a8 -[BatchProductsRequestDelegate productsRequest:didReceiveResponse:] + 5020
	6   StoreKit                            0x00000001b42d252c F61422D2-AFEB-39BD-9143-458D82A29536 + 87340
	7   libdispatch.dylib                   0x0000000106f8a338 _dispatch_call_block_and_release + 24
	8   libdispatch.dylib                   0x0000000106f8b730 _dispatch_client_callout + 16
	9   libdispatch.dylib                   0x0000000106f8de88 _dispatch_queue_override_invoke + 872
	10  libdispatch.dylib                   0x0000000106f9cd74 _dispatch_root_queue_drain + 376
	11  libdispatch.dylib                   0x0000000106f9d698 _dispatch_worker_thread2 + 152
	12  libsystem_pthread.dylib             0x00000001a540fb38 _pthread_wqthread + 212
	13  libsystem_pthread.dylib             0x00000001a5412740 start_wqthread + 8
)
2020-05-18 15:24:47.178091+0300 Leplace World[459:76686] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SKProduct localizedPrice]: unrecognized selector sent to instance 0x282f0ee90'
*** First throw call stack:
(0x1a56f85f0 0x1a541abcc 0x1a55fcea8 0x1a56fc694 0x1a56fe5bc 0x10461d7a8 0x1b42d252c 0x106f8a338 0x106f8b730 0x106f8de88 0x106f9cd74 0x106f9d698 0x1a540fb38 0x1a5412740)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by alexp25** [comment]
Update: I have now switched (forced) to WKWebView as UIWebView was not allowed anymore on App Store, which somehow solved the issue.

**Comment by Seanmclem** [comment]
@alexp25 what is "clearing the handlers"? and why do you need to do it? and when?
sorry, new to this

**Comment by alexp25** [comment]
@Seanmclem I was referring to the event handlers/callbacks that are defined using 
```
let handler = (event) => {
// process event
};
store.when(productId).approved(handler);
```

Initially, I thought these have to be defined on each interaction with the store and then cleared. This is why I used ```once``` instead of ```when``` and cleared with ```store.off(handler);```

Upon further research, I have found out that these have to be defined only once, and never cleared, as in #813 

Anyways, this was not the cause of the initial problem.. https://github.com/j3k0/cordova-plugin-purchase/issues/1036#issuecomment-632103907
