### ISSUE TITLE
Get initial app receipt

### ISSUE THREAD

**Issue by interactivesites** [j3k0/cordova-plugin-purchase#1038]
Hi Jean,

I am facing the issue of getting the initial app-receipt, not IAP. Is this possible?
The flow is supposed to be (paid) app download -> verification of the original purchase (own server) -> server content.

It is related to the Android LVL / licencing, but I will have IAPs too. Hence I'd like to use this plugin for Android & iOS (appStoreReceiptURL). So could the plugin provide both? 

Thanks a lot!
Marco

**Comment by j3k0** [comment]
Yes, recent version of the plugin will send you the appStoreReceipt at startup, if you have a valuable validator and call verify. The "product" will have id = bundle id and type = application

**Comment by interactivesites** [comment]
Thank you mate! I'll dig right in...

**Comment by interactivesites** [comment]
Hi Jean,

I'm using the 10.2.0 version and testing in-app-consumables are fine! 
On ANDROID I am  not getting the initial app transaction object, i.e. the validator is not executed.

```
{
     id: 'de.APPNAME.app',
     type: inAppPurchase.APPLICATION
},

let product = inAppPurchase.get('de.APPNAME.app').  // Will show just the ID and TYPE unless registered in the App store

inAppPurchase.when("de.APNNAME.app").approved(function (product) {
// This is not executed
})
```

One more info: Unfortunately I've created a managed non-consumable in the Android App Store called 'de.APPNAME.app' and it showed as a product. I deleted it again and now it still shows up if I register it as a product -- but as type "inapp".

**Comment by j3k0** [comment]
There is no global receipt on Android like in iOS, but per-product purchase tokens.

You probably want to do this:

```js
inAppPurchase.when("product").approved(function (product) {
    // executed for each owned product
    product.verify();
})
```

This approach also works fine in iOS.

**Comment by interactivesites** [comment]
Thanks -- but shouldn't I replace "product" with my App-Identifier?

```inAppPurchase.when("product").approved(function (product) {```
to
```inAppPurchase.when("my.app.id").approved(function (product) {```
?

And do I need to create this at all?
```
{
     id: 'de.APPNAME.app',
     type: inAppPurchase.APPLICATION
},
```

Because the .approved Event is never triggered, no matter if I register the product or not.

**Comment by AEiosApp** [comment]
Have the same issue, works fine on iOS, but on Android still getting `transaction: null` after several `store.refresh()` requests of my product:

```
{
     id: 'com.my.app',
     type: store.APPLICATION
},
```

Is there any update regarding Android paid app transaction data?
