### ISSUE TITLE
[IOS] Crash on appStoreReceipt

### ISSUE THREAD

**Issue by saulstys** [j3k0/cordova-plugin-purchase#1043]
### system info

```
OSX Catalina 10.15.4
Capacitor 2.1.0. / Ionic 5.2.6
Device: iPhone iOS 13.4.1
Plugin Version: 10.2.0
```

### Expected behavior
App not crashing after refresh()

### Observed behavior

The app is crashing after calling refresh().
Xcode reports an error in AppDelegate
```
    Thread 1: EXC_BAD_ACCESS (code=1, address=0xe97bd4d80)
```
The last trace i get in Xcode console is a
```
    To Native Cordova ->  InAppPurchase appStoreReceipt InAppPurchase1377474454 ["options": []]
```
Same code is working perfectly on Android and worked on IOS until few days ago.
No changes 

Is the number in InAppPurchase1377474454 is related to the apple product ID ?
If it's the case, that product doesn't exist in my AppStore Connect (maybe an old ref ?) 

### Steps to reproduce

```
    store.register({    
        id:  'com.my.product.id',
        alias:  'PRODUCT 1',
        type:  store.NON_RENEWING_SUBSCRIPTION,
    });
    
    store.when('com.my.product.id').initiated((p) => {
        console.log('STORE( com.my.product.id ) INITIATED');
    });
    
    store.when('com.my.product.id').cancelled((p) => {
        console.log('STORE( com.my.product.id ) CANCELLED');
    });
    
    store.when('com.my.product.id').approved((p) => {    
        console.log('STORE( com.my.product.id ) APPROVED');

        p.finish();
    });
    
    store.error((e) => {
        console.log('######## storekit ERROR ' + e.code + ': ' + e.message);
    });
   
    // Refresh the store to start everything    
    store.refresh();

```

**Comment by saulstys** [comment]
I still have the problem.

After more investigations this is what i noticed : 

1/ uninstalling the app and reinstalling, user the same appstore user doesn't change anything. After the refresh(), the plugin crashes on  appStoreReceipt
2/ running the app on a second clean device and sandbox appleID works, i pass the refresh(), app doesn't crash, products are loaded. I can buy a product but it crash just after
3/ restarting the app on the second device, with the same apple id, crashes again after the refresh()
4/ on the second device, removing the app, disconnecting from icloud and appstore, signing in with a brand new sandbox user, resinstalling the app.... the app crashes after the refresh.

So it looks like something remains on the device, even if i change the appstore user or delete the app.
Is there a cache i could clear and start clean ?

**Comment by Dexus** [comment]
You can try to reset the complete iPhone. Sometimes this is the only way to clean all. Does the User where it crash have purchase restrictions?

**Comment by saulstys** [comment]
Thanks @Dexus for the advice, i will try.
Both users are sandbox users. So as i understand they should be able to buy without restrictions

**Comment by saulstys** [comment]
I solved my problem.
It was caused by another cordova plugin  : base64ToGallery 
Removing that plugin solved the problem, no more crash

**Comment by j3k0** [comment]
Hello, sorry for not getting back to you earlier. Nice to hear that you solved this problem. Weird incompatibility issue, I wonder what this plugin does to make the "refresh" call crash... ("polluting" obj-c system libraries with custom extensions maybe?)
