### ISSUE TITLE
[iOS] Determining auto-renewable subscription status

### ISSUE THREAD

**Issue by dmitry-salnikov** [j3k0/cordova-plugin-purchase#1045]
I need to implement an exact check which would answer does user have an active app subscription or not. The problem of answering this question is in the IAPProduct state updates: product always gets in `valid` state, but then it may - or may not - go with `approved->finished` state updates. 

So, is there any e.g event (or any logic rule at least) which would clearly say "all the things are refreshed, validated, re-requested from server, all the stuff is updated and there will be no more product state updates" so I can consider the product state value wouldn't change by refresh mechanism and then answer the main question "does user have an active subscription"? 

Thanks a lot for any help.

**Comment by stolzda** [comment]
I'm currently trying to solve the same problem. I'm still not sure if I am correct, but as far as I understand it now it you need to verify the receipt in order to check if a subscription has expired.

Specifically:

- You need to set a `store.validator = function (product, callback) { ... }` function.
- In this function you need to check if the product is expired (based on the receipt), and depending on that either call `callback(true, {})` if the user still has a  valid subscription, or something else (which i'm not yet sure what, but maybe something like this `callback(false, {code: store.PURCHASE_EXPIRED})` )

I'm still trying to implement this, so I'm not yet sure how it works.

**Comment by stolzda** [comment]
I think you need two things. 1) Stop products going to state `owned`, which you can achieve with receipt validation. I now use the following:

```
store.validator = function(product, callback) {

    myBackendService.validateReceipt(
        product.transaction.appStoreReceipt, 
        product.transaction.type, 
        function (result) {
            if (result && result.data && result.data.status && result.data.status == 'expired') { 
                callback(false, {code: store.PURCHASE_EXPIRED});
            } else {
                //TODO maybe not all cases are ok
                callback(true, {});
            }
        }, 
        function (result) {
            // TODO handle onError
        });
};

store.when('product').approved(function (product) {
    product.verify();
});

store.when('product').verified(function (product) {
     product.finish();
});

```

I noticed that you then get (sometimes?) the "expired" event. So you could try to do the following:

```
store.when('product').expired(function (product) {
    // TODO: User subscription expired, remove premium access / add ads, etc.
});
```

However, I already implemented it on Android, and for me there the way to detect that the product was not owned anymore was to "not receive an owned" event. So what I ended up doing was the following:

- Whenever I receive an `owned` event, I save the timestamp for that product. 
- Periodically I `store.refresh()` . With a bunch of `setTimeout()` functions I then check if the last `owned` timestamp is too far in the past. ( = "User did not receive an owned event for a long time = probably not subscribed anymore").

It is quite an ugly hack, but it was the only way to get it working for me. With adding enough time between the checks (effectively allowing users to have the subscription-access even some hours / days after it expired) I think it works ok.

Maybe it is possible to get the `expired` event working consistently with receipt validation in all circumanstances, this would be better I assume.
