### ISSUE TITLE
[ANDROID] store.when().error event not triggered

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [j3k0/cordova-plugin-purchase#1047]
### system info
```
Windows
Cordova 9 
Device: Android 6.0.1
Plugin Version: 10.2.0
```

### Expected behavior
`store.when().error()` to be triggered when an error occurs curing purchase.
documentation: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#initiate-a-purchase
The `error` event link goes to the when().error event, so it seems it should be called.

### Observed behavior
`store.error()` event is triggered with store.ERR_PURCHASE.

### Steps to reproduce

- Start a an order with a test account
- Select  "Test card, always declines" as payment method
- Enter password, click OK, click OK

As I understand it, this should cause `store.when().error()` to be triggered (because the order failed).

Bit of my code:
```js
store.when().cancelled(function (p) {
    console.log('cancelled');
});
store.when().error(function (e) {
    console.log('error' + e.code + e.message);
});
```
When I cancel the purchase (by clicking away from the IAB popup), the cancelled event **is** called.  So I don't think it is my syntax.

Additional info:
- The product I am attempting to order is a subscription
- This is the logcat output when I attempt to purchase with the declined card:
  - ` W/CordovaPurchase: onPurchasesUpdated() -> Failed: ERROR: Fatal error during the API action`

**Comment by Lindsay-Needs-Sleep** [comment]
Assuming the documentation will be followed and `store.when().error()` will be triggered:
It also seems to that the `store.error()` event shouldn't be called at all.

It's kind of strange to have 2 callbacks triggered for the same event.  (It makes it harder to handle errors.  eg. if I handle this error from `store.when().error()` then I have to make sure I ignore it in `store.error()`.
But it might just be me.

Honestly, it would be even better BETTER if failed payments would trigger a `store.order()` promise instead.  (like the `error` promise, or maybe a `failed` promise.)

**Comment by Lindsay-Needs-Sleep** [comment]
[iOS] I wasn't able to test a failed purchase on iOS, but it would be nice to get a confirmation on iOS's behavior when a decline card is used.  (Or how to test a failed purchase with sandbox)

**Comment by vinayNdz** [comment]
> [iOS] I wasn't able to test a failed purchase on iOS, but it would be nice to get a confirmation on iOS's behavior when a decline card is used. (Or how to test a failed purchase with sandbox)

@Lindsay-Needs-Sleep Hi, I need some help regarding the in-app purchase in iOS. This is my code, here I want to implement a non-renewable subscription. And when the approved event is triggered I'm passing the appStorereceipt to my server where it calls the verifyReceipt api to apple server from backend and returns the receipt in a human readable form to backend and on success I'm navigating it to a new page. This is what I'm doing here. My doubt are 

1. Is that approved event triggers only when a successful payment is done ?
2. How do we know if the payment got declined by the apple server ? Is their any response from apple server? 
3. If the purchase is unsuccessful does the approved event trigger?

If the payment got declined by the bank or from the apple server I need to do some other functionality. Anticipating your response. Any information would be much helpful. Thanks



`setup() {
      this.store.register({
      id: "lite30",
      type: this.store.NON_RENEWING_SUBSCRIPTION,
      alias: "lite30",
    });

    this.store.register({
      id: "premium365",
      type: this.store.NON_RENEWING_SUBSCRIPTION,
      alias: "premium365",
    });

    // restore purchase
    this.store.refresh();
  }

  registerHandlersForPurchase(productId) {
    let self = this.store;
    let planid;
    if (productId == "lite30") planid = 2;
    else planid = 3;

    this.store.when(productId).updated(function (product) {
      console.log("enteredqwe");
      if (
        product.loaded &&
        product.valid &&
        product.state === self.APPROVED &&
        product.transaction != null
      ) {
        product.finish();
      }
    });

    this.store.when(productId).approved((product: IAPProduct) => {
      product.verify();
      if (
        this.email != "" &&
        this.email != undefined &&
        this.userid != "" &&
        this.userid != undefined
      ) {
        this.commonService
          .inAppPayment(
            this.userid,
            planid,
            product.transaction.appStoreReceipt
          )
          .subscribe(
            (res) => {
              if (res.result_status) {
                this.loader.hideLoader();
                product.finish();
                this.navCtrl.setRoot(MenuPage);
              } else {
              }
            },
            (error) => {
              console.log(error);
            }
          );
      }
    });
  }

  /* PAYMENT PROCESS */
  planSelect(plan) {
    console.log("enteredplanselect", 1);
    this.isEnabled = false;
    setTimeout(() => {
      this.isEnabled = true;
    }, 15000);
    this.registerHandlersForPurchase(plan);
    try {
      let product = this.store.get(plan);
      this.store
        .order(plan)
        .then((p) => {
          this.store.when(plan).initiated((p: IAPProduct) => {
            this.registerHandlersForPurchase(plan);
          });
        })
        .catch((e) => {
          console.log(e);
        });
    } catch (err) {
      console.log("Error Ordering " + JSON.stringify(err));
    }
  }`

**Comment by Lindsay-Needs-Sleep** [comment]
This is still an issue as far as I know.  (even if it is just an issue with the documentation.)

**Comment by mst2020** [comment]
Can confirm: `store.when().error` is **not** triggered.

cordova-plugin-purchase 10.3.0
cordova-android 9.0.0
cordova 10.0.0

Have to use store.error() as an ugly workaround.
