### ISSUE TITLE
[Android][iOS] store.when().registered never triggered

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [j3k0/cordova-plugin-purchase#1049]
### system info

```
Cordova: 9.0
iOS 13 and Android 6
Plugin Version: 10.2.0
products are all subscriptions
```

### Expected behavior
store.when().registered event triggered
documentation: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#events

### Observed behavior
I can see 2 `store.when().updated` events fired per product with the products having state="registered", but `store.when().registered` is never triggered. 

### Steps to reproduce

```js
            store.when().updated(function (p) {
                if (p.state === store.REGISTERED) {
                    console.log('updated registered');
                 }
            });
            store.when().requested(function (p) {
                // never called
                console.log('when requested');
            });

            store.register({
                id: product.id,
                alias: product.alias,
                type: store.PAID_SUBSCRIPTION,
            });
            store.refresh();
```

**Comment by banjerluke** [comment]
You wrote `store.when().requested` instead of `store.when().registered`...

**Comment by Lindsay-Needs-Sleep** [comment]
Oh gee that's embarrassing. 
@banjerluke Thank you.
