### ISSUE TITLE
[Android][iOS] inconsistent purchase cancelled behavior

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [j3k0/cordova-plugin-purchase#1051]
### system info
```
Cordova 9 
Device: Android 6.0.1
Device: iOS 13.4.1
Plugin Version: 10.2.0
```

### Observed behavior

When you cancel a purchase on **iOS**:  
- `store.error()` event is triggered with store.ERR_PAYMENT_CANCELLED.
- AND `store.when().error()` event is triggered with store.ERR_PAYMENT_CANCELLED.
- *Bonus:* The message received with store.ERR_PAYMENT_CANCELLED in the above cases is: `Cannot connect to iTunes Store - {"productid": "the-id"}`  (This is pretty wrong)

When you cancel a purchase on **Android** (by clicking out side the dialog):  
- ONLY the `store.when().cancelled()` event is triggered.

Relevant documentation sections:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#initiate-a-purchase
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#events

### Expected behavior
That Android and iOS have the matching behavior.
The documentation should also match this behavior.

I don't know the reasoning behind how we got here... but I think the way **Android** behaves makes the most sense.

BUT, similar to [this comment](https://github.com/j3k0/cordova-plugin-purchase/issues/1047#issuecomment-643867877): I think the best behavior would be having a `cancelled(product)` promise on `store.order()`.

**Comment by doug1e** [comment]
I face similar issues on IOS but the error code I receive is 6777010, which is store.ERR_UNKNOWN, I believe.
Have you found a workaround?

**Comment by Lindsay-Needs-Sleep** [comment]
Not a very good one.

Inside store.error() I just check if the error == store.ERR_PAYMENT_CANCELLED, and if it is, I ignore it.

**Comment by doug1e** [comment]
Many thanks

**Comment by Lindsay-Needs-Sleep** [comment]
AFAIK this is still a valid issue
