### ISSUE TITLE
Store.get of Android IAP return JSON with null values

### ISSUE THREAD

**Issue by AEiosApp** [j3k0/cordova-plugin-purchase#1053]
# !!! PLEASE USE IN SUBJECT [IOS] OR [ANDROID] AS PREFIX FOR YOUR ISSUE !!!

### system info

```
OSX Catalina 10.15.05
Cordova 9.0.0 // Vuejs & Quasar
Device: Android 9
Plugin Version: 7.4.3
```

### Expected behavior

Get IAP object with IAP properties from Google Play Store

### Observed behavior

store.when('my_iap').updated return an object with null values:

```
{
  "id": "com.ay.italy4merome",
  "alias": "com.ay.italy4merome",
  "type": "non consumable",
  "group": "",
  "state": "registered",
  "title": null,
  "description": null,
  "priceMicros": null,
  "price": null,
  "currency": null,
  "countryCode": null,
  "loaded": false,
  "canPurchase": false,
  "owned": false,
  "introPrice": null,
  "introPriceMicros": null,
  "introPricePeriod": null,
  "introPriceNumberOfPeriods": null,
  "introPricePeriodUnit": null,
  "introPriceSubscriptionPeriod": null,
  "introPricePaymentMode": null,
  "ineligibleForIntroPrice": null,
  "discounts": [],
  "downloading": false,
  "downloaded": false,
  "additionalData": null,
  "transaction": null
}
```
### Steps to reproduce

I coded store.register of my iap, and after store.updated is called I'm trying to store.get, receive an JSON objetc, but values are null.

To debug I just connect Android device to my Mac and execute 
```
quasar build -m cordova -T android
cordova run android
```
Here is my code:

```
          const iap = 'my_iap'

          window.store.register({
            id: iap,
            type: window.store.NON_CONSUMABLE
          })

          window.store.when(iap)
            .updated(() => {
              const product = window.store.get(iap)
              console.log('product: ' + JSON.stringify(product))
            })
          window.store.refresh()
```

The same code works fine when I build & run it for iOS

**Comment by Dexus** [comment]
This can't work if you wait for 'com.ay.italy4merome' and you use 'my_iap' as ID but it should be your alias....

**Comment by AEiosApp** [comment]
Yes, I'm using
```
const iap = 'com.ay.italy4merome'
```
But it still doesn't work
Sorry for mistake in initial message

**Comment by Dexus** [comment]
Hi, are you sure you register your items in the store and for Android your already uploaded your app to beta state?

Von meinem iPhone gesendet

**Comment by AEiosApp** [comment]
Yes, sure - it is already published app (made in Android Studio), and the IAPs are active and users purchase it. 
We are making new version on Cordova, so I'm testing purchase plugin.

**Comment by AEiosApp** [comment]
I build apk and signed it, but after installation to real device still getting null values, any ideas?

**Comment by AEiosApp** [comment]
Sorry guys, found my mistake in app name in package.json.

Now everything works fine both on iOS and Android.
