### ISSUE TITLE
[iOS] No billing PeriodUnit on older iOS devices

### ISSUE THREAD

**Issue by msabbasi** [j3k0/cordova-plugin-purchase#1054]
### system info
```
Cordova: 9.0.0 (cordova-lib@9.0.1)
Devices: iPhone 6s (iOS 13.4.1), iPad mini 2 (iOS 12.4.7), iPhone 5 (iOS 10.3.4), iPad 2 (iOS 9.3.5)
Plugin Version: 10.2.0
```

### Expected behavior
The product should have billingPeriodUnit no matter the device/iOS version.

### Observed behavior
Only the iOS 13, and 12 devices have billingPeriodUnit.

iOS 9 and 10 do not have the billingPeriodUnit parameter at all.

### Steps to reproduce

```js
// This is a summarized, hand written code here, so please forgive syntax errors

var PRODUCTS = {...}; // Please fill with your test products. Mine are subscriptions
var products = {};

store.validator = function (product, callback) {
   // Using ajax for a custom receipt validator
  // which calls callback true eventually
  callback(true);
}

store.ready(function () {
  console.log(products);
  // NO billlingPeriodUnits in the products if on iOS 9/10!!
});

store.when().valid(function (p) {
     products[p.alias] = p;
});

// Register products (they are subscriptions)
        var alias, product;
        for (alias in PRODUCTS) {
            product = PRODUCTS[alias];
            store.register({
                id: product.id,
                alias: alias,
                type: store.PAID_SUBSCRIPTION,
            });
        }

store.refresh();

**Comment by mahnuh** [comment]
Had the same problem even on iOS 13. Plugin version 10.1.1 however seems to work (at least on iOS 13).

**Comment by j3k0** [comment]
The billing period has been exposed by Apple starting **iOS 11.2**. The information isn't available on older devices, as the plugin has no way to know this information.

https://developer.apple.com/documentation/storekit/skproduct/2936884-subscriptionperiod

This field is only supported since plugin version **10.0**.

Sorry that the documentation does not make this clear.
