### ISSUE TITLE
validation /your-check-purchase-path

### ISSUE THREAD

**Issue by Triden** [j3k0/cordova-plugin-purchase#1061]
win 10, android, cordova 9.0.0

"/your-check-purchase-path"

Data Params

The product object will be added as a json string.

Hello, the request comes, but doesn’t get the data in any way? Can you tell me how to get them?
I used $_POST and file_get_contents ('php://input');

**Comment by MadyAkira** [comment]
You just have to parse the body from the request. (req.body)
You'll find all the data you need for receipt verification in req.body.transaction.

Just google for "php parse request body".
