### ISSUE TITLE
[ANDROID] Free Trial Offer information missing

### ISSUE THREAD

**Issue by lonwi** [j3k0/cordova-plugin-purchase#1065]
store.Product object is missing some information related to the Free Trial. Also, there are some additional empty fields that are not documented in the API. The documentation could be a bit better on this. 

### system info
```
cordova 9.0.0
cordova-android: 8.1.0,
Device: Huawei Mate 20 Pro // Android 10.0
Plugin Version: 10.2.0
```

### Expected behaviour
```
introPrice: "0.00 HUF"
introPriceMicros: 0
introPricePaymentMode: "FreeTrial"
introPricePeriod: 14
introPricePeriodUnit: "Day"
```
### Observed behaviour
```
introPrice: ""
introPriceMicros: ""
introPriceNumberOfPeriods: 1
introPricePaymentMode: "FreeTrial"
introPricePeriod: 1
introPricePeriodUnit: ""
introPriceSubscriptionPeriod: ""
```
### Steps to reproduce

Create a Google Play subscription product with 14 days Free Trial offer

**Comment by codingfriend1** [comment]
I am having this same issue on the Pixel 3a using Capacitor.
