### ISSUE TITLE
[Android] Is it possible debug in app purchases?

### ISSUE THREAD

**Issue by Carsak** [j3k0/cordova-plugin-purchase#1071]
### system info
"@ionic-native/in-app-purchase-2": "^4.20.0"
Linux mint 19
Device: Android One 27 api level

### Expected behavior
Debugging via Chrome Remote Debug tool

### Observed behavior
Cant to debug.

### Steps to reproduce
You can upload to Google play internal testing only signed release version. If you try add to config.xml 
```  
  <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:debuggable="true" />
        </edit-config>
```
Errors appears: "You cant upload debuggable version to Google Play"

I tried another option:
1. Upload non-debuggable version to Google play Internal testing
2. Download this version. Check IAP. IAP works
3. Add `<application android:debuggable="true" />` to config.xml
4. Build locally  debuggable apk. Dont change version number
5. Uninstall app on device
6. Install debuggable apk to device.
7. Check IAP. But IAP dont work. Error "IAP dont work on this version app"

Is it possible debug IAP + app with Chrome debug tool?

Sorry for bad english.

**Comment by Lindsay-Needs-Sleep** [comment]
I use windows and cordova, but I will try to help...

Can you try:

Step 1) Don’t add `<application android:debuggable="true" />` to config

Step 2) from any terminal to ensure adb is running.  (You should see your device listed)

Step 3)
From android studio, run the app via the debug button  
OR
`cordova run android` (or the equivalent ionic command)
This installs the debug version of the app by default.  (If you want to install the release version you have to include the `--release` option.  If I am remembering correctly....)

Step 4) In chrome, visit `chrome://devices`

Can you see your device for debugging? 
(You must have the app open.  Or, as a test, you should be able to debug any webpage you visit on your device’s mobile chrome browser.)

**Comment by Carsak** [comment]
@Lindsay-Needs-Sleep 
I tried this

My steps:
1. Upload non-debuggable version to Google play **internal testing**
2. Download apk from  internal testing.
3. Check IAP. IAP Works
Then:
4. Didn’t add <application android:debuggable="true" /> to config
5. Run ionic cordova run android --device
6. Locally version installed to device.
7. But it is empty on chrome://devices

**Comment by Dexus** [comment]
Upload a non debug app to beta/alpha test.

Don‘t change any version and activate debug mode in config, test it on your developer phone

You should see anything you need

Von meinem iPhone gesendet

**Comment by Carsak** [comment]
@Dexus 
So tried
1. Uploaded apk to Alpha channel
2. Installed Apk from alpha channel. IAP Works!
3. Added <application android:debuggable="true" /> to config.xml
4. Run command `ionic cordova build android --release`
5. Tried to install via command adb -d install path/to/apk

Error appears:
ionic cordova build android --release

```
Performing Streamed Install
adb: failed to install app-release.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package myPackagename signatures do not match previously installed version; ignoring!]
```

**Comment by Lindsay-Needs-Sleep** [comment]
Based on the error, I think you need to uninstall the app first, then install with the cmd.

**Comment by Carsak** [comment]
> Based on the error, I think you need to uninstall the app first, then install with the cmd.

1. Uninstalled app
2. Installed app

After IAP didnt work. Error appears "IAP dont work on this version app"

![image](https://user-images.githubusercontent.com/9497934/87865949-e0f0d600-c983-11ea-9453-6436003dedb7.png)

**Comment by Lindsay-Needs-Sleep** [comment]
Sorry, I don’t know why it isn’t working. :(

**Comment by Carsak** [comment]
@Lindsay-Needs-Sleep 
OMG, 
you will not believe!!!

It was all because I didn't add MAIN gmail to testers 

So, I have several accounts in my phone. I added first email to testers list, but it is not MAIN account on device.
After adding main account debugging works!
https://support.google.com/googleplay/android-developer/answer/6062777

![image](https://user-images.githubusercontent.com/9497934/87955561-96bc4180-cab6-11ea-8b8f-c5dcaae17ecb.png)

then just:

1. Upload to Alpha channel release version
2. Run locally command 
`ionic cordova run android --device`
It install debug version to device
3. Use chrome remote debugging.
4. Yes!!!!

![image](https://user-images.githubusercontent.com/9497934/87956880-39c18b00-cab8-11ea-83fa-cc5723953747.png)
