### ISSUE TITLE
[ANDROID] How to rewrite(replace) "when" based callbacks correctly?

### ISSUE THREAD

**Issue by Carsak** [j3k0/cordova-plugin-purchase#1073]
### system info
```
Ionic 3.2.*
Cordova 8.1
Device: Android 9.0
Plugin Version: "cc.fovea.cordova.purchase": "8.1.1",
```

### Expected behavior
Then latest callback will be invoked

### Observed behavior
Invokes all added callbacks

### Steps to reproduce
It is all about validator callback, but the easiest way to reproduce with when().updated() event

I modifying existing project with long history. Project has one IAP service that called at app bootstrap. For example

```
import { InAppPurchase2 } from '@ionic-native/in-app-purchase-2';

@Injectable()
export class Mega_Global_IAP {
 constructor(
    private inAppPurchase: InAppPurchase2,
) {
  this.inAppPurchase.register.................;
  this.inAppPurchase.when('product').update(this.globalUpdate);
  this.inAppPurchase.validator = this.globalValidator();
  this.inAppPurchase.refresh();
  }
}
```
Mega_Global_IAP - it is God object pattern with many code. this.globalValidator, globalUpdate - is too specified functions, serves only for product1

I need create new page with new IAP product2. So decided to create new page-component.
Something like this:
```
import { InAppPurchase2 } from '@ionic-native/in-app-purchase-2';

@Injectable()
export class Local_IAP {
 constructor(
    private inAppPurchase: InAppPurchase2,
) {
  console.warn('My awesome locally service was created');
  this.inAppPurchase.registerProduct2();
  this.inAppPurchase.when('product').update(this.localUpdate);
  this.inAppPurchase.validator = this.localValidator();
  this.inAppPurchase.refresh();
  }
}
```

And now every event of Local_IAP call two callbacks.
1. First Mega_Global_IAP callback
2. Local_IAP callback

![1](https://user-images.githubusercontent.com/9497934/87873534-fb01d700-c9ca-11ea-835a-94949808543b.jpg)

![2](https://user-images.githubusercontent.com/9497934/87873538-03f2a880-c9cb-11ea-9151-12a104e15407.jpg)

So i have two questions:
1. Why Global IAP is using when IAP injecting to Local service? I thought it creates new instances every time
2. How to clear all callbacks? To be more precise, rewrite(replace) global callbacks with my local

Sorry for bad english

**Comment by Dexus** [comment]
You should use the update listeners only for the corresponding SKU and not globally for all products, if you don't want that.

Maybe don't copy & paste only the shit others do... read the docs and register only products with the functions you need. And not global listener for everything... 

Sometimes i think nobody ready really the docs - @j3k0 we should delete the docs and get paid for every question... 😄

**Comment by Carsak** [comment]
@Dexus 
So, do you want to say, global callbacks for all product is anti pattern?
Do not write like:
`when('product')`
Write
`when('my_specific_sku')`
?


then question:
How to add listener to group of product?
Example:
I have SKU_1 SKU_2 SKU_3 SKU_4 ..... SKU_15. All 15 products must handle with one callback

Do I need write 15 times?
when("SKU_1").appoved(callbackForConsumable);
when("SKU_2").appoved(callbackForConsumable);
when("SKU_3").appoved(callbackForConsumable);
when("SKU_4").appoved(callbackForConsumable);
.....
when("SKU_4").appoved(callbackForConsumable);

Then 15 times:
store.off(callbackForConsumable);
store.off(callbackForConsumable);
store.off(callbackForConsumable);
store.off(callbackForConsumable);
......
store.off(callbackForConsumable);

**Comment by Dexus** [comment]
Only if you need for different products different function calls you should use the anti pattern.

I will write here tomorrow a bit more detailing what I mean.

Von meinem iPhone gesendet

**Comment by Dexus** [comment]
So now we want to answer it again. So basically, it's very simple:

For example:
```js
import { InAppPurchase2 } from '@ionic-native/in-app-purchase-2';

@Injectable()
export class Mega_Global_IAP {
  constructor(
    private inAppPurchase: InAppPurchase2,
    private ArrayOfProducts: [{
      id: "cc.fovea.purchase.consumable1",
      alias: "100 coins",
      type: InAppPurchase2.store.CONSUMABLE
    }],
  ) {
    for (let i of this.ArrayOfProducts) {
      console.log(i); // logs the product
      this.inAppPurchase.register(i); // register product
    }

    this.inAppPurchase.when('product').update(this.globalUpdate);
    this.inAppPurchase.validator = this.globalValidator();
    this.inAppPurchase.refresh();
  }
}
```

With a SinglePageApplication (SPA) you only have to do this registration once and execute it. Multiple or for each product individually makes no sense and only leads to problems, as you already described above.

For the `when(xxxx)` calls, you should have a look at the documentation: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#queries to see if there is something suitable for you, otherwise you have to add appropriate distinctions for special single treatments of products in the functions.

If you use the `off(...functionRef...)`, make sure that this function is no longer needed, because all functions with the same signature are removed. Say `store.off(this.globalUpdate)` will cause all references with the signature of `this.globalUpdate` to be removed. And to make it available again the store would have to be reinitialized.

I hope I could help you with that. For any further questions, don't hesitate to write here.

**Comment by Carsak** [comment]
I am preparing some tips for people, who came from PHP or other OOP base language.

I working about month with IAP and Ionic and surprised for some ... features in JS
