### ISSUE TITLE
[ANDROID][IOS] Is store.off() works only with named functions?

### ISSUE THREAD

**Issue by Carsak** [j3k0/cordova-plugin-purchase#1074]
system info
```
Plugin version: 10.2
Cordova version: 8.*
Os: Linux Mint
```

So, question is about store.off();

If somebody register anonymous functions to event, for example store.when().updated, is it impossible to unregister this?

**Comment by Dexus** [comment]
Hi @Carsak,

it is not possible to remove anonymous functions, unless you store a reference to the function at creation.

Regards Josef

**Comment by Carsak** [comment]
Thanks a lot.
Everything cleared up
