### ISSUE TITLE
[ANDROID] Google Play Billing Library Version 3

### ISSUE THREAD

**Issue by chuchuva** [j3k0/cordova-plugin-purchase#1077]
Google [announced Google Play Billing Library Version 3](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html) in June 2020.

Can we switch this plugin to version 3 of Google Play Billing Library?

Right now it uses version 2.2:

https://github.com/j3k0/cordova-plugin-purchase/blob/238b65998cb8bf2bd3d2ecbda05c3bd66a5a60bf/plugin.xml#L122

I'm happy to help with testing.

**Comment by j3k0** [comment]
Just did the change, from what I read it should be backward compatible. I didn't test yet. Want to try it: #1079

**Comment by chuchuva** [comment]
I installed plugin using this command:

    cordova plugin add https://github.com/j3k0/cordova-plugin-purchase

In-app purchasing works fine in my app - thank you very much for making this change! 👍

**Comment by aesculus** [comment]
Google is complaining that my app is not using V2 or greater. I came from V9.0.0 to V10.0.3.  Only one released app so?

I did see this note in their documentation:

> Add the Google Play Billing Library dependency to your app's build.gradle file as shown:

`Add the Google Play Billing Library dependency to your app's build.gradle file as shown:

dependencies {
    def billing_version = "3.0.0"

    implementation 'com.android.billingclient:billing:$billing_version'
}`

It is necessary to add this?

**Comment by aesculus** [comment]
I looked into the plugin.xml on 10.3.0 and see this line item:
`<framework src="com.android.billingclient:billing:3.0.0" />`
So it looks like it should be set OK.
What am I missing?

**Comment by aesculus** [comment]
Never mind. Figured it out.

If this helps anyone else:

I have an internal alpha test version that was using the old billing system (ie < 2.0). There were no testers assigned to it.

Unfortunately in Googleland you cannot remove APKs so Google considered it active. I had one other version internal too. So I had to update both of these inactive APKs with my latest beta version, suffer the complaint I had no tester assigned to it and then I could turn back on automatic subscription renewal.
