### ISSUE TITLE
[ANDROID] Docs has not mention about developerPayload in store.order method

### ISSUE THREAD

**Issue by Carsak** [j3k0/cordova-plugin-purchase#1078]
### system info
common system

### Expected behavior
In this issue [900](https://github.com/j3k0/cordova-plugin-purchase/issues/900#issuecomment-516845833) says, that you can send developer Payload in store.order method.

But I cant find something about this in docs
[DOCS](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeorderproduct-additionaldata)

### Observed behavior
Maybe docs is outdated?

**Comment by j3k0** [comment]
> Maybe docs is outdated?

No: issue #900 is outdated.

This has changed because purchases can now occur without a direct call to `order()`.

See https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storedeveloperpayload for the new way to set the developerPayload.
