### ISSUE TITLE
Change subscription in the app

### ISSUE THREAD

**Issue by Triden** [j3k0/cordova-plugin-purchase#1080]
Hello, I could not find a guide on how to change the option to switch from one subscription to another. For example from 'standard' to 'vip'.

By default, the subscription expiration date is changed. How to make sure that the difference is paid immediately?

It turns out that if you switch tariff the ' standart' to the 'vip', you can get information for the 'VIP' and return back to the old tariff. whitch No buy.

IMMEDIATE_WITH_TIME_PRORATION
IMMEDIATE_AND_CHARGE_PRORATED_PRICE
IMMEDIATE_WITHOUT_PRORATION
DEFERRED
https://developer.android.com/google/play/billing/subs#change

// (I did not find enough documentation to support this parameter)
// if (replaceSkusProrationMode) { // int
// params.setReplaceSkusProrationMode(replaceSkusProrationMode)
// }

Is this what I need?

"I did not find enough documentation to support this parameter"
BillingFlowParams.Builder setReplaceSkusProrationMode (int replaceSkusProrationMode)

It's just an int.
https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.ProrationMode

Example:

IMMEDIATE_AND_CHARGE_PRORATED_PRICE
int IMMEDIATE_AND_CHARGE_PRORATED_PRICE
Replacement takes effect immediately, and the billing cycle remains the same. The price for the remaining period will be charged. This option is only available for subscription upgrade.

Constant Value: 2 (0x00000002)

**Comment by Triden** [comment]
// (I did not find enough documentation to support this parameter)
    // if (replaceSkusProrationMode) { // int
    //   params.setReplaceSkusProrationMode(replaceSkusProrationMode)
    // }

Is this what I need?

**Comment by Triden** [comment]
"I did not find enough documentation to support this parameter"
BillingFlowParams.Builder setReplaceSkusProrationMode (int replaceSkusProrationMode)

It's just an int.
https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.ProrationMode

Example:

IMMEDIATE_AND_CHARGE_PRORATED_PRICE
int IMMEDIATE_AND_CHARGE_PRORATED_PRICE
Replacement takes effect immediately, and the billing cycle remains the same. The price for the remaining period will be charged. This option is only available for subscription upgrade.

Constant Value: 2 (0x00000002)

**Comment by j3k0** [comment]
Please check this PR: https://github.com/j3k0/cordova-plugin-purchase/pull/1079

I added the proration mode option when making a purchase (but it's untested, please let me know if it works).

Documentation: https://github.com/j3k0/cordova-plugin-purchase/blob/feature/google-play-3/doc/api.md#storeorderproduct-additionaldata

**Comment by Triden** [comment]
Thanks.) Already corrected the library locally.)
update the library and try. I think it should work.

I do not know English well, I will try to explain it more clearly. When using "IMMEDIATE_AND_CHARGE_PRORATED_PRICE", if a new subscription is more expensive, everything works out well, the user pays the difference immediately. When lowering, it gives an error. I think this is normal, since Google cannot give the difference to the user, at this moment you need to use, for example: "IMMEDIATE_WITH_TIME_PRORATION".
Maybe I did something wrong, but it looks like it really works like this.

Perhaps it will help people if you write on wikipedia.

**Comment by Triden** [comment]
In the "feature/google-play-3" branch
With the version of the library "com.android.billingclient:billing:3.0.0"
Swears at "import com.android.billingclient.util.BillingHelper;"
Does not exist.
Changing to version "2.2.0" solves the problem.

Tariff-to-tariff switching works very well.
