### ISSUE TITLE
[IOS] Error Ordering {} on console when attempt a purchase

### ISSUE THREAD

**Issue by fitmax-project** [j3k0/cordova-plugin-purchase#1083]
everything was working well around 2 month ago...
the only thing change is i have update my project to angular 10.
(app based on ionic + angular + cordova)

for some reason i get **Error Ordering {}** in the console once i initiate my purchase trigger:
```
this.store
        .order(productId, {
          applicationUsername: this.user.getCurrentUser()._id,
        })
```

my OS:
```
OSX catalina 10.15.6
Cordova 5.1.1 ios
Device: iPhone iOS 13.6 
Plugin Version: 10.1.1
```

### Expected behavior
init iap purchase and popup ios app approval
### Observed behavior
Error Ordering {} on console log

### update: 
after some investigation on debug mode i can see the following log:
InAppPurchase[js]: product super_v1 has a transaction in progress: 1000000688278517

but still - the confirmation alert:(example)
https://i.stack.imgur.com/d5ftv.png - not popup

and another log:
Store Error {"code":6777020,"message":"Transaction expired: Transaction has expired 2020-01-23 08:30:36 Etc/GMT"}

**Comment by j3k0** [comment]
Hey @fitmax-project ,

First of, you should now set `applicationUsername` using `store.applicationUsername`. See the updated documentation about this. The reason why is in the release notes.

If the plugin finds a transaction in progress when placing an order, it means it hasn't been finished properly. Is the problem specific to a device? For a dev device, you can is `autoFinishTransactions` to cleanup the transactions queue.

**Comment by francoisduchemin** [comment]
Hi @j3k0 ,

I'm looking for the release notes... can you please tell me where I can find them?

Thanks!

**Comment by j3k0** [comment]
https://github.com/j3k0/cordova-plugin-purchase/releases

**Comment by francoisduchemin** [comment]
Cool, thanks!
