### ISSUE TITLE
IOS - Testflight - approved event never fired after purchase

### ISSUE THREAD

**Issue by xavax31** [j3k0/cordova-plugin-purchase#1085]
/!\ this problem occurs only in testflight test. All work fine while testing in XCode with sandbox user.

### system info

MacBook Pro (Retina 13 pouces, début 2015)  
macOS catalina v 10.15.4  
Cordova 9.0.0
Device: Iphone SE(2016) ios 13.3  
Plugin version: 10.2.0  

### Expected behavior

After user purchases an item, the approved event should be fired.  

### Observed behavior

events requested and initiated are fired, but event approved is not fired after purchase is done (nor error, nor cancelled if cancelled).
Observed for consumable or paid subscription. For paid subscription, i can reproduce these steps to infinity, system or testflight never says that subscription is already done.

### Steps to reproduce

when store.order is called, then testflight popups user password. Weird, a second system popup asks password too (cf linked picture). I cancel the second and  clic on 'acheter' in the testflight one, give my password and validate. A new testflight popup confirms that purchase is done. But no event is fired (approved, error, cancelled).
Same problem if I fill first popup too rather than close it.

![IMG_1826](https://user-images.githubusercontent.com/4051022/89907058-76326380-dbec-11ea-8f03-da33fbc5ab8a.PNG)

![IMG_BFB58292F212-1](https://user-images.githubusercontent.com/4051022/89908995-e0e49e80-dbee-11ea-9d7b-092b24432614.jpeg)

**Comment by matheustavaresdev** [comment]
I'm having the same issue as well... Either the purchase page won't appear at all or it will never get approved...

**Comment by jffs** [comment]
same

**Comment by junklabgames** [comment]
Did anyone have any luck with this issue? Experiencing the same now, fingers crossed
