### ISSUE TITLE
[ANDROID] problem with compileSdkVersion 28

### ISSUE THREAD

**Issue by beebase** [j3k0/cordova-plugin-purchase#1086]
#861 # system info

```
Android 9 api 29
Cordova 10.0.0
Device: Android 9
Plugin Version: latest  cc.fovea.cordova.purchase
```

### Expected behavior
expect "cordova run android to" build without errors
### Observed behavior
When I add the plugin  cc.fovea.cordova.purchase, another plugin (OneSignal) throws this error:
`OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:28.0.0' -> 28 to prevent compile errors! Recommend updating your project's compileSdkVersion!`

When I remove the plugin  cc.fovea.cordova.purchase everything compiles fine.

Is  cc.fovea.cordova.purchase already supporting android api 29?

**Comment by beebase** [comment]
I just noticed the naming difference between cc.fovea.cordova.purchase and cordova-plugin-purchase.
After replacing fovea plugin everything seems to work.
Is cc.fovea.cordova.purchase discontinued? If so, are there any breaking changes?

**Comment by j3k0** [comment]
`cc.fovea.cordova.purchase` is the legacy ID, it's the same plugin though. It got changed a while ago (1 or 2 years) and we're not updating it as often.

I recommend you stick with the new version (`cordova-plugin-purchase`) of the plugin that has bug fixes and SDK upgrades.

**Comment by j3k0** [comment]
You can check the release notes for any major change that might impact you.
