### ISSUE TITLE
Switching app store user should clear the cache for the owned items.

### ISSUE THREAD

**Issue by kitsunde** [j3k0/cordova-plugin-purchase#109]
I created another apple sandbox user to test subscriptions but the new one was also marked as an owner of the product. The problem was that there was receipts and other items cached in `localStorage` relating to the previous user.

Ideally this shouldn't happen, but I realize it's not a normal use case. It would be nice to have an option that disabled caching though.

**Comment by mariusk** [comment]
Agree. It's pretty much impossible to test auto-renewing subscriptions with the plugin as-is.

**Comment by voneddy** [comment]
I second this issue. 

I tried clearing the local storage with lines like:

              localStorage.removeItem('sk_appStoreReceipt');

after printing out the contents by just typing localStorage on safari console. But now none of the purchases load.... I feel after doing this i need to hit the right sequence of loadReceipts() storeKit.refresh() etc but haven't cracked it yet....
