### ISSUE TITLE
[IOS] - iOS13 cannot connect to the itunes store  

### ISSUE THREAD

**Issue by doug1e** [j3k0/cordova-plugin-purchase#1090]
### system info

```
Package info from my package.json file:
@ionic-native/in-app-purchase-2": "^5.28.0",
"cc.fovea.cordova.purchase": "^10.1.1"

ionic cordova -v: 6.11.1
```

### Expected behavior

store.order(productId) successfully completes the order

### Observed behavior

I apologize in advance as this is not a great issue submission. I wanted to add this so that others facing this issue could benefit from your response.

I already have several apps on App Store and Google Store and I use the same in app code for all of them. However, my recent submission is rejected by Apple as the tester gets ```"Cannot connect to the itunes store"``` message while trying to test the purchase. This is odd as I see such error messages from people when they cannot set their test account properly. However, this message was reported by Apple! Infact, twice as my app got rejected twice for this very reason.

### Steps to reproduce

I do not have a Mac as I build my code on the cloud so testing is even more difficult. However, I noticed one thing that could may be relevant here:

I am aware that you cannot test in app on the simulator. However, the simulator behavior on iOS11 (possible the OS that my other apps were approved with) and iOS13 is different.

1) The store info is shown perfectly fine on both versions on the simulator
2) When I try to to purchase on iOS11 simulator it brings a pop up for user login but on iOS13 it provides the same error message: ```cannot connect to the itunes store```

Hence, I wanted to ask your guidance. Are we supposed to handle things differently for iOS13? Is there a special case that we should be aware of? 

Please find my code below:

At the app initialization I called the following method:
```
  configurePurchasing(productId:string) {
      try {                          
          this.iapStore.register({
              id: productId,
              alias: this.productAlias,
              type: this.iapStore.CONSUMABLE
          });
              
          this.iapStore.when(productId).approved((product) => {
              product.finish();
              
              // Purchase is completed         
          });           

          this.iapStore.when(productId).updated((product) => {
              this.renderProductInfo();                    
          });

          this.iapStore.when(productId).cancelled((product) => {
              // Show purchase cancelled message   
              this.purchaseCancelledFlag = true; 
          });
             
          this.iapStore.error((err) => {
              // Show error message
              this.purchaseErrorFlag = true;
          });

          this.iapStore.ready((status) => {                    
              this.renderProductInfo();                    
          });

          this.iapStore.when(productId).error((err) => {
              // Show error message
              this.purchaseErrorFlag = true;
          });                
          
          this.iapStore.refresh();            
      }
      catch (err) {
      }
  }

  renderProductInfo() {
    try {                  
        let product = this.iapStore.get(this.productId);        

        if (!product) {                    
          // Show error message       
        }
        else if (product.state === this.iapStore.INVALID) {
          // Show error message             
        }                
        else if (product.state === this.iapStore.VALID) {
            // Product loaded and valid.
            if (this.storeInfoLoadedFlag == false) {              
              this.title = product.title;
              this.price = product.price;
              this.description = product.description;                             
            }
            else if (this.purchaseErrorFlag) {
	      // Show error message       
            }
            else if (this.purchaseCancelledFlag) {                        
	      // Show cancel message
            }                         
        }                            
    }
    catch (e) {
    }
  }
```

And below is my purchase method:
```
  purchaseLives() {
      try {                        
          productId = this.productId;
          this.iapStore.get(productId);              
          this.iapStore.order(productId);
          
      }
      catch (err) {
      }
  }  
```

**Comment by rafaellop** [comment]
I notice same thing on an iOS simulator getting errors like this:

```
2020-08-27 07:55:27.926741+0200 [42756:510276] InAppPurchase[objc] (before init): load: Product request started
2020-08-27 07:55:28.465659+0200 [42756:510317] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.request:didFailWithError: AppStore unavailable (ERROR 507)
2020-08-27 07:55:28.465952+0200 [42756:510317] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.request:didFailWithError: Error decoding object
2020-08-27 07:55:28.467621+0200 [42756:510276] [store.js] ERROR: ios -> ERROR 6777002: Load failed: Error decoding object - {}
```

The plugin is the latest official 10.2.0 and simulator version is v13. Cordova version 10.0.0. iOS Platform version is 6.1.0.

**Comment by doug1e** [comment]
Hi @rafaellop 

We are not supposed to test the in app purchase on the simulator as far as I know; it can only truly be tested on a real device. I provided that as a data point since my code had been working perfectly fine up until now
Was your code also working before? Is this a new change for you, as well?

I hope the plugin team will provide guidance as I am stuck at this point.

Thanks,

Doug

**Comment by rafaellop** [comment]
I know it is not possible to test purchases on simulators but when I last checked my app was able to connect to the appstore, download products information and it was also possible to test simple logic and UI like pricing downloaded from the appstore but the purchases themselves. This time it couldn't connect at all. However somehow, not sure when and why, it started to work and now it connects properly. Make sure you are correctly logged to your appleid from the xcode preferences. I suppose this might be the reason because I had to relog during the process of updating my app.

**Comment by doug1e** [comment]
Many thanks @rafaellop 
As my code was rejected by Apple twice with this particular message, I hope Jean-Christophe @j3k0 can provide guidance as I am stuck...

Doug

**Comment by rafaellop** [comment]
@doug1e I don't understand what you mean as "applicationUsername".

**Comment by doug1e** [comment]
Thanks for your reply @rafaellop I saw in another issue submission that the applicationUsername variable was set so I assumed we now have to set such a variable...

To provide update to the issue: 
I removed my sandbox account and created a new one. I can now complete the in app purchase using Test Flight.

However, I now have the following error message: "There is no information available for in-app purchases. Try again later" 
It also gives the error code 21105. I see many other users have started to experience the same issue. I assume it is something to the with the sandbox again but not sure to fix this one.

**Comment by doug1e** [comment]
Turned out to be a sandbox issue; not related to the plugin

**Comment by qpwr** [comment]
Any chance you'll let us know what the issue was, @doug1e?

**Comment by sprengerst** [comment]
That would be interesting.

**Comment by doug1e** [comment]
Hi folks,
 
Apologies for the late reply.  

This is issue is pretty much related to the Apple side and how they manage newly created testing accounts. I basically removed all testing account before my final approval request and things worked. Once you test your app, it might be worthwhile to remove all those test accounts before your submission to Apple. This is a last resort as it may not be needed but I could not find an alternative...

Cheers,

Doug
