### ISSUE TITLE
ANDOID- When getting product info,"trialPeriod":null," even though it is configured in google store and returned as "freeTrialPeriod":"P1W" in SKU 

### ISSUE THREAD

**Issue by tgleb** [j3k0/cordova-plugin-purchase#1096]
### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

In example:
```
Ionic:

   Ionic CLI                     : 6.6.0 (C:\Users\....\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\.....\AppData\Local\Android\sdk)
   NodeJS            : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10


```

### Observed behavior
Trial period  is NULL

"one year subscription with a free trial","description":"one year subscription with a free trial","priceMicros":35990000,"price":"$35.99","currency":"CAD","countryCode":null,"loaded":true,"canPurchase":true,"owned":false,"introPrice":"","introPriceMicros":"","introPricePeriod":1,"introPriceNumberOfPeriods":1,"introPricePeriodUnit":"","introPriceSubscriptionPeriod":"","introPricePaymentMode":"FreeTrial","ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"**trialPeriod":null,"trialPeriodUnit":null**,"billingPeriod":1,"billingPeriodUnit":"Year","valid":true}]

Even though code below returns "freeTrialPeriod":"P1W" which is correct, it is 7 days or 1 week in store

"title":"Evaluway one year subscription with a free trial ( Trip Planner, Gas & Emission Calculator)","description":"one year subscription with a free trial"},{"skuDetailsToken":"AEuhLz0SK","productId":"evaluway_subscription_six_months","type":"subs","price":"$29.99","price_amount_micros":29990000,"price_currency_code":"CAD","subscriptionPeriod":"P6M","**freeTrialPeriod":"P1W**","title":" 6 months subscription with a  free trial ( Trip Planner, Gas & Emission Calculator)","description":"6 months subscription with a free trial"}]", source:

**Comment by geleto** [comment]
I have the same problem. While I could hardcode this information - this is a violation of the Google/Apple policy and can get my app rejected or suspended. So that `wontfix` label is a bummer.

**Comment by yiannis-spyridakis** [comment]
Same issue here. Can you please comment on whether this is a known issue and if there are any workarounds?

**Comment by michaelbutler1998** [comment]
Also running into the same issue, was any progress made here?

**Comment by yiannis-spyridakis** [comment]
Hi, please check here:
https://github.com/j3k0/cordova-plugin-purchase/issues/1201
