### ISSUE TITLE
NPM Version is 10.1.1

### ISSUE THREAD

**Issue by selected-pixel-jameson** [j3k0/cordova-plugin-purchase#1099]
Has this repository been updated on NPM? I'm using capacitor and it says that the latest NPM package is 10.1.1.

**Comment by j3k0** [comment]
I suppose you are not using the new id `cordova-plugin-purchase`, but the old `cc.fovea.cordova.plugin` (this plugin switched to this new id a couple of year ago).

Latest version has been published: https://www.npmjs.com/package/cordova-plugin-purchase
