### ISSUE TITLE
[IOS] native in-app purchase popup delay

### ISSUE THREAD

**Issue by nocodedweb** [j3k0/cordova-plugin-purchase#1101]
Experiencing a native popup delay on iOS when calling ```store.order()``` to initiate the native popup for subscriptions.  The popup displays immediately for all Android in-app purchase subscriptions, just having this issue in iOS.

```
OSX Catalina 10.15.6 (19G2021)
Cordova v10.0.0
Xcode : Version 11.7 (11E801a)
Devices:  iPhone 8 w/ iOS 14, and iPhone 11 w/ iOS 13.3.1
Plugin Version: 10.3.0
```

### Expected behavior

User selects a product and clicks the "Continue" button.  On Continue button click, ```store.order()``` is called and the native purchase plugin should pop up immediately.

### Observed behavior

On Android, the native pop up does show immediately.  But on iOS, the native pop up takes anywhere from 2 to 10 seconds to show the selected subscription product.

### Steps to reproduce

User selects a product and clicks the "Continue" button.  On Continue button click, ```store.order()``` is called and the native purchase plugin should pop up immediately.

```
document.addEventListener("deviceready", function() {
    var productIds = ["p1", "p2", "p3"];
    
    for (var i = 0; i < productIds.length; i++) {
        var subscription = productIds[i];
       
        store.register({
            id:    subscription,
            alias: subscription,
            type:  store.PAID_SUBSCRIPTION
    });
}, false);
```

```
$(document).on("click", "button#continue", function() {
    var pId = $("div.product.active").data("id");
    
    store.order(pId)
        .then(function(result) {
            console.log("order success",result);
        },function(error) {
            console.error("order failed",error);
        });
});
```

Is anyone else experiencing this issue and have steps to fix?

**Comment by jffs** [comment]
Make sure you don't have the device connected to the pc when you are doing the test.

**Comment by nocodedweb** [comment]
> Make sure you don't have the device connected to the pc when you are doing the test.

Device is not plugged into anything.

**Comment by j3k0** [comment]
@nocodedweb - `store.order()` is translated almost directly to a call to the native Apple StoreKit API. If it takes time it's very unlikely to be cause by the plugin. Apple in-app purchases server have been experiencing some slowdown during the last few days, it might be the reason for your issue.

BTW you `deviceready` block probably lacks a call to `store.refresh()` and registration of some listeners (or maybe you edited the code for clarity).

**Comment by MarcelSchuermann** [comment]
@nocodedweb Did you find any solution / improvement to this issue?
I have the same problem. Android shows immediately, iOS takes about 4-5 seconds to show the first time. 
Then if I cancel it and click store.order() again it opens immediately.

Any hints?
@j3k0: Maybe you have an idea?

**Comment by j3k0** [comment]
@MarcelSchuermann - When the native method is called (`[[SKPaymentQueue defaultQueue] addPayment:payment]`), you should have a line of native logs (when running from XCode, or visible with Console.app) that says: `"purchase: About to do IAP"`. As far as I know, the plugin does nothing fancy, just calls the native method to place an order.

If there's a delay, it's because Apple is doing something behind the scene before showing the popup. I believe it reloads the product from the AppStore and the user's receipt, to make sure it's showing the most up to date price and that the user can make the purchase.

When calling `order()`, your UI should show that the order is being processed (`product.state` will be `store.INITIATED`).

**Comment by j3k0** [comment]
Closing this, as I don't see how this might be caused by the plugin. I think it's just standard behavior on iOS: I see this kind of delay on native apps as well on iOS.
