### ISSUE TITLE
[IOS] Webhook not sent

### ISSUE THREAD

**Issue by lostrailler** [j3k0/cordova-plugin-purchase#1103]
Hi

We receive payments of 80CHF but the webhooks were not sent and we don't see any errors. No access logs on our servers and nothing on my dashboard.

![Capture d’écran 2020-09-28 à 22 45 32](https://user-images.githubusercontent.com/16555485/94525464-67534f00-0234-11eb-813d-9d8e1ede2a36.png)

**Comment by j3k0** [comment]
Hello, FYI you can contact Fovea's support at support@fovea.cc for support regarding the service.

It might be that the `applicationUsername` are not set when you place the order?
