### ISSUE TITLE
[ANDROID] - product.lastRenewalDate + expiryDate always undefined

### ISSUE THREAD

**Issue by Davparis** [j3k0/cordova-plugin-purchase#1106]
### system info

Cordova 10.0.0
Installed platforms: android 8.1.0
Plugin Version: 10.0.3
Device: Android 9

### Expected behavior
I successfully built a prototype with auto-renewing subscription (type:PAID_SUBSCRIPTION).
product.id, product.alias, product.type, product.title, product.BillingPeriod, product.BillingPeriodUnit are successfully updated with data retrieved from Play Console.
product.state successfully updated in life-cyle.
product.owned and product.canPurchase values are updated as expected.

### Observed behavior
But **product.expiryDate** and **product.lastRenewalDate** always return "**undefined**", even when the subscription is "owned".
Is this normal ?
I would like to find a way to retrieve from store the ending date of a subscription, or the date of its renewal.

**Comment by gregor-srdic** [comment]
I am also looking for an answer for this 👍

**Comment by NickThorne123** [comment]
Same issue here, the exact same code works on iOS.

Cordova 9.0.0
Installed platforms: android 9.0.0
Plugin Version: 10.1.1
Device: Android 8 (Xiaomi Mi5)

**Comment by j3k0** [comment]
Right, a receipt validation server is required to properly handle subscriptions with Apple and Google, else the expiry date and renewal information are not available. I believe this is also mentioned in the API documentation, I'll see how to make this more clear.
