### ISSUE TITLE
[ANDROID] Error package com.android.billingclient.util does not exist import com.android.billingclient.util.BillingHelper;

### ISSUE THREAD

**Issue by mateusmoura** [j3k0/cordova-plugin-purchase#1107]
```
MacOS Catalina 10.15.7
```

Libs: 

```
"cc.fovea.cordova.purchase": "^10.1.1",
"@ionic-native/in-app-purchase-2": "^5.28.0",
```

When try to build in Android Studio:

![image](https://user-images.githubusercontent.com/1554427/95509138-794a9580-098a-11eb-88db-98cf986c3a74.png)

![image](https://user-images.githubusercontent.com/1554427/95508900-12c57780-098a-11eb-8840-7f8892168c1b.png)

File: android/capacitor-cordova-android-plugins/src/main/java/cc/fovea/Security.java:21:

**Comment by fabmesto** [comment]
hi, i have the same problem. how did you solve?

**Comment by p4u1d34n** [comment]
same issue :/

**Comment by calls9-mattwyld** [comment]
same here? Why was is closed?

**Comment by mwyld** [comment]
same here, I wonder why it was closed?
