### ISSUE TITLE
Using This Plugin without ionic-native wrappers

### ISSUE THREAD

**Issue by abomadi** [j3k0/cordova-plugin-purchase#1108]
i was trying to call the plugin functionality without using ionic native wrappers as iam on ionic3 and would like to use the new features / fixes like store.update() functionalities.
tried to declare const store but didn't work any idea how to call the plugin directly ?

**Comment by ratnamyadav** [comment]
Having same issue with mine. Not showing up even in `cordova.plugins` list.

**Comment by abomadi** [comment]
@ratnamyadav make sure to remove ionic wrappers then `declare const store;` this will let you call store JS methods or storekit to call native storekit functions.

**Comment by ratnamyadav** [comment]
@abomadi Should I remove all or just inapp purchase one ??

**Comment by ratnamyadav** [comment]
Thanks
