### ISSUE TITLE
[IOS] How to make the difference between 2 different users in the same app

### ISSUE THREAD

**Issue by saulstys** [j3k0/cordova-plugin-purchase#1109]
Hi,

We have an app with subscriptions and we have a problem when a user creates 2 different accounts.

**On the app**
1/ a user creates an account U1 in the app and purchase a subscription, we validate the purchase with a transaction.id T1.
In our database we assign this transaction T1 to the user U1.

2/ the same user creates a second account U2 in the app and uses the same AppStore account. If he purchases a subscription we validate the purchases with a transaction.id T2. 
In our database we assign this transaction T2 to the user U2.

We noticed that T2 has an original_transaction_id equal to T1.

It seems that all the transactions are attached to the Appstore account and not the (appstore account+user id)

Is there a way to have the transactions attached to my user id and not to the appstore account ?
we use the applicationUserName method but we don't see any difference.

**Appstore server notifications**
AppStore Connect sends the renewal notifications to our server without info regarding the buyer.

Since Apple recommends to use the original_transaction_id to link to the buyer during the server-side validation, how can i know who is the real owner of this transaction ?

Is there a way to attach a developer payload to the transactions when we purchase ?

**Comment by gregor-srdic** [comment]
perhaps you can use [applicationUsername ](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeapplicationusername) field for that ?

**Comment by saulstys** [comment]
Thanks @gregor-srdic for the answer but i already use the  applicationUsername field.

**Comment by pumpknhd** [comment]
@saulstys I'm having the same issue. I also use applicationUsername, but the second user is getting the first user's receipt (which I obviously don't want). Have you been able to solve this?

**Comment by saulstys** [comment]
@pumpknhd , Unfortunately not yet.

**Comment by gregor-srdic** [comment]
I also noticed, that "applicationUsername" is only present after purchasing the subscription and before you close and restart the app - it is not persisted in the subscription (product) on the google play, therefore it is not usable for this purpose :(

**Comment by IIVR** [comment]
@saulstys Same issue. Did you find a solution?

**Comment by j3k0** [comment]
Hello, there's no built in solution to this. Apple sends anonymized receipts that do not include any information about the purchaser, nor can you attach a custom developer payload or account id (like on android). You have to manage the link between applicationUsername and original_transaction_id on your server, picking the strategy that's adequate for your app. Some chose to allow users to share a subscription, some only allow the original purchaser to benefit, some automatically migrate the subscription to the new users (with a limit to the number of migrations), etc.
