### ISSUE TITLE
Non-Renewing Subscription

### ISSUE THREAD

**Issue by calendee** [j3k0/cordova-plugin-purchase#111]
The plugin doesn't mention non-renewing subscriptions.  These are very different than subscriptions and consumables.  How should they be handled with this plugin?

**Comment by agamemnus** [comment]
Is there such a thing for Google Play? You could handle it a few different ways.
* Make it a non-consumable and store it as a subscription in your database. When your server determines the subscription is over, send a message to the app saying the subscription is canceled -- temporarily change the non-consumable to a consumable so the user can subscribe again.
* Make it a consumable and programatically prevent new one-time subscriptions, and/or use your server to check existing subscriptions before telling your app to do the transaction.

**Comment by calendee** [comment]
There are non-renewing subscriptions for Apple.  My question isn't how to handle from my side.  Really, it's how/will the plugin work with Apple.  Does the plugin inform Apple of the type or can it handle the non-renewing subscription type when integrating with Apple.

**Comment by baronem** [comment]
+1

From Apple's [In-App Purchase Programming Guide](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Products.html#//apple_ref/doc/uid/TP40008267-CH2-SW2):

"Non-renewable subscriptions. Subscriptions that don’t involve delivering episodic content. Examples include access to a database of historic photos or a collection of flight maps. It’s your app’s responsibility to make the subscription available on all of the user’s devices and to let users restore the purchase. This product type is often used when your users already have an account on your server that you can use to identify them when restoring content. Expiration and the duration of the subscription are also left to your app (or your server) to implement and enforce."

**Comment by headshota** [comment]
Any updates on the solution for this?

**Comment by agamemnus** [comment]
Seems you just have to code it yourself.

**Comment by headshota** [comment]
My main question is, is the `store.PAID_SUBSCRIPTION` type (defined in the plugin) covering non-renewing subscriptions as well?

**Comment by agamemnus** [comment]
I'm guessing that it would probably not do anything. But that's a good clarification to your question...

**Comment by nnylip** [comment]
I have been informed by the author that the plugin does not handle non-renewing subscriptions correctly. What approach did you finally take?

**Comment by seibelj** [comment]
I made a fix here https://github.com/j3k0/cordova-plugin-purchase/pull/412

**Comment by j3k0** [comment]
The plugin non-renewing subscription support has finally been cleaned up in newly released version 6.0, for both iOS and Android. I created a [helper library for apps that just need non-renewing subscriptions](https://github.com/j3k0/cordova-non-renewing-subscription). Feel free to take a look, to use it or see how it's implemented for reference.
