### ISSUE TITLE
[Android] Cancel event behavior

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [j3k0/cordova-plugin-purchase#1110]
### system info

```
Cordova 9 
Device: Android 6.0.1 and 7
Plugin Version: 10.2.0
```

Somewhat related issue: #1051 

I want to display a loading overlay while the in-app purchase dialog is present (and do other more complex things), but with the way cancel behaves this is not currently possible.

### Steps to reproduce

**Situation 1 (good):**  
* Start a purchase
* Click outside the in-app purchase dialog
* the `store.when().cancelled` event is fired

**Situation 2 (questionable):**  
* Start a purchase
* Click the android hardware overview button or home button (so that the app becomes minimized)
* the `store.when().cancelled` event is fired (maybe ok?)
* return to the app
* The in-app purchase dialog is still present
* Click away from the in-app purchase dialog
* **the `store.when().cancelled` event is NOT fired (definitely not-so-good)**

### Observed behavior

Confusing cancel behavior

### Expected behavior

`store.when().cancelled` **ONLY** called when the in-app purchase dialog is actually cancelled.

AND (less importantly)

`document.addEventListener("pause", function () {))` triggered when the app is minimized when the in-app purchase dialog is open.

`document.addEventListener("resume", function () {))` triggered when the app is resumed when the in-app purchase dialog is open.

**Comment by mst2020** [comment]
> **Situation 2 (questionable):**
> 
> * Start a purchase
> * Click the android hardware overview button or home button (so that the app becomes minimized)
> * the `store.when().cancelled` event is fired (maybe ok?)
> * return to the app
> * The in-app purchase dialog is still present
> * Click away from the in-app purchase dialog
> * **the `store.when().cancelled` event is NOT fired (definitely not-so-good)**

I can confirm this with a little difference: (in the end its the same result: _having an canceled event fired but the iap dialog is still opened_):
1. start a purchase
2. click home button
3. nothing happens
4. return to app
5. cancelled event is fired
6. in-app purchase dialog is still there and useable
7. click anywhere else to cancel: event is *not* fired.


cordova-plugin-purchase 10.3.0
cordova-android 9.0.0
cordova 10.0.0
android 8.0.0

**Comment by mst2020** [comment]
Ok, there is some kind of a "bug".

`iabSetPurchases` is called on every app resume and this triggers the cancelled event.

The problematic line is here: https://github.com/j3k0/cordova-plugin-purchase/blob/d5589af8c449ff87428b9ae8a59abacd839bdaaf/src/js/platforms/android-productdata.js#L151

on resume this happens:

I/chromium(17394): [INFO:CONSOLE(2920)] "InAppBilling[js]: listener: {"type":"setPurchases","data":{"purchases":[]}}", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2920)
I/chromium(17394): [INFO:CONSOLE(2151)] "[store.js] DEBUG: iabSetPurchases: []", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2151)
I/chromium(17394): [INFO:CONSOLE(2151)] "[store.js] DEBUG: iabUpdatePurchases: []", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2151)
I/chromium(17394): [INFO:CONSOLE(74)] "store.when(product.id).cancelled called"
**.... iap dialog is still visible, after a click anywhere else, the real close fires:**
W/CordovaPurchase(17394): onPurchasesUpdated() -> Cancelled: USER_CANCELED: User pressed back or canceled a dialog

But "cancelled" is not called anymore.

The last line is the real cancellation of the iap dialog as processed here: https://github.com/j3k0/cordova-plugin-purchase/blob/d5589af8c449ff87428b9ae8a59abacd839bdaaf/src/android/cc/fovea/PurchasePlugin.java#L412.

It might be asked why iabSetPurchases is called after an resume?
nothing should have changed? the app/purchases/products should have their last state?

**Comment by mst2020** [comment]
@Lindsay-Needs-Sleep as a workaround you can disable queryPurchases in "onStart()" in PurchasePlugin.java.

https://github.com/j3k0/cordova-plugin-purchase/blob/d5589af8c449ff87428b9ae8a59abacd839bdaaf/src/android/cc/fovea/PurchasePlugin.java#L739

If somebody of the plugin developers could say what the idea is behind the "onStart -> queryPurchases()" trigger ... ?

`queryPurchases()` should only be executed on explicit instruction by the app.
It is executed on plugin init and that should be enough? no need to execute it every time the user "comes back" and if the app was destroyed its up to the app developer to reinitialize the purchase plugin. (its like a normal app start)

(i'm pretty sure i don't have the whole picture ... 🤔 )

Other solution, if `onStart()` is necessary, set a boolean:
`onStop() -> app_paused=true -> onStart(), if app_paused!=true -> queryPurchases()`

**Comment by rodrigograca31** [comment]
There's definitely something wrong with the `.cancel` event.....

In my case when I click it nothing happens, but when I navigate back and then forward to the same page it fires it and it fires twice... Then for each time I go back and forward it adds one more firing event.... Its very strange...

**Comment by j3k0** [comment]
Sorry I only get back to this now.

I believe querying for purchases when the app becomes active might be a recommended approach, but not strictly necessary. I actually wonder what happens if we do not do it

I think the idea is that an app can stay inactive for a while, if purchases are never refreshed someone can make sure the app is never stopped, so the status of the purchases are never updated. One can refund a purchase and enjoy it for a long time.

This won't work if we refresh the purchases in `onStart` (or the user needs to keep the android device unlocked with the app open forever).

What could be a good fix is to only `queryPurchases()` if it hasn't been in the last 24h or something. This will probably be make the other bug go away.

**Comment by tehmaestro** [comment]
Hi, I have the same issue and I am unable to update the plugin for the moment. Is it safe to comment the `product.trigger("cancelled")` ? It is the only thing I can think of doing.
