### ISSUE TITLE
ANDROID Subscription Cancellation

### ISSUE THREAD

**Issue by repotoolsapps** [j3k0/cordova-plugin-purchase#1112]
Google Play Console sen this message:

Changes to subscription settings
You must implement account suspension and restoration in your application before November 1, 2020. Additionally, pause subscriptions and re-subscribe options will be enabled by default, unless you explicitly disable them.

Please helpme to fix it. Regards.

**Comment by eliadAfeka** [comment]
Hi, I'm also wondering what is it?

**Comment by paulovargatt** [comment]
I would also like to know

**Comment by qpwr** [comment]
@j3k0 can you shed some light on this? Is this something which would need to be implemented by the app developer or by you (meaning into the plugin)?

**Comment by j3k0** [comment]
Hello, no much things to do. The important things is that your receipt validation service has real-time developer notifications setup correctly, so it gets notified when a user reactivates the subscription but doesn't open the app on an android device with google play. It's mostly important when your app works on multiple platforms.

If you're using a receipt validation service like Fovea's https://billing.fovea.cc/ - make sure real-time developer notifications are setup and you are covered.
