### ISSUE TITLE
[IOS] can switch to production 

### ISSUE THREAD

**Issue by duiliodaniele** [j3k0/cordova-plugin-purchase#1114]
hello to all I'm noob on that,
i have a problem I make an app with that library and all works fine, but I can't move out to sandbox, what I need to do to release that in production? the apple revisor say me more and more time I need to build that in production but I make that in production but the in app purchase always go to the sendbox

please help me 

regards.

**Comment by j3k0** [comment]
Is that solved? Please reopen if needed.
