### ISSUE TITLE
[IOS] 14.1 Store error

### ISSUE THREAD

**Issue by paulovargatt** [j3k0/cordova-plugin-purchase#1117]
Hi,
I'm having problems using this plugin in IOS version 14.1, after calling the "Order" method nothing happens, in other IOS versions it works normally

### system info
```
Cordova 9.0.0
Device: iPhone iOS 14.1
Plugin Version: v10.3.0
```

**Comment by arturomf** [comment]
Can you look for this error in Xcode Console?

`Found nil parameter when creating SKPaymentDiscount`

It could be related with my issue #1123

**Comment by paulovargatt** [comment]
@arturomf  After several tests on IOS testfly, we realized that when making the first purchase the app invokes the store normally by subscribing, but when the cancellation occurs and a new purchase attempt simply does nothing happens! The plugin returns the subscription already expired in the promise of "order method".

@j3k0 What to do in this situation, since in previous versions of IOS this did not happen, is it something new?
