### ISSUE TITLE
[Android] How to configure validation retries (callback mode)

### ISSUE THREAD

**Issue by distante** [j3k0/cordova-plugin-purchase#1119]
I am using a local callback function to develop the UI responses for purchases after validation.

For this I use 2 products and I always reject one and always accept the other.

When I test the rejected one it takes almost 1 minute until the `unverified` event gets called. After attach some logs, I see that the the validation callback gets called until 5 times in that minute and after the 5 time `unverified` is triggered.

Is there a way to configure the amount of retries being done?

I always get this after each fail verification
```
[PurchasesServiceIAP2][DEBUG]: verify -> {"success":false,"data":{"transaction":{"verificationResponse":{"message":"This is a local NOT validated product (id products.test_product_2)"}}}}
22:12:40.539 capacitor-runtime.js:5087 [PurchasesServiceIAP2][DEBUG]: transaction fields for com.saninnsalas.com.audiotraining.products.test_product_2
22:12:40.542 purchases.service.ts:149 [LOG]: Update of product TestProduct2 [state: approved][owned: false] (products.test_product_2) store.Product {id: "products.test_product_2", alias: "products.test_product_2", type: "consumable", group: "", state: "approved", …}
22:12:40.546 capacitor-runtime.js:5005 [PurchasesServiceIAP2][DEBUG]: verify -> error: {"transaction":{"verificationResponse":{"message":"This is a local NOT validated product (id products.test_product_2)"}}}
```

**Comment by j3k0** [comment]
The validator can tell the plugin that it's using the latest receipt, so no retry are needed.

**Comment by distante** [comment]
> The validator can tell the plugin that it's using the latest receipt, so no retry are needed.

Do you have an example for this object? As I said I just need to return it locally to be able to see the UI changes for design.

**Comment by j3k0** [comment]
Add `data.latest_receipt` = `true` to the response.

Maybe a simple way to test would be to setup an account in https://billing.fovea.cc - it's free, it shouldn't take long and you get the best possible behavior from a receipt validator battle-tested with this plugin.
