### ISSUE TITLE
Help! My products are always invalid.

### ISSUE THREAD

**Issue by siauderman** [j3k0/cordova-plugin-purchase#1121]
I have matched the ID when calling register() with the ID in Google Play, and it is still invalid.
I have also double-checked my billing key.
What am I doing wrong?
I'm sorry if this is the wrong place to ask this question but I couldn't find a support forum.

**Comment by siauderman** [comment]
Here is my code
	```
store.register({
		id:'sendall100credits_single',
		type:store.CONSUMABLE
	});
	store.register({
		id:'sendall500credits_single',
		type:store.CONSUMABLE
	});
	store.register({
		id:'sendall1000credits_single',
		type:store.CONSUMABLE
	});
	store.register({
		id:'sendall5000credits_single',
		type:store.CONSUMABLE
	});
	store.register({
		id:'sendall10000credits_single',
		type:store.CONSUMABLE
	});
	store.register({
		id:'sendall100credits_subscription',
		type:store.PAID_SUBSCRIPTION
	});
	store.register({
		id:'sendall500credits_subscription',
		type:store.PAID_SUBSCRIPTION
	});
	store.register({
		id:'sendall1000credits_subscription',
		type:store.PAID_SUBSCRIPTION
	});
	store.register({
		id:'sendall5000credits_subscription',
		type:store.PAID_SUBSCRIPTION
	});
	store.register({
		id:'sendall10000credits_subscription',
		type:store.PAID_SUBSCRIPTION
	});
	store.refresh();
```
When the updated function is called, it is always invalid.

**Comment by jorisbertomeu** [comment]
I have same issue here, my products's ids are identical between Apple and Android, it works well with iOS, but nothing with Android .. some debug logs:
```
I/Capacitor/Console: File: capacitor-runtime.js - Line 11871 - Msg: InAppBilling[js]: getAvailableProducts()
D/CordovaPurchase: queryAllSkuDetails() -> Query INAPP.
    querySkuDetailsAsync()
    executeServiceRequest() -> OK
D/CordovaPurchase: querySkuDetailsAsync() -> Success
W/CordovaPurchase: queryAllSkuDetails() -> Query returned nothing.
```
and
```
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: InAppBillingPlugin993476306, service: InAppBillingPlugin, action: getPurchases, actionArgs: ["null"]
D/CordovaPurchase: getPurchases()
    queryPurchases()
    executeServiceRequest() -> OK
I/Capacitor/Console: File: capacitor-runtime.js - Line 11102 - Msg: [store.js] DEBUG: state: edls_pack_1 -> invalid
I/Capacitor/Console: File: capacitor-runtime.js - Line 11102 - Msg: [store.js] DEBUG: state: edls_pack_5 -> invalid
I/Capacitor/Console: File: capacitor-runtime.js - Line 11102 - Msg: [store.js] DEBUG: state: edls_pack_10 -> invalid
I/Capacitor/Console: File: capacitor-runtime.js - Line 11102 - Msg: [store.js] DEBUG: state: edls_pack_25 -> invalid
I/Capacitor/Console: File: capacitor-runtime.js - Line 11102 - Msg: [store.js] DEBUG: iabGetPurchases()
I/Capacitor/Console: File: capacitor-runtime.js - Line 11871 - Msg: InAppBilling[js]: getPurchases()
I/CordovaPurchase: queryPurchases() -> Elapsed time: 9ms
I/CordovaPurchase: queryPurchases() -> Subscriptions elapsed time: 15ms
    queryPurchases() -> Subscriptions result code: 0 res: 0
D/CordovaPurchase: sendToListener() -> setPurchases
D/CordovaPurchase:             data -> {"purchases":[]}
```

Obviously, all my products are created .. I also tried to run my app with a signed release version. I added my gmail account to tester accounts ..

Thanks for your help

**Comment by jorisbertomeu** [comment]
Okay, I done nothing, but 3/4 products are working today .. Waiting after Play store update is maybe the solution ?

**Comment by siauderman** [comment]
OK I seem to have solved my problems. Once I set the Play Store APK to closed alpha instead of internal testing, I seem to be able to purchase products now.

**Comment by victorpinheiro** [comment]
I'm facing this very same problem. My products are listed on iOS device perfectly but not on Android.
I have just created the subscription products on Google Developer console. 
@jorisbertomeu would you if we wait like 24h it starts working? Or is there a more logical solution?

**Comment by j3k0** [comment]
Have this been solved? Please reopen if needed.

**Comment by harryt2** [comment]
Sorry to necro post but I think this might help some stranded person in the future. I was having the same problem and really confused for a couple of days. **On Google Play you need to hit "Apply Prices" after setting the default price so it populates all the countries. Then hit save.** I did that and it showed up about 30 mins later.
