### ISSUE TITLE
[Android] Purchase Error is not reported with the error callback when closed on Google Agreement

### ISSUE THREAD

**Issue by distante** [j3k0/cordova-plugin-purchase#1122]
### system info

Plugin version 10.3.0
Capacitor 2
Android 10

### Expected behavior
When the user does not accept google agreement for purchases the error callback should be called

### Observed behavior
The plugin register the error as a log and does not trigger the error callback. This log appears: `plugin -> buy error 6777006`

### Steps to reproduce
1. Initialize a puchase
2. when this screen appears, tap outside the container
![image](https://user-images.githubusercontent.com/5490201/97790506-58601380-1bc9-11eb-8429-28aa38348aab.png)

**Comment by j3k0** [comment]
I don't find "plugin -> buy error" in the source code of the plugin. What's the exact error you're getting? Please reopen if this problem is still unsolved (I'm doing some cleaning)
