### ISSUE TITLE
[IOS] store.refresh().cancelled() not being triggered

### ISSUE THREAD

**Issue by Cosmic-Noir** [j3k0/cordova-plugin-purchase#1125]
# system info
```
OS: Catalina 10.15.6
XCode: 12.1
Cordova-IOS: 5.1.1
Capacitor/ios: 2.4.2
Device: iphone X iOS 13.7
Plugin Version: 10.3.0
```
### Expected behavior
When store.refresh() is called and prompts the user for their password, if the user hits 'cancel', I expect store.refresh().cancelled() to trigger, and then call the callback function. 

### Observed behavior
It appears that store.refresh().finished() is triggered before the user enters their password or hits cancel. Then when I hit cancel, nothing is triggered. 

### Steps to reproduce
Revisit the page where store.refresh() is called, when it prompts you for a password, hit cancel. 

# Notes
- This is for a non-renewing subscription type
- Revisiting the page re-prompts for password, if entered, all expected behavior continues correctly

**Comment by j3k0** [comment]
Note: `refresh()` should only called in 2 cases.

When the app starts, then there's no password prompt: except when running from XCode, but it's a special case, and then we get no feedback about user doing cancel. So for this initial refresh, there's no `finish()` or `cancel()` calls.

When the user hits a `Restore Purchases` button. In which case, cancel should get called, but there's apparently an issue in that regard. This is not reliable.

Do not call `refresh()` when entering a page, you can call `update()` if you just want to update the price for things the user can purchase.

**Comment by viktorzavadil** [comment]
> Note: `refresh()` should only called in 2 cases.
> 
> When the app starts, then there's no password prompt: except when running from XCode, but it's a special case, and then we get no feedback about user doing cancel. So for this initial refresh, there's no `finish()` or `cancel()` calls.
> 
> When the user hits a `Restore Purchases` button. In which case, cancel should get called, but there's apparently an issue in that regard. This is not reliable.
> 
> Do not call `refresh()` when entering a page, you can call `update()` if you just want to update the price for things the user can purchase.

I am sorry, it's a little bit off-topic but very similar.

Why initial refresh does not trigger finish? Is this somewhere documented? I have tried to wrap the refresh method into Promise API because I was trying to implement lazy initialization of the store. We don't want to interrupt a user with Apple store login dialog if it's not wanted.

Thank you for the reaction.

**Comment by j3k0** [comment]
> Why initial refresh does not trigger finish?

Internally, iOS's `restorePurchases` has a "completed" callback. That's what subsequent calls to `refresh()` do. The first call to `refresh()` have no completion callback, but you can wait for `store.ready()`.

Apple recommends to always initialize the store as soon as the app starts, to pick-up potential purchases made from outside the app for example. As explained before: this never asks for the user password (store login dialog), so there's no reason not to do it.

**Comment by viktorzavadil** [comment]
> > Why initial refresh does not trigger finish?
> 
> Internally, iOS's `restorePurchases` has a "completed" callback. That's what subsequent calls to `refresh()` do. The first call to `refresh()` have no completion callback, but you can wait for `store.ready()`.
> 
> Apple recommends to always initialize the store as soon as the app starts, to pick-up potential purchases made from outside the app for example. As explained before: this never asks for the user password (store login dialog), so there's no reason not to do it.

Thank you for your response.

It's strange because I think application has wanted to log in to Apple store after initialization and it has been installed from TestFlight.

When exactly is `store.ready()` called? After store initialization and after download all products to app?

**Comment by j3k0** [comment]
> When exactly is store.ready() called? 

When all product metadata have been loaded (price, title, description, ...) and the purchases status is finalized (all product are either `owned` or `[in]valid`).

**Comment by gesrt** [comment]
> > When exactly is store.ready() called?
> 
> When all product metadata have been loaded (price, title, description, ...) and the purchases status is finalized (all product are either `owned` or `[in]valid`).

I found unusual situation in my case.
1. The `store.ready()` will be called immediately in Android. so I can't get correct purchases status. On the contrary. the `refresh().finished()` will be called after the purchases status is finalized
2. The `store.refresh()` callback is not be triggered in iOS.  The `store.ready()` will be called after all status is finalized

I cannot understand this logic.
