### ISSUE TITLE
$BILLING_KEY doesn't seem to stick? 3.6.3.

### ISSUE THREAD

**Issue by agamemnus** [j3k0/cordova-plugin-purchase#113]
I'm not entirely sure what's going on but adding the billing key variable somehow isn't populating the public key field and leaves it as $BILLING_KEY. Using Cordova 3.6.3.

Related: https://github.com/poiuytrez/AndroidInAppBilling/issues/88

**Comment by ayaka209** [comment]
+1

**Comment by sullivanpt** [comment]
Don't know if y'all are having the same issue, but I was able to get my billing key to stick between builds by manually editing the plugins/android.json file line
```
                            "xml": "<string name=\"billing_key_param\">PUT MY KEY HERE</string>",
```
I think it was supposed to set automatically when I installed the plug in, but it didn't configure correctly in my use case (I had already installed the plugin, before I ran 'platform add android')

**Comment by Fortuitous** [comment]
@sullivanpt Hi Patrick!  Fancy meeting you here.  
Any chance you might have some wisdom regarding #147?  I'm trying to get around a similar bug -- #103 -- but don't believe I can edit the files since I'm using phonegap build.  

Anyway -- nice to "see" you.  :)

**Comment by rahmadid** [comment]
Hi, for those of you who experience crash after purchase related to billing key, please install the plugin from the git address. Don't install from plugin registry, it seems that the registry hasn't been updated with the latest code. It just works, I don't have to do any manual code changes. Hope that helps.
