### ISSUE TITLE
Purchases listener for purchases outside app and promo code

### ISSUE THREAD

**Issue by hooliapps** [j3k0/cordova-plugin-purchase#1132]
Hello,

I have the following problem, when user purchase subscription outside app, or use a Voucher code inside app, then there is no Listener who treat the purchases.

The only way in this case is that the user click on Restore purchases.

Do you know how i can manage this please ?

**Comment by j3k0** [comment]
It's probably because you're not setting up your event listeners at app startup. It's mentioned in the documentation.
