### ISSUE TITLE
[Android]Receipt Validation is not working Ionic3

### ISSUE THREAD

**Issue by JeetuChoudhary** [j3k0/cordova-plugin-purchase#1133]
### system info
```
cli packages: (C:\nvm\v10.15.1\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.10

System:

    Android SDK Tools : 26.1.1
    Node              : v10.15.1
    npm               : 6.4.1
    OS                : Windows 10

Device: MI K20 pro // Android 10
```

### Expected behavior
I am implementing subscription and when Payment is successful and after the validator is called it should validate the receipt and Owned status should turn true. I am using [Receipt Validator Fovea](https://billing.fovea.cc/) for subscription receipt validation. 

### Observed behavior
Purchase is working fine if I don't validate it. But, the Receipt validator is not working and failing with the following error.

```

Access to XMLHttpRequest at 'https://validator.fovea.cc/v1/validate?appName=AppNameHere&apiKey=Key here from origin 'http://192.168.0.110:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
store-android.js:1555 [store.js] WARNING: ajax -> request to https://validator.fovea.cc/v1/validate?appName=AppName&apiKey=API Key failed with status 0 ()
store-android.js:1555 [store.js] DEBUG: validator failed, response: "Error 0: "
store-android.js:1555 [store.js] DEBUG: body => undefined
store-android.js:1555 [store.js] DEBUG: verify -> {"success":false,"data":"Error 0: "}
store-android.js:1555 [store.js] DEBUG: verify -> error: "Error 0: "
store-android.js:1555 [store.js] DEBUG: validation failed, no retrying, trigger an error
 
```
To resolve it I followed the step mentioned in [Fovea Receipt Validator](https://billing-dashboard.fovea.cc/setup/cordova/). I added the following code in my index.html file:

```
<meta http-equiv="Content-Security-Policy"
  content="default-src 'self' 'unsafe-eval'; connect-src https://validator.fovea.cc; style-src 'self' 'unsafe-inline'; media-src *">
```
but Adding it breaks all my application's server request with the following error :

```
Refused to connect to 'Every request URL to server' because it violates the following Content Security Policy directive: "connect-src https://validator.fovea.cc"
```

I have also tried the Cordova whitelist and added all these variations in my config.xml but none of these things works.
```
 <access origin="*" />
    <allow-intent href="*" />
    <allow-navigation href="*" />
    <allow-navigation href="http://ionic.local/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="*" />
    <access origin="https://validator.fovea.cc" />
    <allow-navigation href="https://validator.fovea.cc/*" />
    <allow-intent href="https://validator.fovea.cc/*" />
    <allow-intent href="http://localhost/*" />
    <allow-navigation href="http://192.168.0.110:8100/*" />
    <allow-navigation href="http://localhost" />
```
Any Help will be appreciated.

**Comment by jkainth** [comment]
@JeetuChoudhary any luck with this? I'm running into the same issue.
Fovea breaks due to CORS.

**Comment by jkainth** [comment]
Resolved it. Incase someone else runs into the same.
The content security policy did not work for me.

To make it work:
- Instead of using the Validator as a Fovea url, created a function instead
- installed the native http cordova plugin
- in the validator function, call the Fovea url as a http post via the native http plugin

The native http plugin does not enforce CORS like the browser http client injected by Ionic.
I intend to use the native http just for this one call; the rest of the app can keep using the browser http.

J

**Comment by hooliapps** [comment]
Hello,

For me, FOVEA work correctly, but i put this in index.html
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' https://validator.fovea.cc https://api.hooliapps.com https://*.dropboxapi.com https://www.dropbox.com 'unsafe-inline' mailto:* data: gap: https://ssl.gstatic.com https://*.dropboxapi.com https://www.dropbox.com 'unsafe-eval'; connect-src * 'self' https://validator.fovea.cc https://api.hooliapps.com https://*.dropboxapi.com https://www.dropbox.com; style-src * 'self' 'unsafe-inline'; media-src *; script-src https://*.dropboxapi.com https://www.dropbox.com 'self' 'unsafe-inline' 'unsafe-eval'" />

**Comment by jkainth** [comment]
@hooliapps  Ill have to give your meta a try, mine was similar but didnt put fovea in the default-src, only in connect-src.

**Comment by JeetuChoudhary** [comment]
Hello @jkainth , What are you returning from the functions for the validator.

**Comment by JeetuChoudhary** [comment]
@hooliapps  your solution did work for me also.

**Comment by gatelli** [comment]
@jkainth could you write your code with the http plugin? Thx...
