### ISSUE TITLE
[iOS] Returning Application Object instead of Only Products

### ISSUE THREAD

**Issue by farisfaisalthena** [j3k0/cordova-plugin-purchase#1138]
# [iOS] Returning Application Object
Everytime after making a purchase I will get more objects returning instead of only three items that was created in App Store Connect. I am using Angular for this and the code as below. I am new to this so any help in the slight change in code is highly appreciated .

```
products: IAPProduct[] = [];

  constructor(
    private plt: Platform,
    private store: InAppPurchase2,
    private ref: ChangeDetectorRef,
    private toastCtrl: ToastController,
  ) {
    this.isCapacitor = this.plt.is('capacitor');
    if (this.plt.is('capacitor')) {
      this.plt.ready().then(() => {
        // this.store.verbosity = this.store.DEBUG; // Used to DEBUG for any issue
        // Initialize
        this.registerProducts();
        this.setupListeners();
        // When store ready keep track
        this.store.ready(() => {
          this.products = this.store.products;
          // Detect Changes for FrontEnd
          this.ref.detectChanges();
        });
      });
    }

  }

  registerProducts() {
    // Small Tips
    this.store.register({
      id: KIND_TIP,
      type: this.store.CONSUMABLE
    });
    // Medium Tips
    this.store.register({
      id: NICE_TIP,
      type: this.store.CONSUMABLE
    });
    // Large Tips
    this.store.register({
      id: GENEROUS_TIP,
      type: this.store.CONSUMABLE
    });
    // Refresh IAP
    this.store.refresh();
    
  }

  setupListeners() {
    this.store.when('product')
      .approved((p: IAPProduct) => {
        // TODO Add Checking
        // Detect Changes for FrontEnd
        this.ref.detectChanges();
        // Veify Purchase
        return p.verify();
      })
      .verified((p: IAPProduct) => {
        p.finish()
      });
      this.store.refresh();
  }

  async purchase(product: IAPProduct) {
    this.store.order(product).then(p => {
      // Purchase in Progress
    }, e => {
      this.showToastMessage(`Failed to purchase: ${e}`, 'danger');
    });
  }
```

### Expected behavior
Only show the In app Purchase Products

### Steps to reproduce
N/A

**Comment by j3k0** [comment]
First of all, you shouldn't call `this.store.refresh();` from `registerProducts`. It shoud only be called once, after you have both registered products and added your event handlers.

Then, I don't fully understand what you mean by _I will get more objects returning instead of only three_? Can you elaborate?

**Comment by farisfaisalthena** [comment]
Hi. alright so I only need to remove the refresh from my register product only right? What i meant is that I only have 3 IAP items so thats what i meant

**Comment by j3k0** [comment]
That's for sure. Note that on iOS, there's an implicit product created that has the app bundle id has `id` and type `application`. Might be what you're seeing as a 4th item? Closing for now, feel free to reopen if the issue persists.

**Comment by farisfaisalthena** [comment]
hey there, i removed in on  registerProducts and added on `this.store.ready(() => {
          this.products = this.store.products;
          // Detect Changes for FrontEnd
          this.store.refresh(); 
          this.ref.detectChanges();
        });` but i still have the 4th item which is the app bundle. Any idea how i can just filter them out? i tried so many solutions and still failed :(

**Comment by farisfaisalthena** [comment]
This is the current code

`products: IAPProduct[] = [];
  
  constructor(
    private modalCtrl: ModalController,
    private plt: Platform,
    private store: InAppPurchase2,
    private ref: ChangeDetectorRef,
    private toastCtrl: ToastController,
  ) {
    this.isCapacitor = this.plt.is('capacitor');
    if (this.plt.is('capacitor')) {
      this.plt.ready().then(() => {
        this.store.verbosity = this.store.DEBUG; // Used to DEBUG for any issue

        this.registerProducts();
        this.setupListeners();
        this.store.refresh();

        this.store.ready(() => {
          this.products = this.store.products;
          this.ref.detectChanges();
        });
      }); 
    }
  }

  registerProducts() {
    // Small Tips
    this.store.register({
      id: KIND_TIP,
      type: this.store.CONSUMABLE
    });
    // Medium Tips
    this.store.register({
      id: NICE_TIP,
      type: this.store.CONSUMABLE
    });
    // Large Tips
    this.store.register({
      id: GENEROUS_TIP,
      type: this.store.CONSUMABLE
    });
  }

  setupListeners() {
    this.store.when('product')
      .approved((p: IAPProduct) => {
        // TODO Add Checking
        this.ref.detectChanges();
        // Verify Purchase
        return p.verify();
      })
      .verified((p: IAPProduct) => {
        if (p.state == 'approved') {
          if (p.id == 'kind_tip') {
            this.showToastMessage('Thank you for the Kind Tip!', 'success');
          } else if (p.id == 'nice_tip') {
            this.showToastMessage('Thank you for the Nice Tip!', 'success');
          } else if (p.id == 'generous_tip') {
            this.showToastMessage('Wow! Thank you for being so GENEROUS!', 'success');
          }
        }
        p.finish()
      });
  }`
