### ISSUE TITLE
Set group and other params product

### ISSUE THREAD

**Issue by Bond1768** [j3k0/cordova-plugin-purchase#1140]
The question applies to all platforms, OS and versions. Not important.
How can I set a group for PAID_SUBSCRIPTION?
During registration, I cannot do this
`this.iap2.register([{
                id: 'my_id_subs',
                alias: 'al',
                type: this.iap2.PAID_SUBSCRIPTION,
            }]);`
           Possibly after registration
`const sms = this.iap2.get('my_id_subs');
sms.group = 'for exemple group';
this.iap2.order(sms).then((p) => {
            }).catch((e) => {
        });`
But is it right to do this?

**Comment by j3k0** [comment]
Hello, you can setup a group at registration:

```js
 this.iap2.register([{ id: 'my_id_subs', alias: 'al', type: this.iap2.PAID_SUBSCRIPTION, group: 'my_group' }]);
```

Also note that when no groups are set, all subscriptions are assumed to be part of the same group (called `default`).

**Comment by Bond1768** [comment]
> Hello, you can setup a group at registration:
> 
> ```js
>  this.iap2.register([{ id: 'my_id_subs', alias: 'al', type: this.iap2.PAID_SUBSCRIPTION, group: 'my_group' }]);
> ```
> 
> Also note that when no groups are set, all subscriptions are assumed to be part of the same group (called `default`).


Thanks, but typing doesn't allow for this. Specifically interface IAPProductOptions
I will be grateful if you can help with one more question. How to check if a user is logged in Play Market or App Store?

**Comment by j3k0** [comment]
ionic typings are incomplete. Until this is fixed, you can use:

```js
// @ts-ignore
 this.iap2.register([{ id: 'my_id_subs', alias: 'al', type: this.iap2.PAID_SUBSCRIPTION, group: 'my_group' }]);
```

**Comment by j3k0** [comment]
> How to check if a user is logged in Play Market or App Store?

Do you mean, "is the device running Android or iOS"?

**Comment by Bond1768** [comment]
> > How to check if a user is logged in Play Market or App Store?
> 
> Do you mean, "is the device running Android or iOS"?

no, I mean checking if the user is logged in, for exemple, to a Google account - because now if the user is not logged in, then nothing happens when I call `this.iap2.order`.
I want to open a popup if the user is not logged into google account.

**Comment by Bond1768** [comment]
Sorry, could you help me with the above question?

**Comment by j3k0** [comment]
If the user is not logged in, the data about the product is probably unavailable, so `product.canPurchase` is probably false, which mean you shouldn't let the user press the Buy button which calls the `store.order()` function. Does this help?

**Comment by Bond1768** [comment]
> If the user is not logged in, the data about the product is probably unavailable, so `product.canPurchase` is probably false, which mean you shouldn't let the user press the Buy button which calls the `store.order()` function. Does this help?


Thank you very much for your help, this is exactly what I need.
