### ISSUE TITLE
[iOS] Upgrade from 10.3 to 10.5 causes build to fail

### ISSUE THREAD

**Issue by HarelM** [j3k0/cordova-plugin-purchase#1143]
### system info
 When building on macOS in appveyor the build fails adter upgrading from 10.3 to 10.5.
Build log can be found here:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/job/08nkveyi6qjehaq3

### Expected behavior
There should not be a build failure only due to version upgrade of the plugin

### Observed behavior
Build fails on CI server but seems to work on my dev env, not sure my dev env is fully up to date but I've tried to build this twice and it failed in both runs in the CI server.

### Steps to reproduce
See if you can understand what's wrong from the build log.
If not I can try and create a minimal reproduction but I'm guessing this is something simple to solve...

**Comment by HarelM** [comment]
Seems like the CI server is running XCode 11 and therefore the build fails.
Not sure if this is something that worth fixing in this plugin, I'm not sure what is the support requirements for old XCode environment...
I have opened an issue with the CI here:
https://github.com/appveyor/ci/issues/3542

**Comment by j3k0** [comment]
Hello, just checked your CI status logs, it seems like it's solved now?

**Comment by HarelM** [comment]
Yup, seems like this was fixed by the CI vendor.
Feel free to close this issue and/or add this requirement to the release notes of 10.5.0.

**Comment by j3k0** [comment]
Yes, that's probably the addition of `store.redeem()` for iOS 14.0 that causes build issue on "older" XCode. The call to StoreKit's `presentCodeRedemptionSheet` didn't exist before. That slipped through in the release notes.
