### ISSUE TITLE
No visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'

### ISSUE THREAD

**Issue by j4hangir** [j3k0/cordova-plugin-purchase#1144]
The compilation in our build fails with:

```InAppPurchase.m:326:40: error: no visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'```

**Comment by j4hangir** [comment]
I'm also not sure whether this is a warning or an actual error!

**Comment by korsgaard** [comment]
Got the same error, couldn't compile... Commented the line out in the code since I didn't use the feature...

**Comment by j4hangir** [comment]
Also worth mentioning, using the latest XCode seems to bypass this, the project compiled successfully. I didn't investigate further.

**Comment by j3k0** [comment]
You need the latest XCode, because this is a new feature for iOS 14.0

The release notes did mention the new requirement. If you can't use a recent XCode, you have to stick to an older version of the plugin.
