### ISSUE TITLE
[ANDROID] Deleted/expired subscriptions remain active on second device

### ISSUE THREAD

**Issue by websystems-dev** [j3k0/cordova-plugin-purchase#1145]
OS: Windows 7
Cordova 8.1.2
Device(s): Android 10 (and/or Android 11) on Emulator
Plugin Version: 10.5.1

### Expected behavior
When an auto-renewing subscription is paused or deleted via Google Play (https://play.google.com/store/account/subscriptions) or expires, all user's devices should get from the plugin the same values, telling the subscription is no longer active (owned=false)

### Observed behavior
The "main" device (where the user bought the subscription) works fine: the previously actived subscription is no longer owned (owned=false) and I can re-purchase if I want,
The "secondary" device continues to get **owned=true** and this is simply wrong.

### Steps to reproduce
1) In two different devices, the same user logs in to Google with the same Google Account (I'm using a test account and I run 2 instances of Android Emulator).
2) In a first device (let's call it "main device") the user runs my app (compiled in debug mode) then he buys an in-app product (an auto-renewable subscription).
3) Now, when the buy process is complete, both devices get the owned=true value for this product, and this is OK. 
The subscription is now correctly active in the app on both devices.
4) The user goes to https://play.google.com/store/account/subscriptions (using a desktop browser, outside the emulators) and delete (or pause) the purchased subscription (OR waits for the subscription to expire)
5) The user closes and reopens my app on both devices. On startup the apps call store.refresh() as usually.
- on the "main device" the plugins returns correct data, i.e: subscription _not_ owned:
```
additionalData: null
canPurchase: true
loaded: true
owned: false
state: "valid"
transaction: null
trialPeriod: null
trialPeriodUnit: null
type: "paid subscription"
valid: true
...
```
- on the "secondary device" I always get different (wrond) data (I'm pasting here just the values that are different from above):
```
acknowledged: true
canPurchase: false
owned: true
renewalIntent: "Renew"
state: "owned"
transaction: {type: "android-playstore", id: "GPA.****", purchaseToken: "****", purchaseState: 0, developerPayload: undefined, …}
```
As you can see, data returned are different between apps.
Recap: the plugin is returning different values in 2 different devices where: 
- app is the same (same build, same version, same plugins, same .APK)
- google user account is the same
- the purchased/queried product is the same (an auto-renewable subscription)
- under "subscriptions" inside the Play Store app, the subscription is correctly marked as expired

Tests I made:
- Uninstalling and reinstalling the app does not change this behavior.
- Restarting the device does not affect this behavior.
- Logging out from Google Account (on the "secondary device") and logging-in again, solves the wrong behavior, like a "refresh" on the status of the product.

I'm not using any type of validation for the receipt and I don't want to. For now I don't care about spoofing or hacking. I just would like to get real/correct values after calling store.refresh() and trust the response on every device for the same user.

I did not test this on IOS (yet).

So it seems that the status of the purchase is not "propagating" on all devices, but only in the "main" one, where the user initially purchased the product. On the secondary device, the "owned" status seems to not correctly update.
Is this a bug or am I missing somewhat?

**Comment by j3k0** [comment]
Hello,


Cancellations are only being notified once (in your case, this happened on your main device). That's why you generally need a central server when you maintain the status of subscriptions.

A receipt validation server is pretty much required to manage subscriptions, that's how you can maintain the status of your user subscriptions, get server-side notifications for renewal and cancellations, etc. It'll become absolutely necessary if you want you user to use a subscription across different devices (with different OSes).

On iOS, there's no way around it: you will get a subscription as owned (because there's a transaction for it), but the expiry date for the subscription is only available server-side... so there's no way to tell that it's expired except by asking apple.

Without this in place, you have to live with plenty of edge cases not properly handled. Receipt validation isn't only about hacking.


You can test if things work properly by opening a free account on https://billing.fovea.cc

**Comment by websystems-dev** [comment]
Thanks so much for your reply.
I finally decided to implement a verification server, but I'm stuck on another similar problem about "synchronization" between devices: 
1) I buy a subscription on device A. Subscription is active and verified with token XX. Everything is OK.
2) I wait for the subscription expiration. Now the verification says token XX is not longer a valid subscription. Everything is OK
3) I buy again the same prod./subscription on device B, I can verify the new token YY and everything is OK.
4) Now I open again **device A** and call the refresh(), and here comes the problem: the token returned by plugin (and sent to my server for verification) is NOT the new token YY, because the app keeps getting from the plugin (in the product object) the _old_ token XX (no longer valid!) so the verification result is correctly negative.

So it seems again that somewhat is not updating the product data (also the Order-ID and other data are "old") and the app is unable to get "fresh" purchase's data. Is there some cache used by the plugin? Is Android not updating/refreshing? There is a known (or documented) delay in the "propagation"?
(Note: the device itself "knows" that there is again an active subscription: I can see the details inside Play Store app, but the app doesn't)
Thanks again.

**Comment by websystems-dev** [comment]
I add something I discovered, that can be useful. When the subscription is actually active (step 4 in my previous post) if the user try to re-buy the active subscription on device A hes get the Android popup saying it's not possible to buy because he owns the subscription yet (correct behavior).
After this attempt, calling again store.refresh() seems to "refresh" the purchase data, so the token become the new/correct one, and the transaction can be successfully verified.
However I don't think I can follow this strategy in production, i.e. I cannot force the user to "try to tap buy again" just for the purpose of restoring its active subscriptions.

**Comment by j3k0** [comment]
AFAIK, the plugin itself doesn't do any caching of the purchaseToken. What
you get is the token returned by Google Billing library. However, Google do
document that they do cache the purchase information.

In production, the subscription duration is counted in days (not in
minutes, like in sandbox)... which I believe should solve the caching
issue. Obviously, no one is constantly switching device to purhcase once in
one device, then a few minutes later from the other device. You can try by
opening the app the next day (to ensure it's a caching issue).


Anyway, the recommended implementation is to call `store.update()` when
entering the "Subscription" screen. If I'm correct, on Android, it should
do a refresh of the purchase token. If you do that, I think the issue
should be gone.
