### ISSUE TITLE
[IOS] [MacOS] Compilation error

### ISSUE THREAD

**Issue by hooliapps** [j3k0/cordova-plugin-purchase#1146]
Hello

I use last version of plugin and i get the following errors (when i build app in XCode for MacOS). Everything is ok for iOS/Android/Windows.

1.
/Users/alex/Desktop/planningify/ios/release/platforms/ios/Planningify/Plugins/cordova-plugin-purchase/InAppPurchase.m:495:52: 'transactionReceipt' is unavailable: not available on macCatalyst

2.
/Users/alex/Desktop/planningify/ios/release/platforms/ios/Planningify/Plugins/cordova-plugin-purchase/InAppPurchase.m:326:40: No visible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'

3.
gethostuuid' is deprecated: first deprecated in iOS 5.0 - gethostuuid() is no longer supported

This was solved by changing sqlite3.c

https://stackoverflow.com/questions/21969774/gethostuuid-depreciated-with-sqlite-sqlcipher-ios/21978851

static int proxyGetHostID(unsigned char *pHostID, int *pError){
    assert(PROXY_HOSTIDLEN == sizeof(uuid_t));
    memset(pHostID, 0, PROXY_HOSTIDLEN);

#if defined(__MAX_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED<1050
    {
        static const struct timespec timeout = {1, 0}; /* 1 sec timeout */
        if( gethostuuid(pHostID, &timeout) ){
            int err = errno;
            if( pError ){
                *pError = err;
            }
            return SQLITE_IOERR;
        }
    }
#else
    UNUSED_PARAMETER(pError);
#endif

#ifdef SQLITE_TEST
    /* simulate multiple hosts by creating unique hostid file paths */
    if( sqlite3_hostid_num != 0){
        pHostID[0] = (char)(pHostID[0] + (char)(sqlite3_hostid_num & 0xFF));
    }
#endif
    return SQLITE_OK;
}

**Comment by j3k0** [comment]
1. From `InAppPurchase.m:495`

```objc
#if TARGET_OS_IPHONE
  transactionReceipt = [[transaction transactionReceipt] base64EncodedStringWithOptions:0];
#endif
```

2. From `InAppPurchase.m:326`

```objc
#if TARGET_OS_IPHONE
    if (@available(iOS 14.0, *)) {
        [[SKPaymentQueue defaultQueue] presentCodeRedemptionSheet];
    }
#endif
```

With the pre-processor blocks `#if TARGET_OS_IPHONE`, the code inside is supposed to be only compiled when targeting iOS.

Are you sure you are using the `osx` platform on cordova when building for Mac, or trying to build the ios version but targeting macOS? The first option works for me. Also make sure you have the latest XCode.

Note (about point 1) that we've kept `transactionReceipt` to keep compatibility with iOS 6 devices, but I guess it might be time to get rid of this now anyway.


Concerning point 3, I don't find any reference to sqlite3.c in the plugin, are you sure this is related?

**Comment by hooliapps** [comment]
Hello

Effectively, i checked iOS iPad and MacOS.

I will try to check only MacOS.

Sorry, my fault for the point 3, it was caused by Sqlite plugin.

**Comment by j3k0** [comment]
You need to generate the XCode project with `cordova platform add osx` then `cordova prepare osx`, the project will be in `platforms/osx`
