### ISSUE TITLE
[Android] Make sure you’ve integrated your app with the Google Play Billing Library with promotions

### ISSUE THREAD

**Issue by D-Marc1** [j3k0/cordova-plugin-purchase#1150]
I get the following error: "Make sure you’ve integrated your app with the Google Play Billing Library", when I try to add promotions on Google Play. Is this a bug with this plugin?

**Comment by j3k0** [comment]
The plugin is integrated with Google Play Billing Library version 3 (assuming you're using the latest version).

**Comment by D-Marc1** [comment]
My apologizes. This was a random problem I had with Google Play. I waited the next day and it was resolved. I forgot about this issue I opened.

Anyway, thank you so much for this awesome plugin! You’re a lifesaver!
