### ISSUE TITLE
Help: How to use with typescript

### ISSUE THREAD

**Issue by ajmurmann** [j3k0/cordova-plugin-purchase#1151]
This is the first time I am using a Cordova plugin and TypeScript together. Sorry if this is a stupid question!

I am trying to get the[ non-consumable iOS example](https://purchase.cordova.fovea.cc/use-cases/non-consumable-ios) to work with TypeScript. I added the following to my code to have the `store` value on `window`:

```
declare global {
    interface Window {store: IStore}
}
```

Unfortunately I am uncertain how to import the definition of IStore correctly. Looking at `index.d.ts` lead me to think I should be able to do something like `import {IStore} from 'IapStore', but that's not working since the module `IapStore` cannot be found.

Thank you! Any help is highly appreciated!

**Comment by j3k0** [comment]
I actually never used the plugin with typescript. The typings were made by a contributor.

Here's what worked for me on a minimal project:

```ts
// index.ts
import 'cordova-plugin-purchase';

store.refresh();
const x:IapStore.StoreProductType = 'non consumable';
```

```sh
$ tsc index.ts
```

Worked.
