### ISSUE TITLE
[IOS] Npm package in-app-purchase2 store product canPurchase is false for expired subscription products

### ISSUE THREAD

**Issue by sahalshn** [j3k0/cordova-plugin-purchase#1154]
I have two auto-renewable subscription plans, While testing using a sandbox account I can purchase, and then I will cancel from the Manage option in the sandbox account. Once the plan is expired store product field "canPurchase" is should be true right?. But it is not happening. 

Versions 
```
@ionic-native/in-app-purchase-2 : "^4.20.0"
@angular/core : "5.2.11"
cc.fovea.cordova.purchase : 10.1.1

Ionic:

   Ionic CLI          : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.2.0, (and 30 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/litebreeze/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.4.0 (/usr/local/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 12.4 Build version 12D4e
```

**Comment by j3k0** [comment]
It should.

Are you using Android or iOS? Did you fully restart the app? Do you call "store.refresh()" when the app starts?

**Comment by sahalshn** [comment]
@j3k0 I am using both IOS and Android, Issue is in the IOS sandbox environment. If I bought a monthly plan and canceled the plan from the manage option, then the product's canPurchase filed is not getting true even after the plan is expired.

**Comment by j3k0** [comment]
Do you have a receipt validation server setup that correctly returns the expiry date? A receipt validation service is required to properly handle subscriptions. You can try with our service https://billing.fovea.cc/ for free, if you want.

**Comment by sahalshn** [comment]
Yes, I have my own validation server and it is returning the expiry date. Once we purchased any auto-renewable plan, can't we subscribe again to the same plan after it is expired? ( Subscription is canceled from sandbox manage option )

**Comment by j3k0** [comment]
Yes you can subscribe again once it's expired. There's probably an issue with either your code or receipt validation server, because resubscribe works fine.

**Comment by sahalshn** [comment]
@j3k0 I have updated my first comment with ionic info. If I don't wish to validate the receipt and call the store.finish() after a successful purchase, is that okay? If yes, after a monthly plan is expired in a sandbox environment, still canPurchase flag is false.

**Comment by bhaskar-se** [comment]
@sahalshn man I'm having the exact same issue..! can you please tell me if you've found any solutions or ne fixes?

This is happening on second time purchase, after cancelling it from sandbox account or auto expiry after 6 attempts.

It's showing me the status of the product is approved and canPurchase is false. But if I try to re-subscribe from sandbox account then there's no issue with it, it's getting subscribed.

Also, strangely I can not even purchase other products too. It's saying product status is registered but canPurchase is false (for other products)

@j3k0 Please help me. I've mentioned this issue on #448 which is kind 'a different issue.

**Comment by sahalshn** [comment]
@bhaskar-se Please use https://billing.fovea.cc/ for verifying receipt and you can check the response that is coming from the https://billing.fovea.cc/ . Then if you need you can use your own validation with the same format received from https://billing.fovea.cc/

**Comment by bhaskar-se** [comment]
@sahalshn Can you please do me a favor? Please tell me how the validation response format is responsible for this issue?

If I'm using the custom validator n I'm just setting the response manually. 

`store.validator = function(product, callback) {
   if (webServiceRes.isValid) {
      callback(true, { ... transaction details ... })   
   }
   else {
      callback(false, "Impossible to proceed with validation")
   }
})`

Then what's the purpose of having exact response format. Or is it something related to transaction details?

I'm really lost! 😕

**Comment by sahalshn** [comment]
@bhaskar-se I don't have time to detail the step. Better please implement the above receipt verification service and watch their API response.  
`this.store.validator =  your fovea api`

**Comment by bhaskar-se** [comment]
@sahalshn Thanks man! But that's not in my hand, it's not possible to use the fovea api in my app.

I would be happy if anyone else help me with this issue.
