### ISSUE TITLE
[IOS] order() after expiring doesn't work without uninstalling the app first

### ISSUE THREAD

**Issue by OrthoCube** [j3k0/cordova-plugin-purchase#1155]
### system info

OS: macOS, Big Sur
Cordova: 10.0.0
Device: iPhone 8, iOS 14.2
Plugin Version: 10.5.3

### Expected behavior

Calling `store.order(...)` should always present the iOS purchase dialog as long as the product is available for purchase.

### Observed behavior

We are developing an application that uses Ionic (Angular) and Capacitor together with cordova-plugin-purchase to offer subscriptions (monthly and yearly). Purchases work perfectly on Android. However, on iOS, while the first purchase works fine, after that purchase expires (via cancelling the subscription, since it is actually automatically renewing) and the user purchases any product again (now on valid status since it expired already), calling the `order()` function does not do anything. The product status remains valid, no logs are written in the JavaScript console, nor Xcode. No errors, too. We have verified that our verification servers are returning correct responses. However, when we uninstall the app and install it from Xcode again, purchases start working again, and calling the `order()` function does show the purchase dialog again, and things work as expected. Until the subscription expires and they try to purchase again.

However, if the product is not yet expired, and the user tries to change subscription by subscribing to another subscription type, calling the `order()` function works as expected. It is only when a subscription expires, and then it starts to not work until the application is deleted/uninstalled and then installed again.

We implement the purchase using pretty standard code--we tried as minimal as possible to make it simple.

## Initialization

We're trying to use the simplest code as possible.

```
    this.store.validator = 'https://xxxxxxxx/api/app/purchased';

    this.store.register([
      {
        type: this.store.PAID_SUBSCRIPTION,
        id: this.YEARLY_SUBSCRIPTION
      },
      {
        type: this.store.PAID_SUBSCRIPTION,
        id: this.MONTHLY_SUBSCRIPTION
      }
    ]);

    this.subscriptions.add(
      this.status.userData.subscribe(ud => {
        this.user = ud;
        this.store.applicationUsername = ud.id.toString(10);
      })
    );

    this.store.when(this.YEARLY_SUBSCRIPTION)
      .cancelled(this.purchaseCancelled)
      .updated(this.purchaseYearlyUpdated)
      .approved(this.purchaseApproved)
      .verified(this.purchaseVerified)
      .owned(this.purchaseOwned);

    this.store.when(this.MONTHLY_SUBSCRIPTION)
      .cancelled(this.purchaseCancelled)
      .updated(this.purchaseMonthlyUpdated)
      .approved(this.purchaseApproved)
      .verified(this.purchaseVerified)
      .owned(this.purchaseOwned);

    this.store.error(this.handleError);

    this.store.autoFinishTransactions = true;

    this.store.refresh();
```

Other functions:

```
   purchaseCancelled = (p: IAPProduct) => {
    console.log(`${ p.id } cancelled`);
  }

  purchaseYearlyUpdated = (p: IAPProduct) => {
    console.log(`${ p.id } updated`);
    this.yearlyProduct = p;
    this.changeDetectorRef.detectChanges();
  }

  purchaseMonthlyUpdated = (p: IAPProduct) => {
    console.log(`${ p.id } updated`);
    this.monthlyProduct = p;
    this.changeDetectorRef.detectChanges();
  }

  purchaseApproved = (p: IAPProduct) => {
    console.log(`${ p.id } approved`);
    p.verify();
  }

  purchaseVerified = (p: IAPProduct) => {
    console.log(`${ p.id } verified`);
    p.finish();
  }

  purchaseOwned = (p: IAPProduct) => {
    console.log(`${ p.id } owned`);
  }

  handleError = (error) => {
    console.log('Error event:', error);
  }

  purchase(id: string) {
    this.store.order(id);
  }

  ngOnDestroy() {
    this.subscriptions.unsubscribe();
    this.store.off(this.purchaseCancelled);
    this.store.off(this.purchaseYearlyUpdated);
    this.store.off(this.purchaseMonthlyUpdated);
    this.store.off(this.purchaseApproved);
    this.store.off(this.purchaseVerified);
    this.store.off(this.purchaseOwned);
    this.store.off(this.handleError);
  }
```

1. Install the app from Xcode.
2. Purchase a product (user clicks the purchase button, that button triggers `store.order`)
3. Exit app
4. Cancel subscription so it expires
5. Subscription expires
6. Open app, and confirm that subscription is indeed expired (status goes from `approved` to `valid`)
7. Try to purchase subscription again by clicking the purchase button (any subscription)
8. Nothing happens. No logs. No errors. Product status remains `valid`.
9. Closing the app and then running again does not help.
9. Uninstall app
10. Install app again from Xcode
11. Purchase works again

I can't see anything wrong with the code, and since it's working perfectly fine on Android, we're guessing that it might be something wrong with the phone or maybe the cordova-plugin-purchase plugin.

I would really appreciate any suggestions, ideas, opinions, anything. Thank you very much in advance. I'm getting quite desperate.

**Comment by OrthoCube** [comment]
I have noticed that the plugin sometimes sends verification requests that has type=application and the id is set to the app's bundle ID. In this case, as long as the receipt is valid, even if it is expired, the server should reply with ok=true. If the server does not reply with ok=true, the plugin refuses to work at all.

**Comment by j3k0** [comment]
Indeed, you can chose not to validate the application receipt. (do not call `product.verify()` if `type` is `application`), but it's better to do it. It ensure you have a legitimate download (not an app side-loaded, that might have been modified).

Did fixing the receipt validation solve the issue mentioned above?

**Comment by OrthoCube** [comment]
Yes, it seems to be fixed. I'm still extremely cautious and scared that something might cause it to suddenly not work, but it seems to have fixed the issue!

**Comment by j3k0** [comment]
Good to hear. Closing the issue.

Note that using our external receipt validation service (https://billing.fovea.cc) would free you of these kind of headaches.

**Comment by OrthoCube** [comment]
@j3k0 Indeed, and to be honest with you, I'd rather just use Fovea's validation service, but unfortunately, I'm just a developer, and I'm not in charge of the project, so I still have to implement our own validation service...

Still, I am very grateful that you have made this plugin available for free, and you have done a great service to the world because of that. I really do wish the validation service becomes a great success (I mean, it might already be!) so that more people adopt this plugin.

**Comment by ParhamTaher** [comment]
After upgrading from  cc.fovea.cordova.purchase 7.4.3 --> cordova-plugin-purchase 10.5.3, I noticed this issue as well specifically on iOS. We had accounted for product.type == store.APPLICATION in our custom validator function by simply calling product.finish() if the implicit product was received, although this did not seem to work anymore after upgrading and seemed like the implicit iOS product never actually finished, causing the store.order function to no longer work (as the queue has pending transactions). After a lot of debugging and reading comments above it turns out **the validator itself has to succeed before finishing the product!**

For example:

```
// Force the validator to be true
if (product.type == store.APPLICATION || product.alias == store.APPLICATION) {
	callback(true, product);
        return;
}
```
Now in the window.store.when("product").verified method, you can call product.finish() and hopefully this will clear the application product from the transaction queue. This fixed it for me, hopefully it can help someone else as well.
