### ISSUE TITLE
[IOS] Blank (white) screen: WARNING: Your app should be single page to use in-app-purchases, transactionRecipt depreciated

### ISSUE THREAD

**Issue by MarcelSchuermann** [j3k0/cordova-plugin-purchase#1157]
Hi

### system info
```
macOS Catalina 10.15.6
Cordova 10.0.0
Device: iPhone 11 (13.6) - on emulator
Purchase Plugin Version: 10.5.3
```

### Expected behavior
The app starts normal without white screen. In app purchase works.

### Observed behavior
I get a **blank (white) screen** when I build my in app purchase app on iOS.

- On Android it works.
- I used the same code for Android - **I assume the code msut not be changed?**
- IOS Store is set up and in "**Ready to Submit**" state. It is a Non-renewing-Subscription.
- I have fovea server set up and inserted the secret key and bundle id from IOS App Store Connect.
- I used the secret key only in the fovea server settings. In Android I added the plugin with the secret key. **In iOS it is not needed?**

**After build I get following error:**
"No vibible @interface for 'SKPaymentQueue' declares the selector 'presentCodeRedemptionSheet'" 
in following line:
[[SKPaymentQueue defaultQueue] presentCodeRedemptionsheet];
I tried to comment this line out but then I get the white screen when running the app.

**Before I build I get following warning:**
: WARNING: 'transactionReceipt' is deprecated: first deprecated in iOS 7.0

**When I build, following warning appears:**
: WARNING: Your app should be single page to use in-app-purchases

### Steps to reproduce
[https://purchase.cordova.fovea.cc/use-cases/subscription-ios](https://purchase.cordova.fovea.cc/use-cases/subscription-ios)

Would really apreciate some help.

Best regards,
Marcel

**Comment by j3k0** [comment]
The latest version of the plugin requires a recent version of XCode (see "Releases" here on GitHub for details).

Either upgrade XCode or use an older version of the plugin that do not support the latest features from iOS 14.
