### ISSUE TITLE
[iOS] Ability to detect cancelled Offer Code

### ISSUE THREAD

**Issue by D-Marc1** [j3k0/cordova-plugin-purchase#1159]
I only see `store.redeem()` to open the offer code popup, which works fine, but no way to detect if the user cancelled the Offer Code popup. Could I request this feature? 

Also, does successfully accepting an offer code cause the app to go through the normal purchase flow, like in the diagram in the API? There's no way to test this in sandbox, that I'm aware of.

**Comment by skidrow88** [comment]
Hello, 

Same question than @D-Marc1. 

`store.redeem() `return `void`.

I've some in-app items (non-consommable) to buy in my application but there is no way to know the promo code entered is used for. 

Is there a way to do it ?
