### ISSUE TITLE
[ANDROID]: store.ready always shows "owned":false

### ISSUE THREAD

**Issue by glu000** [j3k0/cordova-plugin-purchase#1161]
### system info
```
Ionic:

   Ionic CLI                     : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 11.0.5
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.3.0)   : 1.2.2
```

### Observed behavior

I use the plugin for in-app purchase of a subscription with automatic renewal. As validation service fovea.cc is used. With iOS everything works fine. After purchasing a subscription I get an OWNED event which is used to enable my premium features. After the subscription is canceled, I get an EXPIRED event. Checking the store.ready event after a store.refresh show the correct owned state (true if there is an active subscription and false if there is no active subscription)

With Android purchasing works fine. There is an OWNED event fired, too. But the store.ready (after a store.refresh) shows always "owned":false - even if there is an active subscription. Also strange: when the subscription is ended by the user there is no EXPIRED event fired. 

Any ideas what could be wrong?

Part of my code:

```
      this.store.register({
        id: PRODUCT_KEY1,
        type: this.store.PAID_SUBSCRIPTION,
      });

      this.store.when(PRODUCT_KEY1)
        .approved((p: IAPProduct) => p.verify())
        .verified((p: IAPProduct) => p.finish());

      this.store.when(PRODUCT_KEY1).expired(async (p: IAPProduct) =>
      {
        console.log("STORE.WHEN EXPIRED event: ", JSON.stringify(p))
      });

      this.store.when(PRODUCT_KEY1).owned(async (p: IAPProduct) =>
      {
        console.log("STORE.WHEN OWNED event: ", JSON.stringify(p))
      });


      this.store.ready(async () =>
      {
        console.log("STORE READY: ", JSON.stringify(p))
      });

      this.store.refresh();
```

Finally an example of a store.ready event when there is an active subscription:

```
iap.service.ts:116 STORE READY:  {"id":"month01","alias":"month01","type":"paid subscription","group":"default","state":"valid","title":"Monatsabo","description":"Vollzugriff auf alle Inhalte","priceMicros":19990000,"price":"€ 19,99","currency":"EUR","countryCode":null,"loaded":true,"canPurchase":true,"owned":false,"introPrice":"","introPriceMicros":"","introPricePeriod":null,"introPriceNumberOfPeriods":null,"introPricePeriodUnit":null,"introPriceSubscriptionPeriod":null,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"trialPeriod":null,"trialPeriodUnit":null,"billingPeriod":1,"billingPeriodUnit":"Month","valid":true}
```

**Comment by ptrahan** [comment]
I also have this problem on android. I do a store.refresh() at start of application and later when I do a store.get(productid), the product.owned is always false in the updated handler and the product.canPurchase is false as well. The product.owned should be true because the product was purchased. If I try to purchase again, it says I already have this product. There is definitely a problem with the product.owned flag as many reported this issue.

**Comment by jamesfdickinson** [comment]
I had the same issue, owned items didnt no show up as owned, just canPurchase false when "ready" completed.  They would show up as "owned" if I did a refresh.  I dug through the code and found a finish event for all items refreshed completed.  The owned items were marked as 'owned'
https://github.com/j3k0/cordova-plugin-purchase/blob/d33cdae92e7f62a54a1865fa0f602932995c9c8b/src/js/refresh.js

`
                store.ready(() => {
                    console.log("IAP ready");
                });
                store.refresh().finished((fn) => {
                    console.log("IAP refresh finished",fn);
                    resolve();
                });
`

**Comment by vanessag** [comment]
I've also found that store.ready() fires inconsistently between iOS and android. On iOS it fires after all receipt validation takes place (expected) and on android it seems to fire when all products are valid (unexpected). Also the expired event seems to only fire for Android after closing and reopening the app. @j3k0 any ideas?

**Comment by nadeeth** [comment]
Check these issues. This must be the same as those. 
- https://github.com/j3k0/cordova-plugin-purchase/issues/425
- https://github.com/j3k0/cordova-plugin-purchase/issues/295 

I could fix it by running approved call back every time app starts. 

`store.when("my_product").approved(function(p) {
    // no validation, just confirm the purchase.
    p.finish();
});
`

**Comment by j3k0** [comment]
@bierzorutas : the code has been rewritten since then. If you have a problem it is a different one. Check newer issues or create a new one with your logs and code.
