### ISSUE TITLE
[IOS] Can't order expired non renewing subscription

### ISSUE THREAD

**Issue by oduverne** [j3k0/cordova-plugin-purchase#1164]
Hello, I have an issue on iOS, I can't order expired non renewing subscription

### system info
Compiled on macOS 10.15 | Catalina
Issue happens on iOS 13 and 14

Plugins;
    "@globules-io/cordova-plugin-ios-xhr": "^1.2.0",
    "cordova-android": "^9.0.0",
    "cordova-ios": "^6.1.1",
    "cordova-launch-review": "^4.0.1",
    "cordova-osx": "^6.0.0",
    "cordova-plugin-app-version": "^0.1.12",
    "cordova-plugin-camera": "^5.0.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-keyboard": "^1.2.0",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-purchase": "^10.5.3", (issue also in 10.5.0)
    "cordova-plugin-splashscreen": "^6.0.0",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-x-socialsharing": "^5.6.8",
    "cordova-windows": "^7.0.1",
    "es6-promise-plugin": "^4.2.2"

### Expected behavior
If a non renewing subscription expired the user can order it again

### Observed behavior
When store.order(id) is called nothing happens, the ios popup to do the purchase doesn't open.
Another user reported this issue on ionic forums:
https://forum.ionicframework.com/t/cordova-plugin-purchase-on-ios-order-does-not-work-without-uninstalling-the-app-first/203403

### Steps to reproduce
Order a non renew subscription
Let it expire
Order it again
Nothing happens

Here are the logs:
[logs.txt](https://github.com/j3k0/cordova-plugin-purchase/files/5931183/logs.txt)

Thank you for your help

**Comment by oduverne** [comment]
Hello, here are some updates.
This behavior occurs since v10.0.0. It works fine with v9.0.0 of the plugin.

**Comment by sahalshn** [comment]
@oduverne  I have the same issue in iOS. I am able to purchase an auto-renewable subscription(Monthly) for the first time. After its expiry, I am trying to re-order from my app using the same code store.order(id). But nothing is happening. Here can purchase field is false.

**Comment by pixelone** [comment]
Experiencing this problem as well.   On recurring subscriptions,  once it goes expired  I am unable to purchase again. 

```
"cordova-plugin-purchase": "^10.5.3",
"@ionic-native/in-app-purchase-2": "^5.32.0"

Ionic:
   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.3

Capacitor:
   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

System:
   NodeJS : v15.2.0 (/usr/local/Cellar/node/15.2.0/bin/node)
   npm    : 7.7.5
   OS     : macOS Big Sur
```

Did anyone find a solution for this?

**Comment by oduverne** [comment]
> 
> 
> Experiencing this problem as well. On recurring subscriptions, once it goes expired I am unable to purchase again.
> 
> ```
> "cordova-plugin-purchase": "^10.5.3",
> "@ionic-native/in-app-purchase-2": "^5.32.0"
> 
> Ionic:
>    Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 5.6.3
> 
> Capacitor:
>    Capacitor CLI   : 2.4.7
>    @capacitor/core : 2.4.7
> 
> System:
>    NodeJS : v15.2.0 (/usr/local/Cellar/node/15.2.0/bin/node)
>    npm    : 7.7.5
>    OS     : macOS Big Sur
> ```
> 
> Did anyone find a solution for this?

I use v9.0.0 of the plugin until a fix is found

**Comment by pixelone** [comment]
Thanks @oduverne, just pulled in 9.0 and it's working as intended.   Hopefully this bug gets fixed.

**Comment by maxcorrads** [comment]
Hi, any update on this?

**Comment by ahmad-alkhatib** [comment]
Why there is no support for this library!! at least these problems need to be highlighted in the readme file.
