### ISSUE TITLE
[IOS] IAP not working in production, id in validation returns bundle id in production instead of product id 

### ISSUE THREAD

**Issue by bardgr** [j3k0/cordova-plugin-purchase#1166]
First of all, thanks ffor reading I would not post but I have been debugging for many days without any result.

### system info

macOS Catalina 10.15.7
XCODE 12.4
Cordova 10.0.0
Device: iPhone iOS 14.3.0 
Plugin Version: 10.5.3 **important**: We upgraded from version 9 or 10 hard to remember.
type of IAP: Consumable

**Important:** I have checked, double and triple checked all prerequisites for inApp purchases. IAP was working fine in iOS and still does for android. I have also contacted Apple and provided logs to be sure; their response:
"_We can see that the app doesn't respond to the buttons in production, however we can also see when hooked up to the debugger that StoreKit is getting the products from the server, parsing them properly, and returning them to the your delegate method. There is an error somewhere in the your code. We'd advise you to add production logging or to use the debugger on their production app to see where the error is._"

### Expected behavior
On production version
1. Clicking on the button that does the purchase on my app
2. The request for confirmation from Apple pop ups.
3. After I confirm our server gets the validation with the apple receipt and the IAP id (among other data)
4. We validate the receipt by sending back 0
5. IAP succesful

### Observed behavior
On production version
1. Clicking on the button that does the purchase on my app
2. The request for confirmation from Apple DOES NOT pop up.
3. Our server gets the validation with the apple receipt but **instead of the product id we get the bundle id**
3. We do not validate the receipt by sending back 6778001
4. IAP NOT succesful (the user sees nothing from the moment she/he pressed buy

On Testflight/plugged device version in sandbox
1. Clicking on the button that does the purchase on my app
2. The request for confirmation from Apple pop ups.
3. After I confirm our server gets the validation with the apple receipt and the IAP id (among other data)
4. We validate the receipt by sending back 0
5. IAP succesful

### Steps to reproduce
I am not aware if that is happening to someone else

but here are some debug data.
What I get in my server to validate

`{"id":"<app bundle id in the com.app name format>","alias":"application","type":"application","group":"","state":"approved","title":null,"description":null
,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":true,"canPurchase":false,"owned":false,"introPrice":null
,"introPriceMicros":null,"introPricePeriod":null,"introPriceNumberOfPeriods":null,"introPricePeriodUnit":null,"introPriceSubscriptionPeriod":null
,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":{}

,"transaction":{"type":"ios-appstore","appStoreReceipt":"<the receipt too big to put here>"},`

I do not to want to bombard with unrelated logs bur
@j3k0, if something is needed please tell me and I will try to provide it ASAP.

**Comment by kostisM** [comment]
Same here!!

**Comment by bardgr** [comment]
OK solved it.
It seems that validation is performed in 2 steps.
First a validation comes with bundle id  in the id and that is visible from the type -> type":"application
Then the validation comes with the product id in the id field.
It heloed this solved issue to identify that #1155 

Hope my comment will help others with the same issue.

I believe a more clear documentation on that is needed.
Thank you all :)
