### ISSUE TITLE
[ANDROID] Unregister a callback not working Ionic 3

### ISSUE THREAD

**Issue by dlazzy** [j3k0/cordova-plugin-purchase#1168]
### System info

```
cli packages: (~/.nvm/versions/node/v7.8.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.9

System:

    Android SDK Tools : 26.1.1
    Node              : v7.8.0
    npm               : 4.2.0 
    OS                : Linux 5.8
```

### Expected behavior

Hello, I'm currently trying to make the inapp purchase plugin working correctly. So I've correctly setup the product inside Google Play Console, everything is working. I can make a fake purchase with the testing credit card.

I make an order with `this.store.order('my_product')`, then creating **approved**, **cancelled** and **error** handler. My goal it to execute only one time the **approved** callback.

Inside those callbacks I call a function to disable them. Using store.off(...). It should unregister the callbacks.

### Observed behavior

When a purchase is a success, the **approved** callback is called as many time I've launch an order.

### Steps to reproduce

There is the code I'm using (simplest code), also products are registered when the platform is ready.

##### Registering products when app launched :

```ts
register() {
  if (this.platform.is('android')) {
    this.androidIAP = [
      // There is other products registered before, removed for the issue
      {
        id: 'premium_mode',
        alias: 'premium_mode',
        type: this.store.CONSUMABLE
      }
    ];
    this.store.verbosity = this.store.DEBUG;
    this.androidIAP.map(a => {
      this.store.register(a);
    });
    this.store.refresh();
  }
}
```

##### Buying process :

```ts
buy(product: string) {
  this.store.order(product);
  this.approvedHandler = this.store.when(product).approved((p) => {
    p.finish();
    console.log('PURCHASE SUCCESS');
    this.dismissHandler();
  });
  this.cancelHandler = this.store.when(product).cancelled(() => {
    console.log('PURCHASE CANCELLED');
    this.dismissHandler();
  });
  this.errorHandler = this.store.when(product).error(() => {
    console.log('PURCHASE ERROR');
    this.dismissHandler();
  });
}

dismissHandler() {
  this.store.off(this.errorHandler);
  this.store.off(this.cancelHandler);
  this.store.off(this.approvedHandler);

  // Closing current page in ionic
  return this.navCtrl.pop();
}
```

Problem, when clicking on the button to buy the premium_mode it open the PlayStore dialog. Touch device back button to trigger the **cancelled** callback. It show *PURCHASE CANCELLED* in console. Okay.

The page is closed, due to `this.navCtrl.pop()`, reopening the page, clicking again on the button, tap back button to trigger the **cancelled** callback, page closed again, show *PURCHASE_CANCELLED*. Okay.

Reopening the page once again, clicking the button, make the purchase successfully, **approved** callback is triggered, but in console there is 3 *PURCHASE SUCCESS*, like the callback have never been unregistered.

This cause me problems in my app... I cannot handle well the errors, and also if the purchase is a success and it give (for example) 300 coins instead of 100 because the **approved** callback is triggered 3 times, this is a huge problem.

Store debug, after multiple cancelling and then one purchase :

```text
[store.js] DEBUG: state: premium_mode -> approved
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> defer finishing premium_mode
myoffer.ts:110 PURCHASE SUCCESS
store-android.js:2172 [store.js] DEBUG: product -> finishing premium_mode
store-android.js:2172 [store.js] DEBUG: state: premium_mode -> finished
store-android.js:2172 [store.js] DEBUG: plugin -> consumable finished
(5) store-android.js:2952 InAppBilling[js]: consumePurchase()
```

Thank you for your help.

**Comment by jbfrequence** [comment]
Hi,

**Comment by jbfrequence** [comment]
Hi,

The issue is coming from the fact that the call to `store.when(product).xxxxx(callback)` do not return the callback but a function that register a callback (witch is not the same in term of reference)

The workaround (I wish the authors of this plugin will refactor their functions for callback registration) is to use a method like this :
```
function storeOnce = function(query, action, cb){
 store.once(query, action, cb);
 return cb;
}
```
but then you should use functions like this :
```
storeOnce(product, "approved", function(){...});
storeOnce(product, "cancelled", function(){...});
```
