### ISSUE TITLE
Google Play: stop/resume don't work properly.

### ISSUE THREAD

**Issue by agamemnus** [j3k0/cordova-plugin-purchase#117]
If you are in the middle of a consumable transaction, switch out of the app, and then return back and complete the transaction, any new consumable transaction of the same type will yield the following error:

`Google Play Store error 7: Purchase failed: Error purchasing: IabResult: Unable to buy item (response 7:Error)`

**Comment by agamemnus** [comment]
A lot of the error callbacks don't have a return statement. That's an error and should be fixed.

**Comment by Dhamu143** [comment]
hey is there any update on this issue? i am also facing this issue.

**Comment by agamemnus** [comment]
See: https://github.com/j3k0/cordova-plugin-purchase/issues/108#issuecomment-69243398 for my solution.

**Comment by Dhamu143** [comment]
I replaced plugin's file with https://github.com/agamemnus/cordova-plugin-purchase/blob/fixed_returns/src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java your file. 

it did not work for me.

**Comment by agamemnus** [comment]
Try seeing if the other steps in Issue 108 help.....
