### ISSUE TITLE
Is it possible for a user to buy  in app subscriptions from outside the app?

### ISSUE THREAD

**Issue by r-rodriguez-s** [j3k0/cordova-plugin-purchase#1172]
We've been using this plugin for a few months now and we're doing very well on iOS and Android, but we have a question. We have done a lot of research but we have not been able to clarify it.
We ask for help in case someone knows the answer to help us clarify, we would appreciate it very much.
So far users are buying subscriptions from within our app with the help of this plugin. 
On our server we register the relation of the purchase with the identifier  of the user who bought from the app, previously logged in to our app (validating the buy from the app in our server)
We know that they cancel them from outside the app in the iOS or Android operating system.
We are using the App Store Server Notifications in which we receive from Apple user actions on their subscription and we can record their cancellations and renewals.

Our question is:
Is it possible for a user to buy a subscription from outside of our App? because in that case we could not relate his original purchase token with his user login inside our app because hi is buying outside the app. 
We can only relate the user logged in during the purchase validation process of the plugin if the user buy suscription from inside the app. 

We have observed that one of the App Store Server Notifications that we receive is INITIAL_BUY, but we believe that they must be extra information of purchases of users from inside the app itself because if they were purchases from outside the app we would not be able to search in our tables for the users with the original transaction token in the notification,  we only can register in our tables relations that we would have previously saved if he bought from the app.
It will only be possible for us to save the relationship of our users with their original transaction token if they buy from within the app previously logged into the app.

Thank you for your work and for your help, sorry if I extended the question a lot, I am not fully fluent in English and I wanted to explain myself.

**Comment by nvahalik** [comment]
You can do what you're wanting if you make the "source of truth" a server.

For example:

In our application, we use server messages to create the correct subscription information in our backend. However, we can simply generate a "local" subscription which ultimately updates a `user_is_paid` flag on their account.

If your application is looking for that flag or some other information, then you can technically use whatever you want to make sure that flag gets toggled.
