### ISSUE TITLE
[Android] Server retrieving error: DF-DFERH-01

### ISSUE THREAD

**Issue by faytekin** [j3k0/cordova-plugin-purchase#1173]
I get this error `Error while retrieving information from server DF-DFERH-01` while trying to make a test buying. It is not a rare situation, it continues after clearing Play Store data. It specially occurs at non-consumable product purchases.

**Comment by j3k0** [comment]
Hi, this is an error with the Google Play being in an inconsistent state on a device. Nothing we can fix in the plugin as far as I know. Did you find any solution to this?

**Comment by j3k0** [comment]
Note: I'm closing the issue here because it's not a problem with the plugin. Feel free to reopen if you have more info.
