### ISSUE TITLE
Issue when purchasing the same consumable product

### ISSUE THREAD

**Issue by bobibt** [j3k0/cordova-plugin-purchase#118]
When i purchase the same product (consumable) two times, it triggers two approved events, the third three and so on. Why is this happening. I finish the consumable product before i try to buy it again. Please help i'm stuck with this for weeks.

**Comment by agamemnus** [comment]
A second post isn't going to help everyone. Keep it to the first one...

**Comment by arielfaur** [comment]
I seem to be experiencing the same issues on Android as my code seems to run twice only. I see this in the release build where I trigger a download of a consumable. Anyone else seeing this?

**Comment by skhouseholder** [comment]
What @artistika is describing sounds reminiscent of accidentally running a click handler multiple times when you think it's running only once. Each subsequent nth click causes the code to be executed n times.
