### ISSUE TITLE
Change language depending on region / location

### ISSUE THREAD

**Issue by MarcelSchuermann** [j3k0/cordova-plugin-purchase#1185]
My periodUnits always shows in english (f.e. "Year").
Is it possible to change this to the local unit (f.e. "Jahr" in german)?

**Comment by geleto** [comment]
I also have this problem. Is the language always English, or does it depend on the App/Play Store country, or on the device locale?
I would like to be able to specify the language in store.register(), as the user can select a different language for the app.
AFAIK apple and google require you to display the actual data received for the product and not hardcoded strings, so getting the language right is important.

**Comment by JZubero** [comment]
Same here. @MarcelSchuermann + @geleto Did you guys find a solution already?

**Comment by MarcelSchuermann** [comment]
> Same here. @MarcelSchuermann + @geleto Did you guys find a solution already?

@JZubero: I did not find a solution but my app was accepted in the stores with english unit information.

**Comment by Dexus** [comment]
Normal the App will based on the system Settings use the formation of the currency and every international formatting it get from the store api. So you don’t need to change everything. Only as a small note.

I had never an issue with any app.

Von meinem iPhone gesendet

**Comment by yuto7th** [comment]
@Dexus 
I am also facing the same issue. When I submitted my app to the App Store yesterday, it was correctly displaying in Japanese yen on my end. However, despite this, it appeared in dollars for the reviewer and was rejected. Please advise on the best course of action to address this. I will send you screenshots of how it appears on my end and the rejection notice from the App Store reviewer. Additionally, I am displaying the "product.price" obtained from the product at the time of "store.ready". If this issue cannot be resolved, I cannot update the app. Could someone please follow up on this? Also, I am using plugin version v11.

・Correct display
<img src="https://github.com/j3k0/cordova-plugin-purchase/assets/18374976/67c59daf-afc1-4f10-952d-f01b64584eab" width="30%" />

・Incorrect display (the one that got rejected)
<img src="https://github.com/j3k0/cordova-plugin-purchase/assets/18374976/da460878-19aa-4a40-87fa-cc804e145b0a" width="30%" />
