### ISSUE TITLE
Capacitor 3

### ISSUE THREAD

**Issue by oangelo** [j3k0/cordova-plugin-purchase#1187]
I saw that capacitor 3 offers a lot of advantages, but breaks the compatibility with some plugins. Does this plugin works with Capacitor 3? I saw nothing on the readme.md... Anybody have already tried Capacitor 3 with this plugin?

**Comment by ghonche-yqr** [comment]
Hi
I'm using this plugin with Capacitor 3. I'm not yet finished developing but no conflict so far.
But there are some Capacitor Plugins which are not yet published their stable version. Keep that in mind if you're having your second thoughts.
Good luck

**Comment by ghonche** [comment]
I'm not sure what exactly is your problem but any how this is my code. I'm using InAppPurchase2 in a service to provide iap functions to other components.
 

> import {Injectable} from '@angular/core';
import {IAPProducts, InAppPurchase2} from '@awesome-cordova-plugins/in-app-purchase-2/ngx';
@Injectable({
    providedIn: 'root'
})
export class PurchaseService {
    public isAdFree: boolean = false;
    public iapReady: boolean = false;
    public ownershipLoaded: boolean = false;
    constructor(private store: InAppPurchase2) {
    }
    private registerProduct(id: string, type: string) {
        this.store.register({
            id: id,
            type: type,
        });
    }
    public purchase(id: string) {
        const p = this.store.get(id);
        this.store.order(p).then(data => {
            p.finish();
        }, error => {
        });
    }
    public getProducts(): IAPProducts {
        return this.store.products;
    }
}


Fell free to ask for any details. I will be glad to help.

**Comment by bitbay** [comment]
Thank You @ghonche for Your implication.
My problem isn't at "angular" level (i'm quite familiar with it), but i have problems installing it inside capacitor.
I did
```
// the plugin of course...
$ npm i cordova-plugin-purchase
// dependencies...
$ npm i @awesome-cordova-plugins/in-app-purchase-2
// and dependencies of the dependency...
$ npm i @awesome-cordova-plugins/core
// and finally sync capacitor...
$ npx cap sync
...
update android [info] Found 1 Cordova plugin for android:
       cordova-plugin-purchase@10.6.1
...
```

The `@awesome-cordova-plugins/in-app-purchase-2` solved the `typescript` bindings, and as far i see it serves as a wrapper around and provides the `store` as an injectable angular service - so far so good...

At this point compiling the app and apk works, but the service injected shows up as `undefined` (without any error/warning as far i can tell).

I was wondering if i have to register the plugin in my `MainActivity.java` (as i had to with another plugin) so i tried:
```
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      
 registerPlugin(com.getcapacitor.community.facebooklogin.FacebookLogin.class);
        registerPlugin(cc.fovea.PurchasePlugin.class);
    }
}
```
But can't compile the `android` part, as it can't find some cordova dependencies (PurchasePlugin extends/depends on).

Before going into those details, i would love to hear from You, maybe You already spotted something i missed so far.

**Comment by bitbay** [comment]
...just to give an update and "close" my own question.
> My problem isn't at angular level...
It indeed was a problem, with the way i (manually) handled my dependency tree and injection.

Installing with
```
$ npm i cordova-plugin-purchase
$ npm i @awesome-cordova-plugins/in-app-purchase-2
$ npm i @awesome-cordova-plugins/core
$ npx cap sync
```
the `window.store` *is* available, and after fixing my ng code the `InAppPurchase2` service started to show up as well.

The `capacitorjs` seem to handle the cordova plugin part out of the box, finally modifing `MainActivity.java` wasn't necessary at all - although i haven't got to test any calls into android IAP code yet.

**Comment by bitbay** [comment]
@ghonche , one thing i think You could still help me out with - where does the "$BILLING_KEY" go?
Since using capacitorjs (not using cordova), i'll have to put that value somewhere inside the android project as it doesn't get "ported" by capacitorjs automatically.
Could You do a quick search in Your android forlder for Your "google billing public key" and share the location/filename/content please? Obviously, taking care not to share YOUR key ;)
Thank You!

**Comment by j3k0** [comment]
@bitbay Latest version of the plugin doesn't require `BILLING_KEY` anymore.

**Comment by ghonche** [comment]
@bitbay 
I added the my BILLING_KEY under  `/android/app/src/main/res/values/strings.xml`
like:

`<resources>
    <string name="billing_key">ABCDABCDABCD</string>
</resources>
`
