### ISSUE TITLE
[iOS] Migrate to Fovea Billing

### ISSUE THREAD

**Issue by selected-pixel-jameson** [j3k0/cordova-plugin-purchase#1193]
I'm currently using my own service to verify and validate iOS purchases using this implementation:

`this.store.validator = (product, callback) => this.verifyReceiptCallback(product, callback);`

I would like to add a POST directly to `https://validator.fovea.cc/v1/validate?appName=xxxxxx&apiKey=xxxxx` within my custom `this.verifyReceiptCallback(product,callback)` function. This will allow me to seamlessly migrate to Fovea billing without having to disconnect my custom verification. 

What are the parameters that I need to POST to `https://validator.fovea.cc/v1/validate?appName=xxxxxx&apiKey=xxxxx`?

**Comment by j3k0** [comment]
Hello Jameson,

If you just POST the whole product, it'll work.

You can find the implementation of the URL based validator in the plugin code itself: https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/validator.js#L162-L186

You can also refer to Fovea's validator documentation: https://billing.fovea.cc/documentation/api/v1/validate/
