### ISSUE TITLE
[Android]Ajax request fails when validating recipt with unknown

### ISSUE THREAD

**Issue by lilmnm-kamikaze-** [j3k0/cordova-plugin-purchase#1199]
### system info
Cordova 9
Device: 10ndroid 10
Plugin Version: 6.0.0

### Expected behavior
Ajax call success
### Observed behavior
`[INFO:CONSOLE(2172)] "[store.js] WARNING: ajax -> request to https://[EDITED]/validate.php failed with an exception: Unexpected token < in JSON at position 0"`
### Steps to reproduce
```
store.validator = "https://[EDITED]/validate.php"; //using own validator script
//do the product register
store.order(sku);
store.when(product.ID).approved(function(p) {
	p.verify();
});
store.when(product.ID).verified(finishHim);

```

**Comment by Dexus** [comment]
Your php script returns a invalide json.

Von meinem iPhone gesendet

**Comment by lilmnm-kamikaze-** [comment]
That was the first this i suspected.

No request is sent to the server from the app.

**Comment by Dexus** [comment]
`Unexpected token < in JSON at position 0` means that there is a HTML response from the server. So it dont response a correct json.

what happens if you send a post to your server from commandline?

**Comment by lilmnm-kamikaze-** [comment]
when i use the old plugin i get the valid response 

`{
"error": false,
"message': ok
}`

**Comment by Dexus** [comment]
You can check it with a example JSON body like: https://github.com/j3k0/cordova-plugin-purchase/blob/d33cdae92e7f62a54a1865fa0f602932995c9c8b/src/js/validator.js#L31-L46

**Comment by lilmnm-kamikaze-** [comment]
i have all post requests being sent to my server logged for development and its not getting this request.

I have how ever got it to work by having store.validator as a function

`
function validateIAP(product){
		//alert(JSON.stringify(product.transaction));
		//alert({userID});
		//progress.Page();
		//progress.HideAll();
		var data = JSON.stringify(product.transaction);
		data['userid'] = {userID};
		
		$.ajax({
			url: "https://[EDITED]/validate.php",
			cache: false,
			dataType: 'JSON',
			data: data,
			type: 'POST',
			success: function (response) {
				//do success
			},
			error: function (xhr, ajaxOptions, thrownError) {
				//catch error
			}
		});
	}

store.validator = function(product, callback) {
	    	validateIAP(product);
		    callback(true, { transaction: "Testing_only" }); // success!
		};
`

**Comment by lilmnm-kamikaze-** [comment]
Issue still is not solved.

**Comment by Dexus** [comment]
Okay, then please provide any logs you get, from logcat, console etc. I'm not able to reproduce your problem.

Did it work before? What has changed since than?

**Comment by lilmnm-kamikaze-** [comment]
the message above is from logcat. everything else was as expected up until it goes to validate.
It never worked. i used a different plugin for IAP but it will not be updated to use the new in app billing library v3 so i switched to this one. The only way i can get validating to work is to set up my own ajax call to my server.

**Comment by Dexus** [comment]
Are you really sure that your Validation Script is working as expect? Your Script response is correct in the way this lib need it?
I'm pretty sure that the problem is on your server side, you can write me a email, and I can check your Script, so we can be sure that his is not the problem. Else we will not investigate this error any longer. As I'm not able to reproduce it.

**Comment by lilmnm-kamikaze-** [comment]
Yes the server validation its working as expected as stated above.Also stated above the plugin is not sending a request to the server with that error. I had to set up my own ajax call to the server for it to actually send a request to my server. 
From my understanding the validator returns the correct data which is the transaction. There is nothing in the documentation that i have seen that gives an example of what your validator should be like just the response that is returned when you use the validator.fovea.cc address.
