### ISSUE TITLE
Android test payment seems to break complete store

### ISSUE THREAD

**Issue by CodeHunger** [j3k0/cordova-plugin-purchase#120]
I'm running the following code.

```
store.verbosity = store.DEBUG;
store.register({
  id:    "android.test.purchased",
  alias: "buy object",
  type:  store.CONSUMABLE
});

store.ready(function() {
    console.log("store ready");
    store.order("android.test.purchased");
});

store.refresh();
store.when("buy object").approved(function (order) {
  console.log("You got an EXTRA LIFE!");
  order.finish();
});
```

The script should show a purchase popup when the shop is loaded.
When you have a factory resetted device the script seems to work.
`store ready` is logged and you get the popup and can buy the product.
When you buy the product you get an error:

`Purchase verification failed: missing data.`

The source code which makes this call is found here: https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/android/com/smartmobilesoftware/util/Security.java#L42-45

i've checked the condition seperetly and the `signature` value is empty.

When i restart my app the `store.ready` callback is never called and the app fails to start.
The `store ready` log will not fire.

I have signed the application so i think its the store signature from google which is not send with test payments.

**Comment by CodeHunger** [comment]
#123 fixed this for me.

**Comment by sarahsga** [comment]
#123 fixed this for me too. @flexed 's answer worked for me perfectly! I have also answered it in hope that it might help
