### ISSUE TITLE
[Android] Purchase dialog doesn't show up

### ISSUE THREAD

**Issue by ghonche-yqr** [j3k0/cordova-plugin-purchase#1200]
### system info

```
Cordova 10.0.0
Device: Android 11
cordova-plugin-purchase: 10.5.3,
```

### Expected behavior
To  open google play purchase dialog
### Observed behavior
No dialog is showed.
### Steps to reproduce.

this.store.register({
     id: 'my.product',
     type: this.store.NON_CONSUMABLE,
   });
this.store.refresh();
const p = this.store.get('my.product');
 this.store.order(p);

### Additional Info
I successfully registered the product and after store.refresh() , product status is valid.
store.order(p) returns success but no dialog is showed up.

**Comment by marioluquem** [comment]
A mi me esta pasando algo parecido, has podido solucionarlo? a mi en la console me dice: 
"[store.js] DEBUG: state: categoria_imposibles -> valid"
luego:
purchase_cancelled {}
y lo último que sale es:
[store.js] DEBUG: store.trigger -> triggering action refresh-finished

No me está mostrando el dialogo de compra

**Comment by ghonche-yqr** [comment]
My problem solved! I just created a new product and everything worked fine!
