### ISSUE TITLE
Receipt validation (Reciept is not updated)

### ISSUE THREAD

**Issue by ravshan4yk** [j3k0/cordova-plugin-purchase#121]
I am developing application for iOS and Android.
I am doing validation reciept on my server side.

Here is an example of my code:

``` javascript
store.when("my stuff").approved(function(product) {
    product.verify();
});

store.when("my stuff").verified(function(product) {
    product.finish();
});

store.validator = function(product, callback) {

    callback(true, { ... transaction details ... }); // success!
    ...
    // Here, I check transaction receipts with either Apple or
    // Google servers on my server side.
});
```

When I make the first purchase, then the purchase is successful and the reciept validation passes successfully. Then I make a second purchase, then get an error. Validation reciept on my server side is not successful. Because I think not updated reciept on the client part of the application and when I send this reciept on my server side, I'm getting old not updated transaction.

I uncommented line https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/ios-bridge.js#L341 and all my actions with reciept and transactions were successful.
Tell me what to do?

**Comment by thomashilzendegen** [comment]
Hi ravshan4yk,

just comment the line again as before and reset the cached appStoreReceipt with the following line of code right before every order (with e.g. window.store.order(...)):

```javascript
window.storekit.appStoreReceipt = null;
```

This has the same effect but you are not changing any code of the plugin.

The author of the plugin should have a look into the caching of the appStoreReceipt, there seems to be a problem related to consumables.

Cheers,
Thomas

**Comment by DigitalMystery** [comment]
@thomashilzendegen @ravshan4yk @j3k0 

I am working with subscriptions and it seems like what is happening to me is the same as this thread except right now only on Android.  
Is there something to do on Android to refresh the receipt?  Currently, on the approved the product transaction details are always the same.  When I send it back to my server to validate the receipt never changes so I am always validating the original receipt.  I do get new valid test emails from the store every time I subscribe or cancel.

`store.when('my_id').approved(function(product) {
     var receiptIsAlwaysTheSame = product.transaction.receipt;
     //I send the receipt to my server here to validate     
});`

**Comment by tehmaestro** [comment]
Hi. I'm having the same problem on Android. Did you manage to find a solution? Or is this behavior only when testing subscriptions (daily renewals) ? Thanks.

**Comment by DigitalMystery** [comment]
I could not figure out a way to refresh the receipt.  I could not move it into production like that so for now I am using cordova-plugin-inapppurchase for android and iOS with auto renewable subscriptions.  Then I have a separate branch for Windows using this plugin which only has a lifetime subscription purchase.  Not ideal and I would like to just use this one since it has support for all .  If you figure it out let me know!

**Comment by tehmaestro** [comment]
So, it works for you on android? I am testing auto renewable subscriptions on Android, and the receipt doesn't get refreshed with the latest renewal.

**Comment by DigitalMystery** [comment]
No I could not get it to refresh on any platform.    I hate to link to a different plugin on here, but [cordova-plugin-inapppurchase](https://github.com/AlexDisler/cordova-plugin-inapppurchase) is a separate plugin and it does refresh the receipt but its only for iOS and Android.  Hopefully I can delete this comment one day ;-)

**Comment by tehmaestro** [comment]
Oh, ok, thanks a lot, I will have a look at the code, maybe I can spot the lines that work for the other plugin. Will let you know. Thanks.

**Comment by tehmaestro** [comment]
I've tested the other plugin and I still got the initial receipt sadly instead of the renewal .. also, although I cancelled one of my test subscriptions yesterday, I still got the receipt for that subscription, which is expired, in both plugins.  

 Only after I clear the cached data of the Google Play Store app, I stopped receiving the receipt for the expired subscription.

**Comment by DigitalMystery** [comment]
I never receive the same receipt using the other one, but at least something worked.  Strange that even if I uninstall the app and re-install I would get the same receipt.  Isn't that in essence clearing the cache as well?  I would be interested to know if non-test subscriptions act that way for you also.  Obviously that would not go over to well to force the customer to have to go do that.

**Comment by tehmaestro** [comment]
One more question, trying to get to the bottom of this issue .. Did you have the app in production when you were testing? I have a dev app which is  only beta, I have no apk-s in production .. maybe this matters.

**Comment by DigitalMystery** [comment]
Nope.  Only alpha and beta builds.
