### ISSUE TITLE
please help dude.

### ISSUE THREAD

**Issue by mervantanrikulu** [j3k0/cordova-plugin-purchase#1210]
the app is not working now.
I downloaded the new update.

but I didn't quite understand your plugin.

Could you please write a simple code for me?

sample :
```js
// button onclick="xxx"

function xxx()
{
//purchase code
}

function finish()
{
alert("ok");
}
```

I read the document but I can't figure it out.
please help me

**Comment by Dexus** [comment]
No, read the fucking examples! And the docs that are on n the files and in the other linked sites!

**Comment by mervantanrikulu** [comment]
I read but couldn't find a way.

Is it that hard to help?

**Comment by mervantanrikulu** [comment]
My only question is.


function initStore() {

     if (!window.store) {
         alert("Store not available");
         return;
     }

     store.register({
         id: "domainprice",
         alias: "domainprice",
         type: store.CONSUMABLE
     });

     store.error(function(error) {
         alert("ERROR");
     });

     // ... MORE HERE SOON

     store.refresh();
}

initStore();


I have consumed consumables here.

store.order("domainprice");

I started buying here.

but I couldn't set the successful return field and the error field.

sorry i don't know english.

I couldn't understand.

**Comment by Dexus** [comment]
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/example.js

**Comment by mervantanrikulu** [comment]
dude you are great.

this is what i was looking for :)

I'm solving them all now.

thank you very much.

**Comment by mervantanrikulu** [comment]
store.register({
        id:    "domainprice",
		alias: "domainprice",
        type:   store.CONSUMABLE
    });

store.refresh();

store.get("domainprice");

store.order("domainprice");


store.when("domainprice").approved(function(p) {
    alert("1");
});

bro i tried this code before

but it didn't work when I asked for a second product.

Is there a sample code for me to reset and restart the store?

so I want to register again for every purchase.

**Comment by mervantanrikulu** [comment]
error 6777003 : purchase failed : product not registered : domainprice

**Comment by Dexus** [comment]
did you finish the developer registration with all contracts and financial data on Google Console/Apple Developer?
I think you don't read anything currently! Please read all the stuff of the documentation!

**Comment by mervantanrikulu** [comment]
yes i completed it. It was working before I got paid. I know I've tired you a lot. But if you come to Turkey, I promise to buy you a meal :)

Could you please help me by entering my computer with teamviewer?

220 559 514

1yb7dm2p

**Comment by mervantanrikulu** [comment]
![image](https://user-images.githubusercontent.com/32783110/124367235-0bec3c80-dc5e-11eb-83aa-308fc9eb332e.png)

**Comment by mervantanrikulu** [comment]
do you see any error here bro?
I'm reading the docs.
but i don't know english very well.
I think I misunderstood :(
please don't be mad at me :/

**Comment by mervantanrikulu** [comment]
![image](https://user-images.githubusercontent.com/32783110/124367539-b9f8e600-dc60-11eb-8cd4-303f10ad6207.png)


![image](https://user-images.githubusercontent.com/32783110/124367552-d006a680-dc60-11eb-9a85-f550337fb55c.png)


Look, it works sometimes.
Don't I have to reset it somewhere at the top and pull it again?

**Comment by mervantanrikulu** [comment]
bro i found the problem.

The previous purchase remains open.
That's why it can't find it.

store.off("all");

how can I do that ?

**Comment by mervantanrikulu** [comment]
store.when("productprice").approved(function(order) {
 
        order.finish();
    });
												 store.off("productprice");





													store.register({
														id:    "productprice",
														type:   store.CONSUMABLE
													});
												store.refresh();

												store.get("productprice");

												store.order("productprice");


												store.when("productprice").approved(function(p) {

							alert("ok");
												});

												store.error(function(e){
													alert("ERROR " + e.code + ": " + e.message);
												});


"dexus" dude thank you very much.
this is how i solved the problem.
I'll keep buying the same package :)
That's enough for now :)

control vs. I'll see later, thanks a lot :)

**Comment by mervantanrikulu** [comment]
function alevaldiliman'.$idx.'()
				{

		
													store.register({
														id:    "'.$fiyat.'",
														type:   store.CONSUMABLE
													});	
	
    store.when( "'.$fiyat.'").approved(function(order) {
 
        order.finish();
    });
												 store.off( "'.$fiyat.'");





													store.register({
														id:     "'.$fiyat.'",
														type:   store.CONSUMABLE
													});
												store.refresh();

												store.get( "'.$fiyat.'");

												store.order( "'.$fiyat.'");


												store.when( "'.$fiyat.'").approved(function(p) {
';

$_SESSION["odemekontrol"]="1";

echo'
    store.when( "'.$fiyat.'").approved(function(order) {
 
        order.finish();
    });			
							mecbur'.$idx.'();
												});
												
 }
	

Dude I want to use it as a variable.
but I can't close it because the dropdown backlog name is different.
can you show me the right way?
