### ISSUE TITLE
A question about google payment!

### ISSUE THREAD

**Issue by mervantanrikulu** [j3k0/cordova-plugin-purchase#1214]
good work my dear friend.

I use google payment method.
Can I get paid via iOS with this payment method?
Or do I need to use an iOS payment method?
I want to get paid with google pay on both android and ios.
does it work this way?

**Comment by Dexus** [comment]
No this is no G-Pay or Apple Pay Module!

**Comment by mervantanrikulu** [comment]
I think you misunderstood.I am using google in-app purchase module.Does google in-app purchase work in ios build?19:15, 12 Temmuz 2021, "Josef Fröhle" ***@***.***>:
No this is no G-Pay or Apple Pay Module!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Yandex.Mail mobil uygulamasından gönderildi

**Comment by Dexus** [comment]
No google playstore not working on Apple systems. So you need a Developer Account on each System to sell your items.

**Comment by mervantanrikulu** [comment]
I applied for an ios developer account. I need to rearrange my current application right? ie cordova google in-app purchase library does not work on ios. Different codes and iOS application library are required for iOS, do I understand correctly?

**Comment by Dexus** [comment]
You need an developer account for google playstore and Apple connect. If you have both Setup in the correct way and add your items for purchase you can with this plugin sell your in-App items.

No GPay no Applepay. 

And now please stop spam here with questions that answers you van also read in the docs. If you need commercial support, ask for it and you support this opensource and there supporters and developers.

Thanks!
