### ISSUE TITLE
[IOS] The data in the receipt-data property was malformed (error code :21002)

### ISSUE THREAD

**Issue by tolutronics** [j3k0/cordova-plugin-purchase#1226]
### system info

```
macOS Big Sur  11.4
Capacitor 2.
Device: iPhone iOS 13.3.2 
Plugin Version: 10.6.1

```

### Expected behavior
When the appStoreReceipt from the purchase response, is sent to backend for verification, apple should return a JSON containing the payment informations for further processes.
### Observed behavior
Each time the appStoreReceipt is sent to backend for verification, apple returns 21002 error code, which means the base64 is badly formatted.
### Steps to reproduce
Try to make payment and verify it to see the response

**Comment by tolutronics** [comment]
Solved,

**Comment by grantmk** [comment]
Any hints for those of us struggling with this?
