### ISSUE TITLE
The payment modal window is displayed for too long

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [j3k0/cordova-plugin-purchase#1228]
Device: iPhone iOS 14.7.1
the payment modal window is displayed for too long. About 3 seconds. Apple think that this is a bug. And does not approve the application

**Comment by mervantanrikulu** [comment]
![image](https://user-images.githubusercontent.com/32783110/128616272-4ba37aec-98fa-4818-bfa5-bd9cdb1a2177.png)


I agree friend.
I am also getting an error like this.

**Comment by mervantanrikulu** [comment]
were you able to find a solution?
late opening problem

**Comment by thenaim** [comment]
+ also getting

**Comment by fiverrproject** [comment]
m also getting this issue any buddy did get solution??
