### ISSUE TITLE
Windows Phone support planned?

### ISSUE THREAD

**Issue by EddyVerbruggen** [j3k0/cordova-plugin-purchase#124]
Hi,

Thanks for your efforts with this great plugin, I really appreciate that you made a unified iOS/Android plugin.

Do you plan on adding WP support as well? I found a [rudimentary WP8 implementation](https://github.com/kavukattu/phonegap-iap-wp8) but it needs some love. It would be awesome to have (at least basic) WP support in yours.

Thanks for considering,
Eddy

**Comment by writeosahon** [comment]
Hi @j3k0 @EddyVerbruggen thanks for the great plugin. I SUPPORT THIS REQUEST! PORT THIS PLUGIN TO WINDOWS PHONE!! Hybrid app developers on Windows Phone want to make more money as well.
Please consider this. Thanks

**Comment by j3k0** [comment]
Hi,

Considered. As you may have understand from me letting tons of issues pile up in the last few weeks, I'm really overbooked with clients work. However with a long term deadline (like late 2015) and some support I'll do it (with love)!

**Comment by j3k0** [comment]
Closed by #257

**Comment by dkarzon** [comment]
Just FYI, we now have Windows Phone support for 8.1 universal apps. This platform is called `windows` in cordova and will give you a Phone 8.1 and Store 8.1.

`cordova platform add windows` will add the platform for you.

**Comment by writeosahon** [comment]
Thanks for this guys!! Great work!
