### ISSUE TITLE
iOS Prices null ERROR 6777002

### ISSUE THREAD

**Issue by aklacar1** [j3k0/cordova-plugin-purchase#1240]
OSX BigSur 11.5.2
Cordova 10.0.0
Plugin Version: 10.6.1
Xcode: 12.5
Cordova ios: ~6.2.0
Platform tested on: Simulator and iPhone 5 + Failed review due to prices being null.

Issue:

ERROR: ios -> ERROR 6777002: Load failed: UNKNOWN_ERROR - {}

Android seems to work fine, but regarding ios I always get this error with no further proper data before or after this. Store products prices are not pulled and set as null (with error above).

**Comment by rafaellop** [comment]
Had exactly the same issue. Here's how I fixed it:
https://github.com/j3k0/cordova-plugin-purchase/issues/1238#issuecomment-918165516

TL;DR - the 10.x version sends application receipt validation calls to the backend and if you don't handle this calls then the store.ready is never true.

**Comment by aklacar1** [comment]
Does this happen always ? @rafaellop 

I mean I do not even get to the validation part, since I cannot purchase anything due to prices being null. Or you mean that before it even gets prices it calls for backend validation ?

**Comment by rafaellop** [comment]
Same 13 wrz 2021 15:21 Armin Klačar ***@***.***> napisał(a):
Does this happen always ? @rafaellop
I mean I do not even get to the validation part, since I cannot purchase anything due to prices being null. Or you mean that before it even gets prices it calls for backend validation ?

**Comment by rafaellop** [comment]
@aklacar1 Sorry for being brief in my previous reply. I was on a mobile in hurry.
