### ISSUE TITLE
[Android] Purchase failed: Product not registered

### ISSUE THREAD

**Issue by pedrumgolriz** [j3k0/cordova-plugin-purchase#1241]
### system info

MacOS 11.4
Plugin cordova-plugin-purchase 10.6.1
XCode version 12.1

### Expected behavior
User should be able to purchase Consumable and Non-Consumable IAP's

### Observed behavior
Consumable and Non-Consumable IAP's are displaying the "Product not registered" error.

### Steps to reproduce

On component initialization, after store is ready, I run the following:
```
for (let j = 0; j < this.credits.length; j++) {
      let options: IAPProductOptions = { "id": this.credits[j].storeURI, "type": this.store.CONSUMABLE, "alias": this.credits[j].storeURI };
      this.store.register(options);
      this.store.when(this.credits[j].storeURI)
        .approved((p: IAPProduct) => {
          p.finish();
        })
        .updated((p: IAPProduct)=>{
          console.log("credit",p);
          if(p.price){
            this.credits[j].price = p.price;
          }
        })
        .error((p: IAPProduct)=>{
          console.log(p.state);
        })
        .finished((p: IAPProduct) => {
          if (p.alias.indexOf('daily') == -1 && p.alias.indexOf('pages') > -1) {
            let chars: number = parseInt(localStorage.charactersRemaining) + (this.credits[j].value * 3000);
            localStorage.charactersRemaining = chars.toString();
          }
        })
    }
```

This used to work when it was a separate ionic page, but now as a component embedded in a page it fails. I am able to use the same style for loop to create subscriptions, but Consumables and Non-Consumables are failing. Any ideas?

Edit: This works perfectly fine on iOS

**Comment by pedrumgolriz** [comment]
Here is the log:
Angular is running in development mode. Call enableProdMode() to enable production mode.
bootstrap.js:12 Ionic Native: deviceready event fired after 538 ms
store-android.js:2172 [store.js] DEBUG: state: 3_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 5_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 10_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 20_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 50_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: store.trigger -> triggering action refreshed
store-android.js:2952 InAppBilling[js]: setup ok
store-android.js:2952 InAppBilling[js]: load ["3_pages_daily","5_pages_daily","10_pages_daily","20_pages_daily","50_pages_daily"]
store-android.js:2952 InAppBilling[js]: listener: {"type":"ready","data":{}}
store-android.js:2172 [store.js] DEBUG: plugin -> ready
store-android.js:2952 InAppBilling[js]: getAvailableProducts()
client:52 [WDS] Live Reloading enabled.
store-android.js:2172 [store.js] DEBUG: plugin -> loaded - [{"productId":"10_pages_daily","type":"subs","title":"10 Daily Pages (The Storyteller - AI Powered Text to Speech (TTS))","name":"10 Daily Pages","price":"$24.99","price_amount_micros":24990000,"price_currency_code":"USD","description":"10 Daily Pages + All Voice Actors + AD Free","subscriptionPeriod":"P1M","skuDetailsToken":"AEuhp4KfAKxthPHDKkzlm8tx3wWW5JQVvFDnJJ9gyJdvRXQQeahmGoNjVkN6WZTTDF0="},{"productId":"20_pages_daily","type":"subs","title":"20 Daily Pages (The Storyteller - AI Powered Text to Speech (TTS))","name":"20 Daily Pages","price":"$44.99","price_amount_micros":44990000,"price_currency_code":"USD","description":"20 Daily Pages + All Voice Actors + AD Free","subscriptionPeriod":"P1M","skuDetailsToken":"AEuhp4KB_IWN2p0VocNh90KUgPt4QwU0c9FXFUp4R4YVEhE5FvgsZL1yuSQ8Ef7kIOw="},{"productId":"3_pages_daily","type":"subs","title":"3 Daily Pages (The Storyteller - AI Powered Text to Speech (TTS))","name":"3 Daily Pages","price":"$9.99","price_amount_micros":9990000,"price_currency_code":"USD","description":"3 Daily Pages + All Voice Actors + AD Free","subscriptionPeriod":"P1M","skuDetailsToken":"AEuhp4JV_pPQhsHPqcLsldkavoxJ_izsMpOsalF9arWCGzZrIWV3GXwol0qbxjdlMOU="},{"productId":"50_pages_daily","type":"subs","title":"50 Daily Pages (The Storyteller - AI Powered Text to Speech (TTS))","name":"50 Daily Pages","price":"$99.99","price_amount_micros":99990000,"price_currency_code":"USD","description":"50 Daily Pages + All Voice Actors + AD Free","subscriptionPeriod":"P1M","skuDetailsToken":"AEuhp4LlEN3W4qDsX9WfKb-ATY_RuP0MjGMOBBx8rvZha9-LHKn5fCH-z6elIKYf8Pk="},{"productId":"5_pages_daily","type":"subs","title":"5 Daily Pages (The Storyteller - AI Powered Text to Speech (TTS))","name":"5 Daily Pages","price":"$14.99","price_amount_micros":14990000,"price_currency_code":"USD","description":"5 Daily Pages + All Voice Actors + AD Free","subscriptionPeriod":"P1M","skuDetailsToken":"AEuhp4I9jLfHU1uhcFYvgoyrQQT1ILu_NRCLPYUMeR3UuiWHoJhc83KPLHqVIq5Lscw="}]
store-android.js:2172 [store.js] DEBUG: state: 10_pages_daily -> valid
store-android.js:2172 [store.js] DEBUG: state: 20_pages_daily -> valid
store-android.js:2172 [store.js] DEBUG: state: 3_pages_daily -> valid
store-android.js:2172 [store.js] DEBUG: state: 50_pages_daily -> valid
store-android.js:2172 [store.js] DEBUG: state: 5_pages_daily -> valid
store-android.js:2172 [store.js] DEBUG: iabGetPurchases()
store-android.js:2952 InAppBilling[js]: getPurchases()
store-android.js:2952 InAppBilling[js]: listener: {"type":"setPurchases","data":{"purchases":[]}}
store-android.js:2172 [store.js] DEBUG: iabSetPurchases: []
store-android.js:2172 [store.js] DEBUG: inappbilling.getPurchases() -> Success
store-android.js:2172 [store.js] DEBUG:                             -> object
store-android.js:2172 [store.js] DEBUG:                             -> []
store-android.js:2172 [store.js] DEBUG: state: 3_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 5_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 10_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 20_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 50_pages_daily -> registered
store-android.js:2172 [store.js] DEBUG: state: 1_page -> registered
store-android.js:2172 [store.js] DEBUG: state: 5_pages -> registered
store-android.js:2172 [store.js] DEBUG: state: 10_pages -> registered
store-android.js:2172 [store.js] DEBUG: state: 50_pages -> registered
store-android.js:2172 [store.js] DEBUG: state: 100_pages -> registered
store-android.js:2172 [store.js] DEBUG: state: 1000_pages -> registered
store-android.js:2172 [store.js] DEBUG: iabGetPurchases()
store-android.js:2952 InAppBilling[js]: getPurchases()
store-android.js:2172 [store.js] DEBUG: iabUpdatePurchases: []
store-android.js:2172 [store.js] DEBUG: state: 3_pages_daily -> valid
shop.page.ts:89 subs store.Product
shop.page.ts:89 subs store.Product
store-android.js:2172 [store.js] DEBUG: state: 5_pages_daily -> valid
shop.page.ts:89 subs store.Product
shop.page.ts:89 subs store.Product
store-android.js:2172 [store.js] DEBUG: state: 10_pages_daily -> valid
shop.page.ts:89 subs store.Product
shop.page.ts:89 subs store.Product
store-android.js:2172 [store.js] DEBUG: state: 20_pages_daily -> valid
shop.page.ts:89 subs store.Product
shop.page.ts:89 subs store.Product
store-android.js:2172 [store.js] DEBUG: state: 50_pages_daily -> valid
shop.page.ts:89 subs store.Product
shop.page.ts:89 subs store.Product
store-android.js:2172 [store.js] DEBUG: state: 1_page -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: state: 5_pages -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: state: 10_pages -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: state: 50_pages -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: state: 100_pages -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: state: 1000_pages -> valid
shop.page.ts:121 credit store.Product
shop.page.ts:121 credit store.Product
store-android.js:2172 [store.js] DEBUG: store.trigger -> triggering action refresh-completed
store-android.js:2952 InAppBilling[js]: listener: {"type":"setPurchases","data":{"purchases":[]}}
store-android.js:2172 [store.js] DEBUG: iabSetPurchases: []
store-android.js:2172 [store.js] DEBUG: inappbilling.getPurchases() -> Success
store-android.js:2172 [store.js] DEBUG:                             -> object
store-android.js:2172 [store.js] DEBUG:                             -> []
store-android.js:2172 [store.js] DEBUG: iabUpdatePurchases: []
store-android.js:2172 [store.js] DEBUG: store.trigger -> triggering action refresh-finished
[store.js] DEBUG: state: 10_pages_daily -> requested
[store.js] DEBUG: state: 10_pages_daily -> initiated
InAppBilling[js]: buy()
[store.js] INFO: plugin -> buy error 6777003
store.Error {code: 6777003, message: 'Purchase failed: Product not registered: 5_pages'}
[store.js] DEBUG: state: 5_pages -> valid

**Comment by pedrumgolriz** [comment]
I noticed some odd behavior. I was able to fix the issue by using update instead of refresh, however the plugin only works after the page has been refreshed. Still trying to figure out why this is happening. Anyone??

**Comment by pedrumgolriz** [comment]
Okay was finally able to get this working. Since I had an instance of the plug-in working in the ionic tabs and the page, I had to use update instead of refresh after the initialization of all the IAP's. Also, when calling order, I now do a refresh and waiting for the complete callback.

**Comment by stefano24** [comment]
@pedrumgolriz Hi, i've the same issue on Android. Can you please share your snippet code of this part? When are you calling the update function, refresh and order?

**Comment by pedrumgolriz** [comment]
@stefano24 I had so much odd behavior, the only thing that finally worked was refreshing the page where the store items lived. This is not ideal for many use cases, and I assume it has to do with this specific version of the plugin as it works correctly in all my other apps.

**Comment by danieldanielecki** [comment]
It did happen to me on android when using `store.refresh()` **before** `store.register()`. Apparently, `Android` requires to have `store.refresh()` **after**  `store.order()`. On the other hand, `iOS`will work only in the opposite order with the `store.refresh()` being placed **before** `store.register()`. It can be easily debugged what the server returns using `JSON.stringify(store.products)` on a real device with `Android Studio`/`Xcode`. Can't believe it's not in the docs.

**Comment by joefaron** [comment]
i think these tutorials could be greatly expanded.. with something more than a "micro tutorial".

Anyways, the issue for me and this error was i was passing product and not offer to store.order().. as per:
```
[store.order() takes an offer](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13#storeorder-takes-an-offer)
When placing a purchase, you need to specify which of the product's offer you want to purchase. The store.order() method now the offer that you wish to initiate a purchase. For example:

const offer = product.getOffer("offer-id");
store.order(offer);
```

**Comment by danieldanielecki** [comment]
> It did happen to me on android when using `store.refresh()` **before** `store.register()`. Apparently, `Android` requires to have `store.refresh()` **after** `store.order()`. On the other hand, `iOS`will work only in the opposite order with the `store.refresh()` being placed **before** `store.register()`. It can be easily debugged what the server returns using `JSON.stringify(store.products)` on a real device with `Android Studio`/`Xcode`. Can't believe it's not in the docs.

with the newest plugin version it's no longer the case, workable solution is here https://github.com/Doyban/FlyingPlane/
