### ISSUE TITLE
Will the plugin support billing library version 3?

### ISSUE THREAD

**Issue by LucasBitello** [j3k0/cordova-plugin-purchase#1244]

**Comment by smokyweb** [comment]
same issue with me today.
any solution
![Uploading Screenshot 2021-09-23 at 6.46.45 PM.png…]()
?
https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

**Comment by nitindme** [comment]
We've detected that this app uses an unsupported version of Play Billing. Please upgrade to Billing Library version 3 or newer to publish this app. Learn more about Billing Library 3.

Any Solution?

**Comment by j3k0** [comment]
Hello, the plugin does use the Billing Library v3 and has been for more than a year. If you're using a recent version, you are fine.

That's the only framework referenced in the `plugin.xml` file.

<img width="655" alt="Screen Shot 2021-10-14 at 07 57 43" src="https://user-images.githubusercontent.com/191881/137254579-8f6a60d1-dd12-4598-8f0b-c8d4824e5e5f.png">

You can check the Android code, it's using Billing v3 APIs only.

I've noticed this error on other apps we develop without Cordova, it happened when one of the publishing tracks still contain an old version, so Google considers some user might still have access to the deprecated APIs.
