### ISSUE TITLE
[ANDROID] Billing Library v3 support

### ISSUE THREAD

**Issue by GrandWin** [j3k0/cordova-plugin-purchase#1250]
Starting August 2, 2021, all new apps must use Billing Library version 3 or newer.

When trying to download an application to google play, it writes:
>We've detected that this app uses an unsupported version of Play Billing. Please upgrade to Billing Library version 3 or newer to publish this app. Learn more about Billing Library 3.

Do you plan to support version 3 of this library?

**Comment by j3k0** [comment]
Not a plan: it's supported since July 2020. Are you sure you are using a recent version of the plugin?

That is the only library used by the plugin on Android: `<framework src="com.android.billingclient:billing:3.0.3" />`
