### ISSUE TITLE
PAID_SUBSCRIPTION problem

### ISSUE THREAD

**Issue by mervantanrikulu** [j3k0/cordova-plugin-purchase#1253]
my code 

                       store.register({
														id:    "xdomain",
														type: store.PAID_SUBSCRIPTION,
													});

I am using the subscription system.
but as PAID_SUBSCRIPTION, the user can buy the same product 2 times.
I want to make it a consumable subscription.
can you please help me?

**Comment by mervantanrikulu** [comment]
how should i use it?

**Comment by mervantanrikulu** [comment]
I am selling domain name. man subscribed once. but he wants to buy another domain name. this is my situation.

**Comment by j3k0** [comment]
Hello, please read the documentation from Apple about non-renewing subscription, then the plugin's documentation will show you how to achieve that.

**Comment by j3k0** [comment]
> I am selling domain name. man subscribed once. but he wants to buy another domain name. this is my situation.

Then sell non-renewing subscriptions or consumable. PAID_SUBSCRIPTIONS can only be purchased once. It's for a single subscription.

Honestly, Apple/Google services are not very well suited for those kind of use cases...

**Comment by ipehimanshu** [comment]
can you help us, 
we are getting error like

InAppPurchase[objc]: Product (yearly_plan) does not exist or is not sucessfully initialized.

and we are adding paid subscription for auto renewing, but when we register product and after some time log comes like

![image](https://user-images.githubusercontent.com/26652038/150926732-db96f02b-c175-4dd8-a99f-69c633d30fc7.png)

Android all working great, issue only for ios.

Thanks
