### ISSUE TITLE
[IOS][ANDROID] Track purchased non consumable purchase after reinstall, or on a different device?

### ISSUE THREAD

**Issue by Mike-the-one** [j3k0/cordova-plugin-purchase#1255]
Hi, this is a question.

I am making an ad-based app, offer user to purchase the app to remove the ads.
So I am wondering how do I know if the user has previously purchased the app after reinstall the app, or use multiple devices?

I looked at the API, is `store.refresh()` the correct API to call?  Are non consumable products purchases/transactions tracked in ios and android billing system forever?

Thanks

**Comment by losciur** [comment]
Hi,
as I wrote in this recent issue: https://github.com/j3k0/cordova-plugin-purchase/issues/1363
I have the same problem but only for iOS, while Android works correctly.
The `store.refresh()` doesn't resolve the problem.
