### ISSUE TITLE
Server Side Validator Code

### ISSUE THREAD

**Issue by GregLawson1981** [j3k0/cordova-plugin-purchase#1256]
Hi There

So i am trying to get the Receipt validation to work my my in app subscriptions. I have a pretty good idea of what the controls needed are but the part I cannot figure out is what the server side code for the validator URL needs to return. 

Is there a more detailed example of the subscription and validation server side script?

**Comment by vesper8** [comment]
The expected response object is detailed here https://billing.fovea.cc/documentation/api/v1/validate/
