### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by shamamit11** [j3k0/cordova-plugin-purchase#126]
Hello,
I am getting error as attached in the screenshot whenever I try to build the app for Android.
It says Plugin failed to install. I am using Intel XDK to build and package my app.

But, it works well and fine when I build for iOS. Is there something I missing.
Can someone help on this?

Thanks !!
![failed](https://cloud.githubusercontent.com/assets/10370106/5775728/0af1395a-9da6-11e4-836b-bf91fbb51c87.JPG)

**Comment by valueerrorx** [comment]
how did you add the plugin to your project? 
did you enter the name "cc.fovea.cordova.purchase"
did you also add your license number --variable MIIB...  
did you check the checkbox that the plugin is located in the plugin registry?
