### ISSUE TITLE
BILLING permission to your APK

### ISSUE THREAD

**Issue by gmbad** [j3k0/cordova-plugin-purchase#1263]
Hello there,

In Google play console, products > in-app products, I get the following message:

**"To add in-app products, you need to add the BILLING permission to your APK"**

I've already uploaded the package (app-release.aab), with the cordova-plugin-purchase plugin...

Do I need to create some permissions in config.xml?

Thank you very much!!

Gabriel

**Comment by vvvzp** [comment]
put into platform android section this options
<config-file parent="/*" target="AndroidManifest.xml">
    <uses-permission android:name="com.android.vending.BILLING" />
</config-file>
or modify /config-file if it present

hope it help you!

**Comment by bitbay** [comment]
As of `Google Play Billing Library` You do not have to set explicitly the permission,
Read over [here](https://developer.android.com/google/play/billing/migrate#remove)
> The Google Play Billing Library embeds the com.android.vending.BILLING permission inside its manifest. It is no longer necessary to explicitly add this permission inside your app's manifest.

**Comment by j3k0** [comment]
Yes, in any case the plugin also adds the permission to the android manifest. If it's correctly installed (meaning there was no error while installing the plugin), it should be there.

```xml
      <config-file target="AndroidManifest.xml" parent="/*">
        <uses-permission android:name="com.android.vending.BILLING" />
      </config-file>
```

You can check the generated AndroidManifest.xml in the platforms/android directory if you want to make sure of that...
