### ISSUE TITLE
[IOS] Validator is getting called without approved event on iOS

### ISSUE THREAD

**Issue by bhaskar-se** [j3k0/cordova-plugin-purchase#1269]
Hi @j3k0 I'm having an issue with the validator on iOS. I have gone through all the available issues but haven't found any solutions for this.
In my case I am configuring the validator as function under which I call my own web service in order to validate the auto-renewable subscriptions and based on the response I use the `callback` function. Everything works fine on android but not in case of iOS

### system info
```
macOS Catalina 10.15.7
Cordova 8.1.2
Device: iPhone iOS 15.1
Plugin Version: 10.6.1
```

### Expected behavior
In case there's a pending purchase product `approved` event should be fired initially and then validator should get invoked once I call the `verify()`. Also `refreshed` should get triggered once everything completes (finishing pending purchases).

### Observed behavior
Product `approved`  event isn't fired so, no chance of calling `verify()`. But validator gets invoked initially on app launch, and it goes into a loop (doesn't matter what the response or error is). Also the `refreshed` callback never called. Therefore I'm neither able to show products nor make any further purchases. 

### Steps to reproduce
1. Subscribe any plan
2. Close the app after a successful subscription
3. Re-launch the app

### Code snippet
```
constructor() {
    this.inAppPurchase.validator = (product: IAPProduct, callback) => {
      this.myService.validateReceipt(saleReferencePayload).subscribe(
        (res) => {
          if (res && res.IsValidated) 
            callback(true, { transaction: product.transaction });  
          else
            callback(false, {
              code: this.inAppPurchase.INTERNAL_ERROR,
              error: {
                message: 'Failed to validate receipt.',
              },
            });
        },
        (err) =>
          callback(false, {
            code: this.inAppPurchase.INTERNAL_ERROR,
            error: {
              message: 'Failed to validate receipt.',
            },
          });
      )
    }

    this.inAppPurchase
      .when(SUBSCRIPTION)
      .approved((approvedProduct: IAPProduct) => {
        if (this.isUserLoggedIn && approvedProduct.transaction) {
          approvedProduct.verify()
        }
      })

    this.inAppPurchase
      .when(SUBSCRIPTION)
      .verified((verifiedProduct: IAPProduct) => {
        if (this.isUserLoggedIn) {
          verifiedProduct.finish()
        }
      })

    this.inAppPurchase.once(SUBSCRIPTION).owned((ownedProduct: IAPProduct) => {
      if (this.isUserLoggedIn) {
        alert('suscription success!')
      }
    })

     this.inAppPurchase.register(products)

     this.inAppPurchase.refresh().finished(() => {
              alert('product registered!')
     })
}
```

**Comment by j3k0** [comment]
On iOS, you validator should also return a correct result for the application receipt (`product.type == store.APPLICATION`). If you return an error like `INTERNAL_ERROR`, the plugin will retry the request (as it considers it hasn't been able to perform a validation).

You need to returned error code that represents the state of the receipt (`EXPIRED`, ...).

**Comment by bhaskar-se** [comment]
Thanks for the information.

But shouldn't there be an option to configure the exponential backoff as per our need?
Currently the implementation takes around 146000 ms (combined) to throw an error in case of `INTERNAL_ERROR` .

Also, I've a question why there's a need to validate the product which is having a package id? Is it because iOS receipts contains all purchases and validating the one can restore other purchases too, which will eventually help to not to call storeKit for each purchase receipts on initial refresh?

**Comment by vlad-d** [comment]
> On iOS, you validator should also return a correct result for the application receipt (`product.type == store.APPLICATION`). If you return an error like `INTERNAL_ERROR`, the plugin will retry the request (as it considers it hasn't been able to perform a validation).
> 
> You need to returned error code that represents the state of the receipt (`EXPIRED`, ...).

Hi @j3k0! I noticed that even if I do return the code that represents the state of the receipt, the plugin will still retry the request many times and the product state will go back to 'approved'.

```
callback(
    false,
    {
        code: store.PURCHASE_CONSUMED,
        error: {
            message
        }
    }
);
```
