### ISSUE TITLE
Unable to find global store or iap object in angular v1

### ISSUE THREAD

**Issue by kevinswartz** [j3k0/cordova-plugin-purchase#1270]
Thank you for this plugin!  

Sorry if this is documented somewhere, but I can't seem to track down a solution.  I'm using an angular v1/ionic v1 project, and trying to migrate from https://github.com/AlexDisler/cordova-plugin-inapppurchase.  I do not see a `store` or `InAppPurchase2` object that I can reference globally.  How do I interact with this plugin?

Relevant plugin versions:
cordova-plugin-purchase v10.6.1
cordova-plugin-network-information v1.3.4
cordova-plugin-advanced-http v3.2.2

Here's my `ionic info`:
```
Ionic:

   Ionic CLI         : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 3.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 30 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.11.0
   native-run (update available: 1.5.0)   : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/[redacted]/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Monterey
   Xcode             : Xcode 13.1 Build version 13A1030d

```

Thanks for your help!

**Comment by j3k0** [comment]
There is some minimal example code here:

https://ionicframework.com/docs/native/in-app-purchase-2/

Did you try that?

**Comment by kevinswartz** [comment]
Thanks @j3k0 .  I did look at that.  I cannot use `import` statements here.  This is Angular v1 with Ionic v1.  Most plugins supply some kind of object on `window` that I'm able to interact with.  Thanks!

**Comment by kevinswartz** [comment]
Hi @j3k0 ,
Just wanted to follow up with you about this.  I tried the example code, but ionic v1 does not support ES6 import statements as in: `import { InAppPurchase2 } from '@awesome-cordova-plugins/in-app-purchase-2/ngx';`

Are there any options for Angular v1 plugins?  Thanks!

**Comment by viking2917** [comment]
hi @kevinswartz i use this plugin for angulaar v1. once the plugin is installed it defines a global var called store, which you interact with. e.g. here: https://purchase.cordova.fovea.cc/discover/micro-example. i mostly followed the instructions starting here: https://purchase.cordova.fovea.cc/discover/micro-example

**Comment by kevinswartz** [comment]
Thanks @viking2917, I'm not sure why I wasn't seeing the store global variable before, but I tried things again today and it's working for me.  Thanks for your help!
