### ISSUE TITLE
[IOS] Store not ready and missing products details (new install from TestFlight or XCode)

### ISSUE THREAD

**Issue by amine-labassi** [j3k0/cordova-plugin-purchase#1271]
# [IOS] Store not ready and missing products details (new install from TestFlight or XCode)

### system info

macOS BigSur 11.6
iOS 15.1 (19B74)
Model: iPhone 8 (Model A1863, A1905, A1906, A1907)
Cordova 10.0.0
Plugin version 10.6.1

### Expected behavior

1. Delete app from device
2. Run Xcode to start app en device
3. Check if store is ready -> ready and products details loaded

> Store is expected to be ready since the first app run after a new install from XCode or TestFlight

### Observed behavior

1. Delete app from device
2. Run Xcode to start app en device
3. Check if store is ready -> not ready and products details not loaded
4. Restart the app again from XCode 
5. Check if store is ready -> ready and products details loaded

> We need to restart the app a second time, to get store ready and able to retrieve products details
> This issue happens only on the very first app run after new install from Xcode or TestFlight

### Steps to reproduce

1. Delete app from device
2. Run Xcode to start app en device
3. Check if store is ready

**Comment by combondrn** [comment]
@amine-labassi I have encountered the issue you describe above.  Would you mind sharing your resolution or conclusion?
