### ISSUE TITLE
Product state is invalid.

### ISSUE THREAD

**Issue by frg** [j3k0/cordova-plugin-purchase#128]
Hi,
I'm trying to register a product but the product is being marked as invalid on initiation.

I'm using the "product id" is set when creating the product in the in app purchases section.

Does it matter if the "In-App Purchase" hasnt been submitted for review? Does it have to be accepted even during the testing stage?

Thanks in advance!
Jean

**Comment by omaxlive** [comment]
I have the same problem. Did you solved it or can someone tell us how to solve this?

Thanks,

**Comment by frg** [comment]
@omaxlive I haven't worked on this in a while sorry. If I get the chance I'll find the code and let you know how I solved this.

**Comment by AbuHani** [comment]
any updates ???

**Comment by j3k0** [comment]
https://github.com/j3k0/cordova-plugin-purchase/wiki/F.A.Q.#products-wont-load-invalid-product-id
