### ISSUE TITLE
How to use without framework?

### ISSUE THREAD

**Issue by osbulbul** [j3k0/cordova-plugin-purchase#1280]
Hey,

I am making browser game with PhaserJS and turn it to mobile via CapacitorJS. It's not ionic or cordova project, just one html file and bunch of plain JavaScript, bundling with ViteJS. I am trying to implement some in-app purchase. I installed the package via `npm install cordova-plugin-purchase` command. But what should I do/import to use "store" as example at https://purchase.cordova.fovea.cc/use-cases/non-consumable-ios ?

I couldn't find any example without framework, just in CapacitorJS.

Thanks

**Comment by bitbay** [comment]
Hello @osbulbul , where did You find that `capacitorjs` example? I'm having trouble using that...
Or did You mean `ionic`?

As for Your question, two things:
1. This plugin supposed to be a wrapper/brindge between platform native code and html javascript. Without the "native" part You'll lack real functionality.
2. capacitorjs isn't a "framework" for Your application. It is a framework agnostic, "cross-platform native runtime for web apps". You decide the framework of Yours for Your *web app*

**Comment by osbulbul** [comment]
Hey @bitbay , I think the problem is solved. I couldn't reach the "store" or "window.store" variable, but I can reach it now. Maybe something was wrong about the project setup before, but problem not happening right now. Thanks for interest.
