### ISSUE TITLE
[android] Subscription upgrade does not cancel last purchase

### ISSUE THREAD

**Issue by jijimaro** [j3k0/cordova-plugin-purchase#1283]
# Subscription upgrade does not cancel last purchase

### system info
monaca
Cordova 10.0.0
Device: android  11 
cordova-plugin-purchase 10.5.3

### Expected behavior
We are developing an in-app purchase subscription for ios and Android with cordova-plugin-purchase on Monaca.
ios is complete, but Android's store.order for Google Play Billing Library doesn't work as expected, the last purchased product isn't canceled, and it's a double purchase.

### Observed behavior
Response from cordova-plugin-purchase
---"additionalData"":{""oldSku"":""g2000"",""prorationMode"":""DEFERRED"",""discount"":"""",""applicationUsername"":""""},""transaction"":{""type"":""android-playstore"",""id"":""GPA.xxxx"",""purchaseToken"":""xxxx"",""purchaseState"":0,""receipt"":""{\""orderId\"":\""GPA.xxxx\"",\""packageName\"":\""xxxx\"",\""productId\"":\""g3000\""----

Google Play Developer API --Response from Purchases.subscriptions (after receipt verification)
{""startTimeMillis"":""xxxx"",""expiryTimeMillis"":""xxxx"",""autoRenewing"":true,""priceCurrencyCode"":""JPY"",""priceAmountMicros"":""xxxx"",""countryCode"":""JP"",""developerPayload"":"""",""paymentState"":1,""orderId"":""GPA.xxxx"",""purchaseType"":0,""acknowledgementState"":0,""kind"":""androidpublisher#subscriptionPurchase""}

**Maybe linkedPurchaseToken will be included in the response from google API.**

**As a result, there are two subscriptions.**

**What is the correct way to upgrade my subscription?**

### Steps to reproduce
store.order(xproduct_id, { oldSku: oldproduct_id, prorationMode: 'DEFERRED' ,discount:''});

**Comment by j3k0** [comment]
Is this issue solved? Please re-open if you need assistance (or have more details).

Notice that `oldPurchaseToken` is also required on Android, however the plugin should be able to figure it out from the `oldSku`. Worth trying.

https://github.com/j3k0/cordova-plugin-purchase/blob/master/RELEASE_NOTES.md#update-the-subscription-upgrade--downgrade
