### ISSUE TITLE
iOS doesn't load plans Owned: False when there is already a plan Owned: True

### ISSUE THREAD

**Issue by jopegon81** [j3k0/cordova-plugin-purchase#1295]
On iOS if there is no plan subscribed it loads fine and all plans are available.

But after subscribing to a plan, all other plans become unavailable. A couple of weeks ago it was working well.
On android always worked well too and still does.

![IMG_20220310_163316](https://user-images.githubusercontent.com/86534102/159039106-c3ca4e0a-9418-4954-acd4-5bb98f96df0c.jpg)

**Comment by j3k0** [comment]
What's weird is `Valid: False` which seems to indicate that the details for the product cannot be loaded from the App Store, which means it is unavailable and cannot be purchased (thus "canPurchase: false")
