### ISSUE TITLE
Object list getting null.

### ISSUE THREAD

**Issue by vipinkumarparas** [j3k0/cordova-plugin-purchase#1297]
{"id":"io.cameron.com","alias":"videoid","type":"consumable","group":"","state":"valid","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":true,"canPurchase":true,"owned":false,"introPrice":null,"introPriceMicros":null,"introPricePeriod":null,"introPriceNumberOfPeriods":null,"introPricePeriodUnit":null,"introPriceSubscriptionPeriod":null,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":{"applicationUsername":""},"transaction":null,"valid":true}

Is there any solution and suggestion ?

**Comment by j3k0** [comment]
Need more info. Code, logs. Please read and fill the issue template provided or we cannot help.

**Comment by bjkuncorokk** [comment]
for me, this happen when using `store.get(id)`, this function return the product object but the problem is, all value of the object is `null`, and just alias and id have a right value,
this is my product object
`{
    "id": "200_kakoin",
    "alias": "200_kakoin",
    "type": "consumable",
    "group": "",
    "state": "valid",
    "title": null,
    "description": null,
    "priceMicros": null,
    "price": null,
    "currency": null,
    "countryCode": null,
    "loaded": true,
    "canPurchase": true,
    "owned": false,
    "introPrice": null,
    "introPriceMicros": null,
    "introPricePeriod": null,
    "introPriceNumberOfPeriods": null,
    "introPricePeriodUnit": null,
    "introPriceSubscriptionPeriod": null,
    "introPricePaymentMode": null,
    "ineligibleForIntroPrice": null,
    "discounts": [],
    "downloading": false,
    "downloaded": false,
    "additionalData": null,
    "transaction": null,
    "valid": true
}`

**Comment by j3k0** [comment]
@bjkuncorokk Can you provide additional information? Logs and/or source code?

**Comment by j3k0** [comment]
Good, thanks for the details!
