### ISSUE TITLE
when('product').approved trigger multiple times

### ISSUE THREAD

**Issue by dodomui** [j3k0/cordova-plugin-purchase#1298]
### Observed behavior
in IOS, when('product').approved trigger multiple times while a user performs IAP action.

_Include logs with `store.verbosity = store.DEBUG`_

### System Info

Output of `cordova info`.

**Comment by nosTa1337** [comment]
Same behaviour here. Did you solve it?

**Comment by dodomui** [comment]
> Same behaviour here. Did you solve it? It also triggers on initalization on my test device with no active iap.

Erm... it's weird if it triggers initialization without action.
My solution is not perfect, I set a flag and let the action wait random time then only proceed if any other action had already processing the IAP action.

**Comment by j3k0** [comment]
`when('product').approved` might be called for every pending transactions (on iOS), as well as the "application" product. Notice that all previous transactions will be replayed if you call `store.refresh()` a second time in the lifetime of your app.

It should only be called once, except if the user clicks "restore purchases"

**Comment by dodomui** [comment]
I had call `store.refresh` once.

I noticed that it not just trigger the when('product').approve twice.
It did double charge the consumer.

**Comment by dodomui** [comment]
@nosTa1337 Do you still having the issue?
