### ISSUE TITLE
How to use webhooks from fovea?

### ISSUE THREAD

**Issue by mayankkataria** [j3k0/cordova-plugin-purchase#1302]
I understood the working of webhooks but I don't know how to implement it. I'm using cloud firestore as my backend server. I want to delete user's document when user's subscription is cancelled or expired. Which webhook url should I insert in my fovea settings?

**Comment by j3k0** [comment]
Hello @mayankkataria,

Fovea will inform your servers of changes to a user subscription. The best approach for your case is probably to have cron job that checks for expired subscription every day (or hour, or whatever) and do this cleanup.

The URL you setup will be an address on your server that updates the subscription expiry date for each your users.
