### ISSUE TITLE
approved is supposed to be run multiple times?

### ISSUE THREAD

**Issue by GroverBhumika** [j3k0/cordova-plugin-purchase#1303]
I have faced Approved event hit Multiple times

  makePayment() {
    this.registerHandlersForPurchase(this.PURCHASE_KEY);         // this.PURCHASE_KEY is payment id
    try {
      let product = this.iap2.get(this.PURCHASE_KEY);
      console.log('Product Info: ' + JSON.stringify(product));
      this.iap2.order(this.PURCHASE_KEY).then((p) => {
        console.log('Purchase Succesful' + JSON.stringify(p));
      }).catch((e) => {
        console.log('Error Ordering From Store' + e);
      });
    } catch (err) {
      console.log('Error Ordering ' + JSON.stringify(err));
    }
  }
  

/*--------------------------------*/
  this.registerHandlersForPurchase(){.   
      this.iap2.when(productId).approved((product: IAPProduct) => {
       product.finish()
       this.storePayment(product)         // Function Used for save Transaction value in DB...
    });
}

/*--------------------------------*/

  ngOnDestroy() {
    this.iap2.off(this.PURCHASE_KEY);
  }
  
  
  
  Ionic -> Cordova
    "@ionic-native/in-app-purchase": "^5.36.0",
    "@ionic-native/in-app-purchase-2": "^5.36.0",

**Comment by j3k0** [comment]
This `registerHandlersForPurchase` method SHOULD be run at application startup. Some purchases might be initiated outside the app (promo codes, family sharing, etc.), or pending from a previous session that might have happened on a different device (lost internet during a purchase, phone call that exits the app, etc).

It very possible with your approach that you are registering the handler multiple times...

Make sure you follow the documentation, the recommended approach is for your app to be ready to process the transactions queue at startup. Calling "store.order" will just be one of the ways to initiate a purchase.
