### ISSUE TITLE
Localization for in-app items (consumables)

### ISSUE THREAD

**Issue by dimitriscsd** [j3k0/cordova-plugin-purchase#1304]
I have set everything up and it works well.

However, we have recently added localizations for titles and descriptions in 5 languages on app store connect.

When testing, the items come back with the titles and descriptions always in English, even though we have switched the device's language to something else.

The main description of the app on the store, which is also localized, appears in the correct language.

Any ideas?

Is there anything extra required to be added in the ionic/cordova side for this to work?

**Comment by j3k0** [comment]
Let's assume you are talking about iOS (there is no mention of the platform in your message). The localization depends on the country of the App Store your device is connected to (which defines which products are available and the proper locale to use).

**Comment by dimitriscsd** [comment]
Thanks for the reply. Yes it was for iOS. Figured it out in the end.

Just for the history, in my app at least, the language follows the device and not the account of the playstore.

Thanks for looking into it anyway :)

**Comment by j3k0** [comment]
Thanks for the follow up. Good to hear it's all figured out.
