### ISSUE TITLE
[ANDROID] Migrate to Google Play Billing Library 5

### ISSUE THREAD

**Issue by FischerTech** [j3k0/cordova-plugin-purchase#1306]
Migration to Google Play Billing Library 5 for new subscription model.

As of May 2022, Google has changed the way it handles new subscriptions in the play console. Subscriptions now have bas plans and offers. In the current implementation you can only offer one of the base plans in your subscription. For example, if you have an option for either a monthly, quarterly, or yearly subscription, you can only set one as the default to be shown with Billing Library Version 4, preventing the users from seeing the other available plans.

Subscription Changes Guid: https://developer.android.com/google/play/billing/compatibility
Migration Guide: https://developer.android.com/google/play/billing/migrate-gpblv5

**Comment by j3k0** [comment]
Work is in progress #1308 and under testing - loading products and making a purchase have been tested. I'll close so the discussion goes in the PR.
