### ISSUE TITLE
[iOS] validator request missing data

### ISSUE THREAD

**Issue by dftd** [j3k0/cordova-plugin-purchase#1309]
`additionalData`, and most of the other parameters are empty on the validator on iOS.

```
Array
(
    [id] => ...
    [alias] => application
    [type] => application
    [group] => 
    [state] => approved
    [title] => 
    [description] => 
    [priceMicros] => 
    [price] => 
    [currency] => 
    [countryCode] => 
    [loaded] => 1
    [canPurchase] => 
    [owned] => 
    [introPrice] => 
    [introPriceMicros] => 
    [introPricePeriod] => 
    [introPriceNumberOfPeriods] => 
    [introPricePeriodUnit] => 
    [introPriceSubscriptionPeriod] => 
    [introPricePaymentMode] => 
    [ineligibleForIntroPrice] => 
    [discounts] => Array
        (
        )

    [downloading] => 
    [downloaded] => 
    [additionalData] => 
    [transaction] => Array
        (
            [type] => ios-appstore
            [appStoreReceipt] => // this isn't empty but removed it here
        )

    [version] => 1.0.1
    [valid] => 1
)
```

**Comment by j3k0** [comment]
`additionalData` should contain the `applicationUsername` if `store.applicationUsername` contains (or returns) a value, which is your app's responsability.

Other fields are expected to be empty for the `application` product receipt. It's not missing.

**Comment by dftd** [comment]
I supply `additionalData` in the `store.order()` method like documented here:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeorderproduct-additionaldata

On Android I get that data back on the validator, but not on iOS.

However, I think it might be related to the fact that I'm not testing on a real device. Will check that at some point.
