### ISSUE TITLE
empty product object

### ISSUE THREAD

**Issue by mnesrine** [j3k0/cordova-plugin-purchase#1310]
Hi guys

After I register my products in the google play , I get empty object

`{"id":"sb-01","alias":"sb-01","type":"paid subscription","group":"default","state":"valid","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":true,"canPurchase":true,"owned":false,"introPrice":null,"introPriceMicros":null,"introPricePeriod":null,"introPriceNumberOfPeriods":null,"introPricePeriodUnit":null,"introPriceSubscriptionPeriod":null,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"valid":true}`

it's happens on Android only!!!
iOS working fine.

Anyone know of anything similar?

**Comment by mnesrine** [comment]
This issue occurs in subscriptions on Android, in iOS it's working fine.
Nobody has the same problem?

**Comment by Hyllesen** [comment]
@mnesrine 
I'm struggling with the same problem currently. Did you find a solution to this?

**Comment by Hyllesen** [comment]
> Google's v5 API is backward compatible with v4. You just need to create each subscription (product ID) at the top level with one active base plan. You register the product IDs with the IAP plugin. If you have multiple base plans under a subscription, v4 will only load the one marked as "Backwards compatible".

I believe this is what I've done here?
![image](https://user-images.githubusercontent.com/9279498/180118605-84e22163-60c3-4e98-a263-5cbb19c9b37e.png)
![image](https://user-images.githubusercontent.com/9279498/180118656-b893aba3-378d-4980-b867-0e8c2d45c165.png)

The I register and refresh store.
I can purchase the product and see the price when I tap to buy, and it opens the purchase dialog from Play Store, so I'm guessing my billing key is working properly.

**Comment by Hyllesen** [comment]
After downgrading the cordova-plugin-purchase from v5 branch to current one, I am now getting the price again.

**Comment by vetalfa** [comment]
@Hyllesen what exactly did you do? Downgraded the plugin version or the gradle version of billing client? Thanks in advance

**Comment by Hyllesen** [comment]
> @Hyllesen what exactly did you do? Downgraded the plugin version or the gradle version of billing client? Thanks in advance

Downgraded the plugin version to the current master branch, not the updated v5
