### ISSUE TITLE
acknowledge is needed in paid subscription

### ISSUE THREAD

**Issue by pdaccache** [j3k0/cordova-plugin-purchase#1318]
I have implemented this plugin in my cordova app, it is working perfectly but once a payment is made it is being refinded after 3 days and 10 minutes exactly how to perform an acknowledgment once a subscription is bought? it is not mentioned in the documentation.
i have followed the below to install and configure the plugin:
- https://purchase.cordova.fovea.cc/use-cases/subscription-android

**Comment by Almerick** [comment]
To my awareness, acknowledging a transaction happens at a Google Developer API level, not as part of this plugin. To implement, follow Google's Developer documentation: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/acknowledge.

**Comment by pdaccache** [comment]
Yes it was related to the store validator i have managed to make it work but setting up the fovea billing in order to perform acknowledgments.

Thank you

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by j3k0** [comment]
Actually, just calling `product.finish()` will acknowledge the purchase for subscriptions.

Normally you do that after a successfull receipt validation (which should confirm that the user is associated with the subscription).

```js
store.when()
.approved(p => p.verify())
.verified(p => p.finish());
```

**Comment by mashrurbd** [comment]
> Actually, just calling `product.finish()` will acknowledge the purchase for subscriptions.
> 
> Normally you do that after a successfull receipt validation (which should confirm that the user is associated with the subscription).
> 
> ```js
> store.when()
> .approved(p => p.verify())
> .verified(p => p.finish());
> ```

No man, it doesn't. For consumables, the .finish() thing doesn't work. Google play refunds my payment due to not acknowledging the purchase. Let me know how to fix it.
