### ISSUE TITLE
[Android] Cannot register Non-Renewing Subscription

### ISSUE THREAD

**Issue by nagasiNR** [j3k0/cordova-plugin-purchase#1323]
Hi! I want to setup In App Purchase with Non-Renewing Subscription but in "loaded" callback I receive invalid product.

I use the latest cordova-plugin-purchase (with Android Billing v5)
"cordova-plugin-purchase": "git+https://github.com/j3k0/cordova-plugin-purchase.git",

I set correct BILLING_KEY for plugin
I use type of subscription NON_RENEWING_SUBSCRIPTION
Subscription was created in new Android subscription structure (with base plans and offers)
App was published for Beta testing (hasn't been published for production yet)
Product registration code
```
 this.inAppPurchase.register({
      id: productId,
      alias: productId,
      type: this.inAppPurchase.NON_RENEWING_SUBSCRIPTION,
  });
```
Android Target SDK = v30
Ionic plugins
"@awesome-cordova-plugins/core": "^5.44.0",
"@awesome-cordova-plugins/in-app-purchase-2": "^5.44.0",

cordova-android: 10.0.1

Is there a problem with the plugin?

Tips and tricks are welcome! :)

**Comment by jordanrzymski** [comment]
I am having the same issue

**Comment by JHdezC** [comment]
I am having the same issue, did you find any solution?

**Comment by redalpha01** [comment]
+1

**Comment by j3k0** [comment]
Closing old issues, please reopen if you have a similar issue with version 13 of the plugin.
