### ISSUE TITLE
Google Play subscriptions

### ISSUE THREAD

**Issue by gee1k** [j3k0/cordova-plugin-purchase#1324]
Hi, I'm using the master branch to access the latest Google Play subscriptions.
I have two plans for my subscriptions, but the plugin is returning me three. The first two are my monthly subscription plans and the third is a yearly subscription plan. I see that they both are not exact duplicates, but both are in purchasable status. I'm not sure how I should filter and present them on the UI. Please help me!

Translated with www.DeepL.com/Translator (free version)

<img width="734" alt="image" src="https://user-images.githubusercontent.com/12059800/185569983-d66ffd77-32f9-4d1c-8726-9700bf065933.png">

<img width="366" alt="image" src="https://user-images.githubusercontent.com/12059800/185570086-fdf24aba-783e-49bc-9fdf-da43c86a4437.png">

**Comment by julobato** [comment]
Hey, how did you make to appear multiple plans? I already created the base plans in Google Play Console for the same subscription but when ordering the product, it automatically selects the monthly plan

How did you register them?

**Comment by janne-rantala** [comment]
Same here. I can register only the main subscription product ID, but not the base plans, which actually hold the information, prices, durations, etc

**Comment by janne-rantala** [comment]
@julobato it seems that the latest release 11 does not support new Google's subscriptions. But you can use the branch v13, which does. Check also this example to use it https://gist.github.com/j3k0/8b7e72b6af43572651328c613ac86d59
