### ISSUE TITLE
Fovea doesn't send webhooks for expired subscriptions, unless I manually click refresh on Dashboard

### ISSUE THREAD

**Issue by cm-cm-cm-cm** [j3k0/cordova-plugin-purchase#1326]
1. I buy a auto-renewable play store subscription in my app (sandbox mode = it's a 5 minute subscription)
2. Receipt gets validated on fovea
3. Fovea sends me the webhook
4. I cancel the subscription in playstore
5. After around 5 minutes the subscription is expired
6. No hook gets called
7. I press the Refresh button in Fovea 
![image](https://user-images.githubusercontent.com/3703141/188890987-90705096-d312-48fd-b1a6-7e92f4ee1d04.png)
8. Now I get the hook

How often does Fovea refresh their receipts? Do I have to enable something so I get notified of an expired subscription?

**Comment by cm-cm-cm-cm** [comment]
Got it to work with pub/sub

**Comment by vesper8** [comment]
@cm-cm-cm-cm Do you mind telling me what you did here? I already have pub-sub setup on Google and I pointed it to Fovea (now Iaptic) and I can see that Google is indeed sending requests, but this is not triggering the webhook to my backend.. so the information is stored on Iaptic but shouldn't these events also trigger the webhook to my backend?

**Comment by jaderinoo** [comment]
> @cm-cm-cm-cm Do you mind telling me what you did here? I already have pub-sub setup on Google and I pointed it to Fovea (now Iaptic) and I can see that Google is indeed sending requests, but this is not triggering the webhook to my backend.. so the information is stored on Iaptic but shouldn't these events also trigger the webhook to my backend?

Any update on this? I'm running into the same issue. This is happening with both google and apple for me.
