### ISSUE TITLE
billing issue

### ISSUE THREAD

**Issue by lesterjlester** [j3k0/cordova-plugin-purchase#1327]
This version of the application is not configured for billing through Google Play. Check the help center for more information.

**Comment by j3k0** [comment]
Most certainly not an issue with the plugin itself, but something to resolve with Google Play.

**Comment by selected-pixel-jameson** [comment]
@lesterjlester Did you ever figure out a solution to this problem?

**Comment by selected-pixel-jameson** [comment]
I'm seeing this error when testing on my local environments running off my local servers. But if I submit a internal beta test version the payments seem to be working. Not sure if it will never work locally or if it's something I have misconfigured.
