### ISSUE TITLE
Play Billing Library 4.0 / 5.0

### ISSUE THREAD

**Issue by starterwings** [j3k0/cordova-plugin-purchase#1333]
Is there an efficient way to upgrade Play Billing Library 3.0 to Play Billing Library 4.0 or 5.0 using this plugin?

**Comment by joefaron** [comment]
https://github.com/j3k0/cordova-plugin-purchase/pull/1308

**Comment by j3k0** [comment]
PR 1308 was a little hacky, so I'm taking a new direction with #1330 that should expose all the niceties of billing library v5, with some breaking changes to the API.
