### ISSUE TITLE
Offer code redemption functionality 

### ISSUE THREAD

**Issue by vikasshinde448** [j3k0/cordova-plugin-purchase#1335]
Hi developers,

We need to implement offer code or promo code redemption through in aver app please help us how to do that.  

Android can support to give a promo code section to add offer code but IOS can not give any section to fill offer code so we need to Mack a design and and use to offer code redemption in IOS

**Comment by j3k0** [comment]
With plugin version 11, you can use `store.redeem()`.

With plugin version 13, you can call the presentCodeRedemptionSheet method from the AppStore adapter:

```ts
// javascript
store.getAdapter(Platform.APPLE_APPSTORE).presentCodeRedemptionSheet();

// typecript
const appStore = store.getAdapter(Platform.APPLE_APPSTORE) as CdvPurchase.AppleAppStore.Adapter;
appStore.presentCodeRedemptionSheet();
```
