### ISSUE TITLE
Billing Library version 4 or newer to publish this app.

### ISSUE THREAD

**Issue by DanijelBumbar** [j3k0/cordova-plugin-purchase#1347]
Hello there,

I cant update my VPN Pink App [Vpn Pink](https://www.vpn-pink.com/) bcs Cordova plugin uses old version 
![image](https://user-images.githubusercontent.com/3023577/206881497-6a6f7d34-1bf6-4d13-b3e1-a708024f54d4.png)

Reminder: Starting on August 2, 2022, all new apps must use Billing Library version 4 or newer. By November 1, 2022, all updates to existing apps must use Billing Library version 4 or newer.

**Comment by paulstelzer** [comment]
Seems that you are using an old version. In Version 11, Billing v4 is supported or directly update to version 13 which has v5 support of the billing library.

**Comment by DanijelBumbar** [comment]
thanks for the info
