### ISSUE TITLE
appStoreReceipt missing in validation payload on 13.x right after purchase

### ISSUE THREAD

**Issue by silviogutierrez** [j3k0/cordova-plugin-purchase#1351]
### Observed behavior

```
 [log] - [CordovaPurchase.Validator] DEBUG: validator success, response: {"ok":false,"route":"/validate","status":400,"code":6778001,"message":"The data you sent includes no appStoreReceipt and no transactionReceipt.","data":{"latest_receipt":true,"code":6778001,"error":{"message":"The data you sent includes no appStoreReceipt and no transactionReceipt."}},"source":{"isHttpError":true,"status":400,"code":6778001,"route":"/validate"}}
```

### Expected behavior
I expect `appStoreReceipt` to be populated.

When doing a full end to end test, that is, brand new sandbox user + brand new account on my app, the purchase goes through with StoreKit. But then the validation function is called and appStoreReceipt is empty. For the record, **I'm using the hosted iaptic.com solution**, but it still doesn't work. The logs on the iaptic.com site also show the missing receipt error. So you get a 400 and the purchase never refreshes as `owned = true`

I know subscriptions are not yet documented with 13.1.1, but I figured they would work and that I would try them.

Note that if I then close the app, and reopen it, the validation hook runs correctly and everything works. So it's just right after signing up that appStoreReceipt is missing.

Unfortunately I don't know how to further debug this, but figured maybe  it's something obvious in the 13x branch where appStoreReceipt isn't set after purchasing and maybe it's a quick fix. Let me know how best I can help.

### System Info

Using versionv `13.1.1` on iOS with Capacitor. Previously I used version 9.0.1 and it worked fine. I doubt it's related to Capacitor though.

**Comment by j3k0** [comment]
Thanks for the report.

It's probably only a development issue, as the appStoreReceipt can only be unpopulated when running after installing from XCode (as opposed to installing from the AppStore).

However I think the older version of the plugin was doing a receipt refresh when that happens. Refreshing the receipt often trigger a popup from StoreKit where the user is requested to confirm its AppStore credentials.

I think should still be done during the purchase process. I'll figure out a fix.

**Comment by silviogutierrez** [comment]
I do recall 9.0.1 being "credential" happy on the dev builds. Asking a few times, etc. So it sounds like you're right!

**Comment by j3k0** [comment]
Fixed in `master` branch.

**Comment by silviogutierrez** [comment]
@j3k0 : just tested this on 13.1.3 and I can confirm it's fixed.
