### ISSUE TITLE
v13.0 Micro-example code fails due to "Parsing error: Unexpected token ]"

### ISSUE THREAD

**Issue by macsupport** [j3k0/cordova-plugin-purchase#1352]
### Observed behavior

Parsing error: Unexpected token ] on line 12 in code on https://purchase.cordova.fovea.cc/v/v13.0/discover/micro-example
In particular, this code:

```
store.register([{
    type: CdvPurchase.CONSUMABLE,
    id: 'my_product',
    platform: Platform.TEST,
  ]});       //  Misplaced bracket ']'
```

### Expected behavior
```
store.register([{
    type: CdvPurchase.CONSUMABLE,
    id: 'my_product',
    platform: Platform.TEST,
  }]);
```

**Comment by j3k0** [comment]
Sorry, the micro-example hadn't been updated yet. It has been now:

https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/minimal-example.js

And a more complete example here (that uses typescript):

https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/example/example.ts
