### ISSUE TITLE
NPM Version Doesn't Match Repo Version

### ISSUE THREAD

**Issue by selected-pixel-jameson** [j3k0/cordova-plugin-purchase#1362]
Hello,

I'm adding this as a dependency to my Ionic / Capacitor project and the NPM version doesn't match what that latest version is on this repo.

The NPM version is stating 10.5.3, which doesn't even exist in the Releases. But the repo is stating that version 11.0.0 is that latest release. 

Is the NPM version the latest release? 

FYI we are a paying Fovea customer.

Thank you.

**Comment by paulstelzer** [comment]
The release section here in github is not correct because it seemed not used regulary. The latest version is 13.1.6. See all versions here -> https://www.npmjs.com/package/cordova-plugin-purchase?activeTab=versions

**Comment by j3k0** [comment]
I updated RELEASE_NOTES, it was long overdue. @selected-pixel-jameson  you were probably using the "awesome-cordova-plugins" wrapper, which hasn't been updated with the latest version.

Just install `cordova-plugin-purchase` directly in your project as a cordova plugin, it will works.
