### ISSUE TITLE
[ANDROID] Error onAcknowledgePurchaseResponse()

### ISSUE THREAD

**Issue by no-toodate** [j3k0/cordova-plugin-purchase#1364]
### Observed behavior
Hello everyone! 

I just implemented the latest version of the plugin. 

I have some problems as there is this in my android logcat, and I cannot get to the transaction.finish part. I stay in the "approved" state and seemingly cannot go further.

I don't know if it is due to this... 

i have to add that I can pay, and payment has been confirmed (pop up from google) I even get a message telling me I am already subscribed if I click the order button again.
```
 CdvPurchase D  onAcknowledgePurchaseResponse() -> Success
CdvPurchase  D  onAcknowledgePurchaseResponse() -> Failed: ERROR: Server error, please try again.
CdvPurchase  D  callError({code:6777013, msg:"ERROR: Server error, please try again.")


```
### Expected behavior
For the system to finish the transaction. 

### System Info
 "plugins": {
    "cordova-plugin-network-information": {},
    "cordova-plugin-purchase": {}
  },
  "platforms": [
    "android",
    "browser"
  ]
}
cordova-plugin-purchase 13.1.6 "Purchase"

Here is my code, did I do it in the right order? Did I forget something? 

` this.CdvPurchase.store.register([{
            id: this.valeurEnvoi.app,
                platform: (window as any).CdvPurchase.Platform.GOOGLE_PLAY,
            type: (window as any).CdvPurchase.ProductType.PAID_SUBSCRIPTION,
        }]);

      
        this.CdvPurchase.store.ready(() => {
         

            const produit = this.CdvPurchase.store.get(this.valeurEnvoi.app, (window as any).CdvPurchase.Platform.GOOGLE_PLAY);
           

            for (const clef in produit) {
                if (produit.hasOwnProperty(clef)) {
                    log += clef + ' : ' + produit[clef] + '\n';
                    if (clef === 'offers') {
                        for (const clefOffers in produit[clef][0]) {
                            if (produit[clef][0].hasOwnProperty(clefOffers)) {
                                log += clefOffers + ' : ' + produit[clef][0][clefOffers] + '\n';
                            }
                        }
                    }
                }
            }

            if (produit.canPurchase) {
                this.CdvPurchase.store.order(produit.getOffer());
            }

            this.CdvPurchase.store
                .when()
                .productUpdated(produitUpdated => {
                    this.logObjet('productUpdated', produitUpdated);
                })
                .approved(transaction => {
                    this.logObjet('approved', transaction);
                    transaction.finish();
                })
        });
        this.CdvPurchase.store.initialize([(window as any).CdvPurchase.Platform.GOOGLE_PLAY]);

`

**Comment by no-toodate** [comment]
I need to add that the finish() function is not called. Therefore the purchase stays in the approved state, and I cannot go further than that.

**Comment by geshub** [comment]
> 

I also can't get the finished event to get called on Android (v12). 
The same code is calling this event correctly on IOS.

I can see those in my logs:

[CdvPurchase.Validator] DEBUG: Register a new verified receipt.
[CdvPurchase] INFO: finish(VerifiedReceipt)
[CdvPurchase.GooglePlay.Bridge] INFO: consumePurchase()
[CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"purchaseConsumed","data":{"purchase":{"orderId":"GPA.3323-0342-9288-38202","packageName":"...
[CdvPurchase.GooglePlay] DEBUG: onPurchaseConsumed: GPA.3323-0342-9288-38202

but never getting to the finished event.

**Comment by amycardoso** [comment]
I also noticed that the purchase remains in the approved state even when finish() is called. Tested on Android (v12).

**Comment by bryan-hunter** [comment]
> I also noticed that the purchase remains in the approved state even when finish() is called. Tested on Android (v12).

I am noticing the same thing on Android only - version 13.1.6

I am also afraid to rely on the returned promise from `finish` because it doesn't await so it succeeding is not indicative of really finishing

**Comment by no-toodate** [comment]
I add that I have the same problem with IOS. It doesn't call the verify() function. And I do use the iaptic validator.
