### ISSUE TITLE
[macOS] - Clarification

### ISSUE THREAD

**Issue by grantmk** [j3k0/cordova-plugin-purchase#1365]
I have IAP running fine on iOS (ionic / capacitor). This plugins docs allude to macOS support in places but the store does not load (built with capacitor community electron).

When you refer to macOS support do you mean:

1. iPad apps that can also run on Apple Silicon Macs or
2. We can compile for macOS via electron and electron-builder?

Thanks in advance!

**Comment by j3k0** [comment]
The plugin works as a native macOS plugin on the cordova `osx` platform (StoreKit API is almost identical on macOS and iOS). However the `osx` platform has been deprecated by Cordova in March 2022, see https://github.com/apache/cordova-osx - I'm not sure what kind of support ionic/capacitor have for macOS.
