### ISSUE TITLE
Native: tried calling InAppPurchase2.NON_RENEWING_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.

### ISSUE THREAD

**Issue by nitindme** [j3k0/cordova-plugin-purchase#1366]
nic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.2
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (/Users/nitindigraje/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 8.19.2
   OS     : macOS

Getting error

Ionic Native: deviceready event fired after 22 ms
main.e81bbfd3f1dbd62a.js:1 Native: tried calling InAppPurchase2.NON_RENEWING_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.

**Comment by abreu1234** [comment]
It appears that the latest versions of the plugin are not yet compatible with Ionic Native. Try to downgrade to version 11.

https://github.com/danielsogl/awesome-cordova-plugins/issues/4457

**Comment by oli-kester** [comment]
> It appears that the latest versions of the plugin are not yet compatible with Ionic Native. Try to downgrade to version 11.
> 
> [danielsogl/awesome-cordova-plugins#4457](https://github.com/danielsogl/awesome-cordova-plugins/issues/4457)

I'm pretty new to the world of Android billing - but it seems to me that because v11 of this plugin uses the v4 of the Android billing library internally, Google won't let you publish any new apps that use this downgrade workaround? It gives me an error in the Google Play Console, saying that all new Android apps must use v5 of the Google Play Billing library.
