### ISSUE TITLE
Order suddenly does nothing

### ISSUE THREAD

**Issue by githubowl** [j3k0/cordova-plugin-purchase#1367]
### Observed behavior

store.order(product).then(p => {
                            console.log('purchase in progress', p);
                          }, e => {
                            console.log('Failed', `Failed to purchase: ${e}`);
                          });;

Up to a few days ago this was working perfectly, but suddenly when I run order, nothing happens, no errors, no feedback nothing. I have tried tracing through the Javascript and Order fires and is run through error free.

But I put these console.log in and neither of them does anything.  

I have updated items in the store and resubmitted my app, could that be blocking it?

I have commented out the changed items and don't register them anymore.

Product update fires when I register the product.

An example of a product is:

product updated {"id":"Testsub","alias":"One Week","type":"non renewing subscription","group":null,"state":"valid","title":"Test","description":"Test","priceMicros":7000000,"price":"USD 7.00","currency":"USD","countryCode":"US","loaded":true,"canPurchase":true,"owned":false,"introPrice":null,"introPriceMicros":null,"introPricePeriod":null,"introPricePeriodUnit":null,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"discounts":[],"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"billingPeriod":0,"billingPeriodUnit":"Day","valid":true}

### Expected behavior

The order should take place

### System Info

I am running in angular 14, capacitor 4.3 ionic 5.36.

Output of `cordova info`.

cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: win32
  Node: v14.17.0
  npm: 8.19.2

Thanks a lot

**Comment by j3k0** [comment]
What version of the plugin are you using? Is is iOS or android? Can you check the return value of `store.ready()`?

**Comment by githubowl** [comment]
I found the bug, it was the isReady not being set. Once that was set the functions started to fire again and everything updated.

But one thing, I wasn't able to call store.ready(true) (didn't need it in the end) in typescript because it complained that store.ready required a function. 

Thanks

**Comment by bppearsoft** [comment]
We are seeing a similar issue with purchasing on iOS. Both our development and ad hoc builds work perfectly but the app store build fails on the store.order() call. All products loaded & registered correctly. We're registering our products, registering the callback handlers, then calling store.refresh(). Updated, registered & loaded handlers all fire correctly. When we call store.order(productId) it neither returns nor throws any errors. Following up with the comments above, what more do I need to do to get the ready state? Do I need to explicitly call store.ready()? The sample code is not doing that. Please help!
Thank you

**Comment by bppearsoft** [comment]
@githubowl could you be more specific about isReady? First, are you using v11? What are you calling that ultimately sets the isReady flag (is this the same as the store.ready handler)?

**Comment by githubowl** [comment]
I was not calling verify on the app store receipt product, when i refreshed at the beginning, only on the products and it somehow got stuck. When I added that product id to the list of products to refresh it initialized everything and started working again.

According to the code you can call ready(true) to set isready by force. But I didn't do that. It also wouldn't be so simple with typings because ready expects a function or that was how it complained to me.

Put traces or alerts in and follow it through, it then becomes clear. That's how I solved it. 

Hope that helps.

One thing to note, it used to work without this, but then suddenly stopped, so i'm not sure why this came about.

**Comment by githubowl** [comment]
I'm using the latest version of the code.

**Comment by bppearsoft** [comment]
thank you https://github.com/githubowl. I'm not aware of a separate receipt product that accompanies the actual non-consumable product, is that something else needed to be registered along with the in-app purchase product in the app store? Yes, I have a handler listening to store.ready but not sure how to explicitly trigger it. Thanks for the suggestion, I do have trace messages throughout the workflow reporting to our server. There must be something else store.order does differently when running in an app store build vs dev or ad hoc, do you have any experience with that?

**Comment by githubowl** [comment]
Actually sorry. No I don't. I struggled a bit myself and for future ease I'm looking at all my options for this functionality. So not sure what I'll do.

**Comment by j3k0** [comment]
The plugin waits for events to have been handled before emitting "ready". If I understand @githubowl wasn't handling application receipts (which is an iOS thing, a receipt is generated when downloading from AppStore).

If you have a receipt validation service in place, make sure you either validate the application receipt or finish it right away.

For example:

```ts
store.when().approved(p => {
  if (p.type === store.APPLICATION)
    p.finish(); // not validating application receipt, finishing right away.
  else
    p.verify();
  // or no if-else and just verify all products including the application receipt, it's good practice that solves a number of issues.
});
```

If I'm correct that should solve the issue.
