### ISSUE TITLE
[IOS/Android] product.pricing is always undefined

### ISSUE THREAD

**Issue by geshub** [j3k0/cordova-plugin-purchase#1368]
### Observed behavior

product.pricing shortcut is always undefined in my implementation ( v13.1.6 ) on Android and IOS, I did also try the example code with the same results.
product.offers[0].pricingPhases[0] is returning the correct pricing information, so it's not vital for the payments, but, just to know if others got the same problems or if it's due to my implementation.

### Expected behavior
product.pricing = product.offers[0].pricingPhases[0];

### System Info

Ionic:

   Ionic CLI         : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 3.2.18

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 24 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (/Users/geshub/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v12.14.1 (/usr/local/bin/node)
   npm               : 8.19.1
   OS                : macOS
   Xcode             : Xcode 14.2 Build version 14C18

**Comment by krunalsk007** [comment]
i am also facing this. if you want to get price you can achieve like this after gatiing **productUpdated()** method `product.offers[0].pricingPhases[0].price`

**Comment by j3k0** [comment]
Thanks for the report, there was a bug.
