### ISSUE TITLE
Purchase error

### ISSUE THREAD

**Issue by VapiSoft** [j3k0/cordova-plugin-purchase#137]
I pass the .load  ok (including the registration of the productID).
But when I call .purchase I get an error# 4983507
Cannot connect to iTune

**Comment by OJcode14** [comment]
Are you running on a device or simulator? Can you share your code?

**Comment by VapiSoft** [comment]
I am using it on iPhone 4 with iOS 7.0.4 
The code is very straightforward as the example.
Please note that I see that it passed the .load because I get the description of the product and its price as I entered in the iTune InAppPurchase page.

**Comment by VapiSoft** [comment]
The code is attached.
The part that doesn't work is:  line 151:  window.storekit.purchase(itemId,
1);

Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by VapiSoft** [comment]
Hi, One more thing.
I don't understand where do I submit a callback for an error or success?


Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by VapiSoft** [comment]
Regarding the last question, now I see that you set the purchase callback
in the .init function.

Shlomo Aran
http://www.mobile-gap.com
054-7399-340
