### ISSUE TITLE
ios In-app purchase click continue need long time to popup

### ISSUE THREAD

**Issue by zcj-Git** [j3k0/cordova-plugin-purchase#1370]
Hi, I use cordova-plugin-purchase v11.0.0
I have a problem that to popup after click "continue". 
![image](https://user-images.githubusercontent.com/26144273/215657533-ddf72566-e59e-4c38-b9d1-ebfd7f8541ce.png)
I want to know why to make a product with id equals app's bundle Id? The Receipt generated can be verified?
sorry for my poor English, it is not my mother tongue.

**Comment by j3k0** [comment]
Yes, on iOS a receipt is generated by the AppStore when the app is downloaded.

It allows:

- Checking that the app is a legit AppStore download (not side-loaded, which might mean it's been "patched")
- Knowing extra info, like the first downloaded version (used when making a free feature a paid one for new users)

The plugin also re-validate it every 24h on iOS, checking for potential changes in purchases (like subscription renewals or cancellations) - in case the app remained running for that long (for some app with background jobs).
