### ISSUE TITLE
Why is ErrorCode.PAYMENT_CANCELLED no longer an error?

### ISSUE THREAD

**Issue by HernanZh** [j3k0/cordova-plugin-purchase#1371]
This is specifically mentioned as a comment: https://github.com/j3k0/cordova-plugin-purchase/blob/7a7d0baf8f289b021376abd3de6c67ea2614282f/src/ts/platforms/apple-appstore/appstore-adapter.ts#L216

If you cancel a purchase on iOS, no error is raised and the error callback is not called. I do see the receiptUpdated callback is called on purchaseFailed, but this does to be a reliable way to detect a cancel as the receiptUpdated is also used in other cases. How does one detect a PAYMENT_CANCELLED event?

**Comment by j3k0** [comment]
When a user just closes a popup window, raising an global error shouldn't be the expected behavior. Some apps will send report errors to servers and show an alert to the user, which shouldn't happen in this case.

Now you can just do:

```
store.order(...).then(result => {
  if (result.isError && result.code === CdvPurchase.ErrorCode.PAYMENT_CANCELLED) {
    // used closed the purchase window
  }
});
```
