### ISSUE TITLE
Subscription product is still owned after subscription cancel - Status not updated with store.update() 

### ISSUE THREAD

**Issue by jma83** [j3k0/cordova-plugin-purchase#1373]
Platform: Android - Google Play

Hi, 
After cancelling an active subscription and going back to the app, I call the update function, but the subscription is still owned.

Step by step:
- Purchase a subscription
- Manage play store subscriptions
- Cancel active subscription
- Return to the app and update status. It's owned, but it shouldn't be

On the other hand, if I cancel the subscription and restart the app the product status is updated, and owned is now false.

How can I sync the status of subscriptions with Google Play, without restarting the app? 
If more details are needed I can send some logs.
Thanks in advance.

**Comment by t-vladimir** [comment]
@jma83 Hello.
I'm sorry I can't help you with your problem.
But can you please provide me with some consultation? :)
Did you encounter a problem when google subscriptions don't show any information about the subscription, except for some fields?
<img width="272" alt="image" src="https://user-images.githubusercontent.com/111683680/217205304-1c7d4291-7af2-4ed7-90c8-2ad40451b9ad.png">

IOS subscriptions gave me everything they got, but I don't understand what I'm missing with the Google Subscriptions.
I've encountered a [topic here](https://github.com/j3k0/cordova-plugin-purchase/issues/1310#issuecomment-1190977310), where somebody else got this behavior, but everything that was described to 'heal it' there is already implemented by me:
I do have a subscription, with only one plan, and I'm using `cordova plugin purchase v11`.

**Comment by t-vladimir** [comment]
> @jma83 Hello. I'm sorry I can't help you with your problem. But can you please provide me with some consultation? :) Did you encounter a problem when google subscriptions don't show any information about the subscription, except for some fields?

So, I was silly enough to insert the price for the country from where I'm trying to get the subscription. And only after a few hours, I got all of the subscription data, not just the missing price.

**Comment by j3k0** [comment]
@jma83 Version 13 of the plugin handles this better. Notice that you need a receipt validation server to handle subscription properly (like https://www.iaptic.com or your own custom server).
