### ISSUE TITLE
Subscriptions still get verified after expiration on iOS sandbox (without using receipt validation)

### ISSUE THREAD

**Issue by dbachmann24** [j3k0/cordova-plugin-purchase#1376]
First of all, thanks for the great Plugin!

### Observed behavior

The purchase of auto-renewable subscriptions on iOS (with sandbox test user) is working fine. But when I cancel the subscription and let it expire, the subscription still gets approved and verified after app restart. I tried the same process with receipt validation from [Iaptic](https://www.iaptic.com) and then everything works fine. So my question is: Do you need a receipt validation server to recognize, that a subscription is expired and should not grant access to premium content anymore? Or should it work without receipt validation, only using the plugin? Because in my case, it doesn't.

Here's a simplified version of my code. Additionally i can provide the logs of starting the app after the subscription is cancelled and expired, if needed.

`

    this.plt.ready().then(() => {
      // Only for debugging!
      this.store.verbosity = this.store.DEBUG;

      this.registerProducts();
      this.setupListeners();
      this.store.refresh();

      // Get the real product information
      this.store.ready(() => {
        this.products = this.store.products;
        this.ref.tick();
      });
    });}

    registerProducts() {
    this.store.register({
      id: PRODUCT_1_MONTH_KEY,
      type: this.store.PAID_SUBSCRIPTION,
    });

    this.store.register({
      id: PRODUCT_3_MONTH_KEY,
      type: this.store.PAID_SUBSCRIPTION,
    });

    this.store.register({
      id: PRODUCT_1_YEAR_KEY,
      type: this.store.PAID_SUBSCRIPTION,
    });}

    setupListeners() {
    // General query to all products
    this.store.when('product')
        .approved(async (p: IAPProduct) => {
          // Handle the product deliverable
          return p.verify();
        })
        .verified((p: IAPProduct) => {
          this.unlockPremium(p);
          p.finish();
        })
        .owned(async (p: IAPProduct) => {
          this.unlockPremium(p);
        })
        .error((e: IAPError) => {
          console.log('Error Message: ', e.message);
          console.log('Error Code: ', e.code);
        });
    }`

### Expected behavior

After a subscription is cancelled and expired, the subscription should not be approved and verified anymore.

### System Info

I am using Ionic with capacitor. I followed the appropriate [guide](https://devdactic.com/ionic-in-app-purchase-capacitor). Here's my ionic info and cordova info below that.
____________________________________________________________
ionic info:

Ionic:

   Ionic CLI                     : 6.17.1
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 4.5.0
   @capacitor/android : 4.5.0
   @capacitor/core    : 4.5.0
   @capacitor/ios     : 4.5.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-webview 4.2.1, (and 7 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   ios-sim : 8.0.2
   NodeJS  : v18.12.1 (/usr/local/bin/node)
   npm     : 8.19.2
   OS      : macOS Monterey
   Xcode   : Xcode 14.2 Build version 14C18
__________________________________________________________________
cordova info:

  Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

Project Installed Plugins:

    cordova-plugin-camera: 5.0.1
    cordova-plugin-device: 2.0.3
    cordova-plugin-file-opener2: 3.0.5
    cordova-plugin-file: 6.0.2
    cordova-plugin-ionic-webview: 4.2.1
    cordova-plugin-splashscreen: 5.0.4
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-whitelist: 1.3.4
    cordova-sqlite-storage: 5.1.0

Environment:

    OS: macOS 12.6.1 (darwin 21.6.0) x64
    Node: v18.12.1
    npm: 8.19.2
______________________________________________
I don't know why cordova-plugin-purchase is not listed in the installed plugins. In fact all the listed plugins here were deleted some time ago. Probably they are still listed, because I'm using capacitor and not Cordova. However, but running capacitor sync it says:

[info] Found 3 Cordova plugins for ios:
[capacitor]        call-number@1.0.1
[capacitor]        cordova-plugin-purchase@11.0.0
[capacitor]        cordova-sqlite-storage@6.0.0

These 3 Cordova plugins are actually still in use.

**Comment by j3k0** [comment]
Yes, on iOS the expiration date is not available locally. Expired or not, the transaction will pop-up when the app starts. You need a receipt validation service like https://www.iaptic.com/ or a custom built one.
