### ISSUE TITLE
[ios] canMakePayments, how to use?

### ISSUE THREAD

**Issue by RonaldPK** [j3k0/cordova-plugin-purchase#1378]
Apple's [guidelines for in-app purchases](https://developer.apple.com/design/human-interface-guidelines/technologies/in-app-purchase/introduction/) state "Display your store only when people can make payments. If someone canʼt make payments — for example, because of parental restrictions — consider hiding your store or displaying UI that explains why the store isnʼt available. For developer guidance, see AppStore.canMakePayments."

In www/store.js there is a method `canMakePayments`, which seems to call the iOS method. It takes success and error callbacks. The only way I could figure out how to call the method feels like crossing a lot of bridges:

```
(new CdvPurchase.AppleAppStore.Bridge.Bridge()).canMakePayments(
    () => {console.log('user can make payments')}, // success
    (error) => {console.error('user cannot make payments', error)} // error
);
```

Is that the correct way to use the method? 

Plugin version 13.3.1

**Comment by j3k0** [comment]
No, you shouldn't have to go to that depth, especially creating a new "Bridge" class.

With the just released version `13.3.3`, when you check if the offer can be purchased, it will use the value from `canMakePurchases`.

```
if (!offer.canPurchase) {
  // the given offer cannot be purchased. hide it or hide the buy button.
}
```

There are 2 reasons why an offer cannot be purchased:

1. product is already owned (see `product.owned`)
2. the adapter don't support "order()"

If none of the offers can be purchased, you can hide the whole store.

If you really want to access the low-level value of `canMakePurchases` you can do it like so:

```
    const appStore = store.getAdapter(CdvPurchase.Platform.APPLE_APPSTORE);
    if (appStore && appStore.checkSupport('order')) {
        // user can make payments
    }
```
