### ISSUE TITLE
Updating from version 10.0.2 ..store empty object

### ISSUE THREAD

**Issue by Senglean** [j3k0/cordova-plugin-purchase#1379]
After updating the plugin to latest from version 10.0.2 window.store is an empty object.

Any suggestions?

**Comment by Senglean** [comment]
Reference for others:

Now the plugin contains more than one object so window.store  is now CdvPurchase.store

Also the purchase process changed a little so head on to the docs

**Comment by j3k0** [comment]
Thanks for reference. In particular this document: https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13
