### ISSUE TITLE
Migration from V11 to 13 Guide for JS

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#1381]
I am trying to migrate a JS app from V11 to V13.x

I must say I am having a hard time. So much has changed. I see a TS example but some attributes just don't seem to translate to JS. For example products used to have states but now they don't. And I don't understand how to get owned() for example in the V13x API.

Any help would be appreciated.

**Comment by j3k0** [comment]
Hi, did you find the migration guide on the wiki? There's a link to that page in the README:

https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13

**Comment by aesculus** [comment]
Totally did not see it and saw the statement but never the link. Overlooked many times. 

This would have saved me a day. I guess I just went brain dead.

**Comment by aesculus** [comment]
Just noticed why I did not find it. In the announce page for V13 the link for the wiki does not go to the wiki:

https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md
