### ISSUE TITLE
Reset iOS Sandbox IAP User Environment

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#1386]
I wanted to pass on a technique I use to reset my IAP Sandbox test account and device. I was having issues with both the Apple subscription purchase dialog not showing during purchase as well as my server based validator not completing properly. The later was caused by an old transaction that can never be replaced. Apple has recently allowed for clearing a test accounts purchases, but the plugin was still caching the receipts so it would still fail. Here is what I needed to do. YMMV:

- Have two iTunes accounts. One that you use with Testflight to download the test app and the other that is exclusively used for IAP testing.
- Starting with an installed app that is failing. Logged into the Testflight account on the device, go to the device Settings > General > Device Storage 
- Scroll to your app and then select Delete App. This will delete the cached data on the device and the app itself.
- Now go to Testflight and reinstall the app but don't start it yet.
- On the Web go to your AppStoreConnect account and log in
- Then go to Users and Access
- Go to the Sandbox Testers and locate (or create) the account you use for testing your IAP
- Select the Edit button and then put a checkbox by the account name
- Now select Clear Purchase History. Any history for this account will be removed from Apples test server
- Next go to your iOS device and log out of your Testflight account on Settings
- When complete log into to your Sandbox test account you will use for IAP testing.
- Once that is complete you can restart the app that you are going to test IAP on

If you have the Debug logging on you should see the products loading and registering and also get a message about no receipts found. Your device and account should both be fresh and you can restart your testing from the beginning.

Hope this helps.

**Comment by j3k0** [comment]
Thanks for the tip! I'll close the issue, hopefully people with he problem will find it by searching.
