### ISSUE TITLE
[ANDROID] Approved is invoked twice

### ISSUE THREAD

**Issue by WpsDiscovery** [j3k0/cordova-plugin-purchase#1392]
Windows 10
Cordova  11.1.0
Device: Android 10
Plugin Version: 13.3.5

<h3>Expected behavior</h3>
I click on the order_product button, the purchase is approved and the purchase is saved on the personal server

<h3>Observed behavior</h3>
I click on the buy button, the purchase is approved correctly 1 time but approved is invoked twice, this resulted in a double save on my personal server

<h3>Initializing code</h3>

>
     document.addEventListener("deviceready", onDeviceReady, false);
      function onDeviceReady() { 
        store = CdvPurchase.store;
        const LogLevel = CdvPurchase.LogLevel;
        const ProductType = CdvPurchase.ProductType;
        const Platform = CdvPurchase.Platform;
        store.verbosity = LogLevel.DEBUG;
  
        store.register([{
          id: 'speech_recognition',
          type: ProductType.CONSUMABLE,
          platform: Platform.GOOGLE_PLAY,
        }, {
          id: 'remove_ads',
          type: ProductType.CONSUMABLE,
          platform: Platform.GOOGLE_PLAY,
        }]);
        store.initialize([Platform.GOOGLE_PLAY]);
      }

      function order_product(productId){
        store.when(productId).approved(transaction => {
          console.log('------------------------')
          console.log('purchase approved and registered on my db')
          console.log('------------------------')
          transaction.finish();
          register_product_to_server(transaction.products[0].id);
        });
        store.get(productId).getOffer().order();
      }

register_product_to_server() makes an Ajax call to save the purchase on the server.

How can I fix? Am I doing something wrong in the implementation of the code?
Thanks a lot for your support

**Comment by okhiroyuki** [comment]
Plugin Version: 13.3.5

Same problem.

**Comment by Ralle** [comment]
Happens three times for me. It corresponds to the number of transactions in `CdvPurchase.store.localReceipts`.

**Comment by andreibaca** [comment]
Ubuntu 18.04
Device: Emulator Android SDK 30
Plugin Version: 13.4.0

I have the same problem. 
In my case. This is not related to multiple initializations. I have added a counter and the initialization of listeners is done only once.
It seems that the approved event is invoked second time when the transaction is finished. At lest the state of transaction is finished the second time. So as a workaround just check if the transaction state is 'approved' only then process the purchase on your server. I am not sure if this is a bug or as intended.

Also the transaction.verify() seems to do nothing. 
At least store.when().verified() event does not fire.

**Comment by TheNotorius0** [comment]
> Ubuntu 18.04 Device: Emulator Android SDK 30 Plugin Version: 13.4.0
> 
> I have the same problem. In my case. This is not related to multiple initializations. I have added a counter and the initialization of listeners is done only once. It seems that the approved event is invoked second time when the transaction is finished. At lest the state of transaction is finished the second time. So as a workaround just check if the transaction state is 'approved' only then process the purchase on your server. I am not sure if this is a bug or as intended.
> 
> Also the transaction.verify() seems to do nothing. At least store.when().verified() event does not fire.

It happens to me too, and it's not a bug of multiple initializations.

Your workaround is nice, it's better than what I've implemented (I was storing the transactionID, and if it was the same, the second time I ignored it). 

Basically there are 2 different properties in those object, `state: "approved"` and `"isAcknowledged": false` in the first one and `state: "finished"` and `isAcknowledged": true` in the second one. Not sure what isAcknowledged is though.

About the `store.when().verified` bug, it only happens when the store.validator is not defined. If you defined it (`store.validator = "https://validator.iaptic.com/v3/validate?appName=com.azmar2.sevangames&apiKey=....."`); it doesn't fail. If you don't have a validator I guess you can skip it?

**Comment by j3k0** [comment]
The error is that each time you are calling `order_product`, you are registering a new event handler.

Event handlers have to be registered only once, at startup, before calling `store.initialize()` -- this will also let the app handle pending purchases, like those initiated outside the app, family-shared purchases, ask-to-buy transactions that can remain in the queue for 48h, etc.
