### ISSUE TITLE
iOS subscribe twice in a row gives invalid transactionId

### ISSUE THREAD

**Issue by Ralle** [j3k0/cordova-plugin-purchase#1396]
### Observed behavior

On iOS a transaction with ID `appstore.application` is created when I subscribe, unsubscribe and subscribe.

Reproduce:
1. Be on iOS.
2. Subscribe to something. (Works, you get a valid `transactionId`)
3. Go to Settings and unsubscribe.
4. Go back to app.
5. Reload webpage.
6. Subscribe to same something (Now you get a receipt with `transactionId` = `"appstore.application"`)

This is the code I am using to handle buying:
```
const transaction = await new Promise<CdvPurchase.Transaction>(
  async (resolve, reject) => {
    async function finishPurchase(purchase: CdvPurchase.Transaction) {
      await purchase.finish();
    }

    async function ownedPurchase(purchase: CdvPurchase.Transaction) {
      resolve(purchase);
    }

    // Listen to approved event
    CdvPurchase.store
      .when()
      .approved(finishPurchase)
      .finished(ownedPurchase);
    const purchaseResult = await offer.order();
    if (purchaseResult?.isError) {
      reject(new Error(purchaseResult.message));
    }
  }
);
```

The resulting transaction is invalid on iOS on second purchase.

### Expected behavior

All transactions regardless of number of times subscribed should be valid.

### System Info

Output of `cap ls`.
```
Pirkefnirt-2:soundwheel ralle$ npx cap ls
[info] Found 6 Capacitor plugins for android:
       @capacitor/app@4.1.1
       @capacitor/browser@4.1.0
       @capacitor/share@4.1.0
       @capacitor/splash-screen@4.1.2
       @capacitor/status-bar@4.1.1
       capacitor-plugin-safe-area@1.0.1
[info] Found 8 Cordova plugins for android:
       @moodlehq/cordova-plugin-local-notification@0.9.0-moodle.7
       cordova-androidx-build@1.0.4
       cordova-plugin-background-mode@0.8.0
       cordova-plugin-badge@0.8.8
       cordova-plugin-device@2.1.0
       cordova-plugin-purchase@13.3.10
       cordova-plugin-web-share@1.3.0
       cordova-support-android-plugin@2.0.4
[info] Found 6 Capacitor plugins for ios:
       @capacitor/app@4.1.1
       @capacitor/browser@4.1.0
       @capacitor/share@4.1.0
       @capacitor/splash-screen@4.1.2
       @capacitor/status-bar@4.1.1
       capacitor-plugin-safe-area@1.0.1
[info] Found 6 Cordova plugins for ios:
       @moodlehq/cordova-plugin-local-notification@0.9.0-moodle.7
       cordova-plugin-background-mode@0.8.0
       cordova-plugin-badge@0.8.8
       cordova-plugin-device@2.1.0
       cordova-plugin-purchase@13.3.10
       cordova-plugin-web-share@1.3.0
[info] Found 2 incompatible Cordova plugins for ios, skipped install:
       cordova-androidx-build@1.0.4
       cordova-support-android-plugin@2.0.4
[info] Listing plugins for web is not possible.
```

First subscribe:
<img width="986" alt="Screenshot 2023-03-28 at 10 51 57" src="https://user-images.githubusercontent.com/467309/228184134-8502a585-3b3e-4bd5-94b0-9133efa8346a.png">

Unsubscribe, reload page, then second subscribe:
<img width="1012" alt="Screenshot 2023-03-28 at 10 54 12" src="https://user-images.githubusercontent.com/467309/228184149-d52fa615-b0d1-45dc-b76e-dfdb68683872.png">

**Comment by j3k0** [comment]
Can't you just use the `CdvPurchase.store.localReceipts` property to figure out the latest transaction?

Can you give more context on where you are using this?

The `CdvPurchase.AppleAppStore.APPLICATION_VIRTUAL_TRANSACTION_ID` corresponds to the application download (StoreKit generates a receipt to validate the download of the application, gives extra info as well)

**Comment by Ralle** [comment]
Ah.. It's been forever since I posted this. I have tinkered every day since. Learned how important the Validator is. I kept getting presented an expired receipt, not anymore since I setup validation.

I still feel like the `offer.order()` should give you something that resolved to the actual final transaction ID if nothing else.
