### ISSUE TITLE
Android - store methods are undefined

### ISSUE THREAD

**Issue by ragcsalo** [j3k0/cordova-plugin-purchase#1400]
I'm testing on Android 10 and 13, and on both phones all of the store methods are undefined (register, error, when, refresh)...
The store object is available, but none of the methods are working. I'm testing with a Google Play app, and I already have one in-app purchase product for testing. Does this plugin even work on Android?

**Comment by j3k0** [comment]
What version of the plugin? Maybe you are using the latest version but with a old documentation? `store` object is now `CdvPurchase.store`.
