### ISSUE TITLE
Android / "Confirm plan" / acknowledge a purchase

### ISSUE THREAD

**Issue by migo315** [j3k0/cordova-plugin-purchase#1401]
Hey,

First of all, thank you very much for the library. :-)

This works quite well for iOS. On Android, however, I am at a loss when it comes to implementing a subscription. After a successful "purchase", I get the message "Confirm plan" by opening the app. But it is never confirmed and therefore the subscription is cancelled again.

Any idea what I'm doing wrong here? I have searched and googled for similar issues for hours without finding any info.

![IMG_4279_small](https://user-images.githubusercontent.com/13180135/231414465-dc2c0ed1-a828-4a2c-944c-cac9f48cc0ae.jpg)

**Comment by j3k0** [comment]
It's probably because you are not acknowledging the purchase (done when calling `.finish()` on the transaction)

**Comment by migo315** [comment]
I had thought something like that, but I find absolutely no mistake when I compare this with various example codes.

```
// VueJS with Capacitor


this.iapStore = CdvPurchase.store

this.iapStore.validator = "https://validator.iaptic.com/v3/validate?...;

this.iapStore.applicationUsername = function() {
    return this.$store.getters.getAccountId
}.bind(this)

this.iapStore.register({
    id: this.yearlyProduct.sku,
    type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
    platform: this.platform
})

this.iapStore
    .when()
    .approved(transaction => transaction.verify())
    .verified(receipt => receipt.finish())
    .productUpdated(function (product) {
        // Update Products
    }.bind(this))
    .receiptUpdated(function () {
        // Update Products
    }.bind(this))

this.iapStore.initialize([this.platform])
this.iapStore.update()
```

With iOS it works without any problems. And with consumeables it also works on Android. Only Subscriptions on Android is complaining.

Maybe another idea?

**Comment by migo315** [comment]
I have now switched from subscriptions to InApp and played around. I noticed in the Android logs that the transaction does not seem to be finished. The Approved comments appear in the logs, but not the Finished. But it does on iOS.

That would probably also explain the problem with the subscription. But I'm definitely executing the finish method. Apparently something is running on error in the background?

```
.approved(function (transaction) {
  console.log('#APPROVED#')
  console.log(JSON.stringify(transaction))

  transaction.finish()
})
.finished(function (t) {
  console.log('#FINISHED#')
  console.log(JSON.stringify(t))
})
```

Logs:
```
I/Capacitor/Console: File: http://localhost/js/5645.c4852a3c.js - Line 1 - Msg: #APPROVED#
I/Capacitor/Console: File: http://localhost/js/5645.c4852a3c.js - Line 1 - Msg: {"className":"Transaction","transactionId":"GPA.XYZ","state":"approved","products":[{"id":"300200"}],"platform":"android-playstore","nativePurchase":{"orderId":"GPA.XYZ","packageName":"cloud.coaster.mobile","productId":"300200","purchaseTime":1682014770165,"purchaseState":0,"purchaseToken":"XYZToken","quantity":1,"acknowledged":false,"productIds":["300200"],"getPurchaseState":1,"developerPayload":"","autoRenewing":false,"accountId":"","profileId":"","signature":"XYZSignature","receipt":"{\"orderId\":\"GPA.XYZ\",\"packageName\":\"com.app\",\"productId\":\"300200\",\"purchaseTime\":1682014770165,\"purchaseState\":0,\"purchaseToken\":\"XYZToken\",\"quantity\":1,\"acknowledged\":false}"},"purchaseId":"XYZId","purchaseDate":"2023-04-20T18:19:30.165Z","isPending":false,"isAcknowledged":false,"renewalIntent":"Lapse"}

D/ViewRootImpl@e92c93b[ProxyBillingActivity]: Surface release. android.view.ViewRootImpl$ViewRootHandler.handleMessage:4822 android.os.Handler.dispatchMessage:106 
```

**Comment by migo315** [comment]
Here more Logs:

```
D/CdvPurchase: sendToListener() -> purchasesUpdated
D/CdvPurchase:             data -> {"purchases":[{"orderId":"GPA.3376...", ...}]}
I/Capacitor/Console: File: http://localhost/js/3239.18c102e4.js - Line 1 - Msg: #BUYED#
I/Capacitor/Console: File: http://localhost/ - Line 3467 - Msg: [CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"purchasesUpdated","data":{"purchases":[{"orderId":"GPA.3376...", ...}]}}
I/Capacitor/Console: File: http://localhost/ - Line 3467 - Msg: [CdvPurchase.GooglePlay] DEBUG: onPurchaseUpdated: GPA.3376-...
I/Capacitor/Console: File: http://localhost/js/3239.18c102e4.js - Line 1 - Msg: #APPROVED#
I/Capacitor/Console: File: http://localhost/ - Line 3467 - Msg: [CdvPurchase] INFO: finish(Transaction)
D/ViewRootImpl@670cc71[MainActivity]: setWindowStopped(false) old=false
D/Capacitor/AppPlugin: Firing change: true
V/Capacitor/AppPlugin: Notifying listeners for event appStateChange
D/Capacitor/AppPlugin: No listeners found for event appStateChange
V/Capacitor/AppPlugin: Notifying listeners for event resume
D/Capacitor/AppPlugin: No listeners found for event resume
D/Capacitor: App resumed
```

**Comment by migo315** [comment]
Oh, I got closer. I always initialized the library on a specific page in a VueJS "mounted" method. Now that I have put the code globally in a VueJS plugin, it runs into the finish method. :-)

No idea why this makes a difference. Subscriptions work with it now too. Only with consumables I still get this info that the product is not owned (in test mode). Is this relevant or can I ignore it?

```
D/CdvPurchase: executeServiceRequest() -> OK
I/Capacitor/Console: File: http://localhost/js/app.92be4986.js - Line 1 - Msg: #FINISHED#
W/BillingClient: Error consuming purchase with token. Response code: 8
D/CdvPurchase: onConsumeResponse()
D/CdvPurchase: Item is not owned by the user.
D/CdvPurchase: callError({code:6777013, msg:"Item is not owned by the user.")
```

**Comment by j3k0** [comment]
Hi migo,

Yes the library needs to be initialized at startup.

Also notice that this is incorrect:

```ts
this.iapStore.initialize([this.platform])
this.iapStore.update()
```

the call to `update` is not absolutely necessary and can potentially create issues (because `update` will just fetch a subset of what is fetched in `initialize`, to refresh product prices and things like that)

**Comment by mashrurbd** [comment]
> Oh, I got closer. I always initialized the library on a specific page in a VueJS "mounted" method. Now that I have put the code globally in a VueJS plugin, it runs into the finish method. :-)
> 
> No idea why this makes a difference. Subscriptions work with it now too. Only with consumables I still get this info that the product is not owned (in test mode). Is this relevant or can I ignore it?
> 
> ```
> D/CdvPurchase: executeServiceRequest() -> OK
> I/Capacitor/Console: File: http://localhost/js/app.92be4986.js - Line 1 - Msg: #FINISHED#
> W/BillingClient: Error consuming purchase with token. Response code: 8
> D/CdvPurchase: onConsumeResponse()
> D/CdvPurchase: Item is not owned by the user.
> D/CdvPurchase: callError({code:6777013, msg:"Item is not owned by the user.")
> ```

Hey migo, can you please share where you have put the code and please share the details.
