### ISSUE TITLE
store.get(productId).getOffer() returns undefined even when Play Store returns the data

### ISSUE THREAD

**Issue by hhimanshu** [j3k0/cordova-plugin-purchase#1405]
### Observed behavior
Helo, I am using CapacitorJS with this plugin ton integrate IAP with Google Play. I have succeeded to get the product listed, but when I make purchase, the code to get the offer always returns `undefined`.
The codebase is available [here](https://github.com/hhimanshu/web-payments/blob/h2/in-app/src/App.tsx)

I am able to list the products that I created in Google Play Console
https://github.com/hhimanshu/web-payments/blob/h2/in-app/src/App.tsx

I also see the logs that confirm this understanding
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/6589036/233010657-b9243d9b-47a3-4d6f-a51a-b9d7b50538dd.png">

_Include logs with `store.verbosity = store.DEBUG`_
```text
onscript loading complete
(index):3982 Create CdvPurchase...
App.tsx:62 Setting up store if this is a mobile device
store.js:1325 Create CdvPurchase...
(index):2975 [CdvPurchase] INFO: initialize()
(index):2975 [CdvPurchase.Adapters] INFO: Adding platforms: [{"platform":"android-playstore"}]
(index):2975 [CdvPurchase.Adapters] INFO: 
(index):2975 [CdvPurchase.Adapters] INFO: GooglePlay initializing...
(index):2975 [CdvPurchase.GooglePlay] INFO: Initialize
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: setup ok
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"ready","data":{}}
/favicon.ico:1     Failed to load resource: the server responded with a status of 404 (Not Found)
(index):2975 [CdvPurchase.GooglePlay] DEBUG: Ready
(index):2975 [CdvPurchase.Adapters] INFO: GooglePlay initialized. 
(index):2975 [CdvPurchase.Adapters] INFO: GooglePlay products: [{"type":"non consumable","id":"pwa_inapp_pro_9_99","platform":"android-playstore"}]
(index):2975 [CdvPurchase.GooglePlay] DEBUG: Load: [{"type":"non consumable","id":"pwa_inapp_pro_9_99","platform":"android-playstore"}]
(index):2975 [CdvPurchase.GooglePlay] DEBUG: getAvailableProducts: ["pwa_inapp_pro_9_99"] | []
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: getAvailableProducts()
(index):2975 [CdvPurchase.GooglePlay] DEBUG: Loaded: [{"productId":"pwa_inapp_pro_9_99","title":"PWA Pro (com.bonsaiilabs.payments (unreviewed))","name":"PWA Pro","description":"PWA Pro Plan","product_type":"inapp","product_format":"v11.0","formatted_price":"$12.99","price_amount_micros":12990000,"price_currency_code":"CAD"}]
(index):2975 [CdvPurchase.GooglePlay] DEBUG: getPurchases
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: getPurchases()
(index):2975 [CdvPurchase.Adapters] INFO: GooglePlay loaded: [{"className":"Product","title":"PWA Pro (com.bonsaiilabs.payments (unreviewed))","description":"PWA Pro Plan","platform":"android-playstore","type":"non consumable","id":"pwa_inapp_pro_9_99","group":"default","offers":[{"className":"Offer","id":"pwa_inapp_pro_9_99","pricingPhases":[{"price":"$12.99","priceMicros":12990000,"currency":"CAD","recurrenceMode":"NON_RECURRING"}],"productId":"pwa_inapp_pro_9_99","productType":"non consumable","productGroup":"default","platform":"android-playstore","type":"inapp"}]}]
App.tsx:103 store is ready Array(1)
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"setPurchases","data":{"purchases":[]}}
(index):2975 [CdvPurchase.GooglePlay] DEBUG: onSetPurchases: []
(index):2975 [CdvPurchase.GooglePlay] DEBUG: onPurchaseUpdated: 
(index):2975 [CdvPurchase.GooglePlay] DEBUG: getPurchases success
(index):2975 [CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"setPurchases","data":{"purchases":[]}}
(index):2975 [CdvPurchase.GooglePlay] DEBUG: onSetPurchases: []
(index):2975 [CdvPurchase.GooglePlay] DEBUG: onPurchaseUpdated: 
App.tsx:54 - title: PWA Pro (com.bonsaiilabs.payments (unreviewed))
App.tsx:57   price: $12.99 CAD
App.tsx:97 ready Array(1)
App.tsx:40 placing order for productId=pwa_inapp_pro_9_99
App.tsx:42 offer=undefined
DevTools failed to load source map: Could not load content for http://localhost/static/css/main.591b52c5.css.map: System error: net::ERR_CLEARTEXT_NOT_PERMITTED
App.tsx:40 placing order for productId=pwa_inapp_pro_9_99
App.tsx:42 offer=undefined
```

### Expected behavior
When I press upgrade, the Google Play bottomsheet should appear so that I can continue with the test purchase.

### System Info

Since I am using Capacitor, I am not sure what all other information I can provide other than the project [source code](https://github.com/hhimanshu/web-payments/tree/h2/in-app)

Looking forward to hear what I am missing

Thank you

**Comment by j3k0** [comment]
The links to your codebase don't work (private repo probably). Can you either make it public or copy/paste relevant files in a gist?

**Comment by hhimanshu** [comment]
@j3k0 , my bad and apologies. I have made it public. Thank you for your help

**Comment by hhimanshu** [comment]
@j3k0 , with my latest commit, I was able to see bottom sheet, but it says

```
The item you requested is not available for purchase
```

Here is the screenshot

<img width="415" alt="Screen Shot 2023-04-19 at 9 41 21 AM" src="https://user-images.githubusercontent.com/6589036/233143340-025c420b-39a8-455a-83d0-f610ca6526c3.png">

**Comment by hhimanshu** [comment]
Hey @j3k0 , after wrangling with my phone and Play store settings, finally, I could see this. I do not think that the code is incorrect. Thank you, for being around. This made me work harder on my side and do my due diligence.

I will do the App store work (paperwork, taxation forms), and try the same code there as well. I will keep you updated!

https://user-images.githubusercontent.com/6589036/233153407-206672a3-1d46-4071-9759-61062836b3fc.mp4

**Comment by hhimanshu** [comment]
I was able to complete the flow on Google Play Store with "Closed Testing" mode.

https://user-images.githubusercontent.com/6589036/233219216-c695b3b0-4b65-4322-9220-607ccf1d600f.mov

**Comment by j3k0** [comment]
Thanks for the update, looks good, so I'll close. feel free to reopen.
