### ISSUE TITLE
applicationUsername (metadata) not showing up in apple server notifications appAccountToken field

### ISSUE THREAD

**Issue by prenx4x** [j3k0/cordova-plugin-purchase#1406]
### Observed behavior
When ordering a product I am adding the additional metadata for applicationUsername like 
```
Store.order(productID, {
        applicationUsername: uuid,
      })
```
But when I reveice the apple server notification I can't find it in the transcationInfo in the field appAccountToken.

_Include logs with `store.verbosity = store.DEBUG`_

### Expected behavior
The applicationUsername UUID should be seen in the app store notification receipts

### System Info
iOS, Ionic v6

Output of `cordova info`.

**Comment by j3k0** [comment]
Based on the syntax, I guess you are using an older version of the plugin, right?

Make sure you use the latest version and to set `store.applicationUsername = ....` (cf documentation) -- this should work.

**Comment by mikemellor11** [comment]
I'm noticing the same issue, i'm running v13.4.0. I only noticed as it also causes app store promotional offers to fail as the signature was created with the applicationUsername but the field isn't being sent along with the order call.

If i remove the applicationUsername and pass empty strings everything works fine.

It'd be nice to set this extra field just as a bit of extra security.

**Comment by mikemellor11** [comment]
I think it's the stringArgument function. The check for isMemberOfClass is returning false for me.

```
- (NSString *) stringArgument: (id)value {
    DLog(@"%@, %d, %d, %@, %d", value, value != nil, value != NSNull.null, [value class], [value isMemberOfClass:[NSString class]]);
    if (value != nil && value != NSNull.null && [value isMemberOfClass:[NSString class]]) {
        return value;
    }
    else {
        return nil;
    }
}
```

```
Log: 2ae48240-f7cb-4ea2-9c09-285f0f2a9fb3, 1, 1, __NSCFString, 0
```

**Comment by j3k0** [comment]
OK, this used to work, but maybe Cordova or Capacitor is now using a subclass of the NSString. I'll  this change.
