### ISSUE TITLE
[iOS] Product is owned even though it has expired

### ISSUE THREAD

**Issue by orjandh** [j3k0/cordova-plugin-purchase#1408]
### Issue

I have a problem on iOS where the user will be seen as a valid subscriber even though his subscription has expired a long time ago. I am checking the subscription validity by using the owned function in the API.

The owned function seems to return true when there is an expired subscription. I Suspect this is the culprit https://github.com/j3k0/cordova-plugin-purchase/blob/c1938276876a4aea1b9247bf6836d1bc8fac7a42/src/ts/internal/verified-receipts.ts#L30 as it returns true for owned when it actually is reported as expired. Do tell if this is intended behaviour and I will try to give some more details.

### System Info

OS: macOS Monterey 12.6.5
Node: v16.15.0
npm: 9.6.5
Xcode: 14.2
iOS: 16.4.1
cordova-plugin-purchase: 13.4.0

**Comment by dimasxp** [comment]
the same problem 🤯
