### ISSUE TITLE
Product Undefined

### ISSUE THREAD

**Issue by Cdvalencia** [j3k0/cordova-plugin-purchase#1409]
Hello.

I'm trying to run a simple project to purchase products, but the plugin can't get products.

I installed the plugin as follows.

cordova plugin add cordova-plugin-purchase --variable BILLING_KEY="MY_BASE64_CODE"

![image](https://user-images.githubusercontent.com/4379656/234723774-7b136484-3da3-4d26-a652-affb8baea148.png)

![image](https://user-images.githubusercontent.com/4379656/234703876-efa4ae4d-f359-46ed-848f-721b633688c4.png)

![image](https://user-images.githubusercontent.com/4379656/234702570-5408d9bb-4a78-4a21-9fba-2e0a3a085aa3.png)

### Observed behavior

_Include logs with `store.verbosity = store.DEBUG`_

### System Info

Output of `Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    android: 11.0.0

Project Installed Plugins:

    cordova-plugin-purchase: 13.3.11
    cordova-plugin-whitelist: 1.3.5

Environment:

    OS: Microsoft Windows 10 Home Single Language 10.0.19044 (19044) (Windows 10.0.19044) x64
    Node: v16.14.0
    npm: 8.3.1

android Environment:

    android:
ERROR: Command failed with exit code 1: avdmanager list target
"avdmanager" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.cvalencia._ _ _ _" version="1.0.32" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>PurchaseNC</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="hostname" value="localhost" />
    <preference name="AndroidInsecureFileModeEnabled" value="true" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "plugins": {
    "cordova-plugin-whitelist": {},
    "cordova-plugin-purchase": {
      "BILLING_KEY": "MY_BASE_64_CODE"
    }
  },
  "platforms": [
    "android"
  ]
}
--- End of Cordova JSON Snippet ---`.

**Comment by AlexLaLiga** [comment]
How did you solve this finally?

**Comment by Cdvalencia** [comment]
the error was the line 9. that line don´t must be there.

![image](https://github.com/j3k0/cordova-plugin-purchase/assets/4379656/762f9546-3f69-41f6-a1fe-4584849bbd3f)

so worked.
