### ISSUE TITLE
Ionic v13 Documentation

### ISSUE THREAD

**Issue by razarahil** [j3k0/cordova-plugin-purchase#1415]
There is no documentation to implement this plugin in ionic with capacitor using version 13. Anyone able to integrated in the ionic project?

**Comment by petrot** [comment]
@razarahil follow my issue here: https://github.com/j3k0/cordova-plugin-purchase/issues/1416

I still have a bug on iOS, but the code itself is working.

**Comment by j3k0** [comment]
@razarahil Just follow the same documentation as for Cordova, the README also provides some pointers for ionic / capacitor. I know people that are using the plugin successfully with Capacitor so it should work.
