### ISSUE TITLE
ionic user can't work 13 version

### ISSUE THREAD

**Issue by ulsoftnaver** [j3k0/cordova-plugin-purchase#1417]
I tried to find the latest version 13 sample to work with ionic capacitor, but there is no sample

The ionic module in the link below is

https://danielsogl.gitbook.io/awesome-cordova-plugins/in-app-purchase-2

Not supported.
In the end there is no way to do it.
If you don't replace it with billing 5.0.0 by November, you won't be able to make a payment.
Is there a way?

### Observed behavior

_Include logs with `store.verbosity = store.DEBUG`_

### System Info

Output of `cordova info`.

**Comment by j3k0** [comment]
it is supported, check the related issue here:

https://github.com/danielsogl/awesome-cordova-plugins/issues/4457#issuecomment-1464871575
