### ISSUE TITLE
Can you tell me why the title is attached to the product name?

### ISSUE THREAD

**Issue by ulsoftnaver** [j3k0/cordova-plugin-purchase#1421]
Can you tell me why the title is attached to the product name?

**Comment by j3k0** [comment]
That's the way Google returns it... I think it's not the case with plugin v13 anymore, or am I mistaken?

**Comment by ulsoftnaver** [comment]
If Google returns like that, I'll use the title, but I'm using the '(' character as a split.
it's okay.
thank you

**Comment by ulsoftnaver** [comment]
this.products = this.ps.products;

                 //글짜 짤리는것 수정 ( ) 로 감싸있어서 일단 이렇게 처리함★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
                 for(let person of this.products) //현재 갯수만큼 추가..
                 {              
                    const title = person.title;   
                    const arr = title.split("(");
                    person.title = arr[0];
                  //alert(this.products[0].title);
                 }
