### ISSUE TITLE
Question: If targeting both Android and iOS on a new project, should we use v11 or v13?

### ISSUE THREAD

**Issue by jfbloom22** [j3k0/cordova-plugin-purchase#1423]
### Observed behavior

I tried to use v13, but ran into various issues on iOS.  Based on a lot of comments and the lack of documentation for iOS here: https://purchase.cordova.fovea.cc/v/v13.0/
I was able to get iOS working well with v11. 

Now I am trying to get the plugin working on Android, but I am running into various issues.  The one I am stuck on currently is that Android is logging things to the console about iOS and storekit.  I'll open a separate issue for that. 

What is unclear to me is what version of cordova-plugin-purchase is considered the most stable for iOS and Android?  Any guidance on if we should use V11 or V13 for a production application?

### System Info

Capacitor 5

**Comment by FeFB** [comment]
Hey @jfbloom22, for Android, you should use V13 because the Billing Library 5.0 will be mandatory to deploy Android applications on the Play Store after November 1st.
