### ISSUE TITLE
On Android, getting errors about iOS and Storekit

### ISSUE THREAD

**Issue by jfbloom22** [j3k0/cordova-plugin-purchase#1424]
### Observed behavior

I currently have in app purchases working well on iOS.  When I build for Android however, the plugin is not working.  I am very puzzled by these console logs:

```
[store.js] DEBUG: state: coin_5000 -> registered
[store.js] DEBUG: iOS -> product coin_500 registered
[store.js] DEBUG: iOS -> initializing storekit
InAppPurchase[js]: setup failed
[store.js] ERROR: iOS -> ERROR 677701: Setup failed - {}
```

Why am I seeing errors about iOS and Storekit when running on Android?  

### Expected behavior
Since I have everything working well on iOS, I expect to be able to follow the Android specific instructions below and for it to work.  

https://purchase.cordova.fovea.cc/use-cases/consumable-android
https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play
https://github.com/j3k0/cordova-plugin-purchase/wiki/Troubleshooting-Android

### System Info

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
  "@awesome-cordova-plugins/in-app-purchase-2": "5.45.0",
"cordova-plugin-purchase": "11.0.0",

**Comment by Kamsou** [comment]
Hello @jfbloom22, Have you found a solution for Android?

**Comment by jfbloom22** [comment]
@Kamsou i have not worked on it more yet, but when I do, I plan to use v13 for Android and stick to v11 for iOS.  See this comment:

https://github.com/j3k0/cordova-plugin-purchase/issues/1423#issuecomment-1654788953

**Comment by Kamsou** [comment]
Thanks, it solves my problem of switching to the version 13 ! 

And we no longer need @awesome-cordova-plugins/in-app-purchase-2 now, juste use
`const InAppPurchase = CdvPurchase.store` and iterate
