### ISSUE TITLE
Importing the plugin in React with Nextjs

### ISSUE THREAD

**Issue by andrea-magazzini** [j3k0/cordova-plugin-purchase#1429]
### Observed behavior

I am using React with Nextjs and Capacitor, when I try to import "cordova_plugin_purchase", I get the error "window is not defined"

### Expected behavior

A check is done that window is defined, so that the error is not thrown

**Comment by Angie-96** [comment]
any solution for this?

**Comment by andrea-magazzini** [comment]
I've used another plugin (Glassfy)
