### ISSUE TITLE
Example for version 13.0.0

### ISSUE THREAD

**Issue by rprokopenko** [j3k0/cordova-plugin-purchase#1430]
Hi all, can someone tell me where I can see some example for version 13.0.0. Because, the example which is on the official site - it is not relevant for this version. I'm most interested in an example where I can see how to identify which item was bought.

**Comment by brunoalex** [comment]
same here code dosent work

**Comment by v-trishyn** [comment]
Hi @rprokopenko 
Not sure if you still need it - but I found two examples:
the biggest so far for the Angular
https://github.com/IsraelHikingMap/Site/blob/015d6780a2f9c08440ef51f18231ed81147af638/IsraelHiking.Web/src/application/services/purchase.service.ts

and other example is from the dev.
https://gist.github.com/j3k0/8b7e72b6af43572651328c613ac86d59

**Comment by danieldanielecki** [comment]
I agree, the v13 docs is a total mess.

**Comment by j3k0** [comment]
An example can be found here: https://github.com/j3k0/cordova-subscription-example

I'm trying to put some order on that documentation... Feel free to contribute as well.
