### ISSUE TITLE
[Android] Consumables are marked as owned, cancelled order after some time

### ISSUE THREAD

**Issue by mashrurbd** [j3k0/cordova-plugin-purchase#1435]
### Observed behavior
When I purchase a consumable item, it is marked as owned and I can't purchase it again unless it automatically cancelled due to "not acknowledged" . Please help me on this. I have tried calling p.finish() inside . approved() listener.

_Include logs with `store.verbosity = store.DEBUG`_

### System Info

Output of `cordova info`.

**Comment by krunalsk007** [comment]
i think you have to add `transaction.finish()` inside .approved after `transaction.verify()`.  so that next time app open  than "`isAcknowledged`"  status changed from `false` to `true`.

**Comment by Winamp9** [comment]
Same problem when trying to buy a consumable product again - [CdvPurchase.GooglePlay] WARNING: Order failed: {"message":"ITEM_ALREADY_OWNED","code":6777003}
Did you manage to solve it? Can you provide an example? Here is my:
```
CdvPurchase.store.when().productUpdated(refreshUI);
CdvPurchase.store.when().approved((transaction) => {
if (appStartFlag) {
        transaction.finish();
        return;
}
if (transaction.state === 'approved') {
        transaction.verify();
}
}).verified((transaction) => {
       // Receiving the product 
      // ...
       transaction.finish();
});
```

**Comment by j3k0** [comment]
Old issue, I can only reproduce by registering the type of the product to `NON_CONSUMABLE`. Make sure you're registering your conumable like this:

```js
{
    id: 'consumable1',
    type: ProductType.CONSUMABLE,
    platform: Platform.GOOGLE_PLAY,
  }
```
