### ISSUE TITLE
[Ionic v7 | Capacitor v5] This Plugin v13 is not working with Capacitor

### ISSUE THREAD

**Issue by Iamarslansaleem** [j3k0/cordova-plugin-purchase#1438]
### Observed behavior

_Include logs with `store.verbosity = store.DEBUG`_

I can't provide the logs because It's not triggering it in Capacitor.

**### Expected behavior**

should work the same as version 13 working with Cordova.

**### System Info**

**Output of `project info`.**

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.1.2
   @angular-devkit/build-angular : 16.1.4
   @angular-devkit/schematics    : 16.1.4
   @angular/cli                  : 16.1.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.1.1
   @capacitor/android : 5.1.1
   @capacitor/core    : 5.1.1
   @capacitor/ios     : 5.1.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/usr/local/bin/node)
   npm    : 9.7.2
   OS     : macOS Unknown

**NOTE: Plugin version 13 is not triggering or not even responding with Capacitor. But version 11 works with Capacitor. Looking for help using In-App Purchase v13 with Capacitor v5. thanks!**

you can see my implementation in the screenshot:
![image](https://github.com/j3k0/cordova-plugin-purchase/assets/43752181/8a947c2b-9254-4efa-9ba7-b095a992889a)

**Comment by Iamarslansaleem** [comment]
Hi @j3k0, can you please help me out here real quick?

**Comment by v-trishyn** [comment]
Nothing could be seen in the implementation.
So are you certain that you have installed v13?
Also maybe you need to remove `@awesome-cordova-plugins/in-app-purchase-2` completely - v13 has been implemented in TS and has bundled js file, I'm not sure how `@awesome-cordova-plugins/in-app-purchase-2` is working with this plugin, maybe it is intercepting current pure workflow.
Have you seen a message within the console `Create CdvPurchase...`?

**Comment by j3k0** [comment]
@Iamarslansaleem Have you solved this?
