### ISSUE TITLE
[Android] v13 with Capacitor - can't initialize IAPs - DEVELOPER_ERROR: SKU name can't be empty

### ISSUE THREAD

**Issue by AEiosApp** [j3k0/cordova-plugin-purchase#1440]
### Observed behavior
**CdvPurchase.store.initialize()** never finished on Android with Capacitor, but same code works perfect on:
- iOS with Capacitor
- Android with Cordova (on my another older app)

On the **Logcat** I've:
- checked that **CdvPurchase.store.initialize()** starts after **device ready**
- found an issue:
```
queryAllProductDetails() -> Failed: Unsuccessful query. DEVELOPER_ERROR: SKU name can't be empty.
callError({code:6777002, msg:"Error. DEVELOPER_ERROR: SKU name can't be empty.")
```
![DeviceReady](https://github.com/j3k0/cordova-plugin-purchase/assets/19554725/e9bc6cd4-2b2b-473d-824f-b11aab70d878)
<img width="1381" alt="Screenshot 2023-07-13 at 11 51 47 PM" src="https://github.com/j3k0/cordova-plugin-purchase/assets/19554725/e67bea5f-e7a9-4e04-b7dc-cb01b4c5afc9">

Here's my code:

```
// --- initIAPs ---
// iaps: IAP ids (Array of String)
async function initIAPs(iapIDs, appID, paidToFree) {
  return new Promise(async (resolve) => {
    // register all IAPs in purchase plugin
    var iapsToRegister = []
    console.log('window:')
    console.log(window)
    var platform = window.CdvPurchase.Platform.GOOGLE_PLAY

    const gs = useGlobalsStore()
    if (gs.platform === 'ios') {
      platform = window.CdvPurchase.Platform.APPLE_APPSTORE
    }

    iapIDs.forEach((id) => {
      const iapToRegister = {
        id: id,
        type: window.CdvPurchase.ProductType.NON_CONSUMABLE,
        platform: platform,
      }
      iapsToRegister.push(iapToRegister)
    })

    console.log('#iaptest iapsToRegister: ' + JSON.stringify(iapsToRegister))
    window.CdvPurchase.store.register(iapsToRegister)

    window.CdvPurchase.store.when().productUpdated((product) => {
      console.log(
        '#iaptest initial product update ' +
          product.id +
          ' (owned: ' +
          product.owned +
          '):\n' +
          JSON.stringify(product)
      )
      // resolve(true)
    })

    window.CdvPurchase.store.initialize().then(() => {
      console.log('#iaptest iaps initialised!')
      resolve(true)
    })
  })
}
```

So `console.log('#iaptest iaps initialised!')` never fired on Android.

IAPs configured in Google Play correctly - all of them works fine with production version in Play Store.
IAPs array to register looks correct:

<img width="1432" alt="Screenshot 2023-07-13 at 11 53 16 PM" src="https://github.com/j3k0/cordova-plugin-purchase/assets/19554725/2f38faac-c427-4b7c-917a-4cf6ff33a5fa">

### Expected behavior

In my another, cordova app with the same plugin version v13.6.0 **queryAllProductDetails()** works fine and return product details:

<img width="1379" alt="Screenshot 2023-07-14 at 8 20 21 AM" src="https://github.com/j3k0/cordova-plugin-purchase/assets/19554725/e2894778-17eb-4193-8ba3-1b3d23ddc3ba">

### System Info
cordova-plugin-purchase v13.6.0
capacitor v3.4.3

Output of `cordova info`.

**Comment by AEiosApp** [comment]
@j3k0 check please, and let me know if any debug tests or log can help you to investigate this issue 🙏

**Comment by dferenc-netwizzy** [comment]
Not sure if revelant to Your issue, but i had to specify the `group` explicitly to get v13 working on android

```javascript
store.register({
  id: "PRODUCT_SKU",
  type: CdvPurchase.ProductType.CONSUMABLE,
  platform: CdvPurchase.Platform.GOOGLE_PLAY,
  group: 'default'
})
```

**Comment by AEiosApp** [comment]
@dferenc-netwizzy thanks for the comment, but I've started getting more bug reports from users, seems like v13 is not yet ready, I'll roll back to the stable v11.

**Comment by AEiosApp** [comment]
Issue has gone on v13.10.1
