### ISSUE TITLE
Product Availability Filtering based on availability region

### ISSUE THREAD

**Issue by raghav-kokotree** [j3k0/cordova-plugin-purchase#1441]
We are currently using the cordova-plugin-purchase in my Cordova app for handling in-app purchases and subscriptions. We have encountered an issue regarding the retrieval of products using the plugin.

Currently, when we fetch the products using the `store.register` method, it returns all the products registered in our Apple App Store Connect account, regardless of their availability in the end user's region. This creates a problem as we need to filter out the products that are not available for the user's region.

Specifically, we have a monthly subscription product (e.g., "com.mydomain.monthly") available only in specific regions on the App Store Connect and yearly one "com.mydomain.yearly" available to all regions. 

Here is how we are fetching the products:
```
  store.register([
      {
        id: "com.mydomain.monthly"
        type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
        platform: CdvPurchase.Platform.APPLE_APPSTORE
      },
      {
        id: "com.mydomain.yearly",
        type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
        platform: CdvPurchase.Platform.APPLE_APPSTORE
      }
    ]);
```

However, when we fetch the products, both the monthly and yearly subscriptions are returned, even if the user's device app store region does not match the availability region for the monthly subscription. Additionally, the response does not provide any property that indicates whether a product is available for the user's region. The `canPurchase` property is set to true for both products, which does not help us differentiate their availability.

**Comment by j3k0** [comment]
Old issue, but for reference, Apple should only return available products, so this isn't an issue with the product. Make sure the AppStore sandbox user is in the region you think it is.
