### ISSUE TITLE
New Subscription API of Google

### ISSUE THREAD

**Issue by hcphuc2595** [j3k0/cordova-plugin-purchase#1445]
Hello, 
I've seen today in the Google play console of my app a warning like this
"You're using the InAppProduct API to manage subscriptions, which is now deprecated and will stop being supported for new apps in January 2024, and for all apps in May 2024. Start using the new Subscriptions API to get new features including multiple base plans and offers, as well as prepaid plans" 
And I'm using this library to implement in app purchase for our app written with capacitor/cordova with version 10.5.3 so I'm not sure if this version is ok with the warning from Google or I have to update to which version of this lib? And if yes, can you provide me some documentation what I need to change for the update, pls? Thanks a lot and have a good day.

**Comment by Mustafax06** [comment]
+1

**Comment by hcphuc2595** [comment]
Can you help me to provide the answer because it's really important for us to work on a project with my client? Thanks in advance!

**Comment by AntonAI** [comment]
@j3k0 Any comments on this? Does the recent v13 release already addressed this issue/migration, or not?

**Comment by j3k0** [comment]
Yes, the billing library has been updated with version 13.

**Comment by hcphuc2595** [comment]
Thank you for your response so in this case, can you provide any documentations on how to update the lib to version 13, pls?

**Comment by j3k0** [comment]
Link to migration guide is listed on the README in this repo.
