### ISSUE TITLE
Plugin works on Android even without the billing key specified during installation

### ISSUE THREAD

**Issue by gianlucag** [j3k0/cordova-plugin-purchase#1457]
In https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play#setup-android-applications  it's clearly stated that the plugin should be installed with the billing key specified. It doesn't specify why it should be added and what would happen if not specified. My understanding is that the plugin should not work without a specified billing key. Is the key used only to verify a transaction? That would explain why everything works. Didn't try the verifying process yet.

### Observed behavior

Plugin works without ever specifying a billing key during installation

### Expected behavior

Something along the purchase flow should fail. But I'm able to buy the SKU and successfully complete the purchase flow.

**Comment by danieldanielecki** [comment]
@gianlucag, can you show your sample code?
Sadly, I can't get it working at all with the `v13`.

**Comment by gianlucag** [comment]
@danieldanielecki Hi Daniel, mine is more a general question about what's the purpose of specifying the billing privare key at installation time. The documentation doesnt explain it.

I assume it's used to verifiy a signed transaction but even if that was the case, one has to specify a validator function (i.e. custom code to validate a transaction).

Unfortunately the documentation is not very clear.

**Comment by danieldanielecki** [comment]
Documentation is indeed tragic. You need to find answers in comments to issues :(

**Comment by orjandh** [comment]
I think this was the old behaviour. No need to provide any key when installing the plugin anymore. You provide it in the code if you use fovea or iaptic backend.
