### ISSUE TITLE
CdvPurchase.store.when().approved is triggered twice

### ISSUE THREAD

**Issue by sergip76** [j3k0/cordova-plugin-purchase#1458]
CdvPurchase.store.when().approved is triggered when a transaction status changes to approved, as expected, but also when this transaction changes to finished.
I solved it incuding this in callback:
`if (transaction.status === "approved") { }`
but it seems a bug.

Plugin version: 13.6.0
Platform: Android 12.0.0
Cordova: 12.0.0 (cordova-lib@12.0.1)

**Comment by j3k0** [comment]
Hi. Can you provide full logs (with `store.verbosity` set to `DEBUG`)?

**Comment by sergip76** [comment]
This is the LOGS:

Create CdvPurchase...
[CdvPurchase] INFO: initialize()
[CdvPurchase.Adapters] INFO: Adding platforms: [{"platform":"ios-appstore"},{"platform":"android-playstore"}]
[CdvPurchase.Adapters] INFO: 
[CdvPurchase.Adapters] INFO:
[CdvPurchase.Adapters] INFO: AppStore initializing...
[CdvPurchase.Adapters] INFO: AppStore is not supported.
[CdvPurchase.Adapters] INFO: GooglePlay initializing...
[CdvPurchase.GooglePlay] INFO: Initialize
[CdvPurchase.GooglePlay.Bridge] INFO: setup ok
[CdvPurchase] INFO: update()
[CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"ready","data":{}}
[CdvPurchase.GooglePlay] DEBUG: Ready
[CdvPurchase.Adapters] INFO: GooglePlay initialized.
[CdvPurchase.Adapters] INFO: GooglePlay products: [{"id":"*******","type":"non consumable","platform":"android-playstore"}]
[CdvPurchase.GooglePlay] DEBUG: Load: [{"id":"******","type":"non consumable","platform":"android-playstore"}]
[CdvPurchase.GooglePlay] DEBUG: getAvailableProducts: ["*******"] | []
[CdvPurchase.GooglePlay.Bridge] INFO: getAvailableProducts()
[CdvPurchase.GooglePlay] DEBUG: Loaded: [{"productId":"*******","title":"Remove advertisements","name":"Remove advertisements","description":"Remove advertisements from app.","product_type":"inapp","product_format":"v11.0","formatted_price":"€7.49","price_amount_micros":7490000,"price_currency_code":"EUR"}]
[CdvPurchase.Adapters] INFO: GooglePlay products loaded: [{"className":"Product","title":"Remove advertisements","description":"Remove advertisements from app.","platform":"android-playstore","type":"non consumable","id":"com.altairapps.bicimad.publi","offers":[{"className":"Offer","id":"com.altairapps.bicimad.publi","pricingPhases":[{"price":"€7.49","priceMicros":7490000,"currency":"EUR","recurrenceMode":"NON_RECURRING"}],"productId":"****","productType":"non consumable","platform":"android-playstore","type":"inapp"}]}]
[CdvPurchase.GooglePlay] DEBUG: getPurchases
[CdvPurchase.GooglePlay.Bridge] INFO: getPurchases()
[CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"setPurchases","data":{"purchases":[]}}
[CdvPurchase.GooglePlay] DEBUG: onSetPurchases: []
[CdvPurchase.GooglePlay] DEBUG: onPurchaseUpdated:
[CdvPurchase.AdapterListener] DEBUG: receiptsReady: android-playstore
[CdvPurchase.GooglePlay] DEBUG: getPurchases success
[CdvPurchase] DEBUG: Calling callback: type=productUpdated() name=
[CdvPurchase.Adapters] INFO: GooglePlay receipts loaded: []
[CdvPurchase.AdapterListener] DEBUG: setSupportedPlatforms: android-playstore
[CdvPurchase] DEBUG: Calling callback: type=receiptsReady() name=
[CdvPurchase.ReceiptsMonitor] DEBUG: receiptsReady...
[CdvPurchase.ReceiptsMonitor] DEBUG: check(0/0)
[CdvPurchase.ReceiptsMonitor] INFO: receiptsVerified()
[CdvPurchase.GooglePlay] INFO: Order - {"className":"Offer","id":"******","pricingPhases":[{"price":"€7.49","priceMicros":7490000,"currency":"EUR","recurrenceMode":"NON_RECURRING"}],"productId":"****","productType":"non consumable","platform":"android-playstore","type":"inapp"}
[CdvPurchase.GooglePlay.Bridge] INFO: buy()
SP>> Compra iniciada!!
[CdvPurchase.GooglePlay.Bridge] INFO: listener: {"type":"purchasesUpdated","data":{"purchases":[{"orderId":"GPA.*****","packageName":"******","productId":"*****","purchaseTime":1693846533662,"purchaseState":0,"purchaseToken":"mineioammcfokmhdpplbngfn.AO-J1OzkXX9iM3N2SOEOdOHWLwz0pAYFNcoM1szXx4k_MhXftO60Fe_j1SjtenSoiGkdt4v716P3K0NHKczNBuEOPtv6T6QuTcRaBuTfABtfYCyGRkO-9js","quantity":1,"acknowledged":false,"productIds":["*******"],"getPurchaseState":1,"developerPayload":"","autoRenewing":false,"accountId":"","profileId":"","signature":"FLuzaBgyM3ZA0sXPb+pbFJC53AAE5nKHZZFUqBKBVgnkGBN/NCNmR5pk01b9BIUd/HuHs4e8IztaKTib0L2JcIXR3nhgKGUnzlYa9JqdPZuYgINv3bYBlYBnkG1zY4V00aglkJWtcbGPzfVs4L7tCjwRXF/ym/OsKEwSP5p6DJdVSIGXFk01jqW5d2TJwlEjNtaBRE8OJsXgKOaTMf9NBjr5q/6rwRZNSRjtW/HWRD2uSOww8bDFsR1wZ6TVg2lOzT6/wMMQ5yZzq/9IMeRZApq15uxX5YAPvAaJ1H7uVGL+EQALdAsHwZ9EbA+UZQj8ZUgN5oPUrb6h58iZU4+WPw==","receipt":"{\"orderId\":\"GPA.3363-0208-6075-20251\",\"packageName\":\"*****\",\"productId\":\"*****\",\"purchaseTime\":1693846533662,\"purchaseState\":0,\"purchaseToken\":\"mineioammcfokmhdpplbngfn.AO-J1OzkXX9iM3N2SOEOdOHWLwz0pAYFNcoM1szXx4k_MhXftO60Fe_j1SjtenSoiGkdt4v716P3K0NHKczNBuEOPtv6T6QuTcRaBuTfABtfYCyGRkO-9js\",\"quantity\":1,\"acknowledged\":false}"}]}}
[CdvPurchase.GooglePlay] DEBUG: onPurchaseUpdated: GPA.******
[CdvPurchase] DEBUG: Calling callback: type=approved() name=
[CdvPurchase] DEBUG: Calling callback: type=approved() name=
[CdvPurchase] INFO: finish(Transaction)
[CdvPurchase.GooglePlay.Bridge] INFO: acknowledgePurchase()
[CdvPurchase] DEBUG: Calling callback: type=finished() name=

**Comment by knaito-asial** [comment]
I meet the same issue.
In the first call of approved callback, `transaction.state` is `approved`,
In the second call of approved callback, `transaction.state` is `finished`.

Therefore I use the following approved callback.
```
function approvedPurchase(transaction) {
  if (transaction.state === 'approved') {
    log('--- approved ---');
    console.log(transaction);
    transaction.finish();  
  } else {
    log('--- approved 2 (already finished) ---');
    // Nothing to do. (Already Finish)
  }
} 
```

In store.js, I found that first the following code is called

https://github.com/j3k0/cordova-plugin-purchase/blob/5ee54a1597d0c6d5fca5ccec0857e0282f866bdd/www/store.js#L4670

then the following code is executed 

https://github.com/j3k0/cordova-plugin-purchase/blob/5ee54a1597d0c6d5fca5ccec0857e0282f866bdd/www/store.js#L4665

**Comment by j3k0** [comment]
Is it possible that:

- @sergip76 you are registering the callback twice? (2 calls to `store.when()`)
- @knaito-asial  you are calling both `store.initialize()` and `store.update()` or something similar?

**Comment by sergip76** [comment]
> * @sergip76 you are registering the callback twice? (2 calls to `store.when()`)

I only use 2 handlers. Once each one:

```
CdvPurchase.store.when().approved()
CdvPurchase.store.when().productUpdated()
```

and .approved() is called twice after buy the product.


But when I launch the app I called both initializa and update:
```
CdvPurchase.store.initialize();
CdvPurchase.store.update();
```

Do I have to use only initialize()?

**Comment by j3k0** [comment]
> Do I have to use only initialize()?

Yes. `store.update()` should be called except if you want to refresh the price of products a long time after initialization.

**Comment by ivancduran** [comment]
I have exactly the same issue.

I have several validations to prevent this in my code, but it still happens.

I'm just using:

```
this.store.initialize([this.Platform.GOOGLE_PLAY]);
```

In the code of my application I have a function that does reload to refresh all the components

```
window.location.reload();
```

And every time the page is updated the trigger is duplicated, but it only happens with approved, the verified trigger is only launched once as it should be.

I am using angular and capacitor, the entire in-app purchase is as a service.

```
      if (this.store.products != null && this.store.products.length === 0) {
        await this.registerProducts();
        await this.setupListeners();
      }
      this.store.initialize([this.Platform.GOOGLE_PLAY]);
```

I want to know if is there any way to get the listeners or remove the duplicated.

Thank you.
