### ISSUE TITLE
How to clear CONSUMABLE product

### ISSUE THREAD

**Issue by danieldanielecki** [j3k0/cordova-plugin-purchase#1459]
I really can't find this in the documentation, but after using the product, I'd like to be allowed to purchase it again.
However, I can't really find it in the [store's API](https://github.com/j3k0/cordova-plugin-purchase/blob/v13/api/classes/CdvPurchase.Store.md).

Currently, the user is seeing `Error. You already own this item.` while trying to purchase the same item. While, this is correct behaviour when the user tries to buy it again right after buying for the first time, but after playing a game and using it, I'd like to consume the purchases, but don't know how.

**Comment by danieldanielecki** [comment]
@knaito-asial thanks for the contribution!

What about clearing consumed purchased order, so those could be re-order again?

**Comment by knaito-asial** [comment]
If your product type is `CdvPurchase.ProductType.CONSUMABLE`, the purchased products are automatically consumed.
Could you check the product type?  In my case, I used `CdvPurchase.CONSUMABLE` by mistake which is undefined.

Anyway, we can consume the purchased order directly if we know the purchaseToken.

```
store.getAdapter(CdvPurchase.Platform.GOOGLE_PLAY).bridge.consumePurchase(function (x) { console.log(x); }, function (e) { console.log("err",e); }, "Actual Token");
```
Please replace the third argument in `consumePurchase` method with the actual purchaseToken you want to consume.

**Comment by YBurkhardt** [comment]
I also tried to build my app again and have the same behavior. I use CdvPurchase.store.CONSUMABLE . => "consumable" . But I also can buy it only once. I am sure that this worked a time ago without manually consuming

**Comment by giuseeFG** [comment]
i have the same issue!

**Comment by knaito-asial** [comment]
@danieldanielecki Actual Token means your own purchaseToken.

You may see your own purchaseToken by my first codes
```
const {store, ProductType, Platform} = CdvPurchase;
store.getAdapter(CdvPurchase.Platform.GOOGLE_PLAY).bridge.getPurchases(function (r) { 
  console.log('------ productId, purchaseToken ------'); 
  r.forEach(i => { console.log(i.productId, ':', i.purchaseToken); } ); 
  console.log('-------------------------------------'); }, function (e) { console.error(e); 
});
```

You can execute this code in the chrome inspector console which is connected to the USB connected Android device.

Anyway, if this plugin works properly, manual consuming is not necessary.
Because this plugin consumes purchased order automatically if the product type is `consumable`.
We can see this logic in the following code 

https://github.com/j3k0/cordova-plugin-purchase/blob/b402df92ca4649d142deb162082f851578df0144/www/store.js#L4495-L4497

This is called when the transaction is finished.
(transaction.finish() is called)

**Comment by j3k0** [comment]
You shouldn't have to call the bridge methods. `transaction.finish()` will consume the purchase if the type is `CONSUMABLE`.

**Comment by danieldanielecki** [comment]
> You shouldn't have to call the bridge methods. `transaction.finish()` will consume the purchase if the type is `CONSUMABLE`.
> 
> Example:
> 
> ```ts
> store.when().approved(transaction => {
>   somehowProvideFeature().then(() => {
>     transaction.finish();
>   });
> });
> ```
> 
> If integrating with a receipt validation service (https://www.iaptic.com), you need to wait for the purchase to have been validated. Then ideally you let your server do the job of providing the feature (virtual currency or something), when notified via iaptic's webhook, then notify the app when it's done.

It's working, thanks!

**Comment by pratik-io** [comment]
> About Android, Following command may help you to find the order which is purchased but not consumed.
> 
> ```
> const {store, ProductType, Platform} = CdvPurchase;
> store.getAdapter(CdvPurchase.Platform.GOOGLE_PLAY).bridge.getPurchases(function (r) { 
>   console.log('------ productId, purchaseToken ------'); 
>   r.forEach(i => { console.log(i.productId, ':', i.purchaseToken); } ); 
>   console.log('-------------------------------------'); }, function (e) { console.error(e); 
> });
> ```

I'm using a new version(13.8.6), but no variable named `bridge` exists.
How do I get unconsumed transactions on the new version?

**Comment by j3k0** [comment]
You should find all transactions in `CdvPurchase.store.localTransactions`. However with the recommended implementation, your app should be ready to handle pending transaction and handle `approved` events which will be triggered for unconsumed transactions at startup, and identically when a purchase is made.
