### ISSUE TITLE
Owned status without using validation server

### ISSUE THREAD

**Issue by thebordella** [j3k0/cordova-plugin-purchase#1461]
In this v13 Migration Guide there is a [section #2](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13#2-using-receipt-validation-with-no-back-end-server) called "Using receipt validation with no back-end server". This is exactly what I want to do for a simple app with no user accounts.

The first example given is this:

`store.when().verified(receipt => {
  if (store.owned("my-product")) {
    console.log("my-product is owned");
  }
});`

However in my tests, verified() is never triggered without having defined a URL for store.validator. But I'm not using a validator in this scenario!

So I am confused. How is it possible to get product owned status (single product, non-consumable) without using a validator, any back-end server, or any local receipt validation?

**Comment by j3k0** [comment]
With version 13.7.0, calling `verify()` without a validator will resolve call `verify()` immediately.

As for the `owned` status, it should work except for subscriptions on iOS (because the expiry date is not known locally).
