### ISSUE TITLE
Google Play Android: BillingFlowParams.PRORATION_MODE is Deprecated

### ISSUE THREAD

**Issue by lincolnthree** [j3k0/cordova-plugin-purchase#1462]
Looks like Google has deprecated PRORATION_MODE in favor of a new API.

https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.ProrationMode

Just wanted to give a heads up that this may be going away soon. Hopefully this is useful information.

**Comment by j3k0** [comment]
Thanks for the heads up, it's still available in Billing Library v6 but we will probably handle that when doing the upgrade.
