### ISSUE TITLE
Question: What does "Sub-project dependencies start" mean and why can't I override Billing version?

### ISSUE THREAD

**Issue by avalanchas** [j3k0/cordova-plugin-purchase#1469]
### Question
Please forgive me this might be quite the silly question, or even the wrong place to ask. I am quite new to capacitor/cordova, any help or redirection is greatly appreciated 🙇 

I set up my capacitor project and for most dependency versions, there is an override of the version I can do by setting the `$version` variable myself and then the build uses my version like so
![image](https://github.com/j3k0/cordova-plugin-purchase/assets/6008266/875891bc-04a1-4b43-b447-3440d517f927)

However, that does not seem possible for the Google Play Billing library, as it is hardcoded in the plugin gradle
![image](https://github.com/j3k0/cordova-plugin-purchase/assets/6008266/3c9affbc-d28d-4d0e-a0eb-188c531500c8)

However, it is put between the comments
```
// SUB-PROJECT DEPENDENCIES START
// SUB-PROJECT DEPENDENCIES END
```
so I still have some hope that I can configure this myself? 
We'll need version 6.0.1 to be compatible with Android 14
https://developer.android.com/google/play/billing/release-notes#6-0-1

**Comment by j3k0** [comment]
Old issue, have you solved it? Notice that version 5.2.1 supported by plugin version 13.8.0 is also compatible with Android 14. I believe `// SUB-PROJECT DEPENDENCIES START` is added by capacitor to indicate lines added by things like plugins.
