### ISSUE TITLE
No support for phongap-build

### ISSUE THREAD

**Issue by yarontt** [j3k0/cordova-plugin-purchase#147]
Would be great to have support for phonegap build.
I haven't really done it before, but it should be simple. See here:
https://build.phonegap.com/plugins

**Comment by Fortuitous** [comment]
I am confused about this.  This PhoneGap Build page seems to say that you can use plugins from either PhoneGap Build or from plugins.cordova.io -- which is where this plugin lives:

http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins 

So PhoneGap build seems to think we should be able to use this plugin.  Has anyone done so?  Documentation seems not to exist for this use.

**Comment by Fortuitous** [comment]
Update: Yes, but No.
There is no "support" for Phone Gap Build.  But, as of December 2014, Phone Gap Build offers support for Cordova plugins:  

http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/ http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins

By following the directions in the pages above, I was able to load this plugin through Phonegap Build.  The call in my config.xml reads as follows:

```
<gap:plugin name="cc.fovea.cordova.purchase" source="plugins.cordova.io">
    <param name="BILLING_KEY" value="MIIB . . . (my billing key) . . . AB" />
</gap:plugin>
```

This works.  After lots of fiddling, I was able enact sandbox purchases in both iOS and Android.  But . . . after that first purchase my Android app crashes.  I believe this is Issue #103, #123 and this one:
http://www.html5gamedevs.com/topic/12570-in-app-purchase-mission-accomplished/

Follow those links to find the "fix"  which is to not use the plugin as a plugin, but download it, add the code manually, and edit one file.  As far as I can tell, this fix has no analog for PhoneGap Build.  :(

Can anyone comment on how they have surpassed this roadblock?

Is it possible to fork this repo, make the change described in the links, add the edited repo to plugins.cordova.io, and use that for PhoneGap Build?  

Or might someone fix the bug in this repo and resubmit?

Would love to hear what people are doing, thanks.

**Comment by yarontt** [comment]
Ah... yes, I've managed to use this method to get the plugin in my PGB app.

When you say "sandbox" purchases, you mean real purchases for test users or the "android.test.*" ones? I could only get test users purchase (the first one I mentioned).

Is there any chance someone can fix this? If not, I actually might be able to do it.

**Comment by Fortuitous** [comment]
@yarontt  "When you say "sandbox" purchases, you mean real purchases for test users or the "android.test.*" ones? I could only get test users purchase (the first one I mentioned)."

I did not try the android.test "static responses" as defined here:
http://developer.android.com/google/play/billing/billing_testing.html

I only tried "real" purchases for test users (which are not actually billed to credit cards).  

I got one to work, but the app crashed upon the next call to refresh(), as described in the bugs above.  

I take it you have not gotten much further.  :(  

In #145 , user trayagains suggests: "you can fork the plugin and install your version after you edit the xml as you have access to the plugins."  However, I think this would mean having to add your personal billing code to your fork of the plugin and then publishing that fork which would only work for you (and would let anyone else see your personal billing code).  Seems suboptimal.

**Comment by yarontt** [comment]
Sorry, missed your reply somehow...

I encountered the same issue :(
Will try using the fork instead... 
Any chance you could point me to the working fork? (I remember someone posted it somewhere but can't find it).

Also, any chance the plugin's owner might fix this??

**Comment by rob-baker** [comment]
i've hit the same problem. I have updated the billing_key_param in every location suggested in this thread and the others with no joy.

On windows, i use 

    >cordova build --debug
to build my .apk file. 

Should the "res/values/billing_key_param.xml" file be in the .apk file?

my logs:

    06-08 20:55:39.115: D/IabHelper(5858): Billing service connected.
    06-08 20:55:39.115: D/IabHelper(5858): Checking for in-app billing 3 support.
    06-08 20:55:39.125: D/IabHelper(5858): In-app billing version 3 supported for com.pathuku
    06-08 20:55:39.135: D/IabHelper(5858): Subscriptions AVAILABLE.
    06-08 20:55:39.135: D/CordovaPurchase(5858): Setup finished.
    06-08 20:55:39.135: D/CordovaPurchase(5858): Setup successful. Querying inventory w/ SKUs.
    06-08 20:55:39.135: D/IabHelper(5858): Starting async operation: refresh inventory
    06-08 20:55:39.135: D/IabHelper(5858): Querying owned items, item type: inapp
    06-08 20:55:39.135: D/IabHelper(5858): Package name: com.pathuku
    06-08 20:55:39.135: D/IabHelper(5858): Calling getPurchases with continuation token: null
    06-08 20:55:39.135: D/IabHelper(5858): Owned items response: 0
    06-08 20:55:39.135: E/IABUtil/Security(5858): Purchase verification failed: missing data.
    06-08 20:55:39.135: W/IabHelper(5858): In-app billing warning: Purchase signature verification **FAILED**. Not adding item.
    06-08 20:55:39.135: D/IabHelper(5858):    Purchase data: {"packageName":"com.pathuku","orderId":"transactionId.android.test.purchased","productId":"android.test.purchased","developerPayload":"","purchaseTime":0,"purchaseState":0,"purchaseToken":"inapp:com.pathuku:android.test.purchased"}
    06-08 20:55:39.135: D/IabHelper(5858):    Signature: 
    06-08 20:55:39.135: D/IabHelper(5858): Continuation token: null
    06-08 20:55:39.145: D/IabHelper(5858): Ending async operation: refresh inventory
    06-08 20:55:39.145: D/CordovaPurchase(5858): Inside mGotInventoryListener
    06-08 20:55:39.175: D/SystemWebChromeClient(5858): http://192.168.0.9:7780/inAppPayments.js: Line 433 : ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)
    06-08 20:55:39.175: I/chromium(5858): [INFO:CONSOLE(433)] "ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)", source: http://192.168.0.9:7780/inAppPayments.js (433)


I'm completely stuck on this

**Comment by aphil** [comment]
I'm having the same problem with phonegap build, so I can't edit the billing_key_param.xml. Anyone found a way to make it work?

**Comment by yarontt** [comment]
I use   <gap:plugin name="cc.fovea.cordova.purchase" source="npm" version="3.11.0">
and it works fine.
