### ISSUE TITLE
Ionic not updating UI when changes are invoked inside store.when 

### ISSUE THREAD

**Issue by hccue** [j3k0/cordova-plugin-purchase#1475]
### Observed behavior

When a UI change (like a text changed) is invoked from within store.when.approved, the UI is not updated.
I understand this is an async function, but no other interfering code is running elsewhere or afterwards.
I can confirm the code is executed (in the logs) but the UI is not updated until I fire some other event that triggers UI refresh and then I can see the changes that were already made.

### Expected behavior
UI Update as in any other scenario where a displayable UI element is changed.

### System Info

Angular v15
Ionic V7
in-app-purchase-2 V5.45.0

**Comment by j3k0** [comment]
That's an ionic issue, isn't it?
