### ISSUE TITLE
Play Billing Library requirements for Android 14 compatibility

### ISSUE THREAD

**Issue by itbeyond** [j3k0/cordova-plugin-purchase#1478]
This alert just poped up on one of my apps after I published an update which included the V13 release of this repo.

Android 14 has introduced new [security changes](https://notifications.google.com/g/p/ANiao5qy9imBWpEKWE_Ki5Zhc7UzK3IkydAgWzw1mbkfBIDKhuUHuqWnbp-N78Em2mr4Xe3ehdTfQZNjWMQ6AwNy9qoy3TF0b9u_W4JZlFL4Fuq71UF93XbvEwTLvj4ik5mPdXius_unkwURy8hjVItyQpj-YthTosPDPnKv2ICQjROsXUaoxskRr7NA7Ifo1SxQ0fDr5wTHYHDDT1NTTTkCCoSSXzBpoUC0Dm1e-S9CdkYd1RfD2xhrgttCKnzjHQPvgkS_Ld5P3C3aF-5Aog8RML7GiTNyo9pm88GiElynFQ) which affect apps targeting Android 14. In order to ensure compatibility, Google has released [Play Billing Library version 6.0.1 and 5.2.1](https://notifications.google.com/g/p/ANiao5r97vANjhAnZnjBs5juFzEXCyPhm9GygcvDQThr-a0CIoiNo6EQ3rDan9Nt1Ky-XNt-mvZSFm-eXIxeDFKoND6ybffh6tk_jit2rMSzvVa1EnywHz4FZtp33YJRsDEOjXYHaaGnwNXde6z8qOd4r3L9rQyNrywmoIkzn--hZLCkjQ9DjXf_kzu1L6WV_Ay9U5yWVifQLiX_Mnh-8lvEIz5e-iZZD9fKJmyM6XOPJQ_04395HZE6_T2rd6ZVNDFfo6b8jITIr3RkWz_2pf4rUhaT). When updating your app to target Android 14, following these [migration steps](https://notifications.google.com/g/p/ANiao5p2JpFGFK1u6l-mRyUAb8DjrUy17jxgk-kHb_s_Os_b1widlSWUqAIF5vSPwfJT0V_S52c2Bfb82wn05R62CC7TNGmVK_HJc-9NLy65XuYwFYGsmCuX6p_boKD6MJ19K_crloAS9ic6r9dIQD-xiET5coHH2diA4J03ihMRnAzq9SL6bY49n5Rw_nnRKOA34D4tDrFr3XekzMfuzMwvXu2XOV7ZSs6lSiD53dz1M0A-6W3zKdV3sOq6uZ_2FnkGgt4CM1KN), you will need to update your app to either of these versions of the Play Billing Library to be compatible with the recent security changes.

These changes only affect your app when it starts targeting Android 14. Users running Android 14 while your app is not targeting Android 14 are unaffected.

Are we able to run 5.2.1 without issue as the default seems to install 5.0.0, I am not targeting 14 but it will not be long before we are required/forced to?

**Comment by j3k0** [comment]
Since version `13.8.0`, the plugin uses Billing Library version `5.2.1`
