### ISSUE TITLE
Error initializing plugin on some Android devices (white/blank screen)

### ISSUE THREAD

**Issue by fellipefonseca** [j3k0/cordova-plugin-purchase#1483]
### Observed behavior

Some users are reporting white screen when launching our app. We notice that it is being requested more than 1 GB of available RAM on the smartphone to initialize. If the smartphone has less than 1 GB of available RAM, the plugin won't initialize and our app fails to launch.

### System Info

Output of `cordova info`.
Cordova Packages:

    cli: 10.0.0
        common: 4.1.0
        create: 3.0.0
        lib: 10.1.0
            common: 4.1.0
            fetch: 3.1.0
            serve: 4.0.1

Project Installed Platforms:

    android: 10.1.2

Project Installed Plugins:

    cordova-clipboard: 1.2.1
    cordova-plugin-advanced-http: 3.3.1
    cordova-plugin-android-permissions: 1.1.5
    cordova-plugin-androidx-adapter: 1.1.3
    cordova-plugin-apprate: 1.4.0
    cordova-plugin-calendar: 5.1.5
    cordova-plugin-camera: 6.0.1-dev
    cordova-plugin-cocoapod-support: 1.6.2
    cordova-plugin-contacts: 3.0.1
    cordova-plugin-crop: 0.3.1
    cordova-plugin-datepicker: 0.9.3
    cordova-plugin-device: 1.1.7
    cordova-plugin-dialogs: 2.0.1
    cordova-plugin-facebook-connect: 2.3.0
    cordova-plugin-fcm-with-dependecy-updated: 7.8.0
    cordova-plugin-file-opener2: 3.0.5
    cordova-plugin-file-transfer: 2.0.0-dev
    cordova-plugin-file: 6.0.1
    cordova-plugin-firebase-analytics: 4.5.0
    cordova-plugin-globalization: 1.11.0
    cordova-plugin-http: 1.2.0
    cordova-plugin-idfa: 2.0.0
    cordova-plugin-inappbrowser: 4.1.0
    cordova-plugin-inapppurchase-2: 1.3.0
    cordova-plugin-ionic-keyboard: 2.2.0
    cordova-plugin-nativestorage: 2.3.2
    cordova-plugin-network-information: 2.0.2
    cordova-plugin-purchase: 13.8.6
    cordova-plugin-screen-orientation: 3.0.2
    cordova-plugin-splashscreen: 4.1.0
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-wkwebview-file-xhr: 3.0.0
    cordova-support-android-plugin: 1.0.2
    cordova-support-google-services: 1.4.1
    es6-promise-plugin: 4.2.2
    ionic-plugin-keyboard: 2.2.1

Environment:

    OS: macOS 13.6 (22G120) (darwin 22.6.0) x64
    Node: v12.4.0
    npm: 6.9.0

android Environment:

    android:
ERROR: Command failed with exit code 1: android list target
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /Users/fellipefonseca/Library/Android/sdk/tools/bin/avdmanager list target

Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="br.com.salonsoft" version="4.0.7" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Salon Soft</name>
    <description>Aplicativo de salão de beleza.</description>
    <content src="index.html" />
    <author email="fellipefonseca9@gmail.com">Fellipe Fonseca</author>
    <allow-intent href="http://*/*" />
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="loadUrlTimeoutValue" value="700000" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="ShowSplashScreenSpinner" value="true" />
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
    <preference name="MediaTypesRequiringUserActionForPlayback" value="false" />
    <preference name="AllowInlineMediaPlayback" value="true" />
    <preference name="GradlePluginGoogleServicesEnabled" value="true" />
    <preference name="android-minSdkVersion" value="22" />
    <preference name="android-compileSdkVersion" value="33" />
    <preference name="android-targetSdkVersion" value="33" />
    <preference name="hostname" value="localhost" />
    <preference name="AndroidInsecureFileModeEnabled" value="true" />
    <config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
        <string>Light</string>
    </config-file>
    <platform name="android">
        <allow-intent href="market:*" />
        <preference name="AndroidPersistentFileLocation" value="Compatibility" />
        <resource-file src="resources/android/notification_icon/drawable-mdpi/notification_icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
        <resource-file src="resources/android/notification_icon/drawable-hdpi/notification_icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
        <resource-file src="resources/android/notification_icon/drawable-xhdpi/notification_icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
        <resource-file src="resources/android/notification_icon/drawable-xxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
        <resource-file src="resources/android/notification_icon/drawable-xxxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="windows">
        <preference name="windows-target-version" value="10.0" />
        <splash src="resources/windows/splash/Splash.png" target="SplashScreen" />
        <icon src="resources/windows/icon/Square44x44Logo.png" target="Square44x44Logo" />
        <icon src="resources/windows/icon/SmallTile.png" target="Square71x71Logo" />
        <icon src="resources/windows/icon/Square150x150Logo.png" target="Square150x150Logo" />
        <icon src="resources/windows/icon/Square310x310Logo.png" target="Square310x310Logo" />
        <icon src="resources/windows/icon/Wide310x150Logo.png" target="Wide310x150Logo" />
        <icon src="resources/windows/icon/StoreLogo.png" target="StoreLogo" />
    </platform>
    <platform name="ios">
        <allow-navigation href="https://*vimeo.com*" />
        <allow-navigation href="https://*youtube.com" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="deployment-target" value="12.0" />
        <preference name="pods_use_frameworks" value="true" />
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
            <string>Salon Soft would like to have access to the photo gallery so that the app can upload photos when you want to put them in the register of clients, professionals and products, as well as to update your profile picture in the app. Your photos will not be shared without your permission.</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSCalendarsUsageDescription">
            <string>Salon Soft would like to access your calendar.</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
            <string>Salon Soft would like to have access to the camera so that the app can upload photos when you want to put them in the register of clients, professionals and products, as well as to update your profile picture in the app. Your photos will not be shared without your permission.
            </string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSUserTrackingUsageDescription">
            <string>By allowing access to this data, you allow Salon Soft to: 1) Improve our products and services 2) Know how effective our advertisements are 3) Create advertisements for users similar to you.</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" target="NSContactsUsageDescription">
            <string>Salon Soft would like to access your contacts. Your data will not be shared without your permission.</string>
        </edit-config>
        <splash height="2688" src="resources/ios/splash/Default-2688h~iphone.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-2688h~iphone.png" width="2688" />
        <splash height="1792" src="resources/ios/splash/Default-1792h~iphone.png" width="828" />
        <splash height="828" src="resources/ios/splash/Default-Landscape-1792h~iphone.png" width="1792" />
        <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
        <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="216" src="resources/ios/icon/icon-108@2x.png" width="216" />
    </platform>
    <allow-navigation href="http://10.0.0.109:8101" />
    <allow-navigation href="http://10.0.0.109:8100" />
    <allow-navigation href="http://192.168.43.56:8100" />
    <allow-navigation href="http://192.168.42.205:8101" />
    <allow-navigation href="http://192.168.42.205:8100" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <allow-navigation href="http://10.0.0.111:8100" />
    <allow-navigation href="http://10.0.0.104:8100" />
    <allow-navigation href="http://10.0.0.106:8100" />
    <allow-navigation href="http://10.0.0.102:8100" />
    <allow-navigation href="http://192.168.43.192:8100" />
    <allow-navigation href="http://10.0.0.105:8100" />
    <allow-navigation href="http://10.0.0.107:8100" />
    <allow-navigation href="http://10.0.0.103:8100" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-datepicker" spec="^0.9.3" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-screen-orientation" spec="^3.0.1" />
    <plugin name="cordova-plugin-crop" spec="^0.4.0" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <allow-navigation href="http://192.168.25.90:8100" />
    <allow-navigation href="http://192.168.25.90:8101" />
    <allow-navigation href="http://10.0.0.101:8100" />
    <allow-navigation href="http://10.0.0.108:8100" />
    <plugin name="cordova-clipboard" spec="1.2.1" />
    <plugin name="cordova-plugin-apprate" spec="1.4.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.2.0" />
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "plugins": {
    "cordova-plugin-device": {},
    "cordova-plugin-splashscreen": {},
    "ionic-plugin-keyboard": {},
    "cordova-plugin-datepicker": {},
    "cordova-plugin-calendar": {},
    "cordova-plugin-network-information": {},
    "cordova-plugin-screen-orientation": {},
    "cordova-plugin-crop": {},
    "cordova-plugin-statusbar": {},
    "cordova-clipboard": {},
    "cordova-plugin-apprate": {},
    "cordova-plugin-ionic-keyboard": {},
    "cordova-plugin-cocoapod-support": {},
    "cordova-plugin-inappbrowser": {},
    "cordova-plugin-androidx-adapter": {},
    "cordova-plugin-wkwebview-file-xhr": {},
    "cordova-plugin-file-opener2": {
      "ANDROID_SUPPORT_V4_VERSION": "27.+"
    },
    "cordova-plugin-idfa": {
      "ANDROID_PLAY_ADID_VERSION": "16.+"
    },
    "cordova-plugin-facebook-connect": {
      "APP_ID": "221596308723733",
      "APP_NAME": "App Salon Soft",
      "FACEBOOK_URL_SCHEME_SUFFIX": " ",
      "FACEBOOK_AUTO_LOG_APP_EVENTS": "true",
      "FACEBOOK_HYBRID_APP_EVENTS": "false",
      "FACEBOOK_ADVERTISER_ID_COLLECTION": "true",
      "FACEBOOK_ANDROID_SDK_VERSION": "9.0.0",
      "FACEBOOK_IOS_SDK_VERSION": "9.0.1",
      "FACEBOOK_BROWSER_SDK_VERSION": "v9.0"
    },
    "cordova-plugin-inapppurchase-2": {},
    "cordova-plugin-contacts": {},
    "cordova-plugin-file": {},
    "cordova-plugin-file-transfer": {},
    "cordova-plugin-http": {},
    "cordova-plugin-advanced-http": {
      "ANDROIDBLACKLISTSECURESOCKETPROTOCOLS": "SSLv3,TLSv1"
    },
    "cordova-plugin-firebase-analytics": {
      "ANALYTICS_COLLECTION_ENABLED": "true",
      "AUTOMATIC_SCREEN_REPORTING_ENABLED": "true",
      "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.5.+",
      "IOS_FIREBASE_ANALYTICS_VERSION": "~> 6.32.2"
    },
    "cordova-plugin-camera": {
      "ANDROIDX_CORE_VERSION": "1.6.+"
    },
    "cordova-plugin-android-permissions": {},
    "cordova-plugin-fcm-with-dependecy-updated": {
      "ANDROID_DEFAULT_NOTIFICATION_ICON": "@mipmap/ic_launcher",
      "ANDROID_FCM_VERSION": "23.0.0",
      "ANDROID_FIREBASE_BOM_VERSION": "29.0.1",
      "ANDROID_GOOGLE_SERVICES_VERSION": "4.3.4",
      "ANDROID_GRADLE_TOOLS_VERSION": "4.1.0",
      "IOS_FIREBASE_MESSAGING_VERSION": "~> 7.0.0"
    },
    "cordova-plugin-purchase": {}
  },
  "platforms": [
    "android"
  ]
}

**Comment by j3k0** [comment]
Something makes you believe it's due to this plugin? I believe it would be better to report that issue to the cordova-android team.

**Comment by fellipefonseca** [comment]
Hi. 
Thanks for answering. 
This is because it started happening after updating to version 13 of the plugin

**Comment by j3k0** [comment]
Do you have some crash report on Google Play publisher console, or logs from a device. Is your app waiting for the in-app purchase plugin to be initialized to show something on screen? Do you have a device that fails so you can get some logs?

Plugin isn't really memory hungry, it's just a 340 KB javascript file and doesn't keep much data in memory.

This is a first report so I doubt that the plugin would be responsible of that by itself (plugin being used by apps with hundred thousands of users), it would be interesting to gather more info or there isn't much to analyze...

**Comment by fellipefonseca** [comment]
Hi @j3k0 

We don't have crash reports because the app just stays on an infinite white screen.
I saw another issue from someone reporting that it couldn't work on ionic 3 (#1471), so I believe it's really because of the typescript version, but we wouldn't be able to update to v4 because ionic 3 doesn't support it and there wouldn't be time to version migration, as the Google Play deadline is November 1st.
I tried to set a flag in tsconfig "skipLibCheck": true, which made it possible for me to compile and work on my cell phone, but these reports of a white screen occurred, including with another person on the team.

**Comment by fellipefonseca** [comment]
Solved [here](https://github.com/j3k0/cordova-plugin-purchase/issues/1455#issuecomment-1772217067)

**Comment by aeharding** [comment]
I think I may also be experiencing this white screen issue, because it started happening after I added in-app payments to my app. See https://github.com/aeharding/voyager/issues/946. I will try to investigate and get more logs.

**Comment by aeharding** [comment]
I can confirm that there is something weird going on with this lib, maybe some weird capacitor interaction that's causing Capacitor apps to sporadically not load (especially on iOS for my users). I resolved this by using revenue cat's plugin in https://github.com/aeharding/voyager/pull/951. I wish I could help debug this but there are zero errors to debug and its very sporadic. :( Sorry
