### ISSUE TITLE
store.initialize() never resolves

### ISSUE THREAD

**Issue by mikkimichaelis** [j3k0/cordova-plugin-purchase#1485]
I was experiencing expected behavior.  I then cleared my sandbox purchase history and then the store.initialize() function would never resolve.  I'm not sure if clearing purchase history is really related to the issue.   I examined the logs and found an error returned from App Store:

<img width="1209" alt="image" src="https://github.com/j3k0/cordova-plugin-purchase/assets/78762019/8e6c43bb-17f5-4372-827f-956090fa1fb3">

I upgraded from v13.8.5 to  v13.8.6 and the behavior continued.  I set 'needAppReceipt' to false and the app store issue no longer shows in the log:

<img width="1219" alt="image" src="https://github.com/j3k0/cordova-plugin-purchase/assets/78762019/983fb795-047f-48d5-a6a0-304323d9af7c">

However store.initialize() still does not resolve.  I would expecct store.initalize() to resolve or throw an error and neither ever happens.

### System Info
    "@capacitor/core": "^4.6.3",
    "@capacitor/ios": "4.6.3",
    "@ionic/angular": "^6.5.5",
    "@angular/core": "^15.1.1",

**Comment by mikkimichaelis** [comment]
removing

discountEligibilityDeterminer: this.iaptic.appStoreDiscountEligibilityDeterminer,

allows store.initialize() to resolve.

**Comment by j3k0** [comment]
Somehow it looks like clearing the purchase history makes AppStore's API fail to validate the devices' application receipt. (the `iTunes internal data access error` returned by iaptic is an error from Apple's API)

Plugin initialization will complete when all products have been loaded. However, on iOS, determining the availability of the introductory period can only be achieved by validating the receipt (to check for potential transactions for a given subscription group). So this step is part of loading product information (when `discountEligibilityDeterminer` is defined)

If the receipt is invalid, then initialization will not resolve. This is pretty much dev-environment specific, as normal users should never have an invalid receipt on their device (except on jailbroken devices, but you want those users not to be able to make in-app purchases anyway).

You might try uninstalling the app, to clear the cache

**Comment by mikkimichaelis** [comment]
@j3k0 Thank you so much for the very fast response!  Yes, clearing the cache resolved the issue and I'm able to move forward with developemnt.  Thank you so much for your support, and all the amazing work you've put into this plugin and iaptic.
