### ISSUE TITLE
After lib code to 3.9.0 previous Android functionality stopped working. 

### ISSUE THREAD

**Issue by pahenator** [j3k0/cordova-plugin-purchase#1494]
### Observed behavior

After updating lib to 3.9.0 previous Android functionality stopped working. 

### Expected behavior

It should not if there were no breaking changes. I plan to downgrade to prev versions (13.8.6) which worked fine.

**Comment by j3k0** [comment]
There's no change in code for android between those versions, can you be more specific about what doesn't work? Some logs maybe?

**Comment by pahenator** [comment]
> There's no change in code for android between those versions, can you be more specific about what doesn't work? Some logs maybe?

I closed and issue because the reason of error was other than I thought. BTW, great and convenient library, especially 13.9.x . No more pain with handling unfinished purchases.
