### ISSUE TITLE
Not able to bring google play

### ISSUE THREAD

**Issue by Bridgeprg** [j3k0/cordova-plugin-purchase#150]
Hi

I am working on this for week, how to create button when click on bring google in app store to purchase subscription. 

I try complete example and all it say your not subscribed 

Thank you

**Comment by Bridgeprg** [comment]
I figured the problem but it gives me this error 
error authentication is required. you need to sign in to your google account

**Comment by tmarciszewski** [comment]
There are several prerequisites for in-app purchase to work with google.
1. App must be signed with production key
2. App must be in release mode
3. App must be uploaded to google (alpha/beta) at least once and you need to use the same versionCode as was uploaded to google.
4. Products must be configured and published (this takes several hours)
5. You need to test from real device (no simulators)
6. You should configure billing test account and it should be different than your developer account

I hope it helps.

**Comment by Andrea2985** [comment]
how can I build my phonegap android app in release mode with eclipse?

**Comment by tmarciszewski** [comment]
Not sure about eclipse but here's quite good guide about building from command line

http://ionicframework.com/docs/guide/publishing.html

**Comment by Andrea2985** [comment]
@tmarciszewski can you help me with this https://github.com/j3k0/cordova-plugin-purchase/issues/144?
