### ISSUE TITLE
Validate receipt on app startup on V13

### ISSUE THREAD

**Issue by veronicatc** [j3k0/cordova-plugin-purchase#1509]
The app I am working on uses auto renewable subscriptions. 

On version 11, when I called store.refresh() at initialization, the iOS receipt got automatically validated.

I want to have the same behavior with version 13, but that is not happenning when I call store.initialize(). How can I have the app get the iOS receipt and validate it on startup, after initialize ?

Please help, thanks!

**Comment by flyingbarista** [comment]
I am also having this problem, can anyone help this has brought my app to a standstill. All worked perfectly before upgrading. Please help?

**Comment by flyingbarista** [comment]
I have made some progress with the following:

CdvPurchase.store.when()
            .approved(transaction => {transaction.verify(); console.log("receipt.verify");
                 document.getElementById('billing_info').innerHTML ="validating purchases" })
            .verified(receipt => {receipt.finish(); refreshUI(); console.log("receipt.finish")})

refreshing the UI in the .verified event seems to do the trick

**Comment by MarcelSchuermann** [comment]
I think this is related to #1363 - I have the same problem.

**Comment by j3k0** [comment]
You need to tell the plugin that you need the application receipt.

```ts
store.initialize([
  {
    platform: Platform.APPLE_APPSTORE,
    options: {
      needAppReceipt: true,
    }
  }
])
```

**Comment by veronicatc** [comment]
> You need to tell the plugin that you need the application receipt.
> 
> ```ts
> store.initialize([
>   {
>     platform: Platform.APPLE_APPSTORE,
>     options: {
>       needAppReceipt: true,
>     }
>   }
> ])
> ```

I am starting the plugin this way, but store.when().verified is not getting called. I added console.log in there which never shows, and when I call findInVerifiedReceipts, it doesn't find the product. 

I see it calls approved for the transaction for the app itself (transaction with id appstore.application) but for no other 
transaction. I just purchased a renewable subscription with a Sandbox user, so there is a transaction...

I also updated to the latest version of the plugin, but the issue persists.

I have been checking for hours and don't find the cause. Thanks for any help.

**Comment by kreso22** [comment]
Any luck with this?

**Comment by j3k0** [comment]
If you are running a custom validator, make sure its response complies with the one expected by the plugin (cf API documentation)

**Comment by kreso22** [comment]
> If you are running a custom validator, make sure its response complies with the one expected by the plugin (cf API documentation)

Thank you for your time!

I am not using a validator.

I created a new issue here (with code): https://github.com/j3k0/cordova-plugin-purchase/issues/1606
