### ISSUE TITLE
Documentation issue/question

### ISSUE THREAD

**Issue by viking2917** [j3k0/cordova-plugin-purchase#1510]
### Observed behavior

The Gitbook documentation Micro Example is mildly confusing to me, and perhaps misleading. The example says:

```
store.when()
    .productUpdated(refreshUI)
    .approved(finishPurchase);
``` 

and 

```
function finishPurchase(p) {
  localStorage.goldCoins = (localStorage.goldCoins | 0) + 10;
  p.finish();
  refreshUI();
}
```

It seems to imply that the approved handler returns a product - p - instead of a transaction. 

I am in the process of migrating from v11 to v13, and at least as far as I know, with version 13, it's a transaction that gets a finish(). So should this be written as:?

```
function finishPurchase(transaction) {
  localStorage.goldCoins = (localStorage.goldCoins | 0) + 10;
  transaction.finish();
  refreshUI();
}
```

I could not see a way to submit a pull request on the gitbook, but if there is a way, I am happy to submit a change.

**Comment by MarcelSchuermann** [comment]
Good point. I also think the micro example could be improved.

With the when.productUpdated() function I get an object of class "Receipt" (refering to your IAP-Product, therefore I guess the "p" comes from). This receipt consists of multiple transactions. 

so I would call it
`when.productUpdated(receipt)`

I have the problem, that in iOS for a subscription the productUpdated() function gets called nonstop. 
Any idea on this? @j3k0?

**Comment by j3k0** [comment]
@MarcelSchuermann You can check https://j3k0.github.io/cordova-subscription-example/ for a full working example. It's a different issue so I will close this one.
