### ISSUE TITLE
In-app purchase not working after publishing iOS app to App Store

### ISSUE THREAD

**Issue by igeeganage** [j3k0/cordova-plugin-purchase#1516]
I've created test accounts which are able to obtain the price of the in app purchase as well as actually purchasing it without an issue. However after publishing the iOS app to App Store, the version of the app in App store can't even retrieve price and the product details.  Android app is working fine.

**Comment by j3k0** [comment]
That looks like a setup issue you need to resolve with Apple. Did you submit your in-app purchase products with the app? Are all of banking, tax and agreements setup properly on AppStore Connect. Open an Apple Technical Support ticket to get support from Apple, as this is most likely not related to the plugin itself.
