### ISSUE TITLE
BSF Cordova Ecosystem Crowdfunding Plan

### ISSUE THREAD

**Issue by zzz131519** [j3k0/cordova-plugin-purchase#1519]
Hello everyone,

I'm Jason.z, the founder of [BSF](https://byteee.fund).

We've noticed that this project has remained very popular in the past.

However, unfortunately, it seems that this project has not been maintained for some time,

which is unfortunate for users who want to continue using and supporting the project.

Based on this, BSF has initiated the **Cordova Ecosystem Crowdfunding Plan** ,

with the main purpose of addressing the upgrading and maintenance of old Cordova projects,

as well as compatibility and adaptability for new platforms.

You can learn more about it by clicking on this [link](https://byteee.fund/post/bsf-cordova-crowdfunding-plan).

So, if you feel that this project needs continued upgrading and maintenance,

please let us know through [voting](https://github.com/byteee-fund/bsf-crowdfunding-plan/discussions/3).

We will decide whether to launch a crowdfunding plan for this project based on the voting results and the recruitment of maintainers,

as well as the subsequent development and maintenance plans.

If you are willing to be a long-term maintainer of the project, you can also contact us.

Of course, if you do not agree with the operating model of BSF Software Foundation,

or if you are a maintenance team for this project and believe that this ISSUE infringes and damages your rights,

you can also delete this ISSUE.

We sincerely apologize for any inconvenience this may cause.

BSF is our bold attempt and exploration of the sustainable development of software projects.

We hope to contribute to the development of software projects through the power of the community!

**Comment by zzz131519** [comment]
We are very sorry that we misjudged this project because after review, we found that the author of the project is still maintaining the project. Therefore, we have closed this issue. Of course, everyone can still vote or propose other cordova projects through the above link. , thank the author again for his contribution, let us continue to share power for the cordova ecosystem.

**Comment by j3k0** [comment]
Thanks for doing this, even though it doesn't sound like an issue with this plugin ;-)

**Comment by j3k0** [comment]
Thanks for doing this, even though it doesn't sound like an issue with this plugin ;-)
