### ISSUE TITLE
Using the plugin when offline

### ISSUE THREAD

**Issue by stegua** [j3k0/cordova-plugin-purchase#152]
When the device is offline, I get the following error:

 `ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory`

A comment in the file `cordova-plugin-purchase/src/js/refresh.js` says (line 57,58):

`// BEWARE. If user is offline, he won't be able to access the content
        // because validation will fail with a connection timeout.`

Does this **really** mean that I cannot check the purhcased products when the device is offline?
Should I manually managed locally which products have been purchased by the user?
Thanks.

**Comment by tmarciszewski** [comment]
If you are offline there is no possibility to contact AppStore/PlayStore. I think you should store info about purchases locally after purchase has been confirmed.

**Comment by stegua** [comment]
@tmarciszewski Thanks for your reply!
For the PlayStore, there is a support for Local Caching in-app calls (InApp Billing V3).
To manually manage information about products is discouraged:

`http://stackoverflow.com/questions/21277362/android-in-app-purchase-check-buyer-offline`

And local caching seems to work fine (see 2nd answer with 9 points):

`http://stackoverflow.com/questions/14231859/how-to-best-save-inapp-purchase-status-locally`

Btw., I have not investigated if the Apple Store support local caching.
