### ISSUE TITLE
Products loading for users in some countries, but not in others

### ISSUE THREAD

**Issue by leespokd** [j3k0/cordova-plugin-purchase#1534]
Hi,

Has anyone else experienced an issue, whereby subscription products will load in some countries, but not in others? We are having problems with users in EU countries - the subscription products are not showing - but in the UK, US Australia etc, they are appearing fine.

Just to ad, the countries we are experiencing issues with, are included in out list of available countries in Google Play, IOS.

**Comment by j3k0** [comment]
I think this is an issue you have to ask either Google or Apple whether the problem appears in one of those platforms.
