### ISSUE TITLE
[Android] No way to filter out deactivated products?

### ISSUE THREAD

**Issue by xiaoxiao99** [j3k0/cordova-plugin-purchase#1537]
### Observed behavior

According to the API documentation, it seems Product.canPurchase is the only avaliable flag to check if a product is active or not.
However, I found this flag is always true even if product is inactive.
To confirm that fact I updated the product title at the same timing as deactivaing product in play store.
It turns out the product title was updated in my app after a few hours, but the canPurchase flag still remains true.
So it is not an issue of local caching.

### Expected behavior

If canPurchase is not the right place to check product activeness, what else should I look into?

### System Info
cordova-android :12.0.1
cordova-plugin-purchase:  3.10.1

PS
This is my first try on this plugin, so I do not have chance to check the behavior on iOS yet.

**Comment by j3k0** [comment]
For reference, if Apple or Google returns the product AND the user has the ability to make purchase (can be disabled for kids for instance), the product will be returned. In sandbox mode, all products are purchasable if I'm correct.
