### ISSUE TITLE
[Android] Monetization.subscriptions APIs will replace InAppProducts API for subscription catalog management

### ISSUE THREAD

**Issue by HarelM** [j3k0/cordova-plugin-purchase#1542]
This is more of a question than an issue I guess, or a feature request...
I just got a mail from google about monitizaiton.subscription API that will be enforced in May 1st for existing apps.
Here's the relevant kb article:

https://android-developers.googleblog.com/2023/06/changes-to-google-play-developer-api-june-2023.html?utm_source=email&utm_medium=newsletter&utm_campaign=Play-february24

Is this plugin supports this new API?

**Comment by jellomaster** [comment]
I think the monitizaiton.subscription API is used for the receipt validation and not related to this plugin.  Your receipt validation code or service will need some updating if it wasn't already done.

**Comment by HarelM** [comment]
I use iaptic for receipt validation if I understand what you wrote.
Thanks for the quick response!

**Comment by jellomaster** [comment]
You should be ok.  Reach out to iaptic to cofirm.

**Comment by HarelM** [comment]
iaptic support said that I don't need to do any thing, great.
Closing this issue then.
