### ISSUE TITLE
Android - tryValidation never calls my validator - crashes after first purchase

### ISSUE THREAD

**Issue by JackNova** [j3k0/cordova-plugin-purchase#155]
I'm debugging my application in Android, something weird happens.

If it is the first time I buy a product, the app never calls my validation function and crashes.

If I already bought a product on the store, this is relevant initialisation code:

```
    store.register({
          id:    rgConfig.getStoreId('Statistics'),
          alias: 'Statistics',
          type:   store.NON_CONSUMABLE
      });


    store.when("Statistics").approved(function(product) {
          product.verify();
      });

    store.when("Statistics").verified(function(product) {
          product.finish();
          ...
      });

      store.refresh();
```

.approved() gets called before the .ready() event.

![upload_2015-03-30_at_2 43 54_pm](https://cloud.githubusercontent.com/assets/1033219/6896979/be88d134-d6f0-11e4-86c7-80214723b0a6.png)

this triggers execution of verify(), in this moment state is 'approved'

![upload_2015-03-30_at_2 45 59_pm](https://cloud.githubusercontent.com/assets/1033219/6896985/c860fe20-d6f0-11e4-87d6-4722ae085544.png)

when tryValidation is actually called the state is not 'approved' anymore but 'valid'
so my validator is never called.

![upload_2015-03-30_at_2 48 49_pm](https://cloud.githubusercontent.com/assets/1033219/6896987/cc56f28c-d6f0-11e4-8859-78e5dab1c969.png)

If I force the state to be 'approved' my validator gets called

![upload_2015-03-30_at_2 51 24_pm](https://cloud.githubusercontent.com/assets/1033219/6896991/d2988a48-d6f0-11e4-8916-22581f435f36.png)

**Comment by j3k0** [comment]
Your change may appear to solve the issue, but it will probably have side-effects. Validation is only allowed on a product in "approved" state.

The thing is, for some reasons product state is changed to "valid". The question is, how is state changed to valid? That's were the bug is.

**Comment by JackNova** [comment]
I agree 100%, could it be that when approved() gets called before the .ready() event the state is updated?
By the way, one side effect I'm aware of is that validation is invoked multiple times but to me this is not a problem (for how my app is designed)

**Comment by j3k0** [comment]
There isn't too many places were the product can be set to valid.

https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/android-adapter.js#L61

https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/android-adapter.js#L149-L156

https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/android-adapter.js#L215

https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/android-adapter.js#L230

Do you have time to dig it more?

**Comment by j3k0** [comment]
I'm wondering if it can be solved by just doing on [line 61](https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/android-adapter.js#L61):

```js
state: p.state == store.APPROVED ? p.state : store.VALID
```

Let me know.

**Comment by JackNova** [comment]
I just tested my temporary fix and it works as I was expecting: validation is not executed after the user buys something but it is executed after the user restores the order. I believe that the validation has to be executed both after buy and after restore.
Probably your fix could work

**Comment by JackNova** [comment]
Here is what happens with my fix, I'm watching places where state is updated with .valid

This is called

![image](https://cloud.githubusercontent.com/assets/1033219/6938689/b041b368-d865-11e4-95a1-64667d8cfacc.png)

Then .approved()
Then store.ready()

Then 

![image](https://cloud.githubusercontent.com/assets/1033219/6938728/f7bf713a-d865-11e4-83dc-3f8c0d8c5765.png)


Removing my fix

![image](https://cloud.githubusercontent.com/assets/1033219/6938812/a778b834-d866-11e4-8170-25b2fdc734f9.png)

Then .approved()
Then store.ready()

![image](https://cloud.githubusercontent.com/assets/1033219/6938826/c606d04c-d866-11e4-9dec-013abc1acb92.png)


now the state is valid and validation is skipped:

![image](https://cloud.githubusercontent.com/assets/1033219/6938836/e18e05ce-d866-11e4-8bad-6a2cdfaa8bdc.png)

**Comment by JackNova** [comment]
This is interesting

![image](https://cloud.githubusercontent.com/assets/1033219/6938914/ab5663f6-d867-11e4-98de-88c3c427e479.png)

**Comment by JackNova** [comment]
trying this fix:

store.android[method](function(data) {
                setProductData(product, data);
            }, function(err, code) {
                store.log.info("android -> " + method + " error " + code);
                if (code === store.ERR_PAYMENT_CANCELLED) {
                    product.transaction = null;
                    product.trigger("cancelled");
                } else {
                    store.error({
                        code: code || store.ERR_PURCHASE,
                        message: "Purchase failed: " + err
                    });
                }
                product.set("state", (code===7) ? store.APPROVED : store.VALID);
            }, product.id);

**Comment by j3k0** [comment]
Good catch, I'll integrate the patch.
