### ISSUE TITLE
This product is not available

### ISSUE THREAD

**Issue by yure-cs** [j3k0/cordova-plugin-purchase#1553]
### Observed behavior

Create CdvPurchase...
assinatura.page.ts:63 [CdvPurchase] INFO: initialize(["test"]) v13.10.1
assinatura.page.ts:63 [CdvPurchase.Adapters] INFO: Adding platforms: [{"platform":"test"}]
assinatura.page.ts:63 [CdvPurchase.Adapters] INFO: 
assinatura.page.ts:63 [CdvPurchase.Adapters] INFO: Test initializing...
store.js:337 [CdvPurchase.Adapters] INFO: Test initialized. 
store.js:337 [CdvPurchase.Adapters] INFO: Test products: [{"id":"basic-plan","type":"non renewing subscription","platform":"test"}]
contentScript.js:6 Loaded new content
store.js:337 [CdvPurchase.AdapterListener] DEBUG: receiptsReady: test (1/0)
store.js:337 [CdvPurchase.Adapters] INFO: Test products loaded: [{"isError":true,"code":6777023,"message":"This product is not available","platform":"test","productId":"basic-plan"}]
store.js:337 [CdvPurchase.Adapters] INFO: Test receipts loaded: []
store.js:337 [CdvPurchase.AdapterListener] DEBUG: setSupportedPlatforms: test (1 have their receipts ready)
store.js:337 [CdvPurchase.AdapterListener] DEBUG: triggering receiptsReady()
store.js:337 [CdvPurchase] DEBUG: Calling callback: type=ready() name=#102761c2b3a83823cdb01edd7a5b4a4f reason=initialize_promise_resolved
assinatura.page.ts:29 Products: []
store.js:337 [CdvPurchase] DEBUG: Calling callback: type=receiptsReady() name=receiptsMonitor_setup reason=adapterListener_setSupportedPlatforms
store.js:337 [CdvPurchase.ReceiptsMonitor] DEBUG: receiptsReady...
store.js:337 [CdvPurchase.ReceiptsMonitor] DEBUG: check(0/0)
store.js:337 [CdvPurchase.ReceiptsMonitor] INFO: receiptsVerified()

### Expected behavior

My code don't work

### System Info

Ionic:

   Ionic CLI                     : 7.2.0 (C:\laragon\bin\nodejs\node-v20\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 15.0.0
   @angular-devkit/schematics    : 15.2.9
   @angular/cli                  : 15.2.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.8.1
   @capacitor/android : 4.5.0
   @capacitor/core    : 4.5.0
   @capacitor/ios     : 4.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v20.11.0 (C:\laragon\bin\nodejs\node-v20\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

**Comment by tobiashill** [comment]
I just ran into the same problem. 🫤 

Can't see that test-products and the test-store is described anywhere in docs/wikis etc ...    ... but by looking at the code it seems 🤔 that you only have a few already set possible product ids available in the test store and you cannot invent id:s of your own.

Especially this file seem to set up the static space that defines what products you can define:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ts/platforms/test/test-products.ts

So, if you instead of using 'basic-plan' try 'test-subscription' I think it will work.
