### ISSUE TITLE
[GOOGLE PLAY] Billing API update my code doesn't work.

### ISSUE THREAD

**Issue by ArbitaryMann** [j3k0/cordova-plugin-purchase#1555]
Here is my code i tryed couple times but never got it working.

function initStore() {
    CdvPurchase.store.verbosity = CdvPurchase.LogLevel.DEBUG;
    try{
        setTimeout(() => {
            sendSubscriptionSuccessNotification();
        }, 2500);

    }catch{

    }
    CdvPurchase.store.register([
        {
            id: 'dayemmonth',
            type: CdvPurchase.ProductType.NON_CONSUMABLE,
            platform: CdvPurchase.Platform.GOOGLE_PLAY,
        }
    ]);

    CdvPurchase.store.initialize([CdvPurchase.Platform.GOOGLE_PLAY, CdvPurchase.ProductType.NON_CONSUMABLE]);
    CdvPurchase.store.update();
}

function purchaseAccess() {
    showLoader(6000);
    const productId = 'dayemmonth'; 
    const product = CdvPurchase.store.get(productId, CdvPurchase.Platform.GOOGLE_PLAY);
    if (product) {
        product.order();
    } else {
        alert("Product not found");
    }
}

**Comment by j3k0** [comment]
Have you figured it out? Please reopen if not.

**Comment by ArbitaryMann** [comment]
Sir I cannot install the plugin
