### ISSUE TITLE
Why does it work on Android but not on iOS? And what's the deal with being asked to purchase again when it's supposed to be a consumable purchase? Android is fine

### ISSUE THREAD

**Issue by ulsoftnaver** [j3k0/cordova-plugin-purchase#1560]
Why does it work on Android but not on iOS? And what's the deal with being asked to purchase again when it's supposed to be a consumable purchase? Android is fine

import { Injectable } from '@angular/core';
import { Platform } from '@ionic/angular';
import 'cordova-plugin-purchase/www/store.d';

private approved1: any = (p: any) => 
{
 var pay_id = p.nativePurchase['orderId'];
 var id = p.nativePurchase['productId'];
 var purchaseToken = p.nativePurchase['purchaseToken'];

 const myProduct = this.ps.store.get(p.nativePurchase['productId']);
 var price = myProduct.offers[0].pricingPhases[0].price;
 var currency = myProduct.offers[0].pricingPhases[0].currency;
 var platform = p.platform;

 p.finish();
 this.ps.store.off(this.approved1);
...
}

**Comment by j3k0** [comment]
Can you share more code, context, logs. Can't answer with the limited information you're providing. Also, it works on iOS, it's been well tested.

**Comment by TheNotorius0** [comment]
I use Cordova so I don't know if it's different with Capacitor / Ionic, but you should `console.log` your `p` parameter. Most likely, the code to get the id (`p.nativePurchase['productId']`) works for Android, but it's not correct for iOS. So read the console.log, and find where you can actually find the id, because it might be different from Android.

For example, in Cordova, this is my code:

`const productId = currentPlatform === Platforms.iOS ? verifiedReceipt.collection[0].id : verifiedReceipt.id;`

**Comment by flyingbarista** [comment]
I recently ran into a similar problem.

After upgrading to 13.11.1 I decided to modify my code and access receipt.id to do some filtering of app functionality based on the ID of the current owned subscription.

On Android the ID is as expected, but on iOS the ID returns the app identifier. 

In CdvPurchase.store.when().verified I have the following code
(receipt => {receipt.finish();
                   console.log("ID "+ receipt.id);
                   console.log("receipt.finish "+JSON.stringify(receipt));
                   console.log("receipt.finish "+receipt.collection[0].id);
                   })

On Android
  receipt.id gives the expected result of the ID from store.register

On iOS
  receipt.id fails
  After analysing the JSON what I wanted (the same as on Android) was found here ...
  receipt.collection[0].id

My question is should I just code receipt.collection[0].id in or can we have an update so receipt.id gives the same result on both platforms?

PS hope this helps

**Comment by j3k0** [comment]
On iOS there's a single receipt that contains all transactions for all products, so the "id" of the receipt will always be thatof the app.

On Android, there is 1 receipt per product id, the the "id" of the receipt will be that of the product.

You should indeed look into "receipt.collection" (or I think even better, store.verifiedPurchases -- cf https://www.iaptic.com/documentation/cordova-plugin-api/classes/CdvPurchase.Store.html#verifiedPurchases)
