### ISSUE TITLE
[Android] Cannot Register Existing Products in V13.10.1

### ISSUE THREAD

**Issue by rtkoni** [j3k0/cordova-plugin-purchase#1563]
### Observed behavior

i work now on a app using V13.10.1 of cordova-plugin-purchase and facing issue.
here is my code to register the subscriptions:
store.register({
         id,
         platform: CdvPurchase.Platform.GOOGLE_PLAY,
         type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
         group: 'default'
});
In the log i have this:
"[CdvPurchase.Adapters] INFO: GooglePlay loaded: [{"isError":true,"code":6777012,"message":"Product with id one-month-abo not found."},{"isError":true,"code":6777012,"message":"Product with id three-month-abo not found."},{"isError":true,"code":6777012,"message":"Product with id six-month-abo not found."}]"

i contacted google and they found no error on our google play console and sent me to the forum.
I will be happy for any help
Thank you

### Expected behavior
in-app products work fine and it should also be like this with subscription
### System Info

ext {
    minSdkVersion = 24
    compileSdkVersion = 33
    targetSdkVersion = 33
    androidxActivityVersion = '1.7.0'
    androidxAppCompatVersion = '1.6.1'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.10.0'
    androidxFragmentVersion = '1.5.6'
    coreSplashScreenVersion = '1.0.0'
    androidxWebkitVersion = '1.6.1'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.5'
    androidxEspressoCoreVersion = '3.5.1'
    cordovaAndroidVersion = '10.1.1'
}

**Comment by john290n** [comment]
Hello @rtkoni, how did you manage to resolve this issue? I'm experiencing the same problem!

**Comment by rtkoni** [comment]
Hi @john290n, that was an error on my google play console. I had one subscription an 3 base plans in the  subscription.these were : one-month-abo, three-month-abo, six-month-abo. And that was the raisin why i had error.
To solve that I created three subscriptions and every subscription has one base plan. Now I have following subscriptions on my google console:
Abo_for_one_month with base plan one-month-Abo
Abo_for_tree_month base plan three-month-Abo
Abo_for_six_month base plan six-month-Abo

And it works. I hope that help you
