### ISSUE TITLE
Method startServiceConnection in class PurchasePlugin cannot be applied to given types

### ISSUE THREAD

**Issue by marioshtika** [j3k0/cordova-plugin-purchase#1564]
### Observed behavior
When I run the below command 
```
ionic cordova platform add android
```

The build is failing with the below message
```
> Task :app:compileDebugJavaWithJavac FAILED
/platforms/android/app/src/main/java/cc/fovea/PurchasePlugin.java:307: error: method startServiceConnection in class PurchasePlugin cannot be applied to given types;
    startServiceConnection(() -> {
    ^
  required: Runnable,Runnable
  found: ()->{ if ([...]; } }
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
FAILURE: Build failed with an exception.
```

### More info
Even though I am using `"cordova-plugin-purchase": "^13.10.1"` it is installing the latest tag which is "13.10.3" and not the latest release which is "13.10.1".
If I install it as exact version `"cordova-plugin-purchase": "13.10.1"` it is working fine.

**Comment by j3k0** [comment]
Looks like a new version of java do not like the implicit null value for last parameter. Fixed with last commit, preparing a new patch release.

**Comment by j3k0** [comment]
Please try version v13.10.4

**Comment by marioshtika** [comment]
Hello @j3k0 v13.10.4 is working perfectly 👍
