### ISSUE TITLE
Plans for Upgrading to Google Play Billing Library v6 or v7?

### ISSUE THREAD

**Issue by giloliveira-nmi** [j3k0/cordova-plugin-purchase#1565]
First, thank you for this great plugin! I’ve been using it for several years now, and it has always performed reliably.

Currently, the plugin uses Google Play Billing Library v5, which will be deprecated by 1st November 2024. Given this, I am planning to upgrade it in the coming months. Additionally, Google released v7 of their Billing Library last week: https://developer.android.com/google/play/billing/release-notes.

I am wondering if there are plans to update this plugin to work with either v6 or v7. I haven't seen any information or discussions about these versions, so I thought it best to ask directly.

Thank you for your attention.

**Comment by hooliapps** [comment]
Hello

I have the same problem.

**Comment by ulsoftnaver** [comment]
same problem..  help me please..

**Comment by igortyhon** [comment]
Hi. I second the request!

**Comment by GerardDummett** [comment]
Hi, yes please and thank you.

**Comment by hooliapps** [comment]
A new version of the plugin was delivered with v7 ! Thanks.

**Comment by marioshtika** [comment]
Yes it's, here 😎 

Version 13.11.0
https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v13.11.0

Thank you @j3k0

**Comment by j3k0** [comment]
Welcome

**Comment by giloliveira-nmi** [comment]
That was quick! Thank you @j3k0, appreciate the work!

**Comment by ulsoftnaver** [comment]
thank you very much!!
