### ISSUE TITLE
When running locally window.cordova is undefined. Plugin cannot lookup platformId.

### ISSUE THREAD

**Issue by tobiashill** [j3k0/cordova-plugin-purchase#1566]
### Observed behavior

In a capacitor context:
When running locally in a browser the test to see whether the iOS adapter is active fails. It tries to lookup `platformId` on `window.cordova`. That is undefined. 

You get:

```
TypeError: Cannot read properties of undefined (reading 'platformId')
    at get isSupported (cordova-plugin-purchase.js?v=f10f3220:2303:35)
    at Adapters.<anonymous> (cordova-plugin-purchase.js?v=f10f3220:717:30)
    at Generator.next (<anonymous>)
    at cordova-plugin-purchase.js?v=f10f3220:32:71
    at new Promise (<anonymous>)
    at __awaiter (cordova-plugin-purchase.js?v=f10f3220:14:14)
    at cordova-plugin-purchase.js?v=f10f3220:710:85
    at Array.map (<anonymous>)
    at Adapters.<anonymous> (cordova-plugin-purchase.js?v=f10f3220:710:61)
``` 

When looking in the plugin code we see this: 
```
/** Returns true on iOS, the only platform supported by this adapter */
get isSupported() {
   return window.cordova.platformId === "ios";
}
```

### Expected behavior

This plugin is totally dependent on cordova. Capacitor is mentioned in the docs for this plugin and many of us have moved on. We are not still in cordova-land. 

The workaround is to do this somewhere before the plugin initializes. 

```
// @ts-ignore
window.cordova = Capacitor.getPlatform();

```
But then again:
I can't see that this is mentioned anywhere. I think it should be. 

Or plugin should be less dependent on Cordova. 
Or smarter and pick up this instead if Capacitor.getPlatform() is defined and window.cordova is not.

**Comment by j3k0** [comment]
Hopefully c9dd12f9d1a7ccbfee3426181861666e6472cbaa should fix it. I'll prepare a release with that change as soon as I can.
