### ISSUE TITLE
Wrong currency ($/USD instead of €/EUR) displayed on iOS (not Android)

### ISSUE THREAD

**Issue by sbat** [j3k0/cordova-plugin-purchase#1567]
### Observed behavior

Hello everyone,

I have been facing an issue for the past few days that I haven't been able to resolve: I am seeing the wrong currency ($/USD instead of €/EUR) displayed on iOS.

```product.offers[0].pricingPhases[0].price``` returns "$0.99".

```json
{"className":"Product","title":"xxx","description":"xxx","platform":"ios-appstore","type":"non consumable","id":"xxx.p1","offers":[{"className":"Offer","id":"$","pricingPhases":[{"price":"$0.99","priceMicros":990000,"currency":"USD","paymentMode":"UpFront","recurrenceMode":"NON_RECURRING"}],"productId":"xxx.p1","productType":"non consumable","platform":"ios-appstore","offerType":"Default"}],"raw":{"id":"xxx.p1","description":"xxx","introPrice":null,"introPricePaymentMode":null,"billingPeriodUnit":"Day","countryCode":"US","introPricePeriodUnit":null,"discounts":[],"title":"xxx","price":"$0.99","billingPeriod":0,"group":null,"priceMicros":990000,"currency":"USD","introPricePeriod":null,"introPriceMicros":null},"countryCode":"US"}

```

Here are some details:

* I am using the latest version ```13.11.1```. However, the problem also existed with ```13.10.4```.
* I integrated the ```cordova-plugin-purchase``` plugin into my app two years ago, and it still works correctly in the current live version. It also works correctly in my two-year-old app in the App Store. Therefore, I assume it's not due to the iPhone settings or the App Store settings. I have checked the settings on both the iPhone and the App Store. In the emulator I have the same problem.
* It works correctly on Android, displaying "€".
* Using "navigator.globalization.getLocaleName" returns "de-DE" as the value.
* The App Store region is set to Germany in the iPhone settings.

My question: Why is USD being pulled from the App Store instead of EUR? Is it possible to specify which currency and price are displayed? @j3k0 Do you have the possibility to influence this?

### Expected behavior

I would expect to see the currency € displayed in, for example, Germany, not $.

### System Info

Cordova Packages:

    cli: 12.0.0
        common: 5.0.0
        create: 5.0.0
        lib: 12.0.1
            common: 5.0.0
            fetch: 4.0.0
            serve: 4.0.1

Project Installed Platforms:

    android: 12.0.1
    ios: 7.1.0

Project Installed Plugins:

    cordova-plugin-globalization: 1.11.0
    cordova-plugin-purchase: 13.11.1
    ...

Environment:

    OS: macOS Sonoma 14.5 (23F79) (darwin 23.5.0) arm64
    Node: v18.18.2
    npm: 9.8.1

ios Environment:

    xcodebuild: Xcode 15.4 / Build version 15F31d

**Comment by j3k0** [comment]
Hi @sbat - you can create Test Users from AppStore connect and assign them to the country you want to test against.

All is explained in that documentation from Apple: https://developer.apple.com/documentation/storekit/in-app_purchase/testing_in-app_purchases_with_sandbox

**Comment by WoodyWoodsta** [comment]
Came across this today. I have a subscription product available in the UK and US, and prices for each region. If I set up a sandbox user in the UK region and use that sandbox user in the simulator, I still get USD prices from the plugin.

**Comment by j3k0** [comment]
The plugin only reports the data provided by Apple StoreKit, so this issue isn't related to the plugin but with your Apple sandbox testing environment.

**Comment by WoodyWoodsta** [comment]
Thanks @j3k0, I'll see what happens once our app reaches a Production setup.

**Comment by WoodyWoodsta** [comment]
I'm getting the right currency now in the Sandbox environment. I think my issue was that I was not signed in correctly to iCloud on the simulator device. Even if you sign in via "Settings", it seems as though you need to initiate a purchase which triggers another sign in process. After that, products came back with the right region.

It's possible I did a few things in between that which may have helped - this is the best reasoning I can come up with.
