### ISSUE TITLE
Update com.google.android.play.billingclient.version 

### ISSUE THREAD

**Issue by Afrykakod123** [j3k0/cordova-plugin-purchase#1569]
### Observed behavior

Google Play Billing Library version deprecation

https://developer.android.com/google/play/billing/deprecation-faq

### Expected behavior

Update com.google.android.play.billingclient.version

**Comment by dferenc-netwizzy** [comment]
Not sure what the issue means, but GPBL v7 is used in [cordova-plugin-purchase@13.11.1](https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v13.11.1), the latest available version of the plugin - You just have to update.

**Comment by Afrykakod123** [comment]
Indeed, I had an older version, I don't know how I missed that. Thanks, I'll update it and let you know.

**Comment by Afrykakod123** [comment]
I had an outdated version, my mistake, thanks for the info.

**Comment by john290n** [comment]
Hello @Afrykakod123, is the cordova-plugin-purchase v13.11.1 working fine on Android for you?
