### ISSUE TITLE
IOS:transaction is null, for paid product type

### ISSUE THREAD

**Issue by Moussawi7** [j3k0/cordova-plugin-purchase#157]
Hi,
I am facing a strange issue with product of type **_store.PAID_SUBSCRIPTION**_.
1. I register the products
2. I refresh the store.
3. I order a specific product.
4. approved event fired so i finish the transaction immediately.
5. transaction finished successfully  (I can see it on Xcode console).

the problem is that approved event is fired each time i open application and refresh the store, but here with transaction value: **_null**_.
you can check screenshot below.
Thank you.

![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/5157060/6917857/44b60540-d7b1-11e4-9b7c-51ba5f0e89f7.png)

**Comment by achuinard** [comment]
Did you ever figure this out? I'm seeing a null transaction as well in the sandbox for a paid subscription.
