### ISSUE TITLE
[Android] `orderId` undefined on cancelled Receipt

### ISSUE THREAD

**Issue by dferenc-netwizzy** [j3k0/cordova-plugin-purchase#1570]
Using `cordova-plugin-purchase@13.11.1` i get an `orderId = undefined` for google test purchases using "Payment methods > Slow test card, declines after a few minutes".

I'm updating an app that was released at the end of the last year using `cordova-plugin-purchase@13.6.0` and it was working as expected - i use this `orderId` in a dialog to let a user identify what purchase ("order") i'm showing information about (in a google identifiable manner using google's id format like GPA.XXXX-XXXX-XXXX-XXXXX, for cross-reference).

**Comment by dferenc-netwizzy** [comment]
> ### Handle pending transactions
> The Play Billing Library no longer creates an order ID for pending purchases. For these purchases, the order ID is populated after the purchase is moved to the [PURCHASED](https://developer.android.com/reference/com/android/billingclient/api/Purchase.PurchaseState#PURCHASED) state. Make sure that your integration expects an order ID only after a transaction has fully completed. You can still use the purchase token for your records.

[source](https://developer.android.com/google/play/billing/migrate-gpblv7#handle-pending)

As it seems, in v7 of the GPBL google only fills that field for non-canceled purchases.
Closing issue.

**Comment by dferenc-netwizzy** [comment]
> ### Handle pending transactions
> The Play Billing Library no longer creates an order ID for pending purchases. For these purchases, the order ID is populated after the purchase is moved to the [PURCHASED](https://developer.android.com/reference/com/android/billingclient/api/Purchase.PurchaseState#PURCHASED) state. Make sure that your integration expects an order ID only after a transaction has fully completed. You can still use the purchase token for your records.

[source](https://developer.android.com/google/play/billing/migrate-gpblv7#handle-pending)

As it seems, in v7 of the GPBL google only fills that field for non-canceled purchases.
Closing issue.

**Comment by dferenc-netwizzy** [comment]
> ### Handle pending transactions
> The Play Billing Library no longer creates an order ID for pending purchases. For these purchases, the order ID is populated after the purchase is moved to the [PURCHASED](https://developer.android.com/reference/com/android/billingclient/api/Purchase.PurchaseState#PURCHASED) state. Make sure that your integration expects an order ID only after a transaction has fully completed. You can still use the purchase token for your records.

[source](https://developer.android.com/google/play/billing/migrate-gpblv7#handle-pending)

As it seems, in v7 of the GPBL google only fills that field for non-canceled purchases.
Closing issue.

**Comment by john290n** [comment]
Hello @dferenc-netwizzy, Im facing an issue with `Line 3209 - Msg: [CdvPurchase.Adapters] INFO: GooglePlay products loaded: [{"isError":true,"code":6777012,"message":"Product with id 1_month_premium_test not found.","platform":"android-playstore","productId":"1_month_premium_test"}]` could you please help me?
