### ISSUE TITLE
How to run validator every time app is opened

### ISSUE THREAD

**Issue by alanmilinovic** [j3k0/cordova-plugin-purchase#1576]
In version 11 validator method was always executed even when purchase was not done. Like this:
`store.validator = function (product, callback) {};`

Now that I switched to version 13. This validator method is only called when purchase is done. New syntax looks like this:
` CdvPurchase.store.validator = function (product, callback) {};`

As I am having subscription type of purchase, I need to use my server-side validator every time app. How to manually trigger it?

**Comment by j3k0** [comment]
The validator should be called whenever the app is opened (on iOS, in all cases, on Android only if there are active subscriptions or purchases for the user)

Make sure you initialize the plugin, and have the event handlers in place (approved -> verify -> finish)
