### ISSUE TITLE
v13 iOS Restore purchases with local decoding

### ISSUE THREAD

**Issue by hooliapps** [j3k0/cordova-plugin-purchase#1578]
Hello

There is any way to do this please ?

One auto-renewable product

Local validation only (or at least decoding) to just get the Purchase date (expiry date not needed)

+ Restore purchase button.

It worked with v11 but with v13 i have purchaseDate empty on iOS, but filled on Android.

Best regards

**Comment by j3k0** [comment]
If you want to avoid replaying all transactions, and you have only auto-renewables and a receipt validation service in place, a call to "store.update()" should be enough when doing "restorePurchases". You can probably skip calling `store.restorePurchases()` altogether.

I do not know about local validation.
