### ISSUE TITLE
cordova-plugin-purchase store.when().approved event trigger multiple time.

### ISSUE THREAD

**Issue by AyushKanani07** [j3k0/cordova-plugin-purchase#1579]
I've integrated version 13.11.1 of the cordova-plugin-purchase into my Ionic application. Additionally, I've set up a consumable product in the Apple App Store and created a dedicated sandbox user for testing purposes.
While I can successfully retrieve product details from the store and display them in the application template, I'm encountering an issue during the purchase process. when the purchase was successful store.when() was trigger but each time it will trigger one time more to the previous one. On first purchase it will trigger two time, on second purchase it will trigger three time even i was ensure that the function setupListeners() was call one time in entire app lifecycle then also it will trigger multiple time.

      setupListeners() {
        store.when()
          .approved((p: any) => {
            if (p.products[0].id === this.PRODUCT_GEMS_KEY)) {
              this.gem.update(value => value + 100);
            } else if (p.products.id === this.Comsumable_Plan) {
              console.log('In Consumable paln')
            }
            p.verify();
          })
          .verified((p: any) => {
            p.finish()
          });
      }

![Screenshot 2024-06-29 at 12 51 02 PM](https://github.com/j3k0/cordova-plugin-purchase/assets/154213026/88152ec2-be80-48e9-8279-41492c9759db)

I really appreciate any help you can provide.

**Comment by sksk008** [comment]
found any solution ?

**Comment by selcukbeyhan** [comment]
the state transition documentation is pretty weak. Found any solution?

**Comment by j3k0** [comment]
This looks a lot like you have called "setupListeners" multiple times.

Notice that this should be done only once, at startup: some transaction can be created outside of the app or remain pending, so the app should always be ready to process transactions.

**Comment by michellavezzo** [comment]
> This looks a lot like you have called "setupListeners" multiple times.
> 
> Notice that this should be done only once, at startup: some transaction can be created outside of the app or remain pending, so the app should always be ready to process transactions.

Basically if I do this every time the user click to buy, this issue will happen?

```js

const handleTransaction = (product, finishCallback) => {
	store
		.when()
		.approved((transaction) => {
			if (transaction.products[0].id === product) {
				transaction.verify()
			}
		})
		.verified(transaction => processTransaction(transaction, product, finishCallback))
		.finished(transaction => finishCallback(transaction))
}
```

**Comment by michellavezzo** [comment]
GPT:

## Multiple Event Listeners:

- Cause: If the same event listener (such as .approved() or .verified()) is being registered multiple times, it could result in processPurchases being called more than once.

- Solution: Ensure that event listeners are registered only once. This can be done by checking if the event listener is already set before adding a new one. Consider setting up event listeners outside of any function that might be called multiple times.

```js
let isInitialized = false;

const handleTransaction = (product, finishCallback) => {
    if (!isInitialized) {
        isInitialized = true;

        store.when()
            .approved((transaction) => {
                if (transaction.products[0].id === product) {
                    transaction.verify();
                }
            })
            .verified(transaction => processTransaction(transaction, product, finishCallback))
            .finished(transaction => finishCallback(transaction));
    }
};
```

**Comment by j3k0** [comment]
Yes, if you register handlers multiple times they will be called multiple times.

Notice that this should be done once and only once, at startup. That is because your app also have to handle pending purchases (those for which the flow was interrupted, for example by lost network or app crash or whatever), purchases initiated outside the app (family sharing, promo codes, ...). Purchases can also happen outside the app while the app is launched (backgrounded, minimized, ...) so your app need to always be ready to handle transaction events.

**Comment by michellavezzo** [comment]
> Yes, if you register handlers multiple times they will be called multiple times.
> 
> Notice that this should be done once and only once, at startup. That is because your app also have to handle pending purchases (those for which the flow was interrupted, for example by lost network or app crash or whatever), purchases initiated outside the app (family sharing, promo codes, ...). Purchases can also happen outside the app while the app is launched (backgrounded, minimized, ...) so your app need to always be ready to handle transaction events.

Thanks a lot! 

Seems fixed my issue.
Apple is ok, today I'll test it on google.

----

I'm using nuxt2 + Capacitor.

At our plugin startup function we do:
1st: `store.register([{...`
2nd: `store.when()...` -> mentioned above
3rd: `store.initialize([Platform.APPLE_APPSTORE, Platform.GOOGLE_PLAY])`

As we handle our purchases from our backend, this example below is a bit different from what we have today. but can help someone trying to find a solution
https://gist.github.com/j3k0/8b7e72b6af43572651328c613ac86d59

I hope this topic help someone else! 🇧🇷
