### ISSUE TITLE
App must use Google Play Billing Library version 6.0.1 or later

### ISSUE THREAD

**Issue by luk156** [j3k0/cordova-plugin-purchase#1581]

**Comment by Mdemol** [comment]
I also got this message from Google. Apps after the end of August should be using Google Play Billing Library version 6.0.1 or later. 

Additionally, minimum of SDK 34 is also required.

**Comment by mikecann** [comment]
@luk156 why was this closed? What does "not planned" mean? We are getting this issue too..
