### ISSUE TITLE
Not free trial period in IOS

### ISSUE THREAD

**Issue by bmg1** [j3k0/cordova-plugin-purchase#1582]
### Observed behavior
no free period(3day) in ios

### _Include logs with `CdvPurchase.store.verbosity = CdvPurchase.LogLevel.DEBUG`_
Is in file: [herohabit_bugs_22.06.2024.log](https://github.com/user-attachments/files/16165183/herohabit_bugs_22.06.2024.log)

### Expected behavior
When paying, it is expected that it will offer or show in the logs the possibility of a free period

### System Info
Is in file: [cordovaInfo.txt](https://github.com/user-attachments/files/16165181/cordovaInfo.txt)

**Comment by j3k0** [comment]
The logs stop at "Creating CdvPurchase". Anyway it sounds like a Apple AppStore setup issue (or maybe that AppStore user already used the free trial, it can't be purchased twice).
