### ISSUE TITLE
billing:7.0.0 ->  I do not see a warning message 

### ISSUE THREAD

**Issue by ulsoftnaver** [j3k0/cordova-plugin-purchase#1583]
I do not see a warning message 

My app has been updated to use the Google Play Billing Library version 7.0.0. However, the warning message in the Google Play Console has not disappeared. I have heard that updating to version 7.0.1 might resolve this issue. Could you please check and confirm if this is the cause? Despite updating all apps, the warning message persists.

![image](https://github.com/user-attachments/assets/4c474bb4-cf57-4286-a4e8-f4dabde40b94)

**Comment by d0minYk** [comment]
Have you found an answer to this? Google play is still complaining for all apps even though all tracks have been updated with the latest release.

**Comment by j3k0** [comment]
Note sure why. I know that warning can still occur if there's a alpha, beta or open testing build accessible that uses the old API, or that some old build are still accessible to some users (depending on minimum android SDK versions)... As long as you upgraded the plugin, you should be fine.

A version 7.0.1 doesn't exist as of today. https://developer.android.com/google/play/billing/release-notes

**Comment by j3k0** [comment]
(i believe it's a Google Play Developer Console issue mostly, so I'll close it)
