### ISSUE TITLE
Verify receipt on iOS, why is transaction id == appstore.application

### ISSUE THREAD

**Issue by rgustavsson** [j3k0/cordova-plugin-purchase#1585]
When a successful purchase has been made the plugin sends a valid/unique transaction ID to the backend service. 
After, if I just restart the app and allow the verify() process to validate the receipt, the transaction ID sent to the server is now "appstore.application".

Do you know why? I would expect to get the ID from the previous reciept/purchase?

Using v13.11.1 of the plugin

**Comment by rgustavsson** [comment]
Sorry, I must have missed that there is more details to be accessed from the verify() payload. I can use the appStoreReceipt data.

**Comment by selcukbeyhan** [comment]
you closed the issue but I wanted to share my two cents.
I recall this is related to the "purchase" (installation) of the app.
That you install the app (even free app) is registered as purchase at the iOS side.
