### ISSUE TITLE
API change means store.when().owned is no longer available: how to replace?

### ISSUE THREAD

**Issue by simonrshepherd** [j3k0/cordova-plugin-purchase#1589]
Previously, in the old API, I used an event store.when().owned to fire when a transaction was finally complete and its receipt was present.

Then, I would send that receipt to the server.

Now, however, the owned event is gone. The API migration doc doesn't seem to cover how to migrate use of this owned event.

How can I get the receipt data of a transaction, after the purchase is complete?

Specifically what I send to my server is the purchaseToken from the transaction, and the packageName and productId, both from the receipt.

**Comment by simonrshepherd** [comment]
Do I want to use the verified event on the receipt for this?

so store.verified to listen to the event, and then in the event handler:
`onReceiptVerified: function (receipt) {
        // let's get purchase token, product id for the request
        receipt.purchaseToken;
        receipt.transactions[0].products[0].id;

        // TODO: how to get packageName??? 

        receipt.finish();
    },`

But how would I get the packageName in this context?

**Comment by henkkelder** [comment]
I have strugled with the same change. I now detect the owned state by querying it explicitly in the verified event. 
See example:

`.verified((receipt: CdvPurchase.VerifiedReceipt) => {
        console.log('VerifyReceipt received:' + receipt.id);
        receipt.collection.forEach(purchase => {
          if (this.store.owned(purchase)) {
            const myProd = this.GetProduct(purchase.id);
            if (myProd) {
              console.log('verified:' + purchase.id);
              myProd.owned = true;
              this.makeSubtitle(myProd);
            }
          }
        });
        receipt.finish();
      })`

**Comment by j3k0** [comment]
The proper way would be to implement your own validation function: https://www.iaptic.com/documentation/cordova-plugin-api/classes/CdvPurchase.Store.html#validator

It is called when a receipt is updated. In a success response, the "collection" of verified purchase will let the plugin know which purchase the use owns. (cf `SuccessPayload` in the doc above).

Alternatively, you could use the `receiptUpdated` event (https://www.iaptic.com/documentation/cordova-plugin-api/interfaces/CdvPurchase.When.html#receiptUpdated.receiptUpdated-1).

In all cases, the point main point of sending that receipt (purchaseToken) is to be able to verify server side the status of the purchase, which is better than trusting the client's reported ownership. In principle you shouldn't need both (server side being the superior option)

@henkkelder your solution probably requires you have to a receipt validation service in place (https://www.iaptic.com maybe?) - which already handles product ownership.

**Comment by henkkelder** [comment]
Thank you :-)

I have already implemented a server side validation. This calls my server which in turn calls the AndroidPublisher service or https://api.storekit.itunes.apple.com/inApps.

However, My gut feeling tells me this is never called in this scenario. I do keep a log file on my server of all validation actions. Looking in the play store console at 'cancelled' (Geannuleerd) transactions that are cancelled exactly after 30 minutes I do not see anything in my validation log.
