### ISSUE TITLE
Billing 7.0 version with capacitor

### ISSUE THREAD

**Issue by SimonAlpha40** [j3k0/cordova-plugin-purchase#1590]
Hello i am using a capacitor application i was using th plugin cordova plugin version 11 : but it seems according to Google i have to upgrade the Version because of google play billing 7.0 : i have upgrade the latest version of the plugin :
⠸ update android [info] Found 5 Cordova plugins for android:
       cordova-plugin-chromecast@2.0.1
       cordova-plugin-purchase@13.11.1
       cordova-plugin-screen-orientation@3.0.3
       es6-promise-plugin@4.2.2

but when i launch my app i have this message :( 
164cae6.js:2 Native: tried calling InAppPurchase2.PAID_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.
(anonyme) @ 164cae6.js:2
164cae6.js:2 Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
(anonyme) @ 164cae6.js:2
164cae6.js:2 Native: tried calling InAppPurchase2.register, but the InAppPurchase2 plugin is not installed.
(anonyme) @ 164cae6.js:2
164cae6.js:2 Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
(anonyme) @ 164cae6.js:2
164cae6.js:2 Native: tried calling InAppPurchase2.when, but the InAppPurchase2 plugin is not installed.
(anonyme) @ 164cae6.js:2
164cae6.js:2 Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'

I am a bit lost lol ;) what can i do ?
The best 

Simon

### System Info

Output of `cordova info`.

**Comment by j3k0** [comment]
Hello, InAppPurchase2 in not required anymore. This plugin is now play typescript and doesn't require a wrapper. Just use the plugin as documented in the README here. (the `CdvPurchase.store` object, not `InAppPurchase2`)

Also check the version 13 migration guide in the wiki for help.
