### ISSUE TITLE
Purchases on Android are cancelled after 30 minutes due to external payment method?

### ISSUE THREAD

**Issue by henkkelder** [j3k0/cordova-plugin-purchase#1591]
In the Netherlands a payment method 'iDeal' exists. 
Basically the user is transferred to its bank app where he/she can confirm the payment.

Now what frequently, but not always, happens is that when a user has paid using iDeal the purchase is cancelled after 30 minutes.

I still haven't found an explanation, but I found this post:
[https://discussions.unity.com](https://discussions.unity.com/t/issue-with-iap-purchase-and-bank-account-verification-on-android/893602)

I think this is the same problem. So what appears to be happening:

- User presses purchase button in my app;
- User is presented with Play Store popup dialog to confirm payment
- User is taken to his bank app to do the actual payment
- Upon return after payment for reasons unknown the Play store dialog is closed which leads to cancellation of the purchase.

The user does not receive any mails to confirm purchase. But the money is taken out of his account. 
Google will refund this within a couple of days.

Has anybody seen this behaviour? How could I mitigate this?

**Comment by j3k0** [comment]
To understand what really happens, session logs would be necessary.

**Comment by henkkelder** [comment]
Thank you for your reply. 

My app registers handlers for productUpdated, verified, approved and receiptsReady. With the exception of purchases done with iDeal this seems to work fine.

Lookin at your documentation at github I do not see a description of the 'TransactionUpdate' event. 
I do see that the 'when' handler has a 'pending' event with a transaction as argument. However I cannot find any description on how to handle that event. Could you please give me some pointers or point me to the documentation?

For iDeal purchases I believe that the order of things might be different. (my own assumption) One important difference is that there is no advance verification of the payment menthod. The actual validation of the payment is just done at the time of the payment. So should .finish be called before the payment has been done, a user could cancel the payment and still receive the purchase.

How do I get a session log when I can only do a real purchase with a signed version of the app that has been published in the Play Store?

**Comment by j3k0** [comment]
The 'TransactionUpdate' event (or something named similarly, I don't remember the exact name) is something the native SDK is triggering (in the Java side of the plugin), which is bubbled up as an "approved" or "finished" event.

To get logs in production you can instrument the plugin's logger by replacing `CdvPurchase.Logger.console` (see https://www.iaptic.com/documentation/cordova-plugin-api/classes/CdvPurchase.Logger.html#console) -- set this to something the user can email to you for instance, or sends them to a log server.

`adb logcat` should also provide logs if you give add an option to set the plugin's verbosity to debug if it's a device you have physical access to.
