### ISSUE TITLE
On iOS CdvPurchase.store.when().approved(transaction => {}) returns the appstore.application transaction

### ISSUE THREAD

**Issue by selcukbeyhan** [j3k0/cordova-plugin-purchase#1594]
Hello,

### Observed behavior
I initiate purchase of subscription successfully on iOS.
Later the event CdvPurchase.store.when().approved(transaction => {}) is called.
Here, the provided transaction to the callback function is the default appstore.application transaction and not the one I triggered.

Here are the logs:
⚡️  [log] - LIFEPLANNER - Subscription: Purchase is approved:  {"className":"Transaction","transactionId":"appstore.application","state":"approved","products":[{"id":"com.myapplication.id"}],"platform":"ios-appstore"}

### Expected behavior
The transaction should have been the one related to my subscription purchase.

Thank you.

**Comment by j3k0** [comment]
On iOS, when any subscription is set to renew, the "application transaction" is set to be validated again (so subscription status are renewed). That is expected.

However, at the time of the first purchase of the subscription you should get the transaction for your subscription.

**Comment by selcukbeyhan** [comment]
got it, thank you.
