### ISSUE TITLE
Error in cordova setup documentation about apiKey

### ISSUE THREAD

**Issue by becvert** [j3k0/cordova-plugin-purchase#1597]
### Observed behavior

on https://www.iaptic.com/documentation/setup/cordova apiKey is autofill with private key

### Expected behavior

apiKey should be autofill with public key as per https://github.com/j3k0/cordova-plugin-purchase/blob/master/api/interfaces/CdvPurchase.IapticConfig.md#apikey

**Comment by j3k0** [comment]
Thanks for the report. Fixed it.
