### ISSUE TITLE
Unknown log output "Transaction finished and removed from paymentQueue - Transactions.updates"

### ISSUE THREAD

**Issue by selcukbeyhan** [j3k0/cordova-plugin-purchase#1598]
Hello,

### Observed behavior
I am developing in iOS with XCode and have a device attached.
During debug, I see in the logs following output: "Transaction finished and removed from paymentQueue - Transactions.updates"
However, I could not find what makes this log entry.
It is important to know because somehow, the finished transactions seem to be stuck at the payment queue.
Each time when I re-start the application via XCode, the verified purchases, verified receipts and local transactions (except appstore.application one) are empty:
⚡️  [log] - LOGPREFIX - Subscription: -store.ready- Verified Purchases:  []
⚡️  [log] - LOGPREFIX - Subscription: -store.ready- Verified Receipts:  []
⚡️  [log] - LOGPREFIX - Subscription: -store.ready- local transactions:  [{"className":"Transaction","transactionId":"appstore.application","state":"approved","products":[{"id":"com.myapplication.id"}],"platform":"ios-appstore"}]

thank you.

**Comment by j3k0** [comment]
Can you share full logs with verbosity set to debug and some source code? Thanks

**Comment by selcukbeyhan** [comment]
I found the issue. During development, I was testing another plugin of Capacitor.
That was throwing this log.
./node_modules/capacitor-subscriptions/ios/Plugin/Subscriptions.swift

**Comment by selcukbeyhan** [comment]
closed. not relevant with this plugin.
