### ISSUE TITLE
Getting plugin not found issue

### ISSUE THREAD

**Issue by nishi-webbrains** [j3k0/cordova-plugin-purchase#1599]
I’ve created an Ionic Capacitor app with React and need to implement in-app purchases. When searching for a Capacitor-specific plugin for in-app purchases, I couldn’t find one. I discovered that I need to use a Cordova plugin for this functionality in Capacitor.

However, when I use the latest version of the cordova-plugin-purchase, I encounter an error on the device: “plugin not installed.” I’m currently using @awesome-cordova-plugins/in-app-purchase-2 alongside cordova-plugin-purchase, and my Google Billing Client version is 7.0.0.

**Comment by j3k0** [comment]
Hello, you should not install "@awesome-cordova-plugins/in-app-purchase-2" but use this plugin directly (install cordova-plugin-purchase). Cf https://github.com/j3k0/cordova-plugin-purchase/?tab=readme-ov-file#note-for-capacitor-users
