### ISSUE TITLE
productUpdated not fired on ios

### ISSUE THREAD

**Issue by luk156** [j3k0/cordova-plugin-purchase#1602]
CdvPurchase.store.when().productUpdated(function(p) {
        switch (p.id) {
          // code //
        }
    });
    return CdvPurchase.store.initialize();

This code works on Android, but I recently discovered that the event no longer triggers on iOS.

**Comment by j3k0** [comment]
Can you share logs? Maybe your products cannot be loaded? (AppStore contract issue, ...?)

**Comment by luk156** [comment]
yes, my mistake.

[CdvPurchase.AppleAppStore] DEBUG: Products loaded: [{"isError":true,"code":6777012,"message":"Product not found in AppStore. #400","platform":"ios-appstore","productId":"3monthsub"},{"isError":true,"code":6777012,"message":"Product not found in AppStore. #400","platform":"ios-appstore","productId":"6monthsub"},{"isError":true,"code":6777012,"message":"Product not found in AppStore. #400","platform":"ios-appstore","productId":"12month"}]
