### ISSUE TITLE
Issue with v13.11.1

### ISSUE THREAD

**Issue by MyTek** [j3k0/cordova-plugin-purchase#1607]
### Observed behavior

Setting this doesn't appear to work or I'm doing something wrong:

store.applicationUsername = '9e7ee220aced5367585f2b048f97b33a';

### Expected behavior

On iOS i expected to receive that value back in the webhook from apple.

### System Info

{
  "transactionId": "2000000725875555",
  "originalTransactionId": "2000000725875555",
  "bundleId": "com.example",
  "productId": "product1",
  "purchaseDate": 1727338993000,
  "originalPurchaseDate": 1727338993000,
  "quantity": 1,
  "type": "Consumable",
  "inAppOwnershipType": "PURCHASED",
  "signedDate": 1727339027581,
  "environment": "Sandbox",
  "transactionReason": "PURCHASE",
  "storefront": "USA",
  "storefrontId": "555555",
  "price": 5000,
  "currency": "USD"
}

My goal is to tie the purchase to my backend somehow using a user id from my system.  Right now Im totally stuck at how other people are doing this or if I'm doing something wrong.  Forgive me if there isnt enough information.  I can provide whatever you need.

Also i have tried every version of UUID and basic strings i can think of.  I have also tried to set it in the order like so with no luck:

await offer.order({applicationUsername: '9e7ee220aced5367585f2b048f97b33a'});

**Comment by j3k0** [comment]
You should set applicationUsername like this: `CdvPurchase.store.applicationUsername = () => getUserId()`.

**Comment by MyTek** [comment]
Confirmed that does in fact work.  Thank you!

For anyone else encountering this, for iOS the applicationUsername HAS to be a UUID (v4 i think).  Then if properly set it will return the uuid like so in the server-to-server notification from apple like this:

"appAccountToken":"4758a858-26cc-47a9-ae79-1ad8254b96ea"

I set it like this:

store.applicationUsername = () => user.uuid

Also to note this works in sandbox also.

**Comment by j3k0** [comment]
Thanks for the comment, I'll make sure to make this appear in the documentation.

**Comment by Gokuldev23** [comment]
> Confirmed that does in fact work. Thank you!
> 
> For anyone else encountering this, for iOS the applicationUsername HAS to be a UUID (v4 i think). Then if properly set it will return the uuid like so in the server-to-server notification from apple like this:
> 
> "appAccountToken":"4758a858-26cc-47a9-ae79-1ad8254b96ea"
> 
> I set it like this:
> 
> store.applicationUsername = () => user.uuid
> 
> Also to note this works in sandbox also.

how do you done this part i only get some accountId after setting this . the accountId like a UUID how can i use that
