### ISSUE TITLE
Cordova-plugin-purchase - Android: Product with this id not found

### ISSUE THREAD

**Issue by john290n** [j3k0/cordova-plugin-purchase#1614]
Hi @j3k0,
I wanted to report an issue related to Android for cordova-plugin-purchase v13.11.1. It seems that it doesn't work on Android when I try to register products with store.register. I get the error “Product with this ID not found” when running the app on an Android physical device through Android Studio.

I believe I’ve completed all the necessary configurations, but I'm not sure why this is happening. I’m using React JS and Capacitor. My Android app is deployed in production, and I have set up the merchant account in the Google Play Console, where I have active products and subscriptions. I’m using licensed users on my Android device and have tried pushing the app to alpha closed testing and internal testing but without success.

please let me know if you have any idea. Thanks in advance!

**Comment by Dexus** [comment]
DID YOU REGISTER YOUR DEVELOPER ACCOUNT CORRECTLY? If not you will never get a working IAP!

**Comment by john290n** [comment]
Hello @Dexus, I think my developer account is correct because my app is published on the production. Also I have created some products where the status of these products is "Active", after that I have completed the Payment Profile but Im still getting the same error!

**Comment by john290n** [comment]
<img width="577" alt="Screenshot 2024-10-25 at 21 57 33" src="https://github.com/user-attachments/assets/37ce8b2f-c7f9-4112-80cc-0cfe38870f8e">
<img width="1440" alt="Screenshot 2024-10-25 at 21 58 15" src="https://github.com/user-attachments/assets/5c076f24-07dd-4730-b5b3-3b8c58a6c8f4">
<img width="704" alt="Screenshot 2024-10-25 at 21 59 02" src="https://github.com/user-attachments/assets/cc58f4cb-daff-48c1-9770-69176db072af">
<img width="688" alt="Screenshot 2024-10-25 at 21 59 37" src="https://github.com/user-attachments/assets/620dad5a-42eb-4d76-a15d-4986455476f4">
<img width="495" alt="Screenshot 2024-10-25 at 22 00 02" src="https://github.com/user-attachments/assets/b87aef89-bd11-4fbb-a849-b8a9125aaa06">
<img width="891" alt="Screenshot 2024-10-25 at 22 00 41" src="https://github.com/user-attachments/assets/a4f5a123-0269-4451-9837-58a271e5503a">

@Dexus

**Comment by john290n** [comment]
@Dexus could you please send me any contact information, so maybe you can help me to fix this issue?

**Comment by john290n** [comment]
I fixed the issue by installing the Play Billing Library on my physical device, logging in with my License Tester account in the Play Billing Lab app, setting the country to match my Google Play Console account, and running the app in release mode from Android Studio. The cordova-plugin-purchase library works for both iOS and Android as well!
