### ISSUE TITLE
Making Product Lose Owned Status?

### ISSUE THREAD

**Issue by OJcode14** [j3k0/cordova-plugin-purchase#162]
I have a custom validation method set up for iOS and Android. All works fine with the exception that I cannot see any method through which to change product's owned status from "true" to "false".

**Comment by j3k0** [comment]
Only consumable can be reverted to `not owned`, when calling `finish` if I'm right. Non-consumable are, by definition, always owned.

**Comment by OJcode14** [comment]
So where does a subscription "owned/not owned" fit in? In your example you use the owned status of a subscription to visually show whether a user is subscribed. It doesn't matter so much since the user can still re-subscribe even if product is "owned" it's just the fact that I can't use the p.owned status for much if I can't change it when my validation service says it's expired for that particular user.

store.when("subscription1").updated(function(p) {
        if (p.owned) {
            document.getElementById('subscriber-info').innerHTML = 'You are a lucky subscriber!';
        }
        else {
            document.getElementById('subscriber-info').innerHTML = 'You are not subscribed';
        }
    });

**Comment by j3k0** [comment]
I checked on iOS. If validator returns the PURCHASE_EXPIRED status, `product.owned` is set to false.

If you have your own custom logic in place, you can do `product.trigger("expired")`

**Comment by OJcode14** [comment]
Ah, ok. Perfect, that's what I was looking for thanks.

**Comment by hazmouneZaineb** [comment]
I have a custom validation method configured for iOS, everything works fine, but if the validation failed with the code PURCHASE_EXPIRED or INTERNAL_ERROR, the product is still in the APPROVED state and does not return to the VALID state, so I cannot make a new purchase and it can't renew the subscription. How can i reset the product state ?
`
this.store.validator = async (product: IAPProduct, callback) => {
			const body: ApplePayValidateModel = {
				receipt: product.transaction.appStoreReceipt
			};
			try {
				const res = await this.service.Create(body, ApiUrl.VALIDATE_APPLE_PAY, RequestType.JSON).toPromise() as ServerResponse;
				const result = res.value as AppleValidation;
				if (result.passed) {
					callback(true, { transaction: result.transaction });
				} else {
					callback(false, {
						code: result.status,
						error: { message: "validation failed for " + product.id }
					});
				}
			} catch (error) {
				callback(false, {
					code: this.store.INTERNAL_ERROR,
					error: { message: "error server => " + JSON.stringify(error) }
				});
			}
		};`

`this.store.when("subscription").unverified(p => console.log("unverified ", p));`
