### ISSUE TITLE
No Transaction Receipt for iOS NON_CONSUMABLE ?

### ISSUE THREAD

**Issue by westoj** [j3k0/cordova-plugin-purchase#164]
I don't seem to be getting a transaction receipt for NON_CONSUMABLE products hence can't then verify these types of purchases. I get a transaction receipt for subscriptions

This is the log of the product object at validation and approval:

{"id":"productSample","alias":"productSample","type":"non consumable","state":"owned","title":"TitleOfProd","description":"prod description","price":"£1.49","currency":null,"loaded":true,"canPurchase":false,"owned":true,"transaction":{"type":"ios-appstore","id":"1000000150414167"},"valid":true,"transactions":[]}

**Comment by pawelkaczmarek** [comment]
@OJcode14 have you managed to solve this issue? We are also looking for the solution of this problem.

**Comment by gwidonw** [comment]
@OJcode14, try to implement store validator.

#### Define validator ####
    store.validator = function(product, callback) {
        console.log(product) // Here you will find product receipt
    });

#### After product is approved, validate it ####
    store.when("product.id").approved(function(product){
        product.verify();
    });

#### More details: ####
* https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validator
* https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#receipt-validation

**Comment by Alphatiger** [comment]
@gwidonw #234 is the format is correct, please any one confirm this?

**Comment by Alphatiger** [comment]
For validation of apple receipt only sending the "type":"ios-appstore","id":"1000000150414167"} 
id mentioned is enough, please mention any validator, which works  ant example will be great.
