### ISSUE TITLE
product.owner is always false

### ISSUE THREAD

**Issue by PadreMontoya** [j3k0/cordova-plugin-purchase#165]
Hello,

I have an app that's been live for several months using cordova-plugin-purchase, and we're collecting funds, so I know it works.  I'm not able to get "Restore Purchases" to work, however, because product.owned always returns false.  My simple test for this is:

```
        store.when("merchant_fun_pack").approved(function (product) {
            product.finish();
            PurchaseManager.unlockGame();
            alert("Merchant Fun Pack purchased!");
        });         

        store.when("merchant_fun_pack").updated(function(product){
            alert("Debug: Fun pack updated.  Product owned: " + product.owned);
        });
```

I see the alerts coming across, but they always come across as "Debug: Fun pack updated.  Product owned: false".

I confirmed that merchant_fun_pack is a "Managed product" in Google Play, so it shouldn't be consumable.  And since we're collecting funds, I'd presume product.finish() is being hit correctly.

Any suggestions?

**Comment by nikoTM** [comment]
any updates on this ?

**Comment by aesculus** [comment]
You have to call store.refresh() again in your restore button. It seems to require this after the initial call. This is loosely documented.
