### ISSUE TITLE
webapp version

### ISSUE THREAD

**Issue by UnSleep** [j3k0/cordova-plugin-purchase#167]
What about webapps or other platforms?

can you add paypal to the library?

**Comment by j3k0** [comment]
That's possible. If someone have interest in investing either time or money, I will gladly help!

**Comment by sam2x** [comment]
Hey, this would be awesome feature if paypal is integrated, any plans about this ?

**Comment by j3k0** [comment]
No new plans about this. If some guys at PayPal are interested to make it possible...? Then why not.
