### ISSUE TITLE
Clear incomplete transactions (iOS)

### ISSUE THREAD

**Issue by BrettGregson** [j3k0/cordova-plugin-purchase#168]
In the process of implementing the plugin, I had a couple of transactions on sandbox accounts which were never completed. Now, everytime I start the app, no matter which apple ID I am logged in with, the device prompts me to enter the password for the sandbox accounts for which the transaction was not completed.

I am unable to find a way to clear these past transactions

**Comment by OJcode14** [comment]
This occurs if you don't finish transactions with a sandbox account and then delete the sandbox account. Unfortunately the only fix I've found for this is to change the bundle id of your project which you can do if you haven't had a version approved yet.

**Comment by jgberg** [comment]
You need to handle this condition by finishing the transactions...

**Comment by invalidusernam3** [comment]
How do I access the pending transactions?

**Comment by jgberg** [comment]
My products are all consumable.  For each product I have (pName), I check
if the product is loaded, valid and in the state of approved, and if it is
I finish it...  I do this once my app is setup and the user is _not_
purchasing anything... This clears up the problem of unfinished products...

var p = store.get( pName );

        *if*( p && p.loaded && p.valid && p.state == store.APPROVED )

            p.finish(); // now the user is charged...

**Comment by invalidusernam3** [comment]
Thanks jgberg, that looks simple enough
