### ISSUE TITLE
How is product state "owned" handled?

### ISSUE THREAD

**Issue by andiNr5** [j3k0/cordova-plugin-purchase#170]
First of all, I would like to say that I very much like this plugin, thanks for the good work! I am currently developing an iOS-application (that i would like to publish quite soon) and I have a question about the "owned"-state.

I am using several non-consumable In-App-Products and I would like to provide means to restore previously bought products (for example if the app has been re-installed on a new device). My purchase-buttons shall, after re-installing the app, show something like "restore" instead of the product-price.

Now if i purchase one of the products successfully and **restart** the app, I can see in the log-messages that the state of the product is correctly set to "owned". However, if i **de-install** and **re-install** the app, the state is set to "valid" on app-startup. Hence it appears that the information whether a product has been purchased is stored locally and lost during de-installation. Is this true? This would be unfortunate, as it now appears to the user that he will have to purchase the product again. Also when "buying" the product for a second time, the apple-message-boxes show that it already has been purchased and can be re-loaded. So the information that the product is owned by the user must be available. However maybe I am also using something incorrectly...

**Comment by 695Multimedia** [comment]
I am experiencing this same issue. Any news?

**Comment by andiNr5** [comment]
It looks like calling store.refresh() a second time will update the status of your In-App-Purchases. I use this to provide functionality to restore purchases that have already been bought.

**Comment by aesculus** [comment]
You have to call store.refresh() again in your restore button. It seems to require this after the initial call. This is loosely documented.
