### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Ajaxy** [j3k0/cordova-plugin-purchase#174]
No alert ever shown:

``` javascript
        store.register({
            id:    'bonus_boost_x2',
            alias: 'boost_x2',
            type:  store.PAID_SUBSCRIPTION
        });

        store.error(function (err) {
            alert('STORE ERROR');
        });

        store.ready(function () {
            alert(100);
        });

        store.refresh();
```

**Comment by Ajaxy** [comment]
Actually I can run `store.get('boost_x2')` and retrieve product object, but `store.order` doesn't work and doesn't produce any error either.

**Comment by eprochassoncag** [comment]
Any update on that? I have pretty much the same issue (i.e.: store.ready never resolves the callback) and I'm running out of idea.

**Comment by Ajaxy** [comment]
It finally worked for me (ensure you have newest version and calling `store.refresh()`). Still stuck with #350 :(

**Comment by eprochassoncag** [comment]
May I ask which version you are using?
I indeed call `store.refresh()` first, but it seems like `store.ready` never triggers (but if I try a couple time it sometimes work).
Weirder: I can actually (test) purchase stuff, so the configuration looks alright.

**Comment by Ajaxy** [comment]
I use last revision from this repo: bef30f1

**Comment by eprochassoncag** [comment]
No difference.

Interestingly, if I re-fire the store init procedure (register product, refresh, ready), it works (and resolve the initial callback as well).

Anyway, I'll keep investigating and I'll open a new issue if I can't get it working.

**Comment by eprochassoncag** [comment]
Turns out it was working fine, it was a bug with Angular 2 (the zone changing not detected, as I was wrapping everything in Observable). Anyway, quite a hairy one, turns out the plugin works perfectly.

And if you land here having the same problem that I have (which will happen if you use that plugin with ionic 2), the hack is to wrap the change of whatever it is that you are updating in a zone.run call, such as in the following snippet:

```
import {NgZone} from '@angular/core';
import {Observable} from 'rxjs/Observable';

@Page({
  template: '<p>{{bitOfInformation}}</p>',
})
export class MyPage {
  private bitOfInformation : string
  constructor(private zone: NgZone) {
    this.initStore().subscribe(
      () => {}, // we don't push value down the observable
      error => {}, // deal with the error
      () => {
        alert("Store init finished")
        this.zone.run(()=> {  // This is the hacky bit that will trigger the refresh of the value in the DOM
          this.bitOfInformation = "Store initialised!"
        })
      }
    )
  }
  
  initStore = function() {
    return Observable.create(observer => {
      store.register({
        // register your product
      })
      store.when("your product").owned(product => {
        // register your product events
      })
      store.when("your product").approved(product => {
        // register your product events
        product.finish()
      })
      // Refresh the store
      store.refresh()
     // Error callback
      store.error(error => {
        observer.error(error)
        observer.complete()
      })
      // Store ready callback
      store.ready(() => {
        observer.complete()
      })
    })
  }    
}
```
