### ISSUE TITLE
Can't Purchase. Authorization required.

### ISSUE THREAD

**Issue by yusuf-azer** [j3k0/cordova-plugin-purchase#175]
This is the first time working with this plugin and IAP (Google Play), I can't seem to find what I'm doing wrong.
No matter what I do, I get "Authorization required".

The App is published in Beta and I am using multiple test accounts and devices.
It's been stalling the project for over 2 weeks now.

Can someone tell me what I am doing wrong or check my script please?

```
// We must wait for the "deviceready" event to fire
// before we can use the store object.
document.addEventListener('deviceready', initializeStore, false);

function initializeStore() {

    if (!window.store) {
        log('Store not available');
        return;
    }

    store.register({
        id:    'com.domainnamechanged.appname.premium_account',
        alias: 'premium_account',
        type:   store.NON_CONSUMABLE
    });

    // Let's set a pretty high verbosity level, so that we see a lot of stuff
    // in the console (reassuring us that something is happening).
    store.verbosity = store.INFO;

    // We register a dummy product. It's ok, it shouldn't
    // prevent the store "ready" event from firing.
    store.when("premium_account").approved(function(product) {
        if (product.owned){
            window.localStorage.setItem("isPremiumAccount", "true");
        } else {
            window.localStorage.setItem("isPremiumAccount", "false");
        }

        product.finish();
    });

    // When every goes as expected, it's time to celebrate!
    // The "ready" event should be welcomed with music and fireworks,
    // go ask your boss about it! (just in case)
    store.ready(function() {
        console.log("\\o/ STORE READY \\o/");
    });

    store.error(function(e){
        console.log("ERROR " + e.code + ": " + e.message);
    });

    // After we've done our setup, we tell the store to do
    // it's first refresh. Nothing will happen if we do not call store.refresh()
    store.refresh();
}

function storeOrder(type){

    if(type == "premium") {
        document.addEventListener('deviceready', init, false);

        function init(){
            store.order("premium_account");

            store.refresh();
        }
    }
}
```

**Comment by Scratch008** [comment]
I changed "store.verbosity" level to "store.DEBUG".
and found out that "the server doesn't recognize this product, it cannot be used.", however the in-app product is active.

**Comment by fer8a** [comment]
Have you set your billing key as described [here](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO#add-android-billing-key)?

Also theres a conditional to check whether your product is valid or not that you should definitively be using (I don't see it in your code).

``` javascript
store.when("premium_account").approved(function(product) {
  if (product.valid) {
    //your logic goes here
    if (product.owned) {
      //do your thing
    } 
  }
});
```
If you can take a screenshot from your console when in debug and post here the output would be helpful too to track the code.

**Comment by Scratch008** [comment]
Thanks for the help.

I managed to fix the issue.

The problem was lying in the Product ID. 

id:    'com.domainnamechanged.appname.premium_account',

solution:

id:    'premium_account',

either the documentation is confusing or it is a new quirk of cordova's latest build in android.
