### ISSUE TITLE
Google Wallet : Cancel an order

### ISSUE THREAD

**Issue by giggioz** [j3k0/cordova-plugin-purchase#179]
Hi,

Let's assume a customer bought an item and the item status goes to 'owned'.

Now i go to the google wallet merchant and cancel that order, an e-mail is sent to the customer informing him about this but i don't receive any update from the store object (i.e. the item keeps the OWNED status)

If i look to the product life-cycle scheme in the doc i see that from the OWNED status there is no way to restore a previous state...

What am i missing?
Thanks for the help.

**Comment by butlimous** [comment]
You are right. Something wrong is here. Test transactions for example are cancelled automatically after 14 days. So product should return back to "valid" state but for some reason, it's stuck at "owned"

**Comment by butlimous** [comment]
After around 12 hours after cancelling a purchase, I found It returned again to "Valid" state and is available for purchase again :) Have you waited enough time?

**Comment by Alphatiger** [comment]
Adding my 2 cents, please switch off and switch on the mobile then business as usual, actually i cam to this post in search of a similar situation where i cancelled the purchase using defer API given by google and when i query it gives me the product is subscribed if i switch off my mobile and switch it on then all the values are reset, (One thing i havent called the product.finish() yet). So this should be something related to google play services cache!!!!!!!

**Comment by Script47** [comment]
@giggioz 
@butlimous 
@Alphatiger 
@j3k0 

I'm currently tackling the same issue and because of it, I can't test my app any further. Has anyone managed to find a viable solution to this issue?

**Comment by giggioz** [comment]
Hi, it's been a while i don't play with this plugin anymore... i think what butlimous said it's true: 

> After around 12 hours after cancelling a purchase, I found It returned again to "Valid" state and is available for purchase again :) Have you waited enough time?

Did it work for you?

**Comment by Script47** [comment]
@giggioz yep, that worked for me. I was hoping for a more code-based reliable solution but thanks anyway. :+1:
