### ISSUE TITLE
Product is invalid

### ISSUE THREAD

**Issue by chrisschaub** [j3k0/cordova-plugin-purchase#181]
So, I've been over the docs and think I have it setup correctly. My product gets registered, see that in the console. But when I try to "get" it, I get a "product is invalid". I'm using a test user account in the sandbox. The store returns ready and refresh works, even register works. 
I'm assuming the product name should be
<bundle>.<productid>
org.foo.app.someproduct1

Thanks for any other places to check!

**Comment by Fortuitous** [comment]
You might #95.  See my comment there where I describe that the store.register.id field must be *exactly* the same as the product id.  So if you enter  "org.foo.app.someproduct1" for the id, you must enter all that as the product id on the Google / Apple servers as well.

**Comment by chrisschaub** [comment]
@Fortuitous -- livesaver!! I can't believe it was that simple. Thanks!
