### ISSUE TITLE
Paid Subscription Can't Restore

### ISSUE THREAD

**Issue by markie040** [j3k0/cordova-plugin-purchase#184]
I have been having trouble with the store.refresh function with my sandbox account. 

I can purchase the subscription without a problem but can't seem to restore the product. if I click to purchase again i get notified i have already purchased the product but the store.refresh will not bring back the transaction history or as that it is owned ?

**Comment by markie040** [comment]
iOS

**Comment by LukePulverenti** [comment]
Did you find a solution?

**Comment by 1b0t** [comment]
I ran into the same problem.
Nothing happens at all if you call restore(). Is this by design? You can re-purchase the subscription and it will be re-enabled (you won't get double charged). But this is very confusing.

**Comment by aesculus** [comment]
You have to call store.refresh() again in your restore button. It seems to require this after the initial call. This is loosely documented.

**Comment by 1b0t** [comment]
Thank you! :+1:

**Comment by remisture** [comment]
@aesculus 
> You have to call store.refresh() again in your restore button. It seems to require this after the initial call. 

Do you mean calling `store.refresh()` two times when hitting the button? Or first calling `store.refresh()` in the init and then when hitting the button?
