### ISSUE TITLE
Approved state does not fire iOS

### ISSUE THREAD

**Issue by chrisschaub** [j3k0/cordova-plugin-purchase#190]
I'm in sandbox mode on iOS, but I can't get the product state to be approved. Does APPROVED fire as part of updated? Or do I have to trap for it separately. I've tried both ways with "when" but can't get it to fire. Other events fire correctly. I basically enter my itunes dev sandbox password, choose "Buy"  and then nothing. My products and app are in sandbox mode though. Also, when a restore happens, does it change the product to APPROVED? Thanks!

**Comment by chrisschaub** [comment]
And the actual error from the simulator is:

[store.js] ERROR: ios -> ERROR 6777010: Cannot connect to iTunes Store - {"productId":"15100334"}

I can register the products, see them become VALID and start the purchase process. But then it fails after choosing "Buy". Not itermittant.

**Comment by butlimous** [comment]
After clicking "Buy", the response should be either purchase was successful or you are not authorized to purchase. When you close the success message, the approved state will fire. If you don't get any message after clicking "Buy", then something else wrong is going.

**Comment by chrisschaub** [comment]
Ok, good, so apple handles the success message? It's funny, the Ionic
emulator will register and verify products -- even know that i've tried to
purchase them and allow free re-download. But, the buy doesn't return a
success popup. On the iOS side, I'm assuming I need to setup a TOTAL test
scenario, bundle id's and provisions with in-app purchase all have to match
for this to work. That might be the issue.

On Mon, May 18, 2015 at 3:33 PM, butlimous <notifications@github.com> wrote:

> After clicking "Buy", the response should be either purchase was
> successful or you are not authorized to purchase. When you close the
> success message, the approved state will fire. If you don't get any message
> after clicking "Buy", then something else wrong is going.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/190#issuecomment-103201219>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by butlimous** [comment]
Of course you can't test without all this stuff!

**Comment by chrisschaub** [comment]
Yes, working much better. Word of warning to all, don't test this in ANY
emulator or simulator even if it looks like it's partially working, it's
not.

On Mon, May 18, 2015 at 3:51 PM, butlimous <notifications@github.com> wrote:

> Of course you can't test without all this stuff!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/190#issuecomment-103207129>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by butlimous** [comment]
I have a question for you, what data you get in product.transaction after you complete a purchase? Mine returns only transaction id while it should return a receipt with fields like signature, enivronment, pod, signing-status, etc...

**Comment by chrisschaub** [comment]
Ha, I just wrote to you about that! I don't get much in transaction, just
type is populated, the rest are undefined. This is what an approved product
object looks like, seems a bit odd ...
```
Object
  alias: "application data"
  canPurchase: false
  currency: null
  description: null
  id: "application data"
  loaded: true
  owned: false
  price: null
  state: "approved"
  title: null
  transaction: Object
    appStoreReceipt: undefined
    signature: undefined
    type: "ios-appstore"
  type: "non consumable"
  valid: true
  version: undefined


On Mon, May 18, 2015 at 6:06 PM, butlimous <notifications@github.com> wrote:

> I have a question for you, what data you get in product.transaction after
> you complete a purchase? Mine returns only transaction id while it should
> return a receipt with fields like signature, enivronment, pod,
> signing-status, etc...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/190#issuecomment-103243620>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
https://github.com/j3k0/cordova-plugin-purchase/issues/192

On Mon, May 18, 2015 at 6:09 PM, Christopher Schaub <chris@schaub.com>
wrote:

> Ha, I just wrote to you about that! I don't get much in transaction, just
> type is populated, the rest are undefined. This is what an approved product
> object looks like, seems a bit odd ...
> ```
> Object
>   alias: "application data"
>   canPurchase: false
>   currency: null
>   description: null
>   id: "application data"
>   loaded: true
>   owned: false
>   price: null
>   state: "approved"
>   title: null
>   transaction: Object
>     appStoreReceipt: undefined
>     signature: undefined
>     type: "ios-appstore"
>   type: "non consumable"
>   valid: true
>   version: undefined
>
>
> On Mon, May 18, 2015 at 6:06 PM, butlimous <notifications@github.com>
> wrote:
>
>> I have a question for you, what data you get in product.transaction after
>> you complete a purchase? Mine returns only transaction id while it should
>> return a receipt with fields like signature, enivronment, pod,
>> signing-status, etc...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/j3k0/cordova-plugin-purchase/issues/190#issuecomment-103243620>
>> .
>>
>
>
>
> --
> Christopher Schaub
> http://chris.schaub.com
>
>


-- 
Christopher Schaub
http://chris.schaub.com
