### ISSUE TITLE
No receipt in iOS after purchase, only Transaction id

### ISSUE THREAD

**Issue by butlimous** [j3k0/cordova-plugin-purchase#191]
I have successfully configured and tested the plugin for android. I use my own validation service so I need to get the receipt data to submit to my validation service. Android returns these data which includes the receipt, signature, and transaction id. I then send these data my validation to verify and reward the user.

In iOS however, calling product.transaction returns only transaction id(s). The response should contain signature, purchase_info, pod, environment, and signing-status. Is anyone else facing this?

Thanks
Regards
Michael

**Comment by butlimous** [comment]
Receipt data is available through the validator not when "Approved" state fires.

**Comment by Alphatiger** [comment]
i am facing the same problem, don't know the steps of setting up a validator for IOS, can you please help me out.
Right now after a purchase i am getting only transaction ID, Please guid me.
