### ISSUE TITLE
Not appearing in Google Wallet

### ISSUE THREAD

**Issue by bryanwokich** [j3k0/cordova-plugin-purchase#194]
So I have an application in Beta, which seems to be working properly.  I can initialize the product and purchase it.

I'm now in a purchased state and cannot figure out how to delete my purchase to retest functionality.

I thought the purchase would appear in Google Wallet and I could cancel, but its not appearing.  Am I missing a step?

**Comment by butlimous** [comment]
The one who cancels the purchase is Merchant not the user. So check the transactions from the merchant wallet and you can cancel them from there or wait 14 days and they will be cancelled automatically.

**Comment by bryanwokich** [comment]
Yup.  I'm logged into the Merchant account when checking Wallet.  Maybe I'm just looking in the wrong spot.

I'm looking at "Wallet Merchant Center" -> Orders....

Thanks for your help, I really appreciate it.

**Comment by butlimous** [comment]
You are on the correct page. You should see a list of the transactions. Click on any of the orders, a sidebar layout will appear. Click on "Cancel Order"

**Comment by bryanwokich** [comment]
Thanks.  I do see a list of orders for another project, but not for the one I’m looking for.  

I don’t see the ones for the current project though.  I wonder if there’s something explicit I need to do to connect the app and the wallet merchant account.   I was under the impression it was one-to-one for developer account to merchant account, but that may be wrong.

**Comment by butlimous** [comment]
It's a one time setup in the Google Play account. You should connect the developer account with the merchant account if you haven't done already

**Comment by butlimous** [comment]
You should have done this already or you won't be able to create in app products at all

**Comment by bryanwokich** [comment]
Yeah.  I can create the products, and the whole thing is functioning for another app (actually making sales).  

What’s extra odd is that I’m receiving positive feedback through the plugin.  I can actually purchase products with the test accounts.  Its just not appearing in the console.
