### ISSUE TITLE
how to check subscription Status

### ISSUE THREAD

**Issue by pconic** [j3k0/cordova-plugin-purchase#201]
Hi

I want know what is subscription Status: 
Canceled
Expired
Good

Thank you

**Comment by uareurapid** [comment]
i might be wrong but i believe this is not included on the plugin, basically you will need to have a valid receipt and validate it against Apple server, might worth a look at:
https://developer.apple.com/library/mac/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html
If you have the receipt data (base 64) you could do a post request and parse the JSON
