### ISSUE TITLE
Multiple consumable products

### ISSUE THREAD

**Issue by HimanthTag** [j3k0/cordova-plugin-purchase#204]
I am confused by the way this plugin works with ios, i am getting things work with android, however with one issue. For ios, i am registering multiple products at once, then by calling store.refresh() prompts for the password just when user enters the screen. So i am calling the store.refresh() every time user clicks on buy a product, sometimes the when watch function gets called even before the transaction is completed and it making a callback which calls my internal function to provide the consumable product data.

My code goes like this

store.verbosity = store.INFO;

```
store.register([
    {
        id: "product1_id",
        alias: "1st product",
        type: store.CONSUMABLE
    },
    {
        id: "product2_id",
        alias: "2nd product",
        type: store.CONSUMABLE
    },
    {
        id: "product3_id",
        alias: "3rd product",
        type: store.CONSUMABLE
    }
    ]);

 // When every goes as expected, it's time to celebrate!
    // The "ready" event should be welcomed with music and fireworks,
    // go ask your boss about it! (just in case)
    store.ready(function() {
       notify("Store is ready");
    });

    // After we've done our setup, we tell the store to do
    // it's first refresh. Nothing will happen if we do not call store.refresh()
    store.refresh();
```

  purchaseProduct = function(product_id){

```
store.order(product_id);
store.when(product_id).approved(function(product) {
       product.verify();
 });

 store.when(product_id).verified(function(product) {
     provideProductToUser().then(function() {
        product.finish();
   });
 });

 store.when(product_id).owned(function(product) {
                 notify("Product is now owned");
 });

 store.when(product_id).cancelled(function(p) {
      notify("Transaction cancelled");
 });
```

  }

Is this the correct way to write the code, should i call refresh within ready event? Can i add when listeners each time user clicks the buy product. Actually tried various ways of doing things, but could not succeed yet..

And the one issue with android, the event listeners are called multiple times as i purchase a same product. No. of times i purchase a consumable product, the same no. of times the approved call back gets called. Trying to solve this for quite a long time, any help would be much appreciated. Advance thanks..

**Comment by nikoTM** [comment]
As far as I could figure out, you should call store.refresh at the end of your purchaseProduct function so it applies new event handlers, also I have read somewhere that it is a bit buggy to register multiple products at once, so you should just call store.register for every product. Regarding some callbacks being called multiple times, I think it is because every product goes through the whole product cycle upon registration( you can look at logs when verbosity is set to DEBUG).

**Comment by HimanthTag** [comment]
With debugging i found that couple of my consumable products are missing the other information in log, as i register and refresh i am getting descriptions and price for 2 consumable products and getting store response only with the product id for other 2 consumable products. Is there any restriction with the size of product id that we register with itunes?

**Comment by HimanthTag** [comment]
Actually product_id was one of the issue, when i try to get product details, i did not get few products details until i reduced the id size. No where it has mentioned in itunes doc about it.. Hope knowing this may solve few developers problem..

**Comment by j3k0** [comment]
Didn't know about this limitation either. How long was your product ID?

Thanks a lot for following up on this.

**Comment by HimanthTag** [comment]
I had about 29 characters, just checked if i can reduce it to see if its working.. oops, it worked..

**Comment by HimanthTag** [comment]
By any chance, will you have time to post any working code sample with multiple consumable products. Or atleast a reference where i can find some sample code. I develop in angularjs, register products in controller, as i call store.refresh() when user wants to purchase, it prompts for credentials but in background it processes the purchase..  Am i doing it right?

**Comment by j3k0** [comment]
There's nothing special about using multiple products, just call register multiple times.

```js
store.register({... product info 1 ...});
store.register({... product info 2 ...});
```

**Comment by j3k0** [comment]
Also, `refresh` should be called at app startup (right after init and registering products)

**Comment by HimanthTag** [comment]
For IOS: As i am registering the products inside my angular controller, i am getting the popup asking for itunes account password whenever i enter the screeen. I want it popup only when i try to buy a product, calling refresh does open it but at the same time in the background the purchase process takes place too.

**Comment by Sanafan** [comment]
The PopUp-Window will only appear if there are unfinished products inside your queue. Try to finish all products and the window will not pop up on `store.refresh()`

Install GapDebug, you can see the whole console output inside it.

**Comment by Pigsnuck** [comment]
"The PopUp-Window will only appear if there are unfinished products inside your queue."

Thanks for that tip!  That's very useful!

**Comment by Pigsnuck** [comment]
Actually, that doesn't appear to be true.  I get the popup even with no unfinished items in the queue.
