### ISSUE TITLE
Is there any way to get a list of my current products in the store?

### ISSUE THREAD

**Issue by rwillett** [j3k0/cordova-plugin-purchase#205]
Hi,

We're currently working through adding subscriptions to my Jambuster app. Whilst its not all working, its *seems* to be working enough. Famous last words :)

One thing we can't find is how to get a list of products that we have made available on iTunesConnect. 

We've created a monthly subscription, three monthly and yearly subscription and can register these using store.register and store.refresh. Looks good and we can see the right data. 

What we'd like to do, is to just use iTunesConnect to create different offerings, e.g. a snap sale for one week subscriptions and have the app automatically retrieve this. At the moment we have to resubmit a new app as it requires a code change.

We know we can create a XML file we could download to the app from our web server that describes the new offerings, so we don't have to resubmit but thats a two step process and things can go wrong. It seems cleaner to use iTunesConnect to have one place to store everything and we know to connect to it anyway to get the pricing details.

Is there any way to get a list of the product ID's that we can iterate over, apply store.register to them and the app automatically picks these things up. If not we'll have to resort to an XML file.

Any and all suggestions gratefully received.

Thanks for reading,

Rob

**Comment by j3k0** [comment]
You need to resort to XML file (or whatever). StoreKit SDK don't provide the list of products.

A quick and dirty (!) alternative is to register product IDs like:
`p01, p02, p03, p04, [...], p50` (more than what you need)

They'll be `invalid` until you create them on iTunes Connect. You can use the alias feature to give them some sense in the code.

**Comment by rwillett** [comment]
OK. 

Thanks for prompt answer, we thought that was probably the response :)

I can see the idea behind the p0 - p50. My understanding is that once you use and ID up in iTunesConnect its dead and buried and cannot be used again. So that idea would work for a long time but would eventually need to refreshed with another batch of numbers.

Good idea!

Thanks.

Rob
