### ISSUE TITLE
Hopefully simple (and quick) confirmation needed!

### ISSUE THREAD

**Issue by rwillett** [j3k0/cordova-plugin-purchase#208]
Our understanding is that the only way to check cordova-plugin-purchase is working is to use it on an actual device. So we can't use the Xcode iPhone simulators or the Android simulator such as Genymotion. We have looked in the docs and as many mailing lists as we can find and can see tangential references to it but it would be good to know for certain. Its just a lot slower deploying to a real device each time :) So do we have to use actual devices?

I also suspect there are no store simulators we can use. We've seen Objective C libraries that people can compile but thats not going to help us. Any information such as "No" would be helpful (and expected)

Thanks

Rob.

**Comment by rafaellop** [comment]
Yes, you need a device, at least for Android (I don't know iOS so cannot tell).
Android emulators don't have google play service installed neither iab.
You can install them by yourself but it's a pain bigger than using a device.
You can eventually use the genymotion emulator, but it's not free and still require installation of the packages, but this should be easier than for a stock emulator from google.

Debugging on a device is quite fast and for me it is better than those shitty (sorry) emulators.

**Comment by rwillett** [comment]
Thanks for the reply. We suspected that was the case but were really, really hoping we were wrong.

We know iOS better than Android and as far as we can see you need a real device as well. We can run the same code on the device and on the simulator, the simulator returns an error

ERROR 6777010:

The device works. Well it doesn't, but thats because our code doesn't work :) We'll fix that today though.

We've brought the Genymotion emulator, mainly for making sure all our screen displays work OK. Once we have the iOS version working, we'll move over to Android and get that working.The Android emulators are pretty rubbish, must be said. My personal machine is a maxed out 4790K with 32GB of RAM, twin high end graphics cards and its still slooooooooooooow with the stock Android emulator.

Anyway thanks again.

Rob

**Comment by j3k0** [comment]
iOS device required.

I have plans to create a "dummy / dry-run" mode for apps' automated tests (and simulators)... but nothing really done yet.

**Comment by rwillett** [comment]
Ok, if you feel like implementing it in the next, say 48 hours, please feel free to go ahead :)

Best wishes,

Rob.

**Comment by rafaellop** [comment]
If you want to speed up the emulators use the x86 images and install HAXM driver from Intel. I'm on Windows and I don't know if this would work on Mac but on mine W81 emulators are usable now. Work almost same fast as devies.

@j3k0 Nice to have you here :-) Quick question, I'm working on receipt verification and I've got working server side but it seems the validator part in your code expects some special data in the response. I do Google Play store response check on server and just reply true/false states to my apps (non cordova), but it seems that your plugin expects some other data. I utilize the simple approach with store.validator = url and then handlers for the verified and unverified events.
