### ISSUE TITLE
Hosting content on Apple servers

### ISSUE THREAD

**Issue by saruz** [j3k0/cordova-plugin-purchase#21]
Heya,

Any idea would this work out of the box or do I need some configuring? For what its worth, I read something about using the SKDownload class to download the content.

You can read more about it in the In-app-purchase guide provided by Apple.

Thank you already for the plugin :)

**Comment by whyameye** [comment]
any further development on this? It would be a really useful feature to have...

**Comment by rewonc** [comment]
@peacemoon +1

**Comment by peacemoon** [comment]
sorry guys, i have switched to fully native development and don't use this plugin anymore. But if you follow the tutorial here: http://xinsight.ca/blog/iap-content-download-in-ios6/, you should get the content download function.

**Comment by j3k0** [comment]
Feature added, thanks to @dpa99c #255
