### ISSUE TITLE
How to know Subscription billing period monthly, weekly etc

### ISSUE THREAD

**Issue by Alphatiger** [j3k0/cordova-plugin-purchase#213]
I dont see a way how to get information on subscription period like monthly, weekly, daily etc.

**Comment by rwillett** [comment]
I don't believe there is a way from within the plugin. I was also looking for this and couldn't see it either.

**Comment by Alphatiger** [comment]
Any update appreciated

**Comment by dominic-simplan** [comment]
+1, would be nice not to have to hardcode the subscription duration

**Comment by Dexus** [comment]
you should do this via your server validator... there is no need to do this via app... and it would be insecure if you do...

**Comment by dominic-simplan** [comment]
I think there is a misunderstanding, this has nothing to do with security. It is only for displaying the duration of a subscription in the app.

I define the name, description, price and duration of a subscription in the AppStore.

Then in the app, I use store.getProduct() to get and display the name, description and the price of the subscription (as mentioned in the plugin docs), but currently I have to hard-code the duration.

**Comment by j3k0** [comment]
The problem is that the information isn't provided by iOS and Android platforms (except if that changed since last time I checked).

It is on windows, so I'll try to make the value available there. It'll still have to be hardcoded (or stated in the product title) for other platforms.

**Comment by dominic-simplan** [comment]
@j3k0 don't know if I am looking at the right documentation, but it seems to be there for iOS and Windows as well?
https://developer.apple.com/documentation/storekit/skproduct#//apple_ref/occ/cl/SKProduct
https://developer.android.com/google/play/billing/billing_reference#getSkuDetails

**Comment by j3k0** [comment]
`billingPeriod` and `trialPeriod` added on windows UWP. 642b84d
