### ISSUE TITLE
get product details without signing in

### ISSUE THREAD

**Issue by andreassh** [j3k0/cordova-plugin-purchase#214]
Thanks for a great plugin!

I have an issue, that I would like to hear if there is a workaround to. 
The first time i use the plugin on a new device I'm able to retrieve products from apple using the store.refresh() method, without the user being prompted for a iTunes Store. 
However, as soon as a user has bought an item and closed the App, the App keeps prompting me for a iTunes Store password, every time I start up the app and try to retreive a product using store.refresh().

Is there a way to get product details without calling store.refresh()? Or calling store.refresh() without prompting for password?

**Comment by Sanafan** [comment]
+1

**Comment by uareurapid** [comment]
Are you testing in sandbox?
If so, you need to make sure you´re logout from Settings->iTunes & App Store
Also, make sure you use a sandbox account when prompted..
If you close the app and don´t logout, next time it will prompt again, sandbox is a bit tricky... will not happen on production env though..

**Comment by andreassh** [comment]
Thanks for the answer @uareurapid. I am indeed in sandbox mode. Good to hear that this won't happen in production env.
