### ISSUE TITLE
getting price , description etc null when we fire store.get

### ISSUE THREAD

**Issue by padmajashukla** [j3k0/cordova-plugin-purchase#216]
Hi,
when we run this code , we get store is ready info.
1) then we call 
 store.register({
                    id: "io.cordova.PushInAppPrvii.Cons",
                    alias: "100 coins",
                    type: store.CONSUMABLE
                });, store.register we dont get any error there
2) then store.refresh() --- no error
3) when store.get(productId) 
var p4 = store.get("io.cordova.PushInAppPrvii.Cons");
               
we still get null for all fields except, Id and type.

What wrong are we doing here
are we getting connected to itunes .. how to check that ..

**Comment by cameronbourke** [comment]
@padmajashukla Are you still having this issue?

**Comment by padmajashukla** [comment]
This was solved !
there were configuration issues ..

regards,
Padmaja

On Thu, Jul 9, 2015 at 1:49 PM, Cameron Bourke <notifications@github.com>
wrote:

> @padmajashukla <https://github.com/padmajashukla> Are you still having
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/216#issuecomment-119870993>
> .
>



-- 
thanks n regards
Padmaja Shukla

**Comment by fabiosussetto** [comment]
Hi @padmajashukla, I'm having the same problem. What configuration issues did you have to fix to get it working? It would be nice to have some kind of error callback in this case, to help understand what's going on.

**Comment by fabiosussetto** [comment]
Nevermind, it works, the bundle id was wrong.
