### ISSUE TITLE
base64EncodedString  deprecated in cordova 3.8.0

### ISSUE THREAD

**Issue by RouR** [j3k0/cordova-plugin-purchase#218]
https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L420-L445

Warning from compiler with suggestion:
```
[[transaction transactionReceipt] base64EncodedString] - "deprecated in cordova 3.8.0 use [NSData cdv_base64EncodedString]"
```

**Comment by j3k0** [comment]
Can you make a Pull Request with the fix?

**Comment by RouR** [comment]
No, I don`t know Objective-C. I found it fortuitously.

**Comment by rwillett** [comment]
Here's a screenshot of the error in case it helps.

![screen shot 2015-06-16 at 09 12 57](https://cloud.githubusercontent.com/assets/668923/8178634/fd4b1d56-1407-11e5-8ca0-0c28a24c257d.png)

**Comment by j3k0** [comment]
Thanks. Fix is merged-in in master.

**Comment by tolutronics** [comment]
When trying to verify the payment using the appstoreReceipt it give 21002 error (The data in the receipt-data property was malformed) ..please is this an error with the base64 been generated... i don't know Objective-C, i would have try to fix.....
Please help look into this..
