### ISSUE TITLE
Product state does not return to VALID upon a validation error

### ISSUE THREAD

**Issue by shaifd** [j3k0/cordova-plugin-purchase#224]
Hi,

According to the documentation, it is stated that:

Any error in the purchase process will bring a product back to the VALID state.
## 

Our application implements our own custom validation against our server, we have noticed that if we fail the validation - the product state remains "approved" instead of getting back to "valid", which means that the user can not order the IAP item again if she fixes what she did before.

While debugging we can return the product to a valid state by manually calling the finish() method of the product, but this does not make sense in a real life environment. Is there a work-around that we did not see - or is it really an issue that needs addressing?

BTW - Another interesting point, when validation fails with an error of store.INVALID_PAYLOAD it might not make sense to do the continued retries - as it is not a connection issue, but clearly something that failed because of a bad/counterfeit receipt.

**Comment by Alphatiger** [comment]
Good one, interested to see how this can be handled
