### ISSUE TITLE
Plugin gets occasional crash on store.refresh()

### ISSUE THREAD

**Issue by rwillett** [j3k0/cordova-plugin-purchase#226]
Hi,

I'm getting the occasional crash when running store.refresh() . It happens about one time in twenty.

Happy to provide more information but not clear what needs to be sent. It is not easy to reproduce but again happy to try.

Here's a screen shot if it makes any difference.

![screen shot 2015-06-25 at 15 59 26](https://cloud.githubusercontent.com/assets/668923/8357581/75e44a2e-1b53-11e5-9f86-332da34d1841.png)

I'm also getting a new error on the subscription validation server which I've never seen before. It appears that the canPurchase, owned and loaded flags are not being set when a new purchase is sent. I handle the error on the web server but I'm sure its all inter related.

I _think_ this is due to the crash and the plugin trying to catch up but I'm not sure as everything is async and so difficult to trace :)

Please let me know what you need.

Thanks,

Rob

**Comment by Defcon0** [comment]
Same problem here :-( For me it's rather working once in twenty times. Crashes everytime :(
