### ISSUE TITLE
product.transaction.appStoreReceipt needs 2 product.refresh() to change

### ISSUE THREAD

**Issue by aminecmi** [j3k0/cordova-plugin-purchase#233]
Hi,

I faced a problem with the plugin while trying to buy non-renewable subscriptions.
The problem was that the appStoreReceipt content wasn't changed after calling refresh() the first time.

After setting the listeners and the first refresh(), the validation of the order was still containing the previous appStoreReceipt.
I solved my issue by calling refresh() twice after setting all the listeners, so that the receipt was the correct one once in the validation function.

Hope it helps someone.

**Comment by rwillett** [comment]
Yes we had that problem :) and solved it the same way.

I think the StoreKit caches a lot of data on the device and it sometimes needs a good kick to make it work properly. 

Rob

**Comment by aminecmi** [comment]
@rwillett how did you solve the problem when the user isn't loggued in to the store, and the two refresh() make the app display the login popup twice (even if the user was loggued in the first time) ?

**Comment by rwillett** [comment]
I haven't so far. Its unclear to me how many times you need to login to the sandbox as it seems to be a random number. Since we haven't gone live I don't know what happens :(

**Comment by aminecmi** [comment]
Just as a follow up.

I just solved the problem of the invalid receipt (the first one wasn't the good one).

I went back to calling ```store.refresh()``` once after the initialization, because it wasn't working as intended, and it wasn't that useful.

After buying something, the verify will be called, but will have the old data, and then I added a conditional  store.refresh() (```if(itemSelected)```) that will call the validation on the product.

This time, the product will be validated.

Hope it helps someone.

**Comment by fabiosussetto** [comment]
@aminecmi hi I'm experiencing the same issue. How did you fix it in the end? When do you call the extra store.refresh()? Thanks!

**Comment by aminecmi** [comment]
@fabiosussetto I call the first ```refresh()``` where it should be called (after all the listeners).

I call the second one inside the validation code
The server that we use will send a different HTTP code if the receipt is an older one, so if it is an older one, I call the ```refresh()``` method that will trigger the validation again, with the right data.

**Comment by fabiosussetto** [comment]
@aminecmi thanks for your reply, I'm trying to use the same workaround.

@j3k0 any thoughts on this? Seems to be quite a problematic issue.

**Comment by fabiosussetto** [comment]
I believe we fixed the issue this way:
```
store.validator = (product, callback) => {
            storekit.refreshReceipts((receipt) => {
                 // now receipt should be the updated one
                  validate(...);
            });
        };
```

After digging a bit into the code we found storekit.refreshReceipts which seems to do the trick at the moment.

**Comment by BlueHayes** [comment]
Using `storekit.refreshReceipts()` worked for me too, thanks @fabiosussetto.

**Comment by aminecmi** [comment]
@fabiosussetto is this asks for the user password twice, as well ?

**Comment by fabiosussetto** [comment]
@aminecmi yeah I noticed that too, not sure if it's because you're running it in sandbox mode (I hope so), or if you can do anything about it. Any input from @j3k0 would be much appreciated.

**Comment by aminecmi** [comment]
@fabiosussetto I think it's beacause of the "two" calls to refresh.
