### ISSUE TITLE
IOS transaction format

### ISSUE THREAD

**Issue by Alphatiger** [j3k0/cordova-plugin-purchase#234]
Hi i am getting product in approved state as follows Can any body confirm that this is correct, for subscription verification iap_verifier nom module is asking for reciept, does transactionid=reciept or it is different?
i am in sandbox mode
{
  "id": "xxxxxxxxx",
  "alias": "xxxxxxxxxxxxxxxx",
  "type": "paid subscription",
  "state": "initiated",
  "title": "parents edition",
  "description": "xxxxxxxxxxx",
  "price": "xxxxxx",
  "currency": null,
  "loaded": true,
  "canPurchase": false,
  "owned": false,
  "transaction": {
    "type": "ios-appstore",
    "id": "xxxxxxxxxxxx"
  },
  "valid": true,
  "transactions": [
    "xxxxxxxxxxxxxxxxxx",

  ]
}

**Comment by uareurapid** [comment]
A receipt is a base64 string

**Comment by Alphatiger** [comment]
@uareurapid  thanks but i am getting transaction data as  {"type":"ios-appstore","id":"1000000162211896"},"valid":true,
i am in sandbox mode, i believe in addition to above data i should receive transaction base6 string, please comment

**Comment by Alphatiger** [comment]
@j3k0  Jean,
After having no luck with this plugin directly, i started using ngStore kit.
There is a method which loads the transaction receipt if we pass the transaction id i am getting transaction reciept. Is there any equivalent in this plugin.

**Comment by LukePulverenti** [comment]
Will the transaction id change as the subscription charges new payments? If so, what about the original transaction id, is that available? According to this it looks like it should be:

https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html

**Comment by bdsimmons** [comment]
Is there any news on getting the original receipt back in a callback as well? For ios, the base64 string and android the full object of the original receipt.
