### ISSUE TITLE
IOS validator

### ISSUE THREAD

**Issue by Alphatiger** [j3k0/cordova-plugin-purchase#235]
Is there any validator for IOS which works, i am getting transaction data like this "type":"ios-appstore","id":"1000000150414167"}, when i use this id for remote receipt validation it is saying data malformed, please give me right pointers.

Other Details:
IOS purchase type: Auto subscription, Sandbox mode

**Comment by Alphatiger** [comment]
@kitsunde @masonicboom @j3k0  Any help Appreciated

**Comment by Pigsnuck** [comment]
Because it looks like you're not validating a receipt.  Where did you get that JSON from?
