### ISSUE TITLE
IOS In-app purchase giving store type as io-appstore and id only, 

### ISSUE THREAD

**Issue by Alphatiger** [j3k0/cordova-plugin-purchase#236]
IOS In-app purchase giving store type as io-appstore and id only, how to validate this and get the receipt information

**Comment by fabiosussetto** [comment]
On iOS you need to set up a validator callback (store.validator = function (product, callback) {...}, check the docs) . product.transaction in you validator callback contains the full receipt data.

**Comment by ozexpert** [comment]
https://github.com/Wizcorp/node-iap requires to send receipt which is described below
```
The receipt string passed may be either the base64 string that Apple really wants, or the decoded receipt as returned by the iOS SDK (in which case it will be automatically base64 serialized).
```
however, i get only the type as ios-appstore and transaction id. where can i find the receipt?

**Comment by ozexpert** [comment]
Ah... i solved it. 

You need to use 

````
store.validator = function(product, callback) {
    console.log(angular.toJson(product));
};

store.when("product").approved(function(product) {
    product.verify();
});
````

Try adding code like above. you'll get product.transaction.appStoreReceipt object, which can be used in node-iap plugin. any questions, feel free to ask me.
