### ISSUE TITLE
Unregister all callbacks for product id

### ISSUE THREAD

**Issue by yankustefan** [j3k0/cordova-plugin-purchase#237]
is it possible to unregister all callbacks for a specific product id at once with one call, or do I need to call .off() for each registered function?

**Comment by tehmaestro** [comment]
Hi. How did you do this in the end? I'm trying to do the same thing.

**Comment by yankustefan** [comment]
I do it manually for each callback.
Blow a sample (contains AngularJS syntax, but you should get what I mean).

```javascript

            function subscriptionApproved(product) {
                dpl_logRemote.debug("verify subscription", "dpl_storeVendorFct", { product: product, user_id: dpl_accountFct.getCurrentUid()});

                // Register Callbacks
                // Verified
                $window.store.once(product.id).verified(orderFinished);
                // Unverified
                $window.store.once(product.id).unverified(subscriptionUnverified);
                // Expired
                $window.store.once(product.id).expired(subscriptionExpired);

                // Verify Subscription
                product.verify();
            }

            function subscriptionCancelled(product) {
                dpl_logRemote.debug("order cancelled (PID)", "dpl_storeVendorFct", { product: product, user_id: dpl_accountFct.getCurrentUid()});
                
                // Unregister Callbacks
                // Approved
                $window.store.off(subscriptionApproved);
                // Verified
                $window.store.off(orderFinished);
                // Unverified
                $window.store.off(subscriptionUnverified);
                // Expired
                $window.store.off(subscriptionExpired);
            }
```

**Comment by tehmaestro** [comment]
Thanks. I ended up modifying the plugin a bit for my personal use case. I changed the `unregister` function, which takes a callback function as a parameter and removes it, to something like this:
```javascript
            unregister: function(cb) {
                var keep = function(o) {
                    return o.cb !== cb;
                };
                for (var i in this.byQuery) {
                    if(typeof cb == 'string') {
                        if(i.indexOf(cb) >= 0) {
                            delete this.byQuery[i];
                        }
                    } else {
                        this.byQuery[i] = this.byQuery[i].filter(keep);
                    }
                }
            }
```

 So what it does is, if the parameter is not a function, it is a string, it removes all the callbacks that the string matches.
  For example, lets say we have a product id : `productID`.
  
  When registering callbacks like `store.when('productID').approved() , store.when('productID').cancelled()` , `this.byQuery` will be populated with the following keys: `productID approved` , 'productID cancelled` .

  Using the function I modified, when calling `store.off('productID')` , all keys from `this.byQuery` that match productID are removed.

  Of course, this should probably be done through another function, something like `store.offProduct('productID')` , but this works for me for now.

**Comment by yankustefan** [comment]
Thank's for your answer!
Looks like a good approach.
Specially if done as a function like `store.offProduct('productID')`.
Maybe you want consider to contribute that back to the core plugin, if you have time and energy.

I will close this one, since it answers my question with a "no" (but with a great input - thanks!).
