### ISSUE TITLE
error 67770017 while doing inapp purchase in cordova android

### ISSUE THREAD

**Issue by Anirban123** [j3k0/cordova-plugin-purchase#238]
The thing is happening whenever i try to purchase the product I am getting this kind of error though all the other functionalities are working i.e my app is initiating properly, i can get a success response while doing query details but when i purchase after saying a succesfull purchase this error is showing

**Comment by aesculus** [comment]
For what its worth this is working for me in PGB using
<code>
<preference name="phonegap-version" value="cli-5.1.1" />
</code>

<code>
<gap:plugin name="cc.fovea.cordova.purchase" source="npm" version="3.11.0">
   <param name="BILLING_KEY" value="MIIB...QAB"/>
</gap:plugin>
</code>
