### ISSUE TITLE
ERROR 6777003: Trying to purchase a unknown product.

### ISSUE THREAD

**Issue by codearachnid** [j3k0/cordova-plugin-purchase#239]
I am testing this in xcode ios simulator. And get the following error when attempting to purchase the product. This is also occurring when I sent it for approval with apple as well.

[Log] [store.js] ERROR: ios -> ERROR 6777003: Trying to purchase a unknown product. - "com.chestercomix.comix.bostonteaparty"

In IAP portal the product is configured with the following settings
Reference Name: Boston's Tea Party
Product ID: com.chestercomix.comix.bostonteaparty
Type: Non-Consumable

in the code a hook for error triggers is wired up as follows:

```
store.error(function(error) {
            console.log(error);
            appFramework.addNotification({
                hold: 3000,
                title: 'In-App purchase error',
                message: 'IAP ERROR ' + error.code + ': ' + error.message,
            });
        });
```

then in the code it loops through a list of product configurations

```
if( store.products.length != IAP.list.length ){
        for(var i=0;i<IAP.list.length;i++){
            store.register({
               id:    IAP.list[i].id,
               alias: IAP.list[i].alias,
               type:   store.NON_CONSUMABLE
           });
        }
    }
```

there is also a hook to the `approved` trigger to listen for approved state and notify the application that the purchase was approved.

```
store.when("product").approved(function (order) {
            // console.log('product approved', order);
successfulPurchase( order );
            order.finish();
        });
```

What am I doing wrong?

**Comment by uareurapid** [comment]
maybe you didn´t registered the product??

**Comment by codearachnid** [comment]
when I query store.products it comes back with the list of products - I also occasionally get error 6777019 "Failed to restore purchases during refresh" so i'm not sure if they're related.

**Comment by RouR** [comment]
try to upload your app to store, install and run from store on device (testflight for apple). i`m not sure what simulator is supported

**Comment by codearachnid** [comment]
so the app is continued to be approved by apple but when I attempt the purchase in the live app it continues to throw error ERROR: ios -> ERROR 6777003: Trying to purchase a unknown product. It continues to successfully bill the user but the store will not refresh locally to show the product as being purchased. What am I missing in https://github.com/codearachnid/com.chestercomix.reader/blob/master/www/js/app.js ?

**Comment by codearachnid** [comment]
You can see this code live in https://itunes.apple.com/us/app/chester-comix/id936969492?mt=8

**Comment by greg84** [comment]
I have a similar problem. The app is live with one non-consumable product, which has been purchased successfully several times. A user has purchased the product using their iPad Mini, but they received `ERROR 6777003: Trying to purchase a unknown product`, and the same message when they try to restore it. However, if they restore the product on their iPhone, it works fine. Any ideas?

**Comment by kirillgroshkov** [comment]
I have similar problem with the test account

**Comment by brunosoune** [comment]
I have the same error: ERROR 6777003: Trying to purchase a unknown product.

I'm debugging the app in device... This occur when I performing store.order(productId)

**Comment by j3k0** [comment]
In-App-Purchase don't work in the XCode iOS simulator.

**Comment by uareurapid** [comment]
yep, not possible to test in-app on sim

**Comment by Masciuniria** [comment]
same error here

**Comment by ghonche-yqr** [comment]
Hey guys
any solution?

**Comment by sajjadalis** [comment]
The subscription was working fine for Google Playstore and now I'm getting this error. Not sure if it's because I subscribed too many times to debug the issues. Tried to change the product, still same error.
