### ISSUE TITLE
A Few Basic Questions

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#240]
I have an existing application I am converting over to an In App Purchase application. I want to give away the application for free and then charge for unlocking two features (access to parts of the application) after the user purchases them. The app will be both Android and iOS.

I cannot find the answer to these basic questions:
- When the user is offline do I just trap the 6777002 error code and hide all the in app purchase features?
- In the case above do I need to monitor the connection state and then call store.refresh() when the connection resumes
- For offline users is the purchase state cached anywhere or do I need to cache my own state (ie local storage) for each IAP feature in order to manage access to that feature when the user is not connected?

**Comment by aesculus** [comment]
Well in the absence of comments I went ahead and tried some things that work for me:
* I trap the 6777002 and just disable the purchase functions until the the store responds
* I am keeping the purchase state in a local variable so when the user is off line they can use the features.

**Comment by Pigsnuck** [comment]
Be careful about doing that. Hackers can easily crack the app if they figure out how to spoof the cached value.
