### ISSUE TITLE
Not getting Storekit loaded on Android, iOS works fine

### ISSUE THREAD

**Issue by ideadx** [j3k0/cordova-plugin-purchase#241]
Followed and read every line: https://fovea.cc/blog/index.php/3-steps-tutorial-for-phonegap-in-app-purchase-on-ios/ and on github page.

07-14 14:33:32.743    2462-2462/? I/chromium﹕ [INFO:CONSOLE(20434)] "ReferenceError: storekit is not defined
            at Object.service.IAP.buy (file:///android_asset/www/js/purchaseService.js:137:9)
            at Scope.$scope.inAppPurchase (file:///android_asset/www/js/profileController.js:42:29)

here is how how i am init:
   storekit.init({
            debug: true, // Enable IAP messages on the console
            ready: service.IAP.onReady,
            purchase: service.IAP.onPurchase,
            restore: service.IAP.onRestore,
            error: service.IAP.onError
        });

Is this plugin still works with Android fine? Is there any other way to init android differently? if so please add on documentation as this is getting really hard to add android support. Thx.

**Comment by aesculus** [comment]
Did you put your billing code for Play in the plugin?
