### ISSUE TITLE
Finishing transactions that failed verification

### ISSUE THREAD

**Issue by rcorrie** [j3k0/cordova-plugin-purchase#242]
We are using this plugin to sell consumable products and we're in the middle of the Apple review process and the apple tester tried to purchase a product, but the verification failed (our api server failed), hence the 'finish()' method was never called. Once we solved the backend api issue, we resubmitted. 

Now the tester is stuck in a state, in which, every time they open the app, they are prompted to enter their itunes password. Then once they proceed to purchase the same consumable product again, they get the prompt:

"This in-app purchase has already been bought. It will be restored for free."

Is there a method that we can call to restore the product? The research that I have done tells me that usually you get the "This in-app pur..." prompt when they are trying to purchase subscriptions, not consumables.

Right now, the only solution to this problem, is to explicitly call 'product.finish()' on init.

Is this intended functionality?

Thanks,
Ricardo

**Comment by fabiosussetto** [comment]
I have the same question, I fixed this by calling product.finish, but I wonder if that's the only way to deal with this scenario.

**Comment by Pigsnuck** [comment]
My understanding (confirmed during testing) is that the following happens:

1. Make a purchase with the validation server disabled.
2. Close the app.
3. Start the validation server.
4. Open the app.  store.refresh() is called.
5. The "approved" event will fire for the purchase that couldn't be validated in step 1.
6. You should call product.verify() to cause the plugin to try to validate the purchase with the server.
7. The server is running, and validates the purchase.
8. The "verified" event is fired by the plugin.
9. You can now call product.finish().

So you only call product.finish() if you have to.  If the validation server is down for any reason, the validation will happen automatically as soon as store.refresh() is called next time, so you don't need to worry about it. ;)

**Comment by Renzo04** [comment]
Hi, Any update on this? My question is... If the server validation fails (because connection error, google or ios server errors, incorrect token, magic bunny...), how can i change the product state back to VALID? This is my code:

```
store.when(subscription.id).approved(function(p) {
   alert("Store approved");
   verifyTransaction(p).then(function() {
       p.finish();
   }).catch(function(error) {
       alert(angular.toJson(error));
   });
});
function verifyTransaction(product) {
   var token;
   if (product.transaction.type == "ios-appstore") {
       token = product.transaction.appStoreReceipt;
   } else {
       token = product.transaction.purchaseToken;
   }
    return $http.post(validatorSubscriptionPurchaseUrl, {
        product_id: product.id,
        purchase_token: token
    });
}
```

**Comment by Renzo04** [comment]
I don't want an APPROVED product if verification fails...
