### ISSUE TITLE
REQUEST: Support Amazon In App Purchasing

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#244]
Sounds like it's very similar to the Android Play In App Purchasing with a few modifications. We would need to make sure we trap what the source of the app was (Amazon or Google) when we initialized the app after downloading.

**Comment by tbolesta** [comment]
Is Amazon support now?

**Comment by gylippus** [comment]
+1

**Comment by rubinchyk** [comment]
**+1 Unfortunately no one answered on this simple question....**

**Comment by darekrusin** [comment]
FYI, this has already been discussed at #97
