### ISSUE TITLE
Problem with store.validator ajax call

### ISSUE THREAD

**Issue by Daz66** [j3k0/cordova-plugin-purchase#245]
Hi,

I've been tearing my hair out with a problem where my server-side purchase validation script is failing. It seems no POST data is actually getting through to my script from the XMLHttpRequest() send in store-android.js  I have tested the script using my own jquery call here:
    $.ajax(
    {
        url:    store.validator, 
        method: 'POST', 
        data: { receipt:    <the receipt>, signature:    <the signature> },
        success: function(resp)     { alert("success: " + JSON.stringify(resp));  }, 
        error: function(status, message)  { alert("Error: " + status + ": " + message);  }
    });
and this works fine!

So my questions is: why does the XMLHttpRequest() POST request in your code fail and yet the jQuery equivalent works?

BTW: the server-side script is an Amazon AWS EC2 instance. I'm not sure if this is significant!

Thanks in advance for any pointers,
Daz

**Comment by bradrlaw** [comment]
I am running into the same issue, the remote validator gets called but no data is sent.  I have the plugin in debug mode and no errors / warnings are thrown.  It shows the receipt prior to the call even.

**Comment by nulleof** [comment]
Data is sending with "application/json" content type here. So you need to use in your php script:
`$data = file_get_contents('php://input');`
for getting post variables instead $_POST.
