### ISSUE TITLE
Phonegap Build: no building iOS app.

### ISSUE THREAD

**Issue by danielesalvatore** [j3k0/cordova-plugin-purchase#246]
Good morning everyone,

first of all i would like to thank you for the plugin. Secondly i would like to report that I keep receiving an error on iOS app compilation on Phonegap Build. The Android version is built fine.

The log says this:

`
The following build commands failed:
    CompileC build/MY_APP.build/Release-iphoneos/MY_APP.build/Objects-normal/armv7/InAppPurchase.o MY_APP/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
`

If i remove the plugin declaration (exactly the same you find in the README of the project, in both formats iOS+Android or only iOS) the iOS version builds fine too.

I know this could be related with the compilation process of Phonegap Build, but did you experience something like this?

Thank you very much for the support

**Comment by ivanthecrazy** [comment]
Got the same with Cordova. How did you remove the plugin declaration?

**Comment by danielefenix** [comment]
@ivanthecrazy Unfortunately I mean that if i do not declare the plugin in my config.xml file the build process ends successfully. I did it just to be sure that the issues comes from its inclusion. In case I find a solution for it I will write it here, please do the same.

**Comment by aesculus** [comment]
<p>For what its worth this is working for me in PGB using<br>
<code><br>
[preference name="phonegap-version" value="cli-5.1.1" /]<br>
</code></p>

<p><code><br>
[gap:plugin name="cc.fovea.cordova.purchase" source="npm" version="3.11.0"]<br>
   [param name="BILLING_KEY" value="MIIB...QAB"/]<br>
[/gap:plugin]<br>
</code></p>

**Comment by danielefenix** [comment]
@aesculus Thank you for your reply. I tried to change the configuration from 
`
<preference name="phonegap-version" value="3.7.0"/>
`
to
`
<preference name="phonegap-version" value="cli-5.1.1"/>
`

With this configuration iOS is compiling, but not Android.

As expected, specifying the PhoneGap Version as 3.7.0 both iOS and Android use the 3.7.0 version. If the values is set to 'cli-5.1.1' iOS uses 3.8.0 and Android 4.0.2.

Is the issue related to Version 4 of PhoneGap in your opinion?
Is there a way to set the PhoneGap Version explicitly for iOS and Android?

Android log:

`
debug:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 125 source files to /project/bin/classes
    [javac] /project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
    [javac]                     webView.evaluateJavascript(js, null);
    [javac]                            ^
    [javac]   symbol:   method evaluateJavascript(String,<null>)
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
    [javac]         webView.post(new Runnable(){
    [javac]                ^
    [javac]   symbol:   method post(<anonymous Runnable>)
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/org/apache/cordova/filetransfer/FileTransfer.java:692: error: cannot find symbol
    [javac]         if (!isLocalTransfer && !Config.isUrlWhiteListed(source)) {
    [javac]                                        ^
    [javac]   symbol:   method isUrlWhiteListed(String)
    [javac]   location: class Config
    [javac] /project/src/org/apache/cordova/inappbrowser/InAppBrowser.java:122: error: cannot find symbol
    [javac]                                 || Config.isUrlWhiteListed(url)) {
    [javac]                                          ^
    [javac]   symbol:   method isUrlWhiteListed(String)
    [javac]   location: class Config
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 errors

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 7 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/project/build.xml
`

**Comment by danielefenix** [comment]
I went back to name="phonegap-version" value="3.7.0" and it seems to work now...

**Comment by aesculus** [comment]
Note: Did you make sure that you had the source="npm" set on all Cordova plugins? Before I had the source set my Android was failing the compile too, especially on the InAppBrowser plugin.

See the example on this plugin statement above.

**Comment by danielefenix** [comment]
Yes, the parameter was in the statement as it is in the documentation example on the home page of the plugin.

**Comment by ivanthecrazy** [comment]
Got it to work! 
1. Update cordova to 5.1.1
2. Re-add iOS platform

**Comment by an-rohangovekar** [comment]
I am using cordova-plugin-purchase for my application, its working perfectly fine with android but giving big error log while building my iOS app in appgyver.

this is last part of error log ,

** BUILD FAILED **
The following build commands failed:
CompileC build/Release-iphoneos/Build/Intermediates/AppGyver.build/Release-iphoneos/Scanner\ RC.build/Objects-normal/armv7/InAppPurchase.o Plugins/cc.fovea.cordova.purchase/InAppPurchase.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by emmychen** [comment]
@an-rohangovekar I got the same error, did you fix it? How did you get pass this error?
