### ISSUE TITLE
Any working example with Ionic framework, angular way?

### ISSUE THREAD

**Issue by rklhui** [j3k0/cordova-plugin-purchase#247]
I know that the ionic framework should be compatible with most cordova plugin, and previously the v3.4.1 of this Purchase plugin could work with ionic, I wondered if there is any working example of this latest version of Purchase with Ionic? Thank you very much.

**Comment by cameronbourke** [comment]
Hey @rklhui, Ionic is just an angular framework, and so it the question you are asking doesn't make sense. The purchase plugin is written in javascript, so any hybrid application can use it. For all the api's check https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md
