### ISSUE TITLE
ERR_PURCHASE 6777002

### ISSUE THREAD

**Issue by mitiaptest** [j3k0/cordova-plugin-purchase#250]
Throwing error ERROR 6777002: Load Failed: Cannot connect to iTunes Store

**Comment by KingNLO** [comment]
The same issue from yesterday

**Comment by KingNLO** [comment]
Im not sure. Spent all day fro investigation but not idea.

**Comment by mitiaptest** [comment]
Same here yesterday there were problem with https://itunesconnect.apple.com as well now its working but throwing issue ERROR 6777002: Load Failed: Cannot connect to iTunes Store.

**Comment by mitiaptest** [comment]
What is you basic assumption behind it ?

**Comment by mitiaptest** [comment]
is your problem resolved ?

**Comment by t-nonque** [comment]
I have the same issue. I didnt find any way to fix it for now.

**Comment by mitiaptest** [comment]
its work for me now.

**Comment by t-nonque** [comment]
Did you have to change anything? Thanks

**Comment by mitiaptest** [comment]
are you trying with sandbox user ?

**Comment by mitiaptest** [comment]
Update your product from iTunes connect and try it again .

**Comment by t-nonque** [comment]
No i am in production :(

**Comment by t-nonque** [comment]
Ill run some test then come back here ^^

**Comment by praveen-vishnu-gp** [comment]
same issue,  not finding proper solution
