### ISSUE TITLE
Can't register new products after store.refresh() is called

### ISSUE THREAD

**Issue by uxder** [j3k0/cordova-plugin-purchase#254]
I have a dynamic list of product ID that can change (list pulled from server).

Therefore, when the use goes to the product purchase page, I register a list of product and then call store.refresh().  Later, when the user revisits this page and a new product is introduced and registered, reruning store.refresh(), does not update the new product.

Roughly it's something like:

```
store.register({ id: product1, alias: product1, type: store.NON_CONSUMABLE });
store.when(product1).updated(function(production) {
   // This gets called.
});
store.refresh();

store.register({ id: product2, alias: product2, type: store.NON_CONSUMABLE });
store.when(product2).updated(function(production) {
   // This never gets called.  How can I get this to update.
});
store.refresh();

```

**Comment by uxder** [comment]
Anyone?  It seems that once initialized and calling refresh, you can't add new products.  Any work around?

**Comment by AndresPF** [comment]
For what I understand you should register all products before calling store.refresh(); for the first time. If there is any update to your products and you wish to refresh manually, reuse store.refresh(); but any new products being registered will be ignored.

That been said, if your list of products are being changed dynamically, you could try and place that page into a different html, reload the page and then re-do your register products process but i'm not sure that it will actually work.

**Comment by uxder** [comment]
Thanks....The only solution I found was indeed to do a hard refresh of the html page.  I had to do a check to see if anything new was introduced and in that case, forced a reload.
