### ISSUE TITLE
Make BILLING_KEY optional?

### ISSUE THREAD

**Issue by dkarzon** [j3k0/cordova-plugin-purchase#256]
Can we make the BILLING_KEY parameter option on the android install?
It doesn't seem to play very nicely with the Visual Studio tools for Cordova.

Not too sure what else this will affect.

**Comment by aesculus** [comment]
How would you use IAB without the Billing_Key?  I accidentally compiled mine that way once and when I submitted to Google Play it pointed out I had IAB but no billing key so it rejected my binary.

**Comment by dkarzon** [comment]
I'm not saying I want to remove the parameter, just make it optional so the plugin will work with other external tools.
All the parameter actually does is modify `billing_key_param.xml` file to add a new string parameter which could be done through other methods that don't affect the build process.

**Comment by dkarzon** [comment]
@j3k0 Sorry, this change may have made it into master from the windows merge. What are your thoughts on it?

**Comment by j3k0** [comment]
Well if that's necessary then so be it.

I remember plugins like google maps have those kinds of parameters as well, how are they handled in Visual Studio? Maybe there's a way similar to PhoneGap Build where those parameters are passed in the config.xml ...?

**Comment by dkarzon** [comment]
@j3k0 Just tested modifying the config.xml file like you mentioned for phonegap build and that works. I'll fix up the parameter in plugin.xml for you and close this issue :+1:
