### ISSUE TITLE
Document windows support

### ISSUE THREAD

**Issue by j3k0** [j3k0/cordova-plugin-purchase#258]
Document how to setup on the windows platform (or link to android HOWTO when appropriate).

See README.md doc/windows.md wiki (https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup)

**Comment by j3k0** [comment]
@dkarzon I assigned that to you. If you know any good tutorial to link to or build some doc from?

**Comment by dkarzon** [comment]
@j3k0 Can do! What's the process for updating the plugin on `plugins.cordova.io`? would be great to get that updated with windows as a supported platform.

**Comment by j3k0** [comment]
The documentation shown on plugins.cordova.io is just the README.md file. It'll get updated when we publish the next version. I added some very initial notes about that already.

Once you tested windows support successfully on your use case, we can publish an update already (but clearly saying that windows support is still beta).

**Comment by rafaellop** [comment]
I can test Windows plugin on Windows X and Windows Phone Universal Platform. At the moment I'm only getting errors like this

`MOJ STORE ERROR 6777002: Loading product info failed - WinRTError: Unknown runtime error`

I have put the example XML to the www folder of my cordova app under the `in-app-purchase.xml` filename and added `store.inappbilling.setTestMode(true);` in my store initialization procedure. I've tried in the store.ready() and outside it. 

Rafal
