### ISSUE TITLE
In-App Purchases not available

### ISSUE THREAD

**Issue by saurabhgwb** [j3k0/cordova-plugin-purchase#260]
Hello. I have included the src, js and code inside index.html but when I am running the application it is giving me alert In-App Purchases not available. Please guide me in right direction.

**Comment by dkarzon** [comment]
Hi @saurabhgwb Can you please provide some more information for us.
Which platform(s)?
Can you give a sample of your code?
Have you setup the items in the respective stores like the docs say?
Can you screenshot the error message?

**Comment by saurabhgwb** [comment]
Hello @dkarzon . I am doing it on cordova android. I have setup all the products on google play. It is not able to find window.storekit. I am calling this on device ready condition. Can you please let me know how to have it successfully fulfill this condition?

Please download the code from here.

https://app.box.com/s/vd1jllr07xoq6a5z98nc8n5mgbx53rj9

Thanks for your help.

**Comment by Anirban123** [comment]
Hello saurabhgwb. The window.storekit is used for IOS not for android......... and whatever js that you have taken in order to work with the in app purchase is all for IOS.

**Comment by saurabhgwb** [comment]
Ok. I have changed it and now i am using android js and able to call InAppBillingPlugin.java but it is giving me this error : error refreshing inventory (querying prices of items).

Although i have put the public key at right places and checked that in InAppBillingPlugin.java, public key is available. Please guide me right direction.

**Comment by saurabhgwb** [comment]
Also please check the update code here : 

https://app.box.com/s/vd1jllr07xoq6a5z98nc8n5mgbx53rj9

Thanks

**Comment by saurabhgwb** [comment]
Hi Dkarzon,

Any update for us?

Thanks in advance.

**Comment by jreynerio** [comment]
Hi saurabhgwb, I have the same problem, do you fix this and it works for you ?

Thanks

**Comment by saurabhgwb** [comment]
No, We are still working on it.

On Thu, Aug 20, 2015 at 2:00 AM, jreynerio <notifications@github.com> wrote:

> Hi saurabhgwb, I have the same problem, do you fix this and it works for
> you ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/260#issuecomment-132772357>
> .
>



-- 

Regards
Saurabh Chhajed | COO | Skype - gowebbaby | 718-717-8666
