### ISSUE TITLE
owned state / subscriptions persistent or not?

### ISSUE THREAD

**Issue by 1b0t** [j3k0/cordova-plugin-purchase#265]
First of all thanks for this awesome plugin. I'm liking it a lot. :)

I've a question about paid subscriptions and the owned state after a purchase has been verifed and finished. 
On iOS it is persistent across app restarts and even set to true if there's no network connectivity.
On Android it gets reset to false every time and it only updates back to true once it has verified the purchase with the server again.
I was just wondering if this is a bug? What is the expected behaviour?

**Comment by viktorstaikov** [comment]
I have the same problem, mate... :(

**Comment by cciszak** [comment]
Exactly the same problem, seems like a bug and I am surprised that nobody even clarified if this is as designed or a bug. If it's as designed could somebody explain the reason behind this?

This process is even repeat for purchases that were cancelled in the Merchant account. If the app goes to Approved and Verify every time it opens we will be providing additional features every time a user opens the app...
