### ISSUE TITLE
get purchases

### ISSUE THREAD

**Issue by prabinyovan** [j3k0/cordova-plugin-purchase#267]
Thanks for this awesome plugin. It works well as expected. 

But I am not sure How do I get the products/subscriptions I have purchased/subscribed ??

**Comment by codearachnid** [comment]
This also seems to be causing me trouble - once purchased it never refreshes/callsback to unlock the content. On subsequent runs of the application the product is still not shown as purchased while apple's console shows money received for the purchases.

**Comment by aesculus** [comment]
Try store.refresh() again after your app is all settled down

**Comment by codearachnid** [comment]
I am using `store.refresh()` after the products are registered on each app load. Shall I call it more than once?

**Comment by aesculus** [comment]
Yes. The first time it does not pick up the state correctly. After your page is fully loaded call it again or call it as a action of your restore button.

**Comment by prabinyovan** [comment]
This doesn't seems to be working. I dont see any changes in the product details after calling store.refresh() after order finished.

**Comment by codearachnid** [comment]
I've added `store.refresh()` to several additional places in my app as well and it doesn't seem to be affecting. I can see where the user has purchased it in apple's control panel but it's not updating on refresh apparently.

**Comment by codearachnid** [comment]
You can see my source code running the refresh here https://github.com/codearachnid/com.chestercomix.reader/blob/master/www/js/app.js

**Comment by prabinyovan** [comment]
@codearachnid Thanks. I will look into it.

 I can get product details by calling store.get("product1");

Just wanted to know which object of the product will have the information of whether it is purchased or nor?

**Comment by codearachnid** [comment]
@prabinyovan so don't use my code as an example of working functionality. I too am running into issues with the status of the product not being updated to being owned. The core of my code relies on the updated callback to fire and update the data model

`
store.when("product").updated(function(){
                 var newManifest = [];
                 $.each(vmComixManifest.manifest(), function( key, comix ){
                     var product = store.get( comix.iap() );
                     newManifest[key] = comix;
                     if( product.owned ){
                         newManifest[key].owned( 'true' );
                     }
                     if( vmComixManifest.manifest().length-1 === key ){
                         vmComixManifest.manifest(newManifest);
                     }
                 });
             });
`

**Comment by prabinyovan** [comment]
Actually, it was my fault, I was looking for the status of consumable subscription which will be valid for one time. I got the status of it immediately after the purchase by calling store.get("product_id");

Later I added an auto-renewable subscription and I had to get it's status on every call whenever I call store.get method. The property owned was set to true once I purchased.

**Comment by kjakub** [comment]
I am looking into this plugin first time, i am bit lost. Can you guys help me ? I also need get previous purchases for the user .
