### ISSUE TITLE
In app Purchase Auto Renewable -> Tracking Transactions 

### ISSUE THREAD

**Issue by padmajashukla** [j3k0/cordova-plugin-purchase#271]
I have a problem in understanding the purchase.
When user clicks on buy , we get a confirmation that product is subscribed,
Now, how do we get the status of transaction . transaction id.
Is it anywhere listed what all callbacks will be required and if it is a callback how do we relate that this transaction was for this app id only ..
Can anyone please explain the process after a auto renewable product is subscribed,
I am not able to track the subscriptions after buying. 
It is urgent ..

**Comment by prabinyovan** [comment]
you can get the status of the product by calling store.get("product_id");
