### ISSUE TITLE
iOS - can't order a product without calling store.refresh() first

### ISSUE THREAD

**Issue by sfeast** [j3k0/cordova-plugin-purchase#273]
I'm not 100% certain about that statement, but I haven't found an obvious way to do it. Issue is that blindly calling store.refresh often results in Apple's sign in dialog popping up, which I'm concerned may be a bit off putting to users who are not actively trying to make a purchase. I get that it's needed to pull product info from Apple, but there are cases where we can get by w/out needing this info.

So first this is just a question - is there a way to order a product on iOS w/out first calling store.refresh()?

**Comment by Daniial** [comment]
I am using store.refresh() on load and I am not being prompted to login to apple until I make the store.order call.

One work around for you might be to call store.refresh when the user opens the shop window. You could setup a Boolean to make sure it's only ever called once.

**Comment by sfeast** [comment]
@Daniial that's interesting, perhaps this is because I'm in sandbox mode for testing. Are you not seeing the prompt with store.refresh() in both sandbox & production?

Thanks for the suggestion, that is an option.

**Comment by sfeast** [comment]
Ok this looks like it's just during development. In production now & not seeing the sign in dialog popping up anymore, until the user actually tries to buy something.
