### ISSUE TITLE
Expired/Cancelled subscriptions require the use to login after store.refresh() on iOS

### ISSUE THREAD

**Issue by Dolemite1347** [j3k0/cordova-plugin-purchase#275]
If the user's subscription expires and the user cancels their subscription, the iTunes login prompt is presented. The subscription remains active and content is visible until the user logs in. If the user logs in the content is then hidden. How can I hide the content without having the login prompt appear as the subscription is already expired and our verification service is returning that it is a expired subscription as well?

**Comment by headshota** [comment]
Have the same issue, after returning `store.PURCHASE_EXPIRED` from validator for Non-renewing subscription, the login prompt is presented. If I click `Cancel` the user stays subscribed.
