### ISSUE TITLE
Calling store.refresh() twice does not seem to restore "non-consumable" purchase on iOS

### ISSUE THREAD

**Issue by okeyto** [j3k0/cordova-plugin-purchase#279]
I am experiencing this issue and calling sore.refresh() a second time from a "Restore Purchases" button does not seem to work for me (for a non-consumable). This is on iOS.

I registered all required callbacks including "updated" (per product). All the events fire on first call to sore.refresh() but none is called on the second call. Although, the second call causes the phone to prompt for "Sign In to iTunes Store" dialog. But signing-in does not seem to do anything.

Do I need to update the inapp purchase plugin, maybe?

I am currently running ver 3.11.0, downloaded with "cordova plugin add https://github.com/j3k0/cordova-plugin-purchase.git"

Any help appreciated.

**Comment by gfragioud** [comment]
Every view is different document, so be sure that you call store.refresh() from the same view you initialized and  now "lives" the store object...

**Comment by okeyto** [comment]
@gfragioud thanks.

I found the problem.  I was not handling the "approved" properly during the second call to store.refresh().  All is now working fine after I added the below event and called product.finish() in the listener function "approveFn".

store.once("product").approved(approveFn);
