### ISSUE TITLE
Non Renewing Subscription

### ISSUE THREAD

**Issue by padmajashukla** [j3k0/cordova-plugin-purchase#282]
Please confirm, if we need to set type to Paid Subscriptions for Non Renewing Subscriptions and
2)  Where do we set the Expiry date for non  renewing Subscriptions.

**Comment by cykra** [comment]
For iOS atleast, I believe you have to handle this yourself serverside.

**Comment by j3k0** [comment]
Non renewing subscriptions have to be handled manually.

The plugin non-renewing subscription support has been cleaned up in newly released version 6.0, for both iOS and Android. I created a [helper library for apps that just need non-renewing subscriptions](https://github.com/j3k0/cordova-non-renewing-subscription). Feel free to take a look, to use it or see how it's implemented for reference.
