### ISSUE TITLE
Sandbox user Sign out Itunes Connect and account switch

### ISSUE THREAD

**Issue by danielefenix** [j3k0/cordova-plugin-purchase#283]
Good morning,

i successfully installed and used this amazing plugin to implement IAP in my app. As suggested in the tutorial, I used a sand box user in order to test the IAP during the development process in iOS, but i can not find a way to switch back to my personal account.

At the start of the development process, i signed out with my personal account, i didn't login with my sandbox user in General > iTunes & App Store, i started the application and i logged in with my sandbox user from that.

It is time now to pass to production and i can not figure out how to logout the sand box user from my app. 
If i start the application a Sign In popup is displayed and the sandbox email is there. It simply ask for the password but now chance to change the account. When i login within the application the sandbox user account is logged in General > iTunes  & App Store, but if i log out from there the application is stuck with the sandbox email. In other words, it is like if the app is now linked to that email account and it does not give me the chance to change it.

I tried to remove the application (tapping on it and pressing the X button and from General > Manage storage), install it again, to soft reset the iPhone, log out from iTunes & App Store, rebuild the application in debug mode or not, including the plugin or not, in many combination but with no success.

Does anybody experienced something like this? How did you logout your sandbox user when you switched back to your personal iTunes Connect account?

thank you for your support.

**Comment by danielefenix** [comment]
Just for future reference: the only thing that worked was to restore the iPhone.

**Comment by rajington** [comment]
I'm having the same issue, might be worth reopening.

**Comment by brandonbt2** [comment]
Also having this issue!
