### ISSUE TITLE
Product ID in register()

### ISSUE THREAD

**Issue by gfragioud** [j3k0/cordova-plugin-purchase#285]
You mention to not add package name in product's id:

store.register({
     id:    'nonconsumablehosted1', // id without package name!
     alias: 'hosted content download',
     type:   store.NON_CONSUMABLE
 });

But if I register my products in this way and then I try to order any of them, they are invalid.
Instead if I register them with package name (com.company.application.id) it works...

Why is this happening to my system?
Thanks in advance!

**Comment by drago-aca** [comment]
Hi,

This is problem on line 285 file index.js (full demo)
var elId = p.id.split(".")[3];

If you don't use id like com.myapp.test.order1 change it to:
var elId = p.id;

**Comment by gfragioud** [comment]
OK thank you!
