### ISSUE TITLE
product.finish() does not set state='FINISHED'

### ISSUE THREAD

**Issue by danielesalvatore** [j3k0/cordova-plugin-purchase#288]
I am experiencing the following problem: even if I call the product.finish() method, the product's state is not set to 'FINISHED'. This makes the plugin to invoke several time the approved's callback even if not necessaire. 

I am running on an iOS device (iPhone 5 iOS 9)
The application is built with PGB
I am using a sandbox user
The application is not published yet
Plugin version 3.11.0
The product's registration process is working
The purchase is working, I receive the Success alert.
In order to finish a product I use the following code:

```
store.when("product").approved(function (p) {
    console.log("---------------------------------- approved " + p.id + " " + p.state)
    p.finish();
    console.log("---------------------------------- finished " + p.id + " " + p.state)
```

but both the logs shows that the state='APPROVED'

Do you have any clue about why is this happening? Could this come from the fact I use a sandbox user? 

Thank you for your support.

**Comment by mstrop** [comment]
Hi, do you have a solution for this? I have exactly the same problem.

**Comment by gsfioravanti** [comment]
Has anyone determined if this is just a sandbox problem?  Because I am seeing the same behavior.

**Comment by mstrop** [comment]
Unfortunately not yet .... It looks like I'll have to spend some real money on this buying my own product.

**Comment by stevecarlton** [comment]
Ahh, seeing this as well from the sandbox, anyone verify yet if this just applies to the sandbox?

**Comment by stevecarlton** [comment]
Seeing this as well in the sandbox, seems like if this is the case then it should be documented.
