### ISSUE TITLE
Purchases are not "owned" after app restart [Android]

### ISSUE THREAD

**Issue by viktorstaikov** [j3k0/cordova-plugin-purchase#295]
Hi guys,

My case is like this: I have an app that offers subscriptions for extra functionality. The problem is that after a subscription is purchased (__successfully__), the app works as expected, but when the app is closed and started again - it looks like nothing was purchased and when I try to buy it again, I get "You have already bought this item." from Google Play. As I check my Google Play account I can see the active subscription.

I'm using Cordova 4.0 and latest version of the plugin.

After some debuging it turned out that the state of the subscription is __approved__ and not __owned__, as expected. __owned__ property is _false_. __transaction__ property is populated with the coresponding data. __canPurchase__ is false.

So... What can be causing this anomaly or where can I look for the "troublemaker"?

**Comment by j3k0** [comment]
Hey viktor,

Your code is responsible for having the purchase go from "approved" to "owned". This allows your app to perform validation of the purchase each time it starts.

You should have something like:

```js
store.when("my_product").approved(function(p) {
    // no validation, just confirm the purchase.
    p.finish();
});
```

This will be called each time your app starts for all purchases, allowing you to check if they're expired, fake or whatever (if you want to do those checks).

-JC

**Comment by viktorstaikov** [comment]
Thanks,

I have reviewed my code and adjust it to your comment and now it is okay.

Thanks :smiley:
