### ISSUE TITLE
ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Billing service failed to initialize. (response: 6:Error)

### ISSUE THREAD

**Issue by shman2000** [j3k0/cordova-plugin-purchase#300]
Hi, 

do you have any idea how to fix it? Plugin seems to be set up correctly, but communication with the store doesn't work.

09-30 20:18:08.206    5602-5602/com.gamelegance.game I/chromium﹕ [INFO:CONSOLE(412)] "refresh", source: file:///android_asset/www/js/index.js (412)
09-30 20:18:08.207    5602-5602/com.gamelegance.game I/chromium﹕ [INFO:CONSOLE(460)] "[store.js] DEBUG: store.trigger -> triggering action refreshed", source: file:///android_asset/www/plugins/cc.fovea.cordova.purchase/www/store-android.js (460)
09-30 20:18:08.207    5602-5602/com.gamelegance.game I/chromium﹕ [INFO:CONSOLE(460)] "[store.js] DEBUG: queries !! 'refreshed'", source: file:///android_asset/www/plugins/cc.fovea.cordova.purchase/www/store-android.js (460)
09-30 20:18:08.207    5602-5602/com.gamelegance.game I/chromium﹕ [INFO:CONSOLE(735)] "InAppBilling[js]: setup ok", source: file:///android_asset/www/plugins/cc.fovea.cordova.purchase/www/store-android.js (735)
    --------- beginning of system

09-30 20:18:54.325    5602-5602/com.gamelegance.game I/chromium﹕ [INFO:CONSOLE(412)] "ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Billing service failed to initialize. (response: 6:Error)", source: file:///android_asset/www/js/index.js (412)

**Comment by natsu90** [comment]
I've kind of similar error, `ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying prices of items). (response: 6:Error) `. This happen to me sometimes, and it's because of unstable internet connection. So what I do is, re-trigger the refresh when the init failed;

````
store.error(store.ERR_SETUP, function() {
   store.trigger("refreshed");
 });
````

You might want to limit the refresh attempt if your app is offline, or put a refresh button instead.

**Comment by braianj** [comment]
Any solution on this? The trigger one doesn't work in my case

**Comment by claudioviola** [comment]
I've a same problem. Anyone has find out a solution?

**Comment by claudioviola** [comment]
Ok works! 
1 close all apps
1 clear data from Google Play Store App
2 open  Google Play Store: configure account
3 open cordova apps

**Comment by Alveoli** [comment]
I'm encountering the `ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying prices of items). (response: 6:Error)` on about 5% of my Android users. 

Anybody experiencing something similar? Found any solutions?

**Comment by aesculus** [comment]
This has cropped up again. Anyone with an answer to this recently?

**Comment by remisture** [comment]
This happens to me as well when running `ionic run android` on a real device.

> ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying prices of items).

**Comment by jeanpoelie** [comment]
anyone? I keep running into this issue...

**Comment by mukeshkush** [comment]
I have done with purchasing an item but clicking on same button >> 
Facing the issue : **In-app billing error: Unable to buy item, Error response: 7:Item Already Owned**
How can i start with In app purchase in ionic?

**Comment by ErxrilOwl** [comment]
Same problem. Any news for this issue?

**Comment by aesculus** [comment]
I see this problem again now. "Billing service failed to initialize"

Is it possible this occurs if the user has intermittent connection?

**Comment by vtambourine** [comment]
As @claudioviola mentioned, in my case clearing all data from Google Play Store and Google Play services (in Settings menu) helped to get out from polluted state.

**Comment by nishanth930** [comment]
any progress.??
