### ISSUE TITLE
iOS 9 - Cannot finish transaction

### ISSUE THREAD

**Issue by csheppard** [j3k0/cordova-plugin-purchase#303]
I'm using sandbox and getting **Cannot finish transaction** logged whenever I make a purchase and restore purchases.

I've spent all day on the problem and added some more logging to finishTransaction in InAppPurchase.m to try and figure out what's going on:

```
- (void) finishTransaction: (CDVInvokedUrlCommand*)command
{
    CDVPluginResult* pluginResult;
    NSString *identifier = (NSString*)[command.arguments objectAtIndex:0];
    SKPaymentTransaction *transaction = nil;
    
    DLog(@"command.arguments %@.", command.arguments);
    DLog(@"identifier %@.", identifier);

    if (identifier) {
        transaction = (SKPaymentTransaction*)[unfinishedTransactions objectForKey:identifier];
    }
    
    DLog(@"unfinishedTransactions %@.", unfinishedTransactions);
    DLog(@"transaction %@.", transaction);

    if (transaction) {
        DLog(@"Transaction %@ finished.", identifier);
        [[SKPaymentQueue defaultQueue] finishTransaction:transaction];
        [unfinishedTransactions removeObjectForKey:identifier];
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
        [self transactionFinished:transaction];
    }
    else {
        DLog(@"Cannot finish transaction %@.", identifier);
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Cannot finish transaction"];
    }
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}
```

Here is the result:
```
2015-10-05 16:37:54.437 APP[341:20432] InAppPurchase[objc]: command.arguments (
    1000000174471854
).
2015-10-05 16:37:54.437 APP[341:20432] InAppPurchase[objc]: identifier 1000000174471854.
2015-10-05 16:37:54.437 APP[341:20432] InAppPurchase[objc]: unfinishedTransactions {
    "" = "<SKPaymentTransaction: 0x17e58c00>";
}.
2015-10-05 16:37:54.438 APP[341:20432] InAppPurchase[objc]: transaction (null).
2015-10-05 16:37:54.438 APP[341:20432] InAppPurchase[objc]: Cannot finish transaction 1000000174471854.
```

I don't know Objective C but I'm guessing the transaction in unfinishedTransactions is being stored without a key here?

Appreciate any help.

Thanks!

**Comment by webbprofessor** [comment]
Was this working in a prior iOS version? You're making me nervous about pushing IAP to production...

**Comment by csheppard** [comment]
I believe so, we're not in production yet, still testing. I have no real useful info to give at the moment sorry.

**Comment by csheppard** [comment]
I've solved the problem (that I was having at least).

It seems iOS always thought my consumable had downloads to process which it doesn't, transaction.downloads is always true.

I changed the line at https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L502

to:
```
        if(downloads && downloads.count){
```

Now my purchases can finish after verification.

**Comment by optikalefx** [comment]
Please update your cordova plugin to include this. Right now we have to use the GIT URL.

**Comment by anonrig** [comment]
@j3k0 please update your cordova plugin.

**Comment by anonrig** [comment]
@saniyusuf you should see this.

**Comment by guopengliang** [comment]
Thank you for sharing this @csheppard. You save my day!
I have been experiencing the nightmare of unfinished transactions that leads to constantly asking me to login to my Apple ID. And I cannot make any new In-App purchases. Same symptom as described in #339.
After applying this patch, now the transactions can finish normally.

**Comment by mike623** [comment]
is there any solution to to fix problem without update plugin ? My app already promoted to production and launched

**Comment by saniyusuf** [comment]
The latest version 4.0 of the plugin fixes this


[image: photo]
*Sani Yusuf*
Founder, Haibrid LTD
w:http://www.haibrid.com
<http://github.com/saniyusuf>
<http://stackoverflow.com/users/1714088/sani-yusuf>
<http://about.me/saniyusuf>
<http://linkedin.com/in/saniyusuf> <https://twitter.com/saniyusuf>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=>

On 28 January 2016 at 12:46, 404 Not Found <notifications@github.com> wrote:

> is there any solution to to fix problem without update plugin ? My app
> already promoted to production and launched
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/303#issuecomment-176139644>
> .
>



-- 
Kind Regards
[image: photo]
*Sani Yusuf*
Founder Of Haibrid
<http://github.com/saniyusuf>
<http://stackoverflow.com/users/1714088/sani-yusuf>
<http://about.me/saniyusuf>
<http://linkedin.com/in/saniyusuf> <https://twitter.com/saniyusuf>
Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by mike623** [comment]
I am ready 4.0
