### ISSUE TITLE
Marking non renewing subscription as expired

### ISSUE THREAD

**Issue by voneddy** [j3k0/cordova-plugin-purchase#305]
Hey,

Sorry to be posting up and issue, I normally can find answers without do this...

Ive searched through every relevant thread i can find here and can't find an answer to marking non renewing subscriptions expired so the user can re-purchase them...

Ive got products listing and purchasing the first time fine, then can return product expired code from the validator off the in_app.original_purchase_date_ms field which then marks the product as canPurchase = true, and owned = false, but how then do i mark the purchase as expired to enable repurchase? 

Everytime I go to repurchase the 'This In-App purchase has already been brought. It will be restored for free' dialog appears....

Great plug in otherwise, if i can just sort this it's ready to roll out!!

Cheers mate
Ed

**Comment by voneddy** [comment]
Hey mate, I'm no objective C coder but think line 501 in inAppPurchase.m.paymentQueue() should be

if((NSInteger)[downloads count] > 0){
not 
if(downloads){

as downloads will always exist so the transaction will never be put in the unfinished transaction list...

Seems to have fixed the '...restored for free...' dialog, looks like the transactions was never being finished...

**Comment by j3k0** [comment]
Hey @voneddy 
Indeed, fixed a couple hours ago. See #303

**Comment by voneddy** [comment]
beat me to it! lol
