### ISSUE TITLE
All products remain APPROVED after restart

### ISSUE THREAD

**Issue by kjakub** [j3k0/cordova-plugin-purchase#311]
```
store.when("product").updated(function(p) {
    if(p.loaded && p.valid && p.state === store.APPROVED){
      p.finish();
    }

    if(p.loaded && p.valid && p.state === store.OWNED){
      console.log('OWNED',p)
    }

});
```

 I am calling finish() on each product, then i get OWNED state, but everytime i restart app, all products remains APPROVED only

**Comment by aesculus** [comment]
After your app settles down call store.refresh() again

**Comment by dvcroft** [comment]
I'm having the same problem. Calling refresh again starts the product life cycle again.

**Comment by paulojoao** [comment]
This happens to me too, when I call the store.refresh method will refresh the product to the correct state. but this can take a long time and makes many calls on my validation server (one for each transaction) and there is no promise or event that warns me that the verification of all the products has been completed.
