### ISSUE TITLE
How do I call consumePurchase and getPurchases request ?

### ISSUE THREAD

**Issue by kjakub** [j3k0/cordova-plugin-purchase#312]

**Comment by kjakub** [comment]
title fix

**Comment by arenddeboer** [comment]
I don't think you call consumePurchase yourself. It is automatically called (for consumable products)  when finishing an order.
Buy product, after the "approved" event verify/validate purchase on your server (or use the paid validation service provided here), then if verified, call order.finish() this will consume the product.
At least this is what i distill from the docs,source and experience.

**Comment by kjakub** [comment]
@arenddeboer Thank you for answer. Do you know when user is actually billed from store ? Before "approved" ? Or after "finished" event ? 

BTW don't you know what is going in iOS ?  https://github.com/j3k0/cordova-plugin-purchase/issues/331

**Comment by arenddeboer** [comment]
I expect after finished event.
Not yet working on the iOS version of my app, fingers crossed.
