### ISSUE TITLE
Login keeps coming back...

### ISSUE THREAD

**Issue by anykeysolutions** [j3k0/cordova-plugin-purchase#315]
I use the plugin on a special purchase page. As soon as the user hits this page and store.refresh is called, the login for the app stores appears, which is fine. But if I go back to any other page, which doesn't use the plugin, hit the home button and go back to the app, the login appears again.

This behaviour doesn't stop. If I visited the purchase page once, every time I hit the home button and go back to the app, the login shows again. It can only be stopped if I close the application completly, If I reenter it, the problem is gone. Also, if I don't visit the purchase page, everything is fine.

But as soon as store.refresh is called, the problem exists again. I made sure, that I don't call store.refresh multiple times, I only call it once.

It looks like the app has to check something with the store every time I go back to the app. But I can't figure out, what the problem is and why it's calling the login every time.

Any suggestions?

**Comment by rotoxl** [comment]
Hi, 

same problem here. I have also used several sandbox users and everytime I get to the purchase screen it begins to ask for the password of those sandbox users

**Comment by Neh3maH** [comment]
Hi, Same problem here.

**Comment by saniyusuf** [comment]
same here any ideas what is wrong

**Comment by saniyusuf** [comment]
aapraently this is correct behaviour when you use a different account to buy the product from the one that is on the phone itslef

**Comment by Neh3maH** [comment]
Seriously, thanks a lot !
So it would be because I use the sandbox users instead of the real user of the phone ?

**Comment by saniyusuf** [comment]
based on my information that is correct. If you use a differnt user from the one the phone is tied to this will happen anytime you are about to use an app that calls that refresh which makes sense.

**Comment by saniyusuf** [comment]
@Neh3maH I have tested this theory and it does not seem to solve the issue. Can anyone confirm they have a fix and this is not a bug

**Comment by saniyusuf** [comment]
Hi Guys please use this link to the branch provided in this comment where there is  a fix. You might have to delte your app completely from the phone and sign out restart you phone and even remove and re add the IOS project then run again after putting the fix. https://github.com/d3orn/cordova-plugin-purchase/tree/transactionFix

**Comment by rotoxl** [comment]
Hi @saniyusuf,

gonna give it a try. It would be great news to have it working

**Comment by saniyusuf** [comment]
@rotoxl you might have to restore your phone for this to work like I had to on my test device.

**Comment by bwalsh** [comment]
Tried this, but did not work. @saniyusuf  exactly what steps did you take to get this to work?

**Comment by saniyusuf** [comment]
@bwalsh restore your test iphone then install the app

**Comment by bwalsh** [comment]
@saniyusuf  thank you.  what do you mean by: "restore your test iphone"

**Comment by saniyusuf** [comment]
like restor it form settings. There is a cache problem you can get rid of this by trying soo many times or just storing your iphone like fatcory reset @bwalsh

**Comment by enricodeleo** [comment]
I reset to factory then restored my iPhone backup and I'm having the same behavior. 
It is impossible to work because everytime I open the app products are flagged as bought (even if I click on cancel on the login prompt) and sometimes the login request pops randomly even when I'm on other apps.
Is it possible to reset all the logins and pending transactions at once ?

**Comment by bwalsh** [comment]
Any news on fix &/or workaround?  Any definitive word if it affects released apps?

**Comment by saniyusuf** [comment]
Fix is availablein v 4 of the plugin

**Comment by optikalefx** [comment]
I don't think this is fixed, My users still get asked for password randomly throughout app use

**Comment by glennsjostrom** [comment]
@optikalefx Your users? In production or testflight users?

**Comment by optikalefx** [comment]
Right now, testflight users. But it's hard for me to trust it in prod. You know?

**Comment by glennsjostrom** [comment]
Okey, thats "positive" I guess. No, I don't know. Just hoping it will work well in production.

**Comment by priyag676** [comment]
Hi,
The issue mentioned above is also replicated on ionic app i.e. live on itunes app store, I am the using the previous version of the plugin.
https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/138

**Comment by Dexus** [comment]
I can only reproduce it when I have my phone with multiple sandbox accounts and/or live accounts and buyed with different accounts the products. I think it has a reason why apple prefer to use a own test device.
