### ISSUE TITLE
[iOS] Products show up as invalid

### ISSUE THREAD

**Issue by axtscz** [j3k0/cordova-plugin-purchase#316]
Whenever I try to add a product to the store using the plugin on iOS, it returns with a "Product Invalid" message.

The product has been added to the app in iTunes Connect:
![image](https://cloud.githubusercontent.com/assets/2145941/10490414/8b098b98-7266-11e5-9d75-703b0f5ee315.png)

The code is as follows:

    store.register({
                id: "Upgrade",
                alias: "full version",
                type: store.NON_CONSUMABLE
            });

The error message I get:
![screen shot 2015-10-14 at 11 30 14 am](https://cloud.githubusercontent.com/assets/2145941/10490499/097cd3ae-7267-11e5-9b3a-18b6c72c8d0f.png)

Curiously, the Android version works flawlessly

**Comment by sirius2013** [comment]
Is this working now?

**Comment by Ziv-Barber** [comment]
Same here. I think that we must send the app one time to Apple to be able to use the store.

**Comment by RezaRahmati** [comment]
Same problem for me, do we require to send app for review before testing?
based on this link we don't [https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/Introduction.html#//apple_ref/doc/uid/TP40013727-CH1-SW1](url)

If somebody has the solution please add it here

**Comment by j3k0** [comment]
No need. Make sure to check the FAQ on the wiki, full checklist there

**Comment by Ziv-Barber** [comment]
The short answer is:
You can test with a test account on the sandbox before submitting to review or you can submit to review without publishing to the store and test with NON-TEST account.
Also make sure that Apple approved all the bank account / tax / etc documents or else even if you can add a product you still can't test it!

The long answer:
The first time you can add only one product.
To be able to add a product you must send to Apple documents about your company and the bank account, tax numbers, etc. After sending some of them you may be able to add a product but it'll not work until that Apple will be happy with all the documents!
After adding the first product you MUST send it to review to be able to add more products BUT you can test it first in the sandbox using test flight.
After that Apple approve one product then you can add more.
Remember that any Apple ID that you set as tester in test flight will run inside the sandbox while other Apple IDs will run outside of the sandbox. It's the same also for other things, like Push Notification.
After that Apple will approve the first product then you can add more and send them to review separately.

I hope that it'll help anyone.

**Comment by RezaRahmati** [comment]
@Ziv-Barber  Thanks for descriptive answer, based on your answer my case is Apple approved contract for paid applications :)

**Comment by j3k0** [comment]
Closing. All possible issues I know of are listed here:
https://github.com/j3k0/cordova-plugin-purchase/wiki/F.A.Q.#products-wont-load-invalid-product-id
