### ISSUE TITLE
android not working with build.phonegap.com

### ISSUE THREAD

**Issue by ghost** [j3k0/cordova-plugin-purchase#318]
Thanks so much to all the contributors on this pluggin.  I hope someone can fix this one little problem:

Tried this first using build.phonegap.com:

 &lt;gap:plugin name="cc.fovea.cordova.purchase" source="npm"&gt;
       &lt;param name="BILLING_KEY" value="My Key..."/&gt;
&lt;gap:plugin&gt;

Didn't work. (BTW: It did work for iOS)

Tried this second (to build locally):

cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="My Key"

Didn't work.

Tried this third:

phonegap plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="My Key"

That worked.

The best case scenario is it works all three ways. The next best is it works on build.phonegap.com, like it does for iOS. I prefer to use build.phonegap.com for all my production builds.

UPDATE:  After writing this down and then proof reading I realized I could try one more thing:

Tried this fourth:

 &lt;gap:plugin name="cc.fovea.cordova.purchase" &gt;
       &lt;param name="BILLING_KEY" value="My Key..."/&gt;
&lt;gap:plugin&gt;

It worked on build.phonegap.com!

I took off the "source='npm" and that switched it to reference the phonegap plugin repository instead of the npm plugin repository.  Still, this may be an issue pretty soon because there's a warning about the phonegap plugin repository going away.

**Comment by aesculus** [comment]
This one statement works for me for both Apple and Google Play

<gap:plugin name="cc.fovea.cordova.purchase" source="npm" version="3.11.0">
   <param name="BILLING_KEY" value="my key"/>
</gap:plugin>
