### ISSUE TITLE
[Android] Authentication required: plugin -> buy error 6777006

### ISSUE THREAD

**Issue by mcherubin** [j3k0/cordova-plugin-purchase#322]
I've this initialization store called after device ready event:

```
function initializeStore() {

    if (!window.store) {
        console.log('Store not available');
        return;
    }

    store.verbosity = store.DEBUG;

    store.register({
        id:    "12tentativi",
        alias: "12tentativi",
        type:  store.CONSUMABLE
    });

    store.when("12tentativi").approved(function(order) {
        console.log('approved');

        order.finish();
    });


    store.error(function(error) {
        console.log('ERROR ' + error.code + ': ' + error.message);
    }); 

    store.ready(function() {
        console.log("\\o/ STORE READY \\o/");
    });

    store.refresh();
}
```

console give me

```
10-20 21:58:46.475:[store.js] DEBUG: store.queries !! '12tentativi registered':460
10-20 21:58:46.480:[store.js] DEBUG: store.queries !! 'consumable registered':460
10-20 21:58:46.480:[store.js] DEBUG: store.queries !! 'registered':460
10-20 21:58:46.485:[store.js] DEBUG: store.queries !! '12tentativi updated':460
10-20 21:58:46.485:[store.js] DEBUG: store.queries !! 'consumable updated':460
10-20 21:58:46.485:[store.js] DEBUG: store.queries !! 'updated':460
10-20 21:58:46.490:[store.js] DEBUG: queries ++ '12tentativi approved':460
10-20 21:58:46.495:[store.js] DEBUG: store.trigger -> triggering action refreshed:460
10-20 21:58:46.500:[store.js] DEBUG: queries !! 'refreshed':460
10-20 21:58:46.500:InAppBilling[js]: setup ok:735
10-20 21:58:46.505:InAppBilling[js]: load ["12tentativi"]:735
10-20 21:58:46.535:OK:860
10-20 21:58:47.365:[store.js] DEBUG: plugin -> ready:460
10-20 21:58:47.365:InAppBilling[js]: getAvailableProducts called!:735
10-20 21:58:47.365:[store.js] DEBUG: plugin -> loaded - []:460
10-20 21:58:47.365:[store.js] DEBUG: store.queries !! '12tentativi invalid':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'consumable invalid':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'invalid invalid':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'invalid':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! '12tentativi updated':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'consumable updated':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'invalid updated':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'updated':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! '12tentativi loaded':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'consumable loaded':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'invalid loaded':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'loaded':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! '12tentativi updated':460
10-20 21:58:47.370:[store.js] DEBUG: store.queries !! 'consumable updated':460
10-20 21:58:47.375:[store.js] DEBUG: store.queries !! 'invalid updated':460
10-20 21:58:47.375:[store.js] DEBUG: store.queries !! 'updated':460
10-20 21:58:47.375:InAppBilling[js]: getPurchases called!:735
10-20 21:58:47.375:\o/ STORE READY \o/:319
```

in the app I call

store.order('12tentativi');

and the app give me a dialog "Authentication required..." and in the console log: "buy error 6777006"

the plugin was installed with the BILLING_KEY from Play Developer Console

I follow the step:
1. create signed APK 
2. Upload It in beta on Play developer console
3. Create '12tentativi' product
4. Wait over 10 hours
5. install apk on my device with 'adb install xxxxx.apk'

PS: the same procedure in iOS works.

Could you help me? thanks

**Comment by itconsulting-live** [comment]
Same problem here.

**Comment by itconsulting-live** [comment]
mcherubin, were you able to resolve this?

**Comment by Aelios** [comment]
Same issue, found a solution ?

**Comment by mcherubin** [comment]
I solve uploading a signed APK in the 'Alpha' area, and configuring the 'closing alpha test' with an account different from the developer account.
After you'll have to wait some hour (in my case 1,5h but is different I suppose)

**Comment by osro** [comment]
Same problem here. I'm getting the error even with different account from the developer and signed APK.

**Comment by gen4sp** [comment]
have the same. 
APK in alpha and beta already, and nothing (

**Comment by wirelessdreamer** [comment]
I'm receiving the same error. I've tried in closed alpha, and open beta environments.

**Comment by JefferE** [comment]
Is there a real solution to this issue you yet? (I see it was labeled backlog May 26th).

I've got the same problem now. The app says its available (previously it said it wasn't ready yet) so can't imagine just waiting longer is the problem.

**Comment by denssle** [comment]
Same problem here.

**Comment by kaynz** [comment]
+1

**Comment by faytekin** [comment]
+1

**Comment by tpanhorst** [comment]
Any updates here?

**Comment by tpanhorst** [comment]
Any updates here?

**Comment by tpanhorst** [comment]
Any updates here?

**Comment by kaynz** [comment]
@j3k0 ?

**Comment by elektray** [comment]
+1

**Comment by kaynz** [comment]
Check that your local testing build number is equal to the one uploaded to the alpha/beta/release channel  in the app store. Otherwise you'll get the error mentioned in this issue.

**Comment by elektray** [comment]
@kaynz That solved it. Thank you so much.

**Comment by ilya-git** [comment]
I found one more reason to this issue: if you change the package name you get it (i.e. name of your local package is different from the one that is published). Very misleading errors...

**Comment by ErxrilOwl** [comment]
It's **2019** now. Any update for this issue???

**Comment by Dexus** [comment]
> It's **2019** now. Any update for this issue???

What is your problem? Did you upload a first app to enable the in app purchase functions?

**Comment by abesiemsen** [comment]
FYI, I had an error that presented very similarly (subscription error 6777006)... turns out I hadn't activated by products on play.google.com. (Sheepish grin.) Just putting this note here so others in the same boat might waste less time than I did!
