### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by kostap13** [j3k0/cordova-plugin-purchase#323]
Hello.

I have this problem:

... /Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:420:60: error: no
      visible @interface for 'NSData' declares the selector 'cdv_base64EncodedString'
                                transactionReceipt = [[transaction transactionReceipt] cdv_base64EncodedString];

... /Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:445:60: error: no
      visible @interface for 'NSData' declares the selector 'cdv_base64EncodedString'
                                transactionReceipt = [[transaction transactionReceipt] cdv_base64EncodedString];

2 errors generated.

*\* BUILD FAILED **

Cordova version 4.2.0

**Comment by headshota** [comment]
The cordova platform version you are using is not supporting the plugin.

Either you should use a plugin version of `3.9.1` Or upgrade your platform version (or cordova version) so it is at least `3.8`

To check the platform version run: `cordova platform version ios`.
