### ISSUE TITLE
Can't make the plugin works on Windows Phone

### ISSUE THREAD

**Issue by jobberteamcarolo** [j3k0/cordova-plugin-purchase#327]
Hi, plugin is working fine on both android & ios, review went fine.
But we can't have it works on WP, for some reason:
"ReferenceError: 'store' is undefined"

We added IAP's on dev center and they passed certification.

Thanks,
Romain.

**Comment by dkarzon** [comment]
Do you have any more info on this? What version of Windows Phone are you targeting? Currently this plugin only supports the `windows` cordova platform (WP8.1) instead of the `wp8` platform.

Make sure you are targeting the correct version and that you are waiting for the `deviceready` event from the platform.

**Comment by jobberteamcarolo** [comment]
Hi dkarzon,
We are building the app on Phonegap Build ((iOS / Android / Windows)
cli-5.1.1 (3.8.0 / 4.0.2 / 3.8.1)) and we are testing on a WP8.1 Nokia Lumia 630.

Indeed, we are waiting for the deviceready : 

var app = {
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
		initPushwoosh();
		initStore();
		window.analytics.startTrackerWithId('MY_ID_XXX');
        app.receivedEvent('deviceready');		
    },
   ...
};

**Comment by dkarzon** [comment]
Unfortunately PhoneGap Build only supports the Windows Phone 8.0 (`wp8`) platform so this plugin won't actually work with it.

**Comment by jobberteamcarolo** [comment]
Alright then, I will probably look for another pay method with windows phone & PGB like paypal or stripe.

Thanks for the fast response and really great job on the plugin, it is working fine & smooth on iOs & Android =), 
Cheers,
Romain.
