### ISSUE TITLE
IAP.restore(); not working

### ISSUE THREAD

**Issue by shows** [j3k0/cordova-plugin-purchase#329]
have a problem with in-app purchase. When IAP.restore called via a link, nothing happens with IAP.onRestore. IAP.restore senses the click but IAP.onRestore never called.

Version: PhoneGap (iOS / Android / Windows) cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

Plugin I use: cc.fovea.plugins.inapppurchase version="3.4.0"

**Comment by sirius2013** [comment]
Hi,

**Comment by anonrig** [comment]
Yes, it is not working. I'm having the exact same problem, and there is no known solution to this. @shows
