### ISSUE TITLE
Issues with store.refresh()

### ISSUE THREAD

**Issue by Neh3maH** [j3k0/cordova-plugin-purchase#332]
Hi, I'm currrently trying to implement in app purchase and I'm having an issue on the purchase.

First it seems mandatory to call store.refresh before doing anything linked to in app purchase, is it ?

Then when I have two issues with store.refresh():
1. Once I have called it, it prompts me non stop for my Apple credentials every time I switch the app between back and foreground.
2. And when I call it it uses the _approved_ callback I created for store.purchase unlocking the elements the user should be buying even if he presses cancel.

My code :

``` javascript

//This function is called earlier in the code.
function InitializeStore() {
    store.verbosity = store.INFO;

    //Register products into Storekit.
    store.register({
        id: "product.id",
        alias: "unlimited",
        type: store.NON_CONSUMABLE
    });

    //Callback used by Storekit when the store is initialized.
    store.ready(function() {
        console.log("Store Ready");
    });
}


function PurchaseCall(){
    //Call to Storekit to initiate the purchase.
    store.order(product.id);

    //Callback used by Storekit when the product is purchased.
    store.when("product").approved(function (product) {
        FREE_VERSION = false;
                //unlock
        alert("Thank you for your purchase!");

        //Confirm the purchase. Mandatory.
        product.finish();
    });
}

InAppPurchaseManager.prototype.makePurchase = function(productId, quantity) {
    loaderBool = false;
    if (!INIT_SHOP){
        store.refresh();
        INIT_SHOP=true;
    }
    if (FREE_VERSION) {PurchaseCall();}
};
```

I'm using cordova version 5.3.3 and Cordova-plugin-purchase version 4.0.0.

Thanks in advance.

**Comment by Neh3maH** [comment]
I've solved the issue by tricking in the callback but is there a way to prevent store.refresh from asking the Apple credentials when initializing the store ?

**Comment by saniyusuf** [comment]
@Neh3maH how did you sole this can you please provide deatails?

**Comment by saniyusuf** [comment]
Hi Guys please use this link to the branch provided in this comment where there is  a fix. You might have to delte your app completely from the phone and sign out restart you phone and even remove and re add the IOS project then run again after putting the fix. https://github.com/d3orn/cordova-plugin-purchase/tree/transactionFix

**Comment by rotoxl** [comment]
Hi @Neh3maH,

can you, please, share how to achieve this? It would be very helpful
