### ISSUE TITLE
receipts.appStoreReceipt() in README.md

### ISSUE THREAD

**Issue by imskull** [j3k0/cordova-plugin-purchase#34]
in "Advanced use/Receipts" section:
...
receipts.appStoreReceipt(); // null or base64 encoded receipt (iOS >= 7)
...
receipts.appStoreReceipt is not a function, I think it's should be:
...
receipts.appStoreReceipt; // null or base64 encoded receipt (iOS >= 7)
...
it's kinda a little problem, but fixing it will save people time to debug code like me: I submit my app 2 days ago without testing IAP on iOS7 until I found this problem.

**Comment by vladipus** [comment]
I agree with mohamnag

**Comment by j3k0** [comment]
The `receiptforProduct` method has been deprecated on iOS 7. The SDK now only provides a singe receipt for the whole app (containing the history of purchases). As intelligent as the plugin could be, there's isn't a per-product receipt anymore.
