### ISSUE TITLE
[iOS] Can't retrieve updated prices after a refresh

### ISSUE THREAD

**Issue by akofman** [j3k0/cordova-plugin-purchase#340]
Hello,

I'm trying to refresh my product list and check whether prices are updated.

My products are well registered and I can purchase them, retrieve my list of already purchased items, no pb.

Then, without closing my app but just placing it in the pause state, I trigger a `refresh`event when resuming it after updating the prices on ITC.
When I listen the `refresh-completed` event :

```
  window.store.when('refresh-completed', () => {
          const product = window.store.get('MY-PRODUCT-ID');
          console.log(product);
   });
```

I can see this log but the prices of my products are still the same than before my update. If I restart my app, I can see the new prices. Is it possible to get the updated prices with just a refresh ?

**Comment by akofman** [comment]
Sorry, actually it's not just the price, even if I try to update the description or any other fields on ITC, this the same result, I can't retrieve theses updates after a refresh.

**Comment by akofman** [comment]
I took the time to inspect the sources and it appears that ITC is requested only once after the first refresh.

So finally I managed to update my prices using storeKit.load. I let this issue open just in case someone have a better solution.

**Comment by skjorn** [comment]
+1

This is quite relevant I think. I'm looking to use this plugin and I examined the source code and I have exactly the same question. Consider the following scenario on iOS: I launch my app. It registers products to store. I open the shop page. It calls `store.refresh()` for the first time and fetches all products' information. I suspend my app, days go by, name, description, price, availability and whatnot get updated in iTunes Connect. I finally resume my app and go to the shop page. Again `store.refresh()` is called, but only purchases are restored. Products are already fetched from a long time ago.

Is the products' info ever updated after the first refresh()? Am I missing something in the code?

I would appreciate a feedback on this.
