### ISSUE TITLE
Consumable product is approved continuously.

### ISSUE THREAD

**Issue by ghost** [j3k0/cordova-plugin-purchase#343]
After approved of project and I call order.finish() function. And it is purchased. But after restarting app, the already purchased products are again approved. And repeated called. I wonder why does this happen.

I've check and checked again the store.refresh() function call times, and it is only called once through the app life-cycle. I tried several sandbox test users and same. For example when I bought an item as user1, and user2. After the app restart the product is again purchased for every users.

I lost 3 days to find out the problem, but no luck.

**Comment by doomsy** [comment]
I also have this problem in the latest update and running on iOS 9.1. All my apps in the app store continuously call the purchase function after a purchase has completed on each load.

**Comment by pony0621** [comment]
Before updating, wans't there such error?

**Comment by lobovkin** [comment]
Same bug. do you find solution?

**Comment by pony0621** [comment]
Yes. This helped me.

https://github.com/j3k0/cordova-plugin-purchase/issues/303

**Comment by kjda** [comment]
Is this fixed? I call product.finish & then product state becomes owned, but then when I do store.refresh the product goes back to approved state!!
