### ISSUE TITLE
EXC_BAD_ACCESS error, iOS app freezes & xcode debugger starts

### ISSUE THREAD

**Issue by Alveoli** [j3k0/cordova-plugin-purchase#347]
I am trying to get a simple store.refresh to work for iOS using a sandbox environment & user.

The dialog pops up to enter iTunes credentials. After closing that box (whether credentials are valid or not) the app sometimes freezes (more often than not).  Xcode's debugger starts and shows a `Thread1: EXC_BAD_ACCESS (code=1, address=0x9XXXXXX)` error.  There is no way to continue execution except to stop and start the app again.

The breakpoint highlighted is `UIApplicationMain()` in `main.m`:

```
#import <UIKit/UIKit.h>

int main(int argc, char* argv[])
{
    @autoreleasepool {
        int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");
        return retVal;
    }
}
```

Xcode shows memory usage is up to 76.4MB. No idea if that's weird, but seems a bit high.  I am using Meteor 1.2.1 / Cordova 5.  I've been able to get purchasing to work with Android using the same code, so I hope I've not made a silly mistake.

Anyone else having similar issues? Ideas to resolve?

**Comment by vekerdyb** [comment]
Experiencing the exact same issue with Cordova 3.9.2, iOS 9.
Works fine on Android.
@Alveoli Have you found a solution?

**Comment by Alveoli** [comment]
Yes I think so, it seems the idea to is to call refresh as few times as you can.  My code was calling refresh 3 times consecutively in some scenarios and that was causing the crash.

Now I call just the once and the problem hasn't reoccurred. As @j3k0 mentions in the docs, it's very resource expensive, so I guess this is an out-of-memory type issue.

**Comment by bboldi** [comment]
Sorry for re-animating such an old issue, but I'm having the same problem, and I'm calling the ready() function only once ... just curious if anyone got any other solution to this problem [ here is my issue [here is my issue](https://github.com/j3k0/cordova-plugin-purchase/issues/537) ...

thanks in advance.
