### ISSUE TITLE
No event fired on "will be restored for free"

### ISSUE THREAD

**Issue by mike-nelson** [j3k0/cordova-plugin-purchase#350]
I am trying to get non-renewing subscriptions on iOS to work. I want the user to be able to buy one month and then if they click buy one month again they should get another month - ie extend their subscription. The built in dialog that appears says "tap to renew or extend this subscription" so that seems like a sensible scenario.

I sometimes get this message:
"This in-app purchase has already been bought. It will be restored for free."

I gather this could happen if a purchase failed to "finish", which should be fine as it should then re-trigger "approved". The problem is it doesn't seem to trigger any events when this "restore for free" state is entered. The "updated" event it not called. Any way to get an event fired when this state happens? I can see it on the screen but my code cannot tell!

**Comment by danmatthews** [comment]
Having this problem too - did you ever figure it out?

**Comment by mike-nelson** [comment]
Good question. Can't remember exactly. We did stop getting the message about being already bought and restoring for free. I don't think we actually solved but rather it seemed to come right....

We deleted and recreated out IAPs with different names. Which may have helped. We also made sure the button was gone after you click it by going to a new screen with just a loading spinner so user cannot click a button twice. Because it seems to be so slow to connect to App Store etc. We also completed all our purchases - on ready to complete event we complete it. Previously we had a guess clause to only complete if not already has purchased but we realised this didn't work because with a subscription you may have already purchased (a previous month), now that I think about it removing this if statement could have been the answer. 

When testring in app purchases we also got a lot of repeated login to App Store popups. But when we pushed it live those things were not happening. It is generally faster in production although not always - there are sometimes random delays between the processing states.

**Comment by headshota** [comment]
Having the same issue.

**Comment by danmatthews** [comment]
I ended up switching to https://github.com/AlexDisler/cordova-plugin-inapppurchase

So much simpler, but it may not cover all bases like this one does.

**Comment by mike-nelson** [comment]
@danmatthews thanks for the suggestion, that plugin looks good.

**Comment by Ajaxy** [comment]
Same issue here
