### ISSUE TITLE
Registered product displaying as null.

### ISSUE THREAD

**Issue by ghost** [j3k0/cordova-plugin-purchase#352]
I've registered a product on the google play store called update and when I installed the plugin I ensured I put in my app's key however when I register the product in the app it displays all the information fields as null. Below is an extract from my code please note I'm using ionic.

  $scope.storeRegister = function() {
    console.log("This is a test");
    console.log("This means the initializeStore function has been called woop woop");

```
// Let's set a pretty high verbosity level, so that we see a lot of stuff
// in the console (reassuring us that something is happening).
store.verbosity = store.INFO;

  // We register a dummy product. It's ok, it shouldn't
  // prevent the store "ready" event from firing.
store.register({
id:    "update",
alias: "update",
type:  store.CONSUMABLE
});
// When every goes as expected, it's time to celebrate!
// The "ready" event should be welcomed with music and fireworks,
// go ask your boss about it! (just in case)
var product = store.get("update");
var p = JSON.stringify(product);
console.log("The product registered is : ");
console.log(p);
```

The output from console.log(p) is "id":"update","alias":"update","type":"consumable","state":"registered","title":null,"description":null,"price":null,"currency":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"transaction":null

**Comment by arielfaur** [comment]
Have you called store.refresh() ? You need to call that before you can load any products.

**Comment by seana39223** [comment]
Thanks for the response, yes I have. Still not displaying the same as above.

**Comment by quintessencegpy** [comment]
I have the same problem but on ios, did you fix that?
