### ISSUE TITLE
itunes connect stuff

### ISSUE THREAD

**Issue by vespino** [j3k0/cordova-plugin-purchase#372]
Is the documentation on how to create an IAP in itunes connect still up to date? It (itunes connect) now says the following:

"Your first In-App Purchase must be submitted with a new app version. Select it from the app’s In-App Purchases section and click Submit.

Once your binary has been uploaded and your first In-App Purchase has been submitted for review, additional In-App Purchases can be submitted using the table below."

I have submitted a new IAP and added this to a new app, but now what? How can I test it?

Apple is not helping in this case :(

I want to add a simple feature that allows users to get rid of iAds in my app.

Help? :)

**Comment by albertleao** [comment]
Did you ever find a way to get this working?

**Comment by vespino** [comment]
Nope.
