### ISSUE TITLE
Approved callback occurs at every refresh

### ISSUE THREAD

**Issue by dvcroft** [j3k0/cordova-plugin-purchase#383]
I purchase a product, the approved callback fires, I call product.finish(), and then the owned callback fires and the product shows as owned.

If I restart the app, I call store.refresh and in the store ready callback I check the product. It shows as not owned at this point. However, the refresh also causes the approved callback to fire again and the cycle starts over.

Once I have called finish and the product is owned, shouldn't it be owned after the next refresh call too? What could I be missing?

This is on Android 5 and 6 with purchase plugin 4.0.0. The behavior is the same with test purchase and real purchases, and with non-consumable and subscription items.

**Comment by dvcroft** [comment]
Note that in the developer console the order shows as "delivered."

**Comment by dvcroft** [comment]
This is also happening on Android 4.

**Comment by paulojoao** [comment]
I think this is related to #311.

**Comment by dvcroft** [comment]
After looking at the code I think this may be working as designed. I am handling it in my code by tracking the number of approvals that are received before ready is received, and then waiting until all products that started as approved are either owned or error.
