### ISSUE TITLE
Transaction stuck in "Initiated" state and "Approved" fires many times for it later.

### ISSUE THREAD

**Issue by kostenko** [j3k0/cordova-plugin-purchase#384]
Hello,

Thanks for the great plugin!

I have an issue/question, maybe I'm doing something wrong, but cannot figure out. I have a consumable products, let's say com.xxx.consumable1, .consumable3, etc, but it's totally reproducible even with just one product. It's bought on tap on a div.buy, so I do the following:

``` html
<div id="buy-one" data-iapid="consumable1" class="buy cost">buy Consumable1</div>
```

``` javascript
store.register({
    id: "com.xxx.consumable1",
    alias: "consumable1",
    type: store.CONSUMABLE
})
store.refresh()
store.once("com.xxx.consumable1").loaded(function(p) {
    $("#buy-one-cost").text(p.price)
})
$(".buy").on("click", function(e) {
    balance.buyConsumables(this)
})
buyConsumables : function(clicked) {
    var id = $(clicked).data("iapid") // here I take alias to my Consumable1
    store.order(id).then(function(product){
        console.log("store.order then transation.id: " + product.transation)
    })
    store.once(id).approved(function(product) { 
        console.log("store.once approved transation.id: " + product.transation)
        product.finish()
    })
}
```

It seems working fine, but sometimes, especially, if I try to buy the same product several times right away, I get an error popup:
`ERROR 6777010 Purchase of this item is not currently available - item being modified. Try again later`
which is also duplicated in logs:
`ERROR 6777010: Purchase of this item is not currently available`

When I do `store.get("com.xxx.consumable1")`, I see the transaction is stuck in `state: "initiated"` with `transaction: {type: "ios-appstore", id: "1000000190445582"}`
`transactions: ["1000000190445582"] (1)`

And it will be stuck like that forever until there is transaction that goes through and becomes "Approved". So I can try several times in a row and will get the same error, and it will be the same transaction ID (I think it's important), but then finally it goes through and Approved event will fire not once, but the number of times I hit div.buy button (store.order call) and it will product.finish() several times:
`[Log] =====store.once called: 1000000190445489 (console-via-logger.js, line 173)`
`[Log] [store.js] DEBUG: product -> defer finishing com.xxx.consumable1 (console-via-logger.js, line 173)`
`[Log] =====store.once called: 1000000190445489 (console-via-logger.js, line 173)`
`[Log] [store.js] DEBUG: product -> defer finishing com.xxx.consumable1 (console-via-logger.js, line 173)`
Note the exact same transaction ID. Error handler also fires and catches it:

``` javascript
store.error(function(e){
      console.log("ERROR " + e.code + ": " + e.message)
})
```

So my question is: Whether I need to handle this myself by checking transaction ID in Approved event handler, or rollback/discard that initiated transaction (if yes, then how?), or I'm not using the plugin in a right way (see how I use it above), or there is something else I'm missing? 

Thanks

**Comment by JefferE** [comment]
I know this is an old post but I have this EXACT same issue. Consumable stuck in 'initiated' state. I can't get out of this state. What/where causes it get changed to Approved? Is that in the black box that is the App Store, or is the plugin supposed to do this?

**Comment by mehmetkoc182** [comment]
I've been dealing with the same issue for a long time as well. I hope this gets resolved soon
