### ISSUE TITLE
Problem building on ios@4.0.1

### ISSUE THREAD

**Issue by Daz66** [j3k0/cordova-plugin-purchase#390]
Hi,

I've been using this plugin and it's worked perfectly for my Android build. I'm very pleased with that.
I am now in the process of doing the same for ios, but with my app the build fails :(

To narrow the problem down I created and tried to build a test project with the CLI:

> cordova create paytest com.testing.paytest paytest
> cd paytest
> cordova platform add ios
> cordova plugin add cc.fovea.cordova.purchase
> cordova build

All goes fine until this happens:

> In file included from /Users/admin/Desktop/apps/paytest/platforms/ios/paytest/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:9:
> /Users/admin/Desktop/apps/paytest/platforms/ios/paytest/Plugins/cc.fovea.cordova.purchase/InAppPurchase.h:13:9: fatal error: 
>       'Cordova/NSData+Base64.h' file not found
> # import <Cordova/NSData+Base64.h>
> 
> ```
>     ^
> ```
> 
> 1 error generated.

and the build of course fails.

Can anyone suggest a fix or workaround?

Many thanks, Darren

**Comment by glastonbridge** [comment]
You can get the bleeding edge by installing cordova-plugin-purchase from this git repository.  It works just fine on cordova 6.
```
cordova plugin add --save https://github.com/j3k0/cordova-plugin-purchase.git
```

**Comment by Lanayx** [comment]
The same issue for me. Just downloaded the latest plugin version and see fatal error 'Cordova/NSData+Base64.h' file not found

**Comment by srthakkar** [comment]
Having a same problem. and @glastonbridge I used plugin which you mention in your comment. my project build successful but when I running a project It's throwing a error of signal thread "Sigabrt". I am working on Cordova based Ionic framework project.

**Comment by obione86** [comment]
Having the same issue @srthakkar  did you manage to sort this? I am using ionic as well

**Comment by srthakkar** [comment]
Hi @obione86 ,

I just downgrade my build version and it's working. I don't know what happened with latest version but after debugging I found that the old purchase plugin working with old version of Cordova version. Like if you are  using command ' ionic/cordova build ios'  than check your Cordova version as per my knowledge latest one is 6.1 than use 'ionic/Cordova build ios@4.1' I take 4.1 as an example so just Google it different versions of Cordova and use it after platform with @ symbol. Than check your app. You can also check version of your project in terminal at the time of build. I hope this helps.

**Comment by srthakkar** [comment]
Hi @Obione86,
If you still have a problem to fix that than you mail me at sagar2121992@gmail.com . I provide you actual build version no and old purchase plugin package.

**Comment by hypery2k** [comment]
c

**Comment by webbpage** [comment]
I had to downgrade from cli-6.0.0 to cli-5.2.0 for iOS to work via PhoneGap Build. Any ETA on when this will be fixed?

**Comment by myusufe** [comment]
If you use Intel XDK, try to install npm as "cc.fovea.cordova.purchase", instead of cordova-plugin-purchase.
I am able to build using Cordova 6 for iOS and Android.
