### ISSUE TITLE
Store not available

### ISSUE THREAD

**Issue by penega-dev** [j3k0/cordova-plugin-purchase#393]
What can cause the store to be unavailable even after the device ready event.
The same code is use for 2 other projects and it works correctly.

The certificate and the mobile provision seem to work since the app build. Can it be related to the account or something in the iTunes Connect pannel.

`IAP.initialize = function () {
        IAP.log('initialize');
        document.addEventListener('deviceready', IAP.onDeviceReady, false);
    };

```
// deviceready event handler.
// will just initialize the Purchase plugin
IAP.onDeviceReady = function () {
    IAP.log('onDeviceReady');
    IAP.initStore();
};

// initialize the purchase plugin if available
IAP.initStore = function () {

    if (!window.store) {
        IAP.log('Store not available');
        return;
    }

    //rest of the code does not execute

};`
```

**Comment by gen4sp** [comment]
same. any ideas?

**Comment by mehmetkoc182** [comment]
Suddenly started having this issue.
Any ideas?
