### ISSUE TITLE
android.test.purchased

### ISSUE THREAD

**Issue by alecapu** [j3k0/cordova-plugin-purchase#394]
Are supported Android reserved product IDs for testing static In-app Billing responses like android.test.purchased?
It's worked only a time in my test, and now i don't do nothing when I use android.test.purchased with consumable... why?? I have consume it with finish() but nothing... why?

**Comment by alecapu** [comment]
Probably, is better to modifify IabHelper.java

Line 497 in:
if (purchaseData.indexOf("android.test.")<=0 && !Security.verifyPurchase(mSignatureBase64, purchaseData, dataSignature)) {

Line 864 in:
if ( purchaseData.indexOf("android.test.")>0 || Security.verifyPurchase(mSignatureBase64, purchaseData, signature)) {

or something of more secure...

**Comment by BLACKburn49** [comment]
Did anyone find a solution? I'm stuck facing what's apparently the same problem...
