### ISSUE TITLE
Upgrade / Downgrade Subscriptions

### ISSUE THREAD

**Issue by sabkaraja** [j3k0/cordova-plugin-purchase#396]
Hi
I have multiple subscriptions in my app & users have the option to choose ONE. I am wondering how will the user cancel an existing subscription and move to a new one. While reading up on the topic, I came across getBuyIntentToReplaceSkus method. Is this implemented OR there a work around for this

**Comment by noosxe** [comment]
I think this is not implemented. I need this feature too, but can't find any info, can't even find a way to cancel active subscription.

**Comment by kristfal** [comment]
@noosxe Cancelling active subscriptions is not handled by the plugin or apps in general. For iOS and Android, it is handled in the AppStore subscription center and Google Play Store 'My apps& games'.

**Comment by noosxe** [comment]
Thanks for info @kristfal . That's actually sad because I'll have to implement upgrade/downgrade functionality into this plugin or it becomes useless for me.

**Comment by sabkaraja** [comment]
I think the best way to handle would be using server api calls.

I had some in-app purchases free and paid mixed. I ended up with race-conditions validating the plans on google store as well as my own api. In the end, I ended up doing authorisation through the plugin and after that, validation, verification, cancellation etc done from the server via PHP api.

**Comment by souly1** [comment]
any update on what is to happen with this?

**Comment by JefferE** [comment]
@sabkaraja 

< In the end, I ended up doing authorisation through the plugin and after that, validation, verification, cancellation etc done from the server via PHP api. >

Any chance you'd be willing to share that PHP code?

**Comment by souly1** [comment]
Hi Guys, just wanted to update that I've created a pull request solving this issue. 
You can find the solution here:
https://github.com/j3k0/cordova-plugin-purchase/pull/512

Enjoy!
