### ISSUE TITLE
Android - Handle Cancelled Purchase (android.test.canceled)?

### ISSUE THREAD

**Issue by stevecarlton** [j3k0/cordova-plugin-purchase#398]
I have recently added a consumable IAP through Android and see some evidence that users are being granted the IAP functionality but not seeing the same amount of charges in my Google Play Merchant Account.

For instance since Feb 11th, I see 8 purchases (Chargeable and Charged) in my Google Play Merchant Account but 16 purchases in my backend database which would be realtime of course.

So, am I simply experiencing a reporting delay on the Google side or should I be looking at something in my app code?

**Comment by stevecarlton** [comment]
So after more testing with the static product codes from Google. I believe the issue is that the order is cancelled somehow (such as in android.test.canceled).

Any ideas how to handle this using the plugin? I am surprised this isn't documented.

**Comment by stevecarlton** [comment]
@mlmassey was your fix referenced to this issue by mistake?

**Comment by mlmassey** [comment]
Yup.  Changed the title
