### ISSUE TITLE
How to cancel the auto renew subscription?

### ISSUE THREAD

**Issue by sing0730** [j3k0/cordova-plugin-purchase#410]
How to cancel the auto renew subscription? Thanks.

**Comment by kristfal** [comment]
@sing0730 Cancelling active subscriptions is not handled by the plugin or apps in general. For iOS and Android, it is handled in the AppStore subscription center and Google Play Store 'My apps& games'.

Apps implementing subscriptions should deep link to those apps. This is a requirement for iOS at least.

**Comment by piin** [comment]
Hello, I am testing(sandbox mode) the subscriptions but I've already wait for more than 30 minutes but the state subscriptions is "owned" someone knows the reason? Thanks in advance.
