### ISSUE TITLE
This item is not available for purchase

### ISSUE THREAD

**Issue by ragTest** [j3k0/cordova-plugin-purchase#413]
Hi,
I'm trying to run on Android.
I keep getting this error "This item is not available for purchase" I set the test account and downloaded from the link (opt-in) provided in the console.

Help!!!

**Comment by ragTest** [comment]
store.register({
                id: 'coins2',
                alias: 'test2',
                type: store.CONSUMABLE
            });

            store.error(function (error) {
                console.log('ERROR ' + error.code + ': ' + error.message);
            });

            var product = store.get("coins2");

            store.when("test2").approved(function (product) {
                product.finish();
            });

            store.refresh();
        }


        function buyCoin() {
            store.order('coins2');
        }

**Comment by AbuHani** [comment]
make sure the product status is active  ?

**Comment by ragTest** [comment]
yes, from yesterday

**Comment by ragTest** [comment]
I have 3 active products

**Comment by JohnWeidner** [comment]
Make sure that the versionCode that's in your AndroidManifest.xml for the build that you have on your phone is the same as the versionCode for your app that you uploaded to the Google developer console.

**Comment by ragTest** [comment]
Yes, I check is same version

**Comment by AbuHani** [comment]
use the same test account you specified in developer console.

**Comment by ragTest** [comment]
I created a test user (including g +) and placed on developer console> settings> Gmail accounts with testing access

**Comment by ragTest** [comment]
This user then has been enabled for alpha testing and shared the opt-in link and apk version is correct.
I am going crazy!!!

**Comment by AbuHani** [comment]
try use different account ?

**Comment by ragTest** [comment]
Yes, I try with 2 account

**Comment by ragTest** [comment]
I always have same result

**Comment by mparpaillon** [comment]
I'm not sure it will solve your issue but I think I had the same issue when adding a new item to purchase. I had to upload and publish the APK in alpha stage before it appears available in app

**Comment by mparpaillon** [comment]
It can be alpha, beta or public release but I guess that you want to test it before publishing it, so go for alpha stage then try again... hope this helps

**Comment by JohnWeidner** [comment]
When you make a changes in Google's Developer Console to your In-app items, APK, or product settings, it can take a couple of hours before those changes become active.   This makes debugging this issue extra hard because you must wait between changing something on google and testing to see if it made any difference.   

1.  Make sure the In-App product shows a status of Active on the developer console.
2.  Make sure the In-App product id matches what your using in your app
3.  Make sure the build version listed on Google matches what's in the app you are testing
4.  Make sure the app is published (alpha, beta, or prod) in the google developer console

Watch the adb log as you run your app to see if an error is being displayed.

**Comment by ragTest** [comment]
I checked all the points you've described and are ok

**Comment by AbuHani** [comment]
try clear play store data from mobile ?

**Comment by ragTest** [comment]
I tried but it does not work

**Comment by ragTest** [comment]
I added the plugin by PhoneGap build, it could be a problem ?

**Comment by ragTest** [comment]
https://www.npmjs.com/package/cc.fovea.cordova.purchase

**Comment by ragTest** [comment]
Hi guys,
I created a new empty app to run the tests.
The first time I was able to buy the product (success).
Now from any device / users the app no longer works.

**Comment by ragTest** [comment]
Now I get this error:

ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)

**Comment by AbuHani** [comment]
#76

**Comment by ragTest** [comment]
With the app published in alpha state gave an error when closing the order and also every time that I tried to initialize the store.
I think the problem is in the signature key, I managed to solve by publishing the apk also in production.
