### ISSUE TITLE
Keep showing popup ask user login to iTune Store every time open app

### ISSUE THREAD

**Issue by ngoclt** [j3k0/cordova-plugin-purchase#421]
As mentioned in documentation, the app should call store.refresh() when user open app to get product info from Apple Server. 
However, this function require user to be authenticated. It makes the app display alert view that ask user to input his password every time open app.
It's very annoying. 

Is there anyway that allows me to fetch the product info ? No process for billing or restoring. I believe they require to authenticate user before process. 

Thanks in advantage,

**Comment by ngoclt** [comment]
Sorry, 
It's my mistake. The problem is because I didn't call in approved event.

`p.finish() `

to finish the transaction. Therefore ios keep trying to ask user to login and finish the transaction.

**Comment by adriano-di-giovanni** [comment]
Does anybody of you use GoogleMobileAds SDK for iOS? If so, try to delay the store initialization. Does the popup still fires? If so, try to add

[GADMobileAds disableAutomatedInAppPurchaseReporting];
to your AppDelegate

Does the popup still fires?
