### ISSUE TITLE
When iOS app starts, it always popup to ask for itunes's password.

### ISSUE THREAD

**Issue by emmychen** [j3k0/cordova-plugin-purchase#427]
If I call store.refresh() , then iOS app starts, it always popup to ask for iTunes password.  If I don't call store.refresh().  store.buy() will not do anything!  

Emmy

**Comment by emmychen** [comment]
Any plan to fix it issue?

**Comment by osro** [comment]
There is an issue for this already : #357

**Comment by adriano-di-giovanni** [comment]
Does anybody of you use GoogleMobileAds SDK for iOS? If so, try to delay the store initialization. Does the popup still fires? If so, try to add

[GADMobileAds disableAutomatedInAppPurchaseReporting];
to your AppDelegate

Does the popup still fires?
