### ISSUE TITLE
Server Side Validation

### ISSUE THREAD

**Issue by axtscz** [j3k0/cordova-plugin-purchase#431]
Does anyone have any resources that might help in setting up a server to validate subscriptions? I've looked but haven't found many good ones.

**Comment by PauloBronfox** [comment]
Hi,

here is part of my code for iOS validation based on several sources:

- set validator in your app: 
store.validator = "http://xxx/check-purchase.php";

- set up script on your php server: 
<?php
/** 
 *  \file check-purchase.php
 */

function validate_receipt($receipt) {
try {
    $end_point = 'https://sandbox.itunes.apple.com/verifyReceipt';
    //$end_point = 'https://buy.itunes.apple.com/verifyReceipt';
        $ch = curl_init($end_point);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array('receipt-data' => $receipt,'password'=>'your_password')));
        $response = curl_exec($ch);
        $errno = curl_errno($ch);
        $errmsg = curl_error($ch);
        curl_close($ch);
        if ($errno !== 0) {
            throw new Exception($errmsg, $errno);
        }
        $data = json_decode($response);
        if (isset($data->status) && $data->status === 0) {
            // check if receipt is still valid
            date_default_timezone_set("UTC"); 
            $now = time('now') * 1000;  // in milliseconds
            
            $isValid = false;
            foreach($data->latest_receipt_info as $receipt)
            {
                if ($receipt->expires_date_ms > $now) $isValid = true;
            }
            
            $code = 0;
            if (!$isValid) $code = 6778003;
            return ["ok"=>$isValid,"data"=>["code"=>$code]];
            
            //return $data->receipt;
        } else {
            return FALSE;
        }
    } catch (Exception $ex) {
        return FALSE;
    }
}

$data = json_decode($HTTP_RAW_POST_DATA);

if ($data->{'transaction'}->{'type'}=='ios-appstore') {
    $resu = validate_receipt($data->{'transaction'}->{'appStoreReceipt'});
    if ($resu===FALSE) {
        exit();
    }
    
    // register tickets
    echo json_encode($resu);
    // check for validity
    
    $fp = fopen('./tmp/request.log', 'a');
    fwrite($fp, json_encode($resu));
    fclose($fp);
    
}
?>

I'll add android support. Any comments to improve the scripts are welcome

**Comment by yertos** [comment]
@PauloBronfox any updates to this? I'm probably going to end up having to write my own, but if you have something, it might help.

**Comment by PauloBronfox** [comment]
The code for Android is the following one:

// android validation
function verify_market_in_app($signed_data, $signature, $public_key_base64) 
{
	$key =	"-----BEGIN PUBLIC KEY-----\n".
		chunk_split($public_key_base64, 64,"\n").
		'-----END PUBLIC KEY-----';   
	//using PHP to create an RSA key
	$key = openssl_get_publickey($key);
	//$signature should be in binary format, but it comes as BASE64. 
	//So, I'll convert it.
	$signature = base64_decode($signature);   
	//using PHP's native support to verify the signature
	$result = openssl_verify(
			$signed_data,
			$signature,
			$key,
			OPENSSL_ALGO_SHA1);
	if (0 === $result) 
	{
		return false;
	}
	else if (1 !== $result)
	{
		return false;
	}
	else 
	{
		return true;
	}
} 

$data = json_decode($HTTP_RAW_POST_DATA);

if ($data->{'transaction'}->{'type'}=='android-playstore') {
    // check if transaction if valid
    $purchaseToken = $data->{'transaction'}->{'receipt'};
    $signature = $data->{'transaction'}->{'signature'};
    $public_key_base64 = 'xxx';
    $isValid = verify_market_in_app($purchaseToken, $signature, $public_key_base64);
    
    
    $code = 0;
    if (!$isValid) $code = 6778003;
    $result = ["ok"=>$isValid,"data"=>["code"=>$code]];

    
    $receiptInfo = json_decode($data->{'transaction'}->{'receipt'});
    $productId = $receiptInfo->productId;
    $purchaseTime = $receiptInfo->purchaseTime;
    
    $bill = (object) array('product_id' => $productId,
               'purchase_date_ms' => $purchaseTime,
               'expires_date_ms' => 0);
    
    echo json_encode($result);
    
    
}

**Comment by aesculus** [comment]
This looks great, but I am still confused on how to call this on the client.

If anyone has a simple example on how to use the above routines on the client for auto renewing subscription that would be appreciated.

In the doc it says to include your validator as above;

store.validator = "http://xxx/check-purchase.php";

And also that I need a callback setup?
		store.validator = function(product, callback) {
			callback(false, {
        error: {
            code: store.PURCHASE_EXPIRED,
            message: "XYZ"
        }
    	});
    };

Is this callback needed when we are using the server side?  My server side callback never seems to get call.

**Comment by aesculus** [comment]
For some reason when verifying an order on iOS when I do this I get a 1 as in the log.

$data = json_decode($HTTP_RAW_POST_DATA);
error_log(print_r($data)."\n");

Any thoughts why I get a 1 instead of an array of a product?

**Comment by aesculus** [comment]
I hacked the iOS validation a bit to handle both sandbox and regular transactions.  In my test builds I add:
   additionalData: 'sandbox'
in the store.register for the subscription product.

Then I pick it up on the server side and in the App Store validation

$test = 0;
if ($data->{'additionalData'} == 'sandbox') $test = 1;
$result = validate_receipt($data->{'transaction'}->{'appStoreReceipt'}, $test);

And check the value of $test to see which $end_point to use.  Keeps me from having to have two sets of code or switching back and forth, often forgetting to make the switch until I get the 21007 error. And this way I can run both beta's and production with the same validation code.

**Comment by aesculus** [comment]
If you want to actually validate subscriptions on Android it's a bit more complicated like the iOS one. Here are two good links to help you. Note the second link assumes you have the token already as described in at the bottom of the first link.

https://developers.google.com/android-publisher/authorization

http://stackoverflow.com/questions/41982496/check-google-android-subscription-status-on-backend
