### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by Kinzi** [j3k0/cordova-plugin-purchase#432]
Hi,

I'm working with ionic. When I try to build for ios I get the following error:

`Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/**/dropbox/packtor/mobileapp/packtor/platforms/ios/cordova/build-debug.xcconfig,-project,Packtor.xcodeproj,ARCHS=i386,-target,Packtor,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/**/dropbox/packtor/mobileapp/packtor/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/**/dropbox/packtor/mobileapp/packtor/platforms/ios/build/sharedpch`

building for android works fine.

I already tried:
- `rm / add the plugin`
- `rm / add platform`
- `rm / add platform folder & plugin folder`

Here is my setup:
cc.fovea.cordova.purchase 4.0.0 "Purchase"
Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.0
Gulp local: Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.10.0
Xcode version: Xcode 7.3 Build version 7D175

I'm stuck. Does anyone have a solution for this? Or an idea on how to solve it?

Thanks!

**Comment by Kinzi** [comment]
OK. It's working now. I don't know exactly what I did - but I guess it was reinstallinf everything (platform/plugin) fresh outside of the dropbox folder.

**Comment by webbpage** [comment]
I had to downgrade to cli-5.2.0 from cli-6.0.0 for this to work...
