### ISSUE TITLE
iOS touch id problems

### ISSUE THREAD

**Issue by itsonit** [j3k0/cordova-plugin-purchase#433]
Trying to buy a product the app asks for the touch id and do not accept it. (If i used the passwd instead everything works fine.) After three times asking for the touch id the plugin logs:

    [store.js] ERROR: ios -> ERROR 6777010: Verbindung mit iTunes Store nicht möglich

but no error callback is called. :(

**Comment by yeldarby** [comment]
I'm getting this as well.

**Comment by itsonit** [comment]
Update: concerns only the sandbox. In production everything works fine.

**Comment by j3k0** [comment]
FYI, it's because TouchID is linked with your own iTunes account, not with a Test User.
