### ISSUE TITLE
Reconciliate subscriptions or purchases with Google merchant data

### ISSUE THREAD

**Issue by locsim** [j3k0/cordova-plugin-purchase#434]
Hello,

Something very unclear to me: how do we prevent a single Google account from being used on multiple devices, and thus deliver content or services for x users and when only one subscription is paid?

Thank you for your help,
Philippe

**Comment by j3k0** [comment]
You just shouldn't do that. Google and Apple's policy states that once a product has been purchased on 1 device, you should be able to access it from all of your devices.

**Comment by locsim** [comment]
Ok I understand. Thank you for your answer.
