### ISSUE TITLE
Can't find variable: inappbilling

### ISSUE THREAD

**Issue by RezaRahmati** [j3k0/cordova-plugin-purchase#449]
Hi

I am using your plugin, it's working great on Android, but on ios I get this error "Can't find variable: inappbilling"

**Comment by RezaRahmati** [comment]
Sorry, it seems that I made a mistake.
I don't know why but I am using the plugin like this
inappbilling.init(successHandler, errorHandler, { showLog: true }, $scope.productCatalog);
I remember that I have copy paste it from somewhere, but I can not find it in your repo anymore, now I see that I need to call the apis by `store.` so I start reading the api doc again, please close this issue.

**Comment by Dhamu143** [comment]
hello @RezaRahmati  is there any clear example for the flow of use this plugin for android ?
i need to use inapp for android and i can get register store , but after that i did not found any resource to do further. which procedure i need to follow ?
what about the next after store register ? i have also studied the life cycle but not happy with that . :(

**Comment by RezaRahmati** [comment]
@Dhamu143 follow these instructions, https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md it should help you
