### ISSUE TITLE
Android: 6777001:init failed - null

### ISSUE THREAD

**Issue by RegencySoftware** [j3k0/cordova-plugin-purchase#450]
I have products published in Android, and my app active as a Beta Test. 

The sample code below attempts to register one product and I get the following error: **6777001:init failed - null**

I tried commenting out the "Approved" event, same error, then both register product and approved event same error "6777001:init failed - null"

I saw a few other posts where folks were staying they had to create **\res\billing_key.xml** file?

It seems like it is happening right at store.verbosity = store.INFO;

Any help would be appreciated. 

gap:plugin name="**cc.fovea.cordova.purchase**" source="npm" version="4.0.0"
**param name="BILLING_KEY" value="MII.."** 
gap:plugin

store.verbosity = store.INFO;

store.register({
	id: "prod1",
	alias: "Test Product",
	type: store.NON_CONSUMABLE
});

store.when("Test Product").approved(function (order) {
    alert("Order Completed: " + "Test Product");
    order.finish();
});
	
	
store.error(function (error) {
    dxShowMsg("Store Init Error", error.code + ': ' + error.message)
});  	

store.ready(function () {
    console.log("\\o/ STORE READY \\o/");
});

store.refresh();

**Comment by j3k0** [comment]
I can't provide much support for PhoneGap Build (never used it). Using cordova and/or local build, the billing key xml file is created for you.

I notice you use a older version of the plugin (4.0.0), latest is 6.0.0

**Comment by RegencySoftware** [comment]
I appreciate your response. 

I am using DevExtreme with PhoneGap build.  In that process DevExtreme has PhoneGap build a custom template with the plug-ins. Then DevExtreme using Visual Studio creates the APK with that custom template.  Hopefully there is a post-build step I can hook into to create the XML file.

Thank you

**Comment by j3k0** [comment]
That's even further away from my setup. Let me know how you solve this, it will surely enter the documentation.
