### ISSUE TITLE
Non-Renewing iOS Subscriptions "payment information required"

### ISSUE THREAD

**Issue by Andy10Levels** [j3k0/cordova-plugin-purchase#451]
Hello! We have some problem with your plugin.
When user press buy Non-Renewing iOS Subscriptions - we get "initiated" callback. But, if iOS show "payment information required" window - we get "cancelled" callback and when the user fill information - the proccess go next and we get "approved, ..., finished, owned".
This problem only in iTunes version of our program.

**Comment by j3k0** [comment]
So, if I get things right, there's an extra "cancelled" even that shouldn't fire.

This only happens if the user isn't logged in or hasn't filled credit card information, right?

If so, this is probably an iOS behavior: the `cancelled` event is just propagated from the native StoreKit SDK up to the javascript... I will double check that, but pretty sure about it.

**Comment by Andy10Levels** [comment]
Thank's for quick answer!
Yes, you got things right.

**Comment by itibet** [comment]
Hi,
this also happens for consumable products (only on iOS): if the user isn't logged in or hasn't set a payment method then iOS will pop up **Payment Information Required - Tap Continue to sign in, then provide billing info** and the `cancelled` callback is invoked.
Then if the user tap "Continue" the app is paused, the purchase process is handled by iOS out of the app (the user has to set a payment method and then confirm the purchase), it'll be up to the user to resume the app, then:
- if the user hasn't completed the purchase, no more callbacks are invoked
- if the user has completed the purchase, the `approved`, ..., `finished` callbacks are invoked when he goes back to the app (hopefully!).

I would say the `cancelled` event should be invoked only when the app is resumed and the user didn't finalize the purchase process.

Thank you.

**Comment by itibet** [comment]
P.S. is there any way to debug this behaviour in sandbox environment?
When I use a test account it seems there's no way to simulate a missing billing information.
Thanks.

**Comment by thielCole** [comment]
This is a very common situation for me, so if we could see an update to this I would appreciate it. To see the same behavior, I have been able to repro it just by pausing the app (by pressing the home button) and I get the canceled event to fire almost automatically.
