### ISSUE TITLE
unfinished purchases forgotten on app restart (ios)

### ISSUE THREAD

**Issue by greneham** [j3k0/cordova-plugin-purchase#454]
thanks for the great plugin! i have it setup up and almost completely working apart from one issue...

1. buy a consumable product with store.order
2. on success dont call product.finish()
3. now we have an unfinished purchase
4. call store.refresh()
5. it triggers the approved event for reprocessing

so far so good. 

now if i repeat steps 1-3 above and then restart the app and...

1. call store.refresh
2. approved event is not triggered

so it seems the app store forgot the unfinished purchase.

is this a bug in the plugin? 
or a quirk in apple's sandbox environment? 
does calling register on the products when the app starts override any previous state they had?

because the unfinished purchase was forgotten product.canPurchase is true. 

So, if i then try to buy that item again I get an error telling me that "This In-App purchase has already been bought" despite the fact that it's a consumable product

**Comment by j3k0** [comment]
Thanks for the detailed description.

Indeed, there's seems to be an issue in the plugin. Someone need to work on #448 (and I'm afraid it'll have to be me).

**Comment by atorgfr** [comment]
Hi have the same issue and it's the same for consumable and non consumable.
