### ISSUE TITLE
how can i consume a product？

### ISSUE THREAD

**Issue by justintseng** [j3k0/cordova-plugin-purchase#460]
how can i consume a product？

on Android, must consume products that i want to let the user purchase multiple times. If not consume the product after a purchase, the next time will attempt to purchase it you will get the error message: Unable to buy item / Item already owned.

**Comment by j3k0** [comment]
You have to use `product.consume()`, from within the `approved` callback (or `verified` if you use receipt validation)

**Comment by Dhamu143** [comment]
hello @j3k0  is there any clear example for the flow of use this plugin for android ?
i need to use inapp for android and i can get register store , but after that i did not found any resource to do further. which procedure i need to follow ?
what about the next after store register ? i have also studied the life cycle but not happy with that . :(
