### ISSUE TITLE
About using android.test.purchased

### ISSUE THREAD

**Issue by bachnxhedspi** [j3k0/cordova-plugin-purchase#461]
Hi there,

I'm trying to use android.test.purchased when implemeting billing function. I heard somewhere that there's some bugs when using this test product but I have been persisted on it. 

My code:

`        store.register({
            id:    "android.test.purchased",
            alias: "test buy",
            type:  store.NON_CONSUMABLE
        });

```
    // When every goes as expected, it's time to celebrate!
    // The "ready" event should be welcomed with music and fireworks,
    // go ask your boss about it! (just in case)
    store.ready(function() {
        console.log("\\o/ STORE READY \\o/");
        var p = store.get("android.test.purchased");
        console.log(p);
    });

    // After we've done our setup, we tell the store to do
    // it's first refresh. Nothing will happen if we do not call store.refresh()
    store.refresh();

    // Log all errors
    store.error(function(error) {
        console.log('ERROR ' + error.code + ': ' + error.message);
    });

    store.when("android.test.purchased").updated(function(product) {
        console.log('Test purchased updated');
        console.log(product);
        console.log(product.owned);
    });

    store.when("product").approved(function (order) {
      console.log('Buy approved');
      order.finish();
    });`
```

But after I bought it (purchase successful showed), I don't see any sight of "Buy approved" in approved event.

**Comment by j3k0** [comment]
One thing I see in your code, you should call `refresh` after having set the `.error()` and `.when(...)` handlers (because `refresh` can trigger some of those).

Apart from that, did you solve the issue?

**Comment by bachnxhedspi** [comment]
Thanks for your reply @j3k0 
I have been following instruction from gajotres.net, using your plugin for iOS and poiyutrez's plugin for Android (https://github.com/poiuytrez/AndroidInAppBilling)

And, it works welll in Android with poiyutrez's. 

Still making iOS version running, hope to see you later :+1:

**Comment by souly1** [comment]
Hi, 
thanks @j3k0 for the plugin,
I'm using this plugin, reordered things like you wrote but approved not being fired.
any other suggestions?

**Comment by scrakcho** [comment]
It´s the same problem here... with a little code part...
#500
