### ISSUE TITLE
Purchase validation request

### ISSUE THREAD

**Issue by anonrig** [j3k0/cordova-plugin-purchase#463]
I've a question about receipt validation. My application just got approved at AppStore.

Does purchase validation request is called again even though apple says "You are already subscribed to this feature " etc.

Currently, it seems that the `store.refresh()` function doesn't trigger the `.approved` function, even though the user is already subscribed to the feature. Therefore, `product.verify` isn't triggered and all subscription process fails for my case.

Can this be possible? How can I make this right?

**Comment by anonrig** [comment]
@j3k0 any suggestions?

**Comment by flyingsky** [comment]
I was struggling for server receipt validation for half year. Finally I figure out how to do the whole auto renewal subscription. You can see more detail from here: http://flyingsky.github.io/2016/06/28/how-to-use-phonegap-to-do-auto-subscription/
If you still have question, please let me know.

**Comment by GuidoAppedemic** [comment]
@flyingsky i was browsing the issues tickets and stumbled upon this thread. It seems like you know a lot about the auto renewing subscription. I have a problem on ios with registering the (type: store.AUTO_RENEWING_SUBSCRIPTION) product. Would you maybe have a few minutes to read my thread? -> https://github.com/j3k0/cordova-plugin-purchase/issues/487
