### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mlegenhausen** [j3k0/cordova-plugin-purchase#465]
I created some typescript definitions for this plugin: https://github.com/werk85/typed-cordova-plugin-purchase

You can install them via:

``` sh
typings install typings install github:werk85/typed-cordova-plugin-purchase --global --save
```

**Comment by beradrian** [comment]
It would be nice a PR for this project itself.

**Comment by biesbjerg** [comment]
Do you need to include the following in `tsconfig.json` to have types be available, or did I do something wrong?

```
...
	"files": [
		"node_modules/cordova-plugin-purchase/src/js/index.d.ts"
	]
...
```
