### ISSUE TITLE
Purchase restore

### ISSUE THREAD

**Issue by John0x** [j3k0/cordova-plugin-purchase#466]
Hey, apple told me to add a button to my app for users to restore the product.

> We found that your app offers In-App Purchase(s) that can be restored but does not include a "Restore Purchases" feature to allow users to restore the previously purchased In-App Purchase(s)

Do they mean to add a button which calls the store.refresh method or is it something else?

**Comment by j3k0** [comment]
That's it.

**Comment by aesculus** [comment]
And you have to have the button even if you automatically restore purchases. :-(

**Comment by joedaniels29** [comment]
You can't handle it automatically because apple needs the user to enter their password in order to do the refresh.  when you say automatically, you mean you are handling the restore outside of StoreKit?

**Comment by joedaniels29** [comment]
Thanks for this info though! Hope my binary (ascii? lol) gets through on round 3!

**Comment by Guneet13** [comment]
Do we get a response back after the store.refresh, if we are suppose to handle "your purchase has been restored" or "you have nothing to restore"?

**Comment by oduverne** [comment]
Hello,
Purchases restoring doesn't work for me, when I call store.refresh the user password is requested but nothing happens after that, there are no event.
Can you help me?
Thx
