### ISSUE TITLE
What is the difference between store and storekit interfaces?

### ISSUE THREAD

**Issue by Ajaxy** [j3k0/cordova-plugin-purchase#468]
It's pretty unclear. I'm using old `storekit` interface with current version of this plugin on iOS and it works well for me. Is it still supported?

**Comment by j3k0** [comment]
`storekit` is the older interface (which only works on iOS). For now we maintained backward compatibility with older version of the plugin. `store` is the new interface (works also with android and windows).

Of course, at some point we will deprecate the older interface.

**Comment by Ajaxy** [comment]
Thank you
