### ISSUE TITLE
PhoneGap - InAppPurchaseios - window.storekit is undefined

### ISSUE THREAD

**Issue by thomasphilip** [j3k0/cordova-plugin-purchase#47]
I´m having a problem using the plugin below to manage in-app purchases. i think i have installed it correctly because it was working correctly yesterday but today the window.storekit object is undefined

**Comment by denza** [comment]
I have this issue for android. iOS version works just fine.

**Comment by RouR** [comment]
window.storekit renamed to  window.store in latest version
Suggest to close
