### ISSUE TITLE
'appStroreReceipt' and 'transactionReceipt'

### ISSUE THREAD

**Issue by reMake000** [j3k0/cordova-plugin-purchase#470]
For iOs, product.transaction object have 2 encrypted fields: 'appStroreReceipt' and 'transactionReceipt'

As far as I understood:
- 'transactionReceipt' will only return information from 'https://buy.itunes.apple.com/verifyReceipt' about one specific transaction;
- 'appStroreReceipt' will return information about all performed transactions within my app for current iTunes account.

Please, correct me if I wrong. I would like to understand purpose of 'appStroreReceipt'.

**Comment by souly1** [comment]
So it will be mentioned here, transactionReceipt is deprecated, so i guess appStoreReceipt is the way to go...
