### ISSUE TITLE
questions on non-renewing subscriptions

### ISSUE THREAD

**Issue by nnylip** [j3k0/cordova-plugin-purchase#472]
I implemented non-renewing using version 4.0 by seibelj using the approach outlined in this doc:

https://github.com/seibelj/cordova-plugin-purchase/blob/non_renewable_subscription_docs/doc/ios.md#non-renewing-ios-subscriptions

I upgraded my test program to version 6.0 and it appears "p.finish()" when called in ".approved" does not initiate ".owned". Am I missing something? Was the approach changed from 4.0 to 6.0? Thanks

**Comment by JefferE** [comment]
I have this same problem. Non-Renewing is never calling .owner anymore so my processing is broken.

I think this has to do with non-renewing type no longer even defined in 6.0.0 plugin:

http://screencast.com/t/auhuYDzycpm

The left is the previous version I was using (but the script file has no rev # in it so I'm not even sure what rev it was now).

**Comment by nnylip** [comment]
If you follow the non-renewing example for version 6.0, it works in my mini-test app. However, it is 
a big departure from 4.0 example. It requires a leap of faith that it will work if there are long 
periods (1, 6, 12 month) and I don't see a way to have restore done in the case of a client buying a 
new phone. I am considering testing non-renewing with cordova-plugin-inapppurchase, (which has a 
simpler interface)
