### ISSUE TITLE
double store.refresh() needed to get owned products on ios

### ISSUE THREAD

**Issue by adriano-di-giovanni** [j3k0/cordova-plugin-purchase#474]
on iOS 9.3.3 we have to call store.refresh() twice in order to get owned products.
After the first one we only get products loaded.

**Comment by s-muntazir** [comment]
Its also with android

**Comment by adriano-di-giovanni** [comment]
We can't reproduce it on Android. Which version, please?

**Comment by s-muntazir** [comment]
cordova 4.1.1 version.


This is my code

get status event

store.refresh();
var product = store.get("product_d");
alert('price  is' + product.price  + "  all the product detail " + product );
 alert(' finished status   '   + product.FINISHED  + ' owned  status   '   + product.OWNED + ' APPROVED status   '   + product.APPROVED) ;

i dont get the owned status untill i call the below 

store.when("product_d").approved(function(p) {
    p.finish();
});
store.order("product_d")

**Comment by ricardocarvalh0** [comment]
@adriano-di-giovanni any update on this? Could you find a work around? I heard it happens with non consumable products like https://github.com/j3k0/cordova-plugin-purchase/issues/476

**Comment by adriano-di-giovanni** [comment]
@ricardocarvalh0 @j3k0 @giggioz I tested again and I don't need to call `store.refresh()` twice in order to retrieve owned products on iOS 9.3.5. I still need to call it twice on iOS 9.3.2. So, maybe that's something related to iOS version. Can you confirm? Thanks.

**Comment by ricardocarvalh0** [comment]
@adriano-di-giovanni I was using the v4.0.0 of the plugin and i received client feedbacks saying they could not retrive owned products on both Android and iOS. It solved updating the plugin to v6.0.0

**Comment by adriano-di-giovanni** [comment]
@ricardocarvalh0, my tests run on v6.0.0. Please, let me know if some of your clients still give you feedback about missing owned products. Thanks.

**Comment by dvcroft** [comment]
On iOS 9.3.5 the first refresh does not ask for an apple id password and only loads the product information. A second refresh asks for password, and marks products as owned. I am using the 6.0.0 plugin. @adriano-di-giovanni have you found out anymore?

**Comment by adriano-di-giovanni** [comment]
@dvcroft, no. I'm sorry.
