### ISSUE TITLE
How to get owned product for non consumable products 

### ISSUE THREAD

**Issue by s-muntazir** [j3k0/cordova-plugin-purchase#476]
Hi

I have successfully implemented the plugin and it works fine with the purchase. 

But when i try to get the status after i restart the app.. the owned status is false ..the price  attribute is fine but cant grt the owned status until i invoke store.order ()

Any idea what is happening

**Comment by robinvanb** [comment]
@s-muntazir Sorry to hijack your question but could you take a look at #475 for me? Am I doing something wrong?

**Comment by Dhamu143** [comment]
hello to all can you please tell me what to do next after we can register our product in store ?

**Comment by ricardocarvalh0** [comment]
It's happening to me too, my non consumable products come as owned: false even if it was already purchased.

**Comment by elektray** [comment]
@ricardocarvalh0 I'm experiencing the same problem. Did you find any workaround? Thanks

**Comment by ricardocarvalh0** [comment]
Hi @elektray , it solved updating the plugin.
See: https://github.com/j3k0/cordova-plugin-purchase/issues/474#issuecomment-244353238
