### ISSUE TITLE
error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG

### ISSUE THREAD

**Issue by bhorn** [j3k0/cordova-plugin-purchase#477]
Somewhat out of the blue our App won't start anymore. It Crashes with this Stack-Trace:

> java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
>   at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:67)
>   at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
>   at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:864)
>   at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:562)
>   at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
>   at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
>   at java.lang.Thread.run(Thread.java:818)
> Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
>   at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:250)
>   at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47)
>   at java.security.KeyFactory.generatePublic(KeyFactory.java:172)
>   at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:62)
>   ... 6 more
> Caused by: java.lang.RuntimeException: error:0c0740b0:ASN.1 encoding routines:ASN1_get_object:TOO_LONG
>   at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)
>   at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:248)
>   ... 9 more

When a user buys a product, it crashes and won't start anymore because it crashes directly.
Any idea what happened?

**Comment by codelabsoutlook** [comment]
Hi, i have same problem. Plese someone can help us?

**Comment by dotneet** [comment]
I solved this problem.
Check below file.

platforms/android/res/values/billing_key_param.xml

This file contain "billing_key_param" parameter.
It must be same as Public License Key that can be found at play console.

https://developer.android.com/training/in-app-billing/preparing-iab-app.html

**Comment by nehaxccelerata** [comment]
Anybody help i am facing same exception in my code?
