### ISSUE TITLE
Google Play warning: Your app is using an incorrect implementation of in-app billing

### ISSUE THREAD

**Issue by adriano-di-giovanni** [j3k0/cordova-plugin-purchase#479]
Please,
read the email we received

Hello Google Play Developer,

We detected that your app(s) listed at the end of this email are invoking the in-app billing service without setting a target package for the intent. This can enable a malicious package to bypass the Play store billing system and access items that have not been purchased.

**Next Steps**
1. If you are using IabHelper, please start using the latest SDK.
2. If you are manually invoking the in-app billing service, make sure you are calling Intent.setPackage(“com.android.vending”) on any intents to "com.android.vending.billing.InAppBillingService.BIND".
3. Sign in to your Developer Console and submit the updated version of your app.
4. Check back after five hours - we’ll show a warning message if the app hasn’t been updated correctly.

Thanks,
Adriano

**Comment by IsoArska85** [comment]
It seems to be affecting the whole payment process. I cant get any consumables go through any more. My subscriptions does work somehow. Is there a possible fix update coming when, we would need it ASAP.

**Comment by standup75** [comment]
+1

This was working until the latest version of our app I uploaded last week.

**Comment by tiois** [comment]
+1, same problem here.

**Comment by adriano-di-giovanni** [comment]
@j3k0, are you already working on this? Alternatively, can you give me some hints in order to solve the issue and make you a pull request?

Thanks,
Adriano

**Comment by j3k0** [comment]
Hello, sorry I'm not working on this.

IabHelper is located here: `src/android/com/smartmobilesoftware/util/`, you can try replacing with the latest version, not sure if it's gonna work out of the box, but who knows!

If someone starts working on this task, you can create an empty PR, I can give support from there.
