### ISSUE TITLE
QuotaExceededError and Other

### ISSUE THREAD

**Issue by Dolemite1347** [j3k0/cordova-plugin-purchase#480]
I am receiving the following error every time my app loads now. 

QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota. store-ios.js line 968

Line 968: window.localStorage.sk_receiptForTransaction = JSON.stringify(this.receiptForTransaction);

After this error appears it then says "unknown product purchased" and all of my renewing and non-renewing subscriptions renew. Also, each time I refresh my app (in development mode) is automatically renews the non-renew subscription, increments the expire date. Is there a way to prevent this?

**Comment by selected-pixel-jameson** [comment]
I'm getting a very similar error. I'm not sure why.

Runtime Error: The quota has been exceeded. There really aren't any details. I'm using the latest version of this plugin 7.4.3 on iOS 12. There aren't any details beyond this except it mentions 'setAppStoreReceipt'.

The error goes away if I delete the app and reinstall it on my phone.
