### ISSUE TITLE
Renewing paid subscriptions: can't finish them

### ISSUE THREAD

**Issue by ddddm** [j3k0/cordova-plugin-purchase#483]
Having an issue finishing renewing paid subscriptions; our purchase flow looks like:

```
store.validator = function (product, callback) {
  // fake logger - we validate transaction info on API after it was bought
  callback(true, product.transaction);
};

store.once(subscriptionId).approved(function (product) {
  product.verify();
});

store.once(subscriptionId).verified(function (product) {
  product.finish();
  // then send 'product' to the API
});
```

As you can see, we finishing the product no matter what. But for some of our users we see their products in `state: approved` **after** `product.finish()` being called.

Their subscriptions also showing up after the app starts, when `store.refresh()` is called the first time. We see that subscription they bought also has `state: approved` and calling  `product.finish()` on them take no effect.

**Comment by JefferE** [comment]
We're having this same issue ddddm, did you ever find a solution?

**Comment by ddddm** [comment]
@JefferE no solution to this. Still having subscriptions with `approved` status.

**Comment by ithav** [comment]
same issue here.
do you know if "not finishing" an approved subscription may cause issues with google billing mechanism?

**Comment by ddddm** [comment]
@ithav we have no issues with Google billing, all payments go as usual

**Comment by piin** [comment]
Hello, I have the same issue : ( did you ever find a solution @ddddm ?

**Comment by JTronLabs** [comment]
Same issue
