### ISSUE TITLE
Memory usage spike and crash on some iOS devices

### ISSUE THREAD

**Issue by brsaylor** [j3k0/cordova-plugin-purchase#484]
I am developing an iOS app with 162 in-app purchases. On my iPhone 5, I can restore purchases without issue by calling store.refresh() twice (after registering the products). However, on my client's iPhone 6+ and iPad 2, doing this causes memory usage to increase fairly rapidly from about 50 MB to about 200 MB, and then the app crashes (see attached Xcode screenshots). It's not obvious from the stack trace that the error is occurring in this plugin; I'm just suspecting it based on the timing. It doesn't matter if I sign in to the iTunes Store or not - either way, it crashes. Sometimes, Xcode itself locks up and I have to force quit.

![screen shot 2016-07-25 at 11 54 06 am](https://cloud.githubusercontent.com/assets/448997/17574682/2b574ce0-5f18-11e6-87bc-e30192a87e88.png)
![screen shot 2016-07-25 at 12 03 16 pm](https://cloud.githubusercontent.com/assets/448997/17574683/2b731cd6-5f18-11e6-9830-01458fb751a9.png)

I was using version 4.0.0 of the plugin. Updating to 6.0.0-beta did not resolve the issue. It crashes under iOS 9.2, 9.3.2, and 9.3.3.

Any help would be appreciated.

**Comment by BalticDistribution** [comment]
I have the same issue
