### ISSUE TITLE
ready event not fired

### ISSUE THREAD

**Issue by debgoume** [j3k0/cordova-plugin-purchase#486]
Hello, 

I have been struggling with this plugin for many days.

No event is fire, ready not fire, please help

My system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

There is my code : 
 initializeStore () {

   store.verbosity = store.INFO;

   store.register({
        id:    Constants.PRODUCT_ID_LESSONS_1_TO_18,
        alias: "lessons",
        type:  store.CONSUMABLE
    });

```
store.ready(function() {
   alert("Iap Ready!");
});

 store.when(Constants.PRODUCT_ID_LESSONS_1_TO_18).loaded(function(product) {
    alert("Price1:"+ product.price);
 });

 store.refresh();
```

 }

Please help

**Comment by quintessencegpy** [comment]
I have the same issue! How do you fix that?

**Comment by lincolnthree** [comment]
Just ran into this issue myself. Anyone get it figured out?

**Comment by alexnu** [comment]
Same issue here...

**Comment by lincolnthree** [comment]
Not sure what I did but I got this working. Sorry I can't be of more help.
