### ISSUE TITLE
Paid subscription iPhone

### ISSUE THREAD

**Issue by FlorisAppe** [j3k0/cordova-plugin-purchase#487]
Setting up a paid subscription for my app in the google play store (sandbox enviroment) worked like a charm. But when i tried to do the same for iOS i ran into many errors. 

It has to be an auto-renewing subscription.

I've made an auto-renewing subscription called 'premium'.

First thing i did was registering the product like this:

store.register({
          id:    "premium",
          alias: "premium",
          type:   store.AUTO_RENEWING_SUBSCRIPTION
        }

it is giving me errors at the type: store.AUTO_RENEWING_SUBSCRIPTION

any other type works, for example i've made a "test" product, with the CONSUMABLE type and that works. But i cant seem to get the AUTO_RENEWING_SUBSCRIPTION to work. 

when i type store. i get auto fill options like store.CONSUMABLE, store.PAID_SUBSCRIPTION etc. when i look into that list there isn't anything that is close to resembling the auto-renewing subscription.

So my question is, how do i register an auto-renewing subcription type product for IOS?

**Comment by flyingsky** [comment]
use type store.PAID_SUBSCRIPTION
