### ISSUE TITLE
In-App Purchases to remove Ads

### ISSUE THREAD

**Issue by jdnichollsc** [j3k0/cordova-plugin-purchase#490]
Hi guys,

I want to ask you a favor. Can you guys create a tutorial to use this plugin to remove Ads in the apps? It would be very important for hybrid developers.

PD: I'm using the following plugin to use ads with Ionic: https://github.com/floatinghotpot/cordova-admob-pro

Thanks for all, Nicholls

**Comment by chinib** [comment]
Hi Nicholls, Unfortunately I don't have the time to make an elaborate tutorial. But can give some pointers. Currently I also use Ionic(2) with admob and in-app-purchase.
I use a firebase database where the account is set. Standard every account is free. 
When the user opens the app, it will authenticate, when it is a free account it will show ads: 
AdMob.createBanner(); 
and when it is a 'premium' account it will: AdMob.removeBanner(); 

These I have wrapped in functions: showAds(); and removeAds();

When a user clicks to buy the premium: 
 if (window.cordova) {
            this._platform.ready().then(() => {
                inAppPurchase
                    .getProducts([inAppPurchaseName])
                    .then((products) => {
                        inAppPurchase
                            .subscribe(inAppPurchaseName)
                            .then((data) => {
//Change account to premium and store in db
//call removeAds();

Hope this will get you going. 

All the best, Ben

**Comment by ChristianGrieger** [comment]
I have the same problem and still searching for a solution :/

**Comment by ESA14** [comment]
You could just use the function of the plugin to remove the banner:
AdMob.removeBanner();

I did it for iOS this way:

inAppPurchase
    .buy('de.esa.iab_test2')
    .then(function (data) {
    console.log(data);
    /*
      {
        transactionId: ...
        receipt: ...
        signature: ...
      }
    */
   AdMob.removeBanner();
  })
  .catch(function (err) {
    console.log(err);
  });

**Comment by robingatchalian** [comment]
please show where and what code to put, after installing the plugin dont know what to do

**Comment by Dexus** [comment]
Simple code snipped:

```js
store.register({
    id: "ID.of.removeAdsAlias",
    alias: "removeAdsAlias",
    type: store.NON_CONSUMABLE
});
function unlockAppWithoutAds (p) {
// remove here the ads
}
store.when("removeAdsAlias").owned(unlockAppWithoutAds);
```
