### ISSUE TITLE
Authentication is required?

### ISSUE THREAD

**Issue by jdnichollsc** [j3k0/cordova-plugin-purchase#493]
Hi guys,

I'm debugging my app in debug mode using GapDebug, and my app have authentication with Google and Firebase, but testing the method **store.order('id')** appears the following error:

![14067746_10154068461224331_7682725489537126658_o](https://cloud.githubusercontent.com/assets/2154886/17957612/c9155e9a-6a58-11e6-87c0-7adb0b615bfd.jpg)

What is the error? :(

Thanks in advance, Nicholls

**Comment by scrakcho** [comment]
This problem maybe can be caused by not published app as Beta, Alpha or Production in the Google Dev Console (remember few hours is needed)

**Comment by rubinchyk** [comment]
Unfortunately, it's not a this dependence. My app registered 3 days ago and I have this problem.
