### ISSUE TITLE
Product invalid (sometimes)

### ISSUE THREAD

**Issue by anykeysolutions** [j3k0/cordova-plugin-purchase#494]
Hello

We just got our app approved to the app store. However, we have the problem that our in app purchases sometimes get a product invalid message from the store. 90% of the times it works without a problem, but the rest of the time we get an product invalid from the store and can't show the product.

Anyone else had this problem?

Marc

**Comment by malloc32** [comment]
Yes, and I don't know how to refresh again to get a valid product (title, description, price....), Second refresh is different and does not reload data to get a valid product...
Any solution? Thank you
