### ISSUE TITLE
product.approved not firing on Android 5.1.1

### ISSUE THREAD

**Issue by elektray** [j3k0/cordova-plugin-purchase#500]
Hello,

I was wondering if anyone experienced the same problem I have.

When the store.get() is fired, purchase request it made and I'm shown Andoroid standard flow for purchasing the item. I'm shown with a confirmation modal and I receive a billing email from Google Play. 

But...

The product.approve() function doens't fire and the functions I have set to finish the transaction (unlock content in my case) don't run.

I've tested the apk as an alpha tester on a device with a different account from the dev one.

Any help will be awesome!

Thanks

**Comment by aesculus** [comment]
Is this the same issue?

https://github.com/j3k0/cordova-plugin-purchase/issues/497

**Comment by scrakcho** [comment]
Hi,
In all my android devices 5.1 and 6.0 this error is present, it´s my resumed code...
`
angular.forEach(productos,function(producto,key){
            var id=producto.storeId;
            var type=store.NON_CONSUMABLE;
            console.log('Registrando producto: '+id);            
            store.register({
                id:    id,
                type:  type
            });
        });
this.order = function(rute){
        angular.forEach(productos,function(producto,key){
            if(producto.nombre == rute){
                var store_ID = producto.storeId;
                product = store.get(store_ID);
                var estadoCompra = product.owned;
                if(estadoCompra){
                    $rootScope.descargable = true;
                    $rootScope.comprable = false;
                }else{
                    store.when(store_ID).approved(function (order) {
                        doDownloable(store_ID);
                        console.log('Buy finished',order);
                        order.finish();
                    });
                    store.order(store_ID);                   
                }
            }
        });

    };
this.order(store_ID);`

approved event not fire when google process finish correctly...

**Comment by j3k0** [comment]
I don't see `store.refresh()`, maybe it's just not in the short-version of your code

**Comment by elektray** [comment]
I solved the problem by reading a few issues raised in the pass. The secret is to follow the right order:

1) register products

2) store.when("product").updated(function (product) {
        if(product.loaded && product.valid && product.state === store.APPROVED){
           product.finish();
         }
3)    store.refresh();

4) store.when("productZ").approved(function (order) {
         console.log("You just unlocked productZ");
         order.finish();
         });

5)     store.when("productZ").updated(function (product) {
        if(product.loaded && product.valid && product.state === store.APPROVED){
           product.finish();
         }
        console.log('I' m rendering  productZ");
        render(product);
    })
