### ISSUE TITLE
Help to set up a content area closed for ios

### ISSUE THREAD

**Issue by rafaelso86** [j3k0/cordova-plugin-purchase#502]
Hello

I'm starting with the development of applications with Phonegap and I have a problem , I need to set up a form of signature in an application.

I found this plugin and the rate of downloads seems to be what people have used more .

I wonder if there is a tutorial of how to display a closed content, signature buttons and release simply content.

Thanks for the help.

**Comment by j3k0** [comment]
Hi @rafaelso86 this plugin lets user purchase virtual products. If your virtual product is the right to access the closed area, then it looks like it's for you. Read out through the documentation, it explains in details how it works.
