### ISSUE TITLE
Installation Service needed

### ISSUE THREAD

**Issue by ChristianGrieger** [j3k0/cordova-plugin-purchase#506]
Hey all, Hey j3k0,

i know this is the issues ticker but i dont know another way to get in contact.

Is there someone out who could help me to integrate the purchase option into my intelxdk app so it works for ios and andorid over teamviewer?

I have all needed up and running and would need an option to make a fullversion buy avaliable in my app. I am open to pay for this.

Greetings,
Christian

**Comment by j3k0** [comment]
Hi @ChristianGrieger, never used IntelXDK here, so I may not be of much help for the installation part. The topic has been talked about though, did you run a search on issues? I also found [https://software.intel.com/en-us/videos/monetization-with-intel-xdk-inapp-purchasing](this demo video), apparently IntelXDK provides a "hello-inapppurchase" demo.

**Comment by ChristianGrieger** [comment]
Hey j3k0,

yes i found that solution and its integrated :) 

All seems to work well for andorid just the purchase fails without an error.

github.com/gomobile/sample-in-app-purchase/issues/1

Maybe you could check into my teamviewer and see the problem? :) Add me on skype if you have some minutes for me: ticer89

Greetings,
Chris
