### ISSUE TITLE
How to know when refresh process has ended

### ISSUE THREAD

**Issue by malloc32** [j3k0/cordova-plugin-purchase#511]
How is posible to know when refresh process has finished?.
This feature is useful to show progress bar, modal layer....
Thank you.

**Comment by cmgchris** [comment]
is store.ready() what you are looking for?

**Comment by malloc32** [comment]
It is not enough, for example when you are waiting for verification response store.ready()=true :(
At the moment I use a timer that is touched when a product has been updated, but this is a bad solution when you are waiting http responses (offset of seconds, I add a timer gap, but...how long?)... but at the moment is my 'best' solution, but a very bad solution...
Thank you.

**Comment by davidanquetin** [comment]
Hello, I am also looking for a way to have a callback when refresh is ended (for restore operation on many products)
