### ISSUE TITLE
IOS - login popup multiple times

### ISSUE THREAD

**Issue by John0x** [j3k0/cordova-plugin-purchase#514]
Hey,
I've got a critical problem with the newest ios version. 
Upon refreshing (store.refresh()) the app asks the user to login to itunes (the login popup opens) but it does that twice, even when the correct data is entered. I had a similiar problem with another cordova inapppurchase plugin (the popup kept showing without end).

Is this a known issue or is it caused by my code?

`
return new Promise((resolve, reject) => {
 store.refresh();
 resolve();
});
`

**Comment by scrakcho** [comment]
Same problem here... pop up fires multiples times...

**Comment by John0x** [comment]
anything new about this?

**Comment by JWesorick** [comment]
Is there any work around for this issue?

**Comment by j3k0** [comment]
Hello, this might not be your issue, but it's worth knowing that it happens in development, if iTunes is logged in non-sandbox mode (happens when any other app checks something with iTunes). The same behavior can't happen in prod. It's one of StoreKit's SDK rough edges... I'm not 100% sure you're not facing a more complex issue, but I've seen this one happening more often than not.

**Comment by karuppasamypandian0856** [comment]
Hello, @j3k0 your answers right that popup issue not appear in production.Currently my app in live.
Thank you.

**Comment by adriano-di-giovanni** [comment]
I'm facing the same issue and I know for sure it's also a production one. I thought I could delay plugin initialization upon _restore purchases_ or _purchase_ button is clicked but I found that popup still fires. Is this information new? Any ideas about it? Can I investigate further? If so, how?

**Comment by adriano-di-giovanni** [comment]
Does anybody of you use GoogleMobileAds SDK for iOS? If so, try to delay the store initialization. Does the popup still fires? If so, try to add

```objectivec
[GADMobileAds disableAutomatedInAppPurchaseReporting];
```

to your AppDelegate

Does the popup still fires?
