### ISSUE TITLE
Multiple order / Auto-renewable purchase

### ISSUE THREAD

**Issue by jcornic** [j3k0/cordova-plugin-purchase#515]
Hi!

I have an app with 2 inapp purchases available (inside the same subscription group). A monthly subscription & a yearly subscription (both auto-renewable).

I've successfully ordered a subscription, but If I want to change to the other one, I will have 2 "owned" subscriptions, instead of upgrading or downgrading (and cancelling the previous one). Is it normal?

I also don't know where to check how many times the purchase has been renewed, any help?

Thanks

**Comment by anhlhv** [comment]
I am having this same problem

**Comment by Jay031** [comment]
@jcornic  sorry to bother, but I'm desperately searching for a solution to get an Auto Renewable Subscription to work in iOS see #538 
Did you manage to get this to work? If so, could you please help me out?

**Comment by jcornic** [comment]
I've just made it work with some code tuning...
Do you use a validation server?
