### ISSUE TITLE
App stuck while store.refresh

### ISSUE THREAD

**Issue by furuihe** [j3k0/cordova-plugin-purchase#517]
I am quite new to IAP，so after created some consume products, i use the mini-example and call store.order in app, all works fine until now. but my app stuck while retart and call store.refresh, even though reinstall it, app can work only if i remove store.refresh. 
How can i fix it and let my app work again, please?
env:
  cordova-plugin-purchase: 6.0.0
  ionic: 1.3.0
  cordova-ios: 4.1.1
  cordova:  6.1.1

**Comment by websamsara** [comment]
We're having this problem too. It's just happening on Android and seems fine in iOS. It's related to the subscription products for us. It seems to get stuck at the "owned" check. Still trying to figure out if it's just a problem with the beta testing or maybe it doesn't have the same problem when actually published.

**Comment by Jay031** [comment]
Can you provide a small code example? I've had some trouble (not the same as you guys), but I managed to get everything to work in both iOS and Android.
