### ISSUE TITLE
Works on tests, crash on released

### ISSUE THREAD

**Issue by ammichael** [j3k0/cordova-plugin-purchase#520]
Hello guys!

First, I wanna thank you for this awesome plugin. Thanks! (:

I've sent my first IAP and it's been released in App Store, but strangely it is crashing. I've tested in my device again, but here it works perfectly. I can't debug the App Store release, so I have no logs about what is happening.

Any idea? Any help?

**Comment by j3k0** [comment]
Are you sure you submitted your IAP when submitting the build for release?

**Comment by ammichael** [comment]
Pretty sure. Actually, I think it is only crashing in my phone. Hope so..

**Comment by antonfire** [comment]
@ammichael I'm having the same issue, did you fix it?

**Comment by ammichael** [comment]
@antonfire I should've updated here..

It was crashing only in my phone. Maybe because of my iTunes accounts, probably you can't try to really buy it in the same phone you've tested the IAP, not sure why, but.. In every other phone I've tried, worked fine

**Comment by antonfire** [comment]
Thanks

**Comment by jcornic** [comment]
I have the same problem here.
It was working fine in developer mode & on testflight. 

When it was in production, the transaction was made until the end, but the product was never "owned". At each startup, the product state was owned:false and if store.refresh() was called, the app was crashing...

I have had to take this version away from the store... 
Any idea on what was going on?

Here is the log of the startup of the application (although the user had a subscription)
Jan 11 21:46:18 iPhone-XXX[2746] <Notice>: LOG: INAPP: registerProducts
Jan 11 21:46:20 iPhone-XXX[2746] <Notice>: LOG: INAPP: renderIAP: {
    "id": "abo_month",
    "alias": "abonnement mensuel",
    "type": "paid subscription",
    "state": "valid",
    "title": "Premium mensuel",
    "description": "XXX",
    "price": "2,99\M-B\240\M-b\M^B\M-,",
    "currency": "EUR",
    "loaded": true,
    "canPurchase": true,
    "owned": false,
    "downloading": false,
    "downloaded": false,
    "transaction": null,
    "valid": true
}
Jan 11 21:46:20 iPhone-XXX[2746] <Notice>: LOG: INAPP: updated: unsubscribed

**Comment by ammichael** [comment]
@jcornic have you tried on a completely different iPhone? I can't buy my own IAP. When I try, it crashes and behaves just like you described. Changing the iTunes account doesn't help either, but in a different iPhone, with different iTunes account, works fine.
