### ISSUE TITLE
Windows 10 InAppBillingPlugin init error

### ISSUE THREAD

**Issue by ivanina** [j3k0/cordova-plugin-purchase#521]
On Win 10 (Universal Windows platform) I got an error:
`Exception calling native with command :: InAppBillingPlugin :: init ::exception=WinRTError: Unknown runtime error`

Sandbox is false.
Windows store has been set up and added product as add-ons.
The project deployed to testing remote device.

When sandbox is TRUE - I got another error:
`ERROR 6777001: Init failed - undefined`

Works fine on Android and iOS.

Thank you.

**Comment by krooshua** [comment]
Same issue, plugin compatible with Windows 10 (UWP)?

**Comment by ivanina** [comment]
With Windows 10 (UWP) works fine.
I re-setup products on WinStore and spend one day I could buy the product.
My problem was in setup product on Windows Store.

**Comment by franalt** [comment]
How did you do that? Im really struggling to get this working.
