### ISSUE TITLE
android button click in app purchase

### ISSUE THREAD

**Issue by Winston001** [j3k0/cordova-plugin-purchase#528]
Im new to cordova plugins and all. I have set a consumable product from inapp purchase store.Now I call the function of registering in store function .But I dont know ,how to implement correctly. Please help me ,I didnt any results .

**Comment by Jay031** [comment]
Hi, do you still have this problem? This is not a bug/issue, so maybe you should look/post on stackoverflow or at least post code-examples here so we now what you have and where you're stuck.
