### ISSUE TITLE
Authentication is required. - and no way...

### ISSUE THREAD

**Issue by rubinchyk** [j3k0/cordova-plugin-purchase#529]
Have this code:
```
document.addEventListener("deviceready", billing, false);

        function billing() {
             store.verbosity = store.INFO;

             store.register({
                id:    "com.company.nameapp.prod1",
                alias: "citrin1",
                type:  store.NON_CONSUMABLE
            });

			store.when("com.company.nameapp.prod1").approved(function(order) {
				alert('approved');

				order.finish();
			});
        
            store.ready(function() {
                alert("\\o/ STORE READY \\o/");
            });

			 store.error(function(error) {
				alert('ERROR ' + error.code + ': ' + error.message);
			}); 

             store.refresh();

			 $scope.buy = function() {
				$scope.buyField = store.order('com.company.nameapp.prod1');
			 } 
        }		
```

And when I click to buy product, have this error: 
[http://i.stack.imgur.com/g8FVk.png](http://i.stack.imgur.com/g8FVk.png)

"Authentication is required. You need to sign in google account"

What is that and how to solve it? Because very important to create this feature...

**Comment by palmtreeint** [comment]
Having the same issue and it's identical to issue #150 for this plugin. I'll let you know if we figure it out with this app. There are alot of prerequisites so that's the beginning.

**Comment by palmtreeint** [comment]
One thing I notice we have in common is that there is no way to restore purchases.

**Comment by petarov** [comment]
@rubinchyk 

Make sure of the following:

1. You have uploaded and published **alfa** or **beta** version of your app in PlayStore with the BILLING_KEY enabled
2. You have created a test gmail account and added it to **Settings** -> **Gmail accounts with testing access** in your PlayStore Publish console. You can **only test** (buy) IAP with a non-developer account.
3. You can only (buy) IAP using a signed APK. It has to be signed with the same certificate used for publishing to alfa or beta.

Hope that helps.

**Comment by rubinchyk** [comment]
Fixed. Very simple mistake. 

Products id! Instead of: 
 store.register({
                id:    "com.company.nameapp.prod1", ...

Need to write:
               store.register({
                id:    "prod1", ...

And after sign, zip. publish download this version - I have modal window with buying!
