### ISSUE TITLE
Owned property of product is always false

### ISSUE THREAD

**Issue by Stefan3001** [j3k0/cordova-plugin-purchase#532]
I'm facing the following issue:

I have uploaded my android app for alpha testing. Then I have downloaded my app from the play store and successfully complete an in app purchase (approved() gets called). My code looks like this:
`store.order("myItem");`
`store.when("myItem").approved(function(product) {`
            `       product.finish();`
            `       me.__myItemSuccessfulPurchase();`
        `});`

On the next start up of my app I am validating if the item has already been purchased:
`store.register({`
       `     id:    "my_item",`
         `   alias: "myItem",`
       `     type:  store.NON_CONSUMABLE`
    `    });`
    `    store.refresh();`
  `      store.get("myItem").owned;`

But despite the successful purchase the owned property of my product is false. Is there anything I'm missing?

**Comment by gandonov** [comment]
Yeah I'm facing similar issue. Seems like consecutive refresh calls do invoke finished callback, 
but store.('myItem').owned is false. @Stefan3001 did you have any luck with this?

**Comment by Stefan3001** [comment]
No, still stuck... Anyone else having an idea?

**Comment by htsnet** [comment]
+1

**Comment by davidanquetin** [comment]
I have the same problem, products which have state = approved have not owned =true.
I forced it with 
`store.when('product').updated((product) => {
		if(product.state === "approved"){
			product.finish();
              }	
});`

**Comment by ClementBu** [comment]
Hello,
Thanks for this plugin, it is very usefull and well thought!

But I have the same issue here. Tested in a published test app and the owned property is always false.

Also, I don't know if it is related but, even if you specify type.NON_CONSUMABLE, the type of the product I get after refreshing the store is "consumable:", maybe I am doing something wrong though, here is my code:

```
            store.register({
                id: 'my.prod.id',
                alias: 'my_prod',
                type: store.NON_CONSUMABLE
            });

            store.when('my_prod').updated(function() {
                var myProd = store.get('my_prod');
                console.log(myProd); // ==> {"id":"my.prod.id", ... , "type":"consumable", ...} <==
            });

            store.refresh();
```

**Comment by charlesbodman** [comment]
+1
