### ISSUE TITLE
Error during start app

### ISSUE THREAD

**Issue by AlexDag** [j3k0/cordova-plugin-purchase#533]
I have the error "the in-app purchase plugin is not available" during start app.
Could you help me, please, what happened?
It's cordova iOS project

thamnks

**Comment by kriserickson** [comment]
Sounds like plugin isn't getting installed (this happens a lot with cordova plugins, though less often these days).  Try doing 

```
cordova plugin rm cc.fovea.cordova.purchase
cordova plugin add cc.fovea.cordova.purchase
```

and try again.

**Comment by j3k0** [comment]
Is your issue fixed?

**Comment by Dexus** [comment]
Closed as of no response.
