### ISSUE TITLE
store.refresh() needs to be called twice

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#536]
Hi,

I have a "Restore purchases" button which calls `store.refresh()`, but it seems I have to hit the button twice to get `product.owned` set to `true`? Is that by design, or am I doing something wrong? This is If I'm not already signed in to iTunes. When signed in, it appears to work as expected.

Also, I notice the `product.id` is set to my bundle id when this happens (#464?).

**Comment by j3k0** [comment]
Do it doesn't have to be called twice. Do you "finish" the purchases after they've been approved? (cf related documentation)

**Comment by remisture** [comment]
Yes, something like this:

```
store.when("product").approved(function (product) {
   product.finish();
});
```

**Comment by juergengunz** [comment]
same issue for me, @remisture did you solve that?

**Comment by albertleao** [comment]
Facing same issue

**Comment by remisture** [comment]
No, I have not managed to solve this yet. Please let me know if you come across a work around :)

**Comment by amokrunner** [comment]
+1

**Comment by haxxxton** [comment]
Not sure if this is the same issue you're encountering, im finding this issue only happens under some circumstances.
On iOS.

1. be logged out of the apple store in settings
2. open app and click restore purchases
3. initial login window appears.. quickly followed by a new prompt to either 'Use existing Apple ID' or 'Create a new Apple ID' or 'Cancel'
This is where things deviate for me:
3A. Click 'Use existing...' prompt returns to initial login window..
4A. Login as usual
5A. restore callback works as expected
----
3B. Click 'Create new..' prompt switches to app store to create new Apple ID..
4B. store ERR_REFRESH fired
5B. no callback fired
---
3C. Click 'Cancel'.. prompt returns to initial login window..
4C. store ERR_REFRESH fired
5C. Login as usual
6C. no callback fired
7C. click restore purchases.. no login prompt.. restore callback works as expected
---

To me this appears to be that migration away from the actual flow of logging in (ie. creating a new account) or clicking cancel on either prompt (despite the second prompt returning you to the login prompt when clicked) fires the failed callback

**Comment by Defcon0** [comment]
Same here, but only on iOS. I have to call refresh() twice. The first one doesn't trigger approved callback.

**Comment by bhaskar-se** [comment]
Having the same issue. Did anyone find any solutions?

**Comment by Kamsou** [comment]
+1

**Comment by j3k0** [comment]
Hi, never call `store.refresh()` twice, or your users will be asked for their appstore password every time they start the app.

Something else has to be incorrectly setup in your app. `product.owned` is set to true after the purchase has been verified and finished.
