### ISSUE TITLE
Google Play - After purchase, order id issue

### ISSUE THREAD

**Issue by belgarad** [j3k0/cordova-plugin-purchase#542]
Google Play - After purchase, order id is not returning.. 

returning transaction :

'transaction':{
'type':'android-playstore','purchaseToken':'dmg','receipt':'{\'packageName\':\'com.MobileApp\',\'productId\':\'com.point_1000\',\'purchaseTime\':1482927076223,\'purchaseState\':0,\'purchaseToken\':\'dZpyhNklhg\'}','signature':'OGmX='}

**Comment by zsoi** [comment]
I have the same issue, what was the cause?

**Comment by belgarad** [comment]
google doesnt send order id in testing mode. that was suprised to me. i thought it was an error. its really strange but google does this.
