### ISSUE TITLE
When to track transactions in Google Analytics?

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#545]
Hi,

In which lifecycle method should adding GA measuring of transactions from purchases be? `finished`? `owned`? Whats important here is that this only happens once, so i guess `finished` is what i'm looking for?

Is there any examples of this anywhere?

https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce#addTrans

**Comment by juergengunz** [comment]
@remisture what did you end up doing?

**Comment by Dexus** [comment]
I personally would trigger that in finished. Please close this issue when you solved it or I will close it in some days if no other questions or answers of it.

**Comment by remisture** [comment]
I have not implemented this yet. For now, I measure the InApp purchases as events in GA. Something like this:

```
store.when("product").finished(function(product) {
    if (product && product.id !== "xx.xxx.MyBundleId") {
      GAservice.trackEvent("InApp", "Finished", product.id);
    }
  });
```

But this this is not working as intended. This fires waaaay too often, so my GA reports and App Store/Google Play reports are very different.

**Comment by svzi** [comment]
Any news on this? Was anyone able to track the right metrics? @remisture @Dexus @juergengunz

**Comment by remisture** [comment]
No, unfortunately not. Please let me know if you find something :)
