### ISSUE TITLE
Working fine in test mode, but weird behaviour in production...

### ISSUE THREAD

**Issue by jcornic** [j3k0/cordova-plugin-purchase#546]
Hi!

I've been working last few weeks on implementing the plugin with auto-renewable subscription, I thought everything was fine (I've tested everything in sandbox & testflight and it worked), but on production it doesn't work as expected:
- the process of purchase works well (user account is charged)
- but the product never goes to "owned" status

On application start, it just fires once store.when("product").updated with owned:false, and that's it. If i try to call "store.refresh();" it crashes the app...

Any idea on what's going on?

**Comment by zhang024** [comment]
Hi,

 

I am working on same thing, please change another Apple account to test it, somehow if your Apple account has unfinished purchase, then it will run into strange problem.

 

If does not go into owned status, normally means that you did not get p.findish() method fired.

 

Thanks,

 

Sean

**Comment by jcornic** [comment]
I've just resolved the issue.
The validation file on my server was configured with Apple sandbox URL instead of production URL...
