### ISSUE TITLE
How to set up own webservice to validate receipts?

### ISSUE THREAD

**Issue by ekntrtmz** [j3k0/cordova-plugin-purchase#549]
I really need some help to setup my own webservice to validate receipts, because I do not want to pay for it...

Basically, I just need to understand how I have to use this [Node.js Module ](https://github.com/voltrue2/in-app-purchase) with [this part of the documentation (store.validator)](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validator).

Any help is greatly appreciated

**Comment by piin** [comment]
Hi @ekntrtmz, I am using this  https://github.com/j3k0/cordova-plugin-purchase/issues/431 and it works,

**Comment by ekntrtmz** [comment]
@piin Thank you :)
Using your code from #431 for Android: How can I set the product state back to valid from owned, if the subscription is expired?

As I have understood the server will return $code = 0 in the case, that it is not verified (== expired) right?
How to take that and interact with the product life cycle?
