### ISSUE TITLE
Async problems during purchase process present errors for users

### ISSUE THREAD

**Issue by shaifd** [j3k0/cordova-plugin-purchase#552]
Our application uses the plugin to enable in-app subscriptions on both iOS and Android. We recently got an error from an Android user that a purchase failed but her card was charged. We checked the logs and saw that the failure we saw was the our verification process did not get the Google Play transaction-id. Looking earlier in the code - it seems that there was an error in the app with the following message:

platform Android, caller general-store-error-handler/isFamiliarError=true, ; stringified object is: {\"code\":6777010,\"message\":\"Can't start async operation (consume) because another async operation(launchPurchaseFlow) is in progress

We have seen that there was an old issue open for something similar in the plugin but did not see any resolution. Is there a fix we need to apply or do something else in our App to avoid this situation?

**Comment by cdcv** [comment]
We have seen the same behavior.  Working on resolving it.
