### ISSUE TITLE
How to get products?

### ISSUE THREAD

**Issue by Script47** [j3k0/cordova-plugin-purchase#555]
As the title suggest's,  can someone please show me in the most minimal amount of code, how I can simply display products,  even if it just through alerts. I can't seem to get it to with for Android.

**Comment by Dexus** [comment]
Have please a look to the docs and examples.

It is not really difficult, when you read the stuff.

**Comment by Script47** [comment]
There are many issues where people have questioned about how to actually get the products, the documentation is unclear and confusing. Please review it and update it for people instead of closing issues.

**Comment by j3k0** [comment]
@Script47 it seems not to be your case, but many people post issues before reading through doc. @Dexus has been doing an amazing job cleaning up the pile of issues last couple of days.

Please read "Getting Started" https://github.com/j3k0/cordova-plugin-purchase#getting-started

There are links to a minimal example and a more complete example. Once you got the complete example to work on your device, you can change the product id to see if you can load your own products or if you still missed some required setup steps...

Good luck, and once you get there, please help us improve the doc we have been confusing! It's open source.

**Comment by Script47** [comment]
@j3k0 No problem, please keep this issue open so I can query certain things if need be, rather than creating too many issues.
