### ISSUE TITLE
store.get() not returning data from app store

### ISSUE THREAD

**Issue by Flaise** [j3k0/cordova-plugin-purchase#556]
I'm trying to get this plugin working for Android and `store.get()` never appears to be returning data that I have set up in the app store. At the beginning of the app, I'm running the following code:

    document.addEventListener('deviceready', function() {
        // Irrelevant code omitted...
        store.register({
            id: 'premium',
            alias: "Upgrade to Premium",
            type: store.NON_CONSUMABLE
        });
        store.when('premium').updated(app.premiumUpdated);
        store.when('premium').approved(function(product) {
            app.premium = true;
            product.finish();
        });
        app.premiumUpdated();
    }, false);

`app.premiumUpdated` is a bound method that updates the GUI with information from a product object returned from `store.get('premium')`. All of the data appears to be the defaults: the product is not owned, the title is an empty string, the price is an empty string, canPurchase is false, etc. The only field that is populated is `alias`, which appears to come from my own code: `alias: "Upgrade to Premium"`.

The product is already activated in the app store and it has the id "premium", same as what I'm trying to look up on the client side. I uploaded the APK in alpha testing mode and it outputs the same lack of results as when I'm testing.

Is there something I'm misunderstanding about the API or can you give me an idea of how to go about troubleshooting this?

**Comment by matthieu80** [comment]
Hi @Flaise ,
Have you found a solution to this issue?
I have the same problem, getting stuck right at the beginning of my implementation because the products are simply not fetched from the store.

**Comment by Pawnchich79** [comment]
No

**Comment by Dexus** [comment]
Hey where is your `store.refresh();` after register and listeners? Without it will not work. Look https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/example.js or https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/ios.md at end of page and read the comment.
