### ISSUE TITLE
An update on Google Play refunds and a change to Google Play Developer API terms of service

### ISSUE THREAD

**Issue by giggioz** [j3k0/cordova-plugin-purchase#557]
I think the plugin should take this in account, or does it already?

Hello Google Play Developer, 

In order to keep Play fair for users and developers, and bring Play in line with the majority of app and game stores in the industry, we are making a change to our developer policy regarding refunds. We will subtract all refunds from developer payouts, not just those made within 48 hours of purchase. The Google Play Developer Distribution Agreement ("DDA") will be updated to reflect this change in the coming months.

With the same goal in mind, we’ve just launched the Voided Purchases API to help you maintain a fair ecosystem in your app or game.

With the new API, you can check which users have refunded or charged back in-app purchases in order to claw back those items for that user in your app or game. This change helps to deter abusive behavior and will make the ecosystem fairer for all users. 

We updated the Google Play Developer API terms of service to include the terms governing the use of this new API. By using the new API, you indicate your agreement to these terms.

**Comment by rafaellop** [comment]
Here is more information about the Voided Purchase API:
https://developers.google.com/android-publisher/voided-purchases

@j3k0 I'm awared of the plugin's canceled and refunded events and it would be enough for now to know if these events handle the new Google API and can be used "to help you maintain a fair ecosystem in your app or game" :)
