### ISSUE TITLE
iOS Settings Restrictions null product fields

### ISSUE THREAD

**Issue by apparition47** [j3k0/cordova-plugin-purchase#559]
# Env
cc.fovea.cordova.purchase - Using 6.0.3+ (commit 566ce4b)
cordova-ios 4.3.1
iPhone 6 Plus iOS 10.2.1
Ionic 2.1.0
OneSignal-Cordova-SDK - Using 2.0.11+ (commit [42483b7](https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/42483b7b6812d86f1e8918facb05838b3b18d799)) to fix iOS IAP crashes

# Issue
Plugin works great.

However, I'm running into one case with with Apple App Store Review rejecting my app because my IAPs aren't showing up properly with the fields populated (`price` and `title` are missing). I suspect they may have Restrictions turned on (iOS Settings > General > Restrictions > Enable Restrictions > Allow In-App-Purchases: NO). When I restrict IAPs in the manner and view `store.products`, I can see fields like `price` and `title` are null. 

I notice other native apps show title and price even with iOS Restrictions on. Is there any way to have these fields populated with iOS Restrictions on with this plugin?

![](http://a1474.phobos.apple.com/us/r30/Purple111/v4/fd/5b/fd/fd5bfdb3-e534-7d09-d661-f5c9e711755d/attachment-2223029569445938380IMG_0148.PNG?downloadKey3=1488421296_924d5518bb55feac8826191d69526be3)

# Debug log, code sample

```typescript
constructor(private platform: Platform) {
     // same as deviceready
    platform.ready().then(() => this.initStore());
}

// 
initStore() {
    // load available products by this device's appstore
    let prodIds = [];
    if (window.cordova && cordova.platformId === 'ios') {
        prodIds = [
            {
                id: 'com.example.a',
                type: store.CONSUMABLE,
                alias: 'a'
            },
            {
                id: 'com.example.b',
                type: store.CONSUMABLE,
                alias: 'b'
            },
            {
                id: 'com.example.c',
                type: store.CONSUMABLE,
                alias: 'c'
            }
        ];
    }

    // Enable maximum logging level
    store.verbosity = store.DEBUG;

    // Inform the store of your products
    prodIds.forEach(prod => store.register(prod));

    store.validator = (product, callback) => {
        console.debug('IAB-validator', product);
        // ...
    };

    store.when("product").approved(product => {
        product.verify();
    });

    store.when("product").verified(product => {
        console.debug('IAB-verified', product);
        product.finish();
    });

    store.when("product").unverified(product => {
        console.debug('IAB-unverified', product);
        product.finish();
    });

    store.refresh();
}

getProducts() {
     return store.products; // *** see output below ***
 }
```

```html
<ion-list no-lines>
    <ion-item *ngFor="let iap of iapList"><!--iapList populated by getProducts() above -->
        <h2>{{iap.title}}</h2>
        <button ion-button item-right outline (click)="onSelectIap(iap)">{{iap.price}}</button>
    </ion-item>
</ion-list>
```
```js
// after register() and refresh()
// window.store.products =
[{
	"id": "com.example.a",
	"alias": "a",
	"type": "consumable",
	"state": "registered",
	"title": null,
	"description": null,
	"price": null,
	"currency": null,
	"loaded": false,
	"canPurchase": false,
	"owned": false,
	"downloading": false,
	"downloaded": false,
	"additionalData": null,
	"transaction": null
}, {
	"id": "com.example.b",
	"alias": "b",
	"type": "consumable",
	"state": "registered",
	"title": null,
	"description": null,
	"price": null,
	"currency": null,
	"loaded": false,
	"canPurchase": false,
	"owned": false,
	"downloading": false,
	"downloaded": false,
	"additionalData": null,
	"transaction": null
}, {
	"id": "com.example.c",
	"alias": "c",
	"type": "consumable",
	"state": "registered",
	"title": null,
	"description": null,
	"price": null,
	"currency": null,
	"loaded": false,
	"canPurchase": false,
	"owned": false,
	"downloading": false,
	"downloaded": false,
	"additionalData": null,
	"transaction": null
}]
```

**Comment by Dexus** [comment]
@j3k0 can you look here
https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L285

I think this is the problem for some iOS problems, we need to add the function to the purchase functions and remove from setup.

**Comment by j3k0** [comment]
@Dexus you are right, the mentioned line prevents initialization, so loading items won't work.

A simple solution would be to just not show the in-app purchases at all when payments are disabled, for example if setup failed...

Few ideas, from easy to hard.

1. tell developers to hide access to their purchase pages until the product is loaded (`when("product").loaded(function unlockPurchasePage() { ... })`)
2. export the `initialized` boolean: https://github.com/j3k0/cordova-plugin-purchase/blob/ce0b29c94945b3294aea4dc46461c63e8fc7f2d6/www/store-ios.js#L2726
   - dispatch an event like `"initialized"` when it becomes true.
   - tell developers to hide access to their purchase pages until `initialized` becomes true.
3. allow setup to run even when `StoreKit.canMakePayment()` is false. Export a javascript `store.canMakePayment` boolean value (on all platforms), so devs can grey-out their purchase buttons.

**Comment by Dexus** [comment]
Hi @j3k0 

Okay, so i think we remove the mentioned line and use the `3.` because this is already exported as a function as far as i know ([store-ios.js#L2182](https://github.com/j3k0/cordova-plugin-purchase/blob/ce0b29c94945b3294aea4dc46461c63e8fc7f2d6/www/store-ios.js#L2182)). 
This gives the developer more handling options. And we can use the function internal when purchase is made and blocked automatically internal.So we only need to use it once initial and can then prevent the purchase and/or create an alert or something different.

A other Approach will be to tell the developer to check self against the `store.canMakePayment` and take care about the right handling. Where we only use iOS and send fake on Android and Windows as long there is no similar implementation.

**Comment by Dexus** [comment]
ping

**Comment by j3k0** [comment]
A year later... ;-)

I agree with you, it should be solved by documentation.

`1` makes sense in all cases: when product definitions can't be loaded from the store, the page that's supposed to display them should not be accessible, or display a warning like: "You cannot make purchases at this stage. Try again in a moment. Make sure you didn't enable In-App-Purchases restrictions on your phone."

Exposing the `canMakePurchases()` function would be a way to make the above message more specific.
