### ISSUE TITLE
How plugin works without internet and what happening when internet comes back?

### ISSUE THREAD

**Issue by centrual** [j3k0/cordova-plugin-purchase#562]
Hello everybody,

I'm trying to make an app that can work offline. Interestingly, this plugin seems automatically handle it, but i can't figure out how?

Can you help me? How the plugin handle it?

**Comment by cmohanraj10** [comment]
This plugin requires internet connection. Plugin will show the message if there is no internet connection.

![error1](https://user-images.githubusercontent.com/7069726/27032545-2daa9ef4-4f2a-11e7-93dc-4965ef05ea9c.png)
