### ISSUE TITLE
Anyone knows if in-app purchases work within the IOS simulator?

### ISSUE THREAD

**Issue by juanvillegas** [j3k0/cordova-plugin-purchase#563]
Using the latest xcode and IOS versions, do you know if its possible to test IAP in a simulated device? Or do I have to get a real one? Following the docs but they only refer instructions for real devices..

btw, I keep getting different errors, thats why I'm thinking its just not available, like the following:

![image](https://cloud.githubusercontent.com/assets/773149/23977291/23315b0a-09cc-11e7-9611-a90d9ad5407c.png)

Thanks!
Juan

**Comment by j3k0** [comment]
It's in the FAQ: simulator not supported.
