### ISSUE TITLE
iOS auto-renew subscriptions never approved() if credit card needs updated

### ISSUE THREAD

**Issue by gylippus** [j3k0/cordova-plugin-purchase#564]
I'm still working to get more debug and log information today, but wanted to open this up to see if anyone else was experiencing the same issue. 

Our purchases have been working great (thanks for this @j3k0), except for when a user is asked to update their credit card information during the purchase process. When this is the case, 
`approved()` is never called, so we have not been able to know when their purchase is complete and we should be unlocking features for them. 

Hoping I'm able to get some info even with a sandbox purchase in the next few hours. 

Anyone else seen anything similar?

**Comment by juxfr** [comment]
I have the same issue but not particularly if credit card needs an update. The payment is processed, but the purchase is never approved. So the user has paid for the service, but doesn't see any change... It doesn't happen for every users.

I'm using my own validator in php on my server, but maybe I'm doing wrong. Anyone can share is version of validator?

Any thoughts on this?
