### ISSUE TITLE
No Billing permission when uploading to the Play store

### ISSUE THREAD

**Issue by JTronLabs** [j3k0/cordova-plugin-purchase#567]
When uploading the APK the following error is shown:

> Warnings 
You uploaded an APK that does not have BILLING permission, or has a BILLING permission that is limited to specific sdk versions. BILLING permission is required for selling in-app products.

**Comment by JTronLabs** [comment]
I think this was due to not running `cordova prepare` to re-download plugins after deleting them all. Whoops!

**Comment by gmbad** [comment]
Hi @JarLowrey 

The same problem here.

Message from google play console:

"To add in-app products, you need to add the BILLING permission to your APK"

I've already uploaded the package (app-release.aab), with the cordova-plugin-purchase plugin...

Do I need to create some permissions in config.xml?

Tks

**Comment by JarLowrey** [comment]
I had this issue 4.5 years ago and havent touched cordova much since. Did you re-run `cordova prepare`?

**Comment by gmbad** [comment]
Hi James.

Yes, i re-run cordova prepare.
On google play console, do I need to put the App for internal testing so
that the option appears?

tks

**Comment by JarLowrey** [comment]
I don't know. Good luck!
