### ISSUE TITLE
Get currency code & unformatted price for product

### ISSUE THREAD

**Issue by sirflo** [j3k0/cordova-plugin-purchase#57]
For tracking purposes we need to know the price & currency for the products.

I've made some changes so that `storekit.load` returns these values alongside the preformatted price. We tested it with different countries and _so far_ it worked fine.

I'm not submitting a pull request as the current implementation would break existing code. In our code `price` is used for returning an unformatted number and the new `localizedPrice` is the formatted price as it was before.

See the changes for yourself here: https://github.com/platogo/PhoneGap-InAppPurchase-iOS/commit/0e8e842a246a0f2ab92d65932cffa49dd892568e

It would be great if price & currency code would find their way into the plugin.
Also, thanks for providing this plugin!

**Comment by trancee** [comment]
What is the status on this? As for the time being, iOS sends currency:null and adds localized price only...

**Comment by sirflo** [comment]
The pull request/suggestion was for the previous non-unified version of the plugin. I haven't checked if the commit can be applied to the current version (though the changes are minimal).

Have you tried if `currency` is returning something useful when using the plugin from our old fork? https://github.com/platogo/PhoneGap-InAppPurchase-iOS/tree/currency-code

**Comment by trancee** [comment]
Unfortunately, after applying your changes the currency field still returns null. But the price field is now numerical (not localizedPrice).

**Comment by trancee** [comment]
I have found out why it didn't work. The problem was that the JavaScript implementation did not pass on the new variables from the iOS / Android native module. After adding those, everything works as expected!

**Comment by robwebdev** [comment]
I could really do with an unlocalized price for the same reason as the OP.

@j3k0 is there any progress on this? I'd be happy to make an attempt at adding this if you could point me in the right direction.
