### ISSUE TITLE
[ios] When using only Japanese , can't get title and description

### ISSUE THREAD

**Issue by YusukeSakurai** [j3k0/cordova-plugin-purchase#570]
The program is almost completed, but I have some doubts.
I can't get title and descripton at ios.

![img_0230](https://cloud.githubusercontent.com/assets/20940479/24330859/ef48516e-1262-11e7-9577-37f60b8e2bbe.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/20940479/24330861/f4d943cc-1262-11e7-88ae-bd6ae797bdf7.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/20940479/24330860/f0c27204-1262-11e7-9d34-58ed72dfb7cd.png)

**Comment by Dexus** [comment]
Hi @YusukeSakurai 
Can you send me the Title and Description as text here, so I can create a demo to check what happens when I use the Items.

**Comment by j3k0** [comment]
This might be because you didn't call `refresh()` __after__ registering the products... or refresh wasn't done yet when you `alert`-ed the details of the product.
