### ISSUE TITLE
Restore Purchases

### ISSUE THREAD

**Issue by dps-mobile** [j3k0/cordova-plugin-purchase#571]
Hi,

When I call the "Restore Purchases" i get the list of products bought. But the transaction ID is not the same of the transaction ID when receive the purchase receipt.
How do I link the transaction ID of the restore with the purchase transaction ID?

**after buy product:**
` {"transactionId":"1000000286082413","receipt":"MIIT3gY......"}`

**after restore purchases:**
`{productId: "prd-001", date: "2017-03-29T13:27:53Z", transactionId: "1000000286082537", state: 3}`

**Comment by Almerick** [comment]
Hi dps-mobile,

Based on my observation, iTunes treat the "Restore Purchases" process as new transactions altogether, therefore the new transactionIDs.

In my instance, I only respect transactionIDs found in the grand receipt, after validating it with iTunes. All my transactions are stored server-side, so when a user triggers the "Restore Purchases" event, I inspect the validated grand receipt content and if any new transactions are found therein, process those.

Note that this was my implementation of auto-renewable subscriptions and most of which are handled server-side.
