### ISSUE TITLE
Error 6777010 : Connection to itunes store impossible

### ISSUE THREAD

**Issue by davidanquetin** [j3k0/cordova-plugin-purchase#572]
Hej

since a few days, with all my sandbox test accounts, i can not purchase any items from apple store..
My app was working good before, but now the problem is : 
- I disconnect any itunes account in ipad
- I delete / reinstall my cordova app
- I launch it and try to purchase an item. The plug in is well connected, received all informations
- I launch the purchase, write my test account informations, i've got the apple confirmation alter box (do you want to purchase this item), and when I conform...nothing is happened.

When i see the log, there is an error 6777010

I have verified itunes connect settings, there is no changed elements since last time...

Has someone the same problem ?

thanks

![capture d ecran 2017-03-31 a 11 12 51](https://cloud.githubusercontent.com/assets/9817813/24544488/c468d2e4-1603-11e7-9468-08e197305087.png)

UPDATE : it seems it is an apple problem : 
https://forums.developer.apple.com/message/220278#220278

so wait and see !

**Comment by dps-mobile** [comment]
I have the same issue

**Comment by teamherois** [comment]
I just had the same problem - and just got around it. 

My issue was that I was testing with a different sandbox user ID than I had used in the past on the device. At some point - Apple has tied your Sandbox user to your phone. If you ever try to use a different Sandbox user than the one you originally used for a test purchase on that device - you'll get the error.

I reverted back to a previous Sandbox user ID on my test device - and problem solved. I'm testing right now to see if deleting all the past Sandbox users that I tested with on that device - and then moving to a new device - will fix the problem.

**Comment by davidanquetin** [comment]
i have tested with the same sandbox user UD thant in the past, and then with a new one, but any of the two are working...

**Comment by zhang024** [comment]
Hi All,

 

That because products have not been loaded when you purchase. 

 

Here is my workaround.

 

   function WaitingStoreReady(product, times) {

        if (store.isReady) {

            //store.refresh();

            updateProcessing("Loading product...");

            WaitingProduct(product, 0);

            return;

        }

        if (times == 30)//wait for 30s to initialize Google Play;

            _callback(3, 'Store not available');

        else

            setTimeout(function () {

                WaitingStoreReady(product, times + 1)

            }, 1000);

    }

 

   //when you call Order method to process, it will check and ensure the products have been loaded.

    this.Order = function (product, callback) {

        _callback = callback;

 

        if (initializeStore()) {

            updateProcessing("Checking product on store...");

            WaitingStoreReady(product, 0);

        }

    }

 

Thank you,

 

Sean

**Comment by teamherois** [comment]
Problem still open and still an issue.

**Comment by charlesbodman** [comment]
Confirmed

**Comment by heymartinadams** [comment]
Indeed: https://forums.developer.apple.com/thread/69004

**Comment by heymartinadams** [comment]
Fixed. Works me.

**Comment by davidanquetin** [comment]
It's ok for me to , it works again. I close the ticket. Thanks all.

**Comment by HarelM** [comment]
Can anyone explain how to get passed it.
I have a customer with this error code.
It is not sandbox but production environment.
The customer purchased on iPad and would like to use it with his iPhone both with the same apple account and application user...

**Comment by HarelM** [comment]
I think (not sure) that upgrading to version 10.4.0 solved the customer issues.
We have tried to contact them to understand if the issue was resolved but haven't heard back.
I'm guessing that "no news is good news"...
