### ISSUE TITLE
Subscription info does not load only at first time

### ISSUE THREAD

**Issue by rserro** [j3k0/cordova-plugin-purchase#573]
Hi there,
Consider the following scenario:

1 - Download the app from Google Play and click open right away.
2 - Try to get subscription plans info. **No info is received**
3 - Close the app.
4 - Reopen the app.
5 - Try to get subscription plans info. **It will work from now on, with no problems at all**
6 - Delete the app from the phone. Go to [1] and the exact same behavior will happen. Tested in multiple devices, with distinct Google Play accounts. Exact same behavior for all.

Does anyone have a clue of how to solve this problem?
Thanks in advance

**Comment by rserro** [comment]
Extra info:
1 - App and plans are already live for more than one day.
2 - All the subscription process works fine, except for the scenario described above.

**Comment by Dexus** [comment]
following problems may there:

- no internet connection / or not ready rendered webpage
- you use a encrypted app, that not already ready while start the app actions.
- you have an buggy implementation

Please look into your debugging informations to clarify if the "bug" is on your side or not.

Please reopen this Issue if you have future details that have to do with the plugin and we will look deeper into it.
