### ISSUE TITLE
Resolving Open Issues

### ISSUE THREAD

**Issue by heymartinadams** [j3k0/cordova-plugin-purchase#575]
@j3k0 I’m seeing there are a lot of open issues for this Cordova plugin. Though I’m a lone developer, I’m interested in seeing this plugin’s technology advance.

1) Is there anything specific I can do to assist?
2) Would it be helpful if we held a fundraiser that would allow you to get paid while you improve the plugin’s functionality / bug fixes?
3) Any other thoughts... ?

Thanks so much for creating this plugin! Just developed my first app with it: https://www.LifePurposeApp.com

Warm regards,
Martin

**Comment by j3k0** [comment]
Hello @heymartinadams 

Thanks for your offer for help, indeed it's a shame I don't have more time to give it the love this plugin deserves ;-) With my workload and newborn I wasn't available much for quite a while (still ain't). I handle Pull Requests, check on issue's title to see if there's stuff that look more critical than "requests for support".

I'm an independent developer, fundraising could let me to schedule some time to work on the plugin, after the next 3-4 months where I'm basically fully booked on other projects.

If you're willing to get your hands dirty, #557 issue looks important.

If you like to help others by answering to support requests, it's great as well. To make this easier I have a plan to categorize all pending issues to identify where the documentation needs to be improved. The link people to the section containing answers to their question (write the such sections when needed), then have a better index to the different sections: could be a good thing to have for everyone as well.

Those are some random ideas, maybe as a fresh user to the plugin you have some ideas on what could have been done to make your life easier?

Looking forward to reading you!
JC

**Comment by heymartinadams** [comment]
Ok, @j3k0 😊 Since I’m not yet familiar with this tech (or, for that matter, with Objective-C/Swift and Java), there’s not much I can do on the tech side, but I could help streamline the documentation. I won’t do it right away, but it’ll be something I’ll do over the next few weeks and months. I’ll send PR for each one.

Then, once I have a better understanding of the overall structure of the documentation, I can assist more over time, perhaps with a fundraiser.

I’m so glad you developed this. It’s a crucial part of my business strategy. For in-app purchases related to web apps, I use Stripe: https://medium.com/consciousapps/integrating-stripe-with-react-graphql-and-apollo-client-e09fdc9e5b95

Warm regards,
Martin
p.s. And congratulations on your newborn! 😀
