### ISSUE TITLE
Testing In-app billing (Android)

### ISSUE THREAD

**Issue by BLACKburn49** [j3k0/cordova-plugin-purchase#576]
On June 20, 2016, Google made an important change: test purchases don't have an order id anymore.

[https://developer.android.com/google/play/billing/billing_testing.html](url)
"Once authorized for testing access, those users can make purchases without being charged. Test purchases don't have an orderId field, which ensures that there are no actual charges to user accounts."

Transaction seems therefore null when testing (static responses or alpha/beta) which is annoying because you pass `transaction.id` when finishing a purchase in `store-android.js`...

**Comment by j3k0** [comment]
Closed by 626cda00ec0399cfc167240a8032415b3f5d7392
