### ISSUE TITLE
valid order triggering cancelled event

### ISSUE THREAD

**Issue by ethanj** [j3k0/cordova-plugin-purchase#578]
I have been getting a fraction of users who complete a valid transaction as shown in Google Play order management, but the plugin is calling the cancelled callback, rather than the approved callback.

Any idea why this is happening?

**Comment by Dexus** [comment]
Can you please provide some more details and maybe how you check the orders etc? It's difficult to give a hint in to the blue...

**Comment by Dexus** [comment]
@ethanj can you show us how you implemented the code stuff?

**Comment by ethanj** [comment]
@Dexus hey.. thanks for answering! Its not clear what you want to see in terms of code. The way we are checking the orders is to look in Google Play order management for the email address of the subscriber. It seems a consistent fraction of the users subscribing on android and up with an active google play subscription, but no created account on our end. So we attached logging to all the callbacks of the plugin, and consistently in these cases, the logging shows the plugin calling back to cancelled, and never making it to approved.

**Comment by Dexus** [comment]
As long you not call the `product.finish()` the next app start the approved status should re-triggered from the store itself.

I want to see in terms of code, if there is a possible wrong implementation of it.
Unfortunately, I can not reproduce the problem.
