### ISSUE TITLE
Advertising Identifier (IDFA)

### ISSUE THREAD

**Issue by heymartinadams** [j3k0/cordova-plugin-purchase#579]
Apple famously asks on app submission if the app has an Advertising Identifier.

> Advertising Identifier
> 
> Does this app use the Advertising Identifier (IDFA)?
> The Advertising Identifier (IDFA) is a unique ID for each iOS device and is the only way to offer targeted ads. Users can choose to limit ad targeting on their iOS device.
> 
> Ensure that you select the correct answer for Advertising Identifier (IDFA) usage. **If your app does contain the IDFA and you select No, the binary will be permanently rejected and you will have to submit a different binary.**
> 

I just noticed that there’s a mention of the IDFA in `cordova/plugins/cc.fovea.cordova.purchase/src/ios/IAPDevice.m`:

```
#pragma mark - UID Generation methods

+ (NSString *)appleIFA {
    NSString *ifa = nil;
    Class ASIdentifierManagerClass = NSClassFromString(@"ASIdentifierManager");
    if (ASIdentifierManagerClass) { // a dynamic way of checking if AdSupport.framework is available
        SEL sharedManagerSelector = NSSelectorFromString(@"sharedManager");
        id sharedManager = ((id (*)(id, SEL))[ASIdentifierManagerClass methodForSelector:sharedManagerSelector])(ASIdentifierManagerClass, sharedManagerSelector);
        SEL advertisingIdentifierSelector = NSSelectorFromString(@"advertisingIdentifier");
        NSUUID *advertisingIdentifier = ((NSUUID* (*)(id, SEL))[sharedManager methodForSelector:advertisingIdentifierSelector])(sharedManager, advertisingIdentifierSelector);
        ifa = [advertisingIdentifier UUIDString];
    }
    return ifa;
}
```

1) Since I’m thoroughly Objective-C illiterate, **does this mean my app contains the IDFA?**
2) If yes, **how can I remove it?**

Understandably, it’s important to get this question right the first time!

**Comment by Dexus** [comment]
Hi I'm not sure what version you using... but in my repo and plugin folders i can't find a `IAPDevice.m` file and no code like this you quoting.
