### ISSUE TITLE
Event Tracking for Analytics?

### ISSUE THREAD

**Issue by juergengunz** [j3k0/cordova-plugin-purchase#580]
How do you guys track an Event for purchase on GA for example. If I track it in .approved it will get called on restore(). Is there an Event that is only called once after purchase?

**Comment by Dexus** [comment]
Hi @juergengunz maybe you will read the API documentation and use this after that: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeoncequery

**Comment by svzi** [comment]
@Dexus Even after reading that part multiple times, I was unable to understand how that could help. Just listening "once" doesn't mean, that it won't get called when you restore your purchase after a fresh installation or on a new device. So how can we assure, that we only track this IAP once via Google Analytics?

**Comment by j3k0** [comment]
@svzi Doing analytics correctly purely client side isn't possible. You need to track the transactions on a server. StoreKit API doesn't provide anything useful for tracking a transaction client-side, there is no way to know it a transaction has been initiated on another device, processed on another device, or if it's a restored purchase, cancelled by Apple customer service, etc (there's so many edge cases).

But it's possible to build approximated analytics with `once` (only tracking correctly the users that go through the whole purchase funnel in a single shot). This might good be enough as indicators, but won't provide 100% accurate numbers.

I'm in the process of build this feature as a service in https://billing.fovea.cc -- If that something that might interest you (or anyone), I'll be happy to make sure it suits your exact needs. Let me know about the solution you dream about!

**Comment by svzi** [comment]
@j3k0 I'm not trying to do it purely client side. I'm already using Firebase Analytics and the In-App-Purchases for iOS are collected and displayed correctly, but not for Android. So I thought it could be helpful to collect some kind of event manually and mark it as conversion in Firebase Analytics.
