### ISSUE TITLE
Working example in Meteor?

### ISSUE THREAD

**Issue by MastaBaba** [j3k0/cordova-plugin-purchase#582]
Is a basic walkthrough available for setting up in-app purchases in Meteor?

**Comment by Dexus** [comment]
Hi, i don't know much about Meteor but its working with cordova and javascript so you can work with this plugin like in other cordova supported IDEs and Plattforms.

Maybe I will find time and create a example for it. But for now there is no example.

**Comment by MastaBaba** [comment]
Thanks. Yes, I'm sure I can get this plugin to install on Meteor. And I also understand how to define the purchasable products, for iOS and Android. But I'm not clear on how to, then, set up the workflow.

The minimal example (https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/minimal-example.js) seems to show how to define a product in the app, which reflects a product defined in iTunesConnect (or the Google Play Developer Console). But, then, what?
