### ISSUE TITLE
App rejected on iTunes due to IPv6 incompatibility

### ISSUE THREAD

**Issue by darioserfe** [j3k0/cordova-plugin-purchase#583]
Apple is rejecting my app because it is not compatible with IPv6. I'm not hardcoding any IPs and all the calls to my API are working fine.

In the sign up screen, I list the subscriptions plans (auto-renewable type: store.PAID_SUBSCRIPTION) and another account options from my server, but the subscriptions are not listed.

In my tests, using the .ipa compiled in build.phonegap.com, all the subscriptions plans (IAP) shows up and I can finish the purchase without problems, but in the iTunes tests using IPv6 network, the subscriptions (IAP) are not being loaded.

Apple says that this is happening given that my app is not compatible with IPv6, can you confirm that this plugin supports IPv6 DNS64/NAT64 Networks?

Thanks in advance.

**Comment by Dexus** [comment]
I have self had this issue but only when i dont have a IAP Validator without IPv6 support.
With this in mind, i would say you should enable IPv6 on your validation system.

**Comment by darioserfe** [comment]
Hi,

I don't think that the problem is related to the IAP validator.

We request to the validator once the user purchase a subscription.

We are using https://github.com/aporat/store-receipt-validator to valdiate the purchase

After the device ready, we are doing

store.register({
    id: 'id',
    alias: 'alias',
    type: store.PAID_SUBSCRIPTION
});

Setup listeners for callbacks: verified, unverified

and finally

store.refresh();

on the store.ready callback, we are doing

store.get("id");

Thats all.

When you say "IAP Validator" are you refering to the validation of the purchase?

The network communication on our app is working without problems, the problem is to retrieve the subscriptions from iTunes and only fail for the iTunes team under IPv6 network

Please, let me know
Thanks for your help

**Comment by Dexus** [comment]
Ist your external validation script via IPv6 reachable or only IPv4? If your IAP Validation Script ist not reachable via IPv6 the Apple-Team will reject your app! 

I mean store.validator that is a musthave for paid subscription.... because our script use no restricted internet function and only used the internet that the phone support... I think the "problem" is selfmade with your own validation hostname/service that is not IPv6 ready...

Von meinem iPhone gesendet

**Comment by darioserfe** [comment]
You are right, my domain (where the IAP validator is located) isn't IPv6 ready. I'll setup the server and let you.

Thank you very much for your help.

**Comment by sebastian-serfe** [comment]
@Dexus 

Thank you very much for your help.-

Now our server supports IPv6 and the subscription plans are listed. The app was accepted on iTunes,.

Thanks!!

**Comment by Dexus** [comment]
@sebastian-serfe you are welcome

**Comment by Defcon0** [comment]
@darioserfe @sebastian-serfe Could you please provide the basic code on how you configure your store, I mean just the relevant function calls on the store? I'm having a hard time getting my app approved by Apple review team. That would be awesome!
