### ISSUE TITLE
Sporadic "Invalid product type" errors upon IAP order.

### ISSUE THREAD

**Issue by jonathankau** [j3k0/cordova-plugin-purchase#586]
We've been having consistently sporadic TypeErrors thrown from the plugin at https://github.com/j3k0/cordova-plugin-purchase/blob/d7ef5cce3fd8e755840a4d0db29a44894431091e/www/store-android.js#L418 and https://github.com/j3k0/cordova-plugin-purchase/blob/d7ef5cce3fd8e755840a4d0db29a44894431091e/www/store-android.js.

This only happens < 5% of the time, so we're fairly certain that our use of the plugin is as specified in the documentation. All of our products are registered using `store.PAID_SUBSCRIPTION`. Given that this is a client-side error with validating the product type, we believe this is a bug with the plugin itself.

Has anyone run into or resolved similar issues before?

**Comment by Dexus** [comment]
Can you provide an example code where it can reproduced?

**Comment by aesculus** [comment]
Was this ever resolved? I am getting similar results occasionally on iOS

**Comment by mike-nelson** [comment]
I have also had customers this error in the wild infrequently. Does anyone have any clues about it?
