### ISSUE TITLE
Wrong price after updating - Android

### ISSUE THREAD

**Issue by TraceDeTrail** [j3k0/cordova-plugin-purchase#591]
Hi everybody,

After an update of the prices of my products in the play store, I always get the old prices when I ask the store via this plugin (store.get()).
But, when the user purchase the product, the new price is displayed...

Do you know the reason of this issue ?

Thanks.

**Comment by Pigsnuck** [comment]
I think it's because of the Play Store cache.  To confirm, try deleting the Play Store cache and see if the current prices are now displayed.

- Open the Android Settings app.
- Tap on Apps.
- Scroll down and tap on Google Play Store.
- Tap on Storage.
- Tap Clear Cache.
- Restart your app.

**Comment by tt-rkj** [comment]
Just want to confirm what @Pigsnuck said. I had the same issue, and the prices were updated correctly after clearing the play store cache as described.
