### ISSUE TITLE
How to acquire app receipt

### ISSUE THREAD

**Issue by Zapmobilegames** [j3k0/cordova-plugin-purchase#593]
Hello,
I'd like to check with my server if the app has been correctly purchased from the Apple Store. 
I'm not able to find a set of instructions to pick up the receipt to send to my server, as required in the [official Apple docs](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1)

Could you please help?

**Comment by Pigsnuck** [comment]
The receipt is returned from Apple in the restore method, from memory.  You can then send that to your server to be independently (and directly) confirmed for validity with Apple.  Note that your server is responsible for deciding whether a subscription is actually active, as Apple will only confirm valid/not valid.
