### ISSUE TITLE
Google Play Store cache has to be cleared on Android

### ISSUE THREAD

**Issue by Pigsnuck** [j3k0/cordova-plugin-purchase#598]
I just released my app (Paragliding Map) to Google Play, and I am getting a TON of support issues about the same topic: **purchases are not restoring**.

The issue seems to be that after registering the products, they are never retrieved from Google Play.  If the user clears their Google Play Store cache and restarts the app, then everything magically starts to work.

Has anybody else experienced this problem, and is there a workaround?  The plugin works fine in iOS with the same codebase, but not so well on Android.  Well, for me anyway.

**Comment by Pigsnuck** [comment]
Anyone?  This issue is causing me major issues, and I have no current workaround. Am I doing something incorrectly?

**Comment by qpwr** [comment]
Did you somehow solve this, @Pigsnuck?

**Comment by Pigsnuck** [comment]
> Did you somehow solve this, @Pigsnuck?

Unfortunately not. In the next few days I will be upgrading to the latest version of the plugin. Let's see if this has changed.
