### ISSUE TITLE
IAP.onRestore not firing

### ISSUE THREAD

**Issue by jalalimehdi** [j3k0/cordova-plugin-purchase#60]
Hi, Thanks for very useful plugin.
there is a problem IAP.onRestore not firing
please guide me

**Comment by vladipus** [comment]
I may actually have a similar issue. Do I have to consume the item with some special function?

**Comment by LukePulverenti** [comment]
Did any of you find a solution for this?

**Comment by mrthehud** [comment]
I've been having slight issues with IAP on iOS for a while, and it's getting to the point where I can't put it off anymore, so I'll come back once I've sorted it with anything I find. Ping the thread in a few weeks if I've not remembered to come back.

**Comment by anonrig** [comment]
@mrthehud Any updates?
