### ISSUE TITLE
Retrieve all products from Google Play store

### ISSUE THREAD

**Issue by cmohanraj10** [j3k0/cordova-plugin-purchase#601]
I can able to get the product details by giving the product id as follows

store.register({
    id: 'PROD128203', // Product Id
    alias: "100 coins",
    type: store.CONSUMABLE
});
store.refresh();
store.when('PROD128203').updated(function(p) {
    alert("product is " + p.state + ", title is " + p.title+ ", des is " + p.description+ ", price is " + p.price);
});

**I have many products, How can i get all active products in single API call?**

**Comment by Dexus** [comment]
Hi @cmohanraj10 it is not possible to get all products in a single API call.

**Comment by cmohanraj10** [comment]
Not possible to get just product ids also?

**Comment by Dexus** [comment]
No, you can request you productIds from a owned webservice and register them then, but you can't get all you products via API from the store.

**Comment by cmohanraj10** [comment]
For example, I have three products. I want to display something like this
![pgs](https://user-images.githubusercontent.com/7069726/27078907-7468a064-4fea-11e7-835e-8c4c4255a6d2.png)

Is there any documentation available?

**Comment by cmohanraj10** [comment]
store.register({
id: 'PROD128203', // Product Id
alias: "100 coins",
type: store.CONSUMABLE
});
store.refresh();
store.when('PROD128203').updated(function(p) {
alert("product is " + p.state + ", title is " + p.title+ ", des is " + p.description+ ", price is " + p.price);
});

This code works fine if i call first time, next time if i call this function next time it returns

**Comment by cmohanraj10** [comment]
var productIds = ['id1','id2','id3'];
productIds.forEach(function(item){
	var product = store.get(item); //item=>Product Id
	if(!product){
		store.register({
			id: item,
			alias: "100 coins",
			type: store.CONSUMABLE
		});
		store.refresh();
		store.when(item).updated(function(product){
			alert(product.price);
		});
	}
	else{
		alert(product.price);
	}
});

I have three products, I need a price for those products. I have coded like this but i am getting only first product price.  Is that code correct?
