### ISSUE TITLE
Retrieve products price from store

### ISSUE THREAD

**Issue by cmohanraj10** [j3k0/cordova-plugin-purchase#602]
```
var productIds = ['id1','id2','id3'];
productIds.forEach(function(item){
	var product = store.get(item); //item=>Product Id
	if(!product){
		store.register({
			id: item,
			alias: "100 coins",
			type: store.CONSUMABLE
		});
		store.refresh();
		store.when(item).updated(function(product){
			$(".pprices").append('<div>'+product.price+'</div>');
		});
	}
	else{
		$(".pprices").append('<div>'+product.price+'</div>');
	}
});
```
I have three products, I need to display the price for those products. I have coded like this but i am getting only first product price. Is that code correct?

**Comment by Dexus** [comment]
First of all: `store.refresh()` should only be called once!!! at the end of register all products and listeners.

You should get for each product you information if you register it on playstore and after it correct with your app.

I personally use a "Template" that get rendered and append to my list. and if a ID exist i update only the template and replace the filled fields with the new data.

Look please to the examples: https://github.com/Fovea/cordova-plugin-purchase-demo/blob/master/www/js/index.js 

That should help you.

**Comment by cmohanraj10** [comment]
Thanks a lot.
