### ISSUE TITLE
[IOS] App randomly crashing on storekit.load 

### ISSUE THREAD

**Issue by ultisoftmeta** [j3k0/cordova-plugin-purchase#603]
I am using cordova-plugin-purchase for iOS and testing via TestFlight (sandbox environment). Problem is that sometimes the purchase goes smooth and sometimes my app crashes while loading storekit.
I will really, really appreciate any pointers and any insights that anyone can provide as this is very critical for my project completion.

Below are the technical details:

I followed following articles:
https://fovea.cc/blog/index.php/3-steps-tutorial-for-phonegap-2x-in-app-purchase-on-ios/
http://fovea.cc/blog/wp-content/uploads/2013/06/iap.js

I am calling IAP.load() followed by IAP.onReady().
Calling IAP.onReady() randomly invokes it multiple times and crashes the app. Sometimes everything works as expected and I am even able to make a purchase.

Code snippet from my implementation:
/*********************************************** Code Snippet begins ****************************************************/
IAP.load = function () {
  // Check availability of the storekit plugin
  if (!window.storekit) {
    alert("In-App Purchases not available");
    return;
  }

  // Initialize
  storekit.init({
    debug:    true,
    ready:    IAP.onReady,
    purchase: IAP.onPurchase,
    restore:  IAP.onRestore,
    error:    IAP.onError
  });
};

IAP.onReady = function () {
    // Once setup is done, load all product data.
    storekit.load(IAP.list, function (products, invalidIds) 
    {
         IAP.products = products;
        IAP.loaded = true;
         for (var i = 0; i < invalidIds.length; ++i) {
        alert("Error: could not load " + invalidIds[i]);
      }
   });
 
};
/*********************************************** Code Snippet ends ****************************************************/

OSX Yosemite 10.10.5 -- where I am building iOS build.
Cordova 7.0.1 
Device: iPhone iOS 10.3.1(14E304)
Plugin Version: 6.1.2
```

### Expected behavior
To load all products
### Observed behavior
Crashes while calling IAP.onready and IAP.onready is getting called multiple times even though I am calling it once.
### Steps to reproduce
Invoke IAP.load() and IAP.onready()

Any suggestions on how to resolve this?  Thank you.

**Comment by Dexus** [comment]
Hi, please dont follow outdated tutorials or blog posts... its from 2013 and so it may be outdated since years... pleas read the readme of this repo and look to the examples that are linked.

Best regards, Dexus

Von meinem iPhone gesendet

**Comment by ultisoftmeta** [comment]
Thank you so much Dexus for your response. I am looking into more details of this repo and will update here on how it goes. Thanks again.

**Comment by ultisoftmeta** [comment]
I checked READ ME at the following location:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/README.md
It directs to iOS Documentation:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/ios.md
iOS documentation has example for Hosted Content and Non-renewable Subscriptions.
We are using Auto-renewable subscriptions. 
 Does following the "non-renewable subscriptions" example is good?
I will appreciate your guidance here.
Thank you so much.
