### ISSUE TITLE
Question: How to get transaction id, receipt number and date of expiry in case of auto renewable subscription

### ISSUE THREAD

**Issue by ultisoftmeta** [j3k0/cordova-plugin-purchase#604]
Hi,

I am trying this plugin for in app purchase iOS and purchasing a product works well for me.
Due to some version problem I am not able to get logs on my device.

I have few questions:
1) How to get product id, transaction id, receipt number and date of expiry of all purchased products in case of auto renewable subscription?
2) How to get only receipt number for an apple id?

Thank you so much for your help.

**Comment by ultisoftmeta** [comment]
I will really appreciate your help on this. 

We need to store the receipt id in our server and since iOS has the common receipt for all transaction , I am trying to find out how to get information on receipt and transactions.

Can you please let me know the way to get this information from this library?

**Comment by Dexus** [comment]
the recipient and the transactionId you will get when you use the `store.validator` and overwrite it... but then you should look at the linked examples!

We dont write your code... we provide you only the chance to use our source so you dont need to write the plugin yourself. If you not abel to read the examples and docs, we cant help you.

**Comment by ultisoftmeta** [comment]
Thank you so much for the information.

I just want to clarify that I am not expecting you to write code but asking for pointers where I am not clear. Also , reading documentation gives us information but if me or any developer is facing issues then they are free to post questions to expedite development process. 

Thanks again.

**Comment by Dexus** [comment]
I'm sorry that i was a bit in rage. But it's a bit annoying to read always the same questions and no body read the docs and examples. 

Please make sure when you use the remote validator you have to support IPv4+6 and only https! TLS 1.0 to TLS 1.3 

Von meinem iPhone gesendet

**Comment by ultisoftmeta** [comment]
I understand. Thank you so much for the information and for all your efforts.

**Comment by ScottMBerger** [comment]
I have a question related to this. I'm testing the subscription purchase and when I do the purchase the message from Apple saying the subscription is complete pops up before the server validation is completed. This seems like an issue if the validation would be to fail? Am I not incorporating it properly?

**Comment by ultisoftmeta** [comment]
As I mentioned in the the question below ,the product goes through different states at the time app is loaded:
https://github.com/j3k0/cordova-plugin-purchase/issues/607

For me , whatever you are pointing out doesn't happen i.e. validation message doesn't comes before verification.

I am providing sample of events that I have written:
  store.when("X").approved(function (p) 
              {  p.verify();     
              });
 store.when("X").verified(function(p) 
                { p.finish();
             });
Here after verification the product transaction is finished.
