### ISSUE TITLE
Question: How is a product consumed?

### ISSUE THREAD

**Issue by armandn** [j3k0/cordova-plugin-purchase#605]
Suppose a user purchases 100 coins. I suppose the app needs to keep the current number of coins internally and when the number reaches 0, to mark the resource as consumed.

However, I don't see anything in the API to mark a purchase as consumed, so what's the difference between consumable and non-consumable products?

**Comment by Dexus** [comment]
The different is consumable are with "finish()" consumed but non-consumable products can be restored after deinstall // reinstall the app or on a other device...

**Comment by Allan-Nava** [comment]
I have a consumable product and I need to show the dialog dynamically, is possibile?
