### ISSUE TITLE
Question: handling offline states

### ISSUE THREAD

**Issue by armandn** [j3k0/cordova-plugin-purchase#606]
Suppose the user has purchased an Unlock product. What's the best way for a Cordova app to keep this state?

Obviously, keeping a simple "unlocked=true" value in the LocalStorage is the easiest, but also easy enough to hack.

Should the app do a store.refresh() on every run?

Any other strategies?

**Comment by Dexus** [comment]
Use a sqlite db or localstorage for your "state save".

each cordova app is  easy to hack, also if you store the data elsewhere... so what will you do now? dont create apps because of hackers can crack it? ;)
