### ISSUE TITLE
[IOS] Question : Regarding State change

### ISSUE THREAD

**Issue by ultisoftmeta** [j3k0/cordova-plugin-purchase#607]
Sorry if this sounds as like a basic question but I just want to get your perspective here.

As per the documentation in following link:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#purchasing

Notes section says:
-------------------------------------------------------------------------------------------------------------------
During application startup, products may go instantly from REGISTERED to APPROVED or OWNED, for example if they are purchased non-consumables or non-expired subscriptions.
-------------------------------------------------------------------------------------------------------------------

So the events for these states are triggered and we have some rest api's written on approved state. But we wish approved event calls code to be invoked when a product purchase is actually approved rather than during app startup state changes.

I can think of one way to identify this i.e. by having a flag for app being loaded for first time.

Is there any other elegant way to skip events transition during app load?
 
Thank you so much for all your help.

**Comment by amokrunner** [comment]
+1
