### ISSUE TITLE
[WINDOWS 10]  I can't finished a consumable product

### ISSUE THREAD

**Issue by sergip76** [j3k0/cordova-plugin-purchase#610]
### system info
Cordova 7.0.1
Device: PC Windows 10
Plugin Version: 6.1.2
Platform: Windows 10

###
I use the plugin for Android and everything works ok, but when I try it with Windows 10:

When I buy a consumable product the status changes to "finished" and not to "valid" and I can't buy it again. When I enter to the app again and I get the product the status is "owned" like a non-consumable product. But it's a consumable product.

This is the product json after finish():

{"id":"XXXX","alias":"nivel_2","type":"consumable","state":"finished","title":"Nivel 2","description":"Nivel 2 con 51 temas y 1023 palabras."xxxx,"price":"0,00 €","currency":"","loaded":true,"valid":true,"canPurchase":false,"owned":true,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"license":{"type":"windows-store-license","expirationDate":"9999-12-31T00:00:00.000Z","isActive":true}}

And when I enter again to the app the product json is:

{"id":"XXXX","alias":"nivel_2","type":"consumable","state":"owned","title":"Nivel 2","description":"Nivel 2 con 51 temas y 1023 palabras."xxxx,"price":"0,00 €","currency":"","loaded":true,"valid":true,"canPurchase":false,"owned":true,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"license":{"type":"windows-store-license","expirationDate":"9999-12-31T00:00:00.000Z","isActive":true}}

How can I change the status to "valid" to buy it again?

**Comment by Dexus** [comment]
I would say the product is not consumed, but i dont have a Windows Phone to check why it dont work.

**Comment by sergip76** [comment]
It's not necessary with Windows Phone. You can check it with a Windows 10 app.
