### ISSUE TITLE
[IOS] - problem with un-finished consumable because of validation

### ISSUE THREAD

**Issue by atorgfr** [j3k0/cordova-plugin-purchase#612]
Hi i have i think a bug with validation or there is something i don't understand.
### system info

OSX Sierra 10.12.5
Cordova 7.0.1
Device: iPhone iOS 10.3.2
Plugin Version: 6.0.0

### Expected behavior
When you can't finished a product because of validator (web service validator is down...). I would like after a refresh finish a consumable product.

### Observed behavior
Today I can't do product.finish after store.refresh(). I always have "This In-App purchase has already been bought. It will be restored for free" and i can't finish transaction. 

After a refresh i have found that a new product is added to the store with id equal to my bundle identifier and alias "application data". In state approved.

### Steps to reproduce
```

store.register({
            id: "100.coins",
            alias: "100 coins",
            type: window.store.CONSUMABLE
          });

          store.verbosity = window.store.DEBUG;
          
          store.validator = "http://10.0.0.8:3000/verifyReceipt";

          store.error(function(error) {
              console.log('ERROR ' + error.code + ': ' + error.message);
          });

          store.when("product").approved(function (product) {
              console.log("You got 100!");
              console.log(product);
              product.verify();
          });

          store.when("product").verified(function(product) {
              console.log("Verified !");
              console.log(product);
              product.finish();
          });

          store.when("product").unverified(function(product) {
              console.log("UnVerified !");
              console.log(product);
          });

          store.when("product").expired(function(product) {
              console.log("Expired !");
              console.log(product);
              product.finish();
          });

          store.when("product").cancelled(function (product) {
              console.log("Cancelled !");
              console.log(product);
          });

          store.when("product").error(function (product) {
              console.log("Error !");
              console.log(product);
          });

          store.when("product").finished(function (product) {
              console.log("Finished !");
              console.log(product);
          });

          store.refresh();


```

If web server is down is going to unverified event
At this point, i think it's normal to not do a product.finish()

But, if the user try to buy another time the consumable product, he stuck in this state for this product with this message : "This In-App purchase has already been bought. It will be restored for free". There is no event fire at this point. So we can't finish the first consumable which is valid

Did i miss something ?

**Comment by lignazio** [comment]
I have the same problem.
The ideal behaviour in this case would be to fire a "restore" or an "approved" event from which I could finish the purchase.
Otherwise I haven't found a way to resolve this issue. The user can never buy the product again because can never finish his purchase.

**Comment by atorgfr** [comment]
Ok to fix the issue i have added this 

`
for (SKPaymentTransaction *transaction in [[SKPaymentQueue defaultQueue] transactions]) {
        NSLog(@"finish transactions pending since last load...");
        [[SKPaymentQueue defaultQueue] finishTransaction:transaction];
    }
`
in InAppPurchase.m

in the init of inAppPurchase
it solved my problem

**Comment by robwebdev** [comment]
@atorgfr do you plan on submitting a pull request with this fix?

**Comment by atorgfr** [comment]
not sure is the right thing to do, but i will try.

**Comment by jackdyson31** [comment]
@atorgfr : cheers and I can verify your solution solved my problem related to the consumable class on iOS, you get a situation where the transaction is unfinished - thats it, nothing can be done with the store items already purchased. I definitely think this CRITICAL workaround **should** be in the plugin or some mention made of it in the API instructions.

Further, what is really weird is that at the time of writing, on android, using the manageable class for a consumable product.finish() does not seem to do anything once the purchase is approved and this technique of modifying the plugin lightly to access the underlying iOS or Android native API is really a lifesaver. Impossibly difficult plugin to get right :-(

For those who don't know where the init section of the inAppPurchase.m in iOS, I added it like this:

-(void) setup: (CDVInvokedUrlCommand*)command {
    CDVPluginResult* pluginResult = nil;
    g_initialized = YES;

    if (![SKPaymentQueue canMakePayments]) {
        DLog(@"Cant make payments, plugin disabled.");
        CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Can't make payments"];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
        return;
    }

    self.list = [[NSMutableDictionary alloc] init];
    self.retainer = [[NSMutableDictionary alloc] init];
    self.currentDownloads = [[NSMutableDictionary alloc] init];
    unfinishedTransactions = [[NSMutableDictionary alloc] init];
    //make sure we add only one observer
    if(observer==nil) {
        [[SKPaymentQueue defaultQueue]  addTransactionObserver:self];
        observer = self;
    }
   // atorgfrs code start
    for (SKPaymentTransaction *transaction in [[SKPaymentQueue defaultQueue] transactions]) {
        NSLog(@"finish transactions pending since last load...");
        [[SKPaymentQueue defaultQueue] finishTransaction:transaction];
    }
   // atorgfrs code end
    
    pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"InAppPurchase initialized"];
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}

Best,

J

**Comment by BrainstemStudio** [comment]
@atorgfr Thanks for this, it also solved my problem. Needs to be added as a fix
