### ISSUE TITLE
[IOS][Question] p.owned property always returns true after purchase in test flight environment

### ISSUE THREAD

**Issue by ultisoftmeta** [j3k0/cordova-plugin-purchase#613]
As mentioned in example below:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md

I am using p.owned property to check if product is still owned or expired.
 // Is this product owned? Give him a special class.
            if (product.owned)
                $el.addClass("owned");
            else
                $el.removeClass("owned");

But I am always getting it(product.owned) as  true even if the product has renewed 5 times and subscription should expire now as I am testing using testflight for monthly subscription.

Any suggestions or pointers to point out what I am doing wrong here will be really helpful.

Thank you so much for taking time to read this and for all your help.

**Comment by ultisoftmeta** [comment]
I will really appreciate any pointers on this. After 5 renewals, auto renewable subscription is expected to stop renewing and I am expecting that owned property should return false. Am i missing anything here?
 Thank you so much for help.
 Addition info: One thing that I tried is having a  button for store.refresh  but when i click the button it asks for itunes password multiple times and then it is crashing the app.

**Comment by justin-schroeder** [comment]
@ultisoftmeta I believe this is essentially what receipt validation is for in the context of auto-renewing subscriptions. You need to be able to do server side validation to check if the receipts `latest_receipt_info` includes a purchase for an expiration date in the future. If it doesn't then a `store.PURCHASE_EXPIRED` needs to be returned from the validation callback. However, am still having issues getting 'owned' to revert to `false` at that stage.
