### ISSUE TITLE
Non-Renewing iOS Subscriptions

### ISSUE THREAD

**Issue by cmohanraj10** [j3k0/cordova-plugin-purchase#614]
I want to integrate Non-Renewing Subscription products into my ios app.

    var product = store.get("1_dp");
    if(!product){
	    store.register({
		   id: "1_dp",
		   type: store.NON_CONSUMABLE  //NON_RENEWING_SUBSCRIPTION
	   });
	   store.refresh();
	   store.when("product").updated(function(p){
		renderIAP(p);
	   });
    }
    else{
	    var product = store.get("1_dp");
	    renderIAP(product);
    }

    function renderIAP(product){
	   alert(product.price)
    }

 I am not able to get the product details if register a product using type **store.NON_RENEWING_SUBSCRIPTION**

I am getting the product details using above code but **store.order("1_dp","")** is not working.

Is there anything i am missing?

**Comment by ultisoftmeta** [comment]
store.order(productname) works for me in auto-renewable subscription. Please try that. Thanks.

**Comment by Dexus** [comment]
You have to register each product before you call `store.refresh()` the first time.

After that you can't register new products.
