### ISSUE TITLE
[IOS] Gets store.error instead of store.cancelled when cancel a purchase with Touch-Id enabled

### ISSUE THREAD

**Issue by marbernh** [j3k0/cordova-plugin-purchase#616]
Thank you guys for a great plugin!

We have an issue on production connected to consumable products when touch-id is enabled for puchases. During the purchase the user gets as expected notified with the message:

"Do you want to use Touch Id to confirm the In-App Purchase..."

If the user uses his thumb to verify the Touch-Id the purchase continues as expected but if the user press on the "Cancel"-button we get an store.error event instead of the expected store.cancelled event. 

The object we get from store.error contains the following:
{"code":6777010,"message":"Canceled by user."}

We expect to get the store.cancelled event as we do if the user is not using Touch-Id. Is this connected to this plugin or is it because how iOS are handling this event?

### System info
Cordova 6.5
Device: iPhone iOS 10.3.1 (iPhone 7)
Plugin Version: 6.1.1

### Steps to reproduce
1. Set up Touch-Id so that it is used to verify In-App Purchases
2. Setup purchase of consumable products on Production (Touch-Id does not work on Sandbox)
3. Start a purchase and receive the dialog "Do you want to use Touch Id to confirm the In-App Purchase..."
4. Press Cancel
5. Verify in the logs that we get a store.error event instead of an store.cancelled event

**Comment by tbase82** [comment]
Same problem.

Additionally, if i purchase and cancel multiple times, the app is crashing in distribution mode.  
Tested with ios 10.3.1 and 10.2 (iphone7 and iphone5s)

cordova 7.0.1

My plugins:
cc.fovea.cordova.purchase 6.1.2 "Purchase"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.23 "Google Firebase Plugin"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
