### ISSUE TITLE
Problem with IOS

### ISSUE THREAD

**Issue by BrunoFDeveloper** [j3k0/cordova-plugin-purchase#618]
Hello, in the sandbox mode everything works fine, live release don't work.

On restore purchase the result don't return approved, but The purchase was made!

Only return:
state: 
"Valid"

### system info

In example:
```
    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.1.0 
Device: iPhone iOS 10.3.2 // Android 7.1
Plugin Version: Latest
```

Thank you!

**Comment by Dexus** [comment]
Can you please provide more informations, it has nothing of informations with that we can work.
