### ISSUE TITLE
Receipt validation not working on iOS

### ISSUE THREAD

**Issue by hariharanhs** [j3k0/cordova-plugin-purchase#624]
Hello Team,

We are developing an app using phonegap. Our app contains the in app purchase(Auto-renewable subscription) for that we are using this plugin. The plugin works fine on android in sandbox testing account and we are able to get the receipt properly. 

But in iOS we are not able to get the receipt on sandbox tester account. We are unable to validate the receipt. We are using the following PHP function for store.validator. 
```PHP
<?php
  /*\* 
  -  \file check-purchase.php
    */

    function validate_receipt($receipt) {
    
        try {
   $end_point = 'https://sandbox.itunes.apple.com/verifyReceipt';
   $end_point = 'https://buy.itunes.apple.com/verifyReceipt';
            $ch = curl_init($end_point);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array('receipt-data' => $receipt)));
            $response = curl_exec($ch);
            $errno = curl_errno($ch);
            $errmsg = curl_error($ch);
            curl_close($ch);
            if ($errno !== 0) {
                throw new Exception($errmsg, $errno);
            }
            $data = json_decode($response);
            if (isset($data->status) && $data->status === 0) {
                return $data->receipt;
            } else {
                return FALSE;
            }
        } catch (Exception $ex) {
            return FALSE;
        }
    }
    
    $receipt=$_POST['receipt_data'];
    $rec = validate_receipt($receipt);
    echo json_encode($rec);
?>
```
Also, we are not clear on how to call this function from the app using store.validator. Can you please guide us to proceed further.

Thanks in Advance.

**Comment by Dexus** [comment]
have a look into https://github.com/Wizcorp/node-iap its nodejs but you can simply code it in PHP...

**Comment by stevecarlton** [comment]
@hariharanhs did you ever figured this out? I am struggling with the validation side of things.

One thing I did notice in your code above is that the $end_point is effectively pointing to production since there are two $endpoint lines, perhaps commenting the production line would have fixed the issue.
