### ISSUE TITLE
Product shows valid even though its not active in playstore.

### ISSUE THREAD

**Issue by kodeine** [j3k0/cordova-plugin-purchase#627]
Android,
```
title: "testing"…}
additionalData: null
alias: "test.subscription.one.dollar"
canPurchase: true
currency: "USD"
description: "$1"
downloaded: false
downloading: false
id: "test.subscription.one.dollar"
loaded: true
owned: true
price: "$0.99"
priceMicros: 990000
state: "valid"
title: "testing"
transaction: null
type: "paid subscription"
valid: true
```

it says `valid: true` and `canPurchase: true` even though the product is inactive in playstore.

**Comment by Dexus** [comment]
how long did you wait before you create this issue? You know that the changes need up to 8h?
Also you should always validate each purchase with your backend recipe validator and check against the enabled / disables products.

**Comment by giuseppelt** [comment]
Same issue here.
@Dexus is not about checking, is about retrieving and display on UI.

**Comment by Dexus** [comment]
Clear the cache of the store!

**Comment by drmistral** [comment]
Same problem here. using Android and plugin 7.1.3. 
Waiting updates for many hours and clearing playstore cache does not fix the problem.
Is there a way to detect if a product is not active on playstore?
