### ISSUE TITLE
[iOS] Auto-renewable subscription upgrade/downgrade

### ISSUE THREAD

**Issue by Almerick** [j3k0/cordova-plugin-purchase#629]
### system info
OSX Sierra 10.12.06
Device: iPhone iOS 10.2
Cordova v6.5.0
Plugin Version: tested 6.0.0 and 7.0.1

### Expected behavior
As per iTunes documentation (https://help.apple.com/itunes-connect/developer/#/dev06f89ce98), auto-renewable subscriptions should be set up in subscription groups, allowing users to upgrade, downgrade and crossgrade. The same documentation points to these events occuring on the subscription management page, which is not accessible in the Sandbox environment.

I have not seen any documentation for this plugin yet which covers handling these events within an app. My question then being, does this plugin support downgrading between products from within the app, as a user would normally purchase, or is this event purely intended to be triggered from the subscription management page?

### Observed behavior
I briefly tested this from within the app and was able to successfully upgrade, whereas with downgrades my logs return error 6777010, stating that it "Cannot connect to the iTunes Store" and the downgrade subsequently not being processed successfully.

I am aware that the recent iTunes server notifications mention the "DID_CHANGE_RENEWAL_PREFERENCE" event but again, due to the above, I have not been able to trigger this event.

From my understanding, upgrades/downgrades are prorated by iTunes and I ideally need to know how to handle this server-side and from within the app, if it is supported.

Thanks in advance,

AL

**Comment by aesculus** [comment]
I would like to understand this capability as well and for Android too.

**Comment by jbgomez21** [comment]
Hi @Almerick @aesculus 
I have exactly the same issue, do you have any solution for this?

Has anyone successfully used the plugin to auto-renewable subscription considering their variants?

In other words, make several purchases if I have already made one, delete the application and restore everything etc etc.

I can't do it working, same event fire several time with same information, no change in product among other things makes it difficult to use.

Regards

**Comment by Dexus** [comment]
Yes if you read the apple docs... you would know the Url for that...

Von meinem iPhone gesendet

**Comment by jbgomez21** [comment]
hi @Dexus 

Thx for your reply, can you be more specific please?
How can I with this plugin found in apple doc the answer for my question?

Thx!

Regards!

**Comment by Dexus** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html

Search for „Enabling Users to Manage Subscriptions“

Von meinem iPhone gesendet

**Comment by jbgomez21** [comment]
You propose to restrict that if for example you have done a weekly subscription and it is active and then you try to subscribe to a monthly subscription, the app will not allow you to do that to avoid error 6777010?
 
suggesting that you do that through "Users to Manage Subscriptions" https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/manageSubscriptions
 
Am I right about that?

Thank you very much for your time.

Greetings.
Juan.

**Comment by aesculus** [comment]
@Dexus: Thanks for the tip for just adding the URL to manage the subscription in iTunes. I am all for letting Apple do the heavy lifting. Great tip.
