### ISSUE TITLE
[IOS] Which ID to use?

### ISSUE THREAD

**Issue by davvidbaker** [j3k0/cordova-plugin-purchase#634]
Hey there, I am a little confused about which ID to use for iOS in-app purchases.

This is what I see in iTunes Connect:
![image](https://user-images.githubusercontent.com/6373939/31320977-d452b696-ac4b-11e7-8f33-9d6d42952222.png)

When I call `store.register, which one is the value for the id field?
```
      store.register({
        id: <<⚠️ WHICH VALUE GOES HERE? ⚠️>>,
        alias: 'my alias',
        type: store.NON_CONSUMABLE
      });
```

Thanks for any help anyone can offer!

**Comment by bshafiee** [comment]
you need to use ProductID I believe

**Comment by davvidbaker** [comment]
Yes @bshafiee is correct. Thanks!
