### ISSUE TITLE
[iOS] Support Apple's receipt validation? 

### ISSUE THREAD

**Issue by macfam** [j3k0/cordova-plugin-purchase#640]
Apple recently updated receipt validation for subscription based in-app purchases. I am curious if this plugin will support their newly updated methods/responses?

https://itunespartner.apple.com/en/apps/news/45333106

**Comment by jbgomez21** [comment]
Hi @macfam, 
Do you have this plugin working for auto renew subscription?

Please I need help with a working example!

Regards!

**Comment by Dexus** [comment]
Guys you need to use a validation service, that checks you subscription and retuns ok if it is ok or else an error.
Second you need an public api where apple send his subscription notifications that tells you how is the state of the subscription. Please read the Apple Developer docs and try to understand how it works. 

This Plugin is only one part that you can use or need to provide IAPs but thats not the only thing you need.

So please do not mix up application requests with server requests.

**Comment by macfam** [comment]
@Dexus so is it safe to assume that the newly added information will be returned to the [store.validator](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validator) method? That was the base of my question. 

@jbgomez21 yes, and I remember using [these examples](https://alexdisler.com/) to implement.

**Comment by Almerick** [comment]
@macfam yes, the new receipt fields are included in the iTunes response object, when validating. It will be present in the "pending_renewal_info" key, which is parallel to the "receipt" and "latest_receipt" keys. These new fields are not reliant on the plugin supporting it, purely based on iTunes including it in the validation response.

**Comment by macfam** [comment]
@Almerick perfect, thanks for the response.
