### ISSUE TITLE
[Android]what is android billing key?(license key?)

### ISSUE THREAD

**Issue by kotran88** [j3k0/cordova-plugin-purchase#642]
# !!! PLEASE USE IN SUBJECT [IOS] OR [ANDROID] AS PREFIX FOR YOUR ISSUE !!!

I revised document many times but can't find any of it. 
document says as belows. 
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Add Android Billing Key

Your license key for in-app billing should be added manually to your project. This key is found in Services and API in the Google Play Developer Console.

The license key is set during installation:

cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="MIIB...AQAB"
Replace MIIB...AQAB with your own android license key.

To change it, remove the plugin and add it back with the new key.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

**is this key from 
https://console.developers.google.com
- Credentials - create credentials button - Api key?????**

**Comment by thardes2** [comment]
You can find it here: 
![image](https://user-images.githubusercontent.com/6141477/32482396-c6ed2f3c-c397-11e7-85f8-3a5d45d4e429.png)

**Comment by agrove91** [comment]
Do I need to create a service account in order to get the license key?
