### ISSUE TITLE
IOS : [QUESTION] What happens if user cancels subscription and ask for refund from apple.

### ISSUE THREAD

**Issue by stripathix** [j3k0/cordova-plugin-purchase#646]
**Test Case:**
1) User buys an auto-renewing subscription
2) Uses application
3) Report problem to apple intentionally to get a refund.

Now how will I detect if user has got the refund from Apple and he should not be allowed to use application?

Will Apple even do any refund in this case?

**Comment by Dexus** [comment]
Apple will say please contact the developer.
But if the customer have a good description about the problem then Apple maybe will make a refund by it own. But normaly they will contact you in thouse problems.

But you can make sure the user have no access after refunding if you implement the validation in correct way. Server-side is the importend setup step..

**Comment by stripathix** [comment]
So by "Apple maybe will make a refund by its own" will apple do the refund on its own money and will not use my money for the refund?

**Comment by Dexus** [comment]
You will the charged for the refund or in other words, you will not get the payout of the refunded transaction.

**Comment by Almerick** [comment]
@stripathix, to identify whether Apple has refunded a user, validate the user's grand receipt with Apple. If the related transaction object contains  "cancellation_date" and "cancellation_reason" fields, it points to a refund processed, see: https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW19

Further, if you have a server implementation for your in-app purchases, I would recommend activating the recently introduced "Server Notifications". When a user has received a refund for a given transaction, Apple will send you a "CANCEL" server notification event for the related transaction, which you can then tie back to the user and handle accordingly. See,
https://help.apple.com/itunes-connect/developer/#/dev0067a330b and 
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW13

Regards
