### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Defcon0** [j3k0/cordova-plugin-purchase#648]
Is there any changelog to see what changed in 7.1.0?

**Comment by Dexus** [comment]
Sure you can use the commits but no really changelog file.

Von meinem iPhone gesendet

**Comment by Defcon0** [comment]
Too bad, not very dev friendly :-(

**Comment by j3k0** [comment]
I'd agree that git logs are not "non-technical people" friendly... But they are developer friendly.

## Only merge commits

    $ git log --merges v7.0.2..v7.1.0

commit 08f378f6575609ffb860acf4167b739bc461191f
Merge: 4f56ce9 b970ee9
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Thu Nov 16 10:14:43 2017 +0700

    Merge pull request #637 from j3k0/feature/ios-shouldAddStorePayment
    
    iOS: Add paymentQueue:shouldAddStorePayment:forProduct:

commit 4f56ce93ccf64b916655e26a10e5c60f77580d18
Merge: 9b0e5fd 68b278b
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Thu Oct 19 10:01:56 2017 +0300

    Merge pull request #636 from j3k0/fix/ios-early-observer
    
    iOS early observer

commit 9b0e5fdeb9308b605195e64a4a9dbdec9a3f5fec
Merge: fa40179 7f5e219
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Thu Oct 5 10:02:15 2017 +0300

    Merge pull request #632 from davvidbaker/patch-1
    
    Update Link to iOS in-app purchase guidelines

----

## Only non-merge commits

...for more details:

    $ git log --no-merges v7.0.2..v7.1.0

commit 4b228c2f497cef95cf33360322d1401ada8d441b (HEAD -> master, tag: v7.1.0, origin/master, origin/HEAD)
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Thu Nov 16 10:15:59 2017 +0700

    7.1.0

commit b970ee957c93875361664a718b935fe52f287722 (origin/feature/ios-shouldAddStorePayment, feature/ios-shouldAddStorePayment)
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Thu Oct 19 10:23:29 2017 +0300

    iOS: Add paymentQueue:shouldAddStorePayment:forProduct:

commit 7f5e219e14f06f8a9d2dd1dc6abbf7a187166512
Author: David Baker <drbaker2@gmail.com>
Date:   Wed Oct 4 20:08:51 2017 -0400

    Update Link to iOS in-app purchase guidelines
    
    The pdf that used to be linked no longer exists. The link I replaced it with is the new (as of iOS 11) place to find this information.

commit 68b278b66e99c0ce99d72af997c91f1aca26d794 (origin/fix/ios-early-observer, fix/ios-early-observer)
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Wed Oct 4 14:38:55 2017 +0300

    Set onload=true to initialize early

commit dbddf6cc7884444b1bc2f654026fa2cda61a639c
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Wed Oct 4 12:02:44 2017 +0300

    iOS: Log processing pending transactions

commit 6a779a76007e1cbed167389b7048423a7d8413a4
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Wed Oct 4 11:38:57 2017 +0300

    iOS: Add the transaction observer at initialization
    
    ... i.e. regardless if the JS side is ready
    
     * Store early updates in a "pending" list.
     * Wait for the JS side to be ready.
        * I consider this to be "when product infos has been loaded"
     * Send pending updates after the loading of products.

commit 8ec6ff30b6afca9ccb57b046165635796884ea2b
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Wed Oct 4 09:39:57 2017 +0300

    iOS: Cleanup InAppPurchase.m
    
     * Consistent styling
     * More logging
     * Handle onReset

commit fa40179236e32146e9026688ab1e7bd34f8768f2
Author: Jean-Christophe Hoelt <hoelt@fovea.cc>
Date:   Tue Oct 3 08:36:47 2017 +0300

    iOS: Set autoFinish to NO by default

**Comment by remisture** [comment]
Is there an upgrade guide from 6.1.2 to 7.1.0 somewhere? What are the breaking changes?
