### ISSUE TITLE
[WINDOWS 10] 6777001: Init Failed - undefined

### ISSUE THREAD

**Issue by franalt** [j3k0/cordova-plugin-purchase#650]
Hello everyone.

I am trying to set up Windows 10 (Desktop) purchases for my app. On Android everything is working fine, but on Windows when calling store.refresh() I get "6777001: Init failed - undefined".

I installed the plugin via:

`cordova plugin add cc.fovea.cordova.purchase`

I added in-app-purchase.xml to my root www project folder, with the following content:

`<?xml version="1.0" encoding="utf-16" ?>
<CurrentApp>
  <ListingInformation>
    <App>
      <AppId>MY APP ID</AppId>
      <LinkUri>MY APP'S STORE LINK</LinkUri>
      <CurrentMarket>en-us</CurrentMarket>
      <AgeRating>3</AgeRating>
      <MarketData xml:lang="en-us">
        <Name>Pranadigma</Name>
        <Description>CordovaApp</Description>
        <Price>0.99</Price>
        <CurrencySymbol>$</CurrencySymbol>
        <CurrencyCode>USD</CurrencyCode>
      </MarketData>
    </App>
    <Product ProductId="pranadigma_unlock" ProductType="Consumable">
      <MarketData xml:lang="en-us">
        <Name>Pranadigma Unlock</Name>
        <Price>0.99</Price>
        <CurrencySymbol>$</CurrencySymbol>
        <CurrencyCode>USD</CurrencyCode>
      </MarketData>
    </Product>
  </ListingInformation>
  <LicenseInformation>
    <App>
      <IsActive>true</IsActive>
      <IsTrial>false</IsTrial>
    </App>
  </LicenseInformation>
</CurrentApp>`

And here is my main JS code (This runs onDeviceReady()):

`       store.verbosity = store.DEBUG;

        store.sandbox = true;

        store.register({
            id:    'pranadigma_unlock', // id without package name!
            alias: 'pranadigma_unlock',
            type:  store.CONSUMABLE
        });

        store.when("pranadigma_unlock").approved(function (order) {
            navigator.notification.alert("Purchase approved!");
        });

        store.when("pranadigma_unlock").cancelled(function (order) {
            navigator.notification.alert("Purchase cancelled...");
        });

        store.ready(function() {
            navigator.notification.alert('The store is ready!');
        });

        store.error(function(error) {
            navigator.notification.alert('Store error: ' + error.code + ': ' + error.message);
        });

        store.refresh();`

Im running:

Windows 10
Cordova 7.1.0
Plugin Version: Latest

Can anyone point me in the right direction?

Thanks!

**Comment by Dexus** [comment]
This plugin does not work for Desktop Apps only Windows Mobile.

Regards, Josef

Von meinem iPhone gesendet
