### ISSUE TITLE
How to Restore Purchase in iOS when user already purchase product?

### ISSUE THREAD

**Issue by singhlovey** [j3k0/cordova-plugin-purchase#652]
Hi,

I just want to know is there any function which I can use to fetch restore purchase in iOS app. I am using this plugin in iOS app and using [cranberrygame/cordova-plugin-payment-iap](url) plugin in android app and they have provide function **restorePurchases() { }** function to fetch already purchased product details. I want the same in iOS app.

Please help ASAP!

It would be great if someone provide example code.

Thanks

**Comment by singhlovey** [comment]
Hi,

Can you please reply for the above

Thanks

**Comment by remisture** [comment]
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storerefresh
