### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by Jacse** [j3k0/cordova-plugin-purchase#653]
Hi @j3k0 

I've used your wonderful plugin on my old Cordova projects a lot, but I've now moved over to using React Native. Unfortunately, I've found that no purchase library works as well as yours. Firstly, there are two different ones, one for Android and one for iOS, and secondly, neither has support for finishing transactions like yours.

In practice that means that when users pay, but something goes wrong in my end, the transaction is finished automatically anyway and users end up paying for something they did not receive.

So my question is whether you could be persuaded into porting your library to support React Native? That would be amazing, the community really needs one purchase-library like yours.

**Comment by ozexpert** [comment]
@Jacse you can use https://github.com/axemclion/react-native-cordova-plugin to use the cordova plugin FYI.

**Comment by j3k0** [comment]
@Jacse, thanks for the good words 😄  Please re-open in case the @ozexpert solution doesn't work.

**Comment by Jacse** [comment]
@ozexpert I'm afraid that package is not maintained anymore. It only works for [old versions of React-Native](https://github.com/axemclion/react-native-cordova-plugin/issues/44).
