### ISSUE TITLE
Uncaught ReferenceError: store is not defined

### ISSUE THREAD

**Issue by abhi21x** [j3k0/cordova-plugin-purchase#655]
Uncaught ReferenceError: store is not defined.

OSX Sierra 10.13.1
Cordova 7.1.0
Device: Android 7.1
Plugin Version: 7.1.0

**Comment by Dexus** [comment]
Can't reproduce it... 

Do you have a special browser plugin?

Von meinem iPhone gesendet

**Comment by abhi21x** [comment]
Using these Crodova plugins, nothing special

cc.fovea.cordova.purchase 7.1.0 "Purchase"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Can't access store variable
