### ISSUE TITLE
Subscription Cancellation

### ISSUE THREAD

**Issue by cdcv** [j3k0/cordova-plugin-purchase#657]
I don't believe that the plugin currently supports cancellations of subscriptions.  If it does, it would be great if this were better documented.
This would be a great feature.
In the meantime, how does one deal with users that want to cancel a recurring subscription (iOS or Android)?

Thanks

**Comment by AlexeyYar** [comment]
Same question! How to cancel user's subscription? He even doesn't see subscription in his list, so can't cancel it.

**Comment by Dexus** [comment]
For the iOS users you can read the iOS Developer Docs and you will find a Link where you can link too so the user can manage his subscription.

On android you can include a button and call your own api server that handle the subscription cancel of the subscription. Or you give them a hint how to do via the playstore.

That are your options, but you need to read the manuals of the iOS Developer Guids and same for the android stuff. Have Fun.

**Comment by Dexus** [comment]
BTW this plugin support a mass of things, but the subscription management is not part of this plugin because you need your own service and processing for it, else it would be to unsecure and your app and purchases are easy to hack because you will need much more secure nonpublic keys in your app... so think about that before you cry'ing about what the plugin not support and think about why it is not support the features that you would like to see.

**Comment by HarelM** [comment]
Any chance to revisit this @Dexus @j3k0?
Google just posted a change in requirement to allow users to cancel the subscription from within the app...

**Comment by zstadler** [comment]
Google policy update says:

> **Effective September 30, 2022**
>
 >   We’re updating our Subscriptions policy to state that users must be able to easily cancel their subscriptions from within the app.

**Comment by zstadler** [comment]
> BTW this plugin support a mass of things, but the subscription management is not part of this plugin because you need your own service and processing for it, else it would be to unsecure and your app and purchases are easy to hack because you will need much more secure nonpublic keys in your app... so think about that before you cry'ing about what the plugin not support and think about why it is not support the features that you would like to see.

Currently, subscription management is done with this plug-in without a need for seller's "own service and processing for it"

**Comment by FlueschPluesch** [comment]
You can use store.manageSubscriptions();
