### ISSUE TITLE
[iOS] auto-renewing `product.owned` is true even after store.validator callback returns `store.PURCHASE_EXPIRED`

### ISSUE THREAD

**Issue by justin-schroeder** [j3k0/cordova-plugin-purchase#662]
### System Info

MacOS: 10.13.12
iOS: 11.2.1
Running in sandbox mode with a valid sandbox user on a physical iPhone 6 plus.

### Issue Description

We have an auto-renewing subscription setup in iTunes connect. We are able to purchase the subscription, perform server side validation of the receipt with apple on our servers, and using a the custom validator callback feature set the `product.owned` status to true. However, when our server indicates that the auto-renewing subscription is expired, the product never goes from 'owned:true' to 'owned:false'.

Here's a simple example:
```js
store.validator = function (product, verify) {
  ourApi.validate(product.transaction)
  .then(status => {
    if (status === 'success') {
      console.log('valid product')
      verify(true, {})
    } else if (status === 'expired') {
      console.log('subscription is expired')
      verify(false, {
        code: store.PURCHASE_EXPIRED,
        error: {
          message: 'Subscription expired'
        }
      })
   } else {
      console.log('some other error')
      verify(false, {
        error: {
          message: 'Some other error'
        }
      })
   }
  })
}
```

In the above example, I can confirm that the `subscription is expired` block is executing properly and returning the proper response code to the plugin (`6778003`) How can we make the product revert to `owned:false`?

**Comment by ultisoftmeta** [comment]
Did you try "canPurchase" rather than owned?

**Comment by ultisoftmeta** [comment]
I have not tried that yet but yes your description is right and I am thinking that maybe "canPurchase" indicates if product is ready for purchase.

I will really appreciate if you can share your experience after you try " canPurchase".

Thanks

**Comment by ultisoftmeta** [comment]
Did this work for you? Thanks.

**Comment by znegva** [comment]
I am running into the same issue: an auto-renewing subscription is always `owned:true` for iOS-device/apple-sandbox-user, even through it _should_ be auto-canceled after some time (at least thats what apple docs say...).
For now I am only testing with a sandbox user, hopefully this is the cause of this nasty problem. 

On Android everything is working fine: a subscription is `owned:true` when subscribed, after some renewals (for which i get an email from google play store..) the subscription ends and the purchase-plugin correctly sets `owned:false` for the product.

**Comment by stevecarlton** [comment]
I was having a similar issue, my validator was returning that the subscription was expired but it was still owned. Turned out that it was because I was not signed in or had not verified my itunes sandbox account. The plugin was attempting to refresh the receipts but it was failing and the product was never updated after getting the expired response.

**Comment by znegva** [comment]
testing with a different sandbox account still does not solve the problem for me.
Even worse, the second sandbox user also _ownes_ my auto-renewing-subscription... so there seems to be a problem that some caches are not being cleared... maybe #109 is related to this (my) problem?

**Comment by NoFrank** [comment]
I have the same issue on iOS. The subscription is expired and the verification returns store.PURCHASE_EXPIRED but the product is still owned.

**Comment by MovingHead** [comment]
I have the same problem. Is there still no answer?
