### ISSUE TITLE
Ionic 3 Implementation help

### ISSUE THREAD

**Issue by HardikDG** [j3k0/cordova-plugin-purchase#663]
Has anyone implemented working demo for this plugin to use in Ionic 3?
I need some help regarding `this.store.off` , How can we use call this function with a callback function? 

When I implemented it with the sample code it is giving me an uncaught error in promise when calling purchase/configuration method. Any solution for that?
https://medium.com/@andrew.thielcole/in-app-purchases-with-ionic-3-af13b21f49f2

**Comment by Dexus** [comment]
We don't support wrapper of 3rd party vendors. 

Please look at https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/in-app-purchase-2/index.ts

**Comment by HardikDG** [comment]
Yes. I am using that wrapper only, but I was having some issue with its implementation, so I have opened the issue as I am not sure issue is from which side.

**Comment by Dexus** [comment]
To use the `off` function you need to globalize the function in a variable.

`var/let myfunc = function(...){...}`

and then use the `...off(myfunc)`
