### ISSUE TITLE
Validator Server documentation lacking

### ISSUE THREAD

**Issue by TPETb** [j3k0/cordova-plugin-purchase#667]
First of all, thanks for you hard work with this plugin. It is a solid piece of software! Keep it up!

Unfortunately there a serious topic missing from API Documentation. I can't find information on how do I implement a service to validate subscription status. There's no info on _what_ is passed to server, _what_ is expected in response etc. Should it be just "200 OK" response? Should it be a 200 response with JSON body? What should be in this body? What about request data? Is it just a pure JSON body? Is it a POST param request?

I could only find a link to "Fovea's reeceipt" service, but it is in private beta and no way I can access it in order to try replicating.

Could you please provide documentation describing request/response format for validator service? 

Thanks in advance

**Comment by manzajaro** [comment]
+1

**Comment by sebastian-zarzycki-es** [comment]
Why in the hell is this closed? This was a valid question.
