### ISSUE TITLE
iOS TestFlight User Locks Up Server Validation On Production App

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#674]
I am using this code from #431 which is great in most cases. However if the user an a TestFlight user I must switch the endpoint to:

https://sandbox.itunes.apple.com/verifyReceipt

I do this via a flag in Additional Data.

My problem is if a TestFlight user fails to Stop Testing my app and then loads the production version, Apple still thinks they should be a sandbox user. This ends up locking up my server and throttling the memory.  I have not dived into exactly what is happening on the server code but I wonder if someone has a suggestion on how I can avoid, trap, or respond to this situation.

**Comment by Dexus** [comment]
first of all you should always first use sandbox verify and then on error... productive verify... else you don't get accept the app to the store...

**Comment by j3k0** [comment]
> first of all you should always first use sandbox verify and then on error... productive verify... else you don't get accept the app to the store...

Not 100% sure, but isn't it the other way round? prod -> failure -> sandbox

**Comment by Dexus** [comment]
Yes both ways are ok

Von meinem iPhone gesendet

**Comment by aesculus** [comment]
I suppose in my scenario I should first run the 'https://sandbox.itunes.apple.com/verifyReceipt' since it's the sandbox user that is causing the lockup at 'https://buy.itunes.apple.com/verifyReceipt'.

But I am not certain yet why the CURL code locks up the server when a test user goes against the production verify url.  I guess I need to dive deeper into that code and figure out why.

**Comment by Dexus** [comment]
Normaly you call first the productions API and with the error "this recipt is for sandbox" you start the same call against the sandbox.

I don't know what for a CURL code you mean ... there i can't help you.

**Comment by aesculus** [comment]
The CURL code was referenced in the first post. #431

**Comment by aesculus** [comment]
@Dexus : Thank you for providing the updated sample. I was busy with other things and did not get a chance to implement it until now.

Using a test account when I execute the code my server basically locks up (the memory jumps to 700 mb) and the CPU pegs at 100%.  I don't receive any errors but I have not yet pinned down where this occurs.

I am trapping the status and I get this:
'status' => 21002 
The data in the receipt-data property was malformed or missing.

**Comment by aesculus** [comment]
On the 21002 issue it seems that I may need to check for this as well as the 21007 and submit both to the sandbox validator?

`else if(isset($data->status) && ($data->status === 21007 || $data->status === 21002)){`

https://forums.developer.apple.com/thread/44603

**Comment by aesculus** [comment]
The 21002 status was a miss copied pw. I left a digit off.

When I am running a TestFlight user I am getting this error from CURL

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104 code=56
CURLE_RECV_ERROR (56) Failure with receiving network data.

Nothing on Google coming up with a solid suggestion or relevant problem at this point. Still stumped.

**Comment by Dexus** [comment]
Your PHP version looks like outdated... or your openssl, curl libs...

**Comment by aesculus** [comment]
I am still on PHP 5.6.  Do you think going to 7.1 would help?

**Comment by Dexus** [comment]
Don't know your system setup, but I know sometimes your server can't handle the req/second...

Use Nodejs or a GOlang server... PHP is to slow and many setups are not able to handle the massive request counts per sec... but thats only my thoughts...

**Comment by aesculus** [comment]
Might  be a bit off topic but I am currently working to reduce the number of requests from the app.

ie as soon as I get a valid subscription (my app really only has two levels - paid and free) I am calling store.off('product_id') for each product so it stops hammering the server unnecessarily.  Not sure if this is sound logic or not but I figured it could not hurt.

**Comment by aesculus** [comment]
Status Report: It appears that my server lockups are the result of my app overrunning the server with requests to Apple for confirmation.  I have a number of subscriptions and some of the test machines have a lot of purchases.  

The problem was that I was using when instead of once in the approved callback. This resulted in multiple unnecessary calls the to server for confirmation, all dealing with the most recent receipt so they were redundant at best but worse, over burdening the server. Compounding this would be production requests and if they all came in at the same time the server got backed up and resources got exceeded etc.

Still waiting for some confirmation from beta users to make sure my fix is solid, but at least the server does not get overrun at this point.
