### ISSUE TITLE
[ANDROID] Server validation for a total newbie!

### ISSUE THREAD

**Issue by blackicicle** [j3k0/cordova-plugin-purchase#677]
Hello, I have an app with in app purchase and I am trying to figure out how I can implement the server side validation. Everything that I've read so far just leaves me more confused. Especially the token expiration of 1 hour etc. side for google. (That left me really confused)

Currently the store works and purchases can me made. But a few days ago I woke up to check the app and a user had a score of like $1,000,000,000,000 and fully upgraded where everyone else had like like $34,000.

So far in my app:
```
	store.register({
		id:    "com.bcgmobile.globalempire.productionboost",
		alias: "productionboost",
		type:  store.CONSUMABLE
	});
	function doPurchaseProduction(){
		store.order("productionboost");
	}
	store.when("productionboost").approved(function (order) {
		doStorePurchaseProduction();
        	order.finish();
	});
```

I know that I have to use this instead (after the product is approved) but I'm totally lost on how to implement it:
```
	store.when("productionboost").verified(function(order) {
		doStorePurchaseProduction();
		order.finish();
	});
```

What I've done so far:
   1. I have created a new user from my developer console
   2. I have given that user the permission: Finance->View financial data
   3. I have uploaded the google-api-php to my server

I have NO idea what to do next! Please keep in mind that I am EXTREMELY new so saying check this link out will probably not be of much help. I'm only asking because I've spent the last two days researching and have come up empty handed.

So can some one please outline a step by step guide on what I need to do next?

**Comment by aesculus** [comment]
Did you set your external validation point with:
store.validator = 'your validation url';

Then when the plugin needs to confirm if the subscription is valid it will call that routine and pass it the receipts for you to validate with Google. On return it will call your verified callback for you to process app side with whatever you gave it back from your server code in the return.

**Comment by j3k0** [comment]
Hey @blackicicle,

Did you consider integrating https://billing.fovea.cc

It's a no brainer, it'll handle the hard part for you.
