### ISSUE TITLE
Subscription transactions.

### ISSUE THREAD

**Issue by keepersiete** [j3k0/cordova-plugin-purchase#68]
I've been reading the docs during a big while and I can't figure it out what was happening to me.
I've set a subscription item on iTunes Connect And I launch order function. Then I get the next State from my product:
{"id":"Complete1YearPruebas","alias":"Complete1YearPruebas","type":"paid subscription","state":"owned","title":"Brick Calculator + Clinker Form","description":"Full access to app functionality","price":"0,89 €","currency":null,"loaded":true,"canPurchase":false,"owned":true,"transaction":null,"valid":true}

As shown above, the purchase has been made but no transaction info is stored after the purchase. During it a managed to get this info as transaction:
{"type":"ios-appstore","id":1000000130262128"}

I've tried to launch validator as the docs said using store.fovea.cc:1980/check-purchase but I got an AJAX error. 
I'm stuck in the middle of the process, with no sbusciption verification, and I don't know how to go on.
Thanks a lot,
Endika

**Comment by JefferE** [comment]
@j3k0 

< Alternatively, you register for fovea's reeceipt validation service here >

Is this still an ongoing beta or a dead project offering?
