### ISSUE TITLE
[ANDROID] App crashes after purchase

### ISSUE THREAD

**Issue by haleo9000** [j3k0/cordova-plugin-purchase#681]
### system info

In example:
```
OSX Sierra 10.13.3
Cordova 7.0.1 // Phone Gap 3.19.2 etc.
Device: iPhone iOS 10.3.2 // Android 7.1
Plugin Version: 6.0.0
```

### Expected behavior
I can load up the store after I've made a purchase.

### Observed behavior

I've recently added this into a Meteor application, and am running into a seemingly strange error. With my logs set to debug, I am able to see the following information:

>03-01 08:36:28.906 850-850/appName I/chromium: [INFO:CONSOLE(1496)] "[store.js] DEBUG: store.trigger -> triggering action refreshed", source: http://localhost:12656/plugins/cc.fovea.cordova.purchase/www/store-android.js (1496)
03-01 08:36:28.906 850-850/appName I/chromium: [INFO:CONSOLE(1496)] "[store.js] DEBUG: queries !! 'refreshed'", source: http://localhost:12656/plugins/cc.fovea.cordova.purchase/www/store-android.js (1496)
03-01 08:36:28.906 850-850/appName I/chromium: [INFO:CONSOLE(2023)] "InAppBilling[js]: setup ok", source: http://localhost:12656/plugins/cc.fovea.cordova.purchase/www/store-android.js (2023)
03-01 08:36:28.906 850-850/appName I/chromium: [INFO:CONSOLE(2023)] "InAppBilling[js]: load ["id1","id2"]", source: http://localhost:12656/plugins/cc.fovea.cordova.purchase/www/store-android.js (2023)

The above logs are thrown in the InAppBilling.prototype.init function in store-android. The skus are the same as the ids defined on each product in the store, and it never gets past here. Any ideas on how to troubleshoot further would be greatly appreciated, as this is the point cordova.exec() is called.

Additional Note: Everything works fine and I am able to test purchase one of my products. Once I've purchased it, however, is when the crashing starts.

### Steps to reproduce
To start (when everything is unpurchased), the store loads without comment or complaint. Once I've made a (test) purchase, the application crashes on refresh, then subesquently every time the store loads.

**Comment by haleo9000** [comment]
Are there any ideas out there for what might be going on with this? Any help would be great.

In following some of the other comments and issues, I ensured the refresh is only called once, but that has not seemed to help.

**Comment by wifisher** [comment]
My reply may be a little late, but I have seen something similar with an app crashing after purchase of an item. My issue turned out to be an install issue with the plugin.

The billing key had not be set in platforms/android/res/values/billing_key_param.xml which resulted in an exception from the base64 code.

Fixing the billing key resolved the issue for me. (Reinstalled the plugin.)
