### ISSUE TITLE
[IOS] Copying hosted content package (300Mb) to documentsDirectory takes several minutes

### ISSUE THREAD

**Issue by jasald3** [j3k0/cordova-plugin-purchase#682]
### system info
```
OSX Sierra 10.12.6
Cordova 8.0.0
Device: iPhone iOS 11.2.1
Plugin Version: 6.1.2
in-app purchase type: non-consumable
```

### Expected behavior
Right after downloading the hosted content package, the plugin copies it to the documentsDirectory as explained in https://github.com/j3k0/cordova-plugin-purchase/wiki/Apple-Hosted-Content#user-content-deployed-content-location 
### Observed behavior
My hosted content package (around 300Mb) contains a set of audio files within a special directory structure. I have checked the logs and the download time is not a problem, the problems is that it takes ages (More than 10min) when the plugin copies the directories/files to the documentsDirectory after the download.

Does anyone have the same issue?

Thanks!

**Comment by Dexus** [comment]
I think its the problem of the phone and has nothing to do with the plugin.

**Comment by jasald3** [comment]
@Dexus, thanks for replying. I do not think that the problem might be the phone, the app is being tested using TestFlight in different devices.
