### ISSUE TITLE
[IOS] App crashed while refresh() is called the second time

### ISSUE THREAD

**Issue by Defcon0** [j3k0/cordova-plugin-purchase#683]
Since this seems to be a major bug, I emphasize that I'll help as much as I can to fix this (error reports, testing, bringing more information about my code).

If it's helpful, I activated XCode Zombies and here's the line the issue occurs:

`2018-03-03 11:18:10.565056+0100 MyApp[899:541638] *** -[RefreshReceiptDelegate respondsToSelector:]: message sent to deallocated instance 0x1c462d2a0`

I suspect the problem in the following:

When I refresh(), it calls a login dialogue. But in the background you can see that the login already has been performed, so that the validation stuff can be handled. But the login window is still open in the foreground. Now when I cancel or type in the credentials and tap "OK", the plugin seems to access an object that was there at the time of opening the login window but is now gone.

If that's the cause, the fix would be as easy as checking for a non existing object in the line above.

### system info

```
OSX Sierra 10.12.6 (16G1114)
Cordova 7.1.0
Device: iPhone iOS 11.2.6
Plugin Version: 7.1.2
```

### Expected behavior

No crash ;-)

### Observed behavior

Crash :-)

### Steps to reproduce

1. Log out in Settings -> iTunes & AppStore
2. Open app
3. call refresh()
4. call refresh() second time in order to restore the purchases (this is done in store.ready() )
5. Puchases are being restored and then the app crashes

**Comment by Defcon0** [comment]
Update: The issue also occurs when the appleid login popup doesn't show up :-(

**Comment by j3k0** [comment]
Hi. Can you check that you have the same behaviour with the demo app? Last
time i checked it was alright. If so, figure out what's different in your
code.
