### ISSUE TITLE
Get list of all products without registering them?

### ISSUE THREAD

**Issue by rtm** [j3k0/cordova-plugin-purchase#688]
Apologies if this is not the right forum for such questions.

I am confused as to why I need to provide a list of products using `store.register`. This prevents me from building my app in such a way that I could add new products by just adding entries to a database or the Google Play in-app purchases list. Is this a restriction of how the stores work? Or am I missing some way to retrieve a list of all products registered in the store?

**Comment by j3k0** [comment]
Yes this is a restriction. You can still add your products ids and types to a database on your server and have your client requests this list before registering all products you server replies.
