### ISSUE TITLE
[IOS] Multiple Authentications for Purchase and Refresh

### ISSUE THREAD

**Issue by aabdolla** [j3k0/cordova-plugin-purchase#689]
Hello,

I am using the latest cordova, plugin and iOS versions. I have implemented the plugin and I am running into being forced to authenticate up to three times when purchasing a non consumable product and refreshing. This only happens on iOS, not on android. Has anyone else ran into this issue? I expect at least one authentication for the purchase and refresh but I don't understand why it is happening multiple times.

    initProducts() {
	if (!this.platform.is('cordova')) {
		return;
	}

	var products: any = {};

	let productId;

	if (this.platform.is('ios')) {
    	     productId = this.product.appleProductId;
	} else if (this.platform.is('android')) {
    	     productId = this.product.googleProductId;
  	}

	products[productId] = {
		id: productId,
		alias: productId,
		type: store.NON_CONSUMABLE
	}

	store.error((err) => {
	alert('Store Error ' + JSON.stringify(err));
	})

	store.when(productId).approved((order) => {
		console.log("approved");

		order.finish();

		this.updateProducts();
	});

	store.when(productId).updated((data) => {
		console.log('Loaded' + JSON.stringify(data));

		this.updateProducts();
	});

	store.when(productId).owned((data) => {
		console.log("owned");

		this.updateProducts();
	});

	store.when(productId).cancelled((data) => {

		alert('Purchase was Cancelled');

		this.updateProducts();
	});

	store.when("refresh-completed", () => {
		console.log("restorePurchase finished with refresh");

		console.log("refresh " + productId + " owned: " + store.products[productId].owned);

		alert('Finished Restore');
	});

	store.when(productId).error((err) => {
		
	    alert('An Error Occured ' + JSON.stringify(err));
	});

	console.log("register: " + products[productId]);
	store.register(products[productId]);

	this.initStore();
}

    initStore() {
	let productId;

	if (this.platform.is('ios')) {
    	     productId = this.product.appleProductId;
	} else if (this.platform.is('android')) {
    	     productId = this.product.googleProductId;
  	}

	store.verbosity = store.DEBUG;
	store.ready(() => {
		
		console.log(productId);

		let product = store.get(productId);

		this.updateProducts();
	});
	
	store.refresh();
}

    updateProducts() {
	if (store) {
		if (store.hasOwnProperty('products')) {
			console.log(store.products);

			this.productArr = store.products;
		}
	}
    }

    async purchase() {
	if (!this.platform.is('cordova')) { return };

	 

	let productId;

    if (this.platform.is('ios')) {
      productId = this.product.appleProductId;
    } else if (this.platform.is('android')) {
      productId = this.product.googleProductId;
    }

	try {
		console.log("purchase: " + productId);

		let product = store.get(productId);

		let order = await store.order(productId);
	} catch (err) {
		console.log('Error Ordering ' + JSON.stringify(err));
	}
    }

    async restorePurchase() {
	if (!this.platform.is('cordova')) { return };

	let productId;

	if (this.platform.is('ios')) {
		productId = this.product.appleProductId;
	} else if (this.platform.is('android')) {
		productId = this.product.googleProductId;
	}

	console.log('Products: ' + JSON.stringify(store.products));

	console.log('Refreshing Store: ' + productId);

	try {
		store.refresh();
	} catch (err) {
		console.log('Error Ordering ' + JSON.stringify(err));

	}
    }

**Comment by tattivitorino** [comment]
@aabdolla one question:
I saw you set up the handler 'refresh-completed' but as far as I know base on everything i've read about this plugin there is no handler for the store.refresh(). Which is a shame cause I think its important to have a callback handler for that. Does it work for you?
