### ISSUE TITLE
[ANDROID] This plugin is incompatible with Cordova 8

### ISSUE THREAD

**Issue by tlhunter** [j3k0/cordova-plugin-purchase#690]
Adding this issue for visibility. For more details see #673. The current solution is to downgrade to Cordova 7.

**Comment by theosanderson** [comment]
Thank you for this - I have been wrestling with this for hours. (Would suggest that this is added to documentation ASAP even in the absence of another fix).

**Comment by j3k0** [comment]
v7.1.3 should fix the issue.
