### ISSUE TITLE
[IOS]  Is there a way to verify if my app has been purchased from the Apple Store? 

### ISSUE THREAD

**Issue by llKreator** [j3k0/cordova-plugin-purchase#691]
Hello! Is there a way to verify if my app has been purchased from the Apple Store? 
Because I found only information about iap receipts and their management, nothing on the app purchase.

**Comment by Dexus** [comment]
The receipts are the notify for the purchases of the items, there are no official in app way to verify the app purchase.

**Comment by llKreator** [comment]
thank you for answer
