### ISSUE TITLE
[ANDROID] Understand If Item Purchased

### ISSUE THREAD

**Issue by theavijitsarkar** [j3k0/cordova-plugin-purchase#693]
### system info

```
Cordova - 7.1.0
Android 7
Plugin latest

```

How do I understand if an item has been purchased.
My app has in app gifts that can be purchased only once for one user. 

```
store.when("product").approved(function(product){
		product.finish();
	});
```
The above code is there, I am able to make purchases and the payment is also successfull, the code even hits finish. But later when I do this.

```
store.get(itemId).owned 
```
It is false. How do I check a purchase?

**Comment by gonzalle** [comment]
if your product was recently refreshed you simply have to ask for `product.owned`
