### ISSUE TITLE
Reserved word 'store' collision with Vue 'State Management' standard

### ISSUE THREAD

**Issue by ogardiazabal** [j3k0/cordova-plugin-purchase#696]
I think it's a mistake make **`window.store`** globally and not inside **`cordova.store`**. 
**`store`** is a **reserved word** in the standard of **Vue** to handle "**State Management**"

I think your plugin is nice so I will change the Vue standard, but is not an elegant solution.
Is there a workaround for this?

**Comment by j3k0** [comment]
The `window.store` export dates from the stone-age of cordova. It'd been kept around for backward compatibility with old apps. I guess it's safe to deprecate this now, we might just remove it with the next major release.

Until then, you can probably get around the problem by running `delete window.store` before loading Vue.

**Comment by alexcroox** [comment]
Does this mean you can use `cordova.store` instead of just `store.` like the examples show? Because cordova.store is undefined for me.
