### ISSUE TITLE
[ANDROID] Order being finished before product.finish()

### ISSUE THREAD

**Issue by augustoColasanti** [j3k0/cordova-plugin-purchase#697]
The order is completed before product.finish() be executed.

My code:

Right after initialization:
```
store.register({
                            id:    "com.app.test.p1",
                            alias: "product 1",
                            type:  store.CONSUMABLE
                        });

store.when("com.app.test.p1").approved(function(p) {
                            app.backendrequest
                                    .then(function(response){
                                        p.finish();
                                    })
                        });
```
whever user select product 1:
```
store.order("com.app.test.p1");
```
However, before my backend app request execution, I can see that the order is already completed. I just would like to complete the order after the backend request, so I can make sure that we have registered user's order. Am I doing something wrong?

Thanks in advance!

```
Cordova 7.1.0 // Phone Gap 7.0.1
Device: Android 7.1
Plugin Version: 7.1.3
```

**Comment by AmroAlJundi** [comment]
This happened with me when using the test purchases. Does this happen with normal purchases as well?

**Comment by AmroAlJundi** [comment]
@augustoColasanti Did you find a solution for this? Does it happen with normal purchases as well as test purchases?
