### ISSUE TITLE
[iOS] auto-renewing subscription failed in second month only on iOS

### ISSUE THREAD

**Issue by hariharanhs** [j3k0/cordova-plugin-purchase#699]
**System Info:**

iOS: 11.2.1
Android : 7

**Issue Description:**

We have implemented an auto-renewing subscription in our app. 
We are able to purchase the subscription (iOS,Android), we are using our own server for receipt validation. 

**Our code does the following things:**

1. Will receive the product details from the store.
2. We check if it the state is "Approved" or not. If it is in approved state, then we check that the product is in "CanPurchase" mode. If it in Can purchase mode, we intimate the user to buy the subscription, Or else, we check the "Owned" state of the product. If "owned" state is true, it will leave the user to use the app or else intimate the user to purchase the app.

_```
if(Approved){
     if(canPurchase){
          //leads to purchase
     }else{
          if(owned){
	       //can continue using the app
          }else{
               //leads to purchase
          }
     }
}else{
     if(owned){
          //can continue using the app
     }else{
          //leads to purchase
    }
}
```_

**The problem is:**

1. One of our user reports that, she has auto-renewal enabled in the store. She started the subscription two months back. It works fine for the previous month. But after this month renewal, she faces a problem that the app leads her to the purchase page. But when she tries to purchase, the store returns that she already have the subscription. It seems our above code breaks somewhere. Can anyone help us in handle the auto renewal process in iOS?

**Comment by j3k0** [comment]
The above code is incomplete, so hard to review. Anyway, the documentation should contain everything you need. I you want prioritized support please contact me by email at hoelt@fovea.cc

**Comment by j3k0** [comment]
Not enough data, closing this.
