### ISSUE TITLE
Add support for applicationUsername in purchase requests

### ISSUE THREAD

**Issue by j3k0** [j3k0/cordova-plugin-purchase#70]
``` js
store.setApplicationUsername("HASHVALUE")
```

Then all calls to store.purchase will use this HASHVALUE

``` js
store.when("product").approved(function(product) {
    product.applicationUsername; // it's there!
});
```

Original request:

> **applicationUsername property.**
> On Apple this is a property of the SKPayment object.  On Android it should be passed thru in the fifth argument to launchPurchaseFlow - this is in keeping with the Google security recommendation. (see ‘Security Recommendation’ at http://developer.android.com/training/in-app-billing/purchase-iab-products.html )
> 
> The actual value, in keeping with Apple recommendations, will be a one-way hash of the user’s application login name.  When we are notified that a purchase has completed, that value needs to come back with the purchase information.
> 
> Also, the user could change application accounts without leaving the app - so it could be that  without re-initializing the store, a purchase would be made related to a different application user account.
> 
> Reason:
> 
> 1) On Apple this field is used by Apple to detect fraud.
> 2) On both Apple and Google, the value is used to ensure the purchase is credited to the same user who made the purchase.  Note this is because the user’s Apple/Google store account is generally bound to the device and the application user account is bound to the application and the user may sign in as different users.

Beware, native implementation could have side effects:

> Internally, the plugin has to manage the state of each product (like say the "owned" status, pending transactions, etc). With your use case in mind, it should in fact manage a different pool of products for each applicationUsername.
> 
> A call to store.setApplicationUsername("HHH") should trigger an update of all loaded products to reflect their state in the context of this user.

However, if we restrict the usage to consumable products.

> When you get into all the use cases with multiple users it becomes very difficult. For example, user-A buys consumable-1 and somehow signs out before the purchases 'finishes'.  Then user-B signs in and tries to buy the same consumable-1.  They can't until user-A signs in and lets the purchase finalize.
> 
> However, if we don't try to isolate purchases per user, etc., then we can just process that approved purchase, credit the appropriate user (because the hash value will come back with the payment/receipt) and then user-B will be able to buy consumable-1.
> 
> Of course, there is a whole other problem with non-consumable products and are intended for one-time purchase - like a capability.  In our product, a user might buy a VIP badge.  If it is seen by the store as a one-time purchasable item, then once any one user buys it on a give device, rather under a specific Store account, then no other application user accounts on the same device/store account can buy that product.

**Comment by xdgimf** [comment]
+1

**Comment by giftstart** [comment]
Hi,

I am building a subscription based app and need to differentiate between application users. I am using your plugin and I see you have made some commits for setApplicationUsername method here https://github.com/j3k0/cordova-plugin-purchase/pull/376/commits but the function is unknown when I try to use it. 

Basically if application user A pays for subscription and then logs out and sign in with application user B, I don't want B to have the subscription. Currently it seems since IAP works by apple id, any registration on that same device will get the benefits.

Could you please help me out and point me to the right direction how to achieve this? Thanks.

**Comment by j3k0** [comment]
It's in master now
