### ISSUE TITLE
Please tell me about the significance of the existence of the product.finish method

### ISSUE THREAD

**Issue by nrikiji** [j3k0/cordova-plugin-purchase#702]
I think whether it will be a basic question, but thank you.
I am considering auto-renewable subscription on iOS.

```
store.when("product_id").approved(function(product) {
    product.finish();
});
```
Please tell me about this process to be done at the time of purchase completion.

Q1. Is there any significance of doing this processing?
I feel that it will not change even if I try it as long as I do it in a sandbox environment. . .

Q2. In the example, we are doing this processing with approved, but here I feel I will be called even if it's expired. Is this in the intended shape?

**Comment by j3k0** [comment]
If you don't call "finish()", a transaction will stay in the queue forever. At a high level, "approved()" only means you got a "GO" from the bank, you can deliver the product (unlock feature, whatever) the call "finish()" to tell the platform the transaction can be closed, the money sent to you.

"approved()" is also triggered at every launch by the plugin to give you an opportunity to do receipt validation.

I think all of this is already explained in the documentation, was it unclear?
