### ISSUE TITLE
[iOS] Apple support - The in-app purchase functionality is not present in my binary

### ISSUE THREAD

**Issue by ChrisProlls** [j3k0/cordova-plugin-purchase#705]
Hi all !
After sending my binary to the Apple Store throught iTunes Connect, they respond that the in-app purchaes is not present in by binary. However I installed the plugin correctly. Is there anything else I need to do (with XCode or something else) to integrate correctly the in-app into my application ?

### System info
```
Cordova 8.0.0
Plugin Version: 7.1.3
```

**Comment by j3k0** [comment]
Hi Chris, did you learn anything?

**Comment by xavier-villelegier** [comment]
I had the same issue and had to enable the "In-app purchase" capability.

![image](https://user-images.githubusercontent.com/17592779/43892866-80d5a650-9bcd-11e8-917c-78a2f776f34e.png)

@j3k0 Shouldn't it be enabled by the plugin ? 🤔

**Comment by j3k0** [comment]
> [...] had to enable the "In-app purchase" capability.
> @j3k0 Shouldn't it be enabled by the plugin ? 🤔

It should be. What version of cordova and cordova-ios are you using?
Maybe there was an error when you installed the plugin?

On Thu, Aug 09, 2018 at 10:25:09AM +0000, Xavier Villelégier wrote:
>
> ![image](
https://user-images.githubusercontent.com/17592779/43892866-80d5a650-9bcd-11e8-917c-78a2f776f34e.png
)

**Comment by xavier-villelegier** [comment]
@j3k0 I'm using:
```
cordova-ios@4.5.4
cordova --version: 8.0.0
```

All good when installing, no errors here
![image](https://user-images.githubusercontent.com/17592779/43953941-f1c188ca-9c9a-11e8-8889-51ebd68b550a.png)

I checked with a fresh new project and I have the same issue

```
cordova create hello com.example.hello HelloWorld
cd hello
cordova plugin add cc.fovea.cordova.purchase
cordova platform add ios
```

**Comment by xavier-villelegier** [comment]
@j3k0 Maybe you want me to open a new issue about that ?

I'm trying to build an auto deployment process, for now I have to modify the pbxproj with a custom script to enable the InAppPurchase capability.

**Comment by j3k0** [comment]
@xavier-villelegier This issue can stay here. In case it's necessary, we can include your custom script as a post-install hook in the plugin itself. Would you like trying this?

**Comment by j3k0** [comment]
@xavier-villelegier Can you copy-paste the pbxproj-related custom script around here so we integrate it in the plugin? If it's not production-ready, it can be a starting point.

**Comment by j3k0** [comment]
After some googling, none of the script I found only are suitable for integrating. They rely on some external tools (example, `xmllint`) that we can't expect everyone will have on their system. Also it requires to set the `Team` setting in XCode beforehand, so it's not solving much. Plus I'm afraid it might be hard to guarantee it doesn't conflict with other plugins meddling into the `pbxproj` file.

I guess we'll have to update the documentation to mention that user has to enable the capability manually.
