### ISSUE TITLE
ERROR 6777003: Trying to purchase a unknown product.

### ISSUE THREAD

**Issue by brunosoune** [j3k0/cordova-plugin-purchase#706]
I have the error "ERROR 6777003: Trying to purchase a unknown product" to performing store.order(productId) on Iphone.

The products are registreds successfuly...

The same code work fine in android.

**Comment by Dexus** [comment]
you have register the items and upload the package to itunes? changed the version that is registered in Itunes connect?

Maybe you can provide some more informations, so we can try to create a smilar "item" and setup setting.

We can't find problems out of the blue for the problems: "ERROR 6777003: Trying to purchase a unknown product" because 99,9% the problem is level 8 - developer/sales team that not create/initalize the products or plugin correctly.

**Comment by Dexus** [comment]
Okay, sounds as if your internet connection is very slow, because the app loads all elements after initialization and caches this information - normally. How was the store integrated? Is there a later initialization?

**Comment by ghonche-yqr** [comment]
Hey @brunosoune 
Did you find any solution for this?

**Comment by brunosoune** [comment]
Sorry @ghonche-yqr this my project was descontinued and I don't remember what was the solution and if I found it.

**Comment by ghonche-yqr** [comment]
> Sorry @ghonche-yqr this my project was descontinued and I don't remember what was the solution and if I found it.

Thanks @brunosoune . My problem is solved!

**Comment by CharnjeetIotasol** [comment]
@ghonche-yqr  Can you please help me to solve this issue?

**Comment by ghonche-yqr** [comment]
> @ghonche-yqr Can you please help me to solve this issue?

- Make sure you added your Billing Info to your google play console correctly. It usually takes up to 24 hours to verify your account.
- Try removing in app products and creating a new one.
- Make sure you added your billing_key in your project.
- When testing, Make sure you are logged in with a valid google account on your phone. ( an account which you had purchases with before, can be a reliable test case)
- Register products with **correct ID** and call store.refresh() in your code. then try getting the products (store.products). the returned values should not be null.
- I hope it works!
