### ISSUE TITLE
[Android] Distinguishing between product loading and user unable to purchase

### ISSUE THREAD

**Issue by nonsenseless** [j3k0/cordova-plugin-purchase#707]
# !!! PLEASE USE IN SUBJECT [IOS] OR [ANDROID] AS PREFIX FOR YOUR ISSUE !!!

### system info
OS: Android (all)
Compiling System/Version: MacOS High Sierra
Plugin Version: 7.1.3

### Desired behavior
When a user cancels a subscription, the plugin reports that the product is not Owned and canPurchase is false. I want to have a useful message for this situation, but I can't figure out a good heuristic for displaying it that doesn't get triggered when the product is in the process of loading. For the moment, I'm setting my own flag tied to the loaded event and branching on that basis, but is there a better way to do this?

**Comment by Dexus** [comment]
Currently is there no better way. Because of the generic build and handling of the itunes and playstore api.

But when you are abel to make a PR that would help you to do like you would like to do, we can look a bit deeper how we can make a merge of it.

Regards, Josef
