### ISSUE TITLE
[Android] Signature Verification Failed (Purchase/Restore)

### ISSUE THREAD

**Issue by EWBears** [j3k0/cordova-plugin-purchase#708]
Firstly, many thanks for providing this plugin! It's been very easy to use and greatly appreciated.

### system info

```
cc.fovea.cordova.purchase: 7.1.3

@ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.3.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4 Build version 9F1027a 
```

### Expected behavior
I have 2 apps live on App Store and Google Play, each free to try with an IAP to unlock premium content.  The IAP using this plugin works fine on iOS for both apps and GPlay for 1 of the 2 apps, and after successfully purchasing the IAP I store a value in the database that is checked before to certain pages.

One of my GPlay apps fails to unlock content after a user purchases the IAP product and restores fail with an Signature Verification message.

### Observed behavior
Logcat for working app while restoring purchase on Android phone
```
18:43:15.344  D CordovaPurchase: Setup finished.
18:43:15.344  D CordovaPurchase: Setup successful. Querying inventory w/ SKUs.
18:43:15.344  D IabHelper: Starting async operation: refresh inventory
18:43:15.347  D IabHelper: Querying owned items, item type: inapp
18:43:15.347  D IabHelper: Package name: redacted.master
18:43:15.348  D IabHelper: Calling getPurchases with continuation token: null
18:43:15.355  I Finsky  : [742] com.google.android.finsky.billing.iab.aa.b(155): redacted.master: Account determined from installer data - [e65IiywkzYt0XtSQRT8bUR4QMVU]
18:43:15.362  D IabHelper: Owned items response: 0
18:43:15.372  D IabHelper: Sku is owned: ptfullcontent
```

Logcat output for signature verification failure while restoring purchase on Android phone
```
19:23:31.817 D CordovaPurchase: Setup finished.
19:23:31.817 D CordovaPurchase: Setup successful. Querying inventory w/ SKUs.
19:23:31.817 D IabHelper: Starting async operation: refresh inventory
19:23:31.822 D IabHelper: Querying owned items, item type: inapp
19:23:31.823 D IabHelper: Package name: redacted.reading
19:23:31.823 D IabHelper: Calling getPurchases with continuation token: null
19:23:31.827 I Finsky  : [853] com.google.android.finsky.billing.iab.aa.b(155): redacted.reading: Account determined from installer data - [e65IiywkzYt0XtSQRT8bUR4QMVU]
19:23:31.832 D IabHelper: Owned items response: 0
19:23:31.851 D OpenSSLLib: OpensslErr:Module:4(105:); file:external/boringssl/src/crypto/rsa/padding.c ;Line:114;Function:RSA_padding_check_PKCS1_type_1
19:23:31.851 D OpenSSLLib: OpensslErr:Module:4(131:); file:external/boringssl/src/crypto/rsa/rsa_impl.c ;Line:507;Function:rsa_default_verify_raw
19:23:31.852 E IABUtil/Security: Signature verification failed.
19:23:31.852 W IabHelper: In-app billing warning: Purchase signature verification **FAILED**. Not adding item.
19:23:31.852 D IabHelper:    Purchase data: {"packageName":"redacted.reading","productId":"ptfullreading","purchaseTime":1518626997730,"purchaseState":0,"purchaseToken":"ljhcamlbilmhpjcnkdplbojk.AO-J1Oys0A53DIFWl9BHMXRLNNumXQIsYRRTv7VwskNSjvAtHbg6LkHoh41A5OKXR3gEE4emnLYF2emmeOmCxIzNzwuK6YajmxpXQMicnNZHo2XtTPfTe7ysPyHXa3KHfQODnLOHCWyv"}
19:23:31.852 D IabHelper:    Signature: HSBRC+hs/IX82YyQvRytTcEMhSWbeJpwBE5kGshTKACZDsmaVMT2Sxsi9Ek+mJ4OSoeO8vnB4kOlloRJZjCkAb4QNHf5LMIVRiV7xR0fyWMIGAS56w3IjOaV8OXio936NtavuBanTd0ZjF+H4v7G56rLHvuFv4zsjkfAHV0axA5k0cm/roduh5X3CQ2FmOJ1WdaZmHudDjdbqmEwtxP+3qniPQ0y+TsHUltfWF92JBOG5/A2ucO+XC7+rY8dZQmwhN949yODlwo4s60UP4Nfto9O/y49Ge4Wci2sCWOwiEyBk76srFur9ZYeqOyYaOKSK7ooeFSmZKA/SCuyd2uf6g==
19:23:31.852 IabHelper: Continuation token: null
```

### Other
It looks like the second app recognizes that the product is purchased but something goes wrong verifying the signature, and I've tried dozens of ways to try to fix the bug but nothing works.  I've deleted node_modules directory and re-installed, I've duplicated the node_modules from the working app and put it into the non-working app, I've started new projects from scratch and re-added platform and plugins, but still get this error for some reason.

Obviously I have my BILLING_KEY set in the config.xml and the package.json and they're both the same because both apps are published under the same developer account.

Any advice on how I can fix this or pointing me in the correct direction for further debugging would be greatly appreciated!

**Comment by Dexus** [comment]
The BILLING_KEY is per APP not per Account! So it can't be the same for both apps! Please recheck!

**Comment by EWBears** [comment]
Wow thank you so much for clarifying this!  I don't know why I had this false assumption that it was per-account but I wasted lots of hours trying to figure out the solution.

Seriously - thank you!
