### ISSUE TITLE
Thank you - this is not a bug

### ISSUE THREAD

**Issue by lincolnthree** [j3k0/cordova-plugin-purchase#709]
I just wanted to take a moment to thank you for creating this plugin. I thought it  was a little rough around the edges at first, and the learning curve was high -- In App Purchase is a pain in general from what I gather....

But... the event-model is fantastically suited for this use-case. With a few abstractions, and just a little code... it works fantastically. Thank you for putting this together, and maintaining it.

**Comment by Dexus** [comment]
Thanks I think @j3k0 and all other contributors are happy about this feedback!

**Comment by j3k0** [comment]
Thanks @lincolnthree, your words of appreciation are appreciated. The plugin wouldn't be as awesome without @Dexus' continuous effort in providing support to those in pain ;-)
