### ISSUE TITLE
Android - Calling store.get(productId) after product purchase cancel returns empty data

### ISSUE THREAD

**Issue by yosigolan** [j3k0/cordova-plugin-purchase#715]
### system info
```
Android - any version
Cordova 6.4 // Phone Gap 3.19.2 etc.
Device: Android emulator and Android 7.1
Plugin Version: 7.1.3
```

### Expected behavior
store.get(productId) should return the product details at any time
### Observed behavior
when calling store.get(productId) before the purchase operation it works fine and returns the product data. if i call purchase and the user cancel the purchase, store.get(productId) returns empty data for the product.
however calling store.products returns all data every time. (this is a workaround)

### Steps to reproduce
register product
call store.get(productId) - see the product details
call store.get(productId) again - see the product details again
call store.order - when google screen loads cancel it
call store.get(productId) - product details will be empty
call store.products - see the product details

**Comment by yosigolan** [comment]
any news?

**Comment by ryanhalley** [comment]
I have a similar issue that might be related, so I'm leaving it here in case same root cause:
register product
refresh()
check store.products - see product details
call store.get(productId) - see the product details
unload page
reload page
register product
refresh()
check store.products - see product details
call store.get(productId) - product details will be empty

**Comment by j3k0** [comment]
I reviewed the code. `store.get()` is pretty stupid. `store.products` array doesn't seem to be touched by `store.order` in any ways. Only `store.register()` does -- according to `grep`...

I don't have an Android device with me at the moment to confirm, but is it possible you're doing something weird with either the product itself or the product array in your code?
