### ISSUE TITLE
Feature Request: Make Currency Symbol Available

### ISSUE THREAD

**Issue by budlight** [j3k0/cordova-plugin-purchase#717]
It would be pretty useful to have a currency symbol exposed in the product attributes for formatting price displays.

**Comment by Dexus** [comment]
We provide all the information needed for this, but we will not include I10n or I18n libraries as we will have more to search and maintain.
However, I can speak more honestly for myself here than for @j3k0.

**Comment by j3k0** [comment]
Android already provides the formatted price and iOS a localized price, 
Using those should be enough. If I'm correct, those are exposed by the 
plugin (check the doc, as I forgot the exact field names).

**Comment by Dexus** [comment]
@j3k0 no its not see https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/product.js#L55-L62

**Comment by j3k0** [comment]
I meant the plugin already provides the formatted price (which includes the symbol).

Android has `priceMicros` and `currency`: which allows more custom styling, but it requires some much extra care: many languages don't use the Arabic Numerals, some have the symbol before, some after, some even use different symbols for different amounts, etc... So I think doing it right is so complicated that the vast majority of people are better using the already formatted price.

For others, #720 might be of help once merged in.
