### ISSUE TITLE
is supported rest api?

### ISSUE THREAD

**Issue by gudtkd928** [j3k0/cordova-plugin-purchase#719]
I am preparing service that supports android, ios, and web.
My service is available through subscription.
Using your cordova-plugin-purchase, implemented the purchase and verification on android.
However, the web client needs to proceed with the receipt verification too.
I think it would be much more useful if you supported the rest api. 
Do you have any plan?

**Comment by Dexus** [comment]
we support already a api callback to verify receipts. Read the docs.

**Comment by gudtkd928** [comment]
sorry. i can't find it.
i need rest api that use on web client(pc).
the user purchase subscription and then verify subscription on pc  at next month
