### ISSUE TITLE
Incorrect typings for Typescript

### ISSUE THREAD

**Issue by mnasyrov** [j3k0/cordova-plugin-purchase#721]
Some declarations are missed in `src/js/index.d.ts`, for example:
* `non renewing subscription` in StoreProductType.
* some callbacks in `IWhen` interface (e.g. `finished`).
* `ERR_PAYMENT_EXPIRED` in `IStore` interface.

The typings should be reviewed for missed parts.
Also `package.json` should have ["types"](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) filed which points to the file.

Plugin Version: 7.1.3

**Comment by mnasyrov** [comment]
Maybe it is worth to rename `store` namespace as well. I have collisions with angular's internal `store` file using auto-import in WebStorm.

**Comment by j3k0** [comment]
> worth to rename store namespace

Problem is breaking backward compatibility. Any solution for that?

As for fixing the typescript definitions, help needed.

**Comment by j3k0** [comment]
No `typescript` guru around?
