### ISSUE TITLE
How to restore a purchase? I didn't find api can do this, please help.

### ISSUE THREAD

**Issue by zdd** [j3k0/cordova-plugin-purchase#722]
I am using this plugin in an ios app, but i didn't find a way to restore a purchase, thanks.

**Comment by j3k0** [comment]
You can use `CTRL-F` when you need to find things in the documentation, worked well for me.

https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#restore-purchases-example-usage
