### ISSUE TITLE
ANDROID - Not executing order.finish();

### ISSUE THREAD

**Issue by blackicicle** [j3k0/cordova-plugin-purchase#723]
Compiled using phonegap for android

In example:
```
Phonegap cli-6.5.0 
Device: Android 7 & 8 (two different phones)
Plugin Version: 7.1.3
My code below. 
```

```
//INITIALIZE STORE
	function initializeStore(){
		store.register({
			id:    "com.bcgmobile.globalempire.productionboost",
			alias: "productionboost",
			type:  store.CONSUMABLE
		});
		store.register({
			id:    "com.bcgmobile.globalempire.networthboost",
			alias: "networthboost",
			type:  store.CONSUMABLE
		});
		store.register({
			id:    "com.bcgmobile.globalempire.inventoryboost",
			alias: "inventoryboost",
			type:  store.CONSUMABLE
		});
		store.ready(function() {
			alert("Step 1 reached!");
		});
		store.refresh();
	}

//WHEN BUY IS CLICKED
	function doPurchaseInventory(){
		alert("step 2 reached!");
		store.order("com.bcgmobile.globalempire.inventoryboost");
		alert("step 2 finished!");
	}

//WHEN PURCHASED IS APPROVED
	store.when("com.bcgmobile.globalempire.inventoryboost").approved(function (order) {
        	order.finish();
		alert("step 3 reached!");
		doStorePurchaseInventory();
		alert("step 3 finished!");
	});

//WHEN ERROR
	store.error(function(e){
		alert("ERROR " + e.code + ": " + e.message);
	});
```
Notes:
So far when the app loads it alerts that step one is reached. meaning that the store is loaded.
When i click the buy button, it alerts that step two is reached and step 2 is finished. Then it loads the play store purchase interface for credit card input. (This is where it goes bad)
After purchase, it says items purchased. but nothing happens after that! it does call an error. from store.error. it doesn't say step 3 reached or step three finished.
also when I tap the buy button after that nothing happens. it doesn't show that step two had been reached or finished. Anyone know what that might be so. This plugin has worked flawlessly in other apps don't know what the problem is on this one.

**Comment by j3k0** [comment]
Also, calling `alert()` in the callback might not always work, because those javascript methods are called from the native environment, for some reasons it sometime refuses to show javascript `alert`. `console.log` + `adb logcat` is fine.
