### ISSUE TITLE
[ANDROID] store.refresh gives error and closes the app

### ISSUE THREAD

**Issue by fgubert** [j3k0/cordova-plugin-purchase#724]
### system info
```
Windows 10
Phonegap 6.5.0
Device: Android 7.1.1
Plugin Version: 6.0.0
```

### Expected behavior
I've used the demo js code to register my only 1 consumable and i was able to buy it. When i bought, i have this event:
store.when("alias").approved(function (order) {
// some code to show the consumable
order.finish();
});

And the app was immediately closed after the purchase.
Debugging it, i've discovered that the app only closes when i run store.refresh(), so i put a button to run it manually, and the error persists.

The only error that i got is "application has stopped" and "application keeps stopping".
Enabling the system report, i got the full error:
[fullerror.txt](https://github.com/j3k0/cordova-plugin-purchase/files/2398466/fullerror.txt)

But no clue how to resolve this.

Thanks.

**Comment by j3k0** [comment]
Seems like it complains because your android `BILLING_KEY` is too long.

Make sure you pasted it correctly. It should look like something like this:

```
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJQh6jlNr6SlF3p+I2zGBZdDbCGCTUj8ubZLSks9zYp3BI3lnvj6/MRBAUZQGmLCmrw6dQl/qh8IX3k4mtVPtXZUSx9DTAge0hdBWkcOCuYGcWdvM6PKNigdT1BC3SFjeVgWFZMSpPfmaoZ1a9eA2bONeqDKeCbhLnmgyOUlRSolfw/Tgk+SFpSv26hR3EbHSC4W7Q5NtK5fq/7/MLoYpXiKrz9X4AOa654aoZ3JSmy8XFKj9nYZKElM6tsHkXV9lecUe7yY+ieEdaliZryh50ZTUdT9GY0lDlYn89rbmC5dWJaORzQ97pu8huFQu6xyp/+LEYvieXkCSiFIYF4uIwIDAQAB
```

**Comment by j3k0** [comment]
Welcome. Good luck!
