### ISSUE TITLE
[IOS] crash at order()

### ISSUE THREAD

**Issue by DougJordan9** [j3k0/cordova-plugin-purchase#726]
Hi,

I am using ionic v4 and testing it on iphone. I do not have a mac so I am building it on phonegap and deploying to iphone for testing.

However, the app crashes at the order() call. I can see the ready method is called after the store is registered. However, the app crashes without giving any error.

Could you please provide my some pointers as to why this might be happening?

This might sound like an ionic question but the crash with SIGABRT makes it difficult to debug instead of a graceful error message.

__________________________________________________
let productID: string = "com.XXX.XXXXX";

    try {                        
        this.iapStore.register({
            id: productID,
            alias: "X",
            type: this.iapStore.NON_RENEWING_SUBSCRIPTION
        });
        
        this.iapStore.when(productID).initiated((p) => {                
            ToastMessage.display("INITIATED");
        });
        
        this.iapStore.when(productID).cancelled((p) => {                
            ToastMessage.display("CANCELLED");
        });
       
        this.iapStore.when(productID).approved((p) => {               
            ToastMessage.display("APPROVED");
        });

        this.iapStore.ready((e) => {
            ToastMessage.display("READY");
            this.iapStore.order(productID);    
        });           
        
        this.iapStore.error((e) => {                
            ToastMessage.display("ERRORINAPP:" + e.code + ": " + e.message);
        });

        this.iapStore.refresh();    
__________________________________________________

Thanks,

Doug

**Comment by DougJordan9** [comment]
Hi Jean-Christophe,

First, huge thanks for your reply; I am really grateful. 

I develop on a windows machine and build it on phonegap as I do not have a Mac unfortunately, which makes the testing quite difficult. Here is what I observe:

When I call the store.get() function inside store.ready(), the returned object is pretty much filled with null. I believe this makes sense as I am logged off from App Store at the beginning. App Store does not let me log in with a sandbox test account directly at the App Store. Is this the normal behavior?

When I call the order(), I see a pop up to enter App Store user ID & password but then the application goes white and crashes. 

How do we solve this conundrum (or a mistake I am doing): I am only presented with a login screen at the store.order() call but at that point the get function had returned an empty object already?

I would be grateful for your pointers Jean-Christophe. Many thanks in advance.

Doug

**Comment by j3k0** [comment]
I think you should do:

```js
    this.iapStore.when(productID).loaded((p) => {               
        this.iapStore.order(productID);    
    });
```

If products are never loaded, there's a checklist here: https://github.com/j3k0/cordova-plugin-purchase/wiki/F.A.Q.

**Comment by Dexus** [comment]
A other point maybe that on phonegap the purchase option is not enabled?

That what you need to do manually currently with the project?

So it will impossible to support phonegap currently!

Von meinem iPhone gesendet

**Comment by j3k0** [comment]
@Dexus Right, except if PhoneGap let's you enable the In-App Purchase capability from their interface. I have no experience with that, can't help much.

**Comment by DougJordan9** [comment]
Thank you very much for the checklist Jean-Christophe. Also, many thanks for your reply Dexus. I am new to ionic development and had to check various articles but they all assume you have a tax agreement & bank account set up already at itunesconnect, which I had not.

I set that up and it works. Sorry to bother you with this question but I hope this will be beneficial for others as I have seen similar questions on other platforms.

**Comment by Dexus** [comment]
Good to know. Thanks for your findings :+1:
