### ISSUE TITLE
[ANDROID] Not able to purchase consumable for the second time

### ISSUE THREAD

**Issue by fgubert** [j3k0/cordova-plugin-purchase#727]
### system info
```
Windows 10
Phonegap 6.5.0
Device: Android 7.1.1
Plugin Version: 6.0.0
```

### Expected behavior
I click on the buy button, insert my credentials, the purchase is approved and i got a receipt in my email.

### Observed behavior
When i try to purchase the same consumable for the second time, i got Error 7
![screenshot_20180925-090652](https://user-images.githubusercontent.com/3128358/46017454-e80f6b80-c0ad-11e8-918b-e333b4ef8cd9.png)

So, after trying to modify the code in many ways, i tried to create a new consumable with a different id, and i was able to buy it, but when i tried to buy the second time, the error repeats.

The code:
```JS
store.register({
            id:    'stopinvest.commented_question1', // id without package name!
            alias: 'stopinvest.commented_question1',
            type:   store.CONSUMABLE
        });

store.when("stopinvest.commented_question1").approved(function (order) {
            order.finish();
            methodToSavePurchase();
});
```

`methodToSavePurchase()` makes an ajax call to save purchase to our server.

So, im a bit lost on this, a consumable cannot be purchased two times? How can i do this? 
Any help would be appreciated.

**Comment by Dexus** [comment]
Hi @fgubert,

You should be call `order.finish()` in you Ajax call, when it is without error. Check also double spendings... in your backend.

If this not helps you, please provide some logs! Without we need to talk about the blue sky...

**Comment by fgubert** [comment]
Sure, is just a test code. But why it should matter in this particular error?
If i finished the purchase, i should be able to buy again, or not?

What finish actually does? And why im not able to buy the same id twice?

Thanks alot.

**Comment by Dexus** [comment]
To help you, we need more logs from Android Studio. Its not easy to help you without.

`order.finish()` does what you except, normally...

**Comment by fgubert** [comment]
Im not using Android Studio.
I got logs from android itself, and i was able to found an error in my code. Everything is running ok now, thanks and sorry for the inconvenience.
