### ISSUE TITLE
[ANDROID] billing_key_param.xml requested for changes not found

### ISSUE THREAD

**Issue by francoisduchemin** [j3k0/cordova-plugin-purchase#729]
```
Cordova 8.1.1
Plugin Version: 7.2.0
```

I'm getting the following warning when I try to install the plugin:
```
config file res/values/billing_key_param.xml requested for changes not found at C:\<pathToProject>\platforms\android\res\values\billing_key_param.xml, ignoring
```

The plugin gets installed but I wonder if it could cause problems down the road. Seems related to the [issue 673](https://github.com/j3k0/cordova-plugin-purchase/issues/673).

**Comment by nprather** [comment]
Same warning here: 
![image](https://user-images.githubusercontent.com/3101108/46832288-a5b78100-cd73-11e8-9c04-1eba78ecb02b.png)

**Comment by j3k0** [comment]
I think a quick fix might be to create the directory (`platforms/android/res/values`)

**Comment by nprather** [comment]
I've temporarily gone back to this version and everything seems fine for now: `cordova plugin add cc.fovea.cordova.purchase**@7.1.3** `

**Comment by francoisduchemin** [comment]
@j3k0 I think you can close this issue. It's working fine with version 7.2.1, thanks again for the fix!
