### ISSUE TITLE
[ANDROID] Can't get products from Google Play

### ISSUE THREAD

**Issue by mliashevich** [j3k0/cordova-plugin-purchase#736]
Hello, I'm new in "cordova" and "android" worlds. I use the following setup:

config.xml 
<img width="945" alt="screen shot 2018-10-12 at 9 14 15 pm" src="https://user-images.githubusercontent.com/3639711/46886595-058d5500-ce64-11e8-8810-36feb6453926.png">

product in google store
<img width="934" alt="screen shot 2018-10-12 at 9 21 26 pm" src="https://user-images.githubusercontent.com/3639711/46886882-cf9ca080-ce64-11e8-8abc-81c6ff37ebc4.png">

For building apk - https://build.phonegap.com - is used (certificate is generated locally for the tool)

js code for check (But I always get "NO"):
`

    document.addEventListener('deviceready', function initializeStore() {
      store.refresh();
      var product = store.get("experiments_pack_1");
      if (!product) {
          alert("NO");
      } else if (product.state === store.REGISTERED) {
          alert("REGISTERED");
      } else if (product.state === store.INVALID) {
          alert("INVALID");
      } else {
          // Good! Product loaded and valid.
          alert(product.description);
    }});
`

The app is in alpha release. I used - cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="MIIB...AQAB" - for installing.  

Also I've tried [your example](https://github.com/j3k0/cordova-non-renewing-subscription-demo) as a separate app (with separate billing key) but also get exception - that it is not possible to connect to google play.  Can you please assist?

**Comment by j3k0** [comment]
`store.refresh();` isn't synchronous.

So when you do `var product = store.get("experiments_pack_1");`, the `experiments_pack_1` hasn't been loaded yet. You need to wait for the `store.loaded()` event.

You need to register your products before doing refresh too. Please read the documentation again, you'll find a short demo code to get started.

**Comment by mliashevich** [comment]
Thank you for the fast response. I really appreciate. I've checked a lot of documentation before posted the question here. As you can see I already have a product in google. Will try to wait async response before getting the product.
