### ISSUE TITLE
Version 7.2.1 not available on npm

### ISSUE THREAD

**Issue by francoisduchemin** [j3k0/cordova-plugin-purchase#740]
Sorry to open another issue! I'd be very interested in trying the latest version of `cc.fovea.cordova.purchase` ([7.2.1](https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v7.2.1)). However, this version is not available yet on [npm](https://www.npmjs.com/package/cc.fovea.cordova.purchase) (npm still shows 7.2.0, and `npm info cc.fovea.cordova.purchase version` also returns 7.2.0)
Are you going to update the version on npm?

What I also don't understand is that when I click the [Releases](https://github.com/j3k0/cordova-plugin-purchase/releases) button on GitHub, it shows latest release=6.1.1: why are the newer releases only tags?

**Comment by j3k0** [comment]
Published on npm (I just forgot)... To `npm publish` ;-)

Indeed I need to mark the tags are "releases". Will do that. Thanks for the notice.

**Comment by nprather** [comment]
I went this route, but should have asked for help.  Thanks for getting this in npm:  
`cordova plugin add https://github.com/j3k0/cordova-plugin-purchase.git#a30e8230a70a1ab8e407a6fac53fbdc60347d376 --force"`
