### ISSUE TITLE
[IOS] trigger a receipt refresh request

### ISSUE THREAD

**Issue by LoserAntbear** [j3k0/cordova-plugin-purchase#741]
Maybe i am doing something wrong, but after test environment setup for IAP I've tried to make a purchase using Sandbox account. All the things are going fine until, after making .purchase() request, the only i receive next transaction object:
`
{
  type: ''ios-appstore",
  id: '###' (some number)
}
`
That's it. No receipt of something like that. iOS documentation says, that, if you'd receive response object with no `receipt` field - you should trigger a receipt refresh request, but i found  no info how to do that using plugin's methods. 
Please, could you help me with that issue?

**Comment by j3k0** [comment]
Hello @LoserAntbear - Did you setup a `store.validator` url or function? This is the way to go to access appStoreReceipts.

**Comment by j3k0** [comment]
Close for inactivity...
