### ISSUE TITLE
Introductory Prices for [IOS] and [ANDROID]

### ISSUE THREAD

**Issue by mehmetkoc182** [j3k0/cordova-plugin-purchase#743]
I've tried a new product with an introductory price on it.
It looks like the intro price doesn't get reflected on the price but the product can be purchased with the full price. 
Does the plugin support introductory prices?
Are there any special settings for them?

### system info
```
Cordova 8.0 
Device: iPhone iOS 12.3.2 // Android 9.1
Plugin Version: 7.1.0
```

### Expected behavior
Intro Price

### Observed behavior
Regular price

**Comment by j3k0** [comment]
It is not supported. I've never looked into this, so it might or might not be a lot of extra work.

The plugin has no responsibility as for how much is charged, so I would assume it's just a "presentation" problem? i.e. it show the full price but users are actually charged the introductory price? Or is it not?

**Comment by j3k0** [comment]
Notes for eventual implementation:

 * https://developer.apple.com/documentation/storekit/skproduct/2936878-introductoryprice?language=objc
 * https://developer.apple.com/documentation/storekit/in-app_purchase/offering_introductory_pricing_in_your_app?language=objc

The section on "how to determine eligibility":

>To determine if a user is eligible for an introductory price, check the receipt:
> 1.	Validate the receipt as described in Validating Receipts With the App Store.
> 2.	In the receipt, check the values of the Subscription Trial Period and the Subscription Introductory Price Period for all in-app purchase transactions. If either of these fields are true for a given subscription, the user is not eligible for an introductory price on that subscription product or any other products within the same subscription group.

**Comment by mehmetkoc182** [comment]
Thanks a lot for the clarification. 
I will look into creating a PR for this unless that's something you're already working on.

**Comment by j3k0** [comment]
@mehmetkoc182 Thanks. I've been working on that. The code is in place, still need to test it properly.

**Comment by mehmetkoc182** [comment]
Awesome! thank you. 
I'd love to use this feature as soon as it's deployed. 
Any idea when that'd be?

**Comment by lolosett** [comment]
Are you planning on implementing introductory pricing for android, as well? If so, when? Thanks!

**Comment by j3k0** [comment]
I didn't look into Android yet regarding this, but definitely planning to do it. I can't provide a timeframe though.

**Comment by Seanmclem** [comment]
@j3k0 did this ever get implemented?
