### ISSUE TITLE
Trying to purchase an unknown product IOS

### ISSUE THREAD

**Issue by mathantunes** [j3k0/cordova-plugin-purchase#744]
[IOS]

### system info
OSX Sierra 10.12.6
Cordova-ios@4.5.5 // Ionic 3
Device: iPhone iOS 11.2
Plugin Version: 7.2.0

### Expected behavior
Product retrieved from store according to what has been set up
### Observed behavior
Trying to purchase unknown product
### Steps to reproduce
I created the Product on Itunes Connect.
Added the product id to my code.
First step is to register the product with the correct product id
Set up approved, registered, updated, cancelled and error handlers
Refresh store.

call Get with correct product ID
call Order with correct product ID

the XCode Logs are:
Loaded{"id":"productID,"alias":"productID","type":"consumable","state":"requested","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":true,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"valid":true}
2018-10-22 20:05:56.546938-0300 NFContacts[1444:477718] [store.js] DEBUG: store.queries !! 'consumable updated'
2018-10-22 20:05:56.546974-0300 NFContacts[1444:477718] [store.js] DEBUG: store.queries !! 'valid updated'
2018-10-22 20:05:56.547019-0300 NFContacts[1444:477718] [store.js] DEBUG: store.queries !! 'updated'
2018-10-22 20:05:56.550326-0300 NFContacts[1444:477718] [store.js] ERROR: ios -> ERROR 6777003: Trying to purchase a unknown product. - "ProductID"

I have read two issues from this plugin with no solution on this.

Please help

**Comment by Dexus** [comment]
Duplicate; search before you open tickets. Thanks!

Close #744

Von meinem iPhone gesendet

**Comment by mathantunes** [comment]
Let me give you the links and you tell me if it is solved
#706
#239

Open up and tell me if it is solved, thanks

**Comment by Dexus** [comment]
Please be fair, all you wrote is that it not work. But you not described what you already have done so far. So please tell if you have add the app to the AppStore as beta already or you only add your items.

All details you can tell us may help! And without we can help you not!

Von meinem iPhone gesendet

**Comment by j3k0** [comment]
@mathantunes We don't work for you, so if you like us to give you support for free, on our free time, you'd better not talk this way. That's not how you'll get help.

There's a F.A.Q. on the wiki with this checklist.

 * Have you enabled In-App Purchases for your App ID?
 * Do you have a iTunes Paid Application contract in effect?
 * Have you checked Cleared for Sale for your product?
 * Are there any contracts waiting for approval?
 * In-App Purchases have all fields filled (including screenshots)?
 * Did you wait 24 hours?
 * Using a real device (not a simulator)?
 * Are you using the full product ID in register?
 * Are there any error in your product ID?
 * Do you wait cordova's "deviceready" event before loading the purchases?
 * Have you submitted (and optionally rejected) your application binary?
 * Does your project’s .plist Bundle ID match your App ID?
 * Have you generated and installed a new provisioning profile for the new App ID?
 * Have you configured your project to code sign using this new provisioning profile?
 * Are your bank details active on iTunes Connect?
 * Have you tried deleting the app from your device and reinstalling?
 * Is your device jailbroken? If so, you need to revert the jailbreak for IAP to work.

Did you went over it?

**Comment by mathantunes** [comment]
@j3k0 If you plan to keep a support team, do support developers.
If you do not want to support and have answers like "search before you open tickets. Thanks!" then tell people on your front page that you do not have support.
thank god you do not work for me.

any ways I don't often open issues as my team tries very hard before asking for outside help so I am not here to be offended.

The team decided to remove your plugin and pay extra for the time on developing with other resources.

Hope you do not use this as a "Duplicate" for the next person who asks about this error.

Wish you success, thanks

**Comment by j3k0** [comment]
I deleted the "flame" comments. They won't help anyone. I kept the rest of the conversation just in case it pops up again.
