### ISSUE TITLE
[IOS] Consumable for iOS not working

### ISSUE THREAD

**Issue by fgubert** [j3k0/cordova-plugin-purchase#745]
### system info

```
Windows 10
Phonegap 6.5.0
Device: iPhone iOS 12.0.1
Plugin Version: 6.0.0
```

### Expected behavior
Hello, i have implemented the plugin and its working like a charm on android devices. I click to buy, fire store.order("alias"), and everything went fine.

### Observed behavior
In iOS, when i fire store.order("alias") i got a blank screen with no error.
![attachment-7680979367691170156screenshot-1018-123613](https://user-images.githubusercontent.com/3128358/47437658-6c254380-d77f-11e8-95c5-3d87f763bcca.png)

Besides this, i can debug the app remotely and live, and when i run a store.products[0], as you can see below, the canPurchase is false.
![canpurchase false](https://user-images.githubusercontent.com/3128358/47437774-9aa31e80-d77f-11e8-9041-e530f6aa4aff.png)

Some code that i actually use:
`

        app.myLog('inside initstore');
        if (!window.store) {
            app.myLog('Store not available');
            return;
        }
        store.verbosity = store.DEBUG;
        app.myLog('registerProducts');
        store.register({
            id: 'stopinvest.commented_question1', // id without package name!
            alias: 'Questão Comentada - Uma Unidade',
            type: store.CONSUMABLE
        });

        store.error(function(error) {
            app.myLog('STORE ERROR ' + error.code + ': ' + error.message);
        });

        store.when("stopinvest.commented_question1").approved(function(order) {
            order.finish();
            app.myLog('order.finish');
            localStorage['purchase_question_id'] = null;
        });
        store.ready(function() {
            app.myLog('Store Ready');
        });

        app.myLog('refresh');
        store.refresh();
        if (store.restore) {
            app.myLog('store restore');
            store.restore();
        }
`

Any help would be appreciated.

**Comment by j3k0** [comment]
First of, you're call for `store.restore` isn't appropriate. As per Apple's guidelines, it should be called when the user clicks a "restore purchases" button.

Also, I'm not sure the plugin will play nice with it, since the way you do it, product definitions haven't yet been retrieved from the appStore... It will also trigger a popup asking for users' credentials at each start, which is surely not a good idea.

It seems like you're firing `store.order("...")` when the product's `canPurchase` state is set to false.

Are you testing from a real device? StoreKit isn't supported on iOS simulators.

**Comment by fgubert** [comment]
Other thing that i discovered right now:
- When i first open the app, the deviceready isnt fired as you can see in the screenshot in the first post.
- If i click the home button, and reopen the app, the deviceready is fired, and the store infos as well:
InAppPurchase[js]: setup ok
[store.js] INFO: ios -> storekit ready
[store.js] DEBUG: ios -> loading products
InAppPurchase[js]: load ["stopinvest.commented_question1"]
device ready
InAppPurchase[js]: load ok: { valid:[] invalid:["stopinvest.commented_question1"] }

Any ideas why this could happen?

Thanks.

**Comment by fgubert** [comment]
I have resolved this issue. Was a content-security-policy issue.
But now, the store.products[0] object gets filled, but canPurchase is still false.
Any ideas?
![error](https://user-images.githubusercontent.com/3128358/47578021-ada02500-d91e-11e8-9930-ee44e781d77e.png)

**Comment by j3k0** [comment]
`canPurchase` will be `true` once the product details has been loaded from the AppStore. This is done when you call `refresh()`. It's an asynchronous call, so you have to wait for the `loaded()` event.

Make sure to read carefully this repo's [doc/api.md](../blob/master/doc/api.md) document for all the details. It contains all the above information.

What change was required on your `content-security-policy`?

**Comment by fgubert** [comment]
Thanks, understood.
I had to add the "gap: file:" that was removed before (i dont know why).

The app is working well on android, the issue is only on iOS.
The apple team hasnt made the in app product ready, this is the "invalid" state. Im trying to publish it but they are not helping.

When tey publish, ill come back here and tell if everything is working.

Thanks

**Comment by j3k0** [comment]
I'm closing just not to clutter the issues list. Please give us the feedback if you now have consumable working on iOS. Re-open if the issue persists.

**Comment by fgubert** [comment]
Apple just doesnt publish the in app purchase consumable and it is always in invalid state.
They said that a apple representative will call me. Ill post later.
