### ISSUE TITLE
[IOS] window.store is undefined

### ISSUE THREAD

**Issue by yagudaev** [j3k0/cordova-plugin-purchase#748]
### system info

```
Mac OS High Siera 10.13.6
Cordova 8.0.0
Device: iPhone X iOS 12.1 Beta 5
Plugin Version: 7.2.4
```

### Expected behavior
After `deviceready`, window.store should return the store object.

### Observed behavior
window.store returns undefined

### Steps to reproduce
Use the sample project here: https://github.com/Fovea/cordova-plugin-purchase-demo (need a bit of modification with content security policy see: https://blog.dotnetframework.org/2017/01/29/refused-to-load-gapready-phonegap-cordova-csp/

It will show that the store is not found.

My suspicion is that the plugin is not even loaded properly (I don't see it in the xcode workspace). I'm not entirely sure how Cordova plugins are supposed to work to test this theory further.

**Comment by j3k0** [comment]
I've been able to test successfully with the same version of OSX, cordova and plugin and you use. I don't have a device using iOS beta, but I doubt it'd be that.

More data needed. I can't figure anything out blindly.

**Comment by j3k0** [comment]
@yagudaev Did you figure out the issue? Can you provide any logs? Thanks
