### ISSUE TITLE
How to trigger verify / validator for subscription

### ISSUE THREAD

**Issue by matte5031** [j3k0/cordova-plugin-purchase#749]
I have an api that checks if we should validate the subscription.

If the api returns that the subscription needs to be validated I'm trying the below witout success, the validator method is never called.

 var product = store.get("mysybscriptionname");
 product.verify();

However the verify works and gets the receipt to the validator from the approved function if I call store.order("mysybscriptionname").
However I'm trying to just call verify immediately is that not possible?

If not, how do i trigger the verify -> validator method in my scenario?
Do I have to call the  store.order("mysybscriptionname") in order to validate it or?

Any help or input is highly appreciated. Thanks!

**Comment by matte5031** [comment]
This can get closed

**Comment by j3k0** [comment]
For future users reference: check #750 for details.
