### ISSUE TITLE
Android: How to debug?

### ISSUE THREAD

**Issue by patrickhulce** [j3k0/cordova-plugin-purchase#753]
I'm trying to get the plugin working at a bare minimum using the modified example code with a subscription.

From what I've gathered from the docs here and in the play store, the only way to test subscriptions is to actually publish the application in an internal test track through the store. When I do this though, I can't enable cordova debugging for inspection via `chrome://inspect`. 

Problem: When I call `store.order` with my product ID, nothing happens (no uncaught errors, no UI to prompt payment, etc) I have no clue what's going wrong and no debug avenues. 

Has anyone had success debugging in-app purchases like this?

Code snippet is reproduced below.

Thanks for the help!

```js
function initializeInAppPurchases() {
  // Is this really supposed to be the portion of the product ID that's *after* the package name, or the full product ID?
  const MONTHLY_ID = 'subscription.monthly'

  store.validator =
    'https://reeceipt-validator.fovea.cc/v1/validate?appName=com.myapp.packagename&apiKey=<redacted>'

  store.register({
    id: MONTHLY_ID,
    alias: 'monthly subscription',
    type: store.PAID_SUBSCRIPTION,
  })

  // From https://github.com/Fovea/cordova-plugin-purchase-demo/blob/42fa3523023bd7e978da32c5bb64bea7da7a8142/www/js/index.js

  // `onProductInformation` logs things to the screen and is never called from what I can tell
  store.when('product').updated(product => self.onProductInformation(product))

  // None of these are obviously triggered
  store.when(MONTHLY_ID).approved(purchase => purchase.verify())
  store.when(MONTHLY_ID).verified(purchase => purchase.finish())
  store.when(MONTHLY_ID).updated(purchase => {
    if (purchase.owned) {
      self.onSubscribed(purchase)
    } else {
      self.onUnsubscribed(purchase)
    }
  })

  // This doesn't seem to do anything, I don't get any product updates
  store.refresh()
  // This is what's wired to my button onclick, I can confirm the log message goes through
  self.orderProduct = productId => {
    console.log('Purchase requested', productId)
    store.order(productId)
  }
}

**Comment by j3k0** [comment]
Hi Patrick,

After you've uploaded your app on Google Play (and waited for a little while), you can upload any build that uses the same signing key right to your device using `adb` and test it.

I generally use devices logs, something like `adb logcat "chromium:I *:F"`. (Cordova apps' `console.log` use the `chromium` log tag).

In theory, you can also make a debug build and write a small script that re-sign it using your production signing key. I guess it should be instrumented for debugging. I never actually tried that, logs are enough for me in general.

There's a guide here, a little outdated and might not fit perfectly with your setup, but you'll get the idea: 
https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO#test-android-applications

As for your specific problem:

> When I call store.order with my product ID, nothing happens (no uncaught errors, no UI to prompt payment, etc) I have no clue what's going wrong and no debug avenues.

Logs will be helpful to know more about it. My only clue: did you set the correct billing key?

**Comment by patrickhulce** [comment]
Alright manually installing from locally signed apk worked! I'm not sure why there's a discrepancy between release and debug though, troublesome that the environment which is not debuggable is the one where things aren't working... :/

Side note: first major issue was installing the wrong package on CI, if anyone still has publish rights to `cordova-plugin-purchase` maybe they could update the README to point folks to the real maintained one?

Thanks for the help!

**Comment by j3k0** [comment]
> if anyone still has publish rights to cordova-plugin-purchase maybe they could update the README to point folks to the real maintained one.

I contacted the owner of the package on twitter a while ago but got no reply, I didn't find any other way to reach for him. You should mention him in a tweet `#lostanhourbecauseofyou` ;-)

Good luck with the integration!
