### ISSUE TITLE
[IOS] Cannot purchase Consumable in iOS (working on android)

### ISSUE THREAD

**Issue by fgubert** [j3k0/cordova-plugin-purchase#754]
### system info

```
Windows 10
Phonegap 6.5.0
Device: iPhone iOS 12.0.1
Plugin Version: 6.0.0
```

### Expected behavior
Hello, i have implemented the plugin and its working like a charm on android devices. 
I click to buy, fire store.order("alias"), and everything went fine.

### Observed behavior
In iOS, nothing really happens. I tried to follow the instructions, revised all instructions many times and not a single change in the code was able to get asked to pay for a consumable.

Talked to an Apple representative and they said nothing useful for my problem.

Tried to replace the sign key (production) for a development one, created the sandbox test user, same problem.

My last test was to delete every code that i write and try this tutorial:
https://www.joshmorony.com/how-to-create-ios-in-app-purchases-with-phonegap-build/

My code now is exactly the same, just changed the ID for my current ID.

The IAP.load runs without problem, but since the resource isnt published by apple (and they cannot test since nothing happens):
![ss1](https://user-images.githubusercontent.com/3128358/48087298-107aa180-e1e6-11e8-8eb1-91bd552b39b8.png)

When i was using the "store" object. In console i can see that store.products[0] state is invalid.

I really need to make this work for iOS, but i have no clue of what im doind wrong. Im willing to pay for some support on this.

Thanks.

**Comment by fgubert** [comment]
> Did you upload a version of your app to the App Store? Are you testing with TestFlight? Does the version you're testing match the version that is uploaded to the App Store?

Hello.
Did you upload a version of your app to the App Store? 
**Yes. But in the production profile. The development profile i got an error uploading in application loader.**

Are you testing with TestFlight? 
**Yes**

Does the version you're testing match the version that is uploaded to the App Store?
**In test flight, yes.**

**Comment by kiweb** [comment]
On your test device, are you logged in as a user that is in your App's Test Group?

**Comment by fgubert** [comment]
> On your test device, are you logged in as a user that is in your App's Test Group?

Yes. In itunes/testflight with a user that is in test group, and in pay with a sandbox test user.
