### ISSUE TITLE
ios - purchases restoring doesn't work

### ISSUE THREAD

**Issue by oduverne** [j3k0/cordova-plugin-purchase#757]
Hello,
Purchases restoring doesn't work for me, when I call store.refresh the user password is requested but nothing happens after that, there are no event.
Can you help me?
Thx

On Tue, Jun 21, 2016 at 1:37 PM Moritz Brandes notifications@github.com
wrote:

> Hey, apple told me to add a button to my app for users to restore the
> product.
> 
> We found that your app offers In-App Purchase(s) that can be restored but
> does not include a "Restore Purchases" feature to allow users to restore
> the previously purchased In-App Purchase(s)
> 
> Do they mean to add a button which calls the store.refresh method or is it
> something else?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/j3k0/cordova-plugin-purchase/issues/466, or mute the
> thread
> https://github.com/notifications/unsubscribe/AALtiZeuLiA-BJwkEAcWwSzZm57UHvGvks5qN8XcgaJpZM4I6nMu
> .

_Originally posted by @j3k0 in https://github.com/j3k0/cordova-plugin-purchase/issues/466#issuecomment-227469462_

**Comment by j3k0** [comment]
I can help if I have some logs.

You should try to do the restore by launching the app from XCode (to see logs from the native side)

And with the Safari developer tools connected to the app (to see if anything throws an exception in the javascript code).

**Comment by oduverne** [comment]
Hello,
Thank you for your answer.
I use the plugin version 6.1.2 (7.2.1 doesn't work for me on Android (Error 6777001 : Init Failed - String resource ID #0*0)).
My app is compiled with Phonegap build (cli-7.1.0).
I run the app on ios 12.1
I attached the log in debug mode
Seems that it is getting a product "com.gateauxsurmesure.app" when i do the refresh which is incorrect.
Thank you very much for your help.
Regards
[log_ipad.txt](https://github.com/j3k0/cordova-plugin-purchase/files/2573930/log_ipad.txt)

**Comment by j3k0** [comment]
Hi,

You'd rather use the latest plugin version. It's backward compatible and solves a number of issues.

The `(Error 6777001 : Init Failed - String resource ID #0*0)).` is due to the `billing_key.xml` resource file not being installed at the right place. This is believed to have been fixed with the latest update of  plugin, when using the platform `cordova-android@7.1.1` (there's a bug in the most recent `cordova-android@7.1.2`, that the cordova android team is working on fixing).

**Comment by j3k0** [comment]
More on `com.gateauxsurmesure.app`. This "product" is your own app. It is be registered as a product to give access to the app's receipt fields even when there has been no purchases. It contains sometimes useful information, like when the user first downloaded the app, when he did update it, a unique "download identifier", etc.

**Comment by oduverne** [comment]
Hello,
I use phonegap build to build my app in the cloud, I can only choose phonegap-cli version:
[phonegap versions](https://build.phonegap.com/current-support)
I tried with version 7.1.0 (android 6.3.0) and 8.0.0 (android 7.0.0) but for these versions I get the same error with cordova-plugin-purchase 7.2.1
Therefore I'm stucked with the version 6.1.2

I based my code on cordova-non-renewing-subscription.

I looked at the com.gateauxsurmesure.app "product" and noticed that there is a receipt inside. I decoded it using itunes' servlet. Where does this receipt come from? I contains one of my test transaction but it is not the latest one.
Thank you

**Comment by oduverne** [comment]
Here is the code used to register:

Products definition:
var productsId = {
	products: [
		{
			id: '1monthnr',
			product_type: window.store.NON_RENEWING_SUBSCRIPTION,
			product_hidden: false
		},
		{
			id: '1yearnr',
			product_type: window.store.NON_RENEWING_SUBSCRIPTION,
			product_hidden: false
		}
	]
};

Register products:
for (var i = 0; i < productsId['products].length; ++i) {
	window.store.register({
		id: this.products[i].id,
		type: this.products[i].product_type,
		additionalData: {hidden: this.products[i].product_hidden}
	});
}

**Comment by oduverne** [comment]
I tried to finish this "com.gateauxsurmesure.app" product and it worked.
I'm just wondering where does this receipt comes from (there is only one receipt inside). Is it a good idea to use it to check if the user is subscribed?
Otherwise I don't have other events when I call store.refresh().
I use only non renewal subscriptions.
Thank you for your help

**Comment by oduverne** [comment]
I found where does this receipt come from. "com.gateauxsurmesure.app" product appeared when I tried my app in testflight. Previously I was using it only with a sandbox account with an ipa directly installed on my device.

**Comment by j3k0** [comment]
Hi @oduverne,

If you finish the product, it shouldn't create any issues (does it?). Is the "restore purchases" feature working now?

**Comment by oduverne** [comment]
Hi,
Using "com.gateauxsurmesure.app" product seems to be ok to restore products on ios. It works with sandbox. Hope it will be fine when the app will be published.
Thx
