### ISSUE TITLE
Small update will be needed for proposed cordova-android patch release

### ISSUE THREAD

**Issue by brody2consult** [j3k0/cordova-plugin-purchase#759]
Changes proposed in apache/cordova-android#555 were made so that the same `IInAppBillingService.aidl` entry in plugin.xml will work in cordova-android@6 and cordova-android@latest. This is achieved by remapping of target-dir if it does not start with "app". But this means that you will need to remove the second `IInAppBillingService.aidl` entry from plugin.xml and have your cordova-android@7 users upgrade to the upcoming cordova-android patch release.

Right now you can test with the following cordova-android versions:
* `https://github.com/brodybits/cordova-android#7.1.3-patch-updates`
* `cordova-android@nightly` (or `https://github.com/apache/cordova-android#master`)
* cordova-android@6

Right now `https://github.com/j3k0/cordova-plugin-purchase#v7.1.0` (version before you added the extra aidl entry and hook script) will install and build with the proposed patch release as well as cordova-android@6. So it should be possible for you to get rid of the hook script as well.

I hope this does not prove to be too much of a problem for you. If this does prove to be a major problem then I would be happy to look for another solution.

**Comment by brodybits** [comment]
You can now test with `cordova-android@nightly`. I just updated the description.

**Comment by j3k0** [comment]
Thanks @brodybits - I'll revert the `.aidl` related part.

You don't mention it, but there was also this section that required change in our `plugin.xml` file:

```xml
        <source-file src="src/android/billing_key_param.xml" target-dir="res/values/" />
        <config-file target="res/values/billing_key_param.xml" parent="/*">
            <string name="billing_key_param">$BILLING_KEY</string>
        </config-file>
```

To this : 

```xml
        <hook type="before_plugin_install" src="scripts/androidBeforeInstall.js" />
        <config-file target="*/billing_key_param.xml" parent="/*">
            <string name="billing_key_param">$BILLING_KEY</string>
        </config-file>
```

Where `androidBeforeInstall.js` was creating the `billing_key_param.xml` file at the right location.

This should be covered by `cordova-android@7.1.3` as well, right?

**Comment by brodybits** [comment]
Good point. I would probably rewrite that section as follows:
```xml
        <source-file src="src/android/billing_key_param.xml" target-dir="res/values/" />
        <config-file target="*/billing_key_param.xml" parent="/*">
            <string name="billing_key_param">$BILLING_KEY</string>
        </config-file>
```

Old way to install `billing_key_param.xml`, more flexible `config-file` target, no hook script.

And be sure to test on nightly and upcoming patch release of cordova-android.

With nightly and upcoming patch release, the old `source-file` element should install `billing_key_param.xml` into `app/src/main/res/values`. The hook script seems to install the xml into the same place. And on cordova-android@6 it should work just like it did before.

TBH I have not dealt with the `config-file` element so much, looks like you know what you are doing with it.

I hope this makes sense, please don't hesitate to ask in case of any questions or confusion.

**Comment by brodybits** [comment]
Sorry about this, I am having some second thoughts about the aidl change. Removing the second aidl entry from this plugin should be considered a breaking change since it would no longer work on cordova-android@7.1.1. And remapping of aidl on cordova-android should be considered a breaking change there since it causes the existing version of this plugin (v7.2.4) to install with an error.

I have no idea how many other plugins may be using multiple aidl entries, as needed to support both cordova-android@6 and cordova-android@7.

I think the right thing to do is to undo the aidl change on the proposed patch release and maybe master branch of cordova-android. More work on our side, but probably worth it if we can avoid more broken plugins in the near future.

**Comment by j3k0** [comment]
Idea 2.

Remove the `^src/` and `^app/src/main/aidl/` part of all `<source-file>` entries, the add the correct prefix.

For plugins that have 2 entries, will it cause a problem if the aidl is installed twice at the same location?

**Comment by brodybits** [comment]
> For plugins that have 2 entries, will it cause a problem if the aidl is installed twice at the same location?

Yes that is the whole problem, unfortunately. It would be possible to use `--force` as a workaround, I don't really like it though.

**Comment by brodybits** [comment]
As discussed <https://github.com/apache/cordova-android/issues/547> I think we *do* want to keep the `.aidl` change in the upcoming patch release, which means you would have to remove second `.aidl` entry. I think you should wait for us to publish the patch before making the change. My apologies for all the confusion here.

**Comment by j3k0** [comment]
No problems, I understand the reasons for the confusion ;-) So I'll wait and the patch is released I ask users to stick to `cordova-android@7.1.1`. Good luck with this!

**Comment by brodybits** [comment]
@j3k0 you have to get rid of the second `.aidl` entry for this plugin to work with recent cordova-android releases `7.1.3` and `7.1.3`.
