### ISSUE TITLE
ERROR 6777001: Init failed - Failed to query inventory:

### ISSUE THREAD

**Issue by Moussawi7** [j3k0/cordova-plugin-purchase#76]
Hi @j3k0 ,
I am unable to purchase the same product twice, although that my products are CONSUMEABLE .
and i read the documentation carefully but you didn't mentioned how to consume a product, in order to purchase it again.
note that i am getting the following error:

ERROR 6777001: Init failed - Failed to query inventory: IabResult:
Error refreshing inventory (querying owned items).
(response: 6777017:Error)

Thank you.

**Comment by cameronbourke** [comment]
@j3k0 Awesome plugin man, but I'm running into the same error on Android aswell, but for a different reason.

```
ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)
```

I've finished any pending transactions, and the `billing key` is correct. The error occurs the first time `store.refresh()` is called. What can I get to help you out?

**Comment by dawidroz** [comment]
@cameronbourke - you fix this? We have a this same problem

**Comment by cameronbourke** [comment]
Hey @dawidroz. Do you get an error response. Should look something like this:
`(response: 6777017:Error)`

**Comment by dawidroz** [comment]
Yes. Exactly 

Wysłane z iPhone'a

Dnia 14 cze 2015 o godz. 07:33 Cameron Bourke <notifications@github.com> napisał(a):

**Comment by cloakedninjas** [comment]
For people getting this error message after purchasing `android.test.purchased`. The issue lies with Google:

> After you buy android.test.purchased the verifyPurchase function in Security.java will always fail and the QueryInventoryFinishedListener will stop at the line if (result.isFailure()); this is because the android.test.purchased item always fails the TextUtils.isEmpty(signature) check in Security.java as it is not a real item and has no signature returned by the server.

> - http://stackoverflow.com/questions/14600664/android-in-app-purchase-signature-verification-failed

A workaround for being able to purchase the test item multiple times is to clear data: Settings -> Apps -> Google Play Store -> Clear Data

**Comment by fer8a** [comment]
@j3k0 Any thoughts on this? I have the same problem as @cameronbourke and @dawidroz . It happened to me with non_consumable products. I get the error response only after a purchase has been made even thought my billing_key is properly set.

I tested with another Google account (one without any purchase, hence the error is not happening) and in the logs what I can notice is that for the one with the error the `android -> ready` is not being called.

Like @cameronbourke shows [here](https://gist.github.com/cameronbourke/f4b70284a77bccb72ada) that's the point where the execution ends. This is what is supposed to be executed after:

```
store-android.js:453 [store.js] DEBUG: android -> ready
store-android.js:726 InAppBilling[js]: getAvailableProducts called!
store-android.js:453 [store.js] DEBUG: android -> loaded -
```

**Comment by dominhquan** [comment]
@cloakedninjas : clear all data from google playstore doesn't solve the problem,  we cant get the response from google play, i need it for my server to verify itself. How can i get the valid data, or how to skip this verify phase from this plugin ?

**Comment by aerialglasgow** [comment]
Nov 2015. Great plugin thanks! But this problem is still occurring in Android on the all purchases initiated AFTER the first purchase.

ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)

When the google play app data is cleared I can then start to purchase, but attempting a second purchase the Inventory errors appears again. I am using: 

    store.off(render);
    product.finish();
    order.finish();
    product = null;

I presume this is completing the order. 

Has anyone found this also?

Thanks

**Comment by Chuckv01** [comment]
I was able to fix this error:

ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned items). (response: 6777017:Error)

I had to completely uninstall the purchase plugin (ionic plugin rm cc.fovea.cordova.purchase) and reinstall it (ionic plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="..."). After reinstalling the plugin the error was resolved.

**Comment by pooblej** [comment]
My solution was to use the intel xdk
and used 

<script src="cordova.js"></script>
<script src="xdk/init-dev.js"></script> 
<title></title>
<script >

document.addEventListener("app.Ready", onAppReady, false) ;
function onAppReady() 
{

}


Using this cured the bug

**Comment by cdcv** [comment]
I am getting this same problem.  I have the app published to production.  After trying to complete a purchase on a device, this error happens and I have not been able to get anything other than this error after that point on that device (even after cancelling the subscription in the app store for the account, deleting and reinstalling the app).

Here is the console log from the device (which I got by putting the signed release build on my device using adb per the instructions in the repo):

registerProduct
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! '012 registered'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'paid subscription registered'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'subscription registered'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'registered'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! '012 updated'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'paid subscription updated'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'subscription updated'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.queries !! 'updated'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: store.trigger -> triggering action refreshed
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: queries !! 'refreshed'
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:4479 InAppBilling[js]: setup ok
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:4479 InAppBilling[js]: load ["012"]
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] DEBUG: queries ++ '012 approved'
854827d….js?meteor_js_resource=true:327 TEST: ERROR:{"code":6777001,"message":"Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned subscriptions). (response: 6777017:Error)"}
854827d….js?meteor_js_resource=true:327 Purchase ERROR 6777001: Init failed - Failed to query inventory: IabResult: Error refreshing inventory (querying owned subscriptions). (response: 6777017:Error)
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] WARNING: A callback in 'error' failed with an exception.
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] WARNING:            err is not defined
data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0M…:3952 [store.js] WARNING:            ReferenceError: err is not defined
    at Object.<anonymous> (https://app04.oncamera.co/854827dec597d7826ec3a06915c965ac5b5e73d6.js?meteor_js_resource=true:327:519024)
    at Array.store.error.callbacks.trigger (data:text/javascript;charset=utf-8;base64,Ly8gUGxhdGZvcm06IGFuZHJvaWQKLy8gN2VmOWY5YzAzMTY3YTRkZGU0MzcyZDg2OTQ3M

**Comment by rtm** [comment]
Is there any update or workaround for this problem?

Does removing and re-adding the plug-in really work? Why would that be?

I understand that I have to "finish" the transaction, but what if I have an old attempted transaction that was never finished? How would I finish that?

What about the case where the user tries to buy something, and the process of downloading/installing the purchase fails, so I don't want to finish the transaction, but rather cancel it somehow. How would I do that.

Is this problem related to the specific user that is logged in?

Anyway, thanks for this great plug-in. Overall it's really getting the job done for me. I like the design.

**Comment by Dexus** [comment]
Hi @rtm can you please share some implementation? And you set the BILLING_KEY correctly? 

Regards, Josef

**Comment by aswanee** [comment]
### **Hi j3k0**
I faced the same problem 
the reseon com from change in BILLING_KEY but this is not the real problem i was sure that i have changed the key in config.xml and backage.json but still get old key when run ionic Cordova platform add android 
finaly i found the old key in each of :

1. "app_root\plugins\android.json"
2. "app_root\plugins\fetch.json"

when chaged it the key coped correctly android project and the purcheses executed successfuly 

so to solve this problem when the key changed, you must : 

1. add the new key to package.json 
2. uninstall the plugin cc.fovea.cordova.purchase and reinstall it 

also you can replase the key in each of : 

1. package.json
2. config.xml
3. app_root\plugins\android.json
4. app_root\plugins\fetch.json
5. run command : 
             a: ionic cordova platform rm android 
             b: ionic cordova platform add android

**Comment by frapa** [comment]
I just found out that a reboot of the device seems to solve the problem (at least for me). Hope it helps someone.

**Comment by patrickschmelter** [comment]
On Android 10 I also needed to clear Google Play Services cache

**Comment by mohsinraza** [comment]
I tested your demo project and it works well but when I convert your demo project into vue js with framework 7 it always gives error querying owned items. 

Here is my code snippet. let me know if you could help @j3k0 
`export default {
    components: {},
    data() {
      return {
        productState:'',
        title:'',
        price:'',
        canPurchase:'',
        goldCoins:'Gold: ',
        isOwned:'',
      };
    },
    mounted() {
      const self = this;
      self.render();
      self.restoreInAppPurchase();
        
    },
    methods:{
      restoreInAppPurchase:function(){
        const self = this;

        try{
          if (!window.store) {
            console.log('Store not available');
            return;
          }

          const store = window.store;

          // Enable maximum logging level
          store.verbosity = store.DEBUG;

          store.register(
            {
              id:    'monthly',
              alias: 'my_consumable1',
              type:  store.CONSUMABLE
            }
          );

          store.error(function(error) {
            console.log('ERROR ' + error.code + ': ' + error.message);
          });


          store.when('my_consumable1').updated(self.render);
          //refresh
          store.refresh();
        }catch(err){
          console.log(err);
        }

      },
      render:function(){
        console.log('renderer callded');
        const self = this;
        // Get the product from the pool.
        var product = store.get("my_consumable1");

        if (!product) {
            // $el.html("");
            self.productState = "";
            self.title = "";
            self.price = "";
        }
        else if (product.state === store.REGISTERED) {
            // $el.html("<div class=\"loading\" />");
            self.productState = "loading";
            self.title = "loading";
            self.price = "loading";
        }
        else if (product.state === store.INVALID) {
            // $el.html("");
            self.productState = "Invalid";
            self.title = "";
            self.price = "";
        }
        else {
            // Good! Product loaded and valid.
            // $el.html(
            //       "<div class=\"title\">"       + product.title       + "</div>"
            //     + "<div class=\"description\">" + product.description + "</div>"
            //     + "<div class=\"price\">"       + product.price       + "</div>"
            // );

            self.productState = product.description;
            self.title = product.title;
            self.price = product.price;


            // Is this product owned? Give him a special class.
            if (product.owned){
                self.isOwned = "Owned";
                self.goldCoins = "Gold: 10";
            }else{
              self.isOwned = "Not Owned";
              self.goldCoins = "Gold: 0";
            }

            // Is an order for this product in progress? Can't be ordered right now?
            if (product.canPurchase)
                self.canPurchase = true;
            else
                self.canPurchase = false;
        }

    
      },
      hide:function(){
        // method called when the view is hidden
            store.off(render);
      }

    }
  };`
