### ISSUE TITLE
[IMPORTANT MESSAGE] Issue with cordova-android@7.1.2

### ISSUE THREAD

**Issue by j3k0** [j3k0/cordova-plugin-purchase#762]
Platform `cordova-android` version `7.1.2` introduced a breaking change that prevents the plugin from installing/uninstalling correctly.

The issue is on their side, so while waiting for the release of version `7.1.3` you should stick to `cordova-android@7.1.1`

     cordova platform remove android
     cordova platform add cordova-android@7.1.1

Subscribe to this thread to get notified when the issue is resolved.

**Comment by brodybits** [comment]
Should be resolved by recently published updates (`cordova-android` versions `7.1.3` & `7.1.4`)

**Comment by paulstelzer** [comment]
If you remove this line in your plugin

`<source-file src="src/android/com/android/vending/billing/IInAppBillingService.aidl" target-dir="src/com/android/vending/billing" />`

The plugin will install correctly

**Comment by brodybits** [comment]
Should be resolved by cordova-android 7.1.3 & 7.1.4 but you have to remove the second `.aidl` entry from `config.xml` (#759).

**Comment by j3k0** [comment]
Published `cc.fovea.cordova.purchase@7.2.5`
