### ISSUE TITLE
iOS: Check to see if user purchased original paid app

### ISSUE THREAD

**Issue by mikelsteffen** [j3k0/cordova-plugin-purchase#763]
My app is currently a paid upfront app.  I'm planning to make it free with in-app purchases.  I don't want people that originally payed for the app to have to repurchase in-app purchases.  Is there a way to check if a user has purchased the original paid app?

A non Cordova version of this questions has been asked and answered here,

https://stackoverflow.com/questions/19390810/change-paid-app-to-free-but-know-if-user-previously-purchased-it

Thanks!

**Comment by mikelsteffen** [comment]
It appears as though the original paid app purchase receipt is included when store.when('product').approved is fired.  This includes the original purchase date and version.  It will come through even before any in app purchases have been purchased.

**Comment by dominic-simplan** [comment]
@mikelsteffen do you have to use the bundle ID of the app as the 'product' identifier or on which ID did you register to get the original purchase information of the app?

**Comment by dominic-simplan** [comment]
@mikelsteffen thanks for the update!

**Comment by Lander20** [comment]
Hi @mikelsteffen,
How did you recover the initial purchase of the app?

It didn't work for me :( 
Please help meee

**Comment by ragcsalo** [comment]
does this method work well? if yes, can you give me some hint how to do it the right way? I have the same situation as the author of the original post... :-)

**Comment by pedrumgolriz** [comment]
anyone know how you test this? My devices never get the bundle approved and I don't want to test this in production
