### ISSUE TITLE
Error 6777019 Failed to restore purchase on iOS

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#765]
I have a user who received this message on a second device from the one that made the purchase when selecting restore purchases on iOS.  The secondary information was:

Check your store for a valid purchase.

This scenario may be a bit unusual and here is the underlying information:
The user selected a auto renewing subscription that has a 1 week trial. The trial period has not expired.

I am wondering if the reason he has gotten this error is because his purchase is still within the trial period?

This is on version 7.2.0

**Comment by j3k0** [comment]
Plugin version `7.2.0` does not officially support introductary prices (this hasn't been tested by developers). It's a feature in progress (with preliminary support in the latest beta release).

I'll make sure we include your use case when testing.

**Comment by Dexus** [comment]
Ref: #752, #746, #743
