### ISSUE TITLE
[IOS] Your app should be single page to use in-app-purchases

### ISSUE THREAD

**Issue by paulstelzer** [j3k0/cordova-plugin-purchase#769]
### system info
```
Cordova 8.1.2
Cordova-ios: 4.5.5
Device: iPad iOS 12
Plugin Version: 7.3.0-beta.0
```

### Expected behavior
I am building an App with Angular 7, Ionic 4 and Cordova. On this app I get `"Your app should be single page to use in-app-purchases"`. Does anyone had this issue in last time? I have another app with this Stack and this is working. So I think something in Angular (not your Cordova Plugin) is causing the issue. But I ask here because maybe another one could fixed it

**Comment by j3k0** [comment]
This warning is only shown to remind you of the fact that `"Your app should be single page"`. It's not an error unless your app is switching different HTML file. You're using Angular, so I assume your app is single page, you should be good.

**Comment by paulstelzer** [comment]
@j3k0 okay, then it must be another issue that the IAPs not loaded correctly

**Comment by paulstelzer** [comment]
@j3k0 Okay, got it. Wasn't the issue I said above...

I bought an Subscription with a sandbox account few days ago. Now he wants to check it, but I was already logged out of this sandbox account and used my normal iTunes Account. So refreshing the receipt didn't work and the plugin stops after "receipt refresh request".

After I logged in with my sandbox account again, in the log files I found "got refreshed receipt". And only now he continues and said "ios -> loading products"

Is this normal behaviour? This seems very awkward that he not continue with loading the products. A member of the Apple team who checks the app, had exactly the same problem, that the products were not shown to him ( I think because of the same problem that he tries to check the receipt).

Do you have an idea for this?

**Comment by patrickhulce** [comment]
Are there any consequences of this? I upgraded to iOS 12 (among lots of other changes, but this seems most likely?) and now `store.order` is a NOOP. I'm getting this on my application even when I'm just a single page, and it seems like this might be a common problem. https://groups.google.com/forum/#!topic/phonegap/_YbNq4PcNV0. Could this really be responsible for the broken `store.order` or should I file a separate issue?
