### ISSUE TITLE
[IOS] Refresh receipt stops loading the In-App-Purchases

### ISSUE THREAD

**Issue by paulstelzer** [j3k0/cordova-plugin-purchase#770]
### system info
```
Cordova 8.1.2
Cordova-ios: 4.5.5
Device: iPad iOS 12
Plugin Version: 7.3.0-beta.0
```

### Expected behavior

Loading In-App-Purchases although he is looking for a receipt refresh for a subscription

### Observed behavior

I bought an Subscription with a sandbox account few days ago. Now he wants to check it, but I was already logged out of this sandbox account and used my normal iTunes Account. So refreshing the receipt didn't work and the plugin stops after "receipt refresh request".

After I logged in with my sandbox account again, now it triggers "got refreshed receipt". And only now he continues and said "ios -> loading products". Now i can see the prices of my product etc.

Is this normal behaviour? This seems very awkward that he not continue with loading the products. A member of the Apple team who checks the app, had exactly the same problem, that the products were not shown to him ( I think because of the same problem that he tries to check the receipt).

Do you have an idea for this?

### Steps to reproduce

Buy a subscription with a sandbox account. Close the app, log out of the sandbox account and open the app again. The in app purchases not working anymore

**Comment by Dexus** [comment]
Hi @paulstelzer I will look into this issue.

For now I know, also from other apps, that the biggest Issue is, that you can buy with different accounts and, you have to login in the accounts to reactivate/verify this purchases... maybe i can find the problem.

**Comment by j3k0** [comment]
Note that part of the issue is that you're using the "beta" release of the plugin. Thanks for trying it out. You can probably solve the issue by moving back to the stable version (`7.2.4` as the moment).

I think commit 8ca154d created your problem, new features like introductory prices require that the receipt be loaded at app start. I'll check you use case, indeed failing to load the receipt shouldn't stop the rest of the process.

**Comment by paulstelzer** [comment]
You uploaded 7.3.0-beta.0 as latest (see https://www.npmjs.com/package/cc.fovea.cordova.purchase), not with the beta tag). Have to check if you are right and 7.2.4 has not this issue

**Comment by paulstelzer** [comment]
@j3k0 Yes, you are right. It's not happening on 7.2.5 :)
