### ISSUE TITLE
[ANDROID] Device offline: product becomes valid, but validation fails

### ISSUE THREAD

**Issue by znegva** [j3k0/cordova-plugin-purchase#773]
### system info
```
cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
"cordova-android": "7.1.1"
ionic (Ionic CLI)  : 4.4.0
Ionic Framework    : ionic-angular 3.9.2
Android SDK Tools : 26.1.1
Device: Android 6.0.1
"cc.fovea.cordova.purchase": "7.2.4",
```

### App Description
My App uses a locally stored setting `offerAdditionalFeatures: boolean`, anything related to additional features is dependant on this locally stored setting.

The related purchase is of type `store.NON_CONSUMABLE`.  
I configured the plugin to something like this (shortened and simplified):
```js
this.store.validator = "https://myvalidationserver.com/check_purchase/";

this.store.register({
  id: id,
  alias: alias,
  type: this.store.NON_CONSUMABLE
});

this.store.when(id).updated( (product: IAPProduct) => {
  if(!product){
    this.log("Product " + product.id + "not found");
  }else if(product.state === this.store.REGISTERED){
    this.log(product.id + " was registered");
  }else if(product.state === this.store.INVALID){
    this.log(product.id + " is invalid, probably unknown to the store");
  }else{
    this.log(product.id + " is valid!");
    if(product.owned){
      this.log("You own " + product.id);
      this.offerAdditionalFeatures = true;
    }else{
      this.log("You dont own " + product.id);
      this.offerAdditionalFeatures = false;
    }
  }
)};
```

### Expected behavior
if the device is offline, store initialization at all should fail, as mentioned [here](https://github.com/j3k0/cordova-plugin-purchase/issues/210#issuecomment-110228975).
__OR__
if device is offline online-validation should be bypassed.

### Observed behavior
the product is loaded as if we would be online ( I guess from some cached store or whatever),
product changes to state valid and all the additional infos (such as correct price etc.) are set.  

But because the device is offline the validation service cannot be reached --> validation fails --> product gets status __NOT OWNED__ --> my locally stored variable `this.offerAdditionalFeatures` is set to false.

### Steps to reproduce
- define `NON_CONSUMABLE` product, register in a way as described above to manipulate a local variable to be set in regard to the owned-state of the product.
- Start App with device online
- Buy product, if validation is successful the local variable should be set to true
- Close the App
- disable Wifi, mobile Data etc.
- start App and trigger store update
- you should see that the product becomes valid, but the validation service cannot be reached and therefore the product becomes _not owned_, therefore your local variable is set to `false`

### Additional info, iOS
I also tested the same app on iPhone (iOS 12.1) which works as expected.
I get some store-error-messages (bc. offline..), but the local variable is not changed!

### reflections
Maybe we do not need to react on NotOwned for `store.NON_CONSUMABLE` products anyway?
One scenario is refunded in-app-purchases, when this happens we should be able to react on not-owned-status.

But for subscriptions this is essential, as the owned state most probably will change at some point!

**Comment by Dexus** [comment]
@j3k0 Think we should first document that each product is verified online. Offline verification or caching of the results will not be done. That would probably not approve Apple/Google either...
But I'll check what the well-known AppStores have to say about it.

**Comment by znegva** [comment]
Hi,
the issue was not really about asking for any kind of offline validation, I am aware this impossible without creating more problems.

The problem is, that a product can get status `valid` even if the device is offline.
Because the device is offline checking the receipt with the validation-Server will fail.
This results in the product being `not owned`.

Ultimately this means the plugin attests all products to be `not owned` only because the device is offline.

---
This is only an Android-Problem.
On iOS the product never gets `valid`, so no receipt-validation is tried and no claims about the product are made - which is the correct behaviour, as we just dont know anything, because we are offline 😄

**Comment by j3k0** [comment]
Yes, on iOS product data aren't being cached.

Generally, you have to decide on the best strategy for your app. If your service don't require internet and you want to let users access paid-for features without validation when the device is offline, you're opening up a security hole, but you can.... For example, store the date of last successful validation in localStorage and check if it's set (and not older than 24h for example). Note that hackers can use this to unlock the feature by setting it manually in localStorage. You can make it harder, but as long as the feature is implemented client-side, there's no silver bullet against hackers anyway...

**Comment by j3k0** [comment]
Also note that while offline, products will remain in the "approved" state, meaning that a purchase attempt (real or fake) as been made, but we cannot verify it and proceed to the final "owned" state. For expired subscriptions and cancelled transactions, products will move back to the "valid" state (meaning it has to be purchased again).

This can also be helpful to take a business decision on when you want to make the feature available. (Only when "owned" or also when "approved"..)

**Comment by j3k0** [comment]
Please reopen if you want to discuss more!
