### ISSUE TITLE
Using billing.fovea.cc as validator service: how to know about purchase on my backend?

### ISSUE THREAD

**Issue by byaka** [j3k0/cordova-plugin-purchase#775]
I want to use this service for validating parchase, but i need to know that purchase was done on my backend. any ideas?

**Comment by Dexus** [comment]
I would think you can use your own website/script as a proxy to send it to billing.fovea.cc and get the data of the purchase and the validator to process future.

Von meinem iPhone gesendet

**Comment by byaka** [comment]
@j3k0 thx for info!
