### ISSUE TITLE
[Android] Doesn't trigger cordova 7.1

### ISSUE THREAD

**Issue by eyalish** [j3k0/cordova-plugin-purchase#778]
### system info
Android cordova 7.1.0
Version plugin 7.2.4
been tested on two devices Android 6 and 4+ and Firebase.

I want to say everything worked well until few months ago,
Something has gone wrong lately....
 

```js
flag = false;

document.addEventListener('deviceready', initializeStore, false);

function initializeStore() { // Let's set a pretty high verbosity level, so that we see a lot of stuff                
    // in the console (reassuring us that something is happening).                
    store.verbosity = store.WARNING; // We register a dummy product. It's ok, it shouldn't               
    // prevent the store "ready" event from firing.  "noads"  is the current id                
    store.register({
        id: "xxxxx",
        alias: "no ads",
        type: store.NON_CONSUMABLE
    }); // When everything goes as expected, it's time to celebrate!              
    store.ready(function () {
        console.log("STORE READY");
    }); // When purchase is approved show some logs and finish the transaction.           
    store.when("xxx").approved(function (order) {
        console.log("PURCHASE APPROVED");
        order.finish();
    });
    store.when("xxx").owned(function () {
        console.log("PRODUCT PURCHASED");
        alert('.......');
        disableADS(); // custom function triggered          
    }); // After we've done our setup, we tell the store to do         
    // it's first refresh. Nothing will happen if we do not call store.refresh()                
    store.refresh();
}

function buyADS() {
    store.order('xxxxxx');
}

function disableADS() {
    flag = true;
}
```

### Expected behavior
Button to trigger the inApp window
### Observed behavior
Nothing happens.

**Comment by Dexus** [comment]
Hi @eyalish did you try to update to latest cordova-android 7.1.4?

And can you please tell us what has changed since the last working app? What did you update and from which version?

**Comment by j3k0** [comment]
@eyalish -- can you share the error logs you see. 99% of the time, there's an exception triggered somewhere that prevent the code from running.

Unrelated side note: you should do `disableADS()` before calling `order.finish()`. That's why both Android and iOS have a 2 steps purchase flow. Make sure you deliver the feature before finalizing a transaction.

**Comment by eyalish** [comment]
@Dexus special, just updated few plugins such as; 

>     <plugin name="cordova-plugin-dialogs" spec="2.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-file" spec="6.0.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="3.0.0" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-multidex" source="npm" spec="0.1.4" />
    <gap:plugin name="tappx-phonegap-build" source="npm"/>

I'm using Builder,
it supports maximum 7.1.2 (cli 8.1.1), but it won't work so I use 7.1.0 (cli 7.1.2)

@j3k0 error log attached

[build.phonegap.log](https://github.com/j3k0/cordova-plugin-purchase/files/2680244/build.phonegap.log)
I fixed with your side note.
i can't see any errors on the console with chrome devtools.

**Comment by j3k0** [comment]
@eyalish Sorry I wasn't clear. I'd like to see runtime logs (when the issue occurs), not build logs.

**Comment by eyalish** [comment]
@j3k0 Okay, 
I receive this on console log:
ReferenceError: store is not defined
function buyADS(){   
         store.order('subscription name');
        }

from the log cat it gives: 
12-05 06:06:14.856: I/Robo(11418): Ä±nput_type: NONE
12-05 06:06:14.856: I/Robo(11418): Ä±s_web_view_element: true with ActionParameters{}}.
12-05 06:06:14.863: I/Robo(11474): UiAutomator: click on UiAutomator {# com.google.android.apps.mtaas.crawler.proto.ElementDescription@ca3f64b7
12-05 06:06:14.863: I/Robo(11474): class_name: "android.widget.Button"
12-05 06:06:14.863: I/Robo(11474): component_type: BUTTON
12-05 06:06:14.863: I/Robo(11474): content_description: "Subscribe"
12-05 06:06:14.863: I/Robo(11474): Ä±dentifiers {
12-05 06:06:14.863: I/Robo(11474):   child_position: 13
12-05 06:06:14.863: I/Robo(11474):   mode_agnostic_sequence: "0.2.0.0.0.9"
12-05 06:06:14.863: I/Robo(11474):   mode_specific_sequence: "0.0.0.0.0.13"
12-05 06:06:14.863: I/Robo(11474): }
[logcat (2).txt](https://github.com/j3k0/cordova-plugin-purchase/files/2683598/logcat.2.txt)

**Comment by eyalish** [comment]
@j3k0  PS, The plugin works now with version 7.1.0.
something isn't working with version 7.2.4/7.2.5..

**Comment by j3k0** [comment]
`store` not defined probably means there has been a problem with the plugin installation. Hopefully PhoneGap will update to the latest version of cordova-android soon.
