### ISSUE TITLE
[IOS] Apple ID credentials pop-up

### ISSUE THREAD

**Issue by transasia** [j3k0/cordova-plugin-purchase#781]
Apple Review rejects app with the following message:

> We discovered one or more bugs in your app when reviewed on iPad running iOS 12.1.1 on Wi-Fi.
> 
> Specifically, when we attempted to purchase a subscription, your app loops back to our Apple ID credentials and we were unable to subscribe to your service.

When subscribing, the app asks for the iTunes credentials twice. 
In my case, I get the regular pop-up to confirm the subscription with my password. After that I get a second pop-up asking for the Apple ID and password.

When I enter it again, I am able to subscribe though.

That does not happen with one-time purchases (non consumable).

A few years ago, I opened a similar issue #357 .
It has been said that this only happens while that app is in sandbox mode.
Last time I was able to release the app and it worked afterwards.
But this time, Apple prevents me from releasing the app because of this.

Is there any way to avoid this second popup?

### system info

Device: iOS 12.1.1 iPad
cordova-ios@4.5.5
Plugin Version: 7.2.5 (also on 7.3 beta)
Built with iOS 11.4 SDK (also on OS 12.10 SDK)

**Comment by j3k0** [comment]
Note, it was solved by setting `store.autoFinishTransactions = true`. I suspect the client purchased some products that aren't registered anymore. I have to check the logs to confirm (on my emails).

**Comment by j3k0** [comment]
Sorry @creakosta for not replying earlier. Just a heads up, it seems like the original author issue was from his receipt validation server. The issue apparently went away when using [Fovea's](https://billing.fovea.cc/). I hope you found a solution already.
