### ISSUE TITLE
[IOS] Fails to detect "cancel" during user authentication

### ISSUE THREAD

**Issue by doug1e** [j3k0/cordova-plugin-purchase#786]
### system info

iPhone, ios7
ionic 4
cc.fovea.cordova.purchase: 7.3.0-beta.0

In example:
```
OSX Sierra 10.12.04
Cordova 7.0.1 // Phone Gap 3.19.2 etc.
Device: iPhone iOS 10.3.2 // Android 7.1
Plugin Version: 6.0.0
```

### Expected behavior

After refresh() Apple Store authentication pop up requires user id and password. When cancel is clicked, I'd expect store.when(productId).cancelled() to be called. 

### Observed behavior

The store.when(productId).cancelled() function is called when the product is registered and the purchase is cancelled during the transaction. However, if the "cancel" button is clicked during user authentication, there is no feedback from the API.

I also could not see an error thrown either. I might be doing something wrong but this is what I observe. I'd be grateful for you feedback.

I should also add that the login alert box keeps popping up despite clicking "Cancel"

### Steps to reproduce

Log out from the app store and call refresh() to retrieve product info. I am logged out of the app store mainly to test via sandbox.

**Comment by eduboxgithub** [comment]
I'm also facing this error. 

The "cancel" button on the login screen does not fire the cancel event.

I think it should and fire the "cancel" event.

How can we overcome this situation?

@doug1e did you manage to find a solution?

Thank you.

**Comment by j3k0** [comment]
It's not a bug (in the plugin at least). StoreKit doesn't fire any events when the user hits "cancel", so there's no way to know.

`cancelled` is called when the user cancels a purchase, not when it cancels a "refresh()".

Anyway, are we talking about the initial `refresh()`? The latest version of the plugin isn't supposed to ask for passwords in this case. The only case it might do it is if you're having a subscription product that needs validation and your validation server doesn't support the `latestReceipt` feature.

A subsequent call to `refresh()` is only necessary for the "restore purchases" functionality... in which case, indeed, no callback will be called if the user refuses to login into the AppStore.

**Comment by mifkys** [comment]
Can you explain what format for `latestReceipt` response must be returned from server?

**Comment by mifkys** [comment]
@j3k0 I founded `latest_receipt` in sources. But what exactly server must return in this variable? transaction.appStoreReceipt?
