### ISSUE TITLE
[ANDROID] [store.js] INFO: plugin -> buy error 6777010

### ISSUE THREAD

**Issue by manelclos** [j3k0/cordova-plugin-purchase#788]
### System Info

```
OSX Mojave 10.14.02
Cordova 8.0.0
Device: Android 9
Plugin Version: 7.2.6
```

### Expected behavior
- Show dialog for buying product (subscription)
- Buy the product
- Product update event with state === 'approved'

### Observed behavior
- Error is shown in console after buying the product
[store.js] INFO: plugin -> buy error 6777010
- Product update event with state === 'valid'
- After killing the App the update events contain the good data with state === 'approved'

### store.verbosity = store.DEBUG

```
InAppBilling[js]: buy called!
(Successfully purchased -> OK -> control returned to APP)
[store.js] INFO: plugin -> buy error 6777010
[store.js] DEBUG: store.queries !! '134_xxx.yyy_134 valid'
[store.js] DEBUG: store.queries !! 'quota mensual valid'
[store.js] DEBUG: store.queries !! 'consumable valid'
[store.js] DEBUG: store.queries !! 'valid valid'
[store.js] DEBUG: store.queries !! 'valid'
[store.js] DEBUG: store.queries !! '134_xxx.yyy_134 updated'
[store.js] DEBUG: store.queries !! 'quota mensual updated'
[store.js] DEBUG: store.queries !! 'consumable updated'
[store.js] DEBUG: store.queries !! 'valid updated'
[store.js] DEBUG: store.queries !! 'updated'
```

And some more info yet from the store.error handler:

```
ERROR 6777010: Purchase failed: Error purchasing: IabResult: IAB returned null purchaseData or dataSignature (response: 6777010:Error)
```

**Comment by manelclos** [comment]
Current workaround is to use store.error(), filter the error code and do a location.reload() to force "app restart". Not perfect, but works in the meantime.

**Comment by droppy2014** [comment]
I have the same problem on ionic 3

**Comment by beisnikosspi** [comment]
Me too...

**Comment by AthiraWD** [comment]
Im also facing the same issue

**Comment by manelclos** [comment]
Hi all, this happened to me with version 7.2.6 of the plugin. Can you please say which version are you using/testing? There's been quite a few releases and it would save me some testing time :)

**Comment by devHamza** [comment]
Facing same issue ! on both version : 7.2.6 and 7.4.3 
Any help on this please ? 

cordova ios 8.0.0 
ionic 3

**Comment by ErxrilOwl** [comment]
+1 Any update?

**Comment by j3k0** [comment]
It doesn't happen here. Android is my main dev platform, so I should have noticed. Did you try different version of Android, maybe this happens only on certain devices? Can we get a list of failing devices here (just in case this were we should be looking at)?

**Comment by nprather** [comment]
I'm getting a similar error.  I think this may relate to Android 9.  I've had several users complain that they couldn't purchase and all where running Android 9.0.   I'm just using simple non-consumable purchases...

**Comment by manelclos** [comment]
+1 Running Android 9.0 too on testing device!

**Comment by j3k0** [comment]
Ok. I don't have a Android 9 device here... Anyone could dig out more data for debugging? logcat trace maybe.

**Comment by nprather** [comment]
I ordered a new Pixel that's supposed to arrive tomorrow or the next day...  Until then I'm doing a less accurate test on my end using Genymotion and gapps: https://www.genymotion.com/blog/2-10-open-gapps-widget/

**Comment by Aviho-M** [comment]
+1 Any update? please?

**Comment by j3k0** [comment]
@nprather So how is the Pixel? ;-) Did you make the plugin work with it?

**Comment by nprather** [comment]
Not yet, I ended up doing an emergency switch to this plugin from [Alex](https://github.com/AlexDisler/cordova-plugin-inapppurchase ) and it worked with Android 9, BUT, it introduced some other bugs that I've been putting out, and it would randomly bomb out on iOS so I've since switched iOS back to your plugin version 7.2.8.  

Tomorrow, I'm going to install the latest version of your plugin version 8 and test using the method you documented [here ](https://purchase.cordova.fovea.cc/use-cases/consumable-android#testing) so that I can get logcat output to isolate the problem, if it's still there...  `adb logcat "chromium:I *:E"`  I'll write back here to let you know how it goes.

On a side note, thanks for all your hard work on this plugin!  If I find the bug I will try to get it fixed locally and I guess do a pull request for your review?  I've never contributed to github so not sure how it all works.  Anyway, I'll keep you posted. 
Nathan

**Comment by j3k0** [comment]
> On a side note, thanks for all your hard work on this plugin! If I find the bug I will try to get it fixed locally and I guess do a pull request for your review? I've never contributed to github so not sure how it all works. Anyway, I'll keep you posted.

Welcome, crossing fingers that no fix will be required. Testing is also contributing, so thank you! 😄

**Comment by nprather** [comment]
I just tested on Android 8 and 9 on real devices and everything worked great!  Wish I would have saved myself some work and tested this in Android Studio to try to isolate the bug with logcat before switching all my code to the other plugin but live and learn!

I used a Mac, with the very latest version of Cordova Android (android 8.1.0-dev) for testing :  cordova platform add https://github.com/apache/cordova-android.git . 
Had to use that b/c was getting some errors in Android Studio that the latest version fixed.

I tested the latest pinned version of the Purchase Plugin: cordova-plugin-purchase 8.1.0 "Purchase"

Also works great with Cordova iOS v5.0.1

Thanks for your help!
Nathan

**Comment by rcauquil** [comment]
I'm facing the same issue on a P30pro under Android 10
then when I kill the app, relaunch I get the approved event with the transaction payload

**Comment by rcauquil** [comment]
for anyone facing the same issue, I fixed it by upgrading the module version from 8.x to 10.x

**Comment by joefaron** [comment]
I'm on 11x, had to register all of my google play in-app products, then try to order them.. finally worked.. didn't work when just registering 1 and trying to test it? was getting "buy error".
