### ISSUE TITLE
[ANDROID] Signature verification failed. After update

### ISSUE THREAD

**Issue by DanielDarrenJones** [j3k0/cordova-plugin-purchase#789]
### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

In example:
```
Phone Gap 8.2.2 // Android 7.1.4
Device: Samsung S6 Android 7.0
Plugin Version: 7.2.5
```

### Expected behavior
Application should continue working after updating the application through the android play store test track.

### Observed behavior
If a purchase was in progress but not finished the app fails to load, the console reports
```
01-18 09:23:47.723 13744 13874 E IABUtil/Security: Signature verification failed.
01-18 09:23:47.723 13744 13874 W IabHelper: In-app billing warning: Purchase signature verification **FAILED**. Not adding item.
```
and the app fails to load anything.

### Steps to reproduce
1.) Begin purchase, but do not call the finish method.
2.) Update android test track
3.) Re-open app

**Comment by DanielDarrenJones** [comment]
Update: It appears the subscription is becoming active even though the finish method is not called, and my validator is being bypassed?

Once the subscription has cancelled the plugin will re-open, but not If I manually cancel it.

**Comment by j3k0** [comment]
Your issue seems to indicate that the billing key is misconfigured. Is it possible your `BILLING_KEY` doesn't match the apps' license key on google play developer console?
