### ISSUE TITLE
"sign in to iTunes Store" dialog

### ISSUE THREAD

**Issue by pipep** [j3k0/cordova-plugin-purchase#79]
Hi j3k0, thanks for the great plugin!  

I managed to make it work but I can't figure out how to avoid the "Sign In to iTunes Store" dialog to appear every time I launch the app.

The first time you login it goes, but if I quit and reopen the app, it appears again.. even if the app is open on the background, it appears from time to time.

I'm hoping to make it appear only when someone tries to buy something, not on launch or store initialization.

Any ideas ?

**Comment by uxder** [comment]
I'm running into the same issue but from an application point of view, I need to call store.refresh() multiple times.

Does the popup show up because it's a sandbox account?  In a real live app, it wouldn't keep popping up right since the user is already logged into their itunes account.

**Comment by pipep** [comment]
@uxder
When I found myself on this situation I was on ios sandbox as well, so you shouldn't see the problem there at all.. sandbox is "live, but out of the store", everything else is as it will be shown to costumers...

You most definitely don't need to call store.refresh() multiple times.

I don't know your scenario, but take a deep read at the API documentation, almost everything you need to achieve is covered, this issue was my mistake in the first place...

**Comment by uxder** [comment]
Thanks pipep.

Yeah I was calling store.refresh in order to get the product state as owned (to restore purchases).

I ended up making that a separate button and it worked.

I do get a login prompt even on the first store.refresh() though.  That is normal right?

**Comment by adriano-di-giovanni** [comment]
Does anybody of you use GoogleMobileAds SDK for iOS? If so, try to delay the store initialization. Does the popup still fires? If so, try to add

[GADMobileAds disableAutomatedInAppPurchaseReporting];
to your AppDelegate

Does the popup still fires?
