### ISSUE TITLE
[IOS] store.ready callback is not triggered after first store.refresh

### ISSUE THREAD

**Issue by walmink** [j3k0/cordova-plugin-purchase#791]
### Problem
After registering a product, setting a callback for `store.ready` and calling `store.refresh()`, the callback never gets called. However, something in the logs is happening after I call `store.refresh()` (see logs below).

My code is based on the [minimal example](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/minimal-example.js).

### Logs
```
[Log] >> Call store.register() (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'com.walmink.secretsigns.UnlockAllRiddles registered' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'Unlock all riddles registered' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'non consumable registered' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'registered' (cordova.js, line 1732)
[Log] [store.js] DEBUG: ios -> product com.walmink.secretsigns.UnlockAllRiddles registered (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'com.walmink.secretsigns.UnlockAllRiddles updated' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'Unlock all riddles updated' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.queries !! 'updated' (cordova.js, line 1732)
[Log] >> Set callback on store.ready() (cordova.js, line 1732)
[Log] >> Set callback on store.error() (cordova.js, line 1732)
[Log] >> Call store.refresh() (cordova.js, line 1732)
[Log] [store.js] DEBUG: store.trigger -> triggering action refreshed (cordova.js, line 1732)
[Log] [store.js] DEBUG: queries !! 'refreshed' (cordova.js, line 1732)
[Log] [store.js] DEBUG: ios -> initializing storekit (cordova.js, line 1732)
```

### system info
```
OSX Mojave 10.14.2
Cordova 8.1.2 (cordova-lib@8.1.1)
Device: iPhone SE (iOS 12.0.1)
Plugin version: 7.2.5
```

**Comment by walmink** [comment]
Here's some more info to hopefully isolate the problem:

Calling the `store.get()` manually (by button click) a while after the app has loaded, shows that data was either not retrieved or not updated:
```
Product:
additionalData: null
alias: "Unlock all riddles"
canPurchase: false
countryCode: null
currency: null
description: null
downloaded: false
downloading: false
id: "com.walmink.secretsigns.UnlockAllRiddles"
loaded: false
owned: false
price: null
priceMicros: null
state: "registered"
title: null
transaction: null
type: "non consumable"
```

However, using another plugin called [cordova-plugin-inapppurchase](https://github.com/AlexDisler/cordova-plugin-inapppurchase), calling `getProducts("UnlockAllRiddles")` does retrieve the data for me, so it seems there is no problem with my setup on the Apple side.

🤔

**Comment by Dexus** [comment]
Do you use the ID for the product with the bundle ID?

The question is what do you have used in the apple developer center for the item... please do not add the bundle ID of the app!

Von meinem iPhone gesendet

**Comment by j3k0** [comment]
To complete @Dexus comment: maybe your ID is `UnlockAllRiddles` and not `com.walmink.secretsigns.UnlockAllRiddles`. ?

**Comment by walmink** [comment]
@Dexus, @j3k0, my apologise for not responding. I was relying on email notifications to keep me updated, but forgot I don't receive them on this user account. 🙄

I saw the product ID formatted with bundle ID in the [minimal example](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/minimal-example.js) like this `com.example.app.inappid1`, so that's what I mimicked. Didn't realise I shouldn't use it! Removing the bundle ID didn't help, though.

I also tried it with a simple product ID named `test` to exclude any possible issues with capitalisation or other special characters. No luck.

However, I have a feeling the problem may be elsewhere. In the [minimal example](https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/minimal-example.js), it saids:

```
We register a dummy product. It's ok, it shouldn't prevent the store "ready" event from firing.
```

I assume this means that whatever products I register, real or not, doesn't matter. for the "ready" event. The store's "ready" event should trigger whenever it successfully connected to the App Store API.

Is that correct and if so, what may be my problem. I am able to successfully connect and get the product ID using Alex Disler's [in-app purchase plugin](https://github.com/AlexDisler/cordova-plugin-inapppurchase), but I'd much prefer to use yours.

**Comment by gabn88** [comment]
I'm having a similar issue on iOS. When connected with a debug app to a sandbox user account, everything works fine. But when using the production app, with a real user, the list of products doesn't come up. I tried updating from 7.2.4 to 7.4.3, but the problem persists.

I do get [store.js] INFO: ios -> storekit ready
But the store.ready callback is never called.

**Comment by gabn88** [comment]
Okay, it is working now.

What I did: remove platform. Update to the latest version. Also update wkwebview to the latest version. Updated to iOS-cordova 5.0.0. Removed cordova-plugin-app-event. Not sure what fixed it, but probably the upgrade to ios-cordova 5.0.0, including the new build system, as this is required by Apple since March.
