### ISSUE TITLE
More precise documentation regarding renewable subscriptions needed.

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [j3k0/cordova-plugin-purchase#794]
Some initial questions:

- how would cancelling a subscription affect the data returned by the plugin (owned, canPurchase, transaction, etc.)
- how would renewal of a subscription affect the data returned by the plugin (owned, canPurchase, transaction, etc.)
- as a result of a validator, what should we return when subscription is cancelled? Cancelled subscription is not yet expired (so still owned, until a date). But the only codes available are PURCHASE_EXPIRED, CONNECTION_FAILED and INVALID_PAYLOAD
- what is the expected flow for controlling renewable subscription? Does the author recommend the notification URL from (for instance) Apple and handle it on server, or would the plugin be able to handle all the state changes?
- `During application startup, products may go instantly from REGISTERED to APPROVED or OWNED, for example if they are purchased non-consumables or non-expired subscriptions.` - could it ever happen that it can go through all these states? REGISTERED -> APPROVED -> OWNED? Or once the purchase is approved, validated and finished, the APPROVED status would never trigger?
- why is the external transaction data (like iOS receipt, for example) "merged in" into product.transaction, rather than put into separate field, so that potential data loss can be prevented?
- how introductory prices (iOS) work with that plugin? If someone is purchasing a 1-month renewable subscription, with 2-week free trial period, how is that reflected in the data the plugin provides? How would the status change?
- what is the actual input data format for http validator?
- what is the actual output data format for http validator? What statuses? Should you return errors as 200 or other status?

**Comment by sebastian-zarzycki-es** [comment]
The lack of response is worrying.

**Comment by albertleao** [comment]
Bump

**Comment by solojuve1897** [comment]
Bump again

**Comment by Dexus** [comment]
See https://github.com/j3k0/cordova-plugin-purchase-documentation which can be found here: https://purchase.cordova.fovea.cc/
