### ISSUE TITLE
[IOS] Subscription are stacking up.

### ISSUE THREAD

**Issue by CarlosDuar** [j3k0/cordova-plugin-purchase#795]
# !!! [IOS] Subscription are stacking up.

It was created an application with the use of subscription for IOS. 
These subscriptions are purchased by the user and are sent to the service when they are approved/verified.
This service saves the transaction_id, expire_date and receipt from this transaction.
When the server finishes saving the info, the transaction / product is terminated with finish(). 
However when the application is rebooted the transaction is made again. passing through the cycle again. approved () -> verify () -> save to server -> finish.
Thus creating a big list of pending transactions that are executed whenever the user enter the store section.

Is this the normal workflow ?

**Comment by sebastian-zarzycki-es** [comment]
Most probably they're not verified correctly.

**Comment by CarlosDuar** [comment]
We're trying to do server verification only thus having a simple verification function:
```
window.store.validator = (product, callback)=>{
     callback(true, {});
};
```
After this we receive the product on the `verified` callback and send the info to our server. Its there that we validate with  apple's endpoint and handle the purchase at the same time. 

The issue seems that these products aren't being finished, even thou we always finishing the product no matter the server's response.  We even added `store.autoFinishTransactions = true` without much success.

**Comment by sebastian-zarzycki-es** [comment]
This seems like client-validation, not server one. On server, you would response with 200 and with a json object with specific structure (which seems to be totally undocumented at the moment, but you can kinda sorta reverse engineer it, looking through the source).
