### ISSUE TITLE
[ANDROID] Getting error on build after adding plugin

### ISSUE THREAD

**Issue by mowaiskalam** [j3k0/cordova-plugin-purchase#796]
### System info

```
Microsoft Windows 10
Cordova 7.1.0
Device: Android 7.1
Plugin Version: 7.4.1
```

### Expected behavior

Plugin should install and run without any error when providing the correct Billing key

### Observed behavior

Plugin has been installed successfully in app and I added my code for initiating subscription.
When building app it is giving error, here are some logs of error:
```
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug UP-TO-DATE
\platforms\android\app\src\main\java\com\smartmobilesoftware\util\IabHelper.java:444: error: cannot find symbol
                buyIntentBundle = mService.getBuyIntentToReplaceSkus(5, mContext.getPackageName(),
                                          ^
  symbol:   method getBuyIntentToReplaceSkus(int,String,List<String>,String,String,String)
  location: variable mService of type IInAppBillingService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:app:compileDebugJavaWithJavac FAILED
```

### Steps to reproduce

Just install the plugin and build the app

**Comment by Dexus** [comment]
Can you please provide following informations:

- Used SDK version (min, target)
- used java sdk/jre/jdk version

How you build? Do you also use the android studio?

Thanks.

**Comment by Dexus** [comment]
No additonal Informations
