### ISSUE TITLE
[iOS] WebPack errors upon any reference to store. 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [j3k0/cordova-plugin-purchase#797]
OSX Mojave 10.14.3
"ionic-angular": "^3.9.2" | cordova-ios": "^4.5.5",
Device: iPhone iOS 12.1.4
Plugin Version: 7.2.8

This might just be an Ionic issue, but I can't reference the InAppPurchase2 instance without getting an error like such thrown. Even just trying to set

```this.store.verbosity = this.store.DEBUG;``` throws these types of errors. 

__WEBPACK_IMPORTED_MODULE_0__ionic_native_core__["cordova"]) is not a function
 or 
__WEBPACK_IMPORTED_MODULE_0__ionic_native_core__["cordovaPropertyGet"]) is an instance of Object

**Comment by selected-pixel-jameson** [comment]
It looks like Ionic just releases version 5.1.0 of their native core library. I was installing the 5.1.0 version of the plugin but only have the 4.20.0 version of the native library. This was what was causing the issue.

**Comment by j3k0** [comment]
OK, thanks for the the heads-up.
