### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#798]
What is going on with your releases? 5 version bumps in two weeks, and no changelogs?

**Comment by j3k0** [comment]
Changelog is available as `git log` if needed. Apologizes for not taking the time to do it properly.

In short:

 - f152a7f : do not refresh the receipt when the receipt validator returns that a subscription expired and explicitly inform the plugin that it used the most up-to-date information (regardless of the info provided by the plugin).
 - 756a0f5: really make sure that the plugin won't refresh the receipt on iOS. This assumes that everyone doing subscription on iOS uses the `latest_receipt` on their validation servers, which has been the method recommended by Apple for a long time.

With both the above in place, the user shouldn't be requested for a password anymore after the initial purchase of a subscription product.

**Comment by j3k0** [comment]
Notes: some releases have been idiotic, like woops I forgot to update `plugin.xml` or the built javascript files...
