### ISSUE TITLE
(ios) Handle subscribe from the AppStore

### ISSUE THREAD

**Issue by j3k0** [j3k0/cordova-plugin-purchase#799]
@ivanov84 implemented a workaround, it'd be nice to it cleanup and put out there for everyone to use.

---

Here are the steps to do this:

1. add this to **InAppPurchase.m**:

```
- (BOOL)paymentQueue:(SKPaymentQueue *)queue shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product {
    // Another code here
    
    if ([productId isEqualToString:@"com.bestapp.1weeksubscription"]) {
        NSString *js = @"window.storekit.redirectionFromStoreDone.apply(window.storekit)";
        [self.commandDelegate evalJs: js];
        return NO;
    }
    else {
        return YES;
    }
}
```

2. add this to **ios-bridge.js**:

```
this.options = {
    // Another code here
    redirectionDone: options.redirectionDone || noop,
    // Another code here
}; 

InAppPurchase.prototype.redirectionFromStoreDone = function () {
    protectCall(this.options.redirectionDone, 'options.redirectionDone');
};
```

3. add this to **ios-adapter.js**:

```
storekit.init({
    // Another code here
    redirectionDone: storekitAppleStoreRedirectionDone,
    // Another code here
    }, storekitReady, storekitInitFailed); 

function storekitAppleStoreRedirectionDone() {
    store.log.info("ios -> redirection done");
    store.trigger('redirection-done');
}
```

3. add this to your code:

```
store.when('redirection-done', () => {
    this.openMySubscriptionModalPage();
});
```

_Originally posted by @ivanov84 in https://github.com/j3k0/cordova-plugin-purchase/issues/782#issuecomment-448577477_

**Comment by rafaellop** [comment]
@j3k0 This is urgent. Apple started to reject binaries which don't show an information to users before starting the purchase flow. Here's their comment to my rejection:

> Also, we noticed that your app did not fully meet the terms and conditions for auto-renewing subscriptions, as specified in Schedule 2, section 3.8(b) of the Paid Applications agreement.
Specifically, when the user initiates a promotional in-app purchase on the App Store, they are taken into your app to continue the transaction.

**Comment by j3k0** [comment]
it's handled now.
