### ISSUE TITLE
Custom validation - should product.finish() be called?

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [j3k0/cordova-plugin-purchase#802]
What are the consequences of validator returning product as unverified? It seems that current code doesn't really care about the reason, it just checks whether product is valid or whether it is expired, all the other code (INVALID_PAYLOAD / CONNECTION_FAILED) are ignored. The product stays in `approved` state, which means it will be always checked again on every store refresh.

But there are different reasons of the product being "unverified". It could be a connection error to the Apple service. It could be sandbox receipt sent to live server (or the other way around). Finally, it could be a result of custom validation logic, that says that this receipt is not valid.

It doesn't seem like we have the access to the error code. So, how should I know if the reason was the remote validation code not being able to connect to Apple Service vs remote validation code establishing by custom logic that receipt should not be valid?

And how do I react to that? Should I call `product.finish()` after receiving product.unverified event? Or should it always stay in the queue, even if the validation result will always be "unverified"? Note, that this would prevent the user from buying the product again (`canPurchase` is false in `approved` state)

**Comment by j3k0** [comment]
Plugins have a "retry" strategy that is indeed basic: it will retry validation 5 times (with ever increasing timeouts). If I'm correct, the 2 error codes that will stop it from retrying are CONSUMED and EXPIRED. (don't have the exact constants name in mind, you can dig them out). Other error codes indicates that the validation didn't went through, so the state of the transaction is still unknown: should not be finished.

**Comment by sebastian-zarzycki-es** [comment]
I fail to see how this answers my question. Could you be more precise?

**Comment by j3k0** [comment]
>  Should I call product.finish() after receiving product.unverified event?

No

> Or should it always stay in the queue, even if the validation result will always be "unverified"?

It won't stay in the queue if the validator returns EXPIRED or CONSUMED. It'll get back to the `valid` state and `canPurchase` will be true.

**Comment by sebastian-zarzycki-es** [comment]
Thank you.
