### ISSUE TITLE
[Android] com.android.vending.billing does not exist

### ISSUE THREAD

**Issue by josiahbryan** [j3k0/cordova-plugin-purchase#803]
### system info

Using Adobe PhoneGap build, phonegap 8.1.1 via the following in `config.xml`:
`<preference name="phonegap-version"  value="cli-8.1.1" />`

Using version 7.4.3 of the plugin via the following in `config.xml`:
`<gap:plugin name="cc.fovea.cordova.purchase" source="npm" version="7.4.3">`

### Expected behavior
Successful build

### Observed behavior
**Error**: **package com.android.vending.billing does not exist**

Relevant section of the logs:
```
:app:compileReleaseJavaWithJavac/var/gimlet/tmp/47363360608820/3486871/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/var/gimlet/tmp/47363360608820/3486871/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/var/gimlet/tmp/47363360608820/3486871/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
```

### Steps to reproduce
* Use cli-8.1.1
* Add plugin ver 7.4.3
* Build via PhoneGap build
* Build fails

**Comment by josiahbryan** [comment]
Note, I also tried using the plugin straight from this git repo (HEAD), tried forking this git repo and editing plugin.xml directly to change aidl install path, and tried installing the aidl manually in my config.xml - NOTHING has helped.

**Comment by Dexus** [comment]
PhoneGap is not supported.

Regards, Dexus

**Comment by josiahbryan** [comment]
What do you mean ...? The main README documents installing the plugin in PhoneGap build ...
https://github.com/j3k0/cordova-plugin-purchase#install-the-plugin-phonegap-build

**Comment by josiahbryan** [comment]
And the summary specifically mentions PhoneGap: https://github.com/j3k0/cordova-plugin-purchase#summary

**Comment by Dexus** [comment]
Believe it or let it be, it’s your turn. 
You can look in the other issues.

PhoneGap only has work on older versions, but not with newer then the Major Version of 6.

**Comment by Dexus** [comment]
Closes #803
Reason: Duplicate: #759, #760 and others

To compile with PGB, you should contact the developers there to support newer versions. Otherwise there won't be any new support from us for PGB.

**Comment by josiahbryan** [comment]
Support newer versions of what? What does phonegap Build need to change and
support newer versions of?

**Comment by josiahbryan** [comment]
If anyone finds this message in the future, here's what I did to **actually get IAP working with PhoneGap Build**:

Most importantly, I had to use **https://github.com/lilmnm-kamikaze-/customIAP** as the IAP plugin.
Which itself is a fork of `cordova-plugin-inapppurchase` to make it compatible with PGB.

Also, I had to target cli-8.0.0:
`<preference name="phonegap-version" value="cli-8.0.0" />`

Also, I had to carefully tweak the versions of a couple other popular plugins to be compatible and play nice together:

This is the combo that finally worked for `cli-8.0.0`:

```xml
	<plugin name="phonegap-plugin-push" source="npm" spec="2.1.2">
	 	<variable name="FCM_VERSION" value="11.0.1" />
	</plugin>

	<plugin name="cordova-plugin-admobpro-firebase" source="npm">
		<variable name="PLAY_SERVICES_VERSION" value="11.0.1" />
	</plugin>

	<plugin spec="https://github.com/lilmnm-kamikaze-/customIAP.git" source="git" />

	<config-file platform="android" parent="/manifest" mode="merge">
		<uses-permission android:name="com.android.vending.BILLING" />
	</config-file>
```

If anyone has specific questions, feel free to email me directly at josiahbryan@gmail.com
