### ISSUE TITLE
[WINDOWS] Support subscriptions in windows store / Use Windows.Services.Store namespace

### ISSUE THREAD

**Issue by dominic-simplan** [j3k0/cordova-plugin-purchase#805]
Currently the plugin only supports in-app-purchases with the Windows Store, but no subscriptions as far as I can see.
Would be great if Windows Store subscriptions were possible with this plugin, however it seems that subscriptions are only supported when the "Windows.Services.Store" namespace is used (see https://docs.microsoft.com/windows/uwp/monetize/in-app-purchases-and-trials#basic-concepts). Currently, though, this plugin [seems to use](https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/windows/InAppPurchaseProxy.js#L42) the legacy "Windows.ApplicationModel.Store" namespace, so it might be a little bit more work to get the subscriptions working?

**Comment by j3k0** [comment]
Ref #811 - subscriptions are supported on this branch (work in progress, but seems to be working for subscriptions without server-side validation).
