### ISSUE TITLE
[iOS] Unable to tell if product is expired

### ISSUE THREAD

**Issue by selected-pixel-jameson** [j3k0/cordova-plugin-purchase#806]
Hello,

I'm implementing auto renewing subscriptions through iOS using this library. I have everything working correctly, but I'm unable to find a state where the product returns a value with ```expired:true```. I have seen this value come through when I have the verbosity set to debug. But when I log the product from within the different listeners I never see this value. On top of that I do see these values. 

```"canPurchase":false,"owned":true,```

These values lead you to believe that the subscription is indeed NOT expired. However, when I go through the purchasing process I'm able to purchase / renew the subscription. It would be nice to have an explicit value to go off of so that you can reflect this in the UI.  Maybe I'm just looking in the wrong place, I hope that's the case.

Thank you.

**Comment by selected-pixel-jameson** [comment]
I'm not positive. This isn't extremely clear in the documentation, but it appears as if you are supposed to return an expired state from your verification endpoint and return it in the callback like such. 

```callback(false,{code:this.store.PURCHASE_EXPIRED, error:{message:"Purchase Expired"}})```

This will then throw an error with a specific code so you could tell that the subscription is expired.

**Comment by j3k0** [comment]
Yes, expiry date is not available client side, you need a receipt validator to check it server-side. I don't know how far you're into it, just know that we offer this as-a-service. https://billing.fovea.cc/ -- just in case.
