### ISSUE TITLE
[ANDROID] How to determine whether Google Play Billing is available?

### ISSUE THREAD

**Issue by joemckie** [j3k0/cordova-plugin-purchase#807]
This is a general question about the plugin as a whole.

As some versions of Android don't have GPB enabled, how can I get this information so that we can determine whether Google Pay is a billing option?

Thanks

**Comment by j3k0** [comment]
On Android, there isn't a way to tell if the Play is globally available or not. But if the products fail to load, they cannot be purchased (each product have a `canPurchase` boolean). Is this enough for this use case?
