### ISSUE TITLE
[IOS/ANDROID] - Call Validator Explicitly for Cross-Platform Support

### ISSUE THREAD

**Issue by adaoust** [j3k0/cordova-plugin-purchase#812]
### system info

```
macOS Mojave 10.14.3 (18D109)
Cordova: Same on all
Device: Any
Plugin Version: 7.4.3
```

### Expected behavior / Observed behavior / Steps to reproduce

I am using a custom cross-platform validator that uses the product id and the current user id to verify if the subscription is active, however I cannot call verify() for the product without the user having purchased the subscription on the current platform.

e.g.
1. User buys subscription on Android. A transaction is created and the validation occurs on Android (good).
2. User logs in to their iOS device, products are registered, but cannot be verified(). I tried to call verify() once the products are registered to force a validation/update from the backend, but I get the following error:  {"code":6777017,"message":"Product isn't in the APPROVED state"} - the product can't be in the APPROVED state on that platform since the user bought the product on another platform.

### Note

My custom validator can process receipts from both Android and iOS and if I explicitly call it outside of this plugin's validator, I can get wether the user has an active subscription or not (this is possible because the validator stores the transaction receipt in the backend, therefore it can validate even if product.transaction is null upon being called), but I believe I should be able to integrate my validator with this plugin, so that product.owned reflects the appropriate state for the user.

### (EDIT)

~~Just noticed there's a trigger(action: string, args: any) method, could I possible use this to bypass some interval validation and directly call the validator?~~

### (EDIT 2)

Managed to successfully call the validator by adding `product.state = this.iap.APPROVED;` to my valid listener. Still feels like a bit of a hack.

```
private valid = (product: IAPProduct) => {
    console.log(SubscriptionService.LOG_PREFIX + 'valid', JSON.stringify(product));
    product.state = this.iap.APPROVED;
    product.verify();
};
```

**Comment by j3k0** [comment]
I think you shouldn't hack into the plugin's internal like this. The plugin only manages which products are owned on the platform the app is running onto, for the platform user (i.e. iTunes / Google account).

If you have a higher level "user" concept, you should have your own API layer built above the plugin's API to manage user-product's ownership and not hack this into the low-level API of this plugins.

**Comment by adaoust** [comment]
I agree, just wanted to see if there was a way I could integrate with the plugin's API.

Thanks for the help!
