### ISSUE TITLE
Unregister handlers

### ISSUE THREAD

**Issue by francoisduchemin** [j3k0/cordova-plugin-purchase#813]
I am working on an Ionic app with a very simple "Remove ads" in-app purchase. One of the pages displays the products along with a "Buy now" button.

Everything is working fine the **first time** the page is loaded: the `updated` callback is called and the products are displayed. But if the user navigates to another page, and then comes back, the handlers are not called anymore (`productUpdated` is not called in the code below).

Here's what I'm doing:

```
ngOnInit() {
  const product: IAPProductOptions = { ... };
  this.store.register(product);
  this.store.when(this.productId).updated(this.productUpdated);
  this.store.refresh();
}

ngOnDestroy() {
  this.store.off(this.productUpdated);
}

private productUpdated: IAPQueryCallback = (product: IAPProduct) => {
  this.loader.dismiss();
  this.products.push(product); // updates the UI
  ...
};
```

Do I need to unregister something else? Unregister the product somehow? Am I forgetting something?

**Comment by j3k0** [comment]
I'm assuming `ngOnInit()` is called when the view is shown and not when the app starts. You have to register the products and handlers as soon as the app starts and never unregister them again. One thing to keep in mind: in-app purchase events can occur at any time, outside of your control.

This have been discussed time and time again: an order can be initiated from another device / from the AppStore itself, and have to be finalized when your app starts (or gets back from background).

That is Apple/Google requirements, it's stated black and white on their respective documentations.

**Comment by j3k0** [comment]
Also, `productUpdated` is gonna be called way more than 1 time... So if you're pushing the product each time, it might get ugly ;-)

**Comment by j3k0** [comment]
And just a doubt: do you need the fat arrow `=>` for productUpdated (not sure if you're not messing up the value of `this` with this)

**Comment by francoisduchemin** [comment]
Thank you so much for your fast reply @j3k0 !!

- I have some logic in `productUpdated` to check if the product has already been received, and if so only update it.
- The fat arrow is exactly to bind `this` :)
- So you're saying I should register the products and handlers when the app starts. I'm doing it completely wrong then! Until now I was doing this initialization when the page was loaded (and you're right, this can happen multiple times). But then it means that I have to call `this.store.refresh()` when the app starts (just after registering the product and the handlers), right? Will `this.store.refresh()` not trigger a popup (especially on iOS devices) to ask the user to enter his credentials when the app is starting?

**Comment by j3k0** [comment]
> I have to call this.store.refresh() when the app starts (just after registering the product and the handlers), right?

Right.

> Will this.store.refresh() not trigger a popup (especially on iOS devices) to ask the user to enter his credentials when the app is starting?

Nope, except if you're doing subscriptions and your receipt validator doesn't make use of the `latest_receipt_info` field (which isn't your case).

**Comment by francoisduchemin** [comment]
Perfect I'm going to change my implementation accordingly! Thanks a lot. I guess you can close the "issue" (which was not really an issue, more a mistake from my side)

**Comment by j3k0** [comment]
Good luck!

**Comment by wongwideweb** [comment]
Can you post your final solution, please?

**Comment by wongwideweb** [comment]
> Perfect I'm going to change my implementation accordingly! Thanks a lot. I guess you can close the "issue" (which was not really an issue, more a mistake from my side)

Hi there Franco, can you post the final solution to your code here?
