### ISSUE TITLE
[IOS] undefined is not an object (evaluating 'e.transaction')

### ISSUE THREAD

**Issue by albertleao** [j3k0/cordova-plugin-purchase#814]
### system info
```
OSX Mojave 10.14.3
Cordova 7.1.0.
Device: iPhone iOS 12.1.4
Plugin Version: 7.4.3
```

### Observed behavior
After calling store.refresh(), I'm seeing the following error.
`TypeError: undefined is not an object (evaluating 'e.transaction')  store-ios.js:1892`

### Steps to reproduce
Subscribe to monthly subscription plan. Validate with a back end server. call store.refresh()

I'm not sure if this is a serious issue or not but wanted to make sure before deploying this to a production environment.

**Comment by albertleao** [comment]
<img width="1269" alt="Screenshot 2019-03-25 01 13 04" src="https://user-images.githubusercontent.com/1950338/54896581-55ecf200-4e9b-11e9-9167-65e61e43b743.png">

**Comment by Dexus** [comment]
can you provide a screen on the full stacktrace of the error?

because I can't reproduce this currently in my dev @albertleao

**Comment by albertleao** [comment]
Hey @Dexus It's so random I haven't been able to reproduce it, but if I do, I'll post it here.

I don't know if it's related or not, but in my iOS sandbox environment, I get a `product.owned = true` and `product.canPurchase = false` even though my receipt has long expired when I do my server side validation. This is after I register using` product.register(//product info)` and doing a `store.refresh()`

Any ideas?

**Comment by j3k0** [comment]
Hey @albertleao ,

`e.transaction` code isn't found in the plugin code. I believe it's an exception thrown in one of your own callbacks.

The `owned` status should work. You can try using https://billing.fovea.cc as a receipt validator to make sure the problem isn't part of your own server.

**Comment by albertleao** [comment]
Thanks @j3k0 I'll look into that.

Where in the documentation can I find what kind of response is expected from the receipt validator?
