### ISSUE TITLE
[ANDROID] Store.ready not triggered on Android < 8.1

### ISSUE THREAD

**Issue by mathieu21** [j3k0/cordova-plugin-purchase#815]
### system info

Android 7.0 - 7.1 - 8.0
Cordova 8.1.2 - 9.0
Plugin version : 7.4.3

### Description of the issue

I have been using these plugin for a while now but recently I figured that it is not working on all platforms anymore.

I was running on cordova 8.1.2 and got the same behavior on 9.0. 

Basically store.order() doesn't trigger anything below Android 8.1 and it works great above.
What I note is that store.ready is never triggered on version of Android < 8.1.

There is no error in the console appearing so far.

I attached my code for reference:

### code

```
function RegisterProduct() {

	store.register({
		id:    "1month_sub_2.99",
		alias: "1 mois",
		type:  store.PAID_SUBSCRIPTION
	});

	productInApp1 = store.get("1month_sub_2.99");

	store.ready(function () {
        console.log("STORE READY");
    }); 

	store.when("1month_sub_2.99").approved(function(res) {
		alert('Product purchased');
	});	

	store.refresh();
       console.log(JSON.stringify(store));
}


function Onemonth(){
	store.order("1month_sub_2.99");
}
```

RegisterProduct() is triggered on device.ready
Onemonth() is triggered on click of the buy button

**Comment by Dexus** [comment]
Hi @mathieu21,

Please provide the console debug output of your failing devices.

This would help us, but I can‘t confirm currently your problem with my current apps. That are updated yesterday.

Regards

**Comment by mathieu21** [comment]
Hi @Dexus,

Do you mean the console of the store variable or?

**Comment by Dexus** [comment]
@mathieu21 i mean the catlog from adb/android studio

Von meinem iPhone gesendet

**Comment by mathieu21** [comment]
here is the catlog on store.refresh();

`[INFO:CONSOLE(133)] "{"verbosity":3,"sandbox":false,"FREE_SUBSCRIPTION":"free subscription","PAID_SUBSCRIPTION":"paid subscription","NON_RENEWING_SUBSCRIPTION":"non renewing subscription","CONSUMABLE":"consumable","NON_CONSUMABLE":"non consumable","ERR_SETUP":6777001,"ERR_LOAD":6777002,"ERR_PURCHASE":6777003,"ERR_LOAD_RECEIPTS":6777004,"ERR_CLIENT_INVALID":6777005,"ERR_PAYMENT_CANCELLED":6777006,"ERR_PAYMENT_INVALID":6777007,"ERR_PAYMENT_NOT_ALLOWED":6777008,"ERR_UNKNOWN":6777010,"ERR_REFRESH_RECEIPTS":6777011,"ERR_INVALID_PRODUCT_ID":6777012,"ERR_FINISH":6777013,"ERR_COMMUNICATION":6777014,"ERR_SUBSCRIPTIONS_NOT_AVAILABLE":6777015,"ERR_MISSING_TOKEN":6777016,"ERR_VERIFICATION_FAILED":6777017,"ERR_BAD_RESPONSE":6777018,"ERR_REFRESH":6777019,"ERR_PAYMENT_EXPIRED":6777020,"ERR_DOWNLOAD":6777021,"ERR_SUBSCRIPTION_UPDATE_NOT_AVAILABLE":6777022,"REGISTERED":"registered","INVALID":"invalid","VALID":"valid","REQUESTED":"requested","INITIATED":"initiated","APPROVED":"approved","FINISHED":"finished","OWNED":"owned","DOWNLOADING":"downloading","DOWNLOADED":"downloaded","QUIET":0,"ERROR":1,"WARNING":2,"INFO":3,"DEBUG":4,"INVALID_PAYLOAD":6778001,"CONNECTION_FAILED":6778002,"PURCHASE_EXPIRED":6778003,"validator":null,"log":{},"products":[{"id":"1month_sub_2.99","alias":"1 mois","type":"paid subscription","state":"registered","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null},{"id":"3months_sub_5.99","alias":"3 mois","type":"paid subscription","state":"registered","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null},{"id":"12months_sub_11.99","alias":"12 Mois","type":"paid subscription","state":"registered","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null},{"id":"life_premium","alias":"Premium à vie","type":"paid subscription","state":"registered","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null}],"_queries":{"callbacks":{"byQuery":{"refreshed":[{}],"re-refreshed":[{}],"requested":[{}],"finished":[{}],"12months_sub_11.99 approved":[{}],"life_premium approved":[{}],"3months_sub_5.99 approved":[{}],"1month_sub_2.99 approved":[{}]}}},"utils":{},"inappbilling":{"options":{"showLog":false}},"android":{"options":{"showLog":false}}}", source: file:///android_asset/www/functions/Premium.js (133)`

**Comment by mathieu21** [comment]
@Dexus on your apps which work fine, could you share your configuration? Cordova version/Plugin version/Android Version
As so far I have done lot of test on lot of different versions and it feels like it is an issue that is consistent on Android < 8.1
Thanks :)

**Comment by j3k0** [comment]
Hey mathieu,

Make sure you have maximal verbosity (store.DEBUG).... catlog should generate a lot of noise that might help understand what is going on. Please attach it as a txt file or something.

I can confirm that things work well on my test apps with Android 8.0

**Comment by mathieu21** [comment]
@j3k0 I attached the log i got on one android 8.0 and another one i got on a 9.0.

Thanks for your help


[storerefresh 9.0 .log](https://github.com/j3k0/cordova-plugin-purchase/files/3028423/storerefresh.9.0.log)
[storerefresh 8.0.log](https://github.com/j3k0/cordova-plugin-purchase/files/3028424/storerefresh.8.0.log)

**Comment by Dexus** [comment]
@mathieu21 can you try to factory reset your 8.0 device? Maybe you can look if it is allowed to make purchases (parent crontrol) etc.

**Comment by mathieu21** [comment]
@Dexus I ahev tried on physical devices (3) and virtual machines (4) with different configurations and version of Android and it is pattern linked to android version on my side :(

@j3k0 could you share your current cordova configuration that works on android 8.0?

**Comment by mathieu21** [comment]
Any version to share cordova/android/plugins tht I can check if it comes from there?

**Comment by j3k0** [comment]
Last time I did serious Android IAP, it was with:

* NodeJS v10.12.0
* Cordova v8.1.2
* macOS 10.14.1

Using the cordova plugin from the master branch.
