### ISSUE TITLE
[IOS] - Refresh finished event

### ISSUE THREAD

**Issue by ziadsarour** [j3k0/cordova-plugin-purchase#816]
Hello,

I've implemented a refreshed button in my app to restore purchases. The refresh process works perfectly but I want to display a spinner while the refresh is happening.

So my question is : is there an event that is fired at the end of the refresh process ?

I tried with "refreshed" and "re-refreshed" but those events are fired directly after the click, not at the end of the process.

Thank you for this plugin, you've made an incredible work for the community and developers like me who don't want to waste time learning 2 others languages for just some features !

**Comment by ziadsarour** [comment]
Found the solution => #228
I'm using the event "refresh-completed".

`store.when('refresh-completed', () => {})`

**Comment by j3k0** [comment]
Hey Ziad, sorry for not getting back in time. Note that `refresh-completed` is only triggered on iOS. It shouldn't be difficult to implement for Android too, I'll take a look at that.

**Comment by j3k0** [comment]
Ref fdf3ed3
