### ISSUE TITLE
Google Play Something went wrong on our end

### ISSUE THREAD

**Issue by ErxrilOwl** [j3k0/cordova-plugin-purchase#817]
I am trying this plugin on my app. But then when I click my purchase button it always said that. “Something went wrong on our end. Please try again”

![image](https://user-images.githubusercontent.com/19930568/55124716-290e3880-5142-11e9-9360-24da67f6143f.png)

Is there anything that I need to do? I already check some things like, verifying that the productId is correct and if its active. Using a test user, etc

**Comment by ErxrilOwl** [comment]
I already solve the problem. The app needs to be published on the play store.

**Comment by Ross-Rawlins** [comment]
@ErxrilOwl when you say publish, does it have to be live or wil lit work in beta and alpha testing as well?

**Comment by Dexus** [comment]
Beta/Alpha will work as well
