### ISSUE TITLE
Promotion Codes [IOS] [ANDROID]

### ISSUE THREAD

**Issue by justin-devs** [j3k0/cordova-plugin-purchase#818]
OSX Mojave 10.14.3
Meteor JS 1.8.1-beta.20
Device: iPhone iOS 10.3.2 // Android 7.1
Plugin Version: latest

Is there functionality for promotion codes?

**Comment by j3k0** [comment]
Yes, promo codes should just work, as there's nothing specific to be done in the app: they are redeemed outside the app.
