### ISSUE TITLE
[IOS] AppStoreReceipt null (with a 'fix/hack')

### ISSUE THREAD

**Issue by oofaish** [j3k0/cordova-plugin-purchase#819]
### system info
iOS 12.1,
iPhone XS
ionic 3.9.2
cc.fovea.cordova.purchase version 7.4.3 (also same issue with 7.2, so slightly older problem)

### Expected behavior
**IN PRODUCTION**
User has subscribed to a non-consuamble, auto renewing subscription
But then cancel their subscription.
Then wait a few weeks (might happen straight away too, not 100% sure)
If I go to restore purchase/check subscription, it should give me a receipt, that our validator should say is invalid, and we are done.

### Observed behaviour
Trying to restore purchase or check subscription, and refreshReceiptDelegate methods never get called. We get stuck here:

    2019-03-29 22:02:39.243971+0000 Wattson Blue[2081:360729] InAppPurchase[js]: refreshing appStoreReceipt
    2019-03-29 22:02:39.244309+0000 Wattson Blue[2081:360729] InAppPurchase[objc]: appStoreRefreshReceipt: Request to refresh app receipt
    2019-03-29 22:02:39.244402+0000 Wattson Blue[2081:360729] InAppPurchase[objc]: appStoreRefreshReceipt: Starting receipt refresh request...
    2019-03-29 22:02:39.245342+0000 Wattson Blue[2081:360729] InAppPurchase[objc]: appStoreRefreshReceipt: Receipt refresh request started

Neither the success or fail delegate get called.

### Steps to reproduce
As described above but only seems to happen in production currently, which is a bit of a disaster. Interestingly, if I comment out this line:

    storekit.setAppStoreReceipt(null);

in store-is.js, then a receipt is returned and correctly validated (or invalidated...)

this line was originally submitted due to this: https://github.com/j3k0/cordova-plugin-purchase/issues/374
 
Any thoughts on what's happening? I can definitely confirm that commenting that line out does the 'trick' - but then I fear commenting it out, will give me other issues? I will be very surprised if I am the only one with this issues.

Thoughts?

Thanks so much,

Ali

**Comment by oofaish** [comment]
Is anyone using @atake831's fix from the other thread (https://github.com/j3k0/cordova-plugin-purchase/issues/374#issuecomment-174882946)

**Comment by j3k0** [comment]
About this line...
```js
storekit.setAppStoreReceipt(null);
```

The plugin keeps the appStoreReceipt in localStorage (to prevent the user having to type her password each time we need to access it). This line is cleaning the cache, which is desired when doing "restore purchases", as we might now be a different user.

Relative to your problem, sounds more like a bug in the Apple's StoreKit SDK. I highly suspect the issue to be some weird state in your testing device. Have you tried with another device just in case. You can also try to just logout from iTunes before launching the app and trying again... Or factory reset the device if that's an option...

Is it something reproducible with multiple devices?

**Comment by oofaish** [comment]
Just to continue on the thread (really appreciate your help @j3k0)
- It's happening on the one production device - but it's a device where I have had sandbox environment on before, but currently it's happening on this device with a production version of the app running and a production iTunes connect account.

Here is how I have re-worked the code as things stand
(a) that line is commented out.
(b) setting window.storekit.appStoreReceipt = null when someone is explicitly is buying a product/trying to restore purchase before calling store.order/store.refresh. 

(i.e. the initial store refresh when app starts is called without appStoreReceipt set to null, and rest with)

and it seems to work ok (on this case and in a sandbox account on a different iPhone)

Any thoughts if (a) or (b) might have any unexpected results?

Cheers

Ali

**Comment by Dexus** [comment]
Hi @oofaish 

So I'd like to make sure it's really the problem and it's not just on one device.

Can you please provide more information about when the problem occurs so that we can recreate it?

Since I've never had this problem before, I'm a little skeptical.

**Comment by oofaish** [comment]
Hey @Dexus 
> Was the device reset before?
I am pretty sure I did (as for a few days I practically tried everything, kill app, reinstall, logout of iTunes, etc, etc), but can't be 100% sure.

What I have done for now is that if user taps restore, I clear out the cache manually on second try of restore (by accessing windows.storekit....)  - this means the products seem to load OK initially, and then I do restore and it works...

> Can you please provide more information about when the problem occurs so that we can recreate it?
As I mentioned, the original issue was when the subscription had expired - so I am going to wait for my current production subscription to expire and then I will post on here if it happens with the line not commented out, so I would say watch this space...

Cheers

Ali

**Comment by j3k0** [comment]
Hey @oofaish 

It's been a while, do you remember how this story ended? Thanks!

**Comment by oofaish** [comment]
I am still using the patch I mentioned above (https://github.com/j3k0/cordova-plugin-purchase/issues/819#issuecomment-478393008)
though @j3k0 I wonder the issue I emailed you about (where my user's purchase was not hitting your verify server) is potentially related? I forced the app to check the user's purchases and finally his app hit the 'verified' and 'owned' callbacks. Really unsure what happened. 

If you think the issue could be related to my patch (i.e. storekit.setAppStoreReceipt(null); commented out), I ll be tempted to revert my patch...

Thanks again for being a kick ass dev mate! ❤️

**Comment by aesculus** [comment]
I am not sure if this is related or not as I have not been able to correlate this on the device side. But, on my php server validation module I occasionally run into this error:
`Trying to get property 'transaction' of non-object`
where the code is:
`$postdata = file_get_contents("php://input");
	$data = json_decode($postdata);
	if ($data->{'transaction'}->{'type'}=='ios-appstore') {`
