### ISSUE TITLE
Prereq Cordova Versions by Release

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#822]
Can you point me to where a plugins prerequisite versions of the cordova platforms is listed?

For example I think that 7.2.4 needs:
ios 4.5.5
Android 7.1.4

But I am not certain. This would help me figure out the minimum CLI to match up to the plugin release.

**Comment by aesculus** [comment]
Just posting a tickler comment to make sure this was not overlooked.

**Comment by j3k0** [comment]
Sorry I never maintained a compatibility matrix...

For the latest version, 8.0.0. We tested:

 * cordova-android 6.4.0, 7.1.0, 7.1.4, 8.0.0.
    * 2 versions are known to fail: 7.1.1 and 7.1.2, a bug fix in cordova-android@7.1.1 created other issues, like breaking a few plugins installation (including this one).
 * cordova-ios 4.5.5 and 5.0.1
 * cordova-osx 4.5.5 and 5.0.0
 * cordova-windows 7.0.0

**Comment by aesculus** [comment]
Thanks. This is very helpful.  With this I can now see it's safe to go into the water with 8.0.0 as I was caught in the android bug prior to 8.

Could you possibly attach the same whenever you do a major release again?

**Comment by j3k0** [comment]
Yes it will be easier: now that I setup a more more extensive test-matrix on Travis-CI https://github.com/j3k0/cordova-plugin-purchase/blob/master/.travis.yml

**Comment by aesculus** [comment]
:-)
