### ISSUE TITLE
error integrate in-app purchase ionic 3

### ISSUE THREAD

**Issue by christiantigre** [j3k0/cordova-plugin-purchase#835]
# !!! PLEASE HELPME!!!

I have my app on ionic-v3. I’m integrating ina-app purchase https://github.com/j3k0/cordova-plugin-purchase
but when installing it with cordova plugin add cordova-plugin-purchase --variable BILLING_KEY = “my-key” my project removes the native libraries even the splash and the generated imaneges all return to the splash images even icons defaults to ionic. How could I integrate this library if I have problems, and without my project?

**Comment by Dexus** [comment]
Please provide the steps you make, so we can try to reproduce it.

Without it, we have to be psychic, and we're not.

**Comment by j3k0** [comment]
No information provided...
