### ISSUE TITLE
[IOS/ANDROID] - expiryDate attribute not found in the product object

### ISSUE THREAD

**Issue by SVANNER** [j3k0/cordova-plugin-purchase#837]
Linux UBUNTU 16.04

### Expected behavior
Using Ionic V4, having the attribute expiryDate of the product in VS Code
 
### Observed behavior
The expiryDate Attribute is not part of the IAPProduct object in VSCode

### Steps to reproduce
install plugin:
ionic cordova plugin add cc.fovea.cordova.purchase
npm install @ionic-native/in-app-purchase-2

in a page,
import { IAPProduct, InAppPurchase2 } from '@ionic-native/in-app-purchase-2/ngx';
Declare a IAPProduct object
try to use the expiryDate in the editor

**Comment by j3k0** [comment]
It's probably a problem with the ionic-native layer: https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/in-app-purchase-2/index.ts

Seems like they do not support `expiryDate`. I'm not an ionic developer, but I guess adding support for this field should be pretty straightforward.

**Comment by j3k0** [comment]
I submitted a PR to ionic that adds the definition of the missing fields. https://github.com/ionic-team/ionic-native/pull/3037 -- should work as soon as they integrate it. I will close since it's now in their hands.

**Comment by phuwin** [comment]
@j3k0 For iOS,  I'm having the same issue that there is no `expiryDate` in subscription product object, I'm using cordova `9.0.0`, ios engine is `4.5.5`. I test with sandbox mode. No transaction object either. iOS version is `12.3.1`.
I wonder if it's because it's sandbox mode?

**Comment by j3k0** [comment]
On iOS, expiryDate isn't set unless you use a compatible receipt 
validation service. For subscriptions, it's basically a requirement.

You can check out https://billing.fovea.cc/ or create your own.

**Comment by phuwin** [comment]
> On iOS, expiryDate isn't set unless you use a compatible receipt validation service. For subscriptions, it's basically a requirement. You can check out https://billing.fovea.cc/ or create your own.

Does Android automatically (without a validation service) have this `expiryDate` in `product` object?

**Comment by j3k0** [comment]
If I'm correct it does (since a recent update). To correctly detect 
cancellation and attempt to use fake receipt generators it's still a 
good idea to integrate server side receipt validation.
