### ISSUE TITLE
[ANDROID] Build fails on newer Phonegap CLI Versions

### ISSUE THREAD

**Issue by tobspr** [j3k0/cordova-plugin-purchase#838]
### system info

Phonegap Build CLI 8.1.1 (-> Cordova Android  7.1.2)
Latest Plugin Version (7.4.3)

### Expected behavior

The app should compile without errors.

### Observed behavior

The app compiles with the following error (Full: https://pastebin.com/kY1RLVFK):

```
:app:compileDebugJavaWithJavac/var/gimlet/tmp/47075166131680/3339820/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/var/gimlet/tmp/47075166131680/3339820/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/var/gimlet/tmp/47075166131680/3339820/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /var/gimlet/tmp/47075166131680/3339820/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
 FAILED
```

### Steps to reproduce

Create a new phonegap build project, add the plugin and use the latest CLI  (Or 8.0.0)
   `<preference name="phonegap-version" value="cli-8.1.1" />`

The plugin compiles fine with the version 6 / 7 CLI.

I really need the plugin to work on this platform. If this helps, I'd be willing to donate a bit.

**Comment by rsevil** [comment]
+1

I'm experiencing the same issue here.

**Comment by j3k0** [comment]
`cordova-android@7.1.1` introduced a regression in plugins installation procedure. `7.1.2` fixed this but created other issues.

If you have to use `cordova-android@7.1.2`, you can use the plugin at version `7.2.5` which implemented a workaround (which itself breaks the installation with cordova-android > 7.1.2)

**Comment by RezaRahmati** [comment]
I am using cordova 8.0.0 and same issue
