### ISSUE TITLE
[IOS] any need for developers to implement any thing for purchases initiated through app store?

### ISSUE THREAD

**Issue by shepsii** [j3k0/cordova-plugin-purchase#840]
I found this commit: https://github.com/j3k0/cordova-plugin-purchase/pull/637/files and just wanted to check: in order to correctly process IAPs initiated through the iOS App store, there is no need for developers to do anything extra?

TIA!

**Comment by j3k0** [comment]
Nope, just make sure you register events handler and call `store.refresh()` when your app starts.
