### ISSUE TITLE
Error DF-DFERH-01 trying to complete the purchase

### ISSUE THREAD

**Issue by yoprogramo** [j3k0/cordova-plugin-purchase#841]
We have an app that allows monthly and yearly subscriptions and when we try to buy the subscription we receive this error:

"Error while retrieving information from server DF-DFERH-01 "

We have tried different versions of Android (7,8, and 9) in different devices. The curious thing is we have completed some purchases one month ago with the same exact code.

**Comment by j3k0** [comment]
Internet has a couple of checklists for this problem. Like this: https://appuals.com/google-play-store-error-df-dferh-01/

This doesn't appear to be something we have to fix in the code/plugin. Let us know!

**Comment by yoprogramo** [comment]
Good news! uploading the app to beta (even if you have a previous version in production channel it is needed) it is working now.

Thank you for the support
