### ISSUE TITLE
[iOS]: receiving same transaction queue for different Apple IDs after store.refresh() 

### ISSUE THREAD

**Issue by EvelinJK** [j3k0/cordova-plugin-purchase#842]
### system info
```
OSX Mojave 10.14.4
Cordova 8.1.2
Device: iPhone XS and XS Max, iOS 12.2
Plugin Version: 7.2.9
```

Not quite sure if this is a sandbox issue only, but it makes testing virtually impossible for us. Any help would be appreciated.

**The general problem:**
On `store.refresh()` we receive pending transactions from purchases that have been made by a different Apple ID that was logged into the device previously. This obviously makes no sense, since a purchase should only be connected to a specific Apple ID / test user.

We tried this by logging into the device itself as well as the 'Sandbox User' setting on the device with a different Apple ID. So there should be nothing on the phone anymore that connects to another Apple ID and its previous purchases.

This happens with Sandbox test users, we could not test with real purchases so far.

It almost seems like the purchases are connected to the device instead of the Apple ID / test user and this makes no sense.

### Expected behavior
When I sign in with a new test user / Apple ID on the device and as Sandbox, I expect the transaction queue to be empty.

### Observed behavior
New test user receives transaction queue of previously logged in user(s) on store.refresh()

### Steps to reproduce
1) Apple ID 1 makes purchases via plugin that cannot be validated and stays in transaction queue. 
1.2) Apple ID 1 logges out of device and as sandbox user.
1.3) App is deleted from device (just to be sure)

2) Apple ID 2 logges into device and as sandbox user.
2.1) App gets installed 
2.2.) User opens App
2.3) Apple ID 2 receives transaction queue with same unfinished transactions from Apple ID 1

**Comment by j3k0** [comment]
This is how StoreKit (Apple's low-level API) works, so nothing the plugin can do about. You have to handle and finish pending transactions, regardless of which Apple user made the purchase.

In dev, you can end up in a weird state with pending "invalid" transactions. This is a "sandbox" issue. You can cleanup you queue. See:

https://github.com/j3k0/cordova-plugin-purchase/blob/23bb20059ee951b343414f209c297b5509a0a3d7/doc/api.md#random-tips
