### ISSUE TITLE
 getting duplicate products from store

### ISSUE THREAD

**Issue by Isuru-nibaya** [j3k0/cordova-plugin-purchase#843]
This is my code and  i'm little bit confusing about the  documentation. please help me thank you

function initializeStore(dbProductIDList) {
   
    var products = [];
    for (var i = 0; i < dbProductIDList.length; i++) {
        store.register({
            id: dbProductIDList[i],
            type: store.CONSUMABLE
        });
    }
   
    store.refresh();

// Get products from store
    store.when("product").updated(function (product) {

        products.push(product); // getting duplicate records
     
    });

**Comment by j3k0** [comment]
`store.when("product").updated` will be called every time anything happens to the product. So you'll have far more than a duplicate.

Note that the store object already maintains the array of products. You can access them by id: `store.get(dbProductIDList[0])`
