### ISSUE TITLE
[ANDROID]: ANRs inside IabHelper.java

### ISSUE THREAD

**Issue by rj33** [j3k0/cordova-plugin-purchase#845]
I'm seeing various ANR reports from google coming from a call to isBillingSupported inside
onServiceConnected() from the IabHelper.java class.

Here is the report from google:
"main" tid=1 Native 
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x7408a7b0 self=0xa5f05400
  | sysTid=25996 nice=-10 cgrp=default sched=0/0 handle=0xa8c06534
  | state=S schedstat=( 3750021628 1329904891 10429 ) utm=291 stm=82 core=4 HZ=100
  | stack=0xbe37e000-0xbe380000 stackSize=8MB
  | held mutexes=
  #00  pc 0000000000048468  /system/lib/libc.so (__ioctl+8)
  #01  pc 000000000001aacf  /system/lib/libc.so (ioctl+38)
  #02  pc 000000000003cd65  /system/lib/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+168)
  #03  pc 000000000003d757  /system/lib/libbinder.so (_ZN7android14IPCThreadState15waitForResponseEPNS_6ParcelEPi+238)
  #04  pc 000000000003666d  /system/lib/libbinder.so (_ZN7android8BpBinder8transactEjRKNS_6ParcelEPS1_j+36)
  #05  pc 0000000000096e55  /system/lib/libandroid_runtime.so (???)
  #06  pc 00000000005f6be1  /system/framework/arm/boot-framework.oat (Java_android_os_BinderProxy_transactNative__ILandroid_os_Parcel_2Landroid_os_Parcel_2I+140)
  at android.os.BinderProxy.transactNative (Native method)
  at android.os.BinderProxy.transact (Binder.java:615)
  at com.android.vending.billing.IInAppBillingService$Stub$Proxy.isBillingSupported (IInAppBillingService.java:243)
  at com.smartmobilesoftware.util.IabHelper$1.onServiceConnected (IabHelper.java:240)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1465)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1482)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

These ANRs happen across multiple android versions and hardware. 

I suppose the billing check is getting done on the UI thread and is simply taking too long (probably waiting on the network), thus producing the ANR.

I haven't tested it myself yet, but the frostwire project have made several patches to IabHelper.java to resolve a few bugs, including this one (by using their own thread to launch the billing test thus not blocking the UI thread and so not producing an ANR). They have also got fixes for a few other issues including some crashes, which might be related to several closed-without-fixing issues for crashes others have raised against jdk0/cordova-plugin-purchase. 

They have moved on to using a newer billing framework last year, but you can still see their latest version of the IabHelper.java here, and it looks like it would be a good idea to integrate the updates from their version into the j3k0 purchase framework

https://github.com/frostwire/frostwire/blob/4d82da65900bee96b332b3b133b83cb99126eee3/android/src/com/android/vending/billing/IabHelper.java

**Comment by j3k0** [comment]
Hey @rj33. Good point. If you already made some research and can point me to the patches/commits in question, it'd be helpful! Thanks for the idea, good one :)

**Comment by j3k0** [comment]
Found the commit and backported to our code. See #847, @rj33 would you like to test it and confirm it solves the issue for you?

**Comment by j3k0** [comment]
(Closed in favor of the PR)

**Comment by rj33** [comment]
Hi @j3k0 Apologies for the late reply. It looks like you've already merged your change, I'll have a look at  upgrading to the latest version soon. Frostwire had a few older patches to that file made to fix issues before the thread issue that was generating the ANRs I was getting that might be worth also taking, sorry not sure of the patch details, I mainly did a visual comparison between their most recent IabHelper, and the one you had been using. 

Thanks for all your work on this project, just sent a donation via paypal as a small thank you.

**Comment by j3k0** [comment]
@rj33 Always glad to help!
