### ISSUE TITLE
[WINDOWS] refresh-completed event never triggered

### ISSUE THREAD

**Issue by dominic-simplan** [j3k0/cordova-plugin-purchase#846]
### system info
```
Windows 10
Cordova 8.0.1
Plugin Version: master
```

### Expected behavior
On the Windows platform, the 'refresh-completed' event should be triggered after a refresh.

### Observed behavior
The refresh-completed event is not triggered.

### Steps to reproduce
If I am not mistaken, the [iabGetPurchases](https://github.com/j3k0/cordova-plugin-purchase/blob/42d5083c5a0e7dd3979e7a4ecee2a2831e2d6647/www/store-windows.js#L2592) method is missing the callback parameter, which it should call after it has completed.

For example on the [re-refreshed](https://github.com/j3k0/cordova-plugin-purchase/blob/42d5083c5a0e7dd3979e7a4ecee2a2831e2d6647/www/store-windows.js#L2278) event a callback is passed to the iabGetPurchases method.

**Comment by j3k0** [comment]
Good catch, will attempt a fix right away.

**Comment by j3k0** [comment]
I don't have a windows testing environment available, but the fix is super straightforward. Can you confirm?

**Comment by dominic-simplan** [comment]
@j3k0 thanks for the fix! Is is possible that you also need to rebuild and push the www directory?

**Comment by j3k0** [comment]
@dominic-simplan Yup you're right 😆 Done!
