### ISSUE TITLE
iOS Production / Sandbox URL's

### ISSUE THREAD

**Issue by apmanomark** [j3k0/cordova-plugin-purchase#85]
Hi, does the plugin handle production and sandbox urls as apple suggest for ios purchases? I tried to look but cannot find the part of the code where it would be handled. Thanks.

> Always verify your receipt first with the production URL; proceed to verify with the sandbox URL if you receive a 21007 status code. Following this approach ensures that you do not have to switch between URLs while your application is being tested or reviewed in the sandbox or is live in the App Store.
> 
> https://developer.apple.com/library/ios/#technotes/tn2259/_index.html#//apple_ref/doc/uid/DTS40009578-CH1-FREQUENTLY_ASKED_QUESTIONS

**Comment by mepc36** [comment]
> Hi,
> 
> This is something you have to implement in your server (in case you develop your own receipt validation server).
> 
> If you're willing to use an external service for validation, it's in place in Fovea's receipt validation service http://reeceipt.fovea.cc

@j3k0 Are you saying that Fovea automatically handles switching between Apple's production and sandbox environments?

**Comment by j3k0** [comment]
@mepc36 Yes it does.
