### ISSUE TITLE
Unable to call store.call in Ionic 4

### ISSUE THREAD

**Issue by CharnjeetIotasol** [j3k0/cordova-plugin-purchase#850]
# [IOS]

### Expected behavior
UnRegister the callback

### Observed behavior
 But does not work

### Steps to reproduce

I am using the Ionic 4 application and I have set up the event for canceled and another event like this when every time product detail page has been opened

this.store.once(productId)
          .cancelled(this.cancelledEvent.bind(this));

cancelledEvent(error) {
    alert("Hree");
}

I have also store.off this event on ngOnDestroy like this:

ngOnDestroy(): void {
    this.store.off(this.cancelledEvent);
  }

But it is getting alert first time once then 2, 3 and 4.

**Comment by j3k0** [comment]
Because `this.cancelledEvent.bind(this) !== `this.cancelledEvent`.

You have to do (for example):

```js
this.boundCancelledEvent = this.cancelledEvent.bind(this);
this.store.once(productId).cancelled(this.boundCancelledEvent);
this.store.off(this.boundCancelledEvent);
```
