### ISSUE TITLE
how to test on ios?

### ISSUE THREAD

**Issue by vortechron** [j3k0/cordova-plugin-purchase#860]
im managed to buy in-app product on android, but cant get it to work on ios.

[ios] when i click buy button, nothing happen. 

one more thing that i dont understand. what is mean by:

Run your application in debug mode, on an actual device. (from https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO#setup-ios-applications)

**Comment by Dexus** [comment]
Did you already all administrative tasks at apple developer center?

If you not signed the financial contract etc you can’t work forwards.

Von meinem iPhone gesendet

**Comment by vortechron** [comment]
@Dexus financial contract? may i have the link?

**Comment by Dexus** [comment]
Check your Appel developer account!

Von meinem iPhone gesendet

**Comment by vortechron** [comment]
found it!, its under Agreement, Tax and Banking right ? @Dexus

**Comment by Dexus** [comment]
Sounds like you are not n the right way ;)

Von meinem iPhone gesendet

**Comment by vortechron** [comment]
fill in various forms under Agreement, Tax and Banking fix my issue. :))
