### ISSUE TITLE
Ionic Translation for Guide

### ISSUE THREAD

**Issue by plaidfox** [j3k0/cordova-plugin-purchase#864]
Anyone have an ionic v3 translation for the guide of this plugin? Specifically this page?

https://purchase.cordova.fovea.cc/use-cases/consumable-ios#initialization

Thanks!

**Comment by j3k0** [comment]
Hi. I'm in the process of learning ionic so I can. In the meantime maybe this blog post can answer part of your questions https://medium.com/@andrew.thielcole/in-app-purchases-with-ionic-3-af13b21f49f2

**Comment by plaidfox** [comment]
Thanks @j3k0. I'll take a look at that and see if I can get it working on this end.

If you could let me know when the guide is updated to include Ionic, that would be awesome.

Thanks for all your hard work on this plugin!
