### ISSUE TITLE
Multiple Errors When Attempting to Run Through Ionic [IOS]

### ISSUE THREAD

**Issue by plaidfox** [j3k0/cordova-plugin-purchase#865]
I'm attempting to follow along with the Ionic tutorial here: https://medium.com/@andrew.thielcole/in-app-purchases-with-ionic-3-af13b21f49f2 but I am running into a few errors when I try to run the code in xCode.

Here is my setup:

Ionic:

   Ionic CLI          : 5.0.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

Here is a part of my code that I'm using (I also can't figure out why GitHub will auto format some of my code but not all of it...):

  ngOnInit() {
    this.configurePurchasing();
  }

  configurePurchasing() {
    if (!this.platform.is('cordova')) { return; }
    let productId;
    try {
      if (this.platform.is('ios')) {
        console.log("Platform is ios");
        productId = this.ckProduct.appleProductId;
      } else if (this.platform.is('android')) {
        console.log("Platform is Android");
        productId = this.ckProduct.googleProductId;
      }

      // Register Product
      console.log('Registering Product ' + JSON.stringify(productId));
      // Set Debug High
      this.store.verbosity = this.store.DEBUG;
      console.log("Test 0");
      // Register the product with the store
      this.store.register({
        id: productId,
        alias: productId,
        type: this.store.NON_CONSUMABLE
      });
      console.log("Test 1");
      this.registerHandlers(productId);
      console.log("Test 2");
      InAppPurchase2.getPlugin().ready().then((status) => {
        console.log(JSON.stringify(this.store.get(productId)));
        console.log('Store is Ready: ' + JSON.stringify(status));
        console.log('Products: ' + JSON.stringify(this.store.products));
      });

      // Errors On The Specific Product
      this.store.when(productId).error( (error) => {
        alert('An Error Occured' + JSON.stringify(error));
      });
      // Refresh Always
      console.log('Refresh Store');
      this.store.refresh();
    } catch (err) {
      console.log('Error On Store Issues' + JSON.stringify(err));
    }
  }

  registerHandlers(productId) {
    console.log("RegisterHandlers: "+productId);
    // Handlers
    this.store.when(productId).approved( (product: IAPProduct) => {
      // Purchase was approved
      product.finish();
    });

    this.store.when(productId).registered( (product: IAPProduct) => {
      console.log('Registered: ' + JSON.stringify(product));
    });

    this.store.when(productId).updated( (product: IAPProduct) => {
      console.log('Loaded' + JSON.stringify(product));
    });

    this.store.when(productId).cancelled( (product) => {
      alert('Purchase was Cancelled');
    });

    // Overall Store Error
    this.store.error( (err) => {
      alert('Store Error ' + JSON.stringify(err));
    });
  }

And here are the errors I'm seeing in xCode:

2019-05-29 21:30:13.069000-0400 App Name[4755:133185] InAppPurchase[objc] (before init): WARNING: Your app should be single page to use in-app-purchases. onReset is not supported.
2019-05-29 21:30:13.823095-0400 App Name[4755:133185] Ionic Native: deviceready event fired after 466 ms
2019-05-29 21:30:16.971653-0400 App Name[4755:133185] Platform is ios
2019-05-29 21:30:16.971960-0400 App Name[4755:133185] Registering Product "1460624055"
2019-05-29 21:30:16.972305-0400 App Name[4755:133185] Error On Store Issues{"line":90406,"column":113,"sourceURL":"ionic://localhost/build/vendor.js"}

As you can see, not all of my console.log lines are appearing. My app uses multiple pages (each with it's own html, ts, scss files). Is that going to be an issue? Do I need to somehow load this code initially before anything else is loaded?

Any thoughts on how I should continue would be greatly appreciated.

Thank you.

**Comment by j3k0** [comment]
As you might have seen as a warning when the app starts: the plugin does 
not support apps that aren't single page.

Each time your app changes from one HTML file to another, the full 
javascript state is lost (your handlers, the flow of purchases in 
progress, status of products, etc...)

If you're seeing the warning multiple times, it means you have a 
problem. If the warning is seen just once, you're probably fine.

**Comment by plaidfox** [comment]
Ah, gotcha. Well, luckily I've only seen the warning once, so I think I'm all set.

For testing, do I need to be uploading the build to Apple and setting up testflight with my test users in order to see it in action? Or should it be working properly in xCode if I have the code setup right?

**Comment by j3k0** [comment]
It should be working properly in XCode. (if you run it on a device, and build it with the correct Team)
