### ISSUE TITLE
IiOS] Multiple purchases triggered by store.refresh() 

### ISSUE THREAD

**Issue by yonathanseleshi** [j3k0/cordova-plugin-purchase#867]
### system info

 Ionic ios app.

angular: 5.2.11
ionic/core: 4.11
"@ionic-native/in-app-purchase-2": "^4.7.0"
"cordova-plugin-inapppurchase": "^1.2.0"
 "cordova-ios": "5.0.1"
"cc.fovea.cordova.purchase": "^7.4.3",
"cordova-android": "7.1.0",

### Expected behavior

I am selling 3 subscriptions with my app.  1 monthly auto-renewing subscription, a non-renewing 6 month, and a non-renewing 12 month subscription.  I need the purchase to process only one transaction at a time.  I am using a backend php api to process the transactions and update my subscriptions in my database, so having all the transactions process at once triggers multiple subscription updates to my database adding extra months to user's subscriptions.

### Observed behavior

When testing the plugin on iOS(sandbox environment) I am noticing several purchases are processed, which are basically all the old purchases plus the current purchase.  This appears to be the result of the store.refresh() call, which pulls all the old transactions and runs them again.

I saw that there was a call that used to be made to store.autoFinishTransactions = true, but that appears to no longer be available.  Is there a work around for this now?

below is a screenshot of all the old transactions loading.  They are later all processed at once.

<img width="993" alt="Screen Shot 2019-06-05 at 9 14 37 AM" src="https://user-images.githubusercontent.com/10171857/58975185-3b77a480-8779-11e9-8c20-746c730997b9.png">

**Comment by j3k0** [comment]
On iOS, StoreKit will trigger an event for all pending transactions (those that haven't been finished).

You'll get an `approved()` event for all those transaction on each start, until you finish them properly. This is generally an issue that only pops up on development devices, you can clear the queue by setting `store.autoFinishTransactions` to true before the initial call to `store.refresh()`, as far as I know this option is still available.

**Comment by yonathanseleshi** [comment]
The autoFinishTransactions property does not appear to be available.  Am I missing something maybe?

<img width="668" alt="Screen Shot 2019-06-06 at 5 11 12 PM" src="https://user-images.githubusercontent.com/10171857/59073940-1fa9f680-887e-11e9-93c6-6c68da6358ee.png">

**Comment by yonathanseleshi** [comment]
I got it.  Just need to update the version.
