### ISSUE TITLE
store.get() doesn't retrieve the product information

### ISSUE THREAD

**Issue by theunreal** [j3k0/cordova-plugin-purchase#869]
Not sure if I did something wrong, but I can't get the description, price and the product metadata.

My code is simple (Angular):

```
constructor(private store: InAppPurchase2) {
this.products = [{
            id: '10',
            alias: 'ITEM 1',
            type: store.CONSUMABLE
        }, {
            id: '11',
            alias: 'ITEM 2',
            type: store.CONSUMABLE
        }, {
            id: '12',
            alias: 'ITEM 3',
            type: store.CONSUMABLE
        }];
        if (this.platform.is('mobile')) {
            this.products.forEach(product => {
                console.log('Trying to register', product);
                store.register(product);
            });
            store.refresh();
}

ngOnInit() {
if (this.platform.is('mobile')) {
            console.log('Trying to get premium items!');
            this.premium_products = this.products.map(product => this.store.get(product.alias));
            console.log('More info about it?', this.premium_products);
            this.store.when(this.premium_products[0].id).updated(() => {
                console.log(this.store.get(this.premium_products[0].id));
                console.log(this.store.get(this.premium_products[0].alias));
            });
        }
}
```

The output is the same info I gave to the register function(), and the state is registered.
The code inside the when() method is not triggered.

**Comment by j3k0** [comment]
I'm not surprised that the state is `registered` and content equal to whatever you gave to `register()`: loading product info will take some time, and will happen a while after you run through the list of products.

Some tips:

 - you can call `register()` with an array of product (no need for `forEach`).
 - `this.store.products` already contains the array of products (you probably don't need to maintain your own copy of the product: keep a single source of truth)
 - setup your listeners before calling `refresh()`. Move `store.refresh();` to the end of the constructor function
 - setup an `error` listener so you can console log whatever bad happens. In 99% of cases, a misconfiguration of some sort.

**Comment by theunreal** [comment]
> I'm not surprised that the state is `registered` and content equal to whatever you gave to `register()`: loading product info will take some time, and will happen a while after you run through the list of products.
> 
> Some tips:
> 
> * you can call `register()` with an array of product (no need for `forEach`).
> * `this.store.products` already contains the array of products (you probably don't need to maintain your own copy of the product: keep a single source of truth)
> * setup your listeners before calling `refresh()`. Move `store.refresh();` to the end of the constructor function
> * setup an `error` listener so you can console log whatever bad happens. In 99% of cases, a misconfiguration of some sort.



> I'm not surprised that the state is `registered` and content equal to whatever you gave to `register()`: loading product info will take some time, and will happen a while after you run through the list of products.
> 
> Some tips:
> 
> * you can call `register()` with an array of product (no need for `forEach`).
> * `this.store.products` already contains the array of products (you probably don't need to maintain your own copy of the product: keep a single source of truth)
> * setup your listeners before calling `refresh()`. Move `store.refresh();` to the end of the constructor function
> * setup an `error` listener so you can console log whatever bad happens. In 99% of cases, a misconfiguration of some sort.

Thanks, it's helpful.
I'm using Ionic 4 (latest) and the types are not working well with a list of products.  I see that you have sent a pull request about the types to Ionic Native team (https://github.com/ionic-team/ionic-native/pull/3037) but It looks like it is not related to Ionic, and this is a problem in the repo type also:

`register(request: IRegisterRequest): void;`

I submitted a pull request to fix this, please review

**Comment by j3k0** [comment]
Closing for now. Please reopen (or maybe a new issue) if you have more questions.
