### ISSUE TITLE
Issue with capacitor - package IInAppBillin gService does not exist

### ISSUE THREAD

**Issue by theunreal** [j3k0/cordova-plugin-purchase#870]
When I'm trying to run my app in android using capacitor, I get the following error:

```
util\IabHelper.java:234: error: package IInAppBillin
gService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
```

**Comment by j3k0** [comment]
Should capacitor be 100% compatible with Cordova? Never used it, just learned about it.

The plugin installs a `.aidl` containing definition for the `InAppBilling` service. It seems like it hasn't been installed correctly. You should check with them why, maybe that's not supported?

**Comment by j3k0** [comment]
Did you learn anything?

**Comment by theunreal** [comment]
> Did you learn anything?

It happened to me in Cordova as well, and I just did `ionic Cordova platform remove android` then adding again, and it worked.  It looks like it happens sometimes when the "add android" command does not finish successfully.

**Comment by j3k0** [comment]
Thanks for sharing. Surely someone else will stumble upon this issue and be glad you did ;) Cheers
