### ISSUE TITLE
[IOS] autoFinishTransactions odd error

### ISSUE THREAD

**Issue by plaidfox** [j3k0/cordova-plugin-purchase#872]
### system info
```
ionic info

Ionic:

   Ionic CLI                     : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 5 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.1.2

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

cordova plugin ls
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-purchase 8.1.1 "Purchase"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

```

### Expected behavior
Trying to use autoFinishTransactions in my app. I'm struggling with getting multiple sandbox users to not all share the same ownership of non-consumable items.

### Observed behavior
When I run the app in xCode on my phone, I get the following error:
```
2019-06-16 12:01:40.684269-0400 iaptwo[6462:751346] WARN: Native: tried calling InAppPurchase2.autoFinishTransactions, but the InAppPurchase2 plugin is not installed.

2019-06-16 12:01:40.684702-0400 iaptwo[6462:751346] WARN: Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'
```
Everything else about the plugin seems to be working just fine except this.

### Steps to reproduce
Start a basic Ionic app and install cordova-plugin-purchase (ionic cordova plugin add cordova-plugin-purchase). Setup the code using the basic code from here: https://forum.ionicframework.com/t/in-app-purchase-2-not-working-on-production/137660/7

**Comment by jaydrozd** [comment]
Did you ever figure out this error? I’m trying to use Capacitor and are getting the same error message, and I feel like my purchase queue is real full, which is making it hard to debug right now.

**Comment by plaidfox** [comment]
This was so long ago I don't really remember the details of how I dealt with this issue. Obviously the developer never got back to me so I didn't find a solution there. I think I might have done some research into how to change the sandbox user on my local device but I don't remember for sure.

**Comment by akrmr** [comment]
I'm also running into this issue using capacitor. Even wrapping it inside the `platform.ready()` function doesn't seem to work, even though it worked for other plugins that had the same issue. Was anyone able to get this working?
