### ISSUE TITLE
Build failed Cordova [ANDROID]

### ISSUE THREAD

**Issue by YadrovSergey** [j3k0/cordova-plugin-purchase#874]
### system info

```
Windows 10
cordova-lib@9.0.1 
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> java.io.IOException: com.android.ide.common.process.ProcessException: Error while executing process C:\Android\Sdk\build-tools\29.0.0\aidl.exe with arguments {-pC:\Android\Sdk\platforms\android-27\framework.aidl -oD:\DEVELOP\js_app_cordova\platforms\android\app\b
uild\generated\source\aidl\debug -ID:\DEVELOP\js_app_cordova\platforms\android\app\src\debug\aidl -ID:\DEVELOP\js_app_cordova\platforms\android\app\src\main\aidl -ID:\DEVELOP\js_app_cordova\platforms\android\CordovaLib\build\intermediates\bundles\debug\aidl -IC:\Us
ers\yadro\.gradle\caches\transforms-1\files-1.1\support-media-compat-27.1.1.aar\78a2f5759f67075a491ab007a3218e97\aidl -IC:\Users\yadro\.gradle\caches\transforms-1\files-1.1\support-compat-27.1.1.aar\3f58baca2a1c85422c3199a43a03fd0a\aidl -dC:\Users\yadro\AppData\Loc
al\Temp\aidl3474659616846735292.d D:\DEVELOP\js_app_cordova\platforms\android\app\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl}

**Comment by Dexus** [comment]
Please provide your global Cordova plugins, and the project cordova plugins that are installed.

Thanks

**Comment by YadrovSergey** [comment]
cordova info:

cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: win32
  Node: v10.16.0
  npm: 6.9.0

----------------------

cordova requirements:

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-29,android-28,android-27
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-5.1.1\bin\gradl
---------------------------

project plugins:

"dependencies": {
    "cordova-android": "^8.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-purchase": "^8.1.1",
    "cordova-plugin-screen-orientation": "^3.0.1",
    "cordova-plugin-speechrecognition": "git+https://github.com/YadrovSergey/cordova-plugin-speechrecognition.git",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-vibration": "^3.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "es6-promise-plugin": "^4.2.2",
    "onesignal-cordova-plugin": "^2.4.7",
    "phonegap-plugin-barcodescanner": "^8.0.1",
    "yandex-appmetrica-plugin-cordova": "^0.4.0"
  },

**Comment by Dexus** [comment]
Did you update your project or is it a new one?

Von meinem iPhone gesendet

**Comment by killerkarnikel** [comment]
hey i have removed in android studio under sdk tools - build-tools versions with 29.x.x now it seems to work... 💃  (have to show package details)

**Comment by YadrovSergey** [comment]
> Did you update your project or is it a new one

Update project. But before removed folders node_modules, platforms, plugins

**Comment by YadrovSergey** [comment]
> hey i have removed in android studio under sdk tools - build-tools versions with 29.x.x now it seems to work... 💃 (have to show package details)

![image](https://user-images.githubusercontent.com/4640119/59824314-7234e980-9339-11e9-80c9-80c4854f1112.png)


![image](https://user-images.githubusercontent.com/4640119/59824352-87aa1380-9339-11e9-965e-37377dcb217d.png)

**Comment by YadrovSergey** [comment]
Install Android SDK build tools 28.0.3 then build BUILD SUCCESSFUL
