### ISSUE TITLE
Cannot get any date

### ISSUE THREAD

**Issue by Basil22** [j3k0/cordova-plugin-purchase#875]
I tryed to use 'expiryDate' and 'lastRenewalDate', but get nothing.

```
    if (product) {
        let info = product.title;
        if (product.expiryDate)
            info += ', up to ' + product.expiryDate;
        if (product.trialPeriod)
            info += product.trialPeriod + ' (trial)';
        if (product.lastRenewalDate)
            info += ', last renewal ' + product.lastRenewalDate;

        return info;
    }
```
I got only title, not dates. What's wrong?

Happend both on Android and iOS. Plugin version 'phonegap-cli-8.0.0'.

**Comment by Basil22** [comment]
Actually I just need to inform user how long the subscription/trial will be active.

**Comment by phuwin** [comment]
@Basil22 Check this out https://github.com/j3k0/cordova-plugin-purchase/issues/837#issuecomment-503420864

**Comment by Basil22** [comment]
What do you mean by "to implement the billing system"? I guess Apple/Google already did it :)

**Comment by j3k0** [comment]
Hey, yes `expiryDate` isn't available from the plugin. Receipt validation is required with a service like https://billing.fovea.cc/

**Comment by j3k0** [comment]
(to clarify, this will make the new field available on iOS)

**Comment by Basil22** [comment]
Thank you.
