### ISSUE TITLE
[ANDROID] cannot get product info

### ISSUE THREAD

**Issue by LifeEternal** [j3k0/cordova-plugin-purchase#876]
Using store.get(productId), doesn't give me the product information, even when checking the store variable tells me the same info as below (besides the 4 1st fields that may vary). I dont understand why

{  
          "id":"product2teste",
          "alias":"product2teste",
          "type":"non consumable",
          "state":"registered",
          "title":null,
          "description":null,
          "priceMicros":null,
          "price":null,
          "currency":null,
          "countryCode":null,
          "introPrice":null,
          "introPriceMicros":null,
          "introPriceNumberOfPeriods":null,
          "introPriceSubscriptionPeriod":null,
          "introPricePaymentMode":null,
          "ineligibleForIntroPrice":null,
          "loaded":false,
          "canPurchase":false,
          "owned":false,
          "downloading":false,
          "downloaded":false,
          "additionalData":null,
          "transaction":null
       }

**Comment by LifeEternal** [comment]
and now i can get the state, but if i check the product.owned on another device it loses the owned status...

**Comment by Dexus** [comment]
On the other device you need to restore your purchase...

Von meinem iPhone gesendet

**Comment by LifeEternal** [comment]
@Dexus thank you for the reply.
Isn't the owned proprety of a product tied to a google account? How would i be able to do the restore?

Best regards

**Comment by Dexus** [comment]
Please read the docs before, you ask questions many of the questions are answered there!

I don’t know what kind of product you mean but subscriptions are on g accounts and only on one device that restored the purchase available.

Von meinem iPhone gesendet

**Comment by LifeEternal** [comment]
it is in the json example i posted. Its a non consumable, from what ive read "Purchases are linked to a user's iTunes / Google account. As such, it's made available on all devices for this user."

**Comment by LifeEternal** [comment]
@Dexus if i click the button ive in game to open the non consumable in the store it says i already own the product even though product.state = valid and not product.state = owned
