### ISSUE TITLE
[iOS] Plugin doesn't fire events (only after leaving and reentering app)

### ISSUE THREAD

**Issue by bobby1212** [j3k0/cordova-plugin-purchase#877]
### system info
Plugin Version: phonegap-cli-8.0.0
Phonegap Version: cli-8.0.0
Device: iPhone 7 

```
OSX Sierra 10.12.04
Cordova 7.0.1 // Phone Gap 3.19.2 etc.
Device: iPhone iOS 12
Plugin Version: 6.0.0
```

### Expected behavior
Call to store.order() triggers native Popup from  iOS to proceed with an in app purchase.
### Observed behavior
After call to store.order() nothing happens. But if I go out of the app by pressing the homebutton or dragging down the systembar, something happens and a modal from iOS pops up.

The curious thing about this is, that the exact same code works like a charm on Android.

I think that for some reason iTunes doesn't respond and so the events of this plugin never get fired. But if I pause the app by doing on of the things described above, it responds.

**Comment by j3k0** [comment]
_note_: seems to be an issue specific to PhoneGap. Same project works OK with cordova. (To be confirmed)
