### ISSUE TITLE
Question: How to obtain unfinished transaction receipt?

### ISSUE THREAD

**Issue by askona** [j3k0/cordova-plugin-purchase#879]
After app relaunch, if there is pending transaction, callback for product (**store.when(productId).approved(myProduct)**) being called.

 **myProduct** has field 'transaction', but there is no receipt, just transaction id.

 How to obtain transaction receipt for this case? I need to send it again to my server for validation.

**Comment by askona** [comment]
I found an answer - receipt data can added to product after verification.

**Comment by EvelinJK** [comment]
> I found an answer - receipt data can added to product after verification.

@askona Could you explain what you mean with your above comment?

We have the same issue and need to re-fetch the receipt data – but for our backend validation (like directly after a purchase), we have to send the transaction data **including** the receipt data and not just the transaction id. 

The validation with the App Store seems not to be possible with only the id, they want the whole receipt. So I don't really understand how you got the receipt data **after** verification?

**Comment by askona** [comment]
@EvelinJK This is my code. Once purchase is **approved**, I'm adding it to unfinished transactions until **verified**. After purchase verified, **.verified** callback called, and inside you can find **appStoreReceipt** and **transactionReceipt** fields. I'm sending to backend **appStoreReceipt**, and it verifies with Apple server. But now I faced other issue - **appStoreReceipt** is null in case of purchase was not completed before, and completing now, and there is only **transactionReceipt**, which dont want to be verified by our backend...
```
registerProduct(productId) {
        try {
            this.inAppPurchase.register({
                id: productId,
                type: this.inAppPurchase.CONSUMABLE
            });

            this.inAppPurchase.once(productId).approved((product: IAPProduct) => {
                this.utils.logger.log('!!!!!!!!!!!!!!!!!!!!!!!!!!!PRODUCT PURCHASE APPROVED', JSON.stringify(product));
                this.unfinishedTransactions.push(product);
            });


            this.inAppPurchase.when(productId).updated((product: IAPProduct) => {
                this.utils.logger.log('=================> UPDATED PRODUCT ' + JSON.stringify(product));
                if (!product) {
                    return;
                } else if (product.state === this.inAppPurchase.INVALID) {
                    const existIdx = this.availableProducts.findIndex(p => p.id === product.id);
                    if (existIdx > -1) {
                        this.availableProducts.splice(existIdx, 1);
                    }
                } else {
                    const existIdx = this.availableProducts.findIndex(p => p.id === product.id);
                    existIdx === -1 ? this.availableProducts.push(product) : this.availableProducts[existIdx] = product;
                }


            });

        } catch (e) {
            this.analytics.logEvent('error_register_store_product', {product_id: productId});
            this.utils.logger.error('!!!!!!!!!!!!!!!!!!!!!!!!!!!Error registering product', e);
        }
    }

purchaseProduct(productId): Promise<IAPProduct> {

        this.analytics.logEvent('purchase_initiated', {product_id: productId});

        return new Promise((resolve, reject) => {
            try {
                if (!this.platform.is('cordova')) {
                    this.utils.logger.log('!!!!!!!!!!!!!!!!!!!!!!!!!!!Please use device');
                    resolve(null);
                    return;
                }

                this.utils.logger.log('!!!!!!!! UNFINISHED TRANSACTIONS..', JSON.stringify(this.unfinishedTransactions));
                this.utils.showLoading();

                this.inAppPurchase.once(productId).verified(data => {
                    this.utils.logger.log('!!!!!!! PROD VERIFIED', data);
                    this.utils.logger.log('!!!!!!! PROD VERIFIED', JSON.stringify(data));
                    this.analytics.logEvent('purchase_success', {product_id: productId});
                    this.utils.hideLoading();
                    resolve(this.inAppPurchase.get(productId));
                });

                if (this.unfinishedTransactions.find(p => p.id === productId) && this.inAppPurchase.get(productId).transaction) {
                    this.utils.logger.log('!!!!!!! ASKING FOR VERIFICATION, CAUSE PRODUCT WAS FOUND IN UNFINISHED TRANSACTIONS', productId);
                    this.inAppPurchase.get(productId).verify();
                    return;
                }


                this.inAppPurchase.once(productId).approved((product: IAPProduct) => {
                    product.verify();
                    this.utils.logger.log('!!!!!!!!!!!!!!!!!!!!!!!!!!!PRODUCT PURCHASED', JSON.stringify(product));
                    this.utils.logger.log('!!!!!!!!!!!PRODUCT PRUCHASED THAT PRODUCT', product);
                });

                this.inAppPurchase.once(productId).cancelled((product) => {
                    this.utils.hideLoading();
                    reject();
                    this.analytics.logEvent('purchase_cancelled', {product_id: productId});
                    this.utils.logger.log('!!!!!!!!!!!!!!!!!Purchase was Cancelled');
                });


                this.inAppPurchase.error((err) => {
                    this.utils.hideLoading();
                    reject();
                    this.utils.logger.error(err);
                });

                this.inAppPurchase.order(productId).then(() => {
                    this.utils.logger.log('!!!!!!!!!!!!!!!!Purchase request started sucess, now asking password');
                }).error((error) => {
                    this.utils.hideLoading();
                    reject();
                    this.analytics.logEvent('purchase_failed', {product_id: productId, error_type: 3, reason: JSON.stringify(error)});
                    this.utils.logger.error('!!!!!!!!!!!!!!!!Error Ordering From Store');
                });

                this.inAppPurchase.once(productId).error((error) => {
                    this.utils.hideLoading();
                    this.analytics.logEvent('purchase_failed', {product_id: productId, error_type: 2, reason: JSON.stringify(error)});
                    this.utils.logger.error('!!!!!!!!!!!!!!!!!An Error Occured' + JSON.stringify(error));
                });

            } catch (e) {
                reject(e);
                this.analytics.logEvent('purchase_failed', {product_id: productId, error_type: 1, reason: e.toString()});
            }
        });

    }

    getProductPrice(productId) {
        if (!this.platform.is('cordova')) {
            return;
        }
        return this.inAppPurchase.get(productId) && this.inAppPurchase.get(productId).price;
    }

    confirmPurchaseApprovedOnBackend(product: IAPProduct) {
        const prod = this.unfinishedTransactions.find(p => p.id === product.id);
        if (prod) {
            this.unfinishedTransactions.splice(this.unfinishedTransactions.indexOf(prod), 1);
        }
        return product && product.finish();
    }```

**Comment by EvelinJK** [comment]
@askona 
Thanks for the quick reply.
Our issue (and our flow) is a bit different. We want to be able to re-connect a purchase with a use  in case a user got accidentally deleted from our database. (Since our in-app user email isn't necessarily the same as the  apple ID logged into the phone.) That's why we want to be able to re-fetch the receipt data **for an already successfully finished and still active subscription purchase** (not an unfinished transaction).

I just tested on **Android** and there, the **transaction** field is not empty and includes the **whole receipt data** just as on initial purchase. Only on iOS this field is empty and we only get the transaction id ... 🤷‍♀  

Our general purchase flow works fine. We do not add something to a queue in FE like you and re-check for unfinished transaction, but we send the purchase receipt data immediately to our backend for verification. If a purchase could not be completed successfully on first try, the product should stay in the **approved** state and gets re-verified on next startup. I think this process works fine for us and the product data can still be verified by BE – although this usually never happens for us 😅 , so I cannot be sure. 

Maybe your backend verification has to be adjusted if the re-verification doesn't work. Have you ever tested this on Android or do you only develop for iOS?

**Comment by askona** [comment]
@EvelinJK I solved problem, updating plugin to latest version. And BE was not able to get _productId_ from **appStoreReceipt**, cause **in_app** field in receipt was empty, so I'm sending _productId_ explicitly.
About you case - I didn't tested on Android (but I guess I'll in the future), and I don't see any advice I can give you, sorry:(
Probably you'll solve your problem and share your wisdom here :)

**Comment by EvelinJK** [comment]
@askona Great you could solve your issue :). 
I will share any info here if we can figure this out 😎
