### ISSUE TITLE
[Android] Restoring purchases

### ISSUE THREAD

**Issue by LifeEternal** [j3k0/cordova-plugin-purchase#881]
I have a non consumable item, i buy it. Try to restore it on another device using this.
`    if (!window.store) {
        return;
    }
    else{
        store.error(function(error) {
            console.log('ERROR ' + error.code + ': ' + error.message);
        });
    
        
        store.when($parameters.ProductId).approved(function(product) {
            product.finish();
        });
    
        
        store.refresh();
    }`

"To make the restore purchases work as expected, please make sure that the "approved" event listener had be registered properly, and in the callback product.finish() should be called."

Am i missing something?

I have this on device ready (together with store.refresh etc) to check the state of the product and it never goes beyond valid.

`    store.when($parameters.ProductId).updated(function(product) {
        alert(product.state);
    });`

**Comment by LifeEternal** [comment]
store.refresh() does not get the products the account already owns, trying to make it work on android.
Really need some help on this

**Comment by eduboxgithub** [comment]
Hello, Did you found a solution to this?

I'm also trying to implement a restore button... Can you share some code?
Reading the docs I did the same think as you have in the original post... Added the event and called refresh... but the event does not fire or gives no information...
