### ISSUE TITLE
[ios] Popup show multiple times in PRODUCTION

### ISSUE THREAD

**Issue by romanmuska** [j3k0/cordova-plugin-purchase#886]
I know that this issue already exists but none of them helps me.

### system info
```
macOS MOJAVE 10.14.3
Cordova 8.1.2
Device: iPhone iOS 12.1.4
Plugin Version: 7.4.3
```

### Expected behavior
I want to have just one popup to log into itunes and then it's done.

### Observed behavior
When i close my app and open again popup always appears. I read that in sandbox it is normal but it occurs also in production.

### Steps to reproduce
I think that it can be caused because i call store.refresh multiple times.

```
this.store.refresh();
this.store.ready(() => {
    this.store.refresh(); // second refresh to retrieve purchased products on ios
});
```

But when i delete second refresh in ready function it doesn't fetch purchased products.
So now i don't know what to do. Maybe i can try to delete second refresh and see what happens on production maybe there it retrieves purchased products and also iTunes popup will not appear each time when i start app.

**Comment by rafaellop** [comment]
Why this is tagged as `wontfix`? This is a serious issue which occurs in production versions as well. Users report to me that my app shows the login popup each start and even twice. It's annoying and I'm not surprised their reaction.
