### ISSUE TITLE
[ANDROID] register fails

### ISSUE THREAD

**Issue by MokMec** [j3k0/cordova-plugin-purchase#890]
Hello,

I am developing a phonegap application and I need to add the purchases to my application but I can't do it. 

I did exactly as in the example give with the plugin but it doesn't work. 

my code: 

store.register({type: this.store.CONSUMABLE, id:'com.bbo.product.bb10' });
store.when('com.bbo.product.bb10')
            .updated(refreshUI)
            .approved(finishPurchase);
store.refresh();

var product = store.get('com.bbo.product.bb10');

it returns an empty object. and if I display the blind value as a json I get a lot of error as shown in the image. 

![Screenshot_20190704-160845_BridgeBase](https://user-images.githubusercontent.com/49908569/60673080-3b9db980-9e77-11e9-9d5b-369a156907e8.jpg)

do you have any ideas what's not working?

**Comment by j3k0** [comment]
You're not having a lot of errors. Just displaying the store object (that contains the definition of error constants)

**Comment by MokMec** [comment]
Yes but why I have nothing in product? on the awning I have filled in everything well the price, the description... and there I have nothing. 

everything is null

**Comment by MokMec** [comment]
?

**Comment by Dexus** [comment]
Where you try to call the data?

Is it in a plug-in function from the purchase plugin?
If not there is your problem!

Von meinem iPhone gesendet

**Comment by MokMec** [comment]
I call him from my android phone. 

I have filled in the billing key correctly. I use the purchase plugin directly. 

and if that's my problem, I ask a forum to help me identify it.

**Comment by MokMec** [comment]
?

**Comment by MokMec** [comment]
no one to help me?

**Comment by MokMec** [comment]
I found and fixed the problem.
