### ISSUE TITLE
Error 6777020 Transaction expired.

### ISSUE THREAD

**Issue by Basil22** [j3k0/cordova-plugin-purchase#891]
Sometimes when my application start (especially after update) I got the error above.

Why? How to avoid it?

(This happens in sandbox; the subscription is expired. But why transaction even appears?)

My system:
iOS 12.3.1
Device: iPhone 5s
PhoneGap Version: cli-8.0.0
Plugin Version: phonegap-cli-8.0.0

**Comment by Basil22** [comment]
It looks like that it really happens when subscription expires. But why is this an error?

**Comment by Dexus** [comment]
This is an error when the customer not extends the subscription.

Like he canceled it after purchase.

Regards Josef
