### ISSUE TITLE
[iOS] TransactionFailedError after cancel and re-purchase an auto-renewable subscription 

### ISSUE THREAD

**Issue by csanchez5** [j3k0/cordova-plugin-purchase#895]
Hi.

I have a very weird problem that I can´t figure it out why is happing. If I cancel an auto-renewable subscription through iTunes and attempt to purchase it again, the native dialog ask me to confirm the purchase and display an you're all set dialog, but the plugin receive an error event. The purchase is done, I can see it in the iTunes account, but I don't know why the plugin is receiving an error event.

I have seen this strange behaviour before, when you make a purchase and the privacy policy dialog appears; if you click on the more info button and later close this dialog, an error event is received by the plugin.

Thanks

**Comment by mnill** [comment]
Faced with same issue.
