### ISSUE TITLE
Need an example to restore purchases on Android (non-consumable)

### ISSUE THREAD

**Issue by LifeEternal** [j3k0/cordova-plugin-purchase#896]
I still haven't figured out how to keep the non-consumable item when changing devices. It always seems like the data is stored locally. I've been on this for some weeks now...

**Comment by LifeEternal** [comment]
Everything regarding restoring purchases on Android is not addressed in this plugin for some reason....

**Comment by aesculus** [comment]
From my experience Android is automatic and does not need the same procedure as IOS does.

**Comment by qpwr** [comment]
@LifeEternal, did you solve your issue? How?

**Comment by LifeEternal** [comment]
> @LifeEternal, did you solve your issue? How?

Google takes care of it, but it doesn't always go for data on their servers when you try to get information. It uses the cache stored in the google play store app or something.
