### ISSUE TITLE
[IOS] - Code execution won't wait for user&password confirmation.

### ISSUE THREAD

**Issue by cL41r3-git** [j3k0/cordova-plugin-purchase#897]
Good night!

First of all, thanks for the work with this plugin. It is just amazing!
Sorry if my english is not perfect, I'm not native. I'll try my best.
I will try to be very specific.

I'm building an APP where users can pay for a subscription to get extra service.
I've reviewed all the plugin and its API documentation.
I've followed up every example I've found.
With Android, it just works like a charm, but I'm burning all my options making it work on iOS.

With iOS, code executioin won't wait for user&password confirmation.
I've checked past issues related to password input problems, but none of them treated this.

I'm testing on Sandbox and Testflight environments.

On product.refresh, the plugin asks for my iTunes/AppleStore password.
After that, on product.order, it asks for my password again to confirm the subscription payment.
So far, so good.

The problem is that code execution won't wait for me to introduce the password before trying to approve or verify the product purchase.

It approves it with no password confirmation.
If I force a "true" validation, it validates it with no password confirmation.
It finishes the purchase with no password confirmation.
It marks the subscription as owned with no password confirmation.
Therefore, the store never got the purchase, no receipt is delivered and product is faked as owned.

With Android, code execution waits for me to confirm the purchase with my credit card and password, so it won't try verification until I've confirmed the payment. I understand this is the most logical and expected behavior.

In the ugliest scenario, with iOS, I can just ignore this fact and let the code loop, in failed verification, until the user has introduced its password, as many times asked, so the store will generate a receipt on purchase confirmation, and then, yes, verification will succeed.

So, if you guys have a light here, I'm all ears (eyes?).
Otherwise, may you help me build the ugliest scenario by letting me know:
1 - How many times a failed verification will retry?
2 - Is there a way to configure verification expiracy or max attempts amount?

If plugin/platform versions or any other technical detail is required, I will let you know tomorrow when I'm back to the office.

Thanks a lot in advance for your kind attention and help.
Claire.

**Comment by j3k0** [comment]
Hi Claire,

I suppose there's something wrong with the code (like a misplaced call to `store.refresh()`). More information, like logs and source code, is necessary to diagnose the issue. If French is easier for you (assuming from your first name), feel free to contact me by email: hoelt@fovea.cc

**Comment by cL41r3-git** [comment]
Hi j3k0!!

Thanks a lot for your swiftness.
No I'm not french. My name comes from family inheritance (grand-grand-grand-father or so).
Thanks, anyway, for your kind consideration there :)

For some reason, the code is working now.
Maybe my sandbox subscription time has completely expired?
My only guess is that as we can't manually cancel a sandbox subscription, the plugin detects it on .refresh() and tries to deal with queued transactions straight away?

**How can I clear the transaction queue?**

Additionally, I've realised that, while Play Store sends the purchase notification instantly right after the purchase has been confirmed, Apple Store takes like 15-30 secs to do it. It may happen that verification fails for a while, even if confirmed by the user. Is this a known issue?

And back to my previous questions, in case i needed it later:
**1 - How many times a failed verification will retry?
2 - Is there a way to configure verification expiracy or max attempts amount?**

Just in case, this is my purchase code extract:

```
store.verbosity = store.DEBUG;

store.register(
    {
        id: "monthly_subs",
        type: store.PAID_SUBSCRIPTION,
    }
 );

store.refresh();

store.validator = "https://URL.TO.OWN.VALIDATOR";
     
store.when("monthly_subs").approved((product) => {
    console.log("Purchase has been approved!");
    product.verify();
});

store.when("monthly_subs").verified((product) => {
    console.log("Purchase has been verified!");
    product.finish();
});

store.when("monthly_subs").owned((product)=>{
    console.log("Purchase completed! Hi subscriber!");
    subscribedUser = true;
    // And some product data logs to DB for later use.
});

store.when("monthly_subs").cancelled((product) => {
    console.log("Purchase has been cancelled!");
    subscribedUser = false;
});

store.when("monthly").updated((product) => {
     console.log("Product status updated: " + product.state);
});

store.order("monthly_subs");

store.error((err) => {
            console.error("Store ERROR:  " + JSON.stringify(err));
});
```

**Comment by j3k0** [comment]
Some remarks about the code:

1. you should call `store.refresh()` only after setting up the event handlers (`.when(...)` and `.error(...)`)
2. your code should only be run once, at application startup.
3. I suppose the call to `store.order("...")` is not placed here, is it? You cannot order a product until it has been properly initialized (and is in the `valid` state).

Your questions:

 * Failed verification will be attempted 3 times.
 * There is no way to configure verification expiracy or max attempts amount.

You can try with Fovea's receipt validator to check if you have the same behavior, it's free. https://billing.fovea.cc/

**Comment by cL41r3-git** [comment]
Wow, thanks a lot for the detailed explanation, j3k0.
I'll check this all and be back with a feedback.

Thanks again! Have a nice day!

**Comment by cL41r3-git** [comment]
Sorry, j3k0, I have another hesitation.
I understand the product goes into valid status on successful .refresh and that it will change to approved only after I confirm the purchase with my password. Is that correct?

Thanks!

**Comment by j3k0** [comment]
Yes you're correct. Notice that `refresh()` is asynchronous.

**Comment by cL41r3-git** [comment]
Hi, j3k0!!

It seems to work as expected now.
Thanks for all your help.
May I, though, insist in a last question?

**How can I clear the transaction queue?**

I'm pretty sure I've read it somewhere but I can't find it now.

Again, thanks a lot, j3k0!!
I hope you have a very nice weekend!!

**Comment by j3k0** [comment]
`store.autoFinishTransactions = true;` (before the initial call to 
`store.refresh()`)

**Comment by cL41r3-git** [comment]
That's it!!! Thanks a lot, j3k0.
This is issue can be closed.
I hope it helps others in the future.

Have a nice weekend!!
