### ISSUE TITLE
Android: ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)

### ISSUE THREAD

**Issue by tareqdayya** [j3k0/cordova-plugin-purchase#898]
Hello,

I get the error mentioned in the title on Android. ios, however, works fine.

### system info
```
OSX Mojave 10.14.15
Cordova 9.0.0
Android Platform: 8.0.0
Device:LG G3 // Android 5.1
Plugin Version: 8.1.1
```

### Expected behavior
store.when('product').updated(handler_function) fires and handler_function executes.
I have 2 non-consumables.
 
### Observed behavior
The store.when("product").updated(function (p) { renderIAP(p); }) never fires, so my products never load. The error in the title seems to be the cause. Funny thing, if i try to call the refresh methodagain, the updated event fires but the product never becomes "loaded". so I still can't see my products.

 Here's Android Studio's log [THERE'S A SHORTER CHROME LOG BELOW]:
07-20 17:24:48.735 528-528/com.tareqdayya.sightreading D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
07-20 17:24:49.567 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Num SKUs Found: 2
07-20 17:24:49.567 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clfalt012
07-20 17:24:49.567 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clf01bas
07-20 17:24:49.567 528-636/com.tareqdayya.sightreading D/CordovaPurchase: init start
07-20 17:24:49.568 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Creating IAB helper.
07-20 17:24:49.569 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Starting setup.
07-20 17:24:49.570 528-636/com.tareqdayya.sightreading D/IabHelper: Starting in-app billing setup.
07-20 17:24:49.574 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/js/script.js: Line 1703 : registerProducts
07-20 17:24:49.581 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1703)] "registerProducts", source: file:///android_asset/www/js/script.js (1703)
07-20 17:24:49.581 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'clfalt012 registered'
07-20 17:24:49.581 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'clfalt012 registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'Alto Clef registered'
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'Alto Clef registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'non consumable registered'
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'non consumable registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'registered'
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'clfalt012 updated'
07-20 17:24:49.582 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'clfalt012 updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'Alto Clef updated'
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'Alto Clef updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'non consumable updated'
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'non consumable updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'updated'
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'clf01bas registered'
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'clf01bas registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.583 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'Bass Clef registered'
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'Bass Clef registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'non consumable registered'
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'non consumable registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'registered'
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'registered'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'clf01bas updated'
07-20 17:24:49.584 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'clf01bas updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'Bass Clef updated'
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'Bass Clef updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'non consumable updated'
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'non consumable updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.queries !! 'updated'
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.queries !! 'updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries ++ 'updated'
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries ++ 'updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.585 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries ++ 'Alto Clef approved'
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries ++ 'Alto Clef approved'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries ++ 'Bass Clef approved'
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries ++ 'Bass Clef approved'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries ++ 'Alto Clef updated'
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries ++ 'Alto Clef updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries ++ 'Bass Clef updated'
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries ++ 'Bass Clef updated'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: store.trigger -> triggering action refreshed
07-20 17:24:49.586 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: store.trigger -> triggering action refreshed", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.587 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 1641 : [store.js] DEBUG: queries !! 'refreshed'
07-20 17:24:49.587 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1641)] "[store.js] DEBUG: queries !! 'refreshed'", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (1641)
07-20 17:24:49.587 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 2176 : InAppBilling[js]: setup ok
07-20 17:24:49.587 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(2176)] "InAppBilling[js]: setup ok", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2176)
07-20 17:24:49.589 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 2176 : InAppBilling[js]: load ["clfalt012","clf01bas"]
07-20 17:24:49.590 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(2176)] "InAppBilling[js]: load ["clfalt012","clf01bas"]", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2176)
07-20 17:24:49.594 528-636/com.tareqdayya.sightreading W/PluginManager: THREAD WARNING: exec() call to InAppBillingPlugin.init blocked the main thread for 23ms. Plugin should use CordovaInterface.getThreadPool().
07-20 17:24:49.617 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/js/script.js: Line 1476 : Uncaught TypeError: Cannot read property 'openDatabase' of undefined
07-20 17:24:49.617 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1476)] "Uncaught TypeError: Cannot read property 'openDatabase' of undefined", source: file:///android_asset/www/js/script.js (1476)
07-20 17:24:49.618 528-528/com.tareqdayya.sightreading D/IabHelper: Billing service connected.
07-20 17:24:49.619 528-528/com.tareqdayya.sightreading D/IabHelper: Checking for in-app billing 3 support.
07-20 17:24:49.693 528-528/com.tareqdayya.sightreading D/CordovaPurchase: Setup finished.
07-20 17:24:49.705 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/js/script.js: Line 1769 : ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
07-20 17:24:49.705 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1769)] "ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)", source: file:///android_asset/www/js/script.js (1769)
07-20 17:24:52.447 528-569/com.tareqdayya.sightreading V/AudioTrack: ~AudioTrack, releasing session id from 528 on behalf of 528
07-20 17:24:54.714 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 2176 : InAppBilling[js]: setup ok
07-20 17:24:54.714 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(2176)] "InAppBilling[js]: setup ok", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2176)
07-20 17:24:54.714 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js: Line 2176 : InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas"]
07-20 17:24:54.714 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(2176)] "InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas"]", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2176)
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Num SKUs Found: 4
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clfalt012
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clf01bas
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clfalt012
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Product SKU Added: clf01bas
07-20 17:24:54.715 528-636/com.tareqdayya.sightreading D/CordovaPurchase: init start
07-20 17:24:54.716 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Creating IAB helper.
07-20 17:24:54.716 528-636/com.tareqdayya.sightreading D/CordovaPurchase: Starting setup.
07-20 17:24:54.716 528-636/com.tareqdayya.sightreading D/IabHelper: Starting in-app billing setup.
07-20 17:24:54.724 528-528/com.tareqdayya.sightreading D/IabHelper: Billing service connected.
07-20 17:24:54.724 528-528/com.tareqdayya.sightreading D/IabHelper: Checking for in-app billing 3 support.
07-20 17:24:54.731 528-528/com.tareqdayya.sightreading D/CordovaPurchase: Setup finished.
07-20 17:24:54.734 528-528/com.tareqdayya.sightreading D/SystemWebChromeClient: file:///android_asset/www/js/script.js: Line 1769 : ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
07-20 17:24:54.734 528-528/com.tareqdayya.sightreading I/chromium: [INFO:CONSOLE(1769)] "ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)", source: file:///android_asset/www/js/script.js (1769)

### Here's also the log from chrome at DEBUG verbosity; it's easier to read:
SQLitePlugin.js:175 OPEN database: app.db
SQLitePlugin.js:179 OPEN database: app.db - OK
script.js:1476 DB Opened
script.js:1516 ADD: clefs with value of TT
script.js:1524 UPDATED: clefs with value of TT
script.js:1516 ADD: tempo with value of A
script.js:1524 UPDATED: tempo with value of A
script.js:1516 ADD: frthstLvl with value of 1
script.js:1516 ADD: level with value of 1
script.js:1538 GET: option frthstLvl, index 0 with value of: 1
script.js:1524 UPDATED: level with value of 1
script.js:1516 ADD: key with value of C
script.js:1524 UPDATED: key with value of C
script.js:1516 ADD: inappAA with value of 0
script.js:1538 GET: option inappAA, index 0 with value of: 0
script.js:1516 ADD: inappBB with value of 0
script.js:1538 GET: option inappBB, index 0 with value of: 0
script.js:1505 count in rows: 7
script.js:1702 registerProducts
store-android.js:1641 [store.js] DEBUG: store.queries !! 'clfalt012 registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'Alto Clef registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'non consumable registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'clfalt012 updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'Alto Clef updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'non consumable updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'clf01bas registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'Bass Clef registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'non consumable registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'registered'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'clf01bas updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'Bass Clef updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'non consumable updated'
store-android.js:1641 [store.js] DEBUG: store.queries !! 'updated'
store-android.js:1641 [store.js] DEBUG: queries ++ 'updated'
store-android.js:1641 [store.js] DEBUG: queries ++ 'Alto Clef approved'
store-android.js:1641 [store.js] DEBUG: queries ++ 'Bass Clef approved'
store-android.js:1641 [store.js] DEBUG: queries ++ 'Alto Clef updated'
store-android.js:1641 [store.js] DEBUG: queries ++ 'Bass Clef updated'
store-android.js:1641 [store.js] DEBUG: store.trigger -> triggering action refreshed
store-android.js:1641 [store.js] DEBUG: queries !! 'refreshed'
store-android.js:2176 InAppBilling[js]: setup ok
store-android.js:2176 InAppBilling[js]: load ["clfalt012","clf01bas"]
script.js:1768 ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
store-android.js:2176 InAppBilling[js]: setup ok
store-android.js:2176 InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas"]
script.js:1768 ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
store-android.js:2176 InAppBilling[js]: setup ok
store-android.js:2176 InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas"]
script.js:1768 ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
store-android.js:2176 InAppBilling[js]: setup ok
store-android.js:2176 InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas"]
script.js:1768 ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)
store-android.js:2176 InAppBilling[js]: setup ok
store-android.js:2176 InAppBilling[js]: load ["clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas","clfalt012","clf01bas"]
script.js:1768 ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for billing v3 support. (response: 3:Error)

### Following is my code called from the device-ready handler. I've tried calling it from other places after the device ready event fires:
```
if (!window.store) {
        console.log('Store not available');
        return;
    }

    store.verbosity = store.DEBUG;   

    // Inform the store of your products
    store.register({
        id: FIRST_PRODUCT_ID,
        alias: 'Alto Clef',
        type: store.NON_CONSUMABLE
    });
    store.register({
        id: SECOND_PRODUCT_ID, 
        alias: 'Bass Clef',
        type: store.NON_CONSUMABLE
    });

    // When any product gets updated, refresh the HTML.
    store.when("product").updated(function (p) {
        renderIAP(p);
    });

    // when alto unlock is approved for purchase
    store.when("Alto Clef").approved(function (order) {
        console.log('You just unlocked the ALTO CLEF!');
        order.finish();
    });

    // when bass unlock is approved for purchase
    store.when("Bass Clef").approved(function (order) {
        console.log('You just unlocked the Bass CLEF!');
        order.finish();
    });

    // alto owned
    store.when("Alto Clef").updated(function (product) {
       // do something
    });

    // bass owned
    store.when("Bass Clef").updated(function (product) {
       // do something
    });

   
    store.ready(function () {
        console.log('Store Ready');
        // activate refresh button for restoring purchases
        $('#rfrshPrchs button').removeAttr('disabled').removeClass('disabled').click(() => {
            store.refresh();
        });
    });

    store.refresh();

    store.error(function(error) {
        console.log('ERROR ' + error.code + ': ' + error.message);
    });

    function renderIAP(prdct) {
        // array of labels
        let parts = prdct.id.split(".");

        // find element in DOM
        let elId = parts[parts.length - 1];
        let el = document.getElementById(elId + '-purchase');
        if (navigator.userAgent.includes('Android')) el = document.getElementById(elId.toUpperCase() + '-purchase');
        if (!el) return;
        // not loaded
        if (!prdct.loaded) {
            el.innerHTML = '<h5>Loading ...</h5>';
        } else if (!prdct.valid) {
            el.innerHTML = '<h5>' + prdct.alias + ' Invalid</h5>';
        } else if (prdct.valid) {
            // paragraph with Spinner for when button disappears after clicking it
            let html = "<p class='font-weight-bold col-8'>" + prdct.title + " - " + "<span class='font-weight-normal'>" + prdct.description + "</span>" + "</p>";
            html += `<span class="col-3 text-center"><img class="w-50" src="img/Spinner-1s-200px.svg" alt="loading"></span>`;
            if (prdct.canPurchase) {
                // buy button
                html = "<p class='font-weight-bold col-8'>" + prdct.title + " - " + "<span class='font-weight-normal'>" + prdct.description + "</span>" + "</p>"
                    + "<button class='btn btn-dark col-3 text-center' id='buy-" + prdct.id + "' data-productid='" + prdct.id + "' type='button'>" + prdct.price + "</button>";
            }
            // owned
            if (prdct.owned) {
                // owned tick
                html = "<p class='font-weight-bold col-8'>" + prdct.title + " - " + "<span class='font-weight-normal'>" + prdct.description + "</span>" + "</p>"
                    + `<span class="col-3 text-center">&#x2713;</span>`   // this is a tick
            }
            el.innerHTML = html;
            // buy btn listener
            if (prdct.canPurchase) {
                document.getElementById("buy-" + prdct.id).onclick = function () {
                    let pid = $(this).data('productid');
                    store.order(pid);
                };
            }
        }
    }
```

**Comment by ndevtag** [comment]
I can confirm, that i have the same problem for a paid subscription, but only on Android < 8.1, tested on Android 8.0.

**Comment by j3k0** [comment]
Can you try #911 ?

**Comment by ndevtag** [comment]
Have tested #911, get an other error: "Init failed - Setup failed. BILLING_UNAVAILABLE: Google Play In-app Billing API version is less than 3". Code: 6777001
Maybe because ist an local deployed app? With Android 8.1 and the other version it worked on local deployed app.

**Comment by dnlbbrg** [comment]
Did someone solved this issue? I can't get it worked.

**Comment by j3k0** [comment]
Please use the latest version of the plugin `cordova-plugin-purchase@9.0.1`. This has been solved already.

**Comment by perseluspiton** [comment]
just a note:

when I upload my app to Google Play, it is tested on several devices during the pre-launch report, and most Android 6.0.1 ones send the same error message:

ERROR 6777001: Init failed - Setup failed. BILLING_UNAVAILABLE: Google Play In-app Billing API version is less than 3

all other versions are fine, though, including Android 5

I'm using cordova-plugin-purchase 10.0.0

**Comment by j3k0** [comment]
Thanks, that's useful!

Google dropped support in December 1st for the Billing Library version 2, so
there's no point for the plugin to support it.

Billing Library v3 is supported on all devices running Android 2.2 and higher
and have a "recent" (like 3-4 years old) version of Google Play.

Maybe there's something in common between those devices running 6.0.1 (a
specific manufacturer or android flavor that prevented Google Play upgrade)?

Not sure.

**Comment by perseluspiton** [comment]
Ok, so it seems that Google play test on both real and virtual devices. Using Firebase testing, one can see which one is which. I haven't gone through all of them, but the problematic ones were all virtuals. So it seems, your plugin works perfectly. Cheers!

**Comment by j3k0** [comment]
Thanks for the follow up.

**Comment by michaelbutler1998** [comment]
I am receiving this same error in 2021, did you find a resolution to this @j3k0?
