### ISSUE TITLE
[iOS][ANDROID] .verify() return expected fields.

### ISSUE THREAD

**Issue by cL41r3-git** [j3k0/cordova-plugin-purchase#899]
Good afternoon!!

I'm debugging my personal validator and I'd like to know what are the expected fields .verify() method is expecting to have on return from the validator.

The following works on sucess:
return ["ok" => true, "data" => ["code" => 0]];

I'm guessing on failure it would expect "ok" => false, but I'm not sure about the error codes.
Where can I check this info? I'm reading everything/everywhere but I can't find it.

Thanks a lot in advance!!

**Comment by j3k0** [comment]
The plugin's API documentation contains the list of error code.

**Comment by cL41r3-git** [comment]
My apologies.
I've read it so many times I've ended up by skipping them.
Thanks a lot. This can be closed.

**Comment by cL41r3-git** [comment]
Actually, please, don't close this yet.
I've found the problem is not that I don't get the proper error code, but validation is not working as expected. They go expired.

iTunes/AppleStore is asking for the purchase receipt for validation.
Although, the plugin transaction array is not including this info on product.approved data.

I'm catching the push notifications from the stores in my server, but iOS notifications are hyperdelayed (like 30 secs). PlayStore's are received instantly.

Is this behavior a known issue? I can't find specific confirmation out there.
Has the plugin something to do (like delaying the purchase, or something)?

**Comment by j3k0** [comment]
Apple notification are indeed delayed, nothing the plugin has do do 
about. `appStoreReceipt` should be included in the payload sent to the 
validator (but might not be available yet in `approved()`, will be 
loaded when `.validate()` is called).

**Comment by cL41r3-git** [comment]
Thank you j3k0, so I understand the receipt is only passed to the .validate() parameters.
I'll print out .validate() output then. Thanks!

**Comment by cL41r3-git** [comment]
Solved!! This can be closed now. Thanks a lot!
