### ISSUE TITLE
[IOS] How to identify user in validator API call

### ISSUE THREAD

**Issue by alexcroox** [j3k0/cordova-plugin-purchase#900]
There appears to be no way to modify the payload of the automated store.validator API call on successful subscription. 

I need to pass a userId to my backend with this payload in order to mark their account as subscribed.

What is the common workaround for this? Putting the userId as a paramter in the store.validator URL?

e.g

` store.validator = 'http://192.168.0.7:1980/check-purchase?user-id=123'`

**Comment by pegasx** [comment]
You can pass what ever you want on order method.

{user_id: user_id};
store.order('product_id', {user_id: user_id, extra_some_value: extra_some_value});

server side:

$data['additionalData']['user_id']
$data['additionalData']['extra_some_value']

**Comment by alexcroox** [comment]
What about subscriptions since it doesn't use that store.order function

```
store.validator = 'http://192.168.0.7:1980/check-purchase'

  store.register([
    {
      id: 123,
      alias: 'Premium User',
      type: store.PAID_SUBSCRIPTION
    }
  ])
```

**Comment by pegasx** [comment]
> What about subscriptions since it doesn't use that store.order function

There is only one method to order, it is order :) So subscriptions use order function too. Function register defines proucts.

**Comment by alexcroox** [comment]
You are right, just searched my codebase and found `store.order`. Apologies, and thank you!

**Comment by alexcroox** [comment]
Note to anyone else, you can't just do 

`store.order('product_id', {user_id: user_id, extra_some_value: extra_some_value});`

You need to do:

`store.order('product_id', {developerPayload: {user_id: user_id, extra_some_value: extra_some_value}});`

otherwise your custom keys will be stripped from the payload.
