### ISSUE TITLE
Ionic 4 Capacitor CDVPlugin class InAppPurchase does not exist

### ISSUE THREAD

**Issue by stoppiNeobiz** [j3k0/cordova-plugin-purchase#901]
When lunch the app i receive this error:
To Native Cordova ->  InAppPurchase setup InAppPurchase1479405688 ["options": []]
2019-07-26 11:02:20.992359+0200 App[22534:1888273] CDVPlugin class InAppPurchase (pluginName: inapppurchase) does not exist.
Error: Cordova Plugin mapping not found

**Comment by j3k0** [comment]
Installing the plugin might have failed (or been interrupted). Did you 
try uninstalling and reinstalling it?

**Comment by stoppiNeobiz** [comment]
yes, I've try

**Comment by stoppiNeobiz** [comment]
i've try to install plugin with ionic 4 without capacitor and work

**Comment by stoppiNeobiz** [comment]
[warn] - Native: tried calling InAppPurchase2.DEBUG, but the InAppPurchase2 plugin is not installed.   
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'   
⚡️  [warn] - Native: tried calling InAppPurchase2.verbosity, but the InAppPurchase2 plugin is not installed.   
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'   
⚡️  [warn] - Native: tried calling InAppPurchase2.PAID_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.   
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'   
⚡️  [warn] - Native: tried calling InAppPurchase2.register, but the InAppPurchase2 plugin is not installed.   
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'   

I've try to reinstall but nothing

**Comment by stoppiNeobiz** [comment]
> Installing the plugin might have failed (or been interrupted). Did you try uninstalling and reinstalling it?
> […](#)
> On Fri, Jul 26, 2019 at 02:09:27AM -0700, stoppiNeobiz wrote: When lunch the app i receive this error: To Native Cordova -> InAppPurchase setup InAppPurchase1479405688 ["options": []] 2019-07-26 11:02:20.992359+0200 App[22534:1888273] CDVPlugin class InAppPurchase (pluginName: inapppurchase) does not exist. Error: Cordova Plugin mapping not found -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #901

[warn] - Native: tried calling InAppPurchase2.DEBUG, but the InAppPurchase2 plugin is not installed.
⚡️ [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'
⚡️ [warn] - Native: tried calling InAppPurchase2.verbosity, but the InAppPurchase2 plugin is not installed.
⚡️ [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'
⚡️ [warn] - Native: tried calling InAppPurchase2.PAID_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.
⚡️ [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'
⚡️ [warn] - Native: tried calling InAppPurchase2.register, but the InAppPurchase2 plugin is not installed.
⚡️ [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'

I've try to reinstall but nothing

**Comment by Dexus** [comment]
Install please the native name cordova-plugin-purchase then it will work

Von meinem iPhone gesendet

**Comment by stoppiNeobiz** [comment]
The simple solution is npx cap update after install plugin
