### ISSUE TITLE
[IOS] Sandbox user, auto renewing subscriptions, Android returns to "valid" but iOS remains "approved" state.

### ISSUE THREAD

**Issue by pegasx** [j3k0/cordova-plugin-purchase#902]
On Android and iOS state goes to "approved" first, if verified, we call finish and state goes to "owned". But when app restarts state goes to "approved" again. Is it a normal behaviour?

If it is a normal behaviour, on Android, state goes to "valid" when it expired after all 6 subscription renewal process (30 minutes). But on iOS, state is always "approved" even all subscription renewal process finished and it has been expired or even you call verify again and return expired. Is it because of sandbox user and test?

[store.js] INFO: ios -> restored purchase product_name

state: "approved"
[store.js] INFO: ios -> transaction 1000000XXXXXX purchased (1 in the queue for product_name)

state: "approved"
[store.js] INFO: ios -> transaction 1000000XXXXXX purchased (2 in the queue for product_name)

state: "approved"
[store.js] INFO: ios -> transaction 1000000XXXXXX purchased (3 in the queue for product_name)

state: "approved"
[store.js] INFO: ios -> transaction 1000000XXXXXX purchased (4 in the queue for product_name)

state: "approved"
[store.js] INFO: ios -> transaction 1000000XXXXXX purchased (5 in the queue for product_name)

**Comment by Dexus** [comment]
Subscriptions will checked each restart!

Von meinem iPhone gesendet
