### ISSUE TITLE
[IOS] Wait until all products are restored?

### ISSUE THREAD

**Issue by romanmuska** [j3k0/cordova-plugin-purchase#903]
### system info
```
macOS MOJAVE 10.14.3
Cordova 8.1.2
Device: iPhone iOS 12.1.4
Plugin Version: 8.1.1
```

I have products which are added to localstorage after buy process. It works fine because whenever i catch approved event i add this product to localstorage and call product.finish(). Problem occurs when i want to restore all owned products. When i call store.refresh() it triggers approve event on these products but there is no way to know when all products finished and are owned. I need to have some event which will be called after products are restored, because then i want them to write at once into localstorage and refresh the UI. Do you have some idea? Now i push it one by one to localstorage and each time i add it to localstorage i also call custom event to update view.

**Comment by aesculus** [comment]
what about calling verify before refresh?
