### ISSUE TITLE
Non Sandbox iOS Beta Subscription IAP via Testflight

### ISSUE THREAD

**Issue by aesculus** [j3k0/cordova-plugin-purchase#905]
It's been a long time since I beta tested the IAP function of my app (subscriptions).  In the past I had sandbox users but I want to trial real users via the public beta route.

Can someone help me with how IAP - Subscriptions work in this environment?

- Specifically I would like to know if the Subscription IAPs last the full duration (in my case 1 month and 1 year)
- Is there is difference when having user invited to test via email or just the website link?
- Will they still use the regular validation service vs the sandbox validator? Just not be charged?
- Can existing beta users try out these IAP features too? Currently I bypass the IAP stuff for my beta users
- When the beta ends I understand their Testflight IAPs are not longer valid but I would assume if they still had credit from a prior real IAP, it would continue?
- Anything else I should be aware of?

**Comment by Ralpharoo** [comment]
Regarding durations, purchases follow the same pseudo duration as Sandbox users. This is [outlined here](https://help.apple.com/app-store-connect/#/dev7e89e149d);
1 week > 3 minutes
1 month > 5 minutes
2 months > 10 minutes
3 months > 15 minutes
6 months > 30 minutes
1 year > 1 hour

There is some other really useful information about testing the process and flow of subscriptions on TestFlight here;
[https://davidbarnard.com/post/164337147440/testing-auto-renewable-subscriptions-on-ios
](https://davidbarnard.com/post/164337147440/testing-auto-renewable-subscriptions-on-ios
)

I am not sure how it'll play when you switch between an unreleased subscription and an existing subscription. Should be pretty simple to set up some test cases to see how your code & the App Store handles things. 

Cheers,

**Comment by aesculus** [comment]
@Ralpharoo : Thanks for this. Ugh. This was what I was afraid of. All the hassles of a sandbox test. When is Apple going to get it? I would not put my worst enemy through all of that.

It also answers many of my other questions since these beta users are really sandbox users IMHO.

I like the production test schema he came up with and the offer of the promo codes. So now I have to find a few virgins that are serious enough to try the app out but have not yet subscribed. That is a pretty hard thing to do.
