### ISSUE TITLE
Validator URL required response format

### ISSUE THREAD

**Issue by alexcroox** [j3k0/cordova-plugin-purchase#907]
I've made a successful iOS repeating subscription and the plugin has called my custom backend receipt validator, which returns a 200 and some other information.

However the plugin does not like this response and marks it as un-verified.

What is the required response from the validator in order for the plugin to accept the response as verified? E.g what key/values in the XHR response data?

**Comment by samuelfaj** [comment]
+1

**Comment by BemHur** [comment]
+1

**Comment by alexcroox** [comment]
While we wait for a response, this was my workaround. Instead of providing a url to `validator`, provide a function where you make your own api call and decide the response with `callback`:

```
window.store.validator = async (product, callback) => {
  try {
    let response = await apiCall...

     // If happy with the response just call:
     callback(true)

  } catch (error) {
     // Otherwise return false
     callback(false, {
       code: window.store.PURCHASE_EXPIRED
     })
  }
}
```
