### ISSUE TITLE
[IOS] use fingerprint authentication at the time of purchase

### ISSUE THREAD

**Issue by MokMec** [j3k0/cordova-plugin-purchase#909]
OSX Mojave 10.14.6
Cordova 9.0.0 
Device: iPhone iOS 12.2 // Ipad iOS 12.2
Plugin Version: ^7.4.1

### Expected behavior

when I click on a product to buy it, I use my fingerprint to identify myself to confirm the purchase.

### Observed behavior

When I click on a product to buy it, it asks me for my password and I can't even copy and paste it. Impossible to use the fingerprint

Can you help me with this problem? 

Thank you

**Comment by MokMec** [comment]
?

**Comment by lalmanzar** [comment]
This is only present during testing on the sandbox. There is nothing the plugin can do to change it, since that is handled by apple.

**Comment by Seanmclem** [comment]
@lalmanzar this is also present when testing in test-flight
