### ISSUE TITLE
[Android] Unable to add Items after installing Plugin

### ISSUE THREAD

**Issue by jaca30909** [j3k0/cordova-plugin-purchase#914]
[Android] Unable to add Items after installing Plugin

### system info

Cordova 9.0.1 
Device: Android 8.00
Plugin Version: latest

### Expected behavior
Allow to add items, in Google Play Console.
### Observed behavior
I have installed the plugin in a blank solution with the play store key and also added a manifest file (read not needed any more) but still does not allow me to add items. Keeps telling me that i need to add billing permissions.  What am i missing.
### Steps to reproduce
n/a

**Comment by j3k0** [comment]
Hey, if you're starting a fresh new project, I recommend you try #911 that's very soon to be made the new stable release.

What do you mean "I added a manifest file". Cordova is supposed to manage the manifest file for you. The plugin adds the billing permissions to the manifest file.

**Comment by jaca30909** [comment]
Thank you Jean-Christophe,

I will try the new stable release, when will i be able to submit/add managed product to the play console?  Only after i have my app has been published with your in app purchase plugin? (This is what i see when i try to add product)

 _What do you mean "I added a manifest file". Cordova is supposed to manage the manifest file for you. The plugin adds the billing permissions to the manifest file._

i read that i need to add and amend the manifest manually  -  I tried everything to see if i can get it working.
![billing not activated](https://user-images.githubusercontent.com/54264422/63667037-a8c43000-c7d2-11e9-9b74-049c61594296.JPG)

**Comment by jaca30909** [comment]
i though when my app has been published i will be able to add products.  Took a week to get published and still not able to add products.

**Comment by jaca30909** [comment]
Hi Jean-Chritophe,

thank you, i followed your steps  and able to add managed products.  on to the next challenge.... :)

**Comment by gmbad** [comment]
Hi @jaca30909, @j3k0 

i have the same problem to add a product.

**"To add in-app products, you need to add the BILLING permission to your APK"**

I've already uploaded the package (app-release.aab), with the cordova-plugin-purchase plugin...

AndroidManifest.xml has the permission com.android.vending.BILLING.

How did you solve this problem?

Thank you,

Gabriel

**Comment by gmbad** [comment]
@j3k0 @jaca30909 

In google play console > App bundle explorer > permissions does not appear "com.android.vending.BILLING", but in AndroidManifest is added
