### ISSUE TITLE
Purchase from store

### ISSUE THREAD

**Issue by chathura-rightapps** [j3k0/cordova-plugin-purchase#917]
Hi @j3k0,
 
Sorry for my ignorance. I'm not a cordova developer and I was assigned to implement inapp purchase feature for the app. I tried cordova-plugin-inapppurchase but it has a bug and client reported it to us.So we move to this plugin.Now my question,

I want to purchase something from the store.However I could get the subscription list from the store and that works perfectly for both android and ios platforms.I did it like this.

------------------------------------------------------ 
store.register({
      id: (my product id),
      type: store.CONSUMABLE
  });

 store.ready(function() {
   store.get(my product id);
  });

  store.refresh();
---------------------------------------------------------------

Now I want to implement buy something from the store part. But still I couldn't get it to work.
Please help me.

My cordova version -- 9.0.0
cordova android platform version -- 8.0.0
cordova ios platform version -- 5.0.1
cc.fovea.cordova.purchase version -- 8.1.1

android specific-->
      defaultBuildToolsVersion="28.0.3"
      defaultMinSdkVersion=19
      defaultTargetSdkVersion=28 
      defaultCompileSdkVersion=28 
      gradle version= 4.10.3
ios specific-->
      xcode=10.3

**Comment by j3k0** [comment]
Did you try reading through the documentation? What's wrong with it?

**Comment by chathura-rightapps** [comment]
"Uncaught ReferenceError: inAppPurchase is not defined" I'm seeing in the logcat.Please help me
