### ISSUE TITLE
 [IOS & Android] StoreValidator Multiple Times Logging Purchases With Firebase and Facebook Analytics

### ISSUE THREAD

**Issue by abomadi** [j3k0/cordova-plugin-purchase#925]
`Ionic:

   Ionic CLI          : 5.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 21 other plugins)

Utility:

   cordova-res : 0.5.2
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.4.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8`

### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

In example:
```
OSX Sierra 10.12.04
Cordova 7.0.1 // Phone Gap 3.19.2 etc.
Device: iPhone iOS 10.3.2 // Android 7.1
Plugin Version: 6.0.0
```

### Expected behavior
Facebook and Firebase Analytics capture purchases automatically and for the renewal subscription it should logged once
### Observed behavior
The issue that whenever the user visit subscription page and due to store.refresh() and validating the receipts analytics platforms report them as another purchase. so each time user restore their purchases it logs as a new purchase. however even if i want to disable the auto collect information where can i log the purchase once ?
### Steps to reproduce
Install Firebase Analytics with this property Firebase.setAnalyticsCollectionEnabled(true);
Also install facebook pluin with this property  <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="TRUE" />

**Comment by Dexus** [comment]
This is no bug.

You need to check if this is new purchase or not with your server side validation.

Regards, Josef

Von meinem iPhone gesendet

**Comment by abomadi** [comment]
@Dexus Thanks i will into server responses to handle this
