### ISSUE TITLE
[iOS & Android] UPGRADES/DOWNGRADES

### ISSUE THREAD

**Issue by cL41r3-git** [j3k0/cordova-plugin-purchase#926]
Good night,

After reading the API documentation I can't find any detail regarding subscription upgrades or downgrades for both iOS and Android.

I've read previous issues and, apparently, typical scenario would be to ask the customer/user to manage its subscriptions from their PLAY/APP Store. With iOS, I can create subscription groups and order subscriptions within it by tier, although, with Android I haven't seen such a thing, and I haven't found any confirmation, anywhere, that upgrades can be managed from the subscription page in the Play Store.

1 - Does anyone know?
2 - Is this plugin supporting upgrade/downgrade tasks/events somehow?
3 - In case iOS only solution is to use the iTunes subscription management, I can't see how to handle skuDetails and oldSkuDetails for Android using this plugin as explained in:
https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade

Thanks for your kind attention in advance!

Best regards,
Claire

**Comment by lalmanzar** [comment]
In the documentation it explain how to pass the required data for upgrade/downgrade:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeorderproduct-additionaldata

For iOS the upgrade/downgrade is done automatically based on the tiers, for Android you must specify that you are replacing a previous subscription by passing the oldPurchasedSkus.

**Comment by cL41r3-git** [comment]
Sorry for the late reply!
You are totally right. I didn't understand this would work like that. This can be closed. I'll be back if I find any other inconvenient. THANKS!
