### ISSUE TITLE
[IOS] Crash with invalid product

### ISSUE THREAD

**Issue by crawft** [j3k0/cordova-plugin-purchase#928]
### system info

```
OSX High Sierra 10.13.6
Cordova 9.0.0
Device: iPhone iOS 10.4
Plugin Version: 6.1.1
```

### Expected behavior
Fail gracefully?

### Observed behavior
Crashes app

### Steps to reproduce
I am trying to get my first app with inapp purchasing through app store connect.

I realise I likely have things to sort out with Apple, but they are currently rejecting on the basis that the app crashes on attempt to purchase.

I knew my products were invalid but it looked like I had to submit a version of the app and I'd successfully tested on Android, so I submitted for review with Apple.

Products are registered etc, tho the plugin does report:

```
BatchProductsRequestDelegate.productsRequest:didReceiveResponse: Has 0 validProducts
```

And I can see the products' state is invalid.

On attempt to purchase, I see an update

```
updated {"id":"1465922070","alias":"Issue 2","type":"non consumable","state":"requested","title":null,"description":null,"priceMicros":null,"price":null,"currency":null,"countryCode":null,"introPrice":null,"introPriceMicros":null,"introPriceNumberOfPeriods":null,"introPriceSubscriptionPeriod":null,"introPricePaymentMode":null,"ineligibleForIntroPrice":null,"loaded":true,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"additionalData":null,"transaction":null,"valid":true}
```

Then a crash

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid product identifier: (null)'
```

Any input would be appreciated!

**Comment by Dexus** [comment]
You can upload first a beta version this would enough and then add your items that are valid!

For review you need an app that works! And without upload an initial app as beta you are not able to create items(?)

Von meinem iPhone gesendet

**Comment by crawft** [comment]
Thanks, I had builds in beta but still wasn't able to get valid in-app purchase products.

**Comment by Dexus** [comment]
Do you always update your Build Version? Please do not if you doing right now. Let the build version equal to your last beta upload.

This is the same as of android builds....

Von meinem iPhone gesendet

**Comment by matthiasSchedel** [comment]
@crawft Did you resolve the problem? I'm facing the same errors currently.

**Comment by alexp25** [comment]
Is this solved? How should I get the app approved on the App Store on iOS, if the app crashes because of invalid product id, before the products can actually be approved (the app has to be already approved before that)?

**Comment by alexp25** [comment]
@MovingHead Check out this [solution](https://stackoverflow.com/a/62494100/9326673). In my case, as I remember, I was missing some App Store agreements (e.g. paid apps agreement is required even for free apps with in-app purchases)

**Comment by MovingHead** [comment]
Thank you! 😊
