### ISSUE TITLE
[iOS] Auto-Renewing Subscription never expires

### ISSUE THREAD

**Issue by nielsjakob** [j3k0/cordova-plugin-purchase#931]
### system info
OSX Mojave 10.14.6 (18G95)
XCode 10.3 (10G8)
Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-plugin-purchase 9.0.0 "Purchase"
iPhone 7 with iOS 12.4.1

### Expected behavior
I am trying to get a one-week auto-renewing subscription running on iOS. After subscribing, I expect the subscription to expire after 3 minutes. Or alternatively to auto-renew 6 times with 3 minute-intervals (source: https://help.apple.com/app-store-connect/#/dev7e89e149d)

### Observed behavior
Subscribing works fine.

However, **when I restart the App – even after more than six restarts with at least 3 minutes in between, the Subscription never actually expires**. I open the app and it always gives me the product object with `owned: true`:

```
{
  "id": "subscription1",
  "alias": "subscription1",
  "type": "paid subscription",
  "group": "default",
  "state": "owned",
  "title": "subscription1",
  "description": "subscription1",
  "priceMicros": 3490000,
  "price": "3,49 €",
  "currency": "EUR",
  "countryCode": "DE",
  "introPrice": null,
  "introPriceMicros": null,
  "introPriceNumberOfPeriods": null,
  "introPriceSubscriptionPeriod": null,
  "introPricePaymentMode": null,
  "ineligibleForIntroPrice": null,
  "loaded": true,
  "canPurchase": false,
  "owned": true,
  "downloading": false,
  "downloaded": false,
  "additionalData": {},
  "transaction": {"type": "ios-appstore",
  "id": "1000000566902230",
  "original_transaction_id": "1000000566896535",
  "appStoreReceipt": "MIJK...hpEw=="},
  "valid": true,
  "transactions": []
}
```
As you can see there is also no `expiryDate` property. When I decode the `appStoreReceipt` the resulting JSON has the correct expiration date, for example: "expires_date": "2019-09-10 20:52:27 Etc/GMT".

But as I said, it keeps on renewing every time I start the app and never actually expires. Is there something I am doing wrong?

### Steps to reproduce
I am using the following minimal code. The `subscribe()` function is called when a button is clicked.

```
document.addEventListener('deviceready', function() {

  store.validator = 'https://validator.fovea.cc/v1/webhook/apple?appName=com.BUNDLE-ID&apiKey=API-KEY';

  store.register({
    id  : 'subscription1',
    type: store.PAID_SUBSCRIPTION
  });

  store.when('subscription1').updated(function(product) {
    console.log('UPDATED', JSON.stringify(product));
  })
  store.when('subscription1').approved(function(product) {
    console.log('APPROVED', JSON.stringify(product));
    product.verify();
  })
  store.when('subscription1').verified(function(product) {
    console.log('VERIFIED', JSON.stringify(product));
    product.finish();
  })
  store.when('subscription1').owned(function(product) {
    console.log('OWNED', JSON.stringify(product));
  })
  store.when('subscription1').expired(function(product) {
    console.log('EXPIRED', JSON.stringify(product));
  });

  store.refresh();

})


function subscribe() {
  store.order('subscription1');
}
```

Full www folder:
[www.zip](https://github.com/j3k0/cordova-plugin-purchase/files/3597750/www.zip)

**Comment by nielsjakob** [comment]
Upon closer inspection, I was wrong: after 5 renewals, the subscription is no longer renewed o.O Awesome! :)

**Comment by guigons** [comment]
Hello, what you was wrong? Could you share with us?
