### ISSUE TITLE
[ANDROID] How to get the account identifier used to make the in app purchase

### ISSUE THREAD

**Issue by 8bhsolutions** [j3k0/cordova-plugin-purchase#935]
On a device with multiple accounts, the Google Play Store can be used by all the accounts.

When the order() is called
- Which account is used?
- Can we programmatically get the account identifier used to purchase (for debugging and logging purpose)?
- Can we programmatically allow user to change account use to purchase the order?

**Comment by jffs** [comment]
how did you solve that scenario?

**Comment by 8bhsolutions** [comment]
Didn't get a response from anyone
