### ISSUE TITLE
Non renewing subscription IOS

### ISSUE THREAD

**Issue by ramsh5803** [j3k0/cordova-plugin-purchase#936]
# IOS
Used  cordova non renewing subscription demo and icloudKV plugin to sync on all user devices.The purchase is not getting completed on real device. I  get an error in debugger as icloudKV load string failed. Help would be appreciated.I implemented it in the following way.

```
app.onDeviceReady = function () {
    console.log('initializing the nonRenewing plugin');
  nonRenewing.initialize({ verbosity: store.DEBUG,
                           products: [{ id: 'nonrenewing8',
                                  duration: 3600 }],
                           saveExpiryDate: function(expiryDate, callback) { iCloudKV.save('cordovanonrsdate', expiryDate, callback);
                            },
                           loadExpiryDate: function(callback) { iCloudKV.load('cordovanonrsdate', function(value) { callback(null, value); }, function() { callback('error occured');
                                });
                                },
                           });
```
  Help would be appreciated.

**Comment by Dexus** [comment]
We don’t support iCloudKV... so if you have questions to this ask the developer of it.

Also if we should help you don’t forget to post some more details like logs. 

Regards, Josef

Von meinem iPhone gesendet

**Comment by ramsh5803** [comment]
What is the best way to sync purchases on all user devices.

**Comment by j3k0** [comment]
This is a question about the `cordova-non-renewing-subscription` plugin, issue should be posted there.
