### ISSUE TITLE
Lazy loading for registration of products

### ISSUE THREAD

**Issue by danieldanielecki** [j3k0/cordova-plugin-purchase#938]
This feature has been requested already in [issue#351](https://github.com/j3k0/cordova-plugin-purchase/issues/351) and [issue#333](https://github.com/j3k0/cordova-plugin-purchase/issues/333). Basically, we would like to register product when it'll be required. Otherwise, when there are many products to register up-front it might be difficult to handle for the application.

Comments related of this issue:
- [issue#333 opening comment](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issue-114976483) of @gsfioravanti;
- [issue#333 comment 1](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-156877958) of @rotoxl;
- [issue#333 comment 2](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-195973987) of @arielfaur;
- [issue#351 opening comment](https://github.com/j3k0/cordova-plugin-purchase/issues/351#issue-119932393) of @enricodeleo;
- [issue#351 comment1](https://github.com/j3k0/cordova-plugin-purchase/issues/351#issuecomment-161293946) of @arielfaur;
- [issue#351 comment2](https://github.com/j3k0/cordova-plugin-purchase/issues/351#issuecomment-378788044) of @charlierz;
- [issue#351 comment3](https://github.com/j3k0/cordova-plugin-purchase/issues/351#issuecomment-400196166) of @Luro91;

And in the [issue#351 comment4](https://github.com/j3k0/cordova-plugin-purchase/issues/351#issuecomment-408028048) even @j3k0 says it would be helpful.

These 2 issues have been closed, hope so to keep that one open so this important feature won't be missed in the future. At least we hope so.

Edit: my findings which **could** be related with this issue I described in [#issue333 (comment)](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-533806270), however I'm not sure if it applies here.

**Comment by j3k0** [comment]
Some facts:

 * product information need to be loaded so an order can be processed
 * purchase events can be present the queue at app startup
    * in-app products can be purchased outside of your app
    * in-app purchase flow might have been interrupted during last session
    * this is true on both iOS (since the begging) and Android (since billing API v2)
 * this is why loading app information at app startup is required by the plugin
    * this is also why you need to register purchase events callbacks at app startup, not before you call `order()`
 * so far nobody proved that there's a performance penalty when loading product information at app startup: even with thousands of products, the response is no bigger than a single JPEG image.

I believe that this is a case of premature optimization, except if for these 0.001% of developers in the world that will have 100,000 virtual products to sell in the app... But OK, you can prove me wrong :)

**Comment by danieldanielecki** [comment]
I was facing some issue related with working code on Android, whilst not working on iOS and could find that this repeats in the issue. If you think this is not a problem (even though on one of this issues it's marked as "backlog") then simply close this issue. Personally, I'm not planning to have that many products and for me this works fine and did **not** face any performance-related issues due to the fact. By the way, when I'm loading my products as lazy loaded on Android my code works perfectly fine, but on iOS it does not. The last behaviour I did describe in [issue#333 (comment)](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-533806270), if it helps.

**Comment by j3k0** [comment]
> [...] lazy loaded on Android my code works perfectly fine

Fine in 99% of cases. For example, "Pending Purchases" will probably fail (especially if you leave the app before transaction is completed)

**Comment by danieldanielecki** [comment]
Good to know :) Sadly on iOS it does not :(
