### ISSUE TITLE
[ANDROID] ProrationMode (feature request)

### ISSUE THREAD

**Issue by abesiemsen** [j3k0/cordova-plugin-purchase#941]
Was hoping to set the Prorotation Mode for Android purchases in my app, and noticed this commented code in `PurchasePlugin.java`:
```
// (I did not find enough documentation to support this parameter)
// if (replaceSkusProrationMode) { // int
//   params.setReplaceSkusProrationMode(replaceSkusProrationMode)
// }
```
I also found [this documentation](https://developer.android.com/google/play/billing/billing_subscriptions#prorate) describing how to set ProrationMode as part of the BillingFlowParams.

I'd love to be able to pass a property into the `additionalData` param of the `store.order()` method in order to set the ProrationMode, similar to the way `oldSku` is handled.

Any chance I can convince you to undertake such a feature addition?

**Comment by gvsrepins** [comment]
Hello @j3k0, 

Can you please provide any clarification about how can we procede with this use today? I'm using your plugin and this feature is very much needed. 

Any hack, tips, or tweak may help. 

Thank you very much for all the effort in the open source.

Best,

**Comment by rastafan** [comment]
+1

**Comment by j3k0** [comment]
It is not supported for now I'm afraid, until someone does implement it. It's on my TODO list, but quite far from the top, sorry to say.
