### ISSUE TITLE
[ANDROID] Refunded non consummable not considered

### ISSUE THREAD

**Issue by GautierDele** [j3k0/cordova-plugin-purchase#944]
### system info

Cordova-android: 8.1.0
Device: Android 9
Plugin Version: 8.1.1

### Expected behavior

When a non consumable is refunded, the order method should open the dialog asking for buying the product

### Observed behavior

The order method only launch a verify method to the server. It seems like the plugin thinks the product is owned.
The server is returning:
```json
{"ok":false,"data":{"code":6778003}}
```

Here is the product in detail:

![image](https://user-images.githubusercontent.com/12382966/66391904-a4448700-e9ce-11e9-9c78-027e8a3675af.png)

Nothing seems wrong

### Steps to reproduce

Order a non consummable, refund it and try to order it again

**Comment by j3k0** [comment]
I guess a call to `store.refresh()` can make this work?
