### ISSUE TITLE
[ANDROID] v9.0.0 product.cancelled event dosn't trigger

### ISSUE THREAD

**Issue by Rigwarl** [j3k0/cordova-plugin-purchase#945]
### system info
```
macOS High Sierra 10.13.6
Cordova 9.0.0
Device: Mi A2 Lite, Android 9
Plugin Version: 9.0.0
```

### Expected behavior
If user cancel purchase trigger `product.cancelled` event
### Observed behavior
If user cancel purchase i get
`store.Error {code: 6777003, message: "Purchase failed: USER_CANCELED"}`, `product.cancelled` event dosn't trigger

Work as expected in v8.1.1

**Comment by adamduren** [comment]
I just discovered this as well

**Comment by adamduren** [comment]
@Rigwarl This might have fixed it https://github.com/j3k0/cordova-plugin-purchase/commit/cb221a76765d5bd2fc65c57f49f2e4e4c172453a. Appears to be in 9.0.1

**Comment by Rigwarl** [comment]
@adamduren
Thanks, working like a charm!
Thanks again for awesome plugin :)
