### ISSUE TITLE
store.verifyPurchases() scenarios

### ISSUE THREAD

**Issue by rafaellop** [j3k0/cordova-plugin-purchase#950]
I've noticed a new function `store.verifyPurchases()` but I'm curious for a possible scenarios. Does it work as refresh() or is it a limited version of it? Or can I maybe use it to reverify existing purchases against my receipt verification server? I would want to use the function to verify user purchases every some period of time (e.g. once a week) or when `p.verify().expired` or `p.verify().error` occur. Is it better than `refresh()` which shows the itunes login popup?

**Comment by j3k0** [comment]
It's a work-in-progress (not implemented on Android). Indeed the idea is to make it a light refresh that will never ask for the user password. The plugin already uses it automatically when the app starts and when a subscription expires (to check if it has been renewed).

This function will validate the "application" product, a new thing too. Basically this gives the chance to the receipt validator to return a collection (git grep collection src/js/product.js) to change fields in the products.

Again, this is work-in-progress, use with caution.

**Comment by j3k0** [comment]
Note, I renamed `verifyPurchases()` to `update()` => does more stuff now: namely refreshing the prices from the appstore. it's will be a good method to call before opening your "Store" screen. I'll close the issue, please reopen if you want to continue the discussion.
