### ISSUE TITLE
[IOS] Metadata version mismatch for module

### ISSUE THREAD

**Issue by stockwellb** [j3k0/cordova-plugin-purchase#956]
System Information
```
Ionic:

   Ionic CLI          : 5.0.2
   Ionic Framework    : ionic-angular 3.6.0
   @ionic/app-scripts : 2.1.3

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 6.4.0, ios 4.5.4
   Cordova Plugins   : no whitelisted plugins (16 plugins total)

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.1
   ios-sim           : 5.0.13
   NodeJS            : v8.10.0 
   npm               : 5.6.0
   OS                : macOS Catalina
   Xcode             : Xcode 10.3 Build version 10G8
```

### Expected behavior

Should compile

### Observed behavior

Does not compile.
```
Error: Metadata version mismatch for module 
            /node_modules/@ionic-native/in-app-purchase-2/index.d.ts, 
            found version 4, expected 3 
```

### Steps to reproduce

Import into module
```import { InAppPurchase2 } from "@ionic-native/in-app-purchase-2";```
Add to constructor
```constructor(private inAppPurchase2: InAppPurchase2) ```

**Comment by Dexus** [comment]
you can try this:

package.json
replace this:

"build": "ionic-app-scripts build",

with this:

"build": "ionic-app-scripts build --prod",

Then try running ionic cordova build android --release


or you need to run `npm install`.


your error message does not include to much details about the build run so its difficult to say whats wrong...

**Comment by j3k0** [comment]
No reply, closing.
