### ISSUE TITLE
[android] approved is supposed to be run multiple times?

### ISSUE THREAD

**Issue by martijnmichel** [j3k0/cordova-plugin-purchase#958]
Just a simple question because im new to in app billing and im trying to understand.
In my app ive made an approved listener and an owned listener, but get run when i start the app (or when i made the purchase) but i would expect that, after ive done subscription.finish() then next time only owned would get run, but  every time approved and owned both get triggered. Is this normal behaviour?

**Comment by Dexus** [comment]
Hi please have a look at https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#life-cycle 

Yes it is a normal behaviour!

**Comment by martijnmichel** [comment]
Thanks! Its working nicely. One more simple Q though which i cant find in the docs... which event is run when a subscription is cancelled? Ive tried expired and cancelled but both of them dont get triggered at the date play store gives me for the expiring subscription.

**Comment by Dexus** [comment]
There is no extra event. The validation process will fail and set other properties.

**Comment by martijnmichel** [comment]
Hmm okay.. that means that while the app stays open users can keep using their subscription even when it got cancelled in the meanwhile.. i guess its not a very big problem because most users will eventually close the app anyway but it could mean people can subscribe and unsub, leave the app open, and have free access to my subscribed content.

**Comment by Dexus** [comment]
If your app only works on client side and don’t use an api server as backend. You are right, I think....

Von meinem iPhone gesendet

**Comment by GroverBhumika** [comment]
Hello guys

I have faced same problem
if we transaction details save in DB then which event use for this? I have used APProved event
but when we pay first time it's working fine
when We pay second time then APProved event hits two times
