### ISSUE TITLE
[ANDROID] Your server-side billing confirmations will stop working on December 1, 2019

### ISSUE THREAD

**Issue by zarelint** [j3k0/cordova-plugin-purchase#959]
### system info

```
OSX Sierra 10.12.04
Cordova 8.1.0
Device:  Android 9
Plugin Version: 9.0.0
```

### Expected behavior
google play console show me this warning 

`
ACTION REQUIRED: Your server-side billing confirmations will stop working on December 1, 2019
Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. Note that this is not related to the AIDL/Billing Library deprecation. Learn more`

### Observed behavior
We need a plugin update using the api 3

**Comment by Dexus** [comment]
Do you use your own server validation? It the API request form there are support v3?

**Comment by zarelint** [comment]
yes i use node server with a endpoint doing the validation
