### ISSUE TITLE
Usable with Phonegap build?

### ISSUE THREAD

**Issue by janober** [j3k0/cordova-plugin-purchase#96]
Hello,

just found this plugin and was very happy that there is something that works with Android&iOS. However I am wonedering if it can be used with Phonegap build?
In the setup there is a step to put the BILLING_KEY into an xml file. How can that be done in Phonegap build?

I tried different things like adding the xml to the zip, adding config-file, preference, .. to the config.xml. Nothing worked for me (quite possible that I do it wrong).

Is it possible to set it up like the plugin "com.mcm.plugins.androidinappbilling". It adds the billing key simply as a parameter:

```
  <gap:plugin name="com.mcm.plugins.androidinappbilling" version="3.0.6">
    <param name="BILLING_KEY" value="MII...AB" />
  </gap:plugin>
```

Thanks!

**Comment by yarontt** [comment]
Hey, 
I'm not clear if this should be working and what to do to get it to?

Would adding this be enough?
```
<gap:plugin name="com.mcm.plugins.androidinappbilling" version="3.0.6">
    <param name="BILLING_KEY" value="MII...AB" />
  </gap:plugin>
```

**Comment by Fortuitous** [comment]
@janober 
Hi janober -- I see you worked on getting this plugin functional with PhoneGap Build - thanks!
I'm able to attach the billing key through the config.xml file:
    <gap:plugin name="com.smartmobilesoftware.inappbilling">
      <param name="BILLING_KEY" value="MIIB ... AB" />
    </gap:plugin>
But my android app crashes as described in #103 
Many have mentioned a fix involving installing manually from the repo (not the listed plugin)  and editing a file -- impossible from PG Build.  
Wondering if the plugin is working for you, and if you have found a way around this issue in PGB?

Thanks --

**Comment by janober** [comment]
@Fortuitous Sorry did not work on anything Android related since than so not really up to date. But do not have any problems with crashes. However back than I ended up using my fork and just stayed with it because it worked fine and did not see a reason to switch:
```
  <gap:plugin name="de.4brains.cordova.purchase" version="3.9.1-dev" source="plugins.cordova.io">
    <param name="BILLING_KEY" value="MIIB...." />
  </gap:plugin>
```
Do not remember that I did anything else special. Looked through the config.xml and through my gulpfile which copies all the stuff together and packs it for PGB. Nothing special in there (just the above). You can just give it a try and see if that works for you.

**Comment by Fortuitous** [comment]
@janober Will check it out and report back, thanks!

**Comment by Fortuitous** [comment]
@janober Hey guess what, your fork doesn't crash after Android purchase.  What a nice feature.  :)

**Comment by janober** [comment]
@Fortuitous Very glad to hear! Confirms then also my experience. Guess PGB people should then temporary use that one till somebody figured out what is going on here. Probably some features will be missing because it did never get updated but if they are not needed it should be ok for a temp workaround.

**Comment by briankj** [comment]
I'm having trouble finding the plugin you published.  Is it gone?
"Published it as a cordova plugin:
http://plugins.cordova.io/#/package/de.4brains.cordova.purchase"

**Comment by Fortuitous** [comment]
@janober  So I used your fork for my first iteration and got nice coin from Play and App store users (thanks!).  I'm working on my next version, but of course Phone Gap Build no longer likes your plugin since it no longer supports plugins.cordova.io.  

Did you port your plugin over to npm?  Or did @j3k0 merge your code making your fork redundant?  (And if so, will I need to make any changes to my code making calls to your fork, or should it all just still work?)  
Curious what path you're using these days.  Thanks.
