### ISSUE TITLE
[IOS@4.5.5] store.error neglect dialogue cancellation event

### ISSUE THREAD

**Issue by gasci** [j3k0/cordova-plugin-purchase#961]
# [IOS@4.5.5] !!!

### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

In example:
```
Cordova 9.0.0 
Device: iPhone iOS 12.3.2
cordova-ios 4.5.5
Plugin Version: 9.0.0
```

### Expected behavior
store.error handler should fire the error code and message when the user dismisses the purchase dialogue like it does on android@8.0.0

### Observed behavior
closing of dialogue is neglected by the plugin

### Steps to reproduce
1 try to buy/subscribe a product
2 dismiss the purchase dialogue (in sandbox)
3 get this closing of dialogue event

**Comment by gasci** [comment]
I used cancelled event for ios

**Comment by EvelinJK** [comment]
@gasci could you resolve this issue? 
We have the same problem with version 8.0.1. The cancelled event is not fired when the user dismissed the purchase dialog, both in iOS and Android. It is only fired when the user tries to purchase a product he already owns...

**Comment by gasci** [comment]
```
store.when("product").updated(function (p) {
p.set("state", store.APPROVED);
            });
```
has temporarily solved my problems.

**Comment by EvelinJK** [comment]
Thanks for the quick answer :).
But I don't really understand how this solves the cancelled issue and where this `.set` comes from. Could you explain a bit?

**Comment by gasci** [comment]
I realized that I had been receiving the error because the product had stayed at an inappropriate state to simply `finish()` due to a bug in the plugin, then I changed its state to "approved" to be able to `finish()` it. For more details, you can read the official doc. about the lifecycle of a product by the developer from his website: []((https://purchase.cordova.fovea.cc))
