### ISSUE TITLE
[ANDROID]  Can't find the  methods  manageSubscriptions  or  manageBilling

### ISSUE THREAD

**Issue by r-rodriguez-s** [j3k0/cordova-plugin-purchase#963]
### system info
Windows 10
Cordova 9.0.0 
Device:  Android 5.0.2
Plugin Version: 8.1.1
Using in cordova in an Angular 7 application.

### Expected behavior
According to the documentation, if I run store.manageSubscriptions() or store.manageBilling()
should open the respective pages Manage Subscription or Manage Billing

### Observed behavior
But when I run store.manageSubscriptions() nothing happend and in the inspector of chrome show
store.manageSubscriptions is not a function

and when I run store.manageBilling() nothing happend and in the inspector of chrome show
store.manageBilling is not a function

But store object is OK and exist because I can call 
store.when(....)
store.refresh()
etc,  and all my  subscriptions refresh ok.

It seem like store.manageBilling and store.manageSubscriptions is not accesible or changed name
 or removed.

I have observed that you have these functions in the javascript libraries of the plugin, so being there and my only doubt is if they are disabled for any reason.

### Steps to reproduce
Whenever the functions store.manageBilling and store.manageSubscriptions are called, the error appears and nothing else happens.

The other functions of the store object execute well.

Evidently the tests are being done on the Android device debugging with Chrome on the PC.

In fact we can buy subscriptions registered in Google Play so the connection of the plugin with the store is perfect.

Thanks in advance

**Comment by snavdeepsingh** [comment]
I can find store.manageSubscriptions but can not find store.manageBilling.

**Comment by r-rodriguez-s** [comment]
In the version of the plugin that I specified in my initial question, calling these two functions 

store.manageSubscriptions()
store.manageBilling()

throws in the inspector the error that they are not a function.

It is possible in some version they were and for some reason they have been disabled?

**Comment by j3k0** [comment]
`manageBilling()` has been added in version 9 of the plugin. See https://github.com/j3k0/cordova-plugin-purchase/releases
