### ISSUE TITLE
[ANDROID] ERROR 6777001: Init failed - Problem setting up in-app billing: IabResult: Error checking for BILLING V3 support. (response: 3:Error)

### ISSUE THREAD

**Issue by va0000ll** [j3k0/cordova-plugin-purchase#965]
# Is there any solution for this issue or will you solve it soon

 
![WhatsApp Image 2019-12-04 at 9 27 12 AM](https://user-images.githubusercontent.com/16548209/70183311-dbef4880-1678-11ea-8773-0a1a47b773fa.jpeg)

 
 
Windows 10 Pro
Cordova:  9.0.0 (cordova-lib@9.0.1).
Ionic: V5.4.6
Device: SM A10 
Plugin Version: "cc.fovea.cordova.purchase": "^8.1.1",
 
This error appear when I register my product before ORDERING and nothing happen when I call `store.order('my_product_id')` function .

To add the plugin I use : 
`ionic cordova plugin add cc.fovea.cordova.purchase --variable ......`
Not: 
`ionic cordova plugin add cordova-plugin-purchase --variable ......` (When I use this show UNAVAILABLE_BILLING)

**Comment by j3k0** [comment]
You shouldn't be using `cc.fovea.cordova.purchase`. What's the exact error when you try to install `cordova-plugin-purchase` ?

**Comment by va0000ll** [comment]
When I install `cordova-plugin-purchase` it installed successfully using:
` ionic cordova plugin add cordova-plugin-purchase --variable BILLING_KEY="My Billing Key" `
 put when I build my app and invoke `store.register('my product id')` function this message below fired :

![Screenshot_٢٠١٩١٢٠٨-١٩٠٢١٧_Almobasher](https://user-images.githubusercontent.com/16548209/70394549-7b6a4f00-1989-11ea-845a-8a325b27d61c.jpg)

```
// Track all store errors
this.store.error(err => { 
      alert(`Store Error code: ${err.code} msg: ${err.message}`);
  });
```

Notes: 
My billing key is correct ,
I build my app using `--prod --release` flags 
I have already release test version in google play console 
I use TypeScript wrapper : https://ionicframework.com/docs/native/in-app-purchase-2

please help !

Thank you,

**Comment by j3k0** [comment]
- Is your device rooted?
- Do you have issues with other apps?

**Comment by makryl** [comment]
i had same error when used emulator and was not logged in google play on the emulator. dunno is it ever possible to run app, installed from google play, on real device without google play login

**Comment by geshub** [comment]
<img width="425" alt="Screenshot 2019-12-29 at 12 53 15" src="https://user-images.githubusercontent.com/4352726/71556547-5e7de480-2a3a-11ea-9ba3-2e64f8a47934.png">
@j3k0 Not exactly the same error but looks similar. Is it linked ?
Some users reported me this error on Android ( v10.0.0 )

**Comment by incmobs** [comment]
Some of my users are also experiencing this also with 10.0.1 - 

"ERROR 6777001: Init failed - Setup failed. BILLING_UNAVAILABLE: Google Play In-app Billing API version is less than 3"

The users are all on different versions of Android (6,6.01,8,9,10)

**Comment by jonworek** [comment]
Like @makryl suggested above, I was able to resolve this error by logging into the Google Play store  on the emulator on which I was testing.

**Comment by geshub** [comment]
I can also confirm I tried to remove my google account on my test device to be able to logout from the play store and I got the error message. So it's not a bug.
@j3k0 Would it be possible to have this error just logged into the console without getting an alert in that case ?

**Comment by koraysels** [comment]
Why won't this be fixed? I have multiple users who get this error. My logging service is full of it. 

```
Error: @InAppPurchase : <ERROR>
{"code":6777001,"message":"Init failed - Setup failed. BILLING_UNAVAILABLE: Google Play In-app Billing API version is less than 3"}
```

**Comment by cediim8** [comment]
> i had same error when used emulator and was not logged in google play on the emulator. dunno is it ever possible to run app, installed from google play, on real device without google play login

Similar issue here, turned out that I had removed all Google accounts on my emulator when testing another application. Logging back in to a Google account fixed this issue.

**Comment by michaelbutler1998** [comment]
I am receiving this error after logging in both on a physical test device and my emulator to the Google Play store. 

Can anyone advise?
