### ISSUE TITLE
[ANDROID] Missing non-consumable purchases in response from queryPurchases()?

### ISSUE THREAD

**Issue by Gerarddus** [j3k0/cordova-plugin-purchase#967]
### system info

```
OSX Catalina 10.15.1
Cordova 9.0.0
Device: Android 8.1
Plugin Version: 8.1.1
```

### Expected behavior

My app only has non-consumable inapp purchases. I would expect

```store.when('product').updated```

to return the non-consumable products which are owned with product.owned = true

### Observed behavior

In my debug app, the inapppurchases all are returned as not being owned, even though some of them definately are.
I am trying to update the plugin from plugin 8.1.1, which is showing the owned items correctly.

### Possible solution

I looked at PurchasePlugin.java
Could it be that this line should be added at 292

```purchases.addAll(purchasesResult.getPurchasesList());```

It seems to solve my problem.

**Comment by j3k0** [comment]
Fixed with d41d055 -- published in plugin version v10.0.1
