### ISSUE TITLE
[ANDROID] The requested item is not available for purchase

### ISSUE THREAD

**Issue by ednilsonamaral** [j3k0/cordova-plugin-purchase#968]
### system info
```
OSX Catalina 10.15.1
Ionic 3.9.2 // Cordova Android 8.1.0
Device: Android 8+
cc.fovea.cordova.purchase Version: 8.1.1
@ionic-native/in-app-purchase-2 Version: 4.20.0
```

### Expected behavior

I have In App Purchase 2 in one app here, and I set up the products on Google Play correctly and everything, however, in every APK test I generate, it returns to me that **The requested item is not available for purchase**.

I have tried creating new products, reinstalling the plugins, and the error persists. 

[- Printscreen](https://imgur.com/LLJYC69)

### Observed behavior

I'm generating debug APK.

**Comment by Gerarddus** [comment]
Did you upload an APK to the playstore? If I remember correctly, you can only have available purchases if you've set up the playstore with an APK

**Comment by ednilsonamaral** [comment]
Resolved! Just by sending the signed APK to the Play Store that worked. In debug APK does not work, only in same production APK.

Thanks! 😄
