### ISSUE TITLE
Amazon App Store

### ISSUE THREAD

**Issue by yankustefan** [j3k0/cordova-plugin-purchase#97]
Hi Jean-Christophe

Thank you for your efforts to build and maintain this plugin!

Is this plugin compatible with Amazon's app store?
Since they are running Android apps, it might be feasible.

**Comment by manzapanza** [comment]
+1 !
Hi Jean-Christophe, you could set up another Indie Gogo campaign to support also the amazon store. And then we will try to post everywhere to reach the value. 
What do you think about this?
Thank you!

**Comment by aesculus** [comment]
Bump

**Comment by LukePulverenti** [comment]
What is the point of bumping when the developer already gave an answer? Why not take a crack at it yourself and let us know how it goes?
