### ISSUE TITLE
Android: is BILLING_KEY variable still required?

### ISSUE THREAD

**Issue by shortercode** [j3k0/cordova-plugin-purchase#974]
In https://github.com/j3k0/cordova-plugin-purchase/commit/70f550a80210593a3a4217b8ecae22c2495897c8 the plugin.xml was updated to remove the BILLING_KEY preference, and the README documentation was updated so that it isn't mentioned in the install steps. However, the [Setup Android applications](https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play#setup-android-applications) wiki page till lists it in the instructions. 

Does this mean that the plugin no longer requires the variable after the rewrite and that the Wiki page is out of date?

**Comment by erikyuzwa** [comment]
same question - will add that when I did the `BILLING_KEY` step, I got an error in Android Studio - `Program type already present: com.android.vending.billing.IInAppBillingService`

**Comment by distante** [comment]
I would say yes as per what this page says: https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play

**Comment by Gerarddus** [comment]
I started this conversation [issue](https://github.com/j3k0/cordova-plugin-purchase/issues/972) earlier. Would like to see it back also.

**Comment by Gerarddus** [comment]
Did anyone try to fix this and succeed? Would love to see a pullrequest. I've tried, but failed.

**Comment by shortercode** [comment]
@Gerarddus thanks for posting that. I wasn't aware that it was only used for signature validation. Prior to the billing API update I was maintaining a fork of the plugin which set the the billing key dynamically from JS. With that change I basically depreciated the fork and went back to using the upstream version to reduce our maintenance time.

I'm not fully aware of the tradeoffs of not having client side validation, but I'm guessing this is a push to encourage users to add server side validation if they aren't already. Which I totally support, provided that it's easy enough for non-technical users to set up ( which was a requirement of the integration of this plugin which I worked on ).
