### ISSUE TITLE
[ANDROID] ERROR 6777002: Loading product info failed - Error. SERVICE_UNAVAILABLE: An internal error occurred.

### ISSUE THREAD

**Issue by teaeatate** [j3k0/cordova-plugin-purchase#976]
### system info

macOS Mojave 10.14.6
Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-android 8.1.0
cordova-plugin-purchase 10.0.1

Hello,

The following error appears across multiple users.

**"ERROR 6777002: Loading product info failed - Error. SERVICE_UNAVAILABLE: An internal error occurred."**

The users are all on different versions of Android (4.4.2, 4.4.4, 5.1.1, 6.0, 6.0.1)

Could you please advise?

this is my purchase code extract:

```
import Unlock from './Unlock';
import File from './File';
import Analytics from './Analytics';

export default {
  init() {
    const store = window.store;

    if (!store) {
      Analytics.trackEvent('settings', 'PURCHASE', 'Store not available');
      return;
    }

    store.register({
      id: 'com.fooooo.fullversion',
      alias: 'Full Version',
      type: store.NON_CONSUMABLE,
    });

    store.error((error) => {
      Analytics.trackEvent('settings', 'PURCHASE', `ERROR ${error.code}: ${error.message}`);
    });

    store.ready(() => {
      Unlock.init(store);
    });

    store.when('Full Version').approved((order) => {
      File.getFullVersion();
      order.finish();
    });

    store.refresh();
  },
};
```

**Comment by j3k0** [comment]
This is an error raised by the SDK, the plugin only reports it. Maybe the user doesn't have the google play libs installed, maybe it's running in kid mode with google play disabled, maybe it's running in a place where google play is blocked by a firewall.

**Comment by teaeatate** [comment]
Thank you for teaching me so kindly.
