### ISSUE TITLE
Android: Invalid product type for rewarded products

### ISSUE THREAD

**Issue by distante** [j3k0/cordova-plugin-purchase#980]
### system info
```
Windows 10
Cordova 8 (Ionic 4)
Device: Android 7.1.1
Plugin Version: 8.1.1
@ionic-native/in-app-purchase-2: 5.19.1
```

### Expected behavior
Type of Reward Product should exist
### Observed behavior
No Reward Product type exist in `store.`
### Steps to reproduce
Try to register a rewarded product test like `android.test.reward`

Also in the docs there is not info about how to proceed with reward products.

**Comment by Dexus** [comment]
Please update your plugin version (5.19.1) is not a valide version for your other versions.

**Comment by distante** [comment]
Hi @Dexus sorry, I pasted the version of the Ionic wrapper instead of the plugin version. It is 8.1.1. I just updated my open post.

**Comment by j3k0** [comment]
Reward products are not supported by the plugin.
