### ISSUE TITLE
[IOS] How to get available product information without prompting for iTunes login

### ISSUE THREAD

**Issue by msbit** [j3k0/cordova-plugin-purchase#983]
I'm using Ionic's InAppPurchase2 plugin which is based on this Cordova plugin. From their [documentation](https://ionicframework.com/docs/native/in-app-purchase-2):

> When you perform the initial call to store.refresh(), the platforms' server will be contacted to load informations about the registered products: human readable title and description, price, etc.
>
> This isn't an optional step, store owners require you to display information about a product exactly as retrieved from their server: no hard-coding of price and title allowed! This is also convenient for you as you can change the price of your items knowing that it'll be reflected instantly on your clients' devices.

This seems to be borne out in practice, and is confirmed by the following [comment](https://github.com/j3k0/cordova-plugin-purchase/blob/v8.1.1/src/js/refresh.js#L9-L11):

> /// This will initiate all the complex behind-the-scene work, to load product
> /// data from the servers and restore whatever already have been
> /// purchased by the user.

I am attempting to populate the product details to show the user before they subscribe via purchase, however (possibly) as I already have historical purchases for the same product with the testing user, I am prompted to 'Sign in to iTunes Store' whenever I call `store.refresh()`.

Is there a way to simply fetch all the product information without being prompted to sign in?

**Comment by Treblue** [comment]
I am having this same problem as well. Looking forward to a solution 👍

**Comment by j3k0** [comment]
Not a problem, it's just happens as you're being switched back to the `sandbox` AppStore. If everything is correctly setup in your app, it shouldn't ask for a password (in prod or TestFlight).

**Comment by msbit** [comment]
@j3k0 

> If everything is correctly setup in your app, it shouldn't ask for a password (in prod or TestFlight).

Thanks for that, is there any place specific that this is documented? I'm going through the IAP provisioning for the first time, and there seems to be _quite_ a bit of ambiguous and poorly documented information from the Apple side of things.

In any case, for my purposes I've worked out that I can use the following to just get the product information:

    window['storekit'].load(['product-id'], (validProducts, invalidProductIds) => {
      console.log(validProducts[0]);
    }, () => {
      console.error('some error');
    });

**Comment by DimitrisMpanis** [comment]
> Not a problem, it's just happens as you're being switched back to the `sandbox` AppStore. If everything is correctly setup in your app, it shouldn't ask for a password (in prod or TestFlight).

@j3k0 
It keeps asking for password but I am not sure why. Everything seems to be working as it should. We deployed the app to production and users are being asked for a password right after the app starts.

**Comment by Dexus** [comment]
Reset your Developer Device may be help.

**Comment by francois-n-dream** [comment]
We have the same problem in production. We asked several random people, who never had our app installed before and they also get the login prompt.

I debugged the app by simply doing every command step by step and as soon as I call store.refresh() the prompt appears.

I wonder what "correctly setup" means. Any idea what could be setup incorrectly?

Thank you!

**Comment by makaroll** [comment]
In case others had similar configuration as I did, I was able to fix this issue by registering products and binding listeners on app start rather than when the store view is created (ie when user clicks on 'shop' or 'store' button). Was able to find the answer to correctly setting up the plugin while reading issue https://github.com/j3k0/cordova-plugin-purchase/issues/813#issuecomment-475616551

**Comment by Seanmclem** [comment]
@makaroll, can you reiterate here what specifically was your problem and what you fixed?

**Comment by j3k0** [comment]
Users should not be asked for their password, except if the app wasn't installed through the appstore (in which case there's no receipt on the device, so the plugin will have to do a refreshReceipt that asks for the password).. This is specific to development and testing. Password prompt will also happen if you call `refresh()` twice (or more), make sure your code doesn't do it. In normal circumstances it shouldn't ask for password.

**Comment by Seanmclem** [comment]
@j3k0 Thanks for the info but, the Readme says to run store.refresh() for a "Restore" purchases button which is required by Apple. Can we use store.update() instead? To avoid possibly calling refresh() multiple times.

**Comment by j3k0** [comment]
@Seanmclem the "Restore Purchases" button SHOULD call `store.refresh()`. This is the one case where it's fine to ask the user for the password.

However don't call `store.refresh()` multiple times automatically (without the user hitting the restore purchase button).

**Comment by Seanmclem** [comment]
> @Seanmclem the "Restore Purchases" button SHOULD call `store.refresh()`. This is the one case where it's fine to ask the user for the password.
> 
> However don't call `store.refresh()` multiple times automatically (without the user hitting the restore purchase button).

I see. So store.update won't work for a refresh purchases button?

**Comment by alisterg** [comment]
@j3k0 I have a similar issue, when I call `store.order(id)` it opens the password prompt as well as the FaceID prompt. Are FaceID devices supported?

I am only calling `store.refresh()` a) on app load; b) when user clicks Restore Purchase
