### ISSUE TITLE
how can i install 8.1.0 version of this plugin?

### ISSUE THREAD

**Issue by matrixreal** [j3k0/cordova-plugin-purchase#984]
hi,
how can i install 8.1.0 version of this plugin?
new version gives me somes errors
thanks

**Comment by j3k0** [comment]
Depends if you're using cordova, phonegap or ionic. In general, `spec="~8.1.0"` in the plugin entry in config.xml

This question isn't specific to this plugin, it's a cordova, phonegap or ionic question (how to install specific version of a plugin). so i'm closing
