### ISSUE TITLE
wiki is open for editing

### ISSUE THREAD

**Issue by jonworek** [j3k0/cordova-plugin-purchase#986]
I was able to modify the wiki page at https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play.

I was surprised that I was able to make an update to that page, not having write access to the repository. I was able to make a small change to correct the plugin name that is referenced in the `cordova plugin add` command.

You might want to see about locking that down.

But hopefully the change that I did make is welcome. 😄

**Comment by j3k0** [comment]
Thanks!

Wiki is open on purpose, so it's easy to contribute and it's easy to revert malicious changes (I assume good people will quickly notice and fix). It never happened though 🤞 

https://github.com/j3k0/cordova-plugin-purchase/wiki/_history
