### ISSUE TITLE
[Android] app crashes on .refresh()

### ISSUE THREAD

**Issue by wcjord** [j3k0/cordova-plugin-purchase#989]
### system info
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 22 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/willjc/Library/Android/android-sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 8.0.2
   NodeJS            : v10.18.0 (/usr/local/Cellar/node@10/10.18.0/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

Device:
   Name:      Huawei P20 Pro,  
   Model:     CLT-L29
   OS:           Android v9

### Expected behavior
Hoping to call .refresh() without the app crashing.

### Observed behavior
After successfully making a purchase with a device, the app crashes on subsequent calls to .refresh().

### Steps to reproduce
1. Create a new Ionic v4 app and upload to Google Play with at least one in-app purchase setup.
2. Complete a purchase.
3. Close the app and reopen. Navigate to point at which .refresh() is called.

**Comment by j3k0** [comment]
- What version of the plugin were you using?
- Did you figure out the issue?
