### ISSUE TITLE
[Android] Question : Testing strategies.

### ISSUE THREAD

**Issue by distante** [j3k0/cordova-plugin-purchase#990]
I am starting to implement cordova-plugin-purchase in my Android app. I try to always use TDD with it.

For my integration tests I just use ts-mockito to mock the call to native plugins and updates thru observables or promises.

Since this plugin is mostly callback based it would be good if some kind of mocked class with the expected behavior is exposed. Currently I have a mocked class where I test the `order()` function but test events from `when().event()` is not quite easy and I suppose another developers had the same problem. 

I tried to find any information relevant to this but I have not found any (probably I have not search it  correctly. Is there a recommended testing strategy for this plugin?

**Comment by j3k0** [comment]
Is your question still relevant? For others: you can explain how you did proceed for testing.

**Comment by j3k0** [comment]
(closing until, feel free to reopen if you want to continue the discussion)
