### ISSUE TITLE
InAppPurchase2.manageSubscriptions not working, according to Ionic plugin is not installed.

### ISSUE THREAD

**Issue by adamk22** [j3k0/cordova-plugin-purchase#992]
I'm running into an issue where the manageSubscriptions() doesn't seem to work. On invoking the function, I get an error in the console:

```
> Native: tried calling InAppPurchase2.manageSubscriptions, but the InAppPurchase2 plugin is not installed
> Install the InAppPurchase2 plugin: 'ionic cordova plugin add cc.fovea.cordova.purchase'
```

The plugin is installed:

```
> cordova plugin ls
cc.fovea.cordova.purchase 8.1.1 "Purchase"
```

Package.json:
```
"cordova-plugin-purchase": "^10.0.1",
"cc.fovea.cordova.purchase": "^8.1.1",
"@ionic-native/in-app-purchase-2": "^5.20.0",
```

I'm not sure what I'm doing wrong or whether the wrong packages are installed. The other functions like order() seems to be working normally. I ran into a similar issue (#934) but his solution didn't seem to work for me.

Any ideas how this can be resolved?

**Comment by distante** [comment]
How are you testing it? using `ionic run cordova --livereload` ? 

Are you waiting until `platform.ready()` before trying to use the plugin?

**Comment by adamk22** [comment]
Testing it on a device with a production build and it waits for the platform to be ready before it sets everything up. The plugin seems to be initialised correctly since I can order test subscriptions (working on auto renewable iap) that I set up in the playstore console.

**Comment by distante** [comment]
Can you show me your code? Otherwise I am trying to help blindingly.

**Comment by loicfavory** [comment]
I have the same problem on Android.
The plugin retrieve my products, subscriptions are working well, but manageSubscriptions tells me that the plugin is not installed.
Testing on a device.

    "cc.fovea.cordova.purchase": "^8.1.1",

**Comment by loicfavory** [comment]
OK, got it workging.
`
$ ionic cordova platform rm android
$ ionic cordova plugin rm cc.fovea.cordova.purchase
$ ionic cordova plugin rm cordova-plugin-purchase
$ ionic cordova platform add android
$ ionic cordova platform add cordova-plugin-purchase
`

**Comment by oofaish** [comment]
Hey @loicfavory - I think you are having - which version of the plugin are you ending up with after this - 8 or 10? tnx!

**Comment by adamk22** [comment]
Thank you @loicfavory! I managed to make it work using your steps. (small adjustment, it's `$ ionic cordova plugin add cordova-plugin-purchase` and not `platform add`). I suppose the documentation on the Ionic framework ([link](https://ionicframework.com/docs/native/in-app-purchase-2)) is outdated?

@oofaish the plugin version I ended up with is `cordova-plugin-purchase 10.0.1`

**Comment by j3k0** [comment]
For future reference, note that `cc.fovea.cordova.purchase` is the old id of the plugin. You should ONLY install `cordova-plugin-purchase` -- installing 2 different versions will result in issues like this.
