### ISSUE TITLE
[IOS] Phonegap Build error with plugin version 10

### ISSUE THREAD

**Issue by JamesB1976** [j3k0/cordova-plugin-purchase#994]
### system info

```
macOS Catalina 10.15.3
Cordova 9.0.0
Cordova iOS 5.0.1
Plugin Version: 10.0.0 and 10.0.1
Phonegap Build (https://build.phonegap.com)
```

### issue

I'm using Phonegap Build to create the iOS IPA file for my app, but the latest versions of the plugin (10.0.1 and 10.0.0) are causing an error when I try to build.

To test I created an empty project with just this plugin and I get this error message:

```
Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-purchase 
```

Obviously I can't upgrade to a new version, although if I downgrade to an older version of the plugin (eg 9.0.0), the file does build successfully. However some of my code (eg store.update) doesn't work with the older plugin, and I'd really like to be working with the latest version.

Looking into the error log files, I can see some more output that might help to get to the bottom of the problem:

```
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/Empty_Project-atyznjenicgorrggkpbllrhwlklx/Build/Intermediates.noindex/ArchiveIntermediates/Empty\ Project/IntermediateBuildFilesPath/Empty\ Project.build/Release-iphoneos/Empty\ Project.build/Objects-normal/armv7/InAppPurchase.o Empty\ Project/Plugins/cordova-plugin-purchase/InAppPurchase.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

Hoping somebody might be able to help!

**Comment by j3k0** [comment]
Is this solved?

I think PGB upgraded their cordova version recently, which might help...?

**Comment by JamesB1976** [comment]
Hi, thanks for getting back to me about this.

Although PGB did update to Cordova 9.0.0 last year, their cordova-ios version is only 5.0.1, which means it's only using the iOS 12 SDK, not iOS 13.

So I'm guessing if the plugin uses any iOS 13-specific code, that could be causing the build to fail.

Does that sound like a possible explanation?

**Comment by razam217** [comment]
@JamesB1976 is there any solution you can suggest. I'm facing similar issue.

**Comment by j3k0** [comment]
@razam217 PhoneGap Build has been discontinued. They said they will be taking the service down in October 2020, apparently it's been silently delayed, but you're still advised to switch to Apache Cordova now. PhoneGap Build can disappear any day now.

**Comment by razam217** [comment]
Thanks @j3k0 . But I'm seeing similar issue with Cordova 10.0.0 when I run cordova build ios after adding this plugin.

**Comment by j3k0** [comment]
Can you paste the error message here?

**Comment by razam217** [comment]
![image](https://user-images.githubusercontent.com/9858462/105817350-4f6bbc00-5fd7-11eb-9d54-d6de4def2e51.png)
![image](https://user-images.githubusercontent.com/9858462/105817437-690d0380-5fd7-11eb-912c-55f995de0cfc.png)

**Comment by j3k0** [comment]
Oh right, that's because you're using an older version of XCode. Either update XCode or revert to an older version of the plugin (see "Releases" here on github to check which version introduce this XCode requirement).

**Comment by razam217** [comment]
Perfect. Thanks... Really appreciate your quick response... :)
