### ISSUE TITLE
[iOS] ready callback never fires

### ISSUE THREAD

**Issue by AshleyScirra** [j3k0/cordova-plugin-purchase#995]
### system info

macOS 10.15.3
Cordova 9.0.0
Device: iOS 13.3.1
Plugin Version: 10.0.1

### Expected behavior

store.ready(cb) should always call the callback at some point

### Observed behavior

store.ready(cb) does not always fire the callback, even after a successful initialisation

### Steps to reproduce
We make Construct 3, a game creation tool that uses cordova-plugin-purchase in a Cordova app. A user originally reported this problem to us here: https://github.com/Scirra/Construct-3-bugs/issues/3608
However according to our investigation this is a problem with cordova-plugin-purchase.

In the circumstances described by the user, there is an existing successful consumable purchase when the app starts up. According to my own investigation, the following calls happen:

- cordova-plugin-purchase calls `storekitLoaded`
- this then calls `store.update` with callbacks that will call `store.ready(true)`, intended to call the ready callback when it finishes
- `store.update` calls `storekit.loadReceipts()`
- the callback passed to `loadReceipts()` runs. This adds "verified" and "unverified" events for a product (presumably the existing consumable), which in turn will end up calling the callbacks and setting ready state. Then it calls `p.verify()`.
- in `verify()`, it calls `tryValidation()` after a delay.
- in `tryValidation()`, it reaches the line `if (that.state !== store.APPROVED)`. In this case the state is "owned". This then proceeds to exit with a `return` statement. It appears this means it never proceeds to fire any event, so no callbacks happen, so the ready state is never set.

Presumably this code path should either fire a verified or unverified event.

**Comment by j3k0** [comment]
The issue is that the product `state` should be `approved` when running the validation. Normally, nothing should change that state after the call to `verify()` (until it either succeed or fails).

That's what you should figure out, what does change this state?

**Comment by AshleyScirra** [comment]
Is that actually relevant? The ready callback should fire in all circumstances regardless of the details of the purchase state. In this case the state is "owned" and that does not result in the ready callback running.

**Comment by j3k0** [comment]
That is relevant because it means there is some code responsible for an internally inconsistent state. The plugin shouldn't be expected to work properly if it's in an inconsistent state. Do you know how the product went from "approved" to "owned"?

Maybe the plugin itself is responsible for this issue (regression?) or maybe it's your app/code. We need to dig more as for why this happens.

**Comment by AshleyScirra** [comment]
I think this is still an issue and judging by https://github.com/ionic-team/capacitor/issues/2803 others are running in to it too. I'm not sure what to do about it, I already dug in to the code and outlined what's happening, but none of it's my code. Besides, even if the app makes some set of 
invalid calls, shouldn't the plugin return an error instead of ending up in some kind of corrupt state?

**Comment by Dexus** [comment]
Hi @AshleyScirra I would like to see, how your integration looks like. Would it be possible to share some code or access to v3, so that it is possible to debug and looking deeper into it.

**Comment by AshleyScirra** [comment]
Here's a sample Xcode project: [MobileIAP test app.ios.project.zip](https://github.com/j3k0/cordova-plugin-purchase/files/4832290/MobileIAP.test.app.ios.project.zip)

I tested this with the latest 10.1.2, and it still reproduces. The sample project provides a way to purchase a test item with ID `RAA`. Every call to cordova-plugin-purchase and every event it fires is logged to the console.

To reproduce:
1. Run the Xcode project on a test device with a test account + IAP configured for `RAA`
2. Observe both "store ready", meaning the ready callback fired, in the Xcode log.
3. Tap the text in the bottom right to purchase the item
4. Complete the purchase with a test account
5. Close the app
6. Restart the app
7. Look in the Xcode log. Despite various calls and events firing, "store ready" is not logged, indicating the ready callback was not fired.

The consequence of this is if the app waits for the ready callback before proceeding, it hangs.

I hope this helps track down the issue, let me know if you need any more details.

**Comment by AshleyScirra** [comment]
It looks like we're getting multiple reports of this from our users who use our framework. Is there anything I could do or contribute to speed up investigation of this issue?

**Comment by AshleyScirra** [comment]
Also, do we actually need to wait for the ready callback to fire? It looks like none of the samples use it.

**Comment by Dexus** [comment]
> Also, do we actually need to wait for the ready callback to fire? It looks like none of the samples use it.

Yes you should. 

To your example code, if I did see it right, you never correct register the `When` events...

Also you don't need to register Alias and ID for the product if it is the same value...

To deeper debugging, I need source code and some more docs how this all works.

Because I can't see any product is registred or how i should start.

**Comment by AshleyScirra** [comment]
I've sent an email to hoelt@fovea.cc regarding commercial support for this issue, I think we need this fixed with priority. Thanks for any help.

**Comment by AshleyScirra** [comment]
This issue apparently still reproduces and was closed without being fixed, and someone emailed me for help about it. So for anyone else who hits this footgun: when approving a product, you must go through this process:

1. In the "approved" callback, call `verify()`
2. In the "verified" callback, call `finish()` (even if no verification is done)
3. In the "finished" callback, the purchase has finished successfully

The bug happens if you skip step 2. If you don't do any verification, it's tempting to think you can use this process instead:

1. In the "approved" callback, call `finish()`
2. In the "finished" callback, the purchase has finished successfully

However this silently fails and appears to leave cordova-plugin-purchase in an indeterminate state. To be fair, the documentation does cover the working process, but if you don't do any real verification work it can look like you can skip that step, but you cannot. I still think this is a bug as it should either work the same as a no-op verify, or fail with an exception if you try to call `finish()` too soon, rather than silently failing in a difficult-to-figure-out way, but just my $0.02 🤷‍♂️
