### ISSUE TITLE
[IOS] Being sent app bundle identifier as a product ID purchase to validate

### ISSUE THREAD

**Issue by alexcroox** [j3k0/cordova-plugin-purchase#999]
### system info

```
OSX Sierra 10.15.3
Capacitor 1.5.0
Device: iPhone iOS 13.3.1
Plugin Version: 10.0.1
```

### Expected behavior
To only receive in-app purchases to the validation method.

### Observed behavior
Whenever I load my application, I receive an immediate validation call, and the product.id = 'com.example.myapp'. Which indicates the plugin is mistaking the original app store purchase as an in-app purchase? (also this isn't from the app store it's being loaded via xcode, but it uses the same bundle ID as it's live version which is on the app store).

What should I be doing with this during validation? I'm sending `callback(true)` in the hopes it gets marked as owned and doesn't keep coming back but it's still appearing every app load.

```
[Log] InAppPurchase[js]: loading appStoreReceipt (user-script:2, line 78)
[Log] InAppPurchase[js]: infoPlist: farm.hectare.sml,2.2.2,0,null (user-script:2, line 78)
[Log] Native IAP: Validating – {id: "farm.hectare.sml", alias: "application", type: "application", …} (user-script:2, line 78)
{id: "farm.hectare.sml", alias: "application", type: "application", group: "", state: "approved", …}ObjectadditionalData: nullalias: "application"canPurchase: falsecountryCode: nullcurrency: nulldescription: nulldiscounts: []Array (0)downloaded: falsedownloading: falsegroup: ""id: "farm.hectare.sml"ineligibleForIntroPrice: nullintroPrice: nullintroPriceMicros: nullintroPriceNumberOfPeriods: nullintroPricePaymentMode: nullintroPricePeriod: nullintroPricePeriodUnit: nullintroPriceSubscriptionPeriod: nullloaded: trueowned: falseprice: nullpriceMicros: nullstate: "approved"title: "Application Bundle"transaction: {type: "ios-appstore", appStoreReceipt: "MIIVdgYJKoZIhvcNAQcCoIIVZzCCFWMCAQExCzAJBgUrDgMCGg…qGZZhQ5JDn2aE+dgcNHewHKvBFLDsGgUq/gejNPTsfcUnsEc=", signature: undefined}Objecttype: "application"valid: trueversion: "2.2.2"Object Prototype
[Log] Native IAP: Ignoring app download receipt – {id: "farm.hectare.sml", alias: "application", type: "application", …} 
{id: "farm.hectare.sml", alias: "application", type: "application", group: "", state: "approved", …}Object
[Log] [store.js] DEBUG: verify -> {"success":true,"data":{}}
[Log] [store.js] DEBUG: verify -> success: {} 
[Log] [store.js] DEBUG: syncWithAppStoreReceipt 
[Log] [store.js] DEBUG: {"type":"ios-appstore","appStoreReceipt":"MII...."}
```

`farm.hectare.sml` is the name of my app bundle ID, not the 3 product in-app subscriptions I have setup

**Comment by Dexus** [comment]
Hello,
this validation can be ignored if your app is free. Else you should be
validate it.

Regards, Josef

Am Fr., 28. Feb. 2020 um 10:25 Uhr schrieb Alex <notifications@github.com>:

**Comment by alexcroox** [comment]
If the app was paid for, shouldn't Apple be handling this at the app store level before the app is even installed? Just wondering if these should be filtered out by the plugin to avoid confusion.

**Comment by Dexus** [comment]
please have a look to #982

**Comment by alexcroox** [comment]
ah, appreciate the context! For anyone else landing here, this is the specific comment about why and how to avoid: https://github.com/j3k0/cordova-plugin-purchase/issues/982#issuecomment-579460873
